### ISSUE TITLE
Limit l2arc header size

### ISSUE THREAD

**Issue by douardda** [zfsonlinux/zfs#1420] opened 2013-04-22 14:08 UTC
Hi,

i have serious performance problems with my ZFS system. For the record it's a Debian squeeze+backports (3.2.41-2~bpo60+1 debian kernel) running on a Dell PE2950 (2 Xeon L5420@2.5GHz, 16Go), driving a storage bay consisting of 18 spinning drives (SAS, 7200) and 4 SSDs (2 MLC, 2 SLC for logs and cache).
The HBA is a LSI  SAS9200-8E 

My problem is that after a fresh reboot, the system behaves quite normally, but as write operations occurs on ZFS volumes, performances degrades down to a state which makes it almost unusable (any zfs command take more than a minute to return, IO perf on zfs and zvols are near 0, zfs kernel threads spend most of their time waiting for mutexes, etc.)  

There a detailed explanation on the mailinglist:

https://groups.google.com/a/zfsonlinux.org/forum/#!topic/zfs-discuss/6-2sqov3usM

**Comment by mailinglists35** [comment] 2016-04-24 15:33
I'm getting similar strace and cpu behaviour as described in https://github.com/zfsonlinux/zfs/issues/1420#issuecomment-24904934 (creating new dataset with `zfs create`, recursively reading a property with `zfs get`, mounting/unmounting dataset etc).

Hopefully the root cause is the same and I'm no hijacking this thread.

1Tb mirrored pool with 50% frag and 94% capacity, ~1k datasets each with tens of snapshots, core2duo, 4gb ram, l2arc 1gb on ssd, spl/zfs default parameters
`zpool status` returns instantly

/proc/spl/kstat/zfs/dmu_tx
5 1 0x01 11 528 3702255793 278790911145179
name                            type data
dmu_tx_assigned                 4    450357
dmu_tx_delay                    4    0
dmu_tx_error                    4    0
dmu_tx_suspended                4    0
dmu_tx_group                    4    0
dmu_tx_memory_reserve           4    0
dmu_tx_memory_reclaim           4    0
dmu_tx_dirty_throttle           4    0
dmu_tx_dirty_delay              4    44337
dmu_tx_dirty_over_max           4    0
dmu_tx_quota                    4    0

/proc/spl/kstat/zfs/arcstats
6 1 0x01 91 4368 3705134230 278831289575797
name                            type data
hits                            4    48898849
misses                          4    30851015
demand_data_hits                4    657957
demand_data_misses              4    18896
demand_metadata_hits            4    33375201
demand_metadata_misses          4    30540128
prefetch_data_hits              4    51241
prefetch_data_misses            4    80574
prefetch_metadata_hits          4    14814450
prefetch_metadata_misses        4    211417
mru_hits                        4    2740145
mru_ghost_hits                  4    114561
mfu_hits                        4    32098954
mfu_ghost_hits                  4    278355
deleted                         4    1180533
mutex_miss                      4    6058
evict_skip                      4    101397607
evict_not_enough                4    1584496
evict_l2_cached                 4    19655065600
evict_l2_eligible               4    7276375552
evict_l2_ineligible             4    5524025344
evict_l2_skip                   4    6688
hash_elements                   4    222772
hash_elements_max               4    458993
hash_collisions                 4    949624
hash_chains                     4    35395
hash_chain_max                  4    8
p                               4    1521930796
c                               4    1666021832
c_min                           4    33554432
c_max                           4    2031970304
size                            4    1531454200
hdr_size                        4    42136968
data_size                       4    0
metadata_size                   4    1220733952
other_size                      4    256402488
anon_size                       4    2508800
anon_evictable_data             4    0
anon_evictable_metadata         4    0
mru_size                        4    156073984
mru_evictable_data              4    0
mru_evictable_metadata          4    303104
mru_ghost_size                  4    4698112
mru_ghost_evictable_data        4    0
mru_ghost_evictable_metadata    4    4698112
mfu_size                        4    1062151168
mfu_evictable_data              4    0
mfu_evictable_metadata          4    995460096
mfu_ghost_size                  4    459069440
mfu_ghost_evictable_data        4    0
mfu_ghost_evictable_metadata    4    459069440
l2_hits                         4    543010
l2_misses                       4    30307963
l2_feeds                        4    279023
l2_rw_clash                     4    3
l2_read_bytes                   4    1981267456
l2_write_bytes                  4    3857339904
l2_writes_sent                  4    6080
l2_writes_done                  4    6080
l2_writes_error                 4    0
l2_writes_lock_retry            4    2
l2_evict_lock_retry             4    0
l2_evict_reading                4    0
l2_evict_l1cached               4    20744
l2_free_on_write                4    1775
l2_cdata_free_on_write          4    29
l2_abort_lowmem                 4    0
l2_cksum_bad                    4    0
l2_io_error                     4    0
l2_size                         4    5762187264
l2_asize                        4    1809572864
l2_hdr_size                     4    12180792
l2_compress_successes           4    378819
l2_compress_zeros               4    0
l2_compress_failures            4    31248
memory_throttle_count           4    0
duplicate_buffers               4    0
duplicate_buffers_size          4    0
duplicate_reads                 4    0
memory_direct_count             4    327
memory_indirect_count           4    52049
arc_no_grow                     4    0
arc_tempreserve                 4    0
arc_loaned_bytes                4    0
arc_prune                       4    3702130
arc_meta_used                   4    1531454200
arc_meta_limit                  4    1523977728
arc_meta_max                    4    1574230968
arc_meta_min                    4    16777216
arc_need_free                   4    0
arc_sys_free                    4    63496192

**Comment by behlendorf** [comment] 2016-10-05 02:06
Closing this code has been refactored considerably to reduce the header sizes, in addition the compressed ARC feature was added to further reduce overhead.

**Closed by behlendorf** 2016-10-05 02:06 UTC
Labels: Documentation, Performance
