### ISSUE TITLE
feature request: persistent l2arc

### ISSUE THREAD

**Issue by kez-kuehl** [zfsonlinux/zfs#8825] opened 2019-05-27 14:33 UTC
Hello,

I know persistent l2arc has been dropped from the agenda, but I think it's important for desktop adoption. It would reduce the dependecies.

Config Today:
SSD Cache: LVM / bcache
Crypt: LUKS
[...]

To:
ZFS

**Comment by lundman** [comment] 2019-05-28 02:07
I was working with someone on IRC about that (unfortunately appears to be MIA though?) where we found the latest commit (probably) and re-merged it into a fresh tree:

https://github.com/openzfsonosx/zfs/tree/persist_l2arc

Alas, there are some questions regarding how it should interact with ADB calls;

https://github.com/openzfsonosx/zfs/commit/3ccc6124ee67dda37194933c07fecc062b5760af#diff-163982413ed6b6861e08633c89a77395R9948

But if that can be figured out, it could be tested and all that.

**Comment by gertvdijk** [comment] 2019-06-06 21:08
See https://github.com/zfsonlinux/zfs/issues/3744

**Comment by Ornias1993** [comment] 2019-11-11 08:34
@gertvdijk #3744 is a dead horse.
Person behind that PR has been MIA for a long time.

#2672 seems to have more active development currently

**Comment by Ornias1993** [comment] 2019-11-11 08:37
Also:
This is basically a duplicate of #3744

**Comment by Ornias1993** [comment] 2019-11-12 17:42
@behlendorf 
I think you want to get rid of this one in favor of #3744

#3744 has a good description and links to all other discussions. This Issue is just bloat.

**Comment by behlendorf** [comment] 2019-11-12 18:11
Duplicate of #3744.

**Closed by behlendorf** 2019-11-12 18:11 UTC
Labels: Type: Feature
