### ISSUE TITLE
Can't build in kernel 4.10.x

### ISSUE THREAD

**Issue by Rudd-O** [zfsonlinux/zfs#5954] opened 2017-04-01 12:01 UTC
Just hit this:

```
/*
 * 4.8 - 4.x API,
 *   REQ_OP_DISCARD
 *
 * 2.6.36 - 4.7 API,
 *   REQ_DISCARD
 *
 * 2.6.28 - 2.6.35 API,
 *   BIO_RW_DISCARD
 *
 * In all cases the normal I/O path is used for discards.  The only
 * difference is how the kernel tags individual I/Os as discards.
 *
 * Note that 2.6.32 era kernels provide both BIO_RW_DISCARD and REQ_DISCARD,
 * where BIO_RW_DISCARD is the correct interface.  Therefore, it is important
 * that the HAVE_BIO_RW_DISCARD check occur before the REQ_DISCARD check.
 */
static inline boolean_t
bio_is_discard(struct bio *bio)
{
#if defined(HAVE_REQ_OP_DISCARD)
        return (bio_op(bio) == REQ_OP_DISCARD);
#elif defined(HAVE_BIO_RW_DISCARD)
        return (bio->bi_rw & (1 << BIO_RW_DISCARD));
#elif defined(REQ_DISCARD)
        return (bio->bi_rw & REQ_DISCARD);
#else
#error  "Allowing the build will cause discard requests to become writes "
        "potentially triggering the DMU_MAX_ACCESS assertion. Please file "
        "an issue report at: https://github.com/zfsonlinux/zfs/issues/new"
#endif
}
```

Here:

```
[root@roxanne dkms]# cat ./zfs/0.7.0/build/make.log
DKMS make.log for zfs-0.7.0 for kernel 4.10.6-200.fc25.x86_64 (x86_64)
Sat Apr  1 11:53:41 UTC 2017
make  all-recursive
make[1]: Entering directory '/var/lib/dkms/zfs/0.7.0/build'
Making all in include
make[2]: Entering directory '/var/lib/dkms/zfs/0.7.0/build/include'
Making all in linux
make[3]: Entering directory '/var/lib/dkms/zfs/0.7.0/build/include/linux'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/var/lib/dkms/zfs/0.7.0/build/include/linux'
Making all in sys
make[3]: Entering directory '/var/lib/dkms/zfs/0.7.0/build/include/sys'
Making all in fm
make[4]: Entering directory '/var/lib/dkms/zfs/0.7.0/build/include/sys/fm'
Making all in fs
make[5]: Entering directory '/var/lib/dkms/zfs/0.7.0/build/include/sys/fm/fs'
make[5]: Nothing to be done for 'all'.
make[5]: Leaving directory '/var/lib/dkms/zfs/0.7.0/build/include/sys/fm/fs'
make[5]: Entering directory '/var/lib/dkms/zfs/0.7.0/build/include/sys/fm'
make[5]: Nothing to be done for 'all-am'.
make[5]: Leaving directory '/var/lib/dkms/zfs/0.7.0/build/include/sys/fm'
make[4]: Leaving directory '/var/lib/dkms/zfs/0.7.0/build/include/sys/fm'
Making all in fs
make[4]: Entering directory '/var/lib/dkms/zfs/0.7.0/build/include/sys/fs'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/var/lib/dkms/zfs/0.7.0/build/include/sys/fs'
Making all in crypto
make[4]: Entering directory '/var/lib/dkms/zfs/0.7.0/build/include/sys/crypto'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/var/lib/dkms/zfs/0.7.0/build/include/sys/crypto'
Making all in sysevent
make[4]: Entering directory '/var/lib/dkms/zfs/0.7.0/build/include/sys/sysevent'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/var/lib/dkms/zfs/0.7.0/build/include/sys/sysevent'
make[4]: Entering directory '/var/lib/dkms/zfs/0.7.0/build/include/sys'
make[4]: Nothing to be done for 'all-am'.
make[4]: Leaving directory '/var/lib/dkms/zfs/0.7.0/build/include/sys'
make[3]: Leaving directory '/var/lib/dkms/zfs/0.7.0/build/include/sys'
make[3]: Entering directory '/var/lib/dkms/zfs/0.7.0/build/include'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/var/lib/dkms/zfs/0.7.0/build/include'
make[2]: Leaving directory '/var/lib/dkms/zfs/0.7.0/build/include'
Making all in rpm
make[2]: Entering directory '/var/lib/dkms/zfs/0.7.0/build/rpm'
Making all in generic
make[3]: Entering directory '/var/lib/dkms/zfs/0.7.0/build/rpm/generic'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/var/lib/dkms/zfs/0.7.0/build/rpm/generic'
Making all in redhat
make[3]: Entering directory '/var/lib/dkms/zfs/0.7.0/build/rpm/redhat'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/var/lib/dkms/zfs/0.7.0/build/rpm/redhat'
make[3]: Entering directory '/var/lib/dkms/zfs/0.7.0/build/rpm'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/var/lib/dkms/zfs/0.7.0/build/rpm'
make[2]: Leaving directory '/var/lib/dkms/zfs/0.7.0/build/rpm'
Making all in module
make[2]: Entering directory '/var/lib/dkms/zfs/0.7.0/build/module'
list='icp'; for targetdir in $list; do \
	make -C $targetdir; \
done
make[3]: Entering directory '/var/lib/dkms/zfs/0.7.0/build/module/icp'
mkdir -p api core spi io os algs algs/aes algs/edonr algs/modes algs/sha1 algs/sha2 algs/skein asm-x86_64 asm-x86_64/aes asm-x86_64/modes asm-x86_64/sha1 asm-x86_64/sha2 asm-i386 asm-generic
make[3]: Leaving directory '/var/lib/dkms/zfs/0.7.0/build/module/icp'
make -C /lib/modules/4.10.6-200.fc25.x86_64/build SUBDIRS=`pwd`  CONFIG_ZFS=m modules
make[3]: Entering directory '/usr/src/kernels/4.10.6-200.fc25.x86_64'
  CC [M]  /var/lib/dkms/zfs/0.7.0/build/module/avl/avl.o
  CC [M]  /var/lib/dkms/zfs/0.7.0/build/module/nvpair/nvpair.o
  CC [M]  /var/lib/dkms/zfs/0.7.0/build/module/zcommon/zfs_deleg.o
  CC [M]  /var/lib/dkms/zfs/0.7.0/build/module/icp/illumos-crypto.o
  CC [M]  /var/lib/dkms/zfs/0.7.0/build/module/unicode/u8_textprep.o
  CC [M]  /var/lib/dkms/zfs/0.7.0/build/module/zfs/arc.o
  CC [M]  /var/lib/dkms/zfs/0.7.0/build/module/zpios/pios.o
  CC [M]  /var/lib/dkms/zfs/0.7.0/build/module/zfs/abd.o
In file included from /var/lib/dkms/zfs/0.7.0/build/include/sys/dmu.h:735:0,
                 from /var/lib/dkms/zfs/0.7.0/build/include/sys/dsl_deleg.h:29,
                 from /var/lib/dkms/zfs/0.7.0/build/module/zcommon/zfs_deleg.c:40:
/var/lib/dkms/zfs/0.7.0/build/include/linux/blkdev_compat.h: In function ‘bio_is_discard’:
/var/lib/dkms/zfs/0.7.0/build/include/linux/blkdev_compat.h:409:2: error: #error "Allowing the build will cause discard requests to become writes "
 #error "Allowing the build will cause discard requests to become writes "
  ^~~~~
/var/lib/dkms/zfs/0.7.0/build/include/linux/blkdev_compat.h:410:2: warning: statement with no effect [-Wunused-value]
  "potentially triggering the DMU_MAX_ACCESS assertion. Please file "
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/zfs/0.7.0/build/include/linux/blkdev_compat.h:413:1: error: expected ‘;’ before ‘}’ token
 }
 ^
/var/lib/dkms/zfs/0.7.0/build/include/linux/blkdev_compat.h:413:1: warning: no return statement in function returning non-void [-Wreturn-type]
In file included from /var/lib/dkms/zfs/0.7.0/build/include/sys/dmu.h:735:0,
                 from /var/lib/dkms/zfs/0.7.0/build/include/sys/spa.h:40,
                 from /var/lib/dkms/zfs/0.7.0/build/include/sys/zio.h:34,
                 from /var/lib/dkms/zfs/0.7.0/build/module/zfs/abd.c:119:
/var/lib/dkms/zfs/0.7.0/build/include/linux/blkdev_compat.h: In function ‘bio_is_discard’:
scripts/Makefile.build:294: recipe for target '/var/lib/dkms/zfs/0.7.0/build/module/zcommon/zfs_deleg.o' failed
/var/lib/dkms/zfs/0.7.0/build/include/linux/blkdev_compat.h:409:2: error: #error "Allowing the build will cause discard requests to become writes "
 #error "Allowing the build will cause discard requests to become writes "
  ^~~~~
make[5]: *** [/var/lib/dkms/zfs/0.7.0/build/module/zcommon/zfs_deleg.o] Error 1
/var/lib/dkms/zfs/0.7.0/build/include/linux/blkdev_compat.h:410:2: warning: statement with no effect [-Wunused-value]
  "potentially triggering the DMU_MAX_ACCESS assertion. Please file "
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/zfs/0.7.0/build/include/linux/blkdev_compat.h:413:1: error: expected ‘;’ before ‘}’ token
 }
 ^
/var/lib/dkms/zfs/0.7.0/build/include/linux/blkdev_compat.h:413:1: warning: no return statement in function returning non-void [-Wreturn-type]
scripts/Makefile.build:553: recipe for target '/var/lib/dkms/zfs/0.7.0/build/module/zcommon' failed
make[4]: *** [/var/lib/dkms/zfs/0.7.0/build/module/zcommon] Error 2
make[4]: *** Waiting for unfinished jobs....
In file included from /var/lib/dkms/zfs/0.7.0/build/include/sys/dmu.h:735:0,
                 from /var/lib/dkms/zfs/0.7.0/build/module/zpios/pios.c:37:
/var/lib/dkms/zfs/0.7.0/build/include/linux/blkdev_compat.h: In function ‘bio_is_discard’:
/var/lib/dkms/zfs/0.7.0/build/include/linux/blkdev_compat.h:409:2: error: #error "Allowing the build will cause discard requests to become writes "
 #error "Allowing the build will cause discard requests to become writes "
  ^~~~~
/var/lib/dkms/zfs/0.7.0/build/include/linux/blkdev_compat.h:410:2: warning: statement with no effect [-Wunused-value]
  "potentially triggering the DMU_MAX_ACCESS assertion. Please file "
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/zfs/0.7.0/build/include/linux/blkdev_compat.h:413:1: error: expected ‘;’ before ‘}’ token
```

**Comment by behlendorf** [comment] 2017-04-03 17:25
Can you include the `config.log` so we can determine why the `HAVE_REQ_OP_DISCARD` wasn't defined for the 4.10 kernel you're using.

**Comment by drakedevel** [comment] 2017-04-03 18:39
Not the original reporter, but here's the REQ_OP_DISCARD section from my config.log (4.10.5 on Fedora 25):

```
configure:14815: checking whether REQ_OP_DISCARD is defined
configure:14848: cp conftest.c conftest.h build && make modules -C /lib/modules/4.10.5-200.fc25.x86_64/build EXTRA_CFLAGS=-Werror   M=/var/lib/dkms/zfs/0.6.5.8/build/build 
/var/lib/dkms/zfs/0.6.5.8/build/build/conftest.c: In function ‘main’:
/var/lib/dkms/zfs/0.6.5.8/build/build/conftest.c:49:8: error: variable ‘op’ has initializer but incomplete type
   enum req_op op __attribute__ ((unused)) = REQ_OP_DISCARD;
        ^~~~~~
/var/lib/dkms/zfs/0.6.5.8/build/build/conftest.c:49:15: error: storage size of ‘op’ isn’t known
   enum req_op op __attribute__ ((unused)) = REQ_OP_DISCARD;
               ^~
make[1]: *** [/var/lib/dkms/zfs/0.6.5.8/build/build/conftest.o] Error 1
make: *** [_module_/var/lib/dkms/zfs/0.6.5.8/build/build] Error 2
configure:14851: $? = 2
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "zfs"
| #define PACKAGE_TARNAME "zfs"
| #define PACKAGE_VERSION "0.6.5.8"
| #define PACKAGE_STRING "zfs 0.6.5.8"
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| #define ZFS_META_NAME "zfs"
| #define ZFS_META_VERSION "0.6.5.8"
| #define ZFS_META_RELEASE "2"
| #define ZFS_META_LICENSE "CDDL"
| #define ZFS_META_ALIAS "zfs-0.6.5.8-2"
| #define ZFS_META_AUTHOR "OpenZFS on Linux"
| #define PACKAGE "zfs"
| #define VERSION "0.6.5.8"
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define HAVE_DLFCN_H 1
| #define LT_OBJDIR ".libs/"
| #define HAVE_CURRENT_BIO_LIST 1
| #define HAVE_1ARG_SUBMIT_BIO 1
| #define HAVE_BDEV_BLOCK_DEVICE_OPERATIONS 1
| #define HAVE_BLOCK_DEVICE_OPERATIONS_RELEASE_VOID 1
| #define HAVE_FMODE_T 1
| #define HAVE_3ARG_BLKDEV_GET 1
| #define HAVE_BLKDEV_GET_BY_PATH 1
| #define HAVE_LOOKUP_BDEV 1
| #define HAVE_1ARG_INVALIDATE_BDEV 1
| #define HAVE_BDEV_LOGICAL_BLOCK_SIZE 1
| #define HAVE_BDEV_PHYSICAL_BLOCK_SIZE 1
| #define HAVE_BIO_BVEC_ITER 1
| #define HAVE_REQ_FAILFAST_MASK 1
| 
| 
|               #include <linux/blk_types.h>
| 
| int
| main (void)
| {
| 
|               enum req_op op __attribute__ ((unused)) = REQ_OP_DISCARD;
| 
|   ;
|   return 0;
| }
| 
configure:14869: result: no
```

Can upload all of config.log if you like

**Comment by behlendorf** [comment] 2017-04-03 19:32
This issue should have been addressed by commit a5e046eaacad20487188c9eef231554e1401d8c9 which is part of v0.7.0-rc3 and v0.6.5.9.

**Comment by drakedevel** [comment] 2017-04-03 19:41
Confirmed 0.6.5.9 fixes the build for me. It looks like my `/etc/yum.repos.d/zfs.repo` disappeared (despite the `zfs-release` rpm still being installed), causing me to not get the upgrade from 0.6.5.8 automatically. Sorry for the noise!

**Comment by Rudd-O** [comment] 2017-04-03 21:11
Oooh.  Thank you!

**Closed** 2017-04-03 21:25 UTC
Labels: Build Issue
