### ISSUE TITLE
ddt_object_remove (from ddt_sync_entry()) panics.

### ISSUE THREAD

**Issue by BenEstrabaud** [zfsonlinux/zfs#4051] opened 2015-11-27 12:14 UTC
Hi,

After starting a Volume block device (a similar Volume to LVM) and calling "zpool import" to import the previously created pool ontop of that Volume (single vdev pool), I get a "PANIC" from the ZFS driver in what seems to be the deduplication code:

<0>[ 1390.005410] VERIFY(ddt_object_remove(ddt, otype, oclass, dde, tx) == 0) failed
<0>[ 1390.013567] PANIC at ddt.c:1106:ddt_sync_entry()  
<4>[ 1390.018797] Showing stack for process 24500  
<4>[ 1390.023570] CPU: 0 PID: 24500 Comm: txg_sync Tainted: P           O    4.1.5 #15
<4>[ 1390.031969] Hardware name: Newisys NDS_SB1EA/NDS_SB1EA, BIOS 9.20 07/28/2015
<4>[ 1390.031971]  ffffffffa0695cff ffff881eb48d79e8 ffffffff816b4518 0000000000000000
<4>[ 1390.031972]  ffff881eb48d7a18 ffff881eb48d79f8 ffffffffa0538fe4 ffff881eb48d7b88
<4>[ 1390.031973]  ffffffffa05391b7 ffff881eb48d7ab8 ffffffffa069f93f 6428594649524556
<4>[ 1390.031974] Call Trace:  
<4>[ 1390.031984]  [<ffffffff816b4518>] dump_stack+0x48/0x60  
<4>[ 1390.031989]  [<ffffffffa0538fe4>] spl_dumpstack+0x44/0x50 [spl]  
<4>[ 1390.031992]  [<ffffffffa05391b7>] spl_panic+0xa7/0xe0 [spl]  
<4>[ 1390.032009]  [<ffffffffa0648331>] ? fzap_byteswap+0x831/0x850 [zfs]  
<4>[ 1390.032016]  [<ffffffffa05d9650>] ? dbuf_rele+0x40/0x50 [zfs]  
<4>[ 1390.032021]  [<ffffffffa05d966e>] ? dmu_buf_rele+0xe/0x10 [zfs]  
<4>[ 1390.032034]  [<ffffffffa064c6ca>] ? zap_unlockdir+0x4a/0xc0 [zfs]  
<4>[ 1390.032036]  [<ffffffffa05347dc>] ? spl_kmem_cache_free+0x16c/0x1e0 [spl] 
<4>[ 1390.032044]  [<ffffffffa05e08e6>] ddt_sync+0x2e6/0xa40 [zfs]  
<4>[ 1390.032057]  [<ffffffffa067ee11>] ? zio_buf_free+0x251/0x12f0 [zfs]  
<4>[ 1390.032068]  [<ffffffffa068018b>] ? zio_wait+0x15b/0x1e0 [zfs]  
<4>[ 1390.032081]  [<ffffffffa062183b>] spa_sync+0x3bb/0xe80 [zfs]  
<4>[ 1390.032083]  [<ffffffff81097a09>] ? __wake_up_common+0x59/0x90  
<4>[ 1390.032084]  [<ffffffff810980f3>] ? __wake_up+0x53/0x70  
<4>[ 1390.032087]  [<ffffffff810c3c3f>] ? getrawmonotonic64+0x3f/0xd0  
<4>[ 1390.032099]  [<ffffffffa0637654>] txg_init+0x614/0x890 [zfs]  
<4>[ 1390.032102]  [<ffffffff8118bfc8>] ? kfree+0x108/0x140  
<4>[ 1390.032112]  [<ffffffffa0637280>] ? txg_init+0x240/0x890 [zfs]  
<4>[ 1390.032115]  [<ffffffffa05362c0>] ? __thread_create+0x160/0x1f0 [spl]  
<4>[ 1390.032118]  [<ffffffffa0536338>] __thread_create+0x1d8/0x1f0 [spl]  
<4>[ 1390.032120]  [<ffffffffa05362c0>] ? __thread_create+0x160/0x1f0 [spl]  
<4>[ 1390.032122]  [<ffffffff810788de>] kthread+0xce/0x100  
<4>[ 1390.032124]  [<ffffffff81078810>] ? kthread_freezable_should_stop+0x70/0x70
<4>[ 1390.032125]  [<ffffffff816b8f12>] ret_from_fork+0x42/0x70  
<4>[ 1390.032127]  [<ffffffff81078810>] ? kthread_freezable_should_stop+0x70/0x70
<6>[ 1428.259556] ixgbe 0000:01:00.1 eth3: NIC Link is Down     

That issue only happened once after extensive export/import testing (think tens of iterations).

it seems to be like a "BUG ON" condition, where an assertion fails (ddt_object_remove(ddt, otype, oclass, dde, tx) == 0). Any idea what could be causing this?

**Comment by behlendorf** [comment] 2015-12-10 22:36
@BenEstrabaud it would be great if you could tweak the code slightly so we can get the errno returned.  This should work, then we may be able to say why.

```diff
diff --git a/module/zfs/ddt.c b/module/zfs/ddt.c
index 12c1b73..9df77cf 100644
--- a/module/zfs/ddt.c
+++ b/module/zfs/ddt.c
@@ -1103,7 +1103,7 @@ ddt_sync_entry(ddt_t *ddt, ddt_entry_t *dde, dmu_tx_t *tx,
 
        if (otype != DDT_TYPES &&
            (otype != ntype || oclass != nclass || total_refcnt == 0)) {
-               VERIFY(ddt_object_remove(ddt, otype, oclass, dde, tx) == 0);
+               VERIFY0(ddt_object_remove(ddt, otype, oclass, dde, tx));
                ASSERT(ddt_object_lookup(ddt, otype, oclass, dde) == ENOENT);
        }
 
```

**Comment by loli10K** [comment] 2018-09-11 18:50
Duplicate of https://github.com/zfsonlinux/zfs/issues/1681

**Closed by loli10K** 2018-09-11 18:50 UTC
