### ISSUE TITLE
Clones remounted by rename actions on the parent

### ISSUE THREAD

**Issue by DeHackEd** [zfsonlinux/zfs#2297] opened 2014-05-03 15:10 UTC
<pre>
# zfs snapshot poolname/originfs@current
# zfs clone poolname/originfs@current poolname/clone1 -o mountpoint=/poolname/clone1
# cd /poolname/clone1
# zfs rename poolname/originfs@current poolname/originfs@previous
</pre>

Expected result:
- Rename is successful

Actual result:
- Rename fails because the clone's mount point is busy (unmount fails)

Test system: ZFS v0.6.2-12_g36342b1 (yes, it's behind)

**Comment by loli10K** [comment] 2017-08-18 14:18
Closing as duplicate of https://github.com/zfsonlinux/zfs/issues/6119.

Actually it's the other way around, #6119 is the duplicate, but since it's already using the new issue template and linking another (possibly) related issue i think it's better to close this one.

**Closed by loli10K** 2017-08-18 14:18 UTC
