### ISSUE TITLE
default debian install doesn't load modules until pool is created

### ISSUE THREAD

**Issue by pstratem** [zfsonlinux/zfs#8240] opened 2019-01-05 23:21 UTC
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Debian
Distribution Version	| Stretch
Linux Kernel	| 4.9.0-8
Architecture	|  amd64
ZFS Version	| 0.6.5.9
SPL Version	| 0.6.5.9

### Describe the problem you're observing
"The ZFS modules are not loaded.
Try running '/sbin/modprobe zfs' as root to load them."

zfs-import-cache.service requires that /etc/zfs/zpool.cache exists, however this file is only created when a pool is created.

It was confusing that the modules didn't load when I installed and rebooted.

Could be fixed by either not requiring the file to exist or loading the modules in another service.

**Comment by loli10K** [comment] 2019-01-06 05:44
Duplicate of #6083

**Comment by bunder2015** [comment] 2019-01-06 06:55
Closing as duplicate, please see 6083

**Closed by bunder2015** 2019-01-06 06:55 UTC
