### ISSUE TITLE
Root Xattrs and ACLs disappear on large datasets copied with zfs send/receive

### ISSUE THREAD

**Issue by grantma** [zfsonlinux/zfs#8740] opened 2019-05-13 22:08 UTC
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| 
Distribution Version	| 
Linux Kernel	| 
Architecture	| 
ZFS Version	| 
SPL Version	|

**Comment by fling-** [comment] 2019-05-14 13:13
Duplicate of #8741.
@grantma close this one.

**Comment by behlendorf** [comment] 2019-05-14 14:07
Closing as duplicate of #8741

**Closed by behlendorf** 2019-05-14 14:07 UTC
