### ISSUE TITLE
Missing properties in initial -R replication.

### ISSUE THREAD

**Issue by hkbakke** [zfsonlinux/zfs#5563] opened 2017-01-05 15:51 UTC
### System information
Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Debian
Distribution Version    | Jessie
Linux Kernel                 |  3.16.36-1+deb8u1
Architecture                 |  amd64
ZFS Version                  |  0.6.5.8-2~bpo8+1
SPL Version                  |  0.6.5.8-2~bpo8+2

### Describe the problem you're observing
Local properties set on snapshot are not replicated during initial replication with -R, but are replicated successfully on successive incremental replications with -R -I.

### Describe how to reproduce the problem
Create snapshot on source dataset:
<pre>/sbin/zfs snapshot -o zfssnap:label=replicate-vms-frequent -o zfssnap:version=3.1.0 -r dev-1/test-1@zfssnap_20170105T153439Z</pre>

Replicate snapshot to non-existing destination dataset:
<pre>/sbin/zfs send -R dev-1/test-1@zfssnap_20170105T153439Z | zfs receive -F -v dev-2/backup/test-1</pre>

After replication the snapshot on the source dataset looks like expected:
<pre>
# zfs get all dev-1/test-1@zfssnap_20170105T153439Z
NAME                                   PROPERTY              VALUE                   SOURCE
dev-1/test-1@zfssnap_20170105T153439Z  type                  snapshot                -
dev-1/test-1@zfssnap_20170105T153439Z  creation              Thu Jan  5 15:34 2017   -
dev-1/test-1@zfssnap_20170105T153439Z  used                  0                       -
dev-1/test-1@zfssnap_20170105T153439Z  referenced            19K                     -
dev-1/test-1@zfssnap_20170105T153439Z  compressratio         1.00x                   -
dev-1/test-1@zfssnap_20170105T153439Z  devices               on                      default
dev-1/test-1@zfssnap_20170105T153439Z  exec                  on                      default
dev-1/test-1@zfssnap_20170105T153439Z  setuid                on                      default
dev-1/test-1@zfssnap_20170105T153439Z  xattr                 sa                      inherited from dev-1
dev-1/test-1@zfssnap_20170105T153439Z  version               5                       -
dev-1/test-1@zfssnap_20170105T153439Z  utf8only              off                     -
dev-1/test-1@zfssnap_20170105T153439Z  normalization         none                    -
dev-1/test-1@zfssnap_20170105T153439Z  casesensitivity       sensitive               -
dev-1/test-1@zfssnap_20170105T153439Z  nbmand                off                     default
dev-1/test-1@zfssnap_20170105T153439Z  primarycache          all                     default
dev-1/test-1@zfssnap_20170105T153439Z  secondarycache        all                     default
dev-1/test-1@zfssnap_20170105T153439Z  defer_destroy         off                     -
dev-1/test-1@zfssnap_20170105T153439Z  userrefs              0                       -
dev-1/test-1@zfssnap_20170105T153439Z  mlslabel              none                    default
dev-1/test-1@zfssnap_20170105T153439Z  refcompressratio      1.00x                   -
dev-1/test-1@zfssnap_20170105T153439Z  written               19K                     -
dev-1/test-1@zfssnap_20170105T153439Z  clones                                        -
dev-1/test-1@zfssnap_20170105T153439Z  logicalused           0                       -
dev-1/test-1@zfssnap_20170105T153439Z  logicalreferenced     9.50K                   -
dev-1/test-1@zfssnap_20170105T153439Z  acltype               posixacl                inherited from dev-1
dev-1/test-1@zfssnap_20170105T153439Z  context               none                    default
dev-1/test-1@zfssnap_20170105T153439Z  fscontext             none                    default
dev-1/test-1@zfssnap_20170105T153439Z  defcontext            none                    default
dev-1/test-1@zfssnap_20170105T153439Z  rootcontext           none                    default
dev-1/test-1@zfssnap_20170105T153439Z  zfssnap:label         replicate-vms-frequent  local
dev-1/test-1@zfssnap_20170105T153439Z  zfssnap:version       3.1.0                   local
</pre>

But the destination dataset is missing the custom zfssnap properties:
<pre>
# zfs get all dev-2/backup/test-1@zfssnap_20170105T153439Z
NAME                                          PROPERTY              VALUE                  SOURCE
dev-2/backup/test-1@zfssnap_20170105T153439Z  type                  snapshot               -
dev-2/backup/test-1@zfssnap_20170105T153439Z  creation              Thu Jan  5 15:34 2017  -
dev-2/backup/test-1@zfssnap_20170105T153439Z  used                  0                      -
dev-2/backup/test-1@zfssnap_20170105T153439Z  referenced            19K                    -
dev-2/backup/test-1@zfssnap_20170105T153439Z  compressratio         1.00x                  -
dev-2/backup/test-1@zfssnap_20170105T153439Z  devices               on                     default
dev-2/backup/test-1@zfssnap_20170105T153439Z  exec                  on                     default
dev-2/backup/test-1@zfssnap_20170105T153439Z  setuid                on                     default
dev-2/backup/test-1@zfssnap_20170105T153439Z  xattr                 sa                     inherited from dev-2
dev-2/backup/test-1@zfssnap_20170105T153439Z  version               5                      -
dev-2/backup/test-1@zfssnap_20170105T153439Z  utf8only              off                    -
dev-2/backup/test-1@zfssnap_20170105T153439Z  normalization         none                   -
dev-2/backup/test-1@zfssnap_20170105T153439Z  casesensitivity       sensitive              -
dev-2/backup/test-1@zfssnap_20170105T153439Z  nbmand                off                    default
dev-2/backup/test-1@zfssnap_20170105T153439Z  primarycache          all                    default
dev-2/backup/test-1@zfssnap_20170105T153439Z  secondarycache        all                    default
dev-2/backup/test-1@zfssnap_20170105T153439Z  defer_destroy         off                    -
dev-2/backup/test-1@zfssnap_20170105T153439Z  userrefs              0                      -
dev-2/backup/test-1@zfssnap_20170105T153439Z  mlslabel              none                   default
dev-2/backup/test-1@zfssnap_20170105T153439Z  refcompressratio      1.00x                  -
dev-2/backup/test-1@zfssnap_20170105T153439Z  written               19K                    -
dev-2/backup/test-1@zfssnap_20170105T153439Z  clones                                       -
dev-2/backup/test-1@zfssnap_20170105T153439Z  logicalused           0                      -
dev-2/backup/test-1@zfssnap_20170105T153439Z  logicalreferenced     9.50K                  -
dev-2/backup/test-1@zfssnap_20170105T153439Z  acltype               posixacl               inherited from dev-2
dev-2/backup/test-1@zfssnap_20170105T153439Z  context               none                   default
dev-2/backup/test-1@zfssnap_20170105T153439Z  fscontext             none                   default
dev-2/backup/test-1@zfssnap_20170105T153439Z  defcontext            none                   default
dev-2/backup/test-1@zfssnap_20170105T153439Z  rootcontext           none                   default
</pre>

However after a second incremental sync:
<pre>
/sbin/zfs snapshot -o zfssnap:label=replicate-vms-frequent -o zfssnap:version=3.1.0 -r dev-1/test-1@zfssnap_20170105T154639Z
/sbin/zfs send -R -I @zfssnap_20170105T153439Z dev-1/test-1@zfssnap_20170105T154639Z | zfs receive -F -v dev-2/backup/test-1

Replicating dev-1/test-1 to dev-2/backup/test-1
receiving incremental stream of dev-1/test-1@zfssnap_20170105T154639Z into dev-2/backup/test-1@zfssnap_20170105T154639Z
received 312B stream in 1 seconds (312B/sec)
</pre>

The previous snapshot on the destination is updated to look like I would expect from the initial sync:
<pre>
# zfs get all dev-2/backup/test-1@zfssnap_20170105T153439Z
NAME                                          PROPERTY              VALUE                   SOURCE
dev-2/backup/test-1@zfssnap_20170105T153439Z  type                  snapshot                -
dev-2/backup/test-1@zfssnap_20170105T153439Z  creation              Thu Jan  5 15:34 2017   -
dev-2/backup/test-1@zfssnap_20170105T153439Z  used                  1K                      -
dev-2/backup/test-1@zfssnap_20170105T153439Z  referenced            19K                     -
dev-2/backup/test-1@zfssnap_20170105T153439Z  compressratio         1.00x                   -
dev-2/backup/test-1@zfssnap_20170105T153439Z  devices               on                      default
dev-2/backup/test-1@zfssnap_20170105T153439Z  exec                  on                      default
dev-2/backup/test-1@zfssnap_20170105T153439Z  setuid                on                      default
dev-2/backup/test-1@zfssnap_20170105T153439Z  xattr                 sa                      inherited from dev-2
dev-2/backup/test-1@zfssnap_20170105T153439Z  version               5                       -
dev-2/backup/test-1@zfssnap_20170105T153439Z  utf8only              off                     -
dev-2/backup/test-1@zfssnap_20170105T153439Z  normalization         none                    -
dev-2/backup/test-1@zfssnap_20170105T153439Z  casesensitivity       sensitive               -
dev-2/backup/test-1@zfssnap_20170105T153439Z  nbmand                off                     default
dev-2/backup/test-1@zfssnap_20170105T153439Z  primarycache          all                     default
dev-2/backup/test-1@zfssnap_20170105T153439Z  secondarycache        all                     default
dev-2/backup/test-1@zfssnap_20170105T153439Z  defer_destroy         off                     -
dev-2/backup/test-1@zfssnap_20170105T153439Z  userrefs              0                       -
dev-2/backup/test-1@zfssnap_20170105T153439Z  mlslabel              none                    default
dev-2/backup/test-1@zfssnap_20170105T153439Z  refcompressratio      1.00x                   -
dev-2/backup/test-1@zfssnap_20170105T153439Z  written               19K                     -
dev-2/backup/test-1@zfssnap_20170105T153439Z  clones                                        -
dev-2/backup/test-1@zfssnap_20170105T153439Z  logicalused           0                       -
dev-2/backup/test-1@zfssnap_20170105T153439Z  logicalreferenced     9.50K                   -
dev-2/backup/test-1@zfssnap_20170105T153439Z  acltype               posixacl                inherited from dev-2
dev-2/backup/test-1@zfssnap_20170105T153439Z  context               none                    default
dev-2/backup/test-1@zfssnap_20170105T153439Z  fscontext             none                    default
dev-2/backup/test-1@zfssnap_20170105T153439Z  defcontext            none                    default
dev-2/backup/test-1@zfssnap_20170105T153439Z  rootcontext           none                    default
dev-2/backup/test-1@zfssnap_20170105T153439Z  zfssnap:label         replicate-vms-frequent  received
dev-2/backup/test-1@zfssnap_20170105T153439Z  zfssnap:version       3.1.0                   received
</pre>

**Comment by loli10K** [comment] 2017-01-05 17:38
Possible duplicate of https://github.com/zfsonlinux/zfs/issues/4338? @hkbakke can you confirm that snapshot properties are indeed sent (so we know the problem is on the recv side) with:

```
/sbin/zfs send -R dev-1/test-1@zfssnap_20170105T153439Z | zstreamdump -v
```

**Comment by hkbakke** [comment] 2017-01-05 18:26
It seems to me like they are sent

<pre>
BEGIN record
        hdrtype = 2
        features = 4
        magic = 2f5bacbac
        creation_time = 0
        type = 0
        flags = 0x0
        toguid = 0
        fromguid = 0
        toname = dev-1/test-1@zfssnap_20170105T153439Z

nvlist version: 0
        tosnap = zfssnap_20170105T153439Z
        fss = (embedded nvlist)
        nvlist version: 0
                0x86eedb91686e844b = (embedded nvlist)
                nvlist version: 0
                        name = dev-1/test-1
                        parentfromsnap = 0x0
                        props = (embedded nvlist)
                        nvlist version: 0
                        (end props)

                        snaps = (embedded nvlist)
                        nvlist version: 0
                                zfssnap_20170105T153439Z = 0xb1aa91085eada90b
                        (end snaps)

                        snapprops = (embedded nvlist)
                        nvlist version: 0
                                zfssnap_20170105T153439Z = (embedded nvlist)
                                nvlist version: 0
                                        zfssnap:version = 3.1.0
                                        zfssnap:label = replicate-vms-frequent
                                (end zfssnap_20170105T153439Z)

                        (end snapprops)

                (end 0x86eedb91686e844b)

        (end fss)

END checksum = 1b5e80b6e7/a2a81b40157/2b2a9d20f75d7/94a59cb89f5f06
BEGIN record
        hdrtype = 1
        features = 4
        magic = 2f5bacbac
        creation_time = 586e8ecc
        type = 2
        flags = 0x0
        toguid = b1aa91085eada90b
        fromguid = 0
        toname = dev-1/test-1@zfssnap_20170105T153439Z

OBJECT object = 1 type = 21 bonustype = 0 blksz = 512 bonuslen = 0
OBJECT object = 2 type = 45 bonustype = 0 blksz = 512 bonuslen = 0
OBJECT object = 3 type = 22 bonustype = 0 blksz = 512 bonuslen = 0
OBJECT object = 4 type = 20 bonustype = 44 blksz = 512 bonuslen = 168
OBJECT object = 5 type = 46 bonustype = 0 blksz = 1536 bonuslen = 0
OBJECT object = 6 type = 47 bonustype = 0 blksz = 16384 bonuslen = 0
WRITE object = 1 type = 21 checksum type = 7
offset = 0 length = 512 props = 200000000
WRITE object = 2 type = 45 checksum type = 2
offset = 0 length = 512 props = 0
WRITE object = 3 type = 22 checksum type = 2
offset = 0 length = 512 props = 0
WRITE object = 4 type = 20 checksum type = 2
offset = 0 length = 512 props = 0
WRITE object = 5 type = 46 checksum type = 7
offset = 0 length = 1536 props = f00000002
WRITE object = 6 type = 47 checksum type = 7
offset = 0 length = 16384 props = f0000001f
WRITE object = 6 type = 47 checksum type = 7
offset = 16384 length = 16384 props = f0006001f
END checksum = 141111f5f72/1769ab19d5667e/ebfba4afde4be3/ed7f552e17a5dfb5
END checksum = 0/0/0/0
SUMMARY:
        Total DRR_BEGIN records = 2
        Total DRR_END records = 3
        Total DRR_OBJECT records = 6
        Total DRR_FREEOBJECTS records = 0
        Total DRR_WRITE records = 7
        Total DRR_WRITE_BYREF records = 0
        Total DRR_WRITE_EMBEDDED records = 0
        Total DRR_FREE records = 0
        Total DRR_SPILL records = 0
        Total records = 18
        Total write size = 36352 (0x8e00)
        Total stream length = 42752 (0xa700)
</pre>

**Comment by loli10K** [comment] 2017-01-05 18:36
@hkbakke yes they are indeed, this should be fixed in https://github.com/zfsonlinux/zfs/commit/48f783de792727c26f43983155bac057c296e44d: you can either backport that commit on your current version or wait for it to land in your distro packages.

**Comment by hkbakke** [comment] 2017-01-05 18:43
OK, thank you!

**Closed** 2017-01-05 18:47 UTC
