### ISSUE TITLE
even with a zpool.cache file, zfs module imports pools on load even when zfs_autoimport_disable=1

### ISSUE THREAD

**Issue by aarcane** [zfsonlinux/zfs#2474] opened 2014-07-09 05:26 UTC
When a zpool.cache file is present in the initramfs on debian wheezy 7.5 with zfs version 0.6.3, the initramfs zfs hook calls 
    modprobe zfs zfs_autoimport_disable=1
The pools specified in zpool.cache are still automatically imported.  Clearly this is not the intended behaviour.

**Comment by behlendorf** [comment] 2016-10-12 00:16
Closing.  This is working as intended in current releases.

**Closed by behlendorf** 2016-10-12 00:16 UTC
