### ISSUE TITLE
dataset disappeared after disk failure, resilvering failed

### ISSUE THREAD

**Issue by tr03lf** [zfsonlinux/zfs#3040] opened 2015-01-25 16:32 UTC
Hey guys,

I had a power outage which caused one of my HDDs to fail. I am using a raidz1-pool with 4 2TB disks so i replaced the broken HDD with a new one and started the resilvering process. Although the pool should have been available (degrated of course, but still) i noticed that my main dataset hasn't shown anymore by 'zfs list'. This is the output:
~# zfs list
NAME                USED  AVAIL  REFER  MOUNTPOINT
tank               4,62T   582G  4,62T  /tank
tank/tmp            616K   582G   221K  /tank/tmp
tank/tmp/Download   198K   582G   198K  /tank/tmp/Download
tank/tmp/Upload     198K   582G   198K  /tank/tmp/Upload

as you might see, there are 4,62 TB shown as used, although the listed datasets are almost empty. The used data belongs to the dataset tank/data which is missing. I got a little nervous, but thought that maybe after the resilvering process I could access all datasets again. Unfortunately, that didn't go too well:
~# zpool status -v
  pool: tank
 state: DEGRADED
  scan: resilvered 1,10G in 8h56m with 0 errors on Sun Jan 18 20:58:21 2015
config:
        NAME             STATE     READ WRITE CKSUM
        tank             DEGRADED     0     0     0
          raidz1-0       DEGRADED     0     0     0
            replacing-0  UNAVAIL      0    48     0  insufficient replicas
              old        UNAVAIL      0     0     0  corrupted data
              edisk1     FAULTED      3 9,36K     0  too many errors
            edisk2       ONLINE       0     0     0
            edisk3       ONLINE       0     0     0
            edisk4       ONLINE       0     0     0
errors: No known data errors

Has anybody an explanation what happened to my dataset and maybe some good advice on how to restore it? Furthermore, why didn't the resilvering process finish successfully. According to the zpool and some SMART information there was only 1 faulted disk after the blackout. If there's anything else I can provide to clarify the problem for you, please tell me. Any help is highly appreciated.

Thanks,
Micha

#####
Basic information
CPUs:			4
Memory:			16 GB
VM/Hypervisor:	no
ECC mem:		no
Distribution:		Debian GNU/Linux
Kernel version:		Linux 3.2.0-4-amd64 #1 SMP Debian 3.2.46-1 x86_64 GNU/Linux
SPL/ZFS source:	Packages from the ZoL package repository
SPL/ZFS version:	~# dmesg | grep -E 'SPL:|ZFS:'
[    6.229355] SPL: Loaded module v0.6.1-rc14
[    6.324389] SPL: using hostid 0x007f0101
[    6.331132] ZFS: Loaded module v0.6.1-rc14, ZFS pool version 5000, ZFS filesystem version 5
System services:	FileServer
Short  description:	Dataset disappeared after disk failure

**Comment by DeHackEd** [comment] 2015-01-26 02:47
This isn't a support forum. It's a bug tracker.

All your "referenced" space is in the root filesystem. You made your subfilesystems, but they must not have been mounted. unmount everything except the top-level filesystem - your stuff will be in there.

Alternatively:
<pre># mkdir /tmp/tankroot
# mount --bind /tank /tmp/tankroot</pre>
and all your stuff will be in <tt>/tmp/tankroot</tt>

**Comment by tr03lf** [comment] 2015-01-27 18:58
Alright...sorry about that. Not every issue here looks like a clear bug report to me and I've just posted my problem like it said on the FAQs of zfsonlinux. For all I know, it could be bug, too. If it is not and I'm just totally missing something, that's even better. But unfortunately your advice didn't help. My rootfs is a separate 64GB SSD with an ext4 fs. Unmounting everything and mounting /tank to /tmp/tankroot only showed up an empty folder tmp under the specified location. Could you or anybody be so kind and post a link to a good board where i can post my issue? Thank you!

**Comment by dasjoe** [comment] 2015-03-02 22:53
`zfs list -o name,used,available,referenced,mountpoint,mounted` shows your `tmp` and its sub-datasets as mounted? Then do what @DeHackEd recommends and unmount those datasets, your data is in the root dataset `tank`.

**Comment by behlendorf** [comment] 2016-10-12 01:35
Closing this was a support issue, not a bug.

**Closed by behlendorf** 2016-10-12 01:35 UTC
