### ISSUE TITLE
zpool labelclear /dev/sda and /dev/sdb wiped partitions !!!

### ISSUE THREAD

**Issue by devZer0** [zfsonlinux/zfs#6261] opened 2017-06-23 12:59 UTC
I have setup two old hdd`s for a new OS installation (raid1 mdadm mirror).
The disks had been used in a zpool before.

After new CentOS installation (i.e. new partitioning / formatting) some "ghost" pool showed up i tried to get rid of with zpool labelclear, as i thought that would wipe the "remaining" zfs information from the disks.

IIrc, i wiped the disks befor OS installation with "dd", but as they are 2TB i did not wait dd to finish.

Apparently, the system did not boot anymore after labelclear operation. 
The partition tables seem to be wiped completely and i was not able to recover the partitions.

I`m not sure if that was my mistake in how i used labelclear (maybe i overread something),  why had the partion tables been removed when there (i assume) was only some zfs information at the end or the middle of the disk ?

**Comment by mailinglists35** [comment] 2017-06-23 20:23
you did not provide the commands you used nor the output you got.
you deliberately deleted the issue template you were shown when accessing the 'new issue' button.

how do you expect someone to help you?

**Comment by rlaager** [comment] 2017-06-23 20:58
I can confirm that `zpool labelclear /dev/sdb` deletes not only the partitions on the disk, but the partition label as well. This is true even if there is no valid ZFS information on the disk.

Personally, I wouldn't intentionally run `zpool labelclear` or `mdadm --zero-superblock` on a disk with valid data and expect it to be safe.

@devZer0 Are you asking for 1) the man page to be more clear that this destroys data, 2) `zpool labelclear` to only clear ZFS uberblocks (and only if valid unless forced), both, or something else?

**Comment by richardelling** [comment] 2017-06-24 01:26
This seems defective. The reason the ZFS label skips the first 8KB is to avoid clobbering SMI labels. I'm not certain where all of the other labels write their data, but in any case zpool labelclear should not touch the first 8KB either.

**Comment by devZer0** [comment] 2017-11-22 18:34
@rlaager - yes, i`m asking that the manpage be more clear on what labelclear does and that it`s an dangerous operation with the current implementation. i don`t see the point that blocks from the start of the disk getting wiped when zfs pool info was found via scanning at the _end_ of the disk. as i told i already had cleaerd the disk from beginning and re-partitioned/reformatted (without zfs) and a stale pool was found by zfs kernel module as there still was information at the END of the disk which not yet had been wiped or allocated/overwritten with new partition. it seems labelclear just is just a really dumb operation.  

zpool labelclear should only overwrite some disk region where real zfs data structures reside or if --force is being used and you know what this means. 

i would consider this a bug.

if i would use fdisk and delete a partition, i would be really suprised if suddenly mbr was missing, too...

**Comment by GregorKopka** [comment] 2017-11-23 16:39
I see merit in the suggestion for zpool labelclear to only remove actual (valid) labels instead of mindlessly dd'ing /dev/zero over fixed areas calculated from the geometry of the specified block device.

It would at least prevent accidental data loss in case a wrong device is specified (be it a missing -part? or a missing partition number when using /dev/sd? syntax), it would also be closer to the advertised function of 
> Removes ZFS label information from the specified device.  The  device  must
> not be part of an active pool configuration.

This should IMHO be fixed in the code, not in the man page.

**Comment by kpande** [comment] 2017-11-23 18:06
this is an invalid label, though, not a valid label..

**Comment by devZer0** [comment] 2017-11-24 12:43
what's your definition of "invalid" ?  how can it be invalid if zpool import does find it and keeps me from creating a new pool with the same name for example ?

see https://forums.freebsd.org/threads/55336/ which describes a similar case. 

if there is zfs label information on a disk at a "special" position it can't be up to the end-user to directly fiddle with dd & data blocks at the end of the disk to get rid of such information. 

if i create a file with "touch /file" then it's being added via kernel to the filesysteme and with "rm /file" i can remove it. i do not edit filesystem raw structures on disk to remove that file .  so i expect "zpool labelclear" to be the rm command for zfs label information. rm removes a file and does not touch other data structures on disk. zpool labelclear should remove zfs labels and should not touch other data structures on disk.

**Closed** 2019-03-21 17:13 UTC
