### ISSUE TITLE
write errors after upgrade to 0.6.5.9

### ISSUE THREAD

**Issue by rpgordon** [zfsonlinux/zfs#5861] opened 2017-03-05 15:48 UTC
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Linux Mint
Distribution Version    | 17.1 MATE
Linux Kernel                 | 3.13.0-37 (3.13.11.7)
Architecture                 | amd64
ZFS Version                  | 0.6.5.9-1~trusty
SPL Version                  | 0.6.5.9-1~trusty

### Describe the problem you're observing
Summary:
Write errors when writing to mounted encrypted file containers stored in ZFS datasets.

Details:
For a few years, I've been using several zfs datasets on a single zpool for data storage (not my system partitions) on Linux Mint 17.1.  In February I upgraded zfs-linux and spl-linux through the regular Update Manager from version 0.6.5.8-1\~trusty to 0.6.5.9-1\~trusty.

In most circumstances, read and write access to the zfs datasets was fine after the update, as far as I can tell.  However, I have several old Truecrypt encrypted file containers stored on the zfs file system, and I quickly noticed that when I mount these, I experience all sorts of write errors on the mounted Truecrypt file systems.  The Truecrypt file system is FAT32.  When I save an existing file to the TC volume, I  sometimes get write or IO errors, depending on the application, and sometimes just silence, but the changes are never saved.  I can create blank files in the TC volumes, but can't write to the new files.  When I copy files to the Truecrypt volume, they subsequently disappear.  When I dismount and remount the Truecrypt volume, all changes are gone.

I know that these issues are related to the zfs update, because the update is the only change that I made since I used these TC volumes successfully.  And, through some trouble shooting, I found I can use the TC volumes fine if I copy them to a non-zfs filesystem.  So the TC volumes are not corrupted.  If I create a new TC volume in the zfs system, I get the same problems, while if I create a new TC volume in a non-zfs system, I don't have problems.  Same problems with Ext4-formatted TC volumes

I kind of panicked when this all happened, so I quickly fixed the issues by removing all the zfs and spl packages, and reinstalling the 0.6.5.8 versions from my apt cache.  I didn't save any error logs or messages (and don't really know where these would be, anyway).  So I would have to do some snapshotting (of my system partition) and testing to recreate the problems.  Right now, everything seems to be working fine after reverting to 0.6.5.8.

Please let me know what else I can do to help identify and fix this issue.
### Describe how to reproduce the problem
Create an encrypted Truecrypt file container on a zfs dataset.  Mount the file container using Truecrypt.  Try to write to the mounted Truecrypt volume.

**Comment by behlendorf** [comment] 2017-03-06 18:53
@rpgordon thanks for the clear bug report.  The issue here is that loopback devices created on top of ZFS will become read-only due to check in the loopback driver.  So there's no risk to the data.  This regression was accidentally introduced by commit 933ec99 which was merged for 0.6.5.9 to address an rlimit enforcement issue.  This loopback issue was fixed with #5855 which was recently applied to master and we'll get the fix applied for 0.6.5.10.

For the moment I'd suggest using 0.6.5.8 until 0.6.5.10 is tagged.  Or if you need to run 0.6.5.9 you can cherry pick the fix 7a789346afec87a89c4cde465faf9be4996db556.

**Comment by rpgordon** [comment] 2017-03-07 03:00
Many thanks for the reply and succinct explanation.  I'm glad you guys are on it!

**Comment by behlendorf** [comment] 2017-03-07 17:44
Closed as duplicate of  #5855

**Closed by behlendorf** 2017-03-07 17:44 UTC
