### ISSUE TITLE
/etc/sysconfig/zfs overlay option has changed

### ISSUE THREAD

**Issue by tjikkun** [zfsonlinux/zfs#3782] opened 2015-09-15 14:02 UTC
In commit 2a34db1bdbcecf5019c4a59f2a44c92fe82010f2 the option that has to be set in /etc/sysconfig/zfs to allow overlay mounts has changed. It used to be: DO_OVERLAY_MOUNTS=1 but now it is OVERLAY_MOUNTS=yes
What makes it extra confusing is that the file now lists DO_OVERLAY_MOUNTS='no' by default.
Changing this to yes doesn't work, you actually need to change it to OVERLAY_MOUNTS='yes'

**Comment by FransUrbo** [comment] 2015-09-15 17:31
Oups! Don't know why I missed that. Fixed in #3559 (which also includes a whole bunch of other fixes as well) which I hope @behlendorf can have time to review quite soon.

**Comment by behlendorf** [comment] 2015-09-21 22:44
@FransUrbo since we're definitely going to have another 0.6.5.x point release let's try and cherry-pick some of the important smaller issues in that tag.  I also want to try and get #3559 merged fairly early to master so we can shake it out as much as possible.

**Comment by FransUrbo** [comment] 2015-09-22 07:34
Ok, sounds good. Should I use my best judgement of what to cherry-pick (only [very] important stuff of course), or do you have a list?

Do you want those cherry-picks in separate commits, or as one?


Simplest might be that I use my best judgement, create one commit for each and do a PR with that and we can talk about what to keep and what not to… ?

**Comment by FransUrbo** [comment] 2015-09-22 10:46
Ok, created my PR for this. This also contains a couple of things that isn't really a big problem, but needs to be fixed sooner or later. I'm all for for leaving some of them for "Phase 2". Just let me know which ones we should keep for the point release (and if they're good), then I'll remove the ones we don't want/need in the point release and rebase into one commit.

Or you can do that in the merge, @behlendorf. I'll rebase "Phase 2" against whatever ends up in 'master' so we don't loose anything.

**Comment by behlendorf** [comment] 2015-09-24 00:04
@FransUrbo sounds good.  I don't have a full list of issues so by all means let's go with your best judgement.  I should be able to look over the proposed fixed tomorrow, I've been focusing on some of the other regressions which have been uncovered.

**Comment by FransUrbo** [comment] 2015-09-30 00:48
@behlendorf @nedbass This could be closed because of the merge of my cherry-pick PR. If @nedbass want to wait to close it until he's merged it into the point release, I'm fine with it. But I consider this issue closed...

**Comment by behlendorf** [comment] 2015-09-30 16:45
Yup, closing.

**Closed by behlendorf** 2015-09-30 16:45 UTC
Labels: Bug - Minor
