### ISSUE TITLE
zpool import is very slow

### ISSUE THREAD

**Issue by osd1000** [zfsonlinux/zfs#4493] opened 2016-04-06 13:39 UTC
ZFS version: 0.6.5.5-1~trusty

I have a large pool composed of 2x5-disk raidz2 vdevs and a couple of spares, on which there are c.2000 zfses.

```
  pool: local
 state: ONLINE
  scan: none requested
config:

        NAME        STATE     READ WRITE CKSUM
        local       ONLINE       0     0     0
          raidz2-0  ONLINE       0     0     0
            sda     ONLINE       0     0     0
            sdb     ONLINE       0     0     0
            sdc     ONLINE       0     0     0
            sdd     ONLINE       0     0     0
            sde     ONLINE       0     0     0
          raidz2-1  ONLINE       0     0     0
            sdf     ONLINE       0     0     0
            sdg     ONLINE       0     0     0
            sdh     ONLINE       0     0     0
            sdi     ONLINE       0     0     0
            sdj     ONLINE       0     0     0
        spares
          sdk       AVAIL
          sdl       AVAIL

errors: No known data errors
```

zpool import -N local seems to take 6-13 minutes to complete.  I've tried pointing it at a cache file with -c and at a directory full of devices using -d but neither of these seems to make any difference to the run time.

However, the pool seems to become ONLINE (such that one can zfs mount filesets) very quickly after the zpool import command starts, so what's zpool import doing for all that time?  Is there a way of telling it to finish sooner?

**Comment by behlendorf** [comment] 2016-04-06 17:04
This could be caused by zvol minor creation if your pool contains a large number of volumes.  This has been made asynchronous in 0.6.5.6 which may improve your performance considerably.

If that's not the problem then it would be helpful if you could post in a backtrace for the `zpool import -N` command while it's running.

```
cat /proc/<zpool-import-pid>/stack
```

**Comment by osd1000** [comment] 2016-04-07 08:56
On Wednesday, 6 Apr 2016, Brian Behlendorf wrote:

> This could be caused by zvol minor creation if your pool contains a
> large number of volumes.  This has been made asynchronous in 0.6.5.6
> which may improve your performance considerably.

My pool contains no zvols, so I don't think it's that (or at least not
directly)

However, 0.6.5.6 reduces zpool import -N to about 12s, which is a huge
improvement.  Thanks!

(S)
-- 
`Touch can bring blossom to things that decay.'

**Comment by behlendorf** [comment] 2016-04-07 16:43
@osd1000 great, then it sounds like we can close this out.  Definitely let us know if you observe this problem again with the latest release.

**Closed by behlendorf** 2016-04-07 16:43 UTC
