### ISSUE TITLE
ZFS Invalid mode: 0x50 - SPL PANIC

### ISSUE THREAD

**Issue by greg-hydrogen** [zfsonlinux/zfs#2343] opened 2014-05-18 17:17 UTC
Hello Everyone,

Not sure if this should go in the SPL issue tracker rather than ZFS so feel free to move it.

Running on the lastest HEAD I am receiving this error on a Fedora 20 (x64) running the latest kernel 3.14.4-20

I was able to capture both stacks from two different circumstances 

first stack is from the Fedora box:

May 18 11:32:03 localhost kernel: [ 3457.431066] ZFS: Invalid mode: 0x50
May 18 11:32:03 localhost kernel: [ 3457.431070] VERIFY(0) failed
May 18 11:32:03 localhost kernel: [ 3457.431074] SPLError: 9457:0:(zfs_znode.c:340:zfs_inode_set_ops()) SPL PANIC
May 18 11:32:03 localhost kernel: [ 3457.431075] SPL: Showing stack for process 9457
May 18 11:32:03 localhost kernel: [ 3457.431080] CPU: 6 PID: 9457 Comm: mandb Tainted: PF          O 3.14.4-200.fc20.x86_64 #1
May 18 11:32:03 localhost kernel: [ 3457.431082] Hardware name: To be filled by O.E.M. To be filled by O.E.M./M5A97, BIOS 1208 04/18/2012
May 18 11:32:03 localhost kernel: [ 3457.431083]  0000000000000000 000000008a4d5e5e ffff88051792f7d8 ffffffff816ef1d2
May 18 11:32:03 localhost kernel: [ 3457.431090]  0000000000000000 ffff88051792f7e8 ffffffffa00004b7 ffff88051792f810
May 18 11:32:03 localhost kernel: [ 3457.431096]  ffffffffa00016d8 ffffffffa00157c1 000000000000000a ffff880513690040
May 18 11:32:03 localhost kernel: [ 3457.431099] Call Trace:
May 18 11:32:03 localhost kernel: [ 3457.431108]  [<ffffffff816ef1d2>] dump_stack+0x45/0x56
May 18 11:32:03 localhost kernel: [ 3457.431132]  [<ffffffffa00004b7>] spl_debug_dumpstack+0x27/0x40 [spl]
May 18 11:32:03 localhost kernel: [ 3457.431141]  [<ffffffffa00016d8>] spl_debug_bug+0x78/0xe0 [spl]
May 18 11:32:03 localhost kernel: [ 3457.431184]  [<ffffffffa014662c>] zfs_znode_alloc+0x48c/0x5a0 [zfs]
May 18 11:32:03 localhost kernel: [ 3457.431215]  [<ffffffffa01489c1>] zfs_zget+0x181/0x1f0 [zfs]
May 18 11:32:03 localhost kernel: [ 3457.431243]  [<ffffffffa01260a6>] zfs_dirent_lock+0x446/0x580 [zfs]
May 18 11:32:03 localhost kernel: [ 3457.431274]  [<ffffffffa0126270>] zfs_dirlook+0x90/0x380 [zfs]
May 18 11:32:03 localhost kernel: [ 3457.431292]  [<ffffffffa00b7db5>] ? dbuf_dirty+0x3d5/0x850 [zfs]
May 18 11:32:03 localhost kernel: [ 3457.431323]  [<ffffffffa013cf36>] zfs_lookup+0x306/0x360 [zfs]
May 18 11:32:03 localhost kernel: [ 3457.431353]  [<ffffffffa0157d03>] zpl_lookup+0x93/0x100 [zfs]
May 18 11:32:03 localhost kernel: [ 3457.431357]  [<ffffffff811f34fd>] lookup_real+0x1d/0x50
May 18 11:32:03 localhost kernel: [ 3457.431359]  [<ffffffff811f3e32>] __lookup_hash+0x42/0x60
May 18 11:32:03 localhost kernel: [ 3457.431362]  [<ffffffff816edcd7>] lookup_slow+0x42/0xa7
May 18 11:32:03 localhost kernel: [ 3457.431365]  [<ffffffff811f64fd>] path_lookupat+0x73d/0x7a0
May 18 11:32:03 localhost kernel: [ 3457.431368]  [<ffffffff811cc975>] ? kmem_cache_alloc+0x35/0x1f0
May 18 11:32:03 localhost kernel: [ 3457.431370]  [<ffffffff811f4e1f>] ? getname_flags+0x4f/0x1a0
May 18 11:32:03 localhost kernel: [ 3457.431373]  [<ffffffff811f658b>] filename_lookup+0x2b/0xc0
May 18 11:32:03 localhost kernel: [ 3457.431376]  [<ffffffff811fa507>] user_path_at_empty+0x67/0xc0
May 18 11:32:03 localhost kernel: [ 3457.431380]  [<ffffffff811174a2>] ? from_kgid_munged+0x12/0x20
May 18 11:32:03 localhost kernel: [ 3457.431383]  [<ffffffff811eea9f>] ? cp_new_stat+0x14f/0x180
May 18 11:32:03 localhost kernel: [ 3457.431385]  [<ffffffff811fa571>] user_path_at+0x11/0x20
May 18 11:32:03 localhost kernel: [ 3457.431388]  [<ffffffff811ee593>] vfs_fstatat+0x63/0xc0
May 18 11:32:03 localhost kernel: [ 3457.431391]  [<ffffffff811eeb61>] SYSC_newlstat+0x31/0x60
May 18 11:32:03 localhost kernel: [ 3457.431394]  [<ffffffff81121c76>] ? __audit_syscall_exit+0x1f6/0x2a0
May 18 11:32:03 localhost kernel: [ 3457.431397]  [<ffffffff811eedde>] SyS_newlstat+0xe/0x10
May 18 11:32:03 localhost kernel: [ 3457.431400]  [<ffffffff816ff569>] system_call_fastpath+0x16/0x1b
May 18 11:32:03 localhost kernel: ZFS: Invalid mode: 0x50
May 18 11:32:03 localhost kernel: VERIFY(0) failed
May 18 11:32:03 localhost kernel: SPLError: 9457:0:(zfs_znode.c:340:zfs_inode_set_ops()) SPL PANIC
May 18 11:32:03 localhost kernel: SPL: Showing stack for process 9457
May 18 11:32:03 localhost kernel: CPU: 6 PID: 9457 Comm: mandb Tainted: PF          O 3.14.4-200.fc20.x86_64 #1
May 18 11:32:03 localhost kernel: Hardware name: To be filled by O.E.M. To be filled by O.E.M./M5A97, BIOS 1208 04/18/2012
May 18 11:32:03 localhost kernel: 0000000000000000 000000008a4d5e5e ffff88051792f7d8 ffffffff816ef1d2
May 18 11:32:03 localhost kernel: 0000000000000000 ffff88051792f7e8 ffffffffa00004b7 ffff88051792f810
May 18 11:32:03 localhost kernel: ffffffffa00016d8 ffffffffa00157c1 000000000000000a ffff880513690040
May 18 11:32:03 localhost kernel: Call Trace:
May 18 11:32:03 localhost kernel: [<ffffffff816ef1d2>] dump_stack+0x45/0x56
May 18 11:32:03 localhost kernel: [<ffffffffa00004b7>] spl_debug_dumpstack+0x27/0x40 [spl]
May 18 11:32:03 localhost kernel: [<ffffffffa00016d8>] spl_debug_bug+0x78/0xe0 [spl]
May 18 11:32:03 localhost kernel: [<ffffffffa014662c>] zfs_znode_alloc+0x48c/0x5a0 [zfs]
May 18 11:32:03 localhost kernel: [<ffffffffa01489c1>] zfs_zget+0x181/0x1f0 [zfs]
May 18 11:32:03 localhost kernel: [<ffffffffa01260a6>] zfs_dirent_lock+0x446/0x580 [zfs]
May 18 11:32:03 localhost kernel: [<ffffffffa0126270>] zfs_dirlook+0x90/0x380 [zfs]
May 18 11:32:03 localhost kernel: [<ffffffffa00b7db5>] ? dbuf_dirty+0x3d5/0x850 [zfs]
May 18 11:32:03 localhost kernel: [<ffffffffa013cf36>] zfs_lookup+0x306/0x360 [zfs]
May 18 11:32:03 localhost kernel: [<ffffffffa0157d03>] zpl_lookup+0x93/0x100 [zfs]
May 18 11:32:03 localhost kernel: [<ffffffff811f34fd>] lookup_real+0x1d/0x50
May 18 11:32:03 localhost kernel: [<ffffffff811f3e32>] __lookup_hash+0x42/0x60
May 18 11:32:03 localhost kernel: [<ffffffff816edcd7>] lookup_slow+0x42/0xa7
May 18 11:32:03 localhost kernel: [<ffffffff811f64fd>] path_lookupat+0x73d/0x7a0
May 18 11:32:03 localhost kernel: [<ffffffff811cc975>] ? kmem_cache_alloc+0x35/0x1f0
May 18 11:32:03 localhost kernel: [<ffffffff811f4e1f>] ? getname_flags+0x4f/0x1a0
May 18 11:32:03 localhost kernel: [<ffffffff811f658b>] filename_lookup+0x2b/0xc0
May 18 11:32:03 localhost kernel: [<ffffffff811fa507>] user_path_at_empty+0x67/0xc0
May 18 11:32:03 localhost kernel: [<ffffffff811174a2>] ? from_kgid_munged+0x12/0x20
May 18 11:32:03 localhost kernel: [<ffffffff811eea9f>] ? cp_new_stat+0x14f/0x180
May 18 11:32:03 localhost kernel: [<ffffffff811fa571>] user_path_at+0x11/0x20
May 18 11:32:03 localhost kernel: [<ffffffff811ee593>] vfs_fstatat+0x63/0xc0
May 18 11:32:03 localhost kernel: [<ffffffff811eeb61>] SYSC_newlstat+0x31/0x60
May 18 11:32:03 localhost kernel: [<ffffffff81121c76>] ? __audit_syscall_exit+0x1f6/0x2a0
May 18 11:32:03 localhost kernel: [<ffffffff811eedde>] SyS_newlstat+0xe/0x10
May 18 11:32:03 localhost kernel: [<ffffffff816ff569>] system_call_fastpath+0x16/0x1b

Second one is from a chroot environment (from SL 6.5)
May 17 12:21:48 greg-lnxworkstn kernel: ZFS: Invalid mode: 0x2c
May 17 12:21:48 greg-lnxworkstn kernel: VERIFY(0) failed
May 17 12:21:48 greg-lnxworkstn kernel: SPLError: 7318:0:(zfs_znode.c:340:zfs_inode_set_ops()) SPL PANIC
May 17 12:21:48 greg-lnxworkstn kernel: SPL: Showing stack for process 7318
May 17 12:21:48 greg-lnxworkstn kernel: CPU: 3 PID: 7318 Comm: systemctl Tainted: P           O 3.14.1 #1
May 17 12:21:48 greg-lnxworkstn kernel: Hardware name: To be filled by O.E.M. To be filled by O.E.M./M5A97, BIOS 1208 04/18/2012
May 17 12:21:48 greg-lnxworkstn kernel: ffff88065b666580 ffff88065ba6b7a8 ffffffff815ae9f8 ffffffff81db0840
May 17 12:21:48 greg-lnxworkstn kernel: 0000000000000000 ffff88065ba6b7b8 ffffffffa00895a7 ffff88065ba6b7f8
May 17 12:21:48 greg-lnxworkstn kernel: ffffffffa008ac9a ffffffffa009ee8c ffff88083eccd1e8 ffff88083eccecf0
May 17 12:21:48 greg-lnxworkstn kernel: Call Trace:
May 17 12:21:48 greg-lnxworkstn kernel: [<ffffffff815ae9f8>] dump_stack+0x49/0x61
May 17 12:21:48 greg-lnxworkstn kernel: [<ffffffffa00895a7>] spl_debug_dumpstack+0x27/0x40 [spl]
May 17 12:21:48 greg-lnxworkstn kernel: [<ffffffffa008ac9a>] spl_debug_bug+0x7a/0xe0 [spl]
May 17 12:21:48 greg-lnxworkstn kernel: [<ffffffffa021c503>] zfs_inode_set_ops+0x83/0x180 [zfs]
May 17 12:21:48 greg-lnxworkstn kernel: [<ffffffffa021dfdf>] zfs_znode_alloc+0x2cf/0x3d0 [zfs]
May 17 12:21:48 greg-lnxworkstn kernel: [<ffffffffa0194de1>] ? dmu_object_info_from_dnode+0x91/0xf0 [zfs]
May 17 12:21:48 greg-lnxworkstn kernel: [<ffffffffa021e258>] zfs_zget+0x178/0x1e0 [zfs]
May 17 12:21:48 greg-lnxworkstn kernel: [<ffffffffa01f54de>] ? zap_lookup_norm+0xbe/0x190 [zfs]
May 17 12:21:48 greg-lnxworkstn kernel: [<ffffffffa01fe292>] zfs_dirent_lock+0x482/0x550 [zfs]
May 17 12:21:48 greg-lnxworkstn kernel: [<ffffffffa01fe56b>] zfs_dirlook+0x8b/0x270 [zfs]
May 17 12:21:48 greg-lnxworkstn kernel: [<ffffffffa01f88c0>] ? zfs_zaccess+0xa0/0x2d0 [zfs]
May 17 12:21:48 greg-lnxworkstn kernel: [<ffffffff815b1216>] ? mutex_lock+0x16/0x40
May 17 12:21:48 greg-lnxworkstn kernel: [<ffffffffa02182ae>] zfs_lookup+0x2ee/0x340 [zfs]
May 17 12:21:48 greg-lnxworkstn kernel: [<ffffffffa022d878>] zpl_lookup+0x78/0xe0 [zfs]
May 17 12:21:48 greg-lnxworkstn kernel: [<ffffffff811b343d>] ? d_alloc+0x4d/0x60
May 17 12:21:48 greg-lnxworkstn kernel: [<ffffffff811a6bad>] lookup_real+0x1d/0x60
May 17 12:21:48 greg-lnxworkstn kernel: [<ffffffff811a7168>] __lookup_hash+0x38/0x50
May 17 12:21:48 greg-lnxworkstn kernel: [<ffffffff811aa0ec>] lookup_slow+0x4c/0xc0
May 17 12:21:48 greg-lnxworkstn kernel: [<ffffffff811aaf81>] path_lookupat+0x631/0x6a0
May 17 12:21:48 greg-lnxworkstn kernel: [<ffffffff811ab024>] filename_lookup+0x34/0xc0
May 17 12:21:48 greg-lnxworkstn kernel: [<ffffffff811ac2f9>] user_path_at_empty+0x59/0xa0
May 17 12:21:48 greg-lnxworkstn kernel: [<ffffffff811b65fb>] ? touch_atime+0x5b/0x160
May 17 12:21:48 greg-lnxworkstn kernel: [<ffffffff811a18ee>] SyS_readlinkat+0x5e/0x130
May 17 12:21:48 greg-lnxworkstn kernel: [<ffffffff811a163b>] SyS_readlink+0x1b/0x20
May 17 12:21:48 greg-lnxworkstn kernel: [<ffffffff815bb952>] system_call_fastpath+0x16/0x1b
May 17 12:23:26 greg-lnxworkstn automount[4873]: create_client: hostname lookup failed: Name or service not known
May 17 12:23:26 greg-lnxworkstn automount[4873]: create_client: hostname lookup failed: Name or service not known
May 17 12:23:26 greg-lnxworkstn automount[4873]: get_exports: lookup(hosts): exports lookup failed for Mike's Music
May 17 12:23:26 greg-lnxworkstn automount[4873]: key "Mike's Music" not found in map source(s).
May 17 12:23:27 greg-lnxworkstn automount[4873]: create_client: hostname lookup failed: Name or service not known
May 17 12:23:27 greg-lnxworkstn automount[4873]: create_client: hostname lookup failed: Name or service not known
May 17 12:23:27 greg-lnxworkstn automount[4873]: get_exports: lookup(hosts): exports lookup failed for Robyn Models
May 17 12:23:27 greg-lnxworkstn automount[4873]: key "Robyn Models" not found in map source(s).
May 17 12:24:18 greg-lnxworkstn ntpd[5085]: 0.0.0.0 c612 02 freq_set kernel -2.104 PPM
May 17 12:24:18 greg-lnxworkstn ntpd[5085]: 0.0.0.0 c615 05 clock_sync
May 17 12:24:30 greg-lnxworkstn kernel: INFO: task systemctl:7318 blocked for more than 120 seconds.
May 17 12:24:30 greg-lnxworkstn kernel:      Tainted: P           O 3.14.1 #1
May 17 12:24:30 greg-lnxworkstn kernel: "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
May 17 12:24:30 greg-lnxworkstn kernel: systemctl       D ffffffff8161b6c0     0  7318      1 0x00000004
May 17 12:24:30 greg-lnxworkstn kernel: ffff88065ba6b7a8 0000000000000046 ffff88065b666580 ffff88065ba6a010
May 17 12:24:30 greg-lnxworkstn kernel: 0000000000012cc0 0000000000012cc0 ffff880671ba3050 ffff880816aa5150
May 17 12:24:30 greg-lnxworkstn kernel: 0000000000000000 0000000000000000 ffff88065b666580 ffff880709b04000
May 17 12:24:30 greg-lnxworkstn kernel: Call Trace:
May 17 12:24:30 greg-lnxworkstn kernel: [<ffffffff815af989>] schedule+0x29/0x70
May 17 12:24:30 greg-lnxworkstn kernel: [<ffffffffa008accd>] spl_debug_bug+0xad/0xe0 [spl]
May 17 12:24:30 greg-lnxworkstn kernel: [<ffffffffa021c503>] zfs_inode_set_ops+0x83/0x180 [zfs]
May 17 12:24:30 greg-lnxworkstn kernel: [<ffffffffa021dfdf>] zfs_znode_alloc+0x2cf/0x3d0 [zfs]
May 17 12:24:30 greg-lnxworkstn kernel: [<ffffffffa0194de1>] ? dmu_object_info_from_dnode+0x91/0xf0 [zfs]
May 17 12:24:30 greg-lnxworkstn kernel: [<ffffffffa021e258>] zfs_zget+0x178/0x1e0 [zfs]
May 17 12:24:30 greg-lnxworkstn kernel: [<ffffffffa01f54de>] ? zap_lookup_norm+0xbe/0x190 [zfs]
May 17 12:24:30 greg-lnxworkstn kernel: [<ffffffffa01fe292>] zfs_dirent_lock+0x482/0x550 [zfs]
May 17 12:24:30 greg-lnxworkstn kernel: [<ffffffffa01fe56b>] zfs_dirlook+0x8b/0x270 [zfs]
May 17 12:24:30 greg-lnxworkstn kernel: [<ffffffffa01f88c0>] ? zfs_zaccess+0xa0/0x2d0 [zfs]
May 17 12:24:30 greg-lnxworkstn kernel: [<ffffffff815b1216>] ? mutex_lock+0x16/0x40
May 17 12:24:30 greg-lnxworkstn kernel: [<ffffffffa02182ae>] zfs_lookup+0x2ee/0x340 [zfs]
May 17 12:24:30 greg-lnxworkstn kernel: [<ffffffffa022d878>] zpl_lookup+0x78/0xe0 [zfs]
May 17 12:24:30 greg-lnxworkstn kernel: [<ffffffff811b343d>] ? d_alloc+0x4d/0x60
May 17 12:24:30 greg-lnxworkstn kernel: [<ffffffff811a6bad>] lookup_real+0x1d/0x60
May 17 12:24:30 greg-lnxworkstn kernel: [<ffffffff811a7168>] __lookup_hash+0x38/0x50
May 17 12:24:30 greg-lnxworkstn kernel: [<ffffffff811aa0ec>] lookup_slow+0x4c/0xc0
May 17 12:24:30 greg-lnxworkstn kernel: [<ffffffff811aaf81>] path_lookupat+0x631/0x6a0
May 17 12:24:30 greg-lnxworkstn kernel: [<ffffffff811ab024>] filename_lookup+0x34/0xc0
May 17 12:24:30 greg-lnxworkstn kernel: [<ffffffff811ac2f9>] user_path_at_empty+0x59/0xa0
May 17 12:24:30 greg-lnxworkstn kernel: [<ffffffff811b65fb>] ? touch_atime+0x5b/0x160
May 17 12:24:30 greg-lnxworkstn kernel: [<ffffffff811a18ee>] SyS_readlinkat+0x5e/0x130
May 17 12:24:30 greg-lnxworkstn kernel: [<ffffffff811a163b>] SyS_readlink+0x1b/0x20
May 17 12:24:30 greg-lnxworkstn kernel: [<ffffffff815bb952>] system_call_fastpath+0x16/0x1b
May 17 12:26:30 greg-lnxworkstn kernel: INFO: task systemctl:7318 blocked for more than 120 seconds.
May 17 12:26:30 greg-lnxworkstn kernel:      Tainted: P           O 3.14.1 #1
May 17 12:26:30 greg-lnxworkstn kernel: "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
May 17 12:26:30 greg-lnxworkstn kernel: systemctl       D ffffffff8161b6c0     0  7318      1 0x00000004
May 17 12:26:30 greg-lnxworkstn kernel: ffff88065ba6b7a8 0000000000000046 ffff88065b666580 ffff88065ba6a010
May 17 12:26:30 greg-lnxworkstn kernel: 0000000000012cc0 0000000000012cc0 ffff880671ba3050 ffff880816aa5150
May 17 12:26:30 greg-lnxworkstn kernel: 0000000000000000 0000000000000000 ffff88065b666580 ffff880709b04000
May 17 12:26:30 greg-lnxworkstn kernel: Call Trace:
May 17 12:26:30 greg-lnxworkstn kernel: [<ffffffff815af989>] schedule+0x29/0x70
May 17 12:26:30 greg-lnxworkstn kernel: [<ffffffffa008accd>] spl_debug_bug+0xad/0xe0 [spl]
May 17 12:26:30 greg-lnxworkstn kernel: [<ffffffffa021c503>] zfs_inode_set_ops+0x83/0x180 [zfs]
May 17 12:26:30 greg-lnxworkstn kernel: [<ffffffffa021dfdf>] zfs_znode_alloc+0x2cf/0x3d0 [zfs]
May 17 12:26:30 greg-lnxworkstn kernel: [<ffffffffa0194de1>] ? dmu_object_info_from_dnode+0x91/0xf0 [zfs]
May 17 12:26:30 greg-lnxworkstn kernel: [<ffffffffa021e258>] zfs_zget+0x178/0x1e0 [zfs]
May 17 12:26:30 greg-lnxworkstn kernel: [<ffffffffa01f54de>] ? zap_lookup_norm+0xbe/0x190 [zfs]
May 17 12:26:30 greg-lnxworkstn kernel: [<ffffffffa01fe292>] zfs_dirent_lock+0x482/0x550 [zfs]
May 17 12:26:30 greg-lnxworkstn kernel: [<ffffffffa01fe56b>] zfs_dirlook+0x8b/0x270 [zfs]
May 17 12:26:30 greg-lnxworkstn kernel: [<ffffffffa01f88c0>] ? zfs_zaccess+0xa0/0x2d0 [zfs]
May 17 12:26:30 greg-lnxworkstn kernel: [<ffffffff815b1216>] ? mutex_lock+0x16/0x40
May 17 12:26:30 greg-lnxworkstn kernel: [<ffffffffa02182ae>] zfs_lookup+0x2ee/0x340 [zfs]
May 17 12:26:30 greg-lnxworkstn kernel: [<ffffffffa022d878>] zpl_lookup+0x78/0xe0 [zfs]
May 17 12:26:30 greg-lnxworkstn kernel: [<ffffffff811b343d>] ? d_alloc+0x4d/0x60
May 17 12:26:30 greg-lnxworkstn kernel: [<ffffffff811a6bad>] lookup_real+0x1d/0x60
May 17 12:26:30 greg-lnxworkstn kernel: [<ffffffff811a7168>] __lookup_hash+0x38/0x50
May 17 12:26:30 greg-lnxworkstn kernel: [<ffffffff811aa0ec>] lookup_slow+0x4c/0xc0
May 17 12:26:30 greg-lnxworkstn kernel: [<ffffffff811aaf81>] path_lookupat+0x631/0x6a0
May 17 12:26:30 greg-lnxworkstn kernel: [<ffffffff811ab024>] filename_lookup+0x34/0xc0
May 17 12:26:30 greg-lnxworkstn kernel: [<ffffffff811ac2f9>] user_path_at_empty+0x59/0xa0
May 17 12:26:30 greg-lnxworkstn kernel: [<ffffffff811b65fb>] ? touch_atime+0x5b/0x160
May 17 12:26:30 greg-lnxworkstn kernel: [<ffffffff811a18ee>] SyS_readlinkat+0x5e/0x130
May 17 12:26:30 greg-lnxworkstn kernel: [<ffffffff811a163b>] SyS_readlink+0x1b/0x20
May 17 12:26:30 greg-lnxworkstn kernel: [<ffffffff815bb952>] system_call_fastpath+0x16/0x1b
May 17 12:26:30 greg-lnxworkstn kernel: INFO: task yum:7434 blocked for more than 120 seconds.
May 17 12:26:30 greg-lnxworkstn kernel:      Tainted: P           O 3.14.1 #1
May 17 12:26:30 greg-lnxworkstn kernel: "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
May 17 12:26:30 greg-lnxworkstn kernel: yum             D ffffffff8161b6c0     0  7434   7367 0x00000004
May 17 12:26:30 greg-lnxworkstn kernel: ffff88072d4c98b8 0000000000000046 0000000000000000 ffff88072d4c8010
May 17 12:26:30 greg-lnxworkstn kernel: 0000000000012cc0 0000000000012cc0 ffff88065d2ff050 ffff880816aa5150
May 17 12:26:30 greg-lnxworkstn kernel: 0000000000000000 ffff880709b05390 ffff88065d2ff050 ffff880709b05394
May 17 12:26:30 greg-lnxworkstn kernel: Call Trace:
May 17 12:26:30 greg-lnxworkstn kernel: [<ffffffff815af989>] schedule+0x29/0x70
May 17 12:26:30 greg-lnxworkstn kernel: [<ffffffff815afaee>] schedule_preempt_disabled+0xe/0x10
May 17 12:26:30 greg-lnxworkstn kernel: [<ffffffff815b1163>] __mutex_lock_slowpath+0x183/0x220
May 17 12:26:30 greg-lnxworkstn kernel: [<ffffffffa018bee9>] ? dbuf_rele_and_unlock+0x169/0x220 [zfs]
May 17 12:26:30 greg-lnxworkstn kernel: [<ffffffff815b1223>] mutex_lock+0x23/0x40
May 17 12:26:30 greg-lnxworkstn kernel: [<ffffffffa021e1db>] zfs_zget+0xfb/0x1e0 [zfs]
May 17 12:26:30 greg-lnxworkstn kernel: [<ffffffffa01f54de>] ? zap_lookup_norm+0xbe/0x190 [zfs]
May 17 12:26:30 greg-lnxworkstn kernel: [<ffffffffa01fe292>] zfs_dirent_lock+0x482/0x550 [zfs]
May 17 12:26:30 greg-lnxworkstn kernel: [<ffffffffa01fe56b>] zfs_dirlook+0x8b/0x270 [zfs]
May 17 12:26:30 greg-lnxworkstn kernel: [<ffffffffa01f88c0>] ? zfs_zaccess+0xa0/0x2d0 [zfs]
May 17 12:26:30 greg-lnxworkstn kernel: [<ffffffff815b1216>] ? mutex_lock+0x16/0x40
May 17 12:26:30 greg-lnxworkstn kernel: [<ffffffffa02182ae>] zfs_lookup+0x2ee/0x340 [zfs]
May 17 12:26:30 greg-lnxworkstn kernel: [<ffffffffa022d878>] zpl_lookup+0x78/0xe0 [zfs]
May 17 12:26:30 greg-lnxworkstn kernel: [<ffffffff811b343d>] ? d_alloc+0x4d/0x60
May 17 12:26:30 greg-lnxworkstn kernel: [<ffffffff811a6bad>] lookup_real+0x1d/0x60
May 17 12:26:30 greg-lnxworkstn kernel: [<ffffffff811a7168>] __lookup_hash+0x38/0x50
May 17 12:26:30 greg-lnxworkstn kernel: [<ffffffff811aa0ec>] lookup_slow+0x4c/0xc0
May 17 12:26:30 greg-lnxworkstn kernel: [<ffffffff811aaf81>] path_lookupat+0x631/0x6a0
May 17 12:26:30 greg-lnxworkstn kernel: [<ffffffff8113c26b>] ? release_pages+0x7b/0x1f0
May 17 12:26:30 greg-lnxworkstn kernel: [<ffffffff811ab024>] filename_lookup+0x34/0xc0
May 17 12:26:30 greg-lnxworkstn kernel: [<ffffffff811ac2f9>] user_path_at_empty+0x59/0xa0
May 17 12:26:30 greg-lnxworkstn kernel: [<ffffffff81155cd8>] ? list_lru_add+0xb8/0x100
May 17 12:26:30 greg-lnxworkstn kernel: [<ffffffff811a1fb9>] ? cp_new_stat+0x149/0x170
May 17 12:26:30 greg-lnxworkstn kernel: [<ffffffff811ac351>] user_path_at+0x11/0x20
May 17 12:26:30 greg-lnxworkstn kernel: [<ffffffff811a1c49>] vfs_fstatat+0x59/0xb0
May 17 12:26:30 greg-lnxworkstn kernel: [<ffffffff811a1d3b>] vfs_stat+0x1b/0x20
May 17 12:26:30 greg-lnxworkstn kernel: [<ffffffff811a20bf>] SYSC_newstat+0x1f/0x50
May 17 12:26:30 greg-lnxworkstn kernel: [<ffffffff811a20fe>] SyS_newstat+0xe/0x10
May 17 12:26:30 greg-lnxworkstn kernel: [<ffffffff815bb952>] system_call_fastpath+0x16/0x1b

I am going to downgrade to an earlier version (april 6) but I can keep around this instance for testing...

Please let me know if you need additional info

Package list:
kmod-spl-3.11.10-301.fc20.x86_64.x86_64 0.6.2-38_gad3412e.fc20          @/kmod-spl-3.11.10-301.fc20.x86_64-0.6.2-38_gad3412e.fc20.x86_64
kmod-spl-3.14.4-200.fc20.x86_64.x86_64 0.6.2-38_gad3412e.fc20          @/kmod-spl-3.14.4-200.fc20.x86_64-0.6.2-38_gad3412e.fc20.x86_64
kmod-spl-devel.x86_64                  0.6.2-38_gad3412e.fc20          @/kmod-spl-devel-0.6.2-38_gad3412e.fc20.x86_64
kmod-spl-devel-3.11.10-301.fc20.x86_64.x86_64  0.6.2-38_gad3412e.fc20          @/kmod-spl-devel-3.11.10-301.fc20.x86_64-0.6.2-38_gad3412e.fc20.x86_64
kmod-spl-devel-3.14.4-200.fc20.x86_64.x86_64  0.6.2-38_gad3412e.fc20          @/kmod-spl-devel-3.14.4-200.fc20.x86_64-0.6.2-38_gad3412e.fc20.x86_64
kmod-zfs-3.11.10-301.fc20.x86_64.x86_64 0.6.2-275_gbc25c93.fc20         @/kmod-zfs-3.11.10-301.fc20.x86_64-0.6.2-275_gbc25c93.fc20.x86_64
kmod-zfs-3.14.4-200.fc20.x86_64.x86_64 0.6.2-275_gbc25c93.fc20         @/kmod-zfs-3.14.4-200.fc20.x86_64-0.6.2-275_gbc25c93.fc20.x86_64
kmod-zfs-devel.x86_64                  0.6.2-275_gbc25c93.fc20         @/kmod-zfs-devel-0.6.2-275_gbc25c93.fc20.x86_64
kmod-zfs-devel-3.11.10-301.fc20.x86_64.x86_64 0.6.2-275_gbc25c93.fc20         @/kmod-zfs-devel-3.11.10-301.fc20.x86_64-0.6.2-275_gbc25c93.fc20.x86_64
kmod-zfs-devel-3.14.4-200.fc20.x86_64.x86_64 0.6.2-275_gbc25c93.fc20         @/kmod-zfs-devel-3.14.4-200.fc20.x86_64-0.6.2-275_gbc25c93.fc20.x86_64
spl.x86_64                             0.6.2-38_gad3412e.fc20          @/spl-0.6.2-38_gad3412e.fc20.x86_64
spl-debuginfo.x86_64                   0.6.2-38_gad3412e.fc20          @/spl-debuginfo-0.6.2-38_gad3412e.fc20.x86_64
spl-kmod-debuginfo.x86_64              0.6.2-38_gad3412e.fc20          @/spl-kmod-debuginfo-0.6.2-38_gad3412e.fc20.x86_64
zfs.x86_64                             0.6.2-275_gbc25c93.fc20         @/zfs-0.6.2-275_gbc25c93.fc20.x86_64
zfs-debuginfo.x86_64                   0.6.2-275_gbc25c93.fc20         @/zfs-debuginfo-0.6.2-275_gbc25c93.fc20.x86_64
zfs-devel.x86_64                       0.6.2-275_gbc25c93.fc20         @/zfs-devel-0.6.2-275_gbc25c93.fc20.x86_64
zfs-dracut.x86_64                      0.6.2-275_gbc25c93.fc20         @/zfs-dracut-0.6.2-275_gbc25c93.fc20.x86_64
zfs-kmod-debuginfo.x86_64              0.6.2-275_gbc25c93.fc20         @/zfs-kmod-debuginfo-0.6.2-275_gbc25c93.fc20.x86_64
zfs-test.x86_64                        0.6.2-275_gbc25c93.fc20         @/zfs-test-0.6.2-275_gbc25c93.fc20.x86_64

**Comment by behlendorf** [comment] 2015-02-06 05:39
Hopefully the last SA fix is in #3074 and will be merged for the 0.6.4 tag.  If you're game it would be interesting to run your test case in the VM once 0.6.4 is released or after #3074 is merged.

**Comment by behlendorf** [comment] 2015-02-11 00:23
@greg-hydrogen #3074 has been merged as a62d1b02e372e63862cee276185f2763f641ff10, it address a symlink problem which could cause any issue like this.  Since we've gotten to a reasonable root cause on this issue I'm going to close it out.  However, if you're able to recreate this issue with a new pool on the latest code we can definitely reopen it and have another look.

**Closed by behlendorf** 2015-02-11 00:23 UTC
Labels: Bug - Major, Difficulty - Hard
