### ISSUE TITLE
want resumable zfs send/recv

### ISSUE THREAD

**Issue by rincebrain** [zfsonlinux/zfs#3896] opened 2015-10-07 23:12 UTC
Just a feature request for when this (presumably shortly) gets merged into Illumos, only making it because I didn't see an existing feature request for it...

http://www.slideshare.net/MatthewAhrens/openzfs-send-and-receive
https://www.illumos.org/issues/2605
https://reviews.csiden.org/r/240/

**Comment by kernelOfTruth** [comment] 2015-10-07 23:15
depends on https://github.com/zfsonlinux/zfs/pull/3611 Illumos 5746 more checksumming in zfs send


Sweet !

In code review state already ? :+1:

**Comment by FransUrbo** [comment] 2015-10-08 11:10
My #2668 is a stab at doing something similar.

**Comment by kernelOfTruth** [comment] 2015-10-10 08:00
https://github.com/illumos/illumos-gate/commit/9c3fd1216fa7fb02cfbc78a2518a686d54b48ab8 2605 want to resume interrupted zfs send

**Comment by jimsalterjrs** [comment] 2015-12-17 21:24
@behlendorf , I'm really anxious for this too. Chatted briefly with @ahrens about it in the comments on my latest ZFS article at Ars Technica, and he recommended poking you about ZoL support for resume.  Poke, poke, poke. =)

FWIW, the minute this gets into mainstream ZoL, I'm patching my replication tool [syncoid](https://github.com/jimsalterjrs/sanoid) to take advantage.

**Comment by behlendorf** [comment] 2015-12-18 23:23
It's definitely on the short list.  Our next big push is to sync up with the latest illumos code and pull in all of this functionality and more.  And we're going to be methodical and careful about it to avoid and regressions or destabilization.  But it's certainly coming!

**Comment by kernelOfTruth** [comment] 2016-01-13 23:14
https://github.com/zfsonlinux/zfs/pull/4213

**Comment by greg-hydrogen** [comment] 2016-03-08 23:38
@kernelOfTruth is this stack ready for testing?? I would love to give it a try as it is a feature I have been waiting for a while...

**Comment by kernelOfTruth** [comment] 2016-03-09 11:46
@greg-hydrogen I've just pushed a freshly rebased commit to the repo,

once the (TEST) buildbot runs give green light it should be relatively safe to test,

I however wouldn't use it in production yet since I'm not sure how far the review has progressed until now

CC: @behlendorf

**Comment by pramen** [comment] 2016-08-15 14:34
Hello,

Can I ask about progress?
Is this feature available in any package?

**Comment by kernelOfTruth** [comment] 2016-08-15 16:23
@pramen 

It's included in master starting with June 29th (https://github.com/zfsonlinux/zfs/commits/master?page=3),

the changes are too intrusive to be included in a stable release

so unless the distribution offers "live" or snapshot packages it's out of reach,

and requires manual building

**Comment by behlendorf** [comment] 2016-08-15 18:09
This will be part of the the 0.7.x release.  No distributions I'm aware of are currently shipping this release you'll need to build the latest ZFS from source if you need it.

Thanks for reminding me to close this issue out!

**Closed by behlendorf** 2016-08-15 18:09 UTC
Labels: Feature
