### ISSUE TITLE
archive.zfsonlinux.org does not use TLS

### ISSUE THREAD

**Issue by victoredwardocallaghan** [zfsonlinux/zfs#4541] opened 2016-04-19 00:01 UTC
On the following page [epel](http://zfsonlinux.org/epel.html) there is the URL:
```
http://archive.zfsonlinux.org/epel/zfs-release.el7.noarch.rpm
```
which should use TLS.

You can get a free TLS cert from [Let's Encrypt](https://letsencrypt.org/), after all folks are installing binaries from this URL which do no gpg sig checking so at the very least a TLS session should occur.

Kind Regards,
Edward.

**Comment by DeHackEd** [comment] 2016-04-19 00:57
Duplicate of #4353

**Comment by behlendorf** [comment] 2016-05-11 22:46
Rather than moving the packages from their current location, which is logistically difficult, the public signing keys and package verification commands have been posted [prominently on the wiki](https://github.com/zfsonlinux/zfs/wiki/RHEL-%26-CentOS) which does use TLS.  Users can now more easily validate the zfs-release package.

**Closed by behlendorf** 2016-05-11 22:46 UTC
