### ISSUE TITLE
Starting strace on zfs receive terms the process

### ISSUE THREAD

**Issue by tomassrnka** [zfsonlinux/zfs#4046] opened 2015-11-26 11:20 UTC
We found a strange behaviour on 0.6.5.3+, starting strace -p <pid> on zfs receive process causes the process to terminate.

**Comment by DeHackEd** [comment] 2015-11-26 12:44
Related to #810, the SIGSTOP involved in tracing the process nukes the job.

Send and Receive are (almost) entirely in-kernel operations invoked by a single system call. It can't be interrupted. Forcing the issue makes the job abort.

**Comment by loli10K** [comment] 2018-02-12 20:15
Duplicate of #810

**Closed by loli10K** 2018-02-12 20:15 UTC
