### ISSUE TITLE
zpool add fails with disks referenced by id

### ISSUE THREAD

**Issue by hadees** [zfsonlinux/zfs#4077] opened 2015-12-08 23:13 UTC
@ryao told me to file a bug on this.

I ran the command

`zpool add -f -o ashift=12 tank raidz2 /dev/disk/by-id/ata-WDC_WD30EFRX-68EUZN0_WD-foobar1 /dev/disk/by-id/ata-WDC_WD30EFRX-68EUZN0_WD-foobar2 /dev/disk/by-id/ata-WDC_WD30EFRX-68EUZN0_WD-foobar3 /dev/disk/by-id/ata-WDC_WD30EFRX-68EUZN0_WD-foobar4 /dev/disk/by-id/ata-WDC_WD30EFRX-68EUZN0_WD-foobar5 /dev/disk/by-id/ata-WDC_WD30EFRX-68EUZN0_WD-foobar6 /dev/disk/by-id/ata-WDC_WD30EFRX-68EUZN0_WD-foobar7 /dev/disk/by-id/ata-WDC_WD30EFRX-68EUZN0_WD-foobar8`

It then failed with

`cannot add to 'tank': one or more devices is currently unavailable`

however all the devices were available and it seems to have partitioned them.  Anyway on @dasjoe's advice I reran the command with just regular `/dev/sd*` and it worked.

`zpool add -f -o ashift=12 tank raidz2 /dev/sds /dev/sdt /dev/sdu /dev/sdv /dev/sdw /dev/sdx /dev/sdy /dev/sdz`

After that I was able to export and reimport by id.

According to @dasjoe there seems to be a race condition but he could probably speak more to that than me.  Let me know if you need further information.

**Comment by ryao** [comment] 2015-12-08 23:22
From IRC:

```
22:59 < hadees> For some reason I can't add a new vdev to my pool, it keeps saying "cannot add to 'tank': one or more devices is currently unavailable"
22:59 < hadees> All the devices seem to be there and aren't doing anything
23:00 <+ryao> hadees: What is the command?
23:00 < hadees> zpool add -f -o ashift=12 tank raidz2 /dev/disk/by-id/foobar etc.
23:01 < hadees> ryao: obviously with my own 8 disks at the end
23:01 < hadees> these are new disks if that matters
23:01 < dasjoe> hadees: try with /dev/sdX instead of by-id/
23:02 <+ryao> hadees: This sounds like a bug. 
23:02 < dasjoe> ryao: there seems to be a race condition with udev, I hit it a few days ago
23:02 <+ryao> Which distribution is this?
23:02 < dasjoe> ryao: I *think* by-id/ gets populated too late after zfs puts a GPT on a disk
23:03 < dasjoe> ryao: there are countermeasures against this, but as far as I understand the code ZFS waits until links to /dev/sdX appear, not for -part1 to become available
23:03 < dasjoe> s,code ZFS,code in ZFS,
23:03 -!- Brendon [uid17332@gateway/web/irccloud.com/x-agimfotazvplxjpv] has quit [Quit: Connection closed for inactivity]
23:04 <+ryao> dasjoe: that would be a race and makes sense.
```

**Comment by hadees** [comment] 2015-12-08 23:23
Here is my `zfs get all`

```
NAME  PROPERTY              VALUE                  SOURCE
tank  type                  filesystem             -
tank  creation              Thu Mar  5  0:27 2015  -
tank  used                  29.5T                  -
tank  available             15.4T                  -
tank  referenced            29.5T                  -
tank  compressratio         1.00x                  -
tank  mounted               yes                    -
tank  quota                 none                   default
tank  reservation           none                   default
tank  recordsize            128K                   default
tank  mountpoint            /mnt/raid              local
tank  sharenfs              off                    local
tank  checksum              on                     default
tank  compression           off                    local
tank  atime                 on                     default
tank  devices               on                     default
tank  exec                  on                     default
tank  setuid                on                     default
tank  readonly              off                    default
tank  zoned                 off                    default
tank  snapdir               hidden                 default
tank  aclinherit            restricted             default
tank  canmount              on                     default
tank  xattr                 on                     default
tank  copies                1                      default
tank  version               5                      -
tank  utf8only              off                    -
tank  normalization         none                   -
tank  casesensitivity       sensitive              -
tank  vscan                 off                    default
tank  nbmand                off                    default
tank  sharesmb              off                    default
tank  refquota              none                   default
tank  refreservation        none                   default
tank  primarycache          all                    default
tank  secondarycache        all                    default
tank  usedbysnapshots       0                      -
tank  usedbydataset         29.5T                  -
tank  usedbychildren        2.69G                  -
tank  usedbyrefreservation  0                      -
tank  logbias               latency                default
tank  dedup                 off                    default
tank  mlslabel              none                   default
tank  sync                  standard               default
tank  refcompressratio      1.00x                  -
tank  written               29.5T                  -
tank  logicalused           29.4T                  -
tank  logicalreferenced     29.4T                  -
tank  filesystem_limit      none                   default
tank  snapshot_limit        none                   default
tank  filesystem_count      none                   default
tank  snapshot_count        none                   default
tank  snapdev               hidden                 default
tank  acltype               off                    default
tank  context               none                   default
tank  fscontext             none                   default
tank  defcontext            none                   default
tank  rootcontext           none                   default
tank  relatime              on                     temporary
tank  redundant_metadata    all                    default
tank  overlay               off                    default
```

**Comment by dasjoe** [comment] 2016-03-14 19:21
Actually, duplicate of #3708.

**Closed** 2016-04-25 18:14 UTC

**Comment by jonxor** [comment] 2017-01-27 19:24
I believe this may have been re-introduced as of 0.6.5.6-0ubuntu8 on ubuntu 16.04.
I have a Raidz2 array where a member failed.  When I attempt to replace, it creates the partitions, but then replies with "no such pool or dataset".
I did attempt to reference the old disk by GUID, which had the same issue, but then worked after a few tries.
