### ISSUE TITLE
Unable to mount root fs since upgrading from 0.6.5.1-4-wheezy to 0.6.5.2-1-wheezy

### ISSUE THREAD

**Issue by markdesouza** [zfsonlinux/zfs#3869] opened 2015-10-02 07:29 UTC
During boot, initrd stage fails with:

Command: mount_fs san-rpool/ROOT
Message:
Error: 1

Error: Failed to mount root file system 'san-rpool/ROOT'.

Note I can manually boot the system with:
mount -o zfsutil -t zfs san-rpool/ROOT /root
exit

**Comment by markdesouza** [comment] 2015-10-02 07:34
I presume this relates to  #3816

**Comment by woffs** [comment] 2015-10-02 08:24
I have the same here, but with 0.6.5.2. The root fs is successfully mounted, it seems to be a false error.  Simply pressing ^D continues the boot process. I have set zfsdebug=1 but was not able to get through the logic of zfs-functions.sh yet.

**Comment by markdesouza** [comment] 2015-10-02 10:02
Confirmed. It script falsely reports an error... Attaching a couple screenshots from an affected server

<img width="722" alt="screen shot 2015-10-02 at 8 00 02 pm" src="https://cloud.githubusercontent.com/assets/9853568/10244095/63471500-6940-11e5-8dd2-02680a38bd39.png">
<img width="722" alt="screen shot 2015-10-02 at 8 00 21 pm" src="https://cloud.githubusercontent.com/assets/9853568/10244096/6348fd52-6940-11e5-8ed3-f7c531648148.png">

**Comment by markdesouza** [comment] 2015-10-02 11:06
Digging deaper, It looks like the issue relates to mounting other zfs datasets. Changing line 815 in /etc/zfs/zfs-functions to "return 0" instead of "return 1" fixes the issue. 

**Note:** the structure of the code means that the reported error incorrectly points the users to their being a problem mounting the root file system, as opposed to other datasets ie /var. Prob worth flagging for review

```bash
 797         zfs_action "Mounting '${fs}' on '${rootmnt}/${mountpoint}'" \
 798             "${cmd}" "${fs}" "${rootmnt}/${mountpoint}"
 799         if [ "${ZFS_ERROR}" != 0 ]
 800         then
 801                 disable_plymouth
 802                 if [ "$?" -ne "123" ]; then
 803                         echo ""
 804                         echo "Command: ${ZFS_CMD}"
 805                         echo "Message: ${ZFS_STDERR}"
 806                         echo "Error: ${ZFS_ERROR}"
 807                         echo ""
 808                         echo "Failed to mount ${fs} on ${rootmnt}/${mountpoint}."
 809                         echo "Manually mount the filesystem and exit."
 810                         emergency_shell
 811                 else
 812                         return 1
 813                 fi
 814         else
 815                 return 0
 816         fi
 817 
 818         return 0
 819 }
 820 
```

**Comment by FransUrbo** [comment] 2015-10-02 11:11
Oups! I see it! It's a patch gone wrong and the problem is "everywhere"! I'm building new packages as we speak. Should be available in an hour or so..

Thanx for the assist!

**Comment by markdesouza** [comment] 2015-10-02 11:15
Not a problem. Glad to commit back to the project.

**Comment by RJVB** [comment] 2015-10-02 13:09
Heh, I see I'm not wrong in having 'held' my zfs-initramfs package :)

**Comment by FransUrbo** [comment] 2015-10-04 14:41
@markdesouza Since this is now fixed, can you close this?

**Closed** 2015-10-04 14:42 UTC
Labels: Bug - Minor
