### ISSUE TITLE
Debian packages 

### ISSUE THREAD

**Issue by markdesouza** [zfsonlinux/zfs#4293] opened 2016-01-31 03:48 UTC
The latest release of zfs on linux is 0.6.5.4 but the last debian packages (wheezy & jessie) are for 0.6.5.2-2. Is there a reason why the debian packages are lagging behind the official releases?

**Comment by dasjoe** [comment] 2016-02-02 21:03
Duplicate of https://github.com/zfsonlinux/pkg-zfs/issues/181.

**Comment by rlaager** [comment] 2016-10-01 00:39
If this is about official Debian packages, ask Debian. If this is about unofficial Debian packages, I think the answer is "Debian is packaging it officially now", so ask Debian?

**Closed by rlaager** 2016-10-01 00:39 UTC
