### ISSUE TITLE
txg_sync blocked for 120s

### ISSUE THREAD

**Issue by kpande** [zfsonlinux/zfs#2990] opened 2014-12-26 02:47 UTC
Seen on a system running BackupPC (rsync, trash cleanup jobs, lots of hard links)

[ 8038.216669] INFO: task txg_sync:1351 blocked for more than 120 seconds.
[ 8038.216722]       Tainted: P          IO   3.17.7-vanillabean1 #1
[ 8038.216765] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[ 8038.216836] txg_sync        D 0000000000000004     0  1351      2 0x00000000
[ 8038.216841]  ffff88047cb37be8 0000000000000046 ffff880700000001 ffff880484614110
[ 8038.216846]  0000000000000003 ffff88047cb37fd8 ffff88048065d3d0 0000000000011dc0
[ 8038.216849]  0000000000011dc0 ffff88048065d3d0 0000072ab216962d ffff880497c51dc0
[ 8038.216853] Call Trace:
[ 8038.216864]  [<ffffffff813a3aee>] ? io_schedule+0x5b/0x74
[ 8038.216884]  [<ffffffffa03bad39>] ? cv_wait_common+0xa7/0x103 [spl]
[ 8038.216890]  [<ffffffff8106439d>] ? wake_up_atomic_t+0x22/0x22
[ 8038.216921]  [<ffffffffa06e2fdd>] ? zio_wait+0x116/0x15f [zfs]
[ 8038.216948]  [<ffffffffa0688425>] ? dsl_pool_sync+0xaa/0x39e [zfs]
[ 8038.216979]  [<ffffffffa069c746>] ? spa_sync+0x4d3/0x96b [zfs]
[ 8038.216985]  [<ffffffff810820f3>] ? timekeeping_get_ns_raw.constprop.11+0x11/0x37
[ 8038.216988]  [<ffffffff81082522>] ? getrawmonotonic+0x13/0x4e
[ 8038.217018]  [<ffffffffa06aa470>] ? txg_sync_thread+0x27c/0x4b8 [zfs]
[ 8038.217026]  [<ffffffffa03b7444>] ? spl_kmem_fini+0x6d/0x6d [spl]
[ 8038.217056]  [<ffffffffa06aa1f4>] ? txg_do_callbacks+0x44/0x44 [zfs]
[ 8038.217063]  [<ffffffffa03b7444>] ? spl_kmem_fini+0x6d/0x6d [spl]
[ 8038.217070]  [<ffffffffa03b74ae>] ? thread_generic_wrapper+0x6a/0x75 [spl]
[ 8038.217075]  [<ffffffff81051192>] ? kthread+0x99/0xa1
[ 8038.217079]  [<ffffffff810510f9>] ? __kthread_parkme+0x58/0x58
[ 8038.217083]  [<ffffffff813a646c>] ? ret_from_fork+0x7c/0xb0
[ 8038.217087]  [<ffffffff810510f9>] ? __kthread_parkme+0x58/0x58
[ 8158.182580] INFO: task txg_sync:1351 blocked for more than 120 seconds.
[ 8158.182632]       Tainted: P          IO   3.17.7-vanillabean1 #1
[ 8158.182676] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[ 8158.182746] txg_sync        D 0000000000000004     0  1351      2 0x00000000
[ 8158.182752]  ffff88047cb37be8 0000000000000046 ffff880700000001 ffff880484614110
[ 8158.182756]  0000000000000003 ffff88047cb37fd8 ffff88048065d3d0 0000000000011dc0
[ 8158.182760]  0000000000011dc0 ffff88048065d3d0 0000072ab216962d ffff880497c51dc0
[ 8158.182764] Call Trace:
[ 8158.182775]  [<ffffffff813a3aee>] ? io_schedule+0x5b/0x74
[ 8158.182796]  [<ffffffffa03bad39>] ? cv_wait_common+0xa7/0x103 [spl]
[ 8158.182802]  [<ffffffff8106439d>] ? wake_up_atomic_t+0x22/0x22
[ 8158.182832]  [<ffffffffa06e2fdd>] ? zio_wait+0x116/0x15f [zfs]
[ 8158.182859]  [<ffffffffa0688425>] ? dsl_pool_sync+0xaa/0x39e [zfs]
[ 8158.182890]  [<ffffffffa069c746>] ? spa_sync+0x4d3/0x96b [zfs]
[ 8158.182896]  [<ffffffff810820f3>] ? timekeeping_get_ns_raw.constprop.11+0x11/0x37
[ 8158.182900]  [<ffffffff81082522>] ? getrawmonotonic+0x13/0x4e
[ 8158.182929]  [<ffffffffa06aa470>] ? txg_sync_thread+0x27c/0x4b8 [zfs]
[ 8158.182937]  [<ffffffffa03b7444>] ? spl_kmem_fini+0x6d/0x6d [spl]
[ 8158.182967]  [<ffffffffa06aa1f4>] ? txg_do_callbacks+0x44/0x44 [zfs]
[ 8158.182974]  [<ffffffffa03b7444>] ? spl_kmem_fini+0x6d/0x6d [spl]
[ 8158.182982]  [<ffffffffa03b74ae>] ? thread_generic_wrapper+0x6a/0x75 [spl]
[ 8158.182987]  [<ffffffff81051192>] ? kthread+0x99/0xa1
[ 8158.182991]  [<ffffffff810510f9>] ? __kthread_parkme+0x58/0x58
[ 8158.182995]  [<ffffffff813a646c>] ? ret_from_fork+0x7c/0xb0
[ 8158.182999]  [<ffffffff810510f9>] ? __kthread_parkme+0x58/0x58
[23873.711276] INFO: task txg_sync:1351 blocked for more than 120 seconds.
[23873.711330]       Tainted: P          IO   3.17.7-vanillabean1 #1
[23873.711375] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[23873.711449] txg_sync        D 0000000000000000     0  1351      2 0x00000000
[23873.711454]  ffff88047cb37be8 0000000000000046 ffff880400000001 ffffffff81616450
[23873.711459]  0000000000000003 ffff88047cb37fd8 ffff88048065d3d0 0000000000011dc0
[23873.711462]  0000000000011dc0 ffff88048065d3d0 0000159586eace2d ffff880497c11dc0
[23873.711467] Call Trace:
[23873.711477]  [<ffffffff813a3aee>] ? io_schedule+0x5b/0x74
[23873.711498]  [<ffffffffa03bad39>] ? cv_wait_common+0xa7/0x103 [spl]
[23873.711504]  [<ffffffff8106439d>] ? wake_up_atomic_t+0x22/0x22
[23873.711535]  [<ffffffffa06e2fdd>] ? zio_wait+0x116/0x15f [zfs]
[23873.711562]  [<ffffffffa0688425>] ? dsl_pool_sync+0xaa/0x39e [zfs]
[23873.711593]  [<ffffffffa069c746>] ? spa_sync+0x4d3/0x96b [zfs]
[23873.711599]  [<ffffffff810820f3>] ? timekeeping_get_ns_raw.constprop.11+0x11/0x37
[23873.711602]  [<ffffffff81082522>] ? getrawmonotonic+0x13/0x4e
[23873.711632]  [<ffffffffa06aa470>] ? txg_sync_thread+0x27c/0x4b8 [zfs]
[23873.711640]  [<ffffffffa03b7444>] ? spl_kmem_fini+0x6d/0x6d [spl]
[23873.711670]  [<ffffffffa06aa1f4>] ? txg_do_callbacks+0x44/0x44 [zfs]
[23873.711677]  [<ffffffffa03b7444>] ? spl_kmem_fini+0x6d/0x6d [spl]
[23873.711685]  [<ffffffffa03b74ae>] ? thread_generic_wrapper+0x6a/0x75 [spl]
[23873.711690]  [<ffffffff81051192>] ? kthread+0x99/0xa1
[23873.711694]  [<ffffffff810510f9>] ? __kthread_parkme+0x58/0x58
[23873.711698]  [<ffffffff813a646c>] ? ret_from_fork+0x7c/0xb0
[23873.711701]  [<ffffffff810510f9>] ? __kthread_parkme+0x58/0x58
[24233.608934] INFO: task txg_sync:1351 blocked for more than 120 seconds.
[24233.608986]       Tainted: P          IO   3.17.7-vanillabean1 #1
[24233.609030] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[24233.609101] txg_sync        D 0000000000000005     0  1351      2 0x00000000
[24233.609106]  ffff88047cb37be8 0000000000000046 ffff880800000001 ffff8804846251d0
[24233.609111]  0000000000000003 ffff88047cb37fd8 ffff88048065d3d0 0000000000011dc0
[24233.609114]  0000000000011dc0 ffff88048065d3d0 000015ef2ab4982d ffff880917a51dc0
[24233.609118] Call Trace:
[24233.609129]  [<ffffffff813a3aee>] ? io_schedule+0x5b/0x74
[24233.609149]  [<ffffffffa03bad39>] ? cv_wait_common+0xa7/0x103 [spl]
[24233.609156]  [<ffffffff8106439d>] ? wake_up_atomic_t+0x22/0x22
[24233.609186]  [<ffffffffa06e2fdd>] ? zio_wait+0x116/0x15f [zfs]
[24233.609213]  [<ffffffffa0688425>] ? dsl_pool_sync+0xaa/0x39e [zfs]
[24233.609244]  [<ffffffffa069c746>] ? spa_sync+0x4d3/0x96b [zfs]
[24233.609252]  [<ffffffff810820f3>] ? timekeeping_get_ns_raw.constprop.11+0x11/0x37
[24233.609255]  [<ffffffff81082522>] ? getrawmonotonic+0x13/0x4e
[24233.609285]  [<ffffffffa06aa470>] ? txg_sync_thread+0x27c/0x4b8 [zfs]
[24233.609293]  [<ffffffffa03b7444>] ? spl_kmem_fini+0x6d/0x6d [spl]
[24233.609322]  [<ffffffffa06aa1f4>] ? txg_do_callbacks+0x44/0x44 [zfs]
[24233.609330]  [<ffffffffa03b7444>] ? spl_kmem_fini+0x6d/0x6d [spl]
[24233.609337]  [<ffffffffa03b74ae>] ? thread_generic_wrapper+0x6a/0x75 [spl]
[24233.609343]  [<ffffffff81051192>] ? kthread+0x99/0xa1
[24233.609347]  [<ffffffff810510f9>] ? __kthread_parkme+0x58/0x58
[24233.609353]  [<ffffffff813a646c>] ? ret_from_fork+0x7c/0xb0
[24233.609356]  [<ffffffff810510f9>] ? __kthread_parkme+0x58/0x58
[24473.540655] INFO: task txg_sync:1351 blocked for more than 120 seconds.
[24473.540707]       Tainted: P          IO   3.17.7-vanillabean1 #1
[24473.540751] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[24473.540821] txg_sync        D 0000000000000004     0  1351      2 0x00000000
[24473.540827]  ffff88047cb37be8 0000000000000046 ffff880400000001 ffff880484614110
[24473.540832]  0000000000000003 ffff88047cb37fd8 ffff88048065d3d0 0000000000011dc0
[24473.540835]  0000000000011dc0 ffff88048065d3d0 0000161b6796842d ffff880497c51dc0
[24473.540839] Call Trace:
[24473.540849]  [<ffffffff813a3aee>] ? io_schedule+0x5b/0x74
[24473.540871]  [<ffffffffa03bad39>] ? cv_wait_common+0xa7/0x103 [spl]
[24473.540877]  [<ffffffff8106439d>] ? wake_up_atomic_t+0x22/0x22
[24473.540908]  [<ffffffffa06e2fdd>] ? zio_wait+0x116/0x15f [zfs]
[24473.540935]  [<ffffffffa0688425>] ? dsl_pool_sync+0xaa/0x39e [zfs]
[24473.540966]  [<ffffffffa069c746>] ? spa_sync+0x4d3/0x96b [zfs]
[24473.540974]  [<ffffffff810820f3>] ? timekeeping_get_ns_raw.constprop.11+0x11/0x37
[24473.540977]  [<ffffffff81082522>] ? getrawmonotonic+0x13/0x4e
[24473.541007]  [<ffffffffa06aa470>] ? txg_sync_thread+0x27c/0x4b8 [zfs]
[24473.541015]  [<ffffffffa03b7444>] ? spl_kmem_fini+0x6d/0x6d [spl]
[24473.541044]  [<ffffffffa06aa1f4>] ? txg_do_callbacks+0x44/0x44 [zfs]
[24473.541052]  [<ffffffffa03b7444>] ? spl_kmem_fini+0x6d/0x6d [spl]
[24473.541059]  [<ffffffffa03b74ae>] ? thread_generic_wrapper+0x6a/0x75 [spl]
[24473.541065]  [<ffffffff81051192>] ? kthread+0x99/0xa1
[24473.541069]  [<ffffffff810510f9>] ? __kthread_parkme+0x58/0x58
[24473.541074]  [<ffffffff813a646c>] ? ret_from_fork+0x7c/0xb0
[24473.541078]  [<ffffffff810510f9>] ? __kthread_parkme+0x58/0x58

**Comment by behlendorf** [comment] 2015-01-06 17:50
This is very likely a duplicate of #2523 which was recently fixed in master and will be in the 0.6.4 tag.

**Comment by kpande** [comment] 2015-01-06 18:07
this server was using the following version:
[84156.455930] SPL: Loaded module v0.6.3-53_ga3c1eb7
[835376.949912] ZFS: Loaded module v0.6.3-165_g2d9d57b


It already had that commit

**Comment by behlendorf** [comment] 2015-01-06 18:46
OK, then it sounds like it's time for a new theory.  Does the system lock up and require a reboot after these messages are logged?  Or does it eventually clear up.

If it does clear up nothing in fact may be wrong, it just may just be talking an exceptionally long time to process a chunk of zio's in the current syncing txg.  You could check this by grabbing the following debugging.  It will show how long each txg took and some statistics about how much IO was done during that period.

```
echo 100 >/sys/module/zfs/parameters/zfs_txg_history
...wait until the issue reproduces...
cat /proc/spl/kstat/zfs/<pool>/txgs
```

**Comment by kpande** [comment] 2015-03-15 16:05
```
[~]-[root@replicator]-[0]-[10012]
[:)] # cat /proc/spl/kstat/zfs/backup/txgs    
9 0 0x01 46 5152 11216290494 708466177046273
txg      birth            state ndirty       nread        nwritten     reads    writes   otime        qtime        wtime        stime       
11656078 708237905989510  C     0            0            0            0        0        5000133897   8569         76362        688201      
11656079 708242906123407  C     0            0            0            0        0        4999869164   7582         78082        690261      
11656080 708247905992571  C     0            0            0            0        0        4999972938   6182         74751        677025      
11656081 708252905965509  C     0            0            0            0        0        5000024416   6067         75621        457458      
11656082 708257905989925  C     0            0            0            0        0        4999994855   6872         73883        454857      
11656083 708262905984780  C     0            0            0            0        0        4999993284   5947         75751        456398      
11656084 708267905978064  C     0            0            0            0        0        4999991026   5862         75174        457610      
11656085 708272905969090  C     0            0            0            0        0        5000020357   5887         74684        379265      
11656086 708277905989447  C     0            0            0            0        0        5000058433   6772         78877        184911      
11656087 708282906047880  C     0            0            0            0        0        4999935816   6176         75264        251505      
11656088 708287905983696  C     0            0            0            0        0        4999944045   9623         16507        292971      
11656089 708292905927741  C     0            0            0            0        0        5000057690   8513         75294        468758      
11656090 708297905985431  C     0            0            0            0        0        4999985745   8642         76672        256226      
11656091 708302905971176  C     0            0            0            0        0        5000056347   8810         81003        153786      
11656092 708307906027523  C     0            0            0            0        0        5000033436   7922         78665        692487      
11656093 708312906060959  C     0            0            0            0        0        4999993584   7753         78849        471447      
11656094 708317906054543  C     0            0            0            0        0        4999941860   8440         77412        467841      
11656095 708322905996403  C     0            0            0            0        0        4999986940   6787         74044        226922      
11656096 708327905983343  C     0            0            0            0        0        4999998756   6136         75502        182222      
11656097 708332905982099  C     0            0            0            0        0        5000081654   6960         72908        465193      
11656098 708337906063753  C     0            0            0            0        0        4999909261   6509         74804        455072      
11656099 708342905973014  C     0            0            0            0        0        5000005748   7307         77970        451928      
11656100 708347905978762  C     0            0            0            0        0        5000061521   7782         77347        461274      
11656101 708352906040283  C     0            0            0            0        0        4999922336   8648         76194        455480      
11656102 708357905962619  C     0            0            0            0        0        5000069359   8487         77800        503073      
11656103 708362906031978  C     0            0            0            0        0        5000034686   9178         72183        166497      
11656104 708367906066664  C     0            0            0            0        0        4999926976   6542         74913        139933      
11656106 708377906150528  C     0            0            0            0        0        4999900198   7162         73908        458528      
11656107 708382906050726  C     0            0            0            0        0        4999931192   6066         75222        433921      
11656108 708387905981918  C     0            0            0            0        0        5000073684   7005         73321        231741      
11656109 708392906055602  C     0            0            0            0        0        4999924973   5914         75297        468287      
11656110 708397905980575  C     0            0            0            0        0        4999999533   5880         75599        442838      
11656111 708402905980108  C     0            0            0            0        0        4999995471   6231         74509        470144      
11656112 708407905975579  C     0            0            0            0        0        4999978645   8357         77700        481247      
11656113 708412905954224  C     0            0            0            0        0        5000104718   8435         76399        145537      
11656114 708417906058942  C     0            0            0            0        0        4999926493   8420         78815        140524      
11656115 708422905985435  C     0            0            0            0        0        5000079111   8410         75424        475248      
11656116 708427906064546  C     0            0            0            0        0        5000005425   8288         77067        187058      
11656117 708432906069971  C     0            0            0            0        0        4999992427   7702         76987        457400      
11656118 708437906062398  C     0            0            0            0        0        4999912569   7244         79170        427185      
11656119 708442905974967  C     0            0            0            0        0        4999990016   6214         74992        471071      
11656120 708447905964983  C     0            0            0            0        0        5000029092   8337         77237        456748      
11656121 708452905994075  C     0            0            0            0        0        4999987388   6139         75071        471406      
11656122 708457905981463  C     0            0            0            0        0        5000003249   7467         79140        450423      
11656123 708462905984712  O     0            0            0            0        0        0            0            0            0           
[~]-[root@replicator]-[0]-[10013]
[:)] # cat /proc/spl/kstat/zfs/replicator/txgs
13 0 0x01 48 5376 11216314492 708476038772392
txg      birth            state ndirty       nread        nwritten     reads    writes   otime        qtime        wtime        stime       
13629371 708240845995211  C     0            0            0            0        0        5000020079   9353         74749        281154      
13629372 708245846015290  C     0            0            0            0        0        4999987653   6955         74601        197143      
13629373 708250846002943  C     0            0            0            0        0        5000040735   6320         75564        233876      
13629374 708255846043678  C     0            0            0            0        0        4999941427   8018         78352        290280      
13629375 708260845985105  C     0            0            0            0        0        5000072422   6255         75088        360420      
13629376 708265846057527  C     0            0            0            0        0        4999932537   6207         74681        162192      
13629377 708270845990064  C     0            0            0            0        0        5000005021   5913         74877        158837      
13629378 708275845995085  C     0            0            0            0        0        5000058032   7122         72731        140365      
13629379 708280846053117  C     0            0            0            0        0        4999882723   6547         73914        145586      
13629380 708285845935840  C     1197568      9728         814080       8        52       5000039130   6795         74686        11788537    
13629381 708290845974970  C     147968       10240        773632       8        41       5000020857   10686        75156        14414207    
13629382 708295845995827  C     0            0            0            0        0        4999982399   8645         73761        765615      
13629383 708300845978226  C     0            0            0            0        0        5000073359   8753         88630        723771      
13629384 708305846051585  C     229376       10752        907776       8        48       5000027998   8082         78009        15018504    
13629385 708310846079583  C     221184       12800        867328       9        71       4999928621   7494         78672        13368405    
13629386 708315846008204  C     188416       15360        2879488      11       84       4999997642   8920         75839        26655969    
13629387 708320846005846  C     221184       94208        891904       8        46       5000057951   6924         78547        14342945    
13629388 708325846063797  C     0            0            0            0        0        4999919873   6480         74018        550477      
13629389 708330845983670  C     0            0            0            0        0        5000043479   5989         75349        532124      
13629390 708335846027149  C     188416       7168         872960       8        43       4999957769   6001         74692        15399329    
13629391 708340845984918  C     196608       7168         859136       8        53       5000066005   6372         73986        14268870    
13629392 708345846050923  C     1197568      7168         787456       8        43       4999932272   6907         81308        11479505    
13629393 708350845983195  C     147968       7168         762368       8        39       5000007679   9472         75024        15676506    
13629394 708355845990874  C     0            0            0            0        0        5000075205   7452         78397        534792      
13629395 708360846066079  C     0            0            0            0        0        4999970468   8727         74429        580145      
13629396 708365846036547  C     0            0            0            0        0        5000004529   10518        74489        465135      
13629397 708370846041076  C     0            0            0            0        0        5000071800   6294         73678        501813      
13629399 708380846000430  C     0            0            0            0        0        5000062829   6422         72938        169543      
13629400 708385846063259  C     0            0            0            0        0        4999985154   6392         75089        393354      
13629401 708390846048413  C     0            0            0            0        0        4999977905   5867         75084        181589      
13629402 708395846026318  C     0            0            0            0        0        5000068468   6272         74151        500193      
13629403 708400846094786  C     0            0            0            0        0        5000000645   7314         73968        441133      
13629404 708405846095431  C     1197568      7680         793088       8        40       5000095731   8682         76959        12667276    
13629405 708410846191162  C     147968       7680         769536       8        39       4999875218   9950         71886        13528192    
13629406 708415846066380  C     0            0            0            0        0        4999914764   7697         76893        586871      
13629407 708420845981144  C     0            0            0            0        0        5000135465   8692         76752        574344      
13629408 708425846116609  C     0            0            0            0        0        5000000762   8807         77142        423883      
13629409 708430846117371  C     458752       7680         1130496      8        60       4999927515   6860         74981        15965138    
13629410 708435846044886  C     221184       6144         883200       8        51       5000031643   7797         77713        11824412    
13629411 708440846076529  C     0            0            0            0        0        4999978507   6562         72471        626361      
13629412 708445846055036  C     0            0            0            0        0        4999938897   9015         76069        614948      
13629413 708450845993933  C     0            0            0            0        0        4999985222   5949         82804        449795      
13629414 708455845979155  C     0            0            0            0        0        5000050553   6304         75320        448849      
13629415 708460846029708  C     1197568      6144         785408       8        45       4999956211   7048         78747        11460912    
13629416 708465845985919  C     1213952      6656         775168       8        49       4999988206   8658         76514        10686939    
13629417 708470845974125  C     147968       6656         768512       8        38       5000145713   9220         74138        12390299    
13629418 708475846119838  O     0            0            0            0        0        0            0            0            0           
```

**Comment by kpande** [comment] 2015-03-15 16:07
The above system was observed with a load over 30 for about 15 minutes. Nothing out of the ordinary was happening.

**Comment by behlendorf** [comment] 2015-03-19 16:39
Hmm, nothing particularly out of order in the txg history.

**Comment by behlendorf** [comment] 2016-11-15 05:43
Closing as stale.

**Closed by behlendorf** 2016-11-15 05:43 UTC
