### ISSUE TITLE
debian packaging breaks module compilation

### ISSUE THREAD

**Issue by bdols** [zfsonlinux/zfs#4056] opened 2015-12-01 01:20 UTC
I'm an end user who upgraded everything to current in debian, as part my recent "apt-get upgrade", linux kernel 3.16.0 was installed and some zfs-related packages were upgraded. I found after boot that the zfs module was not compiled for the 3.16.0 kernel

packages:
ii  build-essential                                           11.7                              amd64                             Informational list of build-essential packages
un  linux-headers                                             <none>                            <none>                            (no description available)
ii  linux-headers-3.16.0-4-amd64                              3.16.7-ckt11-1+deb8u6             amd64                             Header files for Linux 3.16.0-4-amd64
ii  linux-headers-3.16.0-4-common                             3.16.7-ckt11-1+deb8u6             amd64                             Common header files for Linux 3.16.0-4
ii  linux-headers-3.2.0-4-amd64                               3.2.68-1+deb7u2                   amd64                             Header files for Linux 3.2.0-4-amd64
ii  linux-headers-3.2.0-4-common                              3.2.68-1+deb7u2                   amd64                             Common header files for Linux 3.2.0-4
un  linux-headers-686-pae                                     <none>                            <none>                            (no description available)
ii  linux-headers-amd64                                       3.16+63                           amd64                             Header files for Linux amd64 configuration (meta-package)
un  linux-headers-generic                                     <none>                            <none>                            (no description available)
ii  spl                                                       0.6.5.3-1                         amd64                             Solaris Porting Layer user-space utilities for Linux
ii  spl-dkms                                                  0.6.5.3-1                         all                               Solaris Porting Layer kernel modules for Linux
ii  zfs-dkms                                                  0.6.5.2-2                         all                               Native ZFS filesystem kernel modules for Linux
ii  zfsutils                                                  0.6.5.2-2                         amd64                             command-line tools to manage ZFS filesystems

zfs-dkms and spl-dkms versions are mismatched

I ran "dpkg-reconfigure zfs-dkms":
------------------------------
Deleting module version: 0.6.5.2
completely from the DKMS tree.
------------------------------
Done.
Loading new zfs-0.6.5.2 DKMS files...
Building only for 3.16.0-4-amd64
Building initial module for 3.16.0-4-amd64
configure: error: 
        *** Please make sure the kmod spl devel package for your distribution
        *** is installed then try again.  If that fails you can specify the
        *** location of the spl source with the '--with-spl=PATH' option.
Error! Bad return status for module build on kernel: 3.16.0-4-amd64 (x86_64)
Consult /var/lib/dkms/zfs/0.6.5.2/build/make.log for more information.

DKMS make.log for zfs-0.6.5.2 for kernel 3.16.0-4-amd64 (x86_64)
Mon Nov 30 19:10:26 CST 2015
make: *** No targets specified and no makefile found.  Stop.

**Comment by bdols** [comment] 2015-12-01 01:21
[zfs-dpkg.log.txt](https://github.com/zfsonlinux/zfs/files/48007/zfs-dpkg.log.txt)

**Comment by bdols** [comment] 2015-12-01 03:32
i worked around this by downgrading spl-dkms to 0.6.5-1 that was still in my apt-cache, thankfully.
ran dpkg-reconfigure zfs-dkms and modprobe zfs to get my zfs volumes back.

**Comment by dasjoe** [comment] 2015-12-01 15:36
`apt-cache policy spl-dkms` should show you're getting spl-dkms from debian's testing or experimental respository. testing and experimental are not supported by @FransUrbo, his packages are stuck at 0.6.5.2 as of now.
See https://github.com/zfsonlinux/pkg-zfs/issues/184 and https://github.com/zfsonlinux/pkg-zfs/issues/181.

**Comment by roeme** [comment] 2015-12-02 09:27
Duplicate of #184.

**Comment by dasjoe** [comment] 2015-12-02 10:10
No, not of #184 but of zfsonlinux/pkg-zfs#184...

**Comment by bdols** [comment] 2015-12-08 02:18
yes, I have had experimental of debian for some time for some reason unrelated to zfs

**Comment by Baristan6** [comment] 2016-03-05 10:07
I had a similar issue.
Reinstalling linux-source and Installing gcc-multilib fixed it for me.
zfs compiled for 3.19.0.32 afterwards.

```
apt-get install linux-source gcc-multilib
dkms remove -m zfs -v 0.6.5.4 --all
dkms remove -m spl -v 0.6.5.4 --all
dkms add -m spl -v 0.6.5.4
dkms add -m zfs -v 0.6.5.4
dkms install -m spl -v 0.6.5.4
dkms install -m zfs -v 0.6.0.4
```

**Comment by FransUrbo** [comment] 2016-04-19 11:18
@behlendorf Can you close this as "won't fix"?

See https://github.com/zfsonlinux/pkg-zfs/issues/184#issuecomment-211864972 for excuse.

**Comment by behlendorf** [comment] 2016-10-01 03:28
Packages are now provided by Debian.

**Closed by behlendorf** 2016-10-01 03:28 UTC
