### ISSUE TITLE
objtool: unsupported stack pointer realignment

### ISSUE THREAD

**Issue by twoertwein** [zfsonlinux/zfs#7504] opened 2018-05-04 01:21 UTC
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  ArchLinux
Distribution Version    | 
Linux Kernel                 | 4.14.39
Architecture                 | x86_64
ZFS Version                  | 0.7.8
SPL Version                  | 0.7.8

### Describe the problem you're observing
While compiling ZFS and SPL into the kernel, I observed a warning message generated by objtool. I have honestly no idea what it is complaining about (and whether it is important at all).

### Describe how to reproduce the problem
Compile ZFS  and SPL with the kernel.

### Include any warning/errors/backtraces from the system logs
```
[...]
zfs/icp/asm-x86_64/modes/gcm_intel.o
  AS      fs/zfs/icp/asm-x86_64/sha1/sha1-x86_64.o
fs/zfs/icp/asm-x86_64/sha1/.tmp_sha1-x86_64.o: warning: objtool: sha1_block_data_order()+0x11: unsupported stack pointer realignment
  AS      fs/zfs/icp/asm-x86_64/sha2/sha256_impl.o
fs/zfs/icp/asm-x86_64/sha2/.tmp_sha256_impl.o: warning: objtool: SHA256TransformBlocks()+0x19: unsupported stack pointer realignment
  AS      fs/zfs/icp/asm-x86_64/sha2/sha512_impl.o
  CC      drivers/acpi/processor_perflib.o
fs/zfs/icp/asm-x86_64/sha2/.tmp_sha512_impl.o: warning: objtool: SHA512TransformBlocks()+0x1c: unsupported stack pointer realignment
[...]
```

**Comment by gmelikov** [comment] 2018-05-04 05:30
Closed as duplicate of #6950.

**Closed by gmelikov** 2018-05-04 05:30 UTC
