### ISSUE TITLE
Less File System Space Available

### ISSUE THREAD

**Issue by ZMarc** [zfsonlinux/zfs#3855] opened 2015-09-30 00:50 UTC
I'm currently encountering discrepancies with the reported file system space available between zfs v0.6.4.2 & v0.6.5.1. 

Pool imported Linux Mint 17.2  (zfs v0.6.5.1)
<pre><code> 
WD-6303  used                  2.57T 
WD-6303  available             64.5G  ⟵ ≈60% difference (0.597222222)
</pre></code> 
Pool imported Linux Mint 13    (zfs v0.6.4.2)
<pre><code> 
WD-6303  used                  2.57T
WD-6303  available             108G
</pre></code> 

=============================================================================

Pool imported Linux Mint 17.2  (zfs v0.6.5.1)
<pre><code> 
WD-2888  used                  3.48T 
WD-2888  available             31.7G ⟵ ≈35% difference (0.353400223)
</pre></code> 
Pool imported Linux Mint 13    (zfs v0.6.4.2)
<pre><code> 
WD-2888  used                  3.48T                 
WD-2888  available             89.7G
</pre></code> 

=============================================================================

zfs v0.6.5.1 will always report less space avalible on the same file system than zfs v0.6.4.2, although the percentage of difference varies from pool to pool.

All pools are version 8, single disk use (no RAID), no quotas, no compression, and there are no snapshots holding deleted data.

zpool list, correctly shows the same space available for both Mint 13 & 17.2 (v0.6.4.2 & v0.6.5.1).

=============================================================================

Pool imported Linux Mint 17.2  (zfs v0.6.5.1)
<pre><code> 
NAME      SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
WD-6303  2.72T  2.57T   152G         -      -    94%  1.00x  ONLINE  -
</pre></code> 
Pool imported Linux Mint 13    (zfs v0.6.4.2)
<pre><code> 
NAME      SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
WD-6303  2.72T  2.57T   152G         -      -    94%  1.00x  ONLINE  -
</pre></code> 

=============================================================================

Pool imported Linux Mint 17.2  (zfs v0.6.5.1)
<pre><code> 
NAME      SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
WD-2888  3.62T  3.48T   148G         -      -    96%  1.00x  ONLINE  -
</pre></code> 
Pool imported Linux Mint 13    (zfs v0.6.4.2)
<pre><code> 
NAME      SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
WD-2888  3.62T  3.48T   148G         -      -    96%  1.00x  ONLINE  -
</pre></code>

**Comment by kernelOfTruth** [comment] 2015-09-30 00:53
https://github.com/zfsonlinux/zfs/releases

```
Default reserved space was increased from 1.6% to 3.2% of total pool capacity. This default percentage can be controlled through the new spa_slop_shift module option, setting it to 6 will restore the previous percentage.
```

**Comment by kernelOfTruth** [comment] 2015-09-30 00:54
dupe of https://github.com/zfsonlinux/zfs/issues/3841 0.6.4->0.6.5.1: df shows disk full, 0 space available

**Comment by ZMarc** [comment] 2015-09-30 00:56
From the above, I'm seeing 60-35% difference well beyond the 1.6% reserve space increase.

**Closed** 2015-09-30 02:03 UTC
