### ISSUE TITLE
zfs deadlock apparently because of zio_wait never returning

### ISSUE THREAD

**Issue by avg-I** [zfsonlinux/zfs#2571] opened 2014-08-05 13:55 UTC
The deadlock is caught with softdog.
Output of foreach bt: https://gist.github.com/avg-I/e02c260bd12e7ab35de7

**Comment by behlendorf** [comment] 2015-02-06 00:20
This is very likely a duplicate of #2523 which has been fixed.

**Closed by behlendorf** 2015-02-06 00:20 UTC
Labels: Bug
