### ISSUE TITLE
resilver statistics are incorrect

### ISSUE THREAD

**Issue by kpande** [zfsonlinux/zfs#7119] opened 2018-02-03 09:50 UTC
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Gentoo
Distribution Version    | 17.0 Desktop
Linux Kernel                 | 4.14.15-gentoo
Architecture                 |  amd64
ZFS Version                  |  0.7.0-271_g4c46b99d
SPL Version                  | 0.7.0-24_g23602fd

### Describe the problem you're observing
When resilvering or scrubbing disks since the addition of sequential resilver, the statistics in `zpool status` are incorrect.

The throughput is calculated by averaging the data scanned over the duration of the scan, and this can be wildly inaccurate.

In addition, it seems that it can simply stop counting once it reaches the amount it expected to scan originally.. Once it reached 2.67T out of 2.67T, 

### Describe how to reproduce the problem
Scrub a pool made of 2x LUKS mirrors.

### Include any warning/errors/backtraces from the system logs
zpool status shows throughput as 358M, and every few seconds seems to reduce by 1M/s.

```
  pool: fishtank
 state: ONLINE
  scan: scrub in progress since Sat Feb  3 02:36:52 2018
        2.67T scanned out of 2.67T at 358M/s, (scan is slow, no estimated time)
        0B repaired, 100.00% done
config:

        NAME           STATE     READ WRITE CKSUM
        fishtank       ONLINE       0     0     0
          mirror-0     ONLINE       0     0     0
            fishtank1  ONLINE       0     0     0
            fishtank3  ONLINE       0     0     0
          mirror-1     ONLINE       0     0     0
            fishtank2  ONLINE       0     0     0
            fishtank4  ONLINE       0     0     0

errors: No known data errors
```

meanwhile, zpool iostat is showing the true story.

```
                                                 capacity     operations     bandwidth 
pool                                           alloc   free   read  write   read  write
---------------------------------------------  -----  -----  -----  -----  -----  -----
fishtank                                       2.67T  6.40T    609      0   609M      0
  mirror                                       1.35T  3.18T    324      0   325M      0
    fishtank1                                      -      -    161      0   162M      0
    fishtank3                                      -      -    162      0   163M      0
  mirror                                       1.32T  3.22T    284      0   285M      0
    fishtank2                                      -      -    143      0   144M      0
    fishtank4                                      -      -    140      0   141M      0
---------------------------------------------  -----  -----  -----  -----  -----  -----

```

```
                                                 capacity     operations     bandwidth    total_wait     disk_wait    syncq_wait    asyncq_wait  scrub
pool                                           alloc   free   read  write   read  write   read  write   read  write   read  write   read  write   wait
---------------------------------------------  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----
fishtank                                       2.67T  6.40T    554      0   554M      0   41ms      -   14ms      -      -      -      -      -   29ms
  mirror                                       1.35T  3.18T    276      0   275M      0   39ms      -   13ms      -      -      -      -      -   27ms
    fishtank1                                      -      -    139      0   139M      0   23ms      -   13ms      -      -      -      -      -    6ms
    fishtank3                                      -      -    136      0   136M      0   56ms      -   14ms      -      -      -      -      -   47ms
  mirror                                       1.32T  3.22T    279      0   279M      0   44ms      -   14ms      -      -      -      -      -   30ms
    fishtank2                                      -      -    141      0   142M      0   34ms      -   15ms      -      -      -      -      -   17ms
    fishtank4                                      -      -    137      0   138M      0   53ms      -   13ms      -      -      -      -      -   44ms

```

**Comment by richardelling** [comment] 2018-02-03 17:40
The throughput is measured using the time of the start of the current scan pass. It might be easier to have a rolling average throughput based upon the most recent txg commit time: current throughput estimate = 1/4 throughput of last txg commit + 3/4 previous throughput estimate

In any case, the estimate of time remaining is often wildly incorrect due to other activity and the ZIO scheduler.

**Comment by kpande** [comment] 2018-02-04 10:53
@richardelling it wasn't that the time to completion is wrong so much as it thinks it is slow and has no estimation, despite the actual throughput being in the hundreds of MB/s and finishing in less than an hour later.

**Comment by behlendorf** [comment] 2018-02-05 20:24
@kpande are you sure your user space is really 0.7.0-271_g4c46b99d.  I ask because the exact `zpool status` messages you posted don't match the final version which was merged with the sequential scrub code.

**Comment by kpande** [comment] 2018-02-05 20:25
@behlendorf yes

**Comment by kpande** [comment] 2018-02-05 20:25
@behlendorf actually, let me get back to you on this.

**Comment by behlendorf** [comment] 2018-02-05 20:30
As long as you the scrub is progressing at at least 10MB/s you should get an estimated completion time.  Take a look at https://github.com/zfsonlinux/zfs/blob/master/cmd/zpool/zpool_main.c#L6099..L6129 to get an idea what will be reported.

> The max speed is 4 GB/sec due to use of 32 bit numbers in the calculation,

@DeHackEd is this still true?  If so we should absolutely fix it.

**Comment by kpande** [comment] 2018-02-05 20:32
looks like my userland was out of date from November, the current message looks like this

```
  scan: scrub in progress since Mon Feb  5 15:31:19 2018
        535G scanned at 2.43G/s, 336K issued at 11.6K/s, 2.57T total
        0B repaired, 0.00% done, no estimated completion time
```

**Comment by DeHackEd** [comment] 2018-02-05 20:35
@behlendorf yes it is. I'll put together something tonight. This should be pretty trivial.

(SSDs + metadata allocation classes + resilver of a metadata vdev = holy $#!7 resilver speeds)

**Comment by kpande** [comment] 2018-02-05 20:56
@behlendorf the numbers are still very wrong because it's counting since the beginning of the event and not a rolling avg over the last txg

**Comment by kpande** [comment] 2018-02-05 20:57
though the disks are reading at 400MB/s the pool status says 187MB/s and the scan rate is decreasing by 1M/s every time the command outputs a status.

```
  pool: fishtank
 state: ONLINE
  scan: scrub in progress since Mon Feb  5 15:31:19 2018
        1.34T scanned at 917M/s, 281G issued at 187M/s, 2.57T total
        0B repaired, 10.70% done, 0 days 03:33:56 to go
config:

        NAME           STATE     READ WRITE CKSUM
        fishtank       ONLINE       0     0     0
          mirror-0     ONLINE       0     0     0
            fishtank1  ONLINE       0     0     0
            fishtank3  ONLINE       0     0     0
          mirror-1     ONLINE       0     0     0
            fishtank2  ONLINE       0     0     0
            fishtank4  ONLINE       0     0     0

errors: No known data errors

  pool: fishtank
 state: ONLINE
  scan: scrub in progress since Mon Feb  5 15:31:19 2018
        1.34T scanned at 916M/s, 282G issued at 187M/s, 2.57T total
        0B repaired, 10.71% done, 0 days 03:33:55 to go
config:

        NAME           STATE     READ WRITE CKSUM
        fishtank       ONLINE       0     0     0
          mirror-0     ONLINE       0     0     0
            fishtank1  ONLINE       0     0     0
            fishtank3  ONLINE       0     0     0
          mirror-1     ONLINE       0     0     0
            fishtank2  ONLINE       0     0     0
            fishtank4  ONLINE       0     0     0

errors: No known data errors

  pool: fishtank
 state: ONLINE
  scan: scrub in progress since Mon Feb  5 15:31:19 2018
        1.34T scanned at 915M/s, 282G issued at 187M/s, 2.57T total
        0B repaired, 10.71% done, 0 days 03:33:54 to go
config:

        NAME           STATE     READ WRITE CKSUM
        fishtank       ONLINE       0     0     0
          mirror-0     ONLINE       0     0     0
            fishtank1  ONLINE       0     0     0
            fishtank3  ONLINE       0     0     0
          mirror-1     ONLINE       0     0     0
            fishtank2  ONLINE       0     0     0
            fishtank4  ONLINE       0     0     0

errors: No known data errors

  pool: fishtank
 state: ONLINE
  scan: scrub in progress since Mon Feb  5 15:31:19 2018
        1.34T scanned at 915M/s, 282G issued at 187M/s, 2.57T total
        0B repaired, 10.72% done, 0 days 03:33:53 to go
config:

        NAME           STATE     READ WRITE CKSUM
        fishtank       ONLINE       0     0     0
          mirror-0     ONLINE       0     0     0
            fishtank1  ONLINE       0     0     0
            fishtank3  ONLINE       0     0     0
          mirror-1     ONLINE       0     0     0
            fishtank2  ONLINE       0     0     0
            fishtank4  ONLINE       0     0     0

errors: No known data errors

```

**Comment by behlendorf** [comment] 2018-02-05 21:23
That's as intended, although the man page is a bit vague and doesn't say that the rate is an average over the entire scrub and not an instantaneous rate.  This was done in the design since it should result in a more accurate estimate.  Are you finding that not to be the case perhaps due to the scan phase?  Although as you know your mileage may vary considerably depending on any active workload and the exact on-disk layout.

**Comment by kpande** [comment] 2018-02-05 21:35
@behlendorf the problem is that the estimate is less accurate than if it were using an average over the previous few TXG

**Comment by kpande** [comment] 2018-02-05 21:35
and, when a disk is failing, the resilver throughput can be misleadingly high for a number of *days* until the user checks `zpool iostat` and sees the numbers are wrong.

**Comment by richardelling** [comment] 2018-02-05 21:51
In the bad old days, it could be misleading by decades, which is why it was changed to display a non-number when the estimate time was very large. In general, it is not feasible to parse the output of ```zpool status``` to get numbers for computation or comparison, the output is intended for humans.

http://src.illumos.org/source/diff/illumos-gate/usr/src/cmd/zpool/zpool_main.c?r2=%2Fillumos-gate%2Fusr%2Fsrc%2Fcmd%2Fzpool%2Fzpool_main.c%4073d314ce9dc7feccc3b74f8109a8f7ee8ff67b42&r1=%2Fillumos-gate%2Fusr%2Fsrc%2Fcmd%2Fzpool%2Fzpool_main.c%40f9af39bacaaa0f9dda3b75ff6858b9f3988a39af

**Comment by kpande** [comment] 2018-02-05 21:52
why output the information there at all then?

**Closed** 2019-04-02 19:48 UTC
Labels: Type: Regression
