### ISSUE TITLE
zfs send -R pool/dataset@snap fails with message "cannot hold: operation not applicable to datasets of this type - internal error: Invalid argument"

### ISSUE THREAD

**Issue by mailinglists35** [zfsonlinux/zfs#5595] opened 2017-01-14 17:40 UTC
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | debian
Distribution Version    | stretch
Linux Kernel                 | 4.8.15-2
Architecture                 | amd64
ZFS Version                  | v0.7.0-rc2_117_g2dbf1bf82
SPL Version                  | v0.7.0-rc2_9_g120faef

### Describe the problem you're observing
```
root@linux:~# zfs send -R pool/iphone@zfs-auto-snap_daily-2017-01-10-0341 > /dev/null
cannot hold: operation not applicable to datasets of this type
internal error: Invalid argument
Aborted

root@linux:~#
```
### Describe how to reproduce the problem
`pool/iphone` is a dataset (on a mirror pool) that contains 7 levels of nested datasets (example: `pool/iphone/private/var/mobile/Containers/Bundle/Application/0D52A067-64D1-4C13-8B14-AD9E3E410384` ; under `Application` there are 870 datasets and in the tree there are two other places that contain another 895 and 130 datasets respectively)
each dataset is auto-snapshotted daily/monthly by `zfs-auto-snapshot`, giving a total number of ~90.000 (snapshots*datasets)
### Include any warning/errors/backtraces from the system logs
strace on zfs at the time of abort. let me know what else you need me to provide.

```
[...]
ioctl(3, _IOC(0, 0x5a, 0x12, 0x00), 0x7ffc779cf5c0) = 0
ioctl(3, _IOC(0, 0x5a, 0x12, 0x00), 0x7ffc779cf9f0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = -1 ENOMEM (Cannot allocate memory)
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = -1 ENOMEM (Cannot allocate memory)
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = -1 ENOMEM (Cannot allocate memory)
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = -1 ESRCH (No such process)
ioctl(3, _IOC(0, 0x5a, 0x12, 0x00), 0x7ffc779cf5c0) = 0
ioctl(3, _IOC(0, 0x5a, 0x12, 0x00), 0x7ffc779cf9f0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = -1 ENOMEM (Cannot allocate memory)
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = -1 ENOMEM (Cannot allocate memory)
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = -1 ENOMEM (Cannot allocate memory)
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = 0
ioctl(3, _IOC(0, 0x5a, 0x15, 0x00), 0x7ffc779cc3a0) = -1 ESRCH (No such process)
brk(0x5556fb894000)                     = 0x5556fb894000
brk(0x5556fb8b5000)                     = 0x5556fb8b5000
brk(0x5556fb8d6000)                     = 0x5556fb8d6000
brk(0x5556fb8f7000)                     = 0x5556fb8f7000
brk(0x5556fb918000)                     = 0x5556fb918000
brk(0x5556fb939000)                     = 0x5556fb939000
brk(0x5556fb95a000)                     = 0x5556fb95a000
brk(0x5556fb97b000)                     = 0x5556fb97b000
brk(0x5556fb99c000)                     = 0x5556fb99c000
brk(0x5556fb9bd000)                     = 0x5556fb9bd000
brk(0x5556fb9de000)                     = 0x5556fb9de000
brk(0x5556fb9ff000)                     = 0x5556fb9ff000
brk(0x5556fba20000)                     = 0x5556fba20000
brk(0x5556fba41000)                     = 0x5556fba41000
brk(0x5556fba62000)                     = 0x5556fba62000
brk(0x5556fba83000)                     = 0x5556fba83000
brk(0x5556fbaa4000)                     = 0x5556fbaa4000
brk(0x5556fbac5000)                     = 0x5556fbac5000
brk(0x5556fbae6000)                     = 0x5556fbae6000
brk(0x5556fbb07000)                     = 0x5556fbb07000
brk(0x5556fbb28000)                     = 0x5556fbb28000
brk(0x5556fbb49000)                     = 0x5556fbb49000
brk(0x5556fbb6a000)                     = 0x5556fbb6a000
brk(0x5556fbb8b000)                     = 0x5556fbb8b000
brk(0x5556fbbac000)                     = 0x5556fbbac000
brk(0x5556fbbcd000)                     = 0x5556fbbcd000
brk(0x5556fbbee000)                     = 0x5556fbbee000
brk(0x5556fbc0f000)                     = 0x5556fbc0f000
brk(0x5556fbc30000)                     = 0x5556fbc30000
brk(0x5556fbc51000)                     = 0x5556fbc51000
brk(0x5556fbc72000)                     = 0x5556fbc72000
brk(0x5556fbc93000)                     = 0x5556fbc93000
brk(0x5556fbcb4000)                     = 0x5556fbcb4000
brk(0x5556fbcd5000)                     = 0x5556fbcd5000
brk(0x5556fbcf6000)                     = 0x5556fbcf6000
brk(0x5556fbd17000)                     = 0x5556fbd17000
brk(0x5556fbd38000)                     = 0x5556fbd38000
brk(0x5556fbd59000)                     = 0x5556fbd59000
brk(0x5556fbd7a000)                     = 0x5556fbd7a000
brk(0x5556fbd9b000)                     = 0x5556fbd9b000
brk(0x5556fbdbc000)                     = 0x5556fbdbc000
brk(0x5556fbddd000)                     = 0x5556fbddd000
brk(0x5556fbdfe000)                     = 0x5556fbdfe000
brk(0x5556fbe1f000)                     = 0x5556fbe1f000
brk(0x5556fbe40000)                     = 0x5556fbe40000
brk(0x5556fccdc000)                     = 0x5556fccdc000
mmap(NULL, 30461952, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f128c1ca000
ioctl(5, _IOC(0, 0x5a, 0x30, 0x00), 0x7ffc779cf520) = -1 EINVAL (Invalid argument)
munmap(0x7f128c1ca000, 30461952)        = 0
write(2, "cannot hold: operation not appli"..., 63) = 63
open("/usr/share/locale/en_US/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
write(2, "internal error: Invalid argument"..., 33) = 33
rt_sigprocmask(SIG_UNBLOCK, [ABRT], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1], [], 8) = 0
getpid()                                = 11216
gettid()                                = 11216
tgkill(11216, 11216, SIGABRT)           = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
--- SIGABRT {si_signo=SIGABRT, si_code=SI_TKILL, si_pid=11216, si_uid=0} ---
+++ killed by SIGABRT +++
```

**Comment by mailinglists35** [comment] 2017-01-14 17:44
the only related issue to zfs send containing my message is #2268 but in my case is a bit different

**Comment by mailinglists35** [comment] 2017-01-14 17:59
```
root@linux:/usr/local/src/zfs/git/spl# zpool get all pool
NAME        PROPERTY                    VALUE                       SOURCE
pool  size                        928G                        -
pool  capacity                    94%                         -
pool  altroot                     -                           default
pool  health                      ONLINE                      -
pool  guid                        <guid removed>         -
pool  version                     -                           default
pool  bootfs                      -                           default
pool  delegation                  on                          default
pool  autoreplace                 off                         default
pool  cachefile                   -                           default
pool  failmode                    continue                    local
pool  listsnapshots               off                         default
pool  autoexpand                  off                         default
pool  dedupditto                  0                           default
pool  dedupratio                  1.17x                       -
pool  free                        50.1G                       -
pool  allocated                   878G                        -
pool  readonly                    off                         -
pool  ashift                      12                          local
pool  comment                     -                           default
pool  expandsize                  -                           -
pool  freeing                     0                           -
pool  fragmentation               52%                         -
pool  leaked                      0                           -
pool  feature@async_destroy       enabled                     local
pool  feature@empty_bpobj         active                      local
pool  feature@lz4_compress        active                      local
pool  feature@spacemap_histogram  active                      local
pool  feature@enabled_txg         active                      local
pool  feature@hole_birth          active                      local
pool  feature@extensible_dataset  enabled                     local
pool  feature@embedded_data       active                      local
pool  feature@bookmarks           enabled                     local
pool  feature@filesystem_limits   enabled                     local
pool  feature@large_blocks        enabled                     local
pool  feature@large_dnode         disabled                    local
pool  feature@sha512              disabled                    local
pool  feature@skein               disabled                    local
pool  feature@edonr               disabled                    local
pool  feature@userobj_accounting  disabled                    local

root@linux:/usr/local/src/zfs/git/spl# zfs get all pool/iphone
NAME                PROPERTY               VALUE                    SOURCE
pool/iphone  type                   filesystem               -
pool/iphone  creation               Fri Dec 11 23:27 2015    -
pool/iphone  used                   43.7G                    -
pool/iphone  available              20.9G                    -
pool/iphone  referenced             1.63G                    -
pool/iphone  compressratio          1.39x                    -
pool/iphone  mounted                no                       -
pool/iphone  quota                  none                     default
pool/iphone  reservation            none                     default
pool/iphone  recordsize             128K                     default
pool/iphone  mountpoint             /mnt/iphone  local
pool/iphone  sharenfs               off                      default
pool/iphone  checksum               on                       default
pool/iphone  compression            lz4                      inherited from pool
pool/iphone  atime                  off                      inherited from pool
pool/iphone  devices                on                       default
pool/iphone  exec                   on                       default
pool/iphone  setuid                 on                       default
pool/iphone  readonly               off                      default
pool/iphone  zoned                  off                      default
pool/iphone  snapdir                hidden                   default
pool/iphone  aclinherit             restricted               default
pool/iphone  canmount               noauto                   local
pool/iphone  xattr                  on                       default
pool/iphone  copies                 1                        default
pool/iphone  version                5                        -
pool/iphone  utf8only               off                      -
pool/iphone  normalization          none                     -
pool/iphone  casesensitivity        sensitive                -
pool/iphone  vscan                  off                      default
pool/iphone  nbmand                 off                      default
pool/iphone  sharesmb               off                      default
pool/iphone  refquota               none                     default
pool/iphone  refreservation         none                     default
pool/iphone  primarycache           all                      default
pool/iphone  secondarycache         all                      default
pool/iphone  usedbysnapshots        32.1M                    -
pool/iphone  usedbydataset          1.63G                    -
pool/iphone  usedbychildren         42.1G                    -
pool/iphone  usedbyrefreservation   0                        -
pool/iphone  logbias                latency                  default
pool/iphone  dedup                  off                      default
pool/iphone  mlslabel               none                     default
pool/iphone  sync                   disabled                 local
pool/iphone  dnodesize              legacy                   default
pool/iphone  refcompressratio       1.51x                    -
pool/iphone  written                0                        -
pool/iphone  logicalused            56.5G                    -
pool/iphone  logicalreferenced      2.19G                    -
pool/iphone  filesystem_limit       none                     default
pool/iphone  snapshot_limit         none                     default
pool/iphone  filesystem_count       none                     default
pool/iphone  snapshot_count         none                     default
pool/iphone  snapdev                hidden                   default
pool/iphone  acltype                off                      default
pool/iphone  context                none                     default
pool/iphone  fscontext              none                     default
pool/iphone  defcontext             none                     default
pool/iphone  rootcontext            none                     default
pool/iphone  relatime               off                      default
pool/iphone  redundant_metadata     all                      default
pool/iphone  overlay                off                      default
pool/iphone  com.sun:auto-snapshot  true                     inherited from pool
```

**Comment by kpande** [comment] 2017-01-14 18:41
this error happens a lot when your kernel module version and userland are out of sync. can you verify this?

**Comment by mailinglists35** [comment] 2017-01-14 18:52
they are both from git master

**Comment by kpande** [comment] 2017-01-14 19:01
I'm sure you compiled and installed git master, but did you actually verify the binaries are what you expect them to be? Is the loaded kernel version what you expect it to be? You did run another version before, right? Did you completely remove it first? you mention debian stretch and the dkms packages behave differently from the kmod deb that are built from git.

**Comment by mailinglists35** [comment] 2017-01-14 19:01
look at versions I have reported for spl and zfs, i have installed this way:
git clone <url of spl>
git clone <url of zfs>
in each dir: ./autogen.sh; ./configure; make; make install
then
git pull
and again configure make make install

**Comment by mailinglists35** [comment] 2017-01-14 19:01
there is no dkms version, i have wiped debian pkgs and i am only running from usr/local from make install

**Comment by kpande** [comment] 2017-01-14 19:02
and you don't have any libzfs or anything installed from debian repo?

**Comment by mailinglists35** [comment] 2017-01-14 19:02
none, i have removed all

**Comment by mailinglists35** [comment] 2017-01-14 19:03
and between compiles i have modprobe -r / modprobe new modules

**Comment by mailinglists35** [comment] 2017-01-14 19:46
to clear any potential criticism, i have `make uninstall` then `make deb`.

**Comment by mailinglists35** [comment] 2017-01-14 19:48
and by the way, this is reproductible with included debian version and with ppa-zfs-daily.
i was running master just to rule out any possible patch since latest release....

**Comment by mailinglists35** [comment] 2017-01-14 22:09
I'm getting the same behaviour on FreeBSD-11-RELEASE
```
internal error: Unknown error: 122
Abort (core dumped)
```

**Comment by mailinglists35** [comment] 2017-01-15 00:33
FWIW, last command output of `zfs send -vR` before printing the error is

lots of
```send from @zfs-auto-snap_daily-2017-01-10-0341 to pool/iphone/private/var/mobile/Containers/Data/Application/96575E40-3E5C-404E-B340-CF1ED588A151@zfs-auto-snap_daily-2017-01-14-0335```

then

```total estimated size is 56.5G```

then the error already pasted

individually sending -vR just that last dataset+snap works ok.

**Comment by loli10K** [comment] 2017-09-02 07:06
Closing as duplicate of #6572

**Closed by loli10K** 2017-09-02 07:06 UTC
