### ISSUE TITLE
send performance is very bad while all cpu occupy by low priority process

### ISSUE THREAD

**Issue by AndCycle** [zfsonlinux/zfs#3607] opened 2015-07-19 10:42 UTC
my system have BOINC projects running on it,
it donate the cpu time for grid computing,
it will run one process per cpu core,

but current ZoL performance seems heavily effect by this,

when BOINC is on, the send performance on 6 disk raidz2 is as low as 20MB/s, 
nice 19 on BOINC won't help

when it's off, it easily top out 400MB/s,

is there any I can tune on module parameter? or I have to touch the source?

**Comment by AndCycle** [comment] 2015-07-19 18:02
tracing code and found this in spa.c,

I tought lower priority is bigger number not smaller?
or am I wrong? I am not familiar with prio

```
pri_t pri = maxclsyspri;
/*
 * The write issue taskq can be extremely CPU
 * intensive.  Run it at slightly lower priority
 * than the other taskqs.
 */
if (t == ZIO_TYPE_WRITE && q == ZIO_TASKQ_ISSUE)
	pri--;

```

**Comment by behlendorf** [comment] 2015-07-20 16:50
This code could certainly use a second look to make sure it's doing something reasonable under Linux.  The idea is to take the specified priority and translate it to the matching nice setting for the taskq threads.  See http://lxr.free-electrons.com/source/include/linux/sched/prio.h#L24 for additional detail on how this is done.

The default values were originally selected for the Solaris scheduler so they may not be the optimal setting for Linux.  It's definitely an area worth investigating.  To make benchmarking easier I'd suggest temporarily adding a module option so you can explicitly set the priority of this taskq when it's created.  Then see what impact specific values have.  That way we can seriously consider changing the default.

**Comment by AndCycle** [comment] 2015-07-20 17:09
I patch zfs/spl maxclsyspri to default 70, which make my system have a reasonable speed I never see before,

before this simple tuning,
a full send from my main pool 5TBx6 raidz2 require about 2 weeks to finish,
now it's gonna finish in one more day, at least 3 times faster,

this prio value definitely require some attention,
and I think you can simply test how bad this is by spawning cpu intensive process for each core with nice 19,
it killed performance just that easy.

**Comment by kernelOfTruth** [comment] 2015-07-20 17:12
@AndCycle care to share your patch ?  =)

**Comment by AndCycle** [comment] 2015-07-20 17:17
@kernelOfTruth 
sorry I never use github's repository before so I gonna post those simple patch here

prio issue only effect if your cpu is always full,
for people have bunch of idle cpu time this doesn't make any different.

for SPL
```
diff -rupN a/include/sys/sysmacros.h b/include/sys/sysmacros.h
--- a/include/sys/sysmacros.h   2015-06-24 07:58:01.000000000 +0800
+++ b/include/sys/sysmacros.h   2015-07-20 08:24:19.001026533 +0800
@@ -93,7 +93,7 @@
  * Treat shim tasks as SCHED_NORMAL tasks
  */
 #define minclsyspri                    (MAX_RT_PRIO)
-#define maxclsyspri                    (MAX_PRIO-1)
+#define maxclsyspri                    DEFAULT_PRIO

 #ifndef NICE_TO_PRIO
 #define NICE_TO_PRIO(nice)             (MAX_RT_PRIO + (nice) + 20)
```

for ZFS
```
diff -rupN a/include/sys/zfs_context.h b/include/sys/zfs_context.h
--- a/include/sys/zfs_context.h 2015-04-09 06:32:38.000000000 +0800
+++ b/include/sys/zfs_context.h 2015-07-20 01:52:22.119260755 +0800
@@ -611,7 +611,7 @@ extern void delay(clock_t ticks);
 #define        max_ncpus       64

 #define        minclsyspri     60
-#define        maxclsyspri     99
+#define        maxclsyspri     70

 #define        CPU_SEQID       (pthread_self() & (max_ncpus - 1))
```

minor fix ZFS
```
diff -rupN a/module/zfs/spa.c b/module/zfs/spa.c
--- a/module/zfs/spa.c  2015-06-23 09:14:46.000000000 +0800
+++ b/module/zfs/spa.c  2015-07-20 02:05:09.200483683 +0800
@@ -880,7 +880,7 @@ spa_taskqs_init(spa_t *spa, zio_type_t t
                         * than the other taskqs.
                         */
                        if (t == ZIO_TYPE_WRITE && q == ZIO_TASKQ_ISSUE)
-                               pri--;
+                               pri++;

                        tq = taskq_create_proc(name, value, pri, 50,
                            INT_MAX, spa->spa_proc, flags);
```

**Comment by kernelOfTruth** [comment] 2015-07-20 17:52
@AndCycle so it won't apply to my system most of the time - unless I stress-test or stress-use it (gaming, compiling, transferring files, etc. - at the same time)

Most likely a condition larger servers are very often in =)

Thanks !

**Comment by behlendorf** [comment] 2015-07-23 21:18
That's an impressive improvement, thanks for running this to ground!  I've taken your original patch and reworked it in to a form which we can get merged.  @AndCycle could you please verify that the proposed patch in #3622 solves your issue.  You'll need to use the latest version of the SPL because I've added a new `defclsyspri` rather than redefining `maxclsyspri` as you did in your original patch.

That patch also doesn't contain the `pri--` to `pri++` change.  The intention here is to give the more CPU intensive threads a lower priority so  they run first and accomplish their work as soon as possible.  I believe this to be correct, but if your testing shows otherwise I'm willing to be convinced!

**Closed** 2015-07-29 14:29 UTC
Labels: Performance

**Comment by AndCycle** [comment] 2015-07-30 11:18
@behlendorf your work looks fine,

but probably won't test your patch on my system, 
there are few line need to be removed in order to clean apply on 0.6.4 which I don't have time to read though,

I think I can wait for 0.6.5 to see how it works out :)

**Comment by behlendorf** [comment] 2015-07-30 21:29
@AndCycle no problem.  Thanks for drawing our attention to this issue so we could address it.

**Comment by avg-I** [comment] 2016-03-28 16:24
@behlendorf while doing some research I have come accross this rather old issue and I have a comment (which is possibly irrelevant now).
You said:
> That patch also doesn't contain the pri-- to pri++ change. The intention here is to give the more CPU intensive threads a lower priority so they run first and accomplish their work as soon as possible. I believe this to be correct, but if your testing shows otherwise I'm willing to be convinced!

I believe that on Solaris / illumos the greater numbers represent the higher / better priorities.
I believe that the relation is the opposite on Linux.  That's certainly the case on FreeBSD.
So, I think that the intention in the original code is to a give a lower (worse) priority to CPU-hungry threads, so that they do not stall other threads for too long.

**Comment by behlendorf** [comment] 2016-03-29 16:52
@avg-I thanks for commenting.  After taking another look at FreeBSD and illumos we determined the same thing, when 1229323d5f82bcb0525b312c80330968cd41466e was finally merged to sort of priorities we did tale that in to account and I believe got it as intended.
