### ISSUE TITLE
Potential SPL memory leak

### ISSUE THREAD

**Issue by kbdone** [zfsonlinux/zfs#3029] opened 2015-01-21 21:18 UTC
I've noticed for some time using ZoL 0.6.3 on Debian (2.6.32) that the slab just keeps growing and growing. We use ZFS to host our VMs, so it means a reboot of the hypervisor every so often. It looks like about 1GB/week and since out hosts have about 280GB I haven't been pushy about the issue. 

I haven't rebooted the host yet, so here is the evidence I have

Contents of ZFS conf
```
root@balthasar:/# cat /etc/modprobe.d/zfs.conf
options zfs zfs_arc_min=4294967296
options zfs zfs_arc_max=17179869184
options zfs zfs_prefetch_disable=1
```
Arc stats
```
root@balthasar:/# arcstat.py
    time  read  miss  miss%  dmis  dm%  pmis  pm%  mmis  mm%  arcsz     c  
16:02:55     5     1     20     1   20     0    0     0    0    15G   16G  
```
However, slab takes up
```
root@balthasar:/# cat /proc/spl/kmem/slab | awk '{ SUM += $3} END { print SUM/1024/1024/1024}' 
116.851
```
A more detailed look shows where
```
root@balthasar:/# cat /proc/spl/kmem/slab 
--------------------- cache -------------------------------------------------------  ----- slab ------  ---- object -----  --- emergency ---
name                                    flags      size     alloc slabsize  objsize  total alloc   max  total alloc   max  dlock alloc   max
spl_vn_cache                          0x00020      4096      1760     4096       88      1     1     6     21    20   126      0     0     0
spl_vn_file_cache                     0x00020      4096      1920     4096       96      1     1     5     21    20   105      0     0     0
spl_zlib_workspace_cache              0x00240         0         0  8388608   268072      0     0     0      0     0     0      0     0     0
space_seg_cache                       0x00020  69357568  19028736     4096       64  16933 12419 28846  643454 297324 1096148      0     0     0
ddt_cache                             0x00040    524288    248400   524288    24840      1     1     2     21    10    42      0     0     0
ddt_entry_cache                       0x00020         0         0     8192      448      0     0     0      0     0     0      0     0     0
zio_cache                             0x00040   7176192   1494368    32768     1072    219   137  1599   6351  1394 46371      0     0     0
zio_link_cache                        0x00020    671744    130896     4096       48    164   111  1037   7380  2727 46665      0     0     0
zio_vdev_cache                        0x00040 113246208 100937760  4194304   131088     27    27    52    810   770  1538      0     0     0
zio_buf_512                           0x00020  32899072  15158272    32768      512   1004  1004  1085  31124 29606 33635      0     0     0
zio_data_buf_512                      0x00020   2326528    946688    32768      512     71    71    81   2201  1849  2511      0     0     0
zio_buf_1024                          0x00040   1572864    860160    32768     1024     48    48    93   1008   840  1953      0     0     0
zio_data_buf_1024                     0x00040   1703936    921600    32768     1024     52    52   120   1092   900  2520      0     0     0
zio_buf_1536                          0x00040   2686976   1638912    65536     1536     41    41    49   1271  1067  1519      0     0     0
zio_data_buf_1536                     0x00040   3080192   1437696    65536     1536     47    47    58   1457   936  1798      0     0     0
zio_buf_2048                          0x00040   3211264   2410496    65536     2048     49    49    57   1225  1177  1425      0     0     0
zio_data_buf_2048                     0x00040  54919168  42100736    65536     2048    838   838   844  20950 20557 21100      0     0     0
zio_buf_2560                          0x00040   3866624   2383360    65536     2560     59    59    63   1239   931  1323      0     0     0
zio_data_buf_2560                     0x00040   3276800   2032640    65536     2560     50    50    65   1050   794  1365      0     0     0
zio_buf_3072                          0x00040   3866624   2383872    65536     3072     59    59   103   1062   776  1854      0     0     0
zio_data_buf_3072                     0x00040   3735552   2737152    65536     3072     57    57   109   1026   891  1962      0     0     0
zio_buf_3584                          0x00040   4980736   3143168   131072     3584     38    38    57   1178   877  1767      0     0     0
zio_data_buf_3584                     0x00040   4980736   3196928   131072     3584     38    38    75   1178   892  2325      0     0     0
zio_buf_4096                          0x00040 289406976 138276864   262144     4096   1104  1104  1151  34224 33759 35681      0     0     0
zio_data_buf_4096                     0x00040 1387528192 670838784   262144     4096   5293  5293  5303  164083 163779 164393      0     0     0
zio_buf_5120                          0x00040   4325376   2990080   131072     5120     33    33    53    693   584  1113      0     0     0
zio_data_buf_5120                     0x00040   5373952   3665920   131072     5120     41    41    67    861   716  1407      0     0     0
zio_buf_6144                          0x00040   4325376   2224128   131072     6144     33    33   166    594   362  2988      0     0     0
zio_data_buf_6144                     0x00040   3932160   2531328   131072     6144     30    30    72    540   412  1296      0     0     0
zio_buf_7168                          0x00040   4456448   2250752   262144     7168     17    17    54    527   314  1674      0     0     0
zio_data_buf_7168                     0x00040   5242880   3548160   262144     7168     20    20    35    620   495  1085      0     0     0
zio_buf_8192                          0x00040  11534336   4513792   262144     8192     44    35   176    924   551  3696      0     0     0
zio_data_buf_8192                     0x00040   7602176   2973696   262144     8192     29    29    57    609   363  1197      0     0     0
zio_buf_10240                         0x00040   7340032   4935680   262144    10240     28    28    47    588   482   987      0     0     0
zio_data_buf_10240                    0x00040   7864320   5457920   262144    10240     30    30    57    630   533  1197      0     0     0
zio_buf_12288                         0x00040  11010048   7077888   524288    12288     21    20    50    651   576  1550      0     0     0
zio_data_buf_12288                    0x00040   9961472   6082560   524288    12288     19    19    38    589   495  1178      0     0     0
zio_buf_14336                         0x00040  10485760   6666240   524288    14336     20    20    31    620   465   961      0     0     0
zio_data_buf_14336                    0x00040   9437184   6623232   524288    14336     18    18    39    558   462  1209      0     0     0
zio_buf_16384                         0x00040 12264144896 5455953920   524288    16384  23392 23392 28198  584800 333005 704950      0     0     0
zio_data_buf_16384                    0x00040 504889344 391725056   524288    16384    963   963   974  24075 23909 24350      0     0     0
zio_buf_20480                         0x00040  15204352  11386880   524288    20480     29    28    77    609   556  1617      0     0     0
zio_data_buf_20480                    0x00040  15728640  10936320   524288    20480     30    30    55    630   534  1155      0     0     0
zio_buf_24576                         0x00040  16777216  11476992   524288    24576     32    32    88    576   467  1584      0     0     0
zio_data_buf_24576                    0x00040  16777216  14155776   524288    24576     32    32    66    576   576  1188      0     0     0
zio_buf_28672                         0x00040  20971520  15052800  1048576    28672     20    19    55    620   525  1705      0     0     0
zio_data_buf_28672                    0x00040  18874368  15998976  1048576    28672     18    18    39    558   558  1209      0     0     0
zio_buf_32768                         0x00040  24117248  18087936  1048576    32768     23    22    88    644   552  2464      0     0     0
zio_data_buf_32768                    0x00040  23068672  20185088  1048576    32768     22    22    45    616   616  1260      0     0     0
zio_buf_36864                         0x00040  23068672  19501056  1048576    36864     22    22    61    550   529  1525      0     0     0
zio_data_buf_36864                    0x00040  24117248  20017152  1048576    36864     23    23    48    575   543  1200      0     0     0
zio_buf_40960                         0x00040  29360128  22814720  1048576    40960     28    27    67    644   557  1541      0     0     0
zio_data_buf_40960                    0x00040  26214400  23552000  1048576    40960     25    25    47    575   575  1081      0     0     0
zio_buf_45056                         0x00040  27262976  21626880  1048576    45056     26    26    72    546   480  1512      0     0     0
zio_data_buf_45056                    0x00040  27262976  23248896  1048576    45056     26    26    53    546   516  1113      0     0     0
zio_buf_49152                         0x00040  31457280  21970944  1048576    49152     30    29    71    570   447  1349      0     0     0
zio_data_buf_49152                    0x00040  33554432  28950528  1048576    49152     32    31    59    608   589  1121      0     0     0
zio_buf_53248                         0x00040  33554432  25239552  1048576    53248     32    32    81    576   474  1458      0     0     0
zio_data_buf_53248                    0x00040  31457280  28753920  1048576    53248     30    30    63    540   540  1134      0     0     0
zio_buf_57344                         0x00040  34603008  29360128  1048576    57344     33    32    90    561   512  1530      0     0     0
zio_data_buf_57344                    0x00040  35651584  33144832  1048576    57344     34    34    64    578   578  1088      0     0     0
zio_buf_61440                         0x00040  39845888  24268800  2097152    61440     19    19    47    589   395  1457      0     0     0
zio_data_buf_61440                    0x00040  41943040  38092800  2097152    61440     20    20    37    620   620  1147      0     0     0
zio_buf_65536                         0x00040  39845888  31784960  2097152    65536     19    19   113    570   485  3390      0     0     0
zio_data_buf_65536                    0x00040 163577856  84017152  2097152    65536     78    78  1887   2340  1282 56610      0     0     0
zio_buf_69632                         0x00040  44040192  36626432  2097152    69632     21    21    44    588   526  1232      0     0     0
zio_data_buf_69632                    0x00040  41943040  32309248  2097152    69632     20    20    32    560   464   896      0     0     0
zio_buf_73728                         0x00040  46137344  31481856  2097152    73728     22    22    49    572   427  1274      0     0     0
zio_data_buf_73728                    0x00040  50331648  37748736  2097152    73728     24    24    37    624   512   962      0     0     0
zio_buf_77824                         0x00040  48234496  43814912  2097152    77824     23    23    55    575   563  1375      0     0     0
zio_data_buf_77824                    0x00040  50331648  44204032  2097152    77824     24    24    40    600   568  1000      0     0     0
zio_buf_81920                         0x00040  50331648  35717120  2097152    81920     24    24    53    576   436  1272      0     0     0
zio_data_buf_81920                    0x00040  50331648  44564480  2097152    81920     24    24    38    576   544   912      0     0     0
zio_buf_86016                         0x00040  58720256  37588992  2097152    86016     28    28    53    644   437  1219      0     0     0
zio_data_buf_86016                    0x00040  52428800  43438080  2097152    86016     25    25    36    575   505   828      0     0     0
zio_buf_90112                         0x00040  56623104  44785664  2097152    90112     27    27    48    594   497  1056      0     0     0
zio_data_buf_90112                    0x00040  54525952  51544064  2097152    90112     26    26    40    572   572   880      0     0     0
zio_buf_94208                         0x00040  58720256  47386624  2097152    94208     28    27    62    588   503  1302      0     0     0
zio_data_buf_94208                    0x00040  58720256  52756480  2097152    94208     28    28    40    588   560   840      0     0     0
zio_buf_98304                         0x00040  60817408  40599552  2097152    98304     29    29    64    580   413  1280      0     0     0
zio_data_buf_98304                    0x00040  62914560  58982400  2097152    98304     30    30    41    600   600   820      0     0     0
zio_buf_102400                        0x00040  65011712  34508800  2097152   102400     31    31    53    589   337  1007      0     0     0
zio_data_buf_102400                   0x00040  67108864  60313600  2097152   102400     32    31    44    608   589   836      0     0     0
zio_buf_106496                        0x00040  71303168  46645248  2097152   106496     34    34    67    612   438  1206      0     0     0
zio_data_buf_106496                   0x00040  67108864  54525952  2097152   106496     32    32    45    576   512   810      0     0     0
zio_buf_110592                        0x00040  71303168  48771072  2097152   110592     34    33    63    612   441  1134      0     0     0
zio_data_buf_110592                   0x00040  67108864  53637120  2097152   110592     32    32    45    576   485   810      0     0     0
zio_buf_114688                        0x00040  73400320  58834944  2097152   114688     35    35    74    595   513  1258      0     0     0
zio_data_buf_114688                   0x00040  67108864  62390272  2097152   114688     32    32    51    544   544   867      0     0     0
zio_buf_118784                        0x00040         0         0  2097152   118784      0     0     0      0     0     0      0     0     0
zio_data_buf_118784                   0x00040         0         0  2097152   118784      0     0     1      0     0    17      0     0     0
zio_buf_122880                        0x00040         0         0  2097152   122880      0     0     0      0     0     0      0     0     0
zio_data_buf_122880                   0x00040         0         0  2097152   122880      0     0     0      0     0     0      0     0     0
zio_buf_126976                        0x00040         0         0  4194304   126976      0     0     0      0     0     0      0     0     0
zio_data_buf_126976                   0x00040         0         0  4194304   126976      0     0     0      0     0     0      0     0     0
zio_buf_131072                        0x00040 5565841408 5319032832  4194304   131072   1327  1327  1581  41137 40581 49011      0     0     0
zio_data_buf_131072                   0x00040 101766397952 97417166848  4194304   131072  24263 24263 24373  752153 743234 755540      0     0     0
lz4_cache                             0x00040  13107200  12189696   524288    16384     25    24    24    775   744   744      0     0     0
sa_cache                              0x00020    102400     32720     4096       80     25    25    25    825   409   825      0     0     0
spill_cache                           0x00040  33554432  28966912  4194304   131072      8     8    10    248   221   310      0     0     0
dnode_t                               0x00020  89653248  70385328    16384      936   5472  5472  6185  87552 75198 98960      0     0     0
dmu_buf_impl_t                        0x00020  51699712  43260560     8192      280   6311  6311  9445  157775 154502 236125      0     0     0
arc_buf_hdr_t                         0x00020 746528768 567114336     8192      288  91129 91129 108415  2187096 1969147 2601960      0     0     0
arc_buf_t                             0x00020  82149376  32549760     4096       72  20056 20056 20806  722016 452080 749016      0     0     0
l2arc_buf_hdr_t                       0x00020  69283840  33828000     4096       40  16915 16914 35105  845750 845700 1755250      0     0     0
zil_lwb_cache                         0x00020         0         0     4096      200      0     0     0      0     0     0      0     0     0
zfs_znode_cache                       0x00020    917504    453744    32768     1104     28    28    28    784   411   784      0     0     0
```
Just so there are no doubts about the module's max
```
root@balthasar:/# cat /sys/module/zfs/parameters/zfs_arc_max
17179869184
```
Lastly, the version of ZFS being run
```
root@balthasar:/# dpkg --list | grep zfs
ii  debian-zfs                       7~wheezy                           amd64        Native ZFS filesystem metapackage for Debian.
ii  dkms                             2.2.0.3-1.2+zfs6                   all          Dynamic Kernel Module Support Framework
ii  grub-common                      2.01-22debian1+zfs3-0.6.3-2~wheezy amd64        GRand Unified Bootloader (common files)
ii  grub-pc                          2.01-22debian1+zfs3-0.6.3-2~wheezy amd64        GRand Unified Bootloader, version 2 (PC/BIOS version)
ii  grub-pc-bin                      2.01-22debian1+zfs3-0.6.3-2~wheezy amd64        GRand Unified Bootloader, version 2 (PC/BIOS binaries)
ii  grub2-common                     2.01-22debian1+zfs3-0.6.3-2~wheezy amd64        GRand Unified Bootloader (common files for version 2)
rc  libzfs1                          0.6.2-4~wheezy                     amd64        Native ZFS filesystem library for Linux
ii  libzfs2                          0.6.3-1~wheezy                     amd64        Native ZFS filesystem library for Linux
ii  zfs-dkms                         0.6.3-1~wheezy                     all          Native ZFS filesystem kernel modules for Linux
ii  zfsonlinux                       3~wheezy                           all          archive.zfsonlinux.org trust package
ii  zfsutils                         0.6.3-1~wheezy                     amd64        command-line tools to manage ZFS filesystems
```
Severals months ago (last reboot time) when talking in #zfsonlinux we worked out that it might be l2arc related. So here is my pool info (yes I use l2arc)
```
root@balthasar:/# zpool status
  pool: epoch
 state: ONLINE
  scan: scrub repaired 0 in 12h55m with 0 errors on Sat Jan 17 12:55:32 2015
config:

	NAME        STATE     READ WRITE CKSUM
	epoch       ONLINE       0     0     0
	  mirror-0  ONLINE       0     0     0
	    a0      ONLINE       0     0     0
	    a1      ONLINE       0     0     0
	    a2      ONLINE       0     0     0
	  mirror-1  ONLINE       0     0     0
	    b0      ONLINE       0     0     0
	    b1      ONLINE       0     0     0
	    b2      ONLINE       0     0     0
	  mirror-2  ONLINE       0     0     0
	    c0      ONLINE       0     0     0
	    c1      ONLINE       0     0     0
	    c2      ONLINE       0     0     0
	  mirror-3  ONLINE       0     0     0
	    d0      ONLINE       0     0     0
	    d1      ONLINE       0     0     0
	    d2      ONLINE       0     0     0
	  mirror-4  ONLINE       0     0     0
	    e0      ONLINE       0     0     0
	    e1      ONLINE       0     0     0
	    e2      ONLINE       0     0     0
	cache
	  l2arc0    ONLINE       0     0     0

errors: No known data errors
```
If you need any further info, or perhaps by this point this is a duplicate, please let me know.

**Comment by chrisrd** [comment] 2015-01-21 23:01
Sorry, no answers here, but...

(`/tmp/kmem-slab` is your  `/proc/spl/kmem/slab` dump above.)

My first thought was "slab fragmentation", however:

```
$ awk '{ size+=$3; alloc+=$4; } END { printf "size: %i GiB, alloc: %i GiB, utilisation: %.2f%%\n", size/(2^30), alloc/(2^30), 100*alloc/size }'  /tmp/kmem-slab
size: 116 GiB, alloc: 104 GiB, utilisation: 89.37%
```

...shows your utilisation is actually reasonable.

Your `zio_data_buf_131072` line shows you have 91G being used by these objects (taking up 95G with the slab overheads included), pretty much explaining the entire over-usage.

So the issue is not technically a "leak" where ZFS has lost track of memory, but a question of why these objects aren't being freed.

The fact that the `alloc` (number of objects currently allocated) at 726K is less than the `max` (maximum used)  at 738K shows that **some** freeing has occurred, so they're not being skipped altogether.

How is your ZFS being used, e.g. are the VMs sitting on ZVOLs or files?

I wonder if the system simply struggling to free the objects or is it not even trying (i.e. they're pinned there somehow)? E.g. how is the ZFS CPU utilisation looking, how busy are the disks, are you getting any "soft lockup" messages in your kernel logs, etc.?

**Comment by prakashsurya** [comment] 2015-01-22 04:47
This is just a shot in the dark, as I didn't thoroughly read through the bug, but any chance that you're hitting this leak: https://www.illumos.org/issues/5222 ? Is that fixed in ZoL? I don't think it was fixed in illumos until this patch (which isn't yet in ZoL, AFAIK):
```
commit 244781f10dcd82684fd8163c016540667842f203
Author: Prakash Surya <prakash.surya@delphix.com>
Date:   Mon Jan 12 19:52:19 2015 -0800

    5497 lock contention on arcs_mtx
    Reviewed by: George Wilson <george.wilson@delphix.com>
    Reviewed by: Matthew Ahrens <mahrens@delphix.com>
    Reviewed by: Richard Elling <richard.elling@richardelling.com>
    Approved by: Dan McDonald <danmcd@omniti.com>
```

**Comment by chrisrd** [comment] 2015-01-22 08:18
@kbdone Sorry, I didn't take into consideration your `arcstat.py` output showing that ZFS thinks there's only 15G of ARC being used. I.e. it does look like a leak.

@prakashsurya Yep, given [the thread that started it all off] (http://thread.gmane.org/gmane.os.freebsd.current/155757/focus=155781) and linked to from [illumos 5222] (https://www.illumos.org/issues/5222) is talking about discrepancies with `zio_data_buf_131072` it looks like you could be right there. (And no, your "5497 lock contention on arcs_mtx" isn't in ZoL yet).

**Comment by kbdone** [comment] 2015-01-22 15:37
@chrisrd and @prakashsurya even thought it might be related to 5222 let me give you the info you asked for.

* We are using ZFS for VM storage directly on a ZFS dataset
* We are also using ZFS to store files for an SMB share via EXT4 on top of a ZVOL (to get the ACL stuff we wanted)

Am I correct to think that the illumos issue listed above occurs only when 

* We are using an l2arc 
* We are using compression (lz4 for us) 
(Both of the above are compressed)

I assume the only way to recover this RAM is to unload the module or perform a reboot (which unloads the module). Is there some incompatability with the illumos patch and ZoL or is it as simple as no-one having done a "commit" yet?

Lastly, I am only a user of ZFS at this point. Is there some way I can confirm for certain my error is related to the illumos 5222 bug, or have I already?

Thanks!

**Comment by dweeezil** [comment] 2015-01-22 17:17
I'll add some l2arc to one of my systems today and see whether I can duplicate the problem.  The patch referred to above seems to port cleanly to ZoL (see dweeezil/zfs@01a4fb8).  If I can duplicate the problem, I'll see whether the patch fixes it.  Unfortunately @kbdone appears to be using a 2.6 kernel and stock 0.6.3 so there are going to be a world of other differences involved in my testing.

**Comment by dweeezil** [comment] 2015-01-23 00:00
I was not able to duplicate the problem. I could not get any apparent leakage of the various zio objects (128k in particular) in either the Linux or SPL slabs.

**Comment by chrisrd** [comment] 2015-01-23 00:44
@dweeezil What sort of testing? From [the original thread](http://thread.gmane.org/gmane.os.freebsd.current/155757/focus=155781) it seems there wasn't a way found to quickly reproduce the problem. The first leak:

> We have observed that arc_release() can be called concurrently with a l2arc in-flight write

...seems like it might be associated with lots of concurrent activity, perhaps in conjunction with memory pressure?

For the second leak:

> we have observed that arc_hdr_destroy() can be called from arc_write_done() for a zio with ZIO_FLAG_IO_REWRITE flag

...there's only one place where `ZIO_FLAG_IO_REWRITE` is set. Did you try setting `zfs_sync_pass_rewrite` to zero? And/or, have you tried running with the patch and seeing if you get anything in `arcstats:l2_cdata_free_on_write`?

@kbdone Yes, my understanding is the issue is purely related to l2arc compression. Lacking a way to reproduce the problem for testing, the best approach might be for you to run your l2arc without compression and see if the problem goes away.

**Comment by chrisrd** [comment] 2015-01-23 00:51
@kbdone Sorry, your further questions: Yes, the only way to recover the memory would be a module unload (via reboot or not).  @dweeezil's version of the patch shows it's compatible with ZoL, however that version was only applied to FreeBSD. Illumos instead went straight to @prakashsurya's patch above which does the same as the smaller patch and more.

**Comment by dweeezil** [comment] 2015-01-23 05:30
@chrisrd I simply tried to stress out my system with an added l2arc and lz4 compression.  Specifically, I ran an Ubuntu 14.04 VM guest with file-based storage on the host and did a lot of operations on its ext4 filesystem.  I was running on a 3.14.23 kernel with current master ZoL code (plus a couple of unrelated patches of my own) which means there are more differences than I care to think about between my setup and the original poster's 2.6 kernel with, I suspect, a stock 0.6.3 ZoL.  I'll try the same test tomorrow with the patch and watch the new kstat counter.

**Comment by dweeezil** [comment] 2015-01-23 05:38
@chrisrd I didn't noticed that illumos had picked up @prakashsurya's patch in illumos/illumos-gate@244781f and that it included the same stuff and more.

**Comment by prakashsurya** [comment] 2015-01-23 20:37
@dweeezil I understand if you guys decide to pull in the FreeBSD fix for the leak (since it's much smaller and well contained vs. the fix landed in illumos), but just be aware that i'll introduce some merge conflicts when pulling in my ARC contention patch. I had to tweak the fix proposed in the bug to suite some of the other changes I made.

Also, it might be easiest to pull in that FreeBSD when trying to reproduce. That patch adds a kstat counter to easily show when it would have previously leaked the buffer. So, with that patch applied, it's easy to tell if you hit that case, while also patching up the leak.

**Comment by dweeezil** [comment] 2015-01-24 03:30
@prakashsurya I've decided to try to port your full patch from illumos (illumos/illumos-gate@244781f).  I reviewed it pretty closely this morning and see it'll have to be dealt with very carefully due to all the ZoL-specific ARC changes we've already got.  That said, in the mean time I'll probably run the simpler patch from FreeBSD with my stress testing to see whether the new counter is incremented.

**Comment by dweeezil** [comment] 2015-01-24 03:40
As a follow-on, I'll be layering this atop illumos/illumos-gate@89c86e3 on which it depends.  I'll also be reverting 68121a0 because the new patch eliminates ```arc_evict_ghost()```.  This is going to be a bit messy.

**Comment by prakashsurya** [comment] 2015-01-25 06:51
Yes, it will need will need careful attention when porting to ensure that changes in ZoL are addressed when porting. While I don't think there are too many differences to keep track of, the ARC is very subtle and difficult to ensure it's correctness, so attention to detail will be important.

And I agree, it'll be best to pull over https://github.com/illumos/illumos-gate/commit/89c86e3 first, just to reduce the number of merge conflicts. I'm more than willing to discuss any incompatibilities while you work on porting those patches over; just point to the right place to have that dialogue (email/IRC/pull request/etc). The reclaim logic was significantly reworked, which means the ZoL changes regarding arc_meta_limit will need to be reworked. I _think_ much of the linux specific changes will be able to be reverted, and the illumos changes used without modification, but it'll take a close eye to say for sure.

**Comment by dweeezil** [comment] 2015-01-25 07:00
@prakashsurya Thanks for the info.  You'll want to take a peek at #3038 which I just posted a few minutes ago.  It's the foundation upon which I am layering your work.  I'll be in touch if I've got any questions.

**Comment by behlendorf** [comment] 2015-02-02 22:03
@dweeezil @prakashsurya Sorry I've been AWOL on this conversation until now.  My preference would be to pull dweeezil/zfs@01a4fb8 in for the 0.6.4 tag since it's much smaller.  Then pull in #3038 when we're happy with it and have been able to really test it.  The ARC is a subtle bit of code.  Sounds good to you guys?  If so I'll merge dweeezil/zfs@01a4fb8 assuming it passed testing.

**Comment by dweeezil** [comment] 2015-02-03 04:43
@behlendorf That sounds like a good idea to me.  I'm deep in the middle of working on the follow-on to #3038 (the illumos 5497 patch) which is quite the beast.  We've done so much fiddling with the ARC code in ZoL that there are many subtle issues that crop up.  I do think that we'll be able to restore quite a bit of synchronization with upstream when this is all done but it will have to be done very carefully and extensively tested.

I've not done much testing on the dweeezil/zfs@01a4fb8 commit other than to verify it doesn't totally break anything.  I'll convert it to a pull request.

**Comment by behlendorf** [comment] 2015-02-04 00:58
@dweeezil Thanks, for FreeBSD fix looks good to me and I haven't seen any issue. I've pulled it in to master.  For anyone who was hitting this issue regularly please see the new `l2_cdata_free_on_write` kstat counter to see if this case has been hit.

**Closed by behlendorf** 2015-02-04 00:58 UTC
Labels: Bug - Minor, Difficulty - Medium

**Comment by markdesouza** [comment] 2015-02-11 23:29
Just thought I would chime in here and say that all my production machines and my home machine are experiencing this issue. Couple of examples below:

Server 1 (Debian 7 / Kernel 3.2.63-2+deb7u2 / ZoL 0.6.3)
arstat: arcsz=6.7gb , c=6.7gb
/proc/spl/kmem/slab: 14.7834
pools: 2x143gb mirrored, 7x 2x 900gb (raid 10)
mem: 16gb total, 513mb free
uptime: 53 days

Server 2 (Debian 7 / Kernel 3.2.63-2+deb7u2 / ZoL 0.6.3)
arstat: arcsz=4.1gb , c=5.9gb
/proc/spl/kmem/slab: 9.70137
pools: 2x500gb mirrored
mem: 12gb total, 1303mb free
uptime: 93 days

Server 3 (Ubuntu 14.04.1 / Kernel 3.11.0-24-generic / ZoL 0.6.2)
arstat: n/a but arc is set to zfs_arc_max=8589934592
/proc/spl/kmem/slab: 11.5508
pools: 5x4tb raidz2 with 200gb larc2 and 40gb zil
mem: 24gb total, 10707mb free
uptime: 226 days

Hope that helps

**Comment by behlendorf** [comment] 2015-02-12 00:58
@markdesouza a fix for this has been merged to master and will be in the next tag.
