### ISSUE TITLE
Importing a pool with '-aN' disables hostid import protection

### ISSUE THREAD

**Issue by supermauro** [zfsonlinux/zfs#4658] opened 2016-05-17 13:27 UTC
After the latest upgrade I run into a potentially disastrous issue. I have two nodes (A CentOS 6.7 and B CentOS 7.2.1511) sharing a disk array via a SAN. Both have ZFS release 0.6.5.7-1 rpm.  Node A has pool MYPOOL imported. Node B does not have any pool previously imported. Node B boots and imports MYPOOL. Result is that MYPOOL is imported at the same time by node A and B at high risk of corruption. 

If I disconnect physically the array from Node B at boot, allow for Node B to complete boot, reconnect the array, then issue zpool import MYPOOL (whilst imported by Node A), Node B correctly reports that the pool is already imported by a different server and does not import the pool.

I tried also to export MYPOOL from node A, import MYPOOL from node B, then export MYPOOL again from node B, then reboot node B. At boot Node B should not import MYPOOL. Instead it does.

zfs package configuration files have never been edited and are at the default status.

**Comment by supermauro** [comment] 2016-05-17 15:38
Further to my previous message I removed all zfs/spl packages and I removed every left over file in /etc/zfs. Then I re-installed zfs from scratch. Same problem.

The problem occurs only under CentOS 7.  Following further investigation I found that when I export MYPOOL on CentOS 7 Node B /etc/zfs/zpool.cache does not get updated. I just run a binary diff and the file remains untouched. This might be the problem in that once a zpool is exported it should be also removed from zpool.cache. Since it is still there it may explain why it gets re-imported at boot.

**Comment by behlendorf** [comment] 2016-05-17 17:22
@supermauro when running ZFS in a failiover setup additional configuration is necessary.  In particular, you should manually generate a  unique `/etc/hostid` for each node.  This will prevent the pool from being automatically imported on the partner not unless the `-f` option is given

As for the zpool.cache file not get updated that does sound like a bug.  The pool should be removed from it when exported.

**Comment by supermauro** [comment] 2016-05-17 19:23
I already have a unique /etc/hostid for each server. However I wonder if zfs looks at it at boot. I think I read somewhere that there are different library calls to get the hostid. If a library call does not look at /etc/hostid but rather generates it on the fly and the generation depends on the NIC's mac address, then at the time zfs is started the NIC has not been raised yet. In my case in fact the NIC does not yet exist when zfs starts because a module must be loaded first (it is an Nvidia NIC and the Nvidia driver was REMOVED by RedHat in CentOS 7 standard kernel).

I tested a reboot with CentOS 6 and this imports only the pools that were imported when the system was shutdown. 

CentOS 7 zfs packages contain an additional zfs-import-scan.service that cannot be disabled and imports any pool, even if it is not in zpool.cache. This is what causes a pool to be imported at boot even though it is not in zpool.cache or if I delete zpool.cache. 

zfs-import-scan.service executes:

ExecStart=/sbin/zpool import -d /dev/disk/by-id -aN

This service should be removed!

It does not explain however why a pool gets imported when it is already imported by the other node. This should not happen and it happens only at boot.

**Comment by supermauro** [comment] 2016-05-17 20:07
I noticed that using kernel 3 zpool.cache gets updated, using kernel 4 it does not get updated when I export a pool.

Furthermore, I have also lost completely a pool because it got imported by a booting node whilst it was imported already by the other node. The pool is not recoverable not even issuing import -F -X

This can be marked a SERIOUS FAULT.

I suspect it might have something to do with the hostid during boot time because when I manually try to import a pool after the system has finished the boot process I do get the correct error that the pool is already imported elsewhere.

**Comment by supermauro** [comment] 2016-05-20 16:04
To summarize there are 3 distinct issues here both leading to a pool being imported when it should not be:

1) on CentOS 7 at boot time a pool resident on shared SAN storage can be imported whilst already imported by a different server. SEVERITY VERY HIGH

2) on CentOS 7 with kernel 4.4.9, 4.4.10 (possibly other releases, although I tested only with these): when a pool is exported, /etc/zfs/zpool.cache does not get updated. SEVERITY MEDIUM, although it contributes to make issue (1) VERY HIGH SEVERITY

3) on CentOS 7 a new static service: zfs-import-scan.service has been introduced. This service scans /dev/disk/by-id and imports indiscriminately any pool it finds, even if the pools were previously explicitly exported and thus they should not be imported. This at boot causes all the pools on shared SAN storage to be imported and because of issue (1) it causes severe damage.
This service has no place even after issue (1) has been resolved. Only pools in zpool.cache that were previously imported should be re-imported at boot. THIS SERVICE MUST BE REMOVED from the rpm packages. SEVERITY MEDIUM, although it contributes to turn issue (1) into VERY HIGH SEVERITY

**Comment by rlaager** [comment] 2016-05-23 22:42
Your item 1 (that data-destroying duplicated mounts are not prevented) is #745.

Regarding your item 3: If you have a zpool.cache file, then zfs-import-scan.service does not start. (See its ConditionPathExists.) However, if you export all pools, then you end up with no zpool.cache (assuming your item 2 is fixed), in which case you have a problem. That issue is specific to HA setups (will always require extra protection) or unzoned SANs. You should probably disable zfs-import-scan.service, using systemd's mechanisms, in your environment.

**Comment by supermauro** [comment] 2016-05-24 00:04
Unfortunately  zfs-import-scan.service has been created as a "static" service and thus it cannot be disabled. I edited the script and pointed the execution to /bin/false.

The bottom line is that such service SHOULD NOT EXIST. If a pool was not imported before shutdown (and thus it isn't in zpool.cache) then clearly the administrator does not want to import it!

If we consider zpool.cache an equivalent for zfs to /etc/fstab, having such service is just like ignoring whatever it is in /etc/fstab and at boot go scan+mount every filesystem found on every disk. This is madness! What if I have a SAN and the filesystem is mounted elsewhere? Yet if I zone my SAN (why should that be necessary?) I prevent any chance of a failover that I WANT TO happen.

All the above of course would not be so much of a problem if zfs were working correctly in CentOS 7. That is if a pool is already imported an error is displayed and the story ends there.
The major issue here is that issuing a zpool import -d /etc/zfs/zpool.cache -aN imports every pool in the cache, whether these are already imported on another server or not!

**Comment by rlaager** [comment] 2016-05-24 01:23
I hear your frustration. I understand you had a catastrophic data loss event. That's not cool.

For reference, I'm not a ZFS committer, and these are my personal opinions only.

While your use case is valid, so are mine. I have no zpool.cache file on my several non-GUI server systems, and I want it that way.

My laptop, like most if not all modern GUI systems, does in fact mount all file systems off all attached disks, ZFS or otherwise.

We need to focus on solutions that cover both use cases.

**Comment by ilovezfs** [comment] 2016-05-24 01:50
If the pool was last imported on another system and yet it is also still in the cache file on the current system, which is quite normal, the pool should not import without -f unless there is a bug. That said, even if there is a bug, and it does import without -f, this shouldn't be an issue unless it's simultaneously imported on two systems.

**Comment by rlaager** [comment] 2016-05-24 01:51
Does "masking" the service (option 3 in the following link) work? http://0pointer.de/blog/projects/three-levels-of-off

**Comment by rlaager** [comment] 2016-05-24 01:53
@ilovezfs If there is no cache file, the system will import ALL pools. That's part of the issue here.

**Comment by ilovezfs** [comment] 2016-05-24 01:54
That is totally unacceptable if true but that sounds like a downstream issue not ZoL proper, as that's not the behavior in master.

**Comment by ilovezfs** [comment] 2016-05-24 02:07
Ah I see this is a divergence between the behavior of the SYSV init scripts and the systemd scripts.  There's no way zpool-import-scan should be enabled by default to run if there's no cache file. That said, it doesn't use -f, so I don't see how the pool could have imported unless there's a bug.

**Comment by supermauro** [comment] 2016-05-24 07:37
There are three issues: (1) is a major bug related to zfs on linux, (2) is a packaged service that should be removed and (3) is a zfs on linux bug related only to kernel 4.
- 1) There is a serious bug because pools are imported when already imported by another server.
- 2) zpool-import-scan exacerbated the fault and it caused a catastrophic failure because although I did not have the pool in zpool.cache, it imported it regardless whilst the pool was imported by another server. This is equivalent to scanning and mounting every filesystem even when not in /etc/fstab
- 3) under CentOS 7, if I use kernel 4, when I export a pool, zpool.cache does not get updated

**Comment by ilovezfs** [comment] 2016-05-24 08:16
The cache file is mostly a distraction in this situation. The only serious issue here is if import -a is not requiring -f when the pool is currently imported by another server, and the two servers have different hostids.

**Comment by behlendorf** [comment] 2016-05-24 21:52
A few things:

* A proper failover solution for this is actively under development to ensure this kind of thing can't happen.  Ever.  See the design in issue #745 for details.  It does not depend on the hostid mechanism which has always been a hack and is problematic for Linux systems which often do no have a stable hostid.  I expect getting the MMP feature finished, tested, and in a tagged release is still a fair ways off but it is being worked on.

* I'm open to disabling the ` zpool-import-scan` by default.  However, this needs to be something which users can enable, many people prefer to run without a cache file on a non-failover configuration where this make sense.  If someone can propose a PR which does this that would be helpful.

**Comment by behlendorf** [comment] 2016-05-25 19:31
@supermauro @ilovezfs @rlaager can you please comment on the propose systemd changes in PR #4496.  They disable the scan service by default but allow it to be enabled as an alternate configuration option.

**Comment by behlendorf** [comment] 2016-05-27 19:00
The scan service has been disabled in master by default and this change has been marked for inclusion in the next point release.

**Comment by supermauro** [comment] 2016-05-27 23:43
@behlendorf Thank you for the change on the scan service. Please note however that the scan service was only exacerbating the issue that allows a pool to be imported whilst already imported by a different server that is the core issue reported in my original message.

**Comment by behlendorf** [comment] 2016-05-27 23:58
Right, I've reopened this issue.  We'll need to investigate that because it shouldn't be possible if you have set hostids on both systems.

**Comment by supermauro** [comment] 2016-05-28 09:09
I confirm that this happens only on CentOS 7 with both kernel plus 3 and kernel 4. /etc/hostid is present on both servers (and clearly each server has a unique hostid). 
It happens only if I import a pool using -aN (either pointing to the cache file or /dev/disk/by-id). If I specify the pool name instead I get the notification that the pool is already imported elsewhere correctly.

**Comment by behlendorf** [comment] 2016-05-31 16:12
@supermauro thank you for identifying the exact case where this fails, we'll look in to it and get it resolved.

**Comment by kpande** [comment] 2016-06-17 22:18
I see this as well, in Debian Wheezy with ZFS HEAD http://i.imgur.com/aeupAos.png

**Comment by behlendorf** [comment] 2016-11-08 22:57
I'm unable to reproduce this issue on CentOS 7 when importing the pool using `-aN`.

```
$ sudo ./cmd/zpool/zpool import -o readonly=on tank
cannot import 'tank': pool may be in use from other system, it was last
accessed by localhost (hostid: 0x11aabb) on Tue Nov  8 13:45:55 2016
use '-f' to import anyway

$ sudo ./cmd/zpool/zpool import -o readonly=on -a
cannot import 'tank': pool may be in use from other system, it was last
accessed by localhost (hostid: 0x11aabb) on Tue Nov  8 13:45:55 2016
use '-f' to import anyway

$ sudo ./cmd/zpool/zpool import -o readonly=on -aN
cannot import 'tank': pool may be in use from other system, it was last
accessed by localhost (hostid: 0x11aabb) on Tue Nov  8 13:45:55 2016
```

@supermauro is it possible you testing with a pool which was cleanly exported from another host.  In this case the labels on disk are updated to reflect the fact that the pool was cleanly exported and it may be safely imported next on any system regardless of the host id.

**Comment by behlendorf** [comment] 2016-12-20 23:43
Closing.  Unable to reproduce.

**Closed by behlendorf** 2016-12-20 23:43 UTC
