### ISSUE TITLE
ZFS attach fails for disk referenced by-id

### ISSUE THREAD

**Issue by CRWdog193** [zfsonlinux/zfs#4144] opened 2015-12-26 22:09 UTC
Arch Linux with zfs-git 0.6.5.3_r0_g9aaf60b_4.2.5_1-1 (archzfs-git).

Migrating to new disks. Trying to convert (temporary!) single-disk vdevs to mirrors, I noted:

[root] # zpool attach -f data ata-ST2000LM003_HN-M201RAD_S377J9AGA05161 ata-ST2000LM003_HN-M201RAD_S377J9AGA05162
cannot attach ata-ST2000LM003_HN-M201RAD_S377J9AGA05162 to ata-ST2000LM003_HN-M201RAD_S377J9AGA05161: no such pool or dataset

Tried various other combinations (e.g. prefacing with /dev/disk/by-id etc.). No change.

However:

[root]# zpool attach -f data /dev/disk/by-id/ata-ST2000LM003_HN-M201RAD_S377J9AGA05161 /dev/sde
[root]# 

[root]# zpool status -v
  pool: data
 state: ONLINE
status: One or more devices is currently being resilvered.  The pool will
	continue to function, possibly in a degraded state.
action: Wait for the resilver to complete.
  scan: resilver in progress since Sat Dec 26 21:58:45 2015
    103G scanned out of 5.12T at 391M/s, 3h44m to go
    25.8G resilvered, 1.97% done
config:

	NAME                                                   STATE     READ WRITE CKSUM
	data                                                   ONLINE       0     0     0
	  ata-ST2000LM003_HN-M201RAD_S377J9EGA08207            ONLINE       0     0     0
	  mirror-1                                             ONLINE       0     0     0
	    ata-ST2000LM003_HN-M201RAD_S377J9AGA05161          ONLINE       0     0     0
	    sde                                                ONLINE       0     0     0  (resilvering)
	  ata-ST2000LM003_HN-M201RAD_S377J9AGA05144            ONLINE       0     0     0
	  ata-ST2000LM003_HN-M201RAD_S377J9EGA08198            ONLINE       0     0     0
	logs
	  ata-Samsung_SSD_850_PRO_128GB_S24ZNSAG401432A-part1  ONLINE       0     0     0
	  ata-Samsung_SSD_850_PRO_128GB_S24ZNSAG406042N-part1  ONLINE       0     0     0
	cache
	  ata-Samsung_SSD_850_PRO_128GB_S24ZNSAG401432A-part2  ONLINE       0     0     0
	  ata-Samsung_SSD_850_PRO_128GB_S24ZNSAG406042N-part2  ONLINE       0     0     0

errors: No known data errors

Somewhat unexpected...

**Comment by dasjoe** [comment] 2016-01-01 00:57
Possible duplicate of #4077

**Comment by ilovezfs** [comment] 2016-01-01 03:03
Someone in IRC had the same issue and a reboot "fixed" it since it's some kind of udev race. Have you tried a reboot yet?

**Comment by CRWdog193** [comment] 2016-01-01 03:29
> Someone in IRC had the same issue and a reboot "fixed" it since it's some kind of udev race. Have you tried a reboot yet?

Yup, pretty much had to; until rebooted, was unable to re-import the pool by-id; same "no such pool or dataset" message, IIRC. 

The export seemed to work fine - based merely on a quick glance at the strings in zpool.cache, it seemed to contain all the expected "by-id" drive indentifiers. But the pool wouldn't import by-id.

After re-boot, the pool could be exported & imported as expected.. 

Went through a similar exercise with 6.3.2 or thereabouts (because I originally built the pool with the drive identifiers). Didn't see this problem then; straight export/import took care of it.

Only difference (other than ZFS version) is that the first time, all drives were already loaded. This time around, I (initially) populated only the necessary slots in the hot-swap bays to build the pool. By hot-plugging them; in retrospect, a udev race would make a lot of sense...

**Comment by ilovezfs** [comment] 2016-01-01 05:14
>The export seemed to work fine - based merely on a quick glance at the strings in zpool.cache, it seemed to contain all the expected "by-id" drive identifiers. But the pool wouldn't import by-id.

As an aside, in the future, to dump zpool.cache in human readable format, just run zdb with no arguments.

Also, it's worth mentioning that your description of the zpool.cache contents and the idea that "export worked fine" contradict each other. Upon any export, the zpool.cache file is rewritten with all the information regarding the just exported pool expunged.

**Comment by dasjoe** [comment] 2016-03-14 19:22
Duplicate of #3708.

**Closed** 2016-04-25 18:14 UTC
