### ISSUE TITLE
zpool replace fails until using the guid

### ISSUE THREAD

**Issue by rhagu** [zfsonlinux/zfs#1174] opened 2013-01-02 13:53 UTC
Ubuntu 12.04 with ZFS module v0.6.0.91-rc13

Today I tried to replace another one but ran into some problems: 

```$ zpool status

  pool: datenraid
 state: DEGRADED
status: One or more devices could not be used because the label is missing or
    invalid.  Sufficient replicas exist for the pool to continue
    functioning in a degraded state.
action: Replace the device using 'zpool replace'.
   see: http://zfsonlinux.org/msg/ZFS-8000-4J
 scan: resilvered 672G in 17h32m with 0 errors on Wed Jan  2 13:02:15 2013
config:

```
NAME                                          STATE     READ WRITE CKSUM
datenraid                                     DEGRADED     0     0     0
  raidz1-0                                    DEGRADED     0     0     0
    ata-SAMSUNG_HD753LJ_S13UJ1KQ107341        UNAVAIL      0     0     0
    ata-SAMSUNG_HD753LJ_S13UJ1KQ108434        ONLINE       0     0     0
    ata-WDC_WD20EARX-00PASB0_WD-WCAZA8466409  ONLINE       0     0     0
    ata-WDC_WD20EARS-00MVWB0_WD-WCAZA2456182  ONLINE       0     0     0
    ata-WDC_WD20EARX-00PASB0_WD-WCAZA8462467  ONLINE       0     0     0
```

errors: No known data errors

---

$ zpool replace -f datenraid ata-SAMSUNG_HD753LJ_S13UJ1KQ107341 ata-WDC_WD20EARS-00MVWB0_WD-WCAZA2464415

cannot replace ata-SAMSUNG_HD753LJ_S13UJ1KQ107341 with ata-WDC_WD20EARS-00MVWB0_WD-WCAZA2464415: no such device in pool

---

$ ls -l /dev/disk/by-id/ | grep /sdc

lrwxrwxrwx 1 root root  9 Jan  2 13:48 ata-WDC_WD20EARS-00MVWB0_WD-WCAZA2464415 -> ../../sdc
lrwxrwxrwx 1 root root 10 Jan  2 13:48 ata-WDC_WD20EARS-00MVWB0_WD-WCAZA2464415-part1 -> ../../sdc1
lrwxrwxrwx 1 root root 10 Jan  2 13:48 ata-WDC_WD20EARS-00MVWB0_WD-WCAZA2464415-part9 -> ../../sdc9
lrwxrwxrwx 1 root root  9 Jan  2 13:48 scsi-SATA_WDC_WD20EARS-00_WD-WCAZA2464415 -> ../../sdc
lrwxrwxrwx 1 root root 10 Jan  2 13:48 scsi-SATA_WDC_WD20EARS-00_WD-WCAZA2464415-part1 -> ../../sdc1
lrwxrwxrwx 1 root root 10 Jan  2 13:48 scsi-SATA_WDC_WD20EARS-00_WD-WCAZA2464415-part9 -> ../../sdc9
lrwxrwxrwx 1 root root  9 Jan  2 13:48 wwn-0x50014ee25a9f382f -> ../../sdc
lrwxrwxrwx 1 root root 10 Jan  2 13:48 wwn-0x50014ee25a9f382f-part1 -> ../../sdc1
lrwxrwxrwx 1 root root 10 Jan  2 13:48 wwn-0x50014ee25a9f382f-part9 -> ../../sdc9

---

$ blkid

/dev/sda1: LABEL="datenraid" UUID="1314569646526997278" UUID_SUB="10495016691942155791" TYPE="zfs_member" 
/dev/sdb: LABEL="datenraid" UUID="1314569646526997278" UUID_SUB="8076640308490212370" TYPE="zfs_member" 
/dev/sdd: LABEL="datenraid" UUID="1314569646526997278" UUID_SUB="3053438509257823248" TYPE="zfs_member" 
/dev/sde: LABEL="datenraid" UUID="1314569646526997278" UUID_SUB="4136006055799383929" TYPE="zfs_member" 
/dev/sdf1: UUID="358d2495-a1ec-4cd5-b668-013dd88c0b20" TYPE="ext4" '''

'''zpool replace -f datenraid /dev/disk/by-id/ata-SAMSUNG_HD753LJ_S13UJ1KQ107341 /dev/disk/by-id/ata-WDC_WD20EARS-00MVWB0_WD-WCAZA2464415'''

came up with the same error

The replacement disk had a prior installation of zfs (same pool) on it but was not completely resilvered and a dd if=/dev/zero of=/dev/sdc was run on it for some minutes until ~3.5Gb of zeros had been written to the disk.

This is the history of the raidz:

'''History for 'datenraid':
2012-04-30.16:38:23 zpool create datenraid raidz1 ada5 ada4 ada3 ada2 ada1
2012-04-30.16:42:11 zpool set autoreplace=on datenraid
2012-04-30.16:42:28 zpool set autoreplace=on datenraid
2012-04-30.16:55:07 zpool autoexpand=on datenraid
2012-04-30.20:14:28 zpool clear datenraid
2012-04-30.20:14:41 zpool scrub datenraid
2012-05-02.03:47:34 zpool scrub datenraid
2012-05-02.11:39:38 zpool replace datenraid 2096603622983636809 /dev/ada3
2012-05-02.17:26:21 zpool replace datenraid 4061460402615561199 /dev/ada1
2012-05-03.00:44:29 zpool replace datenraid 5274696194745958675 /dev/ada2
2012-05-04.01:34:53 zpool scrub datenraid
2012-05-14.13:54:07 zpool import -f datenraid
2012-06-21.18:27:43 zpool import -a -f -o altroot=/target
2012-06-21.19:39:23 zpool import -a -f -o altroot=/target
2012-06-22.00:28:17 zpool import -f datenraid
2012-10-24.21:49:35 zpool import -f datenraid
2012-10-24.21:53:42 zpool scrub datenraid
2012-11-30.03:28:43 zpool import -f datenraid
2012-12-30.22:58:24 zpool import -f datenraid
2013-01-01.14:03:19 zpool set autoexpand=on datenraid
2013-01-01.14:05:16 zpool scrub datenraid
2013-01-01.14:49:09 zpool set autoreplace=on datenraid
2013-01-01.18:03:14 zpool replace datenraid 7578286770174176832 /dev/sdf
2013-01-01.18:48:29 zpool clear datenraid
2013-01-01.19:30:11 zpool replace -f datenraid 7578286770174176832 ata-WDC_WD20EARS-00MVWB0_WD-WCAZA2456182
2013-01-02.13:44:08 zpool clear datenraid```

this is the zbd output:

'''
datenraid:
    version: 28
    name: 'datenraid'
    state: 0
    txg: 227161
    pool_guid: 1314569646526997278
    hostname: 'Neukserver'
    vdev_children: 1
    vdev_tree:
        type: 'root'
        id: 0
        guid: 1314569646526997278
        children[0]:
            type: 'raidz'
            id: 0
            guid: 15055095899949900173
            nparity: 1
            metaslab_array: 30
            metaslab_shift: 34
            ashift: 9
            asize: 3750757662720
            is_log: 0
            create_txg: 4
            children[0]:
                type: 'disk'
                id: 0
                guid: 5244441310988300610
                path: '/dev/disk/by-id/ata-SAMSUNG_HD753LJ_S13UJ1KQ107341'
                phys_path: '/dev/ada5'
                whole_disk: 1
                DTL: 40
                create_txg: 4
            children[1]:
                type: 'disk'
                id: 1
                guid: 8076640308490212370
                path: '/dev/disk/by-id/ata-SAMSUNG_HD753LJ_S13UJ1KQ108434'
                phys_path: '/dev/ada1'
                whole_disk: 1
                DTL: 35
                create_txg: 4
            children[2]:
                type: 'disk'
'''

The error: "no such device in pool" was only fixed after connecting all drives of the raidz (this way its status was online not degraded as in the first tries) and the additional replacement disk and running this command:

'''
zpool replace datenraid 5244441310988300610 /dev/disk/by-id/ata-WDC_WD20EARS-00MVWB0_WD-WCAZA2464415
'''

It was not tested, if the command would work with the raidz in a degraded state (removing the disk that will be replaced).

**Comment by DurvalMenezes** [comment] 2015-01-31 14:09
Just for the record: 

1) The problem is happening with ZoL 0.6.3 both in Ubuntu 13.04 and on EL6.6, see my message (and its followup) on the mailing list: https://groups.google.com/a/zfsonlinux.org/d/msg/zfs-discuss/LfBWLEprYmI/Wy49BPZKynIJ and see also http://askubuntu.com/questions/305830/replacing-a-dead-disk-in-a-zpool/

2) There's no need to reconnect any devices (in fact, the problem here was that the device *was* already connected at the time the zpool offline/remove/replace commands failed -- in fact it was never disconnected in the first place), it's possible to obtain the device GUID using "zdb" or "zdb -l /dev/DEVICE" and then use it instead of the name; zpool offline/remove/replace worked perfectly with the GUID. 

As @behlendorf 's post above, regarding it being fixed in GIT was from January-2013 (more than 1.5 years before the 0.6.3 release), I'm pretty sure that either 1) it wasn't, or 2) there was a regression later on that undid the fix.

**Comment by behlendorf** [comment] 2016-11-15 05:02
The updated FMA code in master now handles this unambiguously with guids.  In addition, the `-g` option was added to `zpool status` to print the guids so they're now easy to determine and use from the command line.

**Closed by behlendorf** 2016-11-15 05:02 UTC
Labels: zed
