### ISSUE TITLE
ZFS send dead for over 12 hours

### ISSUE THREAD

**Issue by eolson78** [zfsonlinux/zfs#3676] opened 2015-08-10 18:17 UTC
CENTOS 6.5 Kernel 3.14.4
Running a 3 Zpool's 
with an NFS based Filebench load running 
send and receive running at every 1 minute interval for Replication

the ZFS Send task sits in a D state as seen below and the stacks indicate constant traversal of the pre-fetch thread. 

root      70913  0.0  0.0 201104  1564 ?        D    Aug09   0:46 zfs send -PRpv -i PoolLoad1/vol2 snaprep64 PoolLoad1/vol2 snaprep65
root      70917  0.0  0.0 201104  1568 ?        D    Aug09   0:47 zfs send -PRpv -i PoolLoad1/vol3 snaprep61 PoolLoad1/vol3 snaprep62
root      70919  0.0  0.0 201104  1568 ?        D    Aug09   0:46 zfs send -PRpv -i PoolLoad1/vol1 snaprep72 PoolLoad1/vol1 snaprep73
root      70920  0.0  0.0 201104  1568 ?        D    Aug09   0:41 zfs send -PRpv -i PoolLoad1/vol5 snaprep75 PoolLoad1/vol5 snaprep76
root     125338  0.0  0.0      0     0 ?        D    12:58   0:00 [kworker/2:0]
root@ip-50-0-0-62:/home/ec2-user# cat /proc/70913/stack 
[<ffffffffa01d2cdd>] taskq_wait_id+0x4d/0x90 [spl]
[<ffffffffa028180d>] spa_taskq_dispatch_sync+0x8d/0xc0 [zfs]
[<ffffffffa024ad32>] dump_bytes+0x42/0x50 [zfs]
[<ffffffffa024b1ef>] dump_write+0xff/0x260 [zfs]
[<ffffffffa024c3c6>] backup_cb+0x466/0x570 [zfs]
[<ffffffffa024cc66>] traverse_visitbp+0x4a6/0x810 [zfs]
[<ffffffffa024cbdb>] traverse_visitbp+0x41b/0x810 [zfs]
[<ffffffffa024cbdb>] traverse_visitbp+0x41b/0x810 [zfs]
[<ffffffffa024cbdb>] traverse_visitbp+0x41b/0x810 [zfs]
[<ffffffffa024d041>] traverse_dnode+0x71/0xd0 [zfs]
[<ffffffffa024ce47>] traverse_visitbp+0x687/0x810 [zfs]
[<ffffffffa024cbdb>] traverse_visitbp+0x41b/0x810 [zfs]
[<ffffffffa024cbdb>] traverse_visitbp+0x41b/0x810 [zfs]
[<ffffffffa024cbdb>] traverse_visitbp+0x41b/0x810 [zfs]
[<ffffffffa024cbdb>] traverse_visitbp+0x41b/0x810 [zfs]
[<ffffffffa024cbdb>] traverse_visitbp+0x41b/0x810 [zfs]
[<ffffffffa024cbdb>] traverse_visitbp+0x41b/0x810 [zfs]
[<ffffffffa024d041>] traverse_dnode+0x71/0xd0 [zfs]
[<ffffffffa024cef0>] traverse_visitbp+0x730/0x810 [zfs]
[<ffffffffa024d208>] traverse_impl+0x168/0x390 [zfs]
[<ffffffffa024d4b5>] traverse_dataset+0x45/0x50 [zfs]
[<ffffffffa024b71b>] dmu_send_impl+0x3cb/0x4e0 [zfs]
[<ffffffffa024bc71>] dmu_send_obj+0x131/0x1e0 [zfs]
[<ffffffffa02b7b77>] zfs_ioc_send+0x97/0x260 [zfs]
[<ffffffffa02bb445>] zfsdev_ioctl+0x495/0x4d0 [zfs]
[<ffffffff811d0ab3>] do_vfs_ioctl+0x73/0x380
[<ffffffff811d0e61>] SyS_ioctl+0xa1/0xb0
[<ffffffff8162d2a9>] system_call_fastpath+0x16/0x1b
[<ffffffffffffffff>] 0xffffffffffffffff
root@ip-50-0-0-62:/home/ec2-user# cat /proc/70917/stack 
[<ffffffffa01d2cdd>] taskq_wait_id+0x4d/0x90 [spl]
[<ffffffffa028180d>] spa_taskq_dispatch_sync+0x8d/0xc0 [zfs]
[<ffffffffa024ad32>] dump_bytes+0x42/0x50 [zfs]
[<ffffffffa024b1ef>] dump_write+0xff/0x260 [zfs]
[<ffffffffa024c3c6>] backup_cb+0x466/0x570 [zfs]
[<ffffffffa024cc66>] traverse_visitbp+0x4a6/0x810 [zfs]
[<ffffffffa024d041>] traverse_dnode+0x71/0xd0 [zfs]
[<ffffffffa024ce47>] traverse_visitbp+0x687/0x810 [zfs]
[<ffffffffa024cbdb>] traverse_visitbp+0x41b/0x810 [zfs]
[<ffffffffa024cbdb>] traverse_visitbp+0x41b/0x810 [zfs]
[<ffffffffa024cbdb>] traverse_visitbp+0x41b/0x810 [zfs]
[<ffffffffa024cbdb>] traverse_visitbp+0x41b/0x810 [zfs]
[<ffffffffa024cbdb>] traverse_visitbp+0x41b/0x810 [zfs]
[<ffffffffa024cbdb>] traverse_visitbp+0x41b/0x810 [zfs]
[<ffffffffa024d041>] traverse_dnode+0x71/0xd0 [zfs]
[<ffffffffa024cef0>] traverse_visitbp+0x730/0x810 [zfs]
[<ffffffffa024d208>] traverse_impl+0x168/0x390 [zfs]
[<ffffffffa024d4b5>] traverse_dataset+0x45/0x50 [zfs]
[<ffffffffa024b71b>] dmu_send_impl+0x3cb/0x4e0 [zfs]
[<ffffffffa024bc71>] dmu_send_obj+0x131/0x1e0 [zfs]
[<ffffffffa02b7b77>] zfs_ioc_send+0x97/0x260 [zfs]
[<ffffffffa02bb445>] zfsdev_ioctl+0x495/0x4d0 [zfs]
[<ffffffff811d0ab3>] do_vfs_ioctl+0x73/0x380
[<ffffffff811d0e61>] SyS_ioctl+0xa1/0xb0
[<ffffffff8162d2a9>] system_call_fastpath+0x16/0x1b
[<ffffffffffffffff>] 0xffffffffffffffff
root@ip-50-0-0-62:/home/ec2-user# cat /proc/70919/stack 
[<ffffffffa01d2cdd>] taskq_wait_id+0x4d/0x90 [spl]
[<ffffffffa028180d>] spa_taskq_dispatch_sync+0x8d/0xc0 [zfs]
[<ffffffffa024ad32>] dump_bytes+0x42/0x50 [zfs]
[<ffffffffa024b1ef>] dump_write+0xff/0x260 [zfs]
[<ffffffffa024c3c6>] backup_cb+0x466/0x570 [zfs]
[<ffffffffa024cc66>] traverse_visitbp+0x4a6/0x810 [zfs]
[<ffffffffa024cbdb>] traverse_visitbp+0x41b/0x810 [zfs]
[<ffffffffa024d041>] traverse_dnode+0x71/0xd0 [zfs]
[<ffffffffa024ce47>] traverse_visitbp+0x687/0x810 [zfs]
[<ffffffffa024cbdb>] traverse_visitbp+0x41b/0x810 [zfs]
[<ffffffffa024cbdb>] traverse_visitbp+0x41b/0x810 [zfs]
[<ffffffffa024cbdb>] traverse_visitbp+0x41b/0x810 [zfs]
[<ffffffffa024cbdb>] traverse_visitbp+0x41b/0x810 [zfs]
[<ffffffffa024cbdb>] traverse_visitbp+0x41b/0x810 [zfs]
[<ffffffffa024cbdb>] traverse_visitbp+0x41b/0x810 [zfs]
[<ffffffffa024d041>] traverse_dnode+0x71/0xd0 [zfs]
[<ffffffffa024cef0>] traverse_visitbp+0x730/0x810 [zfs]
[<ffffffffa024d208>] traverse_impl+0x168/0x390 [zfs]
[<ffffffffa024d4b5>] traverse_dataset+0x45/0x50 [zfs]
[<ffffffffa024b71b>] dmu_send_impl+0x3cb/0x4e0 [zfs]
[<ffffffffa024bc71>] dmu_send_obj+0x131/0x1e0 [zfs]
[<ffffffffa02b7b77>] zfs_ioc_send+0x97/0x260 [zfs]
[<ffffffffa02bb445>] zfsdev_ioctl+0x495/0x4d0 [zfs]
[<ffffffff811d0ab3>] do_vfs_ioctl+0x73/0x380
[<ffffffff811d0e61>] SyS_ioctl+0xa1/0xb0
[<ffffffff8162d2a9>] system_call_fastpath+0x16/0x1b
[<ffffffffffffffff>] 0xffffffffffffffff
root@ip-50-0-0-62:/home/ec2-user# cat /proc/70920/stack 
[<ffffffffa01d2cdd>] taskq_wait_id+0x4d/0x90 [spl]
[<ffffffffa028180d>] spa_taskq_dispatch_sync+0x8d/0xc0 [zfs]
[<ffffffffa024ad32>] dump_bytes+0x42/0x50 [zfs]
[<ffffffffa024b1ef>] dump_write+0xff/0x260 [zfs]
[<ffffffffa024c3c6>] backup_cb+0x466/0x570 [zfs]
[<ffffffffa024cc66>] traverse_visitbp+0x4a6/0x810 [zfs]
[<ffffffffa024cbdb>] traverse_visitbp+0x41b/0x810 [zfs]
[<ffffffffa024cbdb>] traverse_visitbp+0x41b/0x810 [zfs]
[<ffffffffa024cbdb>] traverse_visitbp+0x41b/0x810 [zfs]
[<ffffffffa024d041>] traverse_dnode+0x71/0xd0 [zfs]
[<ffffffffa024ce47>] traverse_visitbp+0x687/0x810 [zfs]
[<ffffffffa024cbdb>] traverse_visitbp+0x41b/0x810 [zfs]
[<ffffffffa024cbdb>] traverse_visitbp+0x41b/0x810 [zfs]
[<ffffffffa024cbdb>] traverse_visitbp+0x41b/0x810 [zfs]
[<ffffffffa024cbdb>] traverse_visitbp+0x41b/0x810 [zfs]
[<ffffffffa024cbdb>] traverse_visitbp+0x41b/0x810 [zfs]
[<ffffffffa024cbdb>] traverse_visitbp+0x41b/0x810 [zfs]
[<ffffffffa024d041>] traverse_dnode+0x71/0xd0 [zfs]
[<ffffffffa024cef0>] traverse_visitbp+0x730/0x810 [zfs]
[<ffffffffa024d208>] traverse_impl+0x168/0x390 [zfs]
[<ffffffffa024d4b5>] traverse_dataset+0x45/0x50 [zfs]
[<ffffffffa024b71b>] dmu_send_impl+0x3cb/0x4e0 [zfs]
[<ffffffffa024bc71>] dmu_send_obj+0x131/0x1e0 [zfs]
[<ffffffffa02b7b77>] zfs_ioc_send+0x97/0x260 [zfs]
[<ffffffffa02bb445>] zfsdev_ioctl+0x495/0x4d0 [zfs]
[<ffffffff811d0ab3>] do_vfs_ioctl+0x73/0x380
[<ffffffff811d0e61>] SyS_ioctl+0xa1/0xb0
[<ffffffff8162d2a9>] system_call_fastpath+0x16/0x1b
[<ffffffffffffffff>] 0xffffffffffffffff

**Comment by eolson78** [comment] 2015-08-10 18:46
this really appears similar to #3655

**Comment by dweeezil** [comment] 2015-08-11 12:28
@eolson78 The issue threads on which it's waiting are sending the data through the pipe and on to the receiver.  You'll see this type of stack when the receiving end is blocked.  For example, running ```zfs send <whatever>@snap | sleep 3600``` will produce the exact same stack in the ```zfs``` process.  The problem is on the receiving end.

**Comment by dweeezil** [comment] 2015-08-11 12:32
And for completeness, yes, #3655 is the exact same issue.  You need to check out what's happening on the receive end.  This can be caused poor network connectivity, stuck TCP sessions or, of course, a problem with ZFS on the receiving side (assuming the send stream is targeting a ```zfs receive``` rather than being written to a file or a device).

**Comment by behlendorf** [comment] 2015-08-19 17:43
Closing as duplicated of #3655.

**Closed by behlendorf** 2015-08-19 17:43 UTC
