### ISSUE TITLE
Pool features cannot be disabled at time of creation

### ISSUE THREAD

**Issue by sempervictus** [zfsonlinux/zfs#5294] opened 2016-10-17 23:01 UTC
Seems we can't create pools with newer features disabled for backwards compatibility:
```
# sudo zpool create -O mountpoint=none -O compression=lz4 -O overlay=on -O atime=off -o ashift=12 -o feature@async_destroy=enabled -o feature@empty_bpobj=enabled -o feature@lz4_compress=enabled -o feature@spacemap_histogram=enabled -o feature@enabled_txg=enabled -o feature@hole_birth=enabled -o feature@extensible_dataset=enabled -o feature@embedded_data=enabled -o feature@bookmarks=enabled -o feature@filesystem_limits=enabled -o feature@large_blocks=enabled rpool /dev/mapper/root_crypt
```
results in:
```
# zpool get all rpool
NAME   PROPERTY                    VALUE                       SOURCE
rpool  size                        784M                        -
rpool  capacity                    0%                          -
rpool  altroot                     -                           default
rpool  health                      ONLINE                      -
rpool  guid                        14865096722165664340        -
rpool  version                     -                           default
rpool  bootfs                      -                           default
rpool  delegation                  on                          default
rpool  autoreplace                 off                         default
rpool  cachefile                   -                           default
rpool  failmode                    wait                        default
rpool  listsnapshots               off                         default
rpool  autoexpand                  off                         default
rpool  dedupditto                  0                           default
rpool  dedupratio                  1.00x                       -
rpool  free                        784M                        -
rpool  allocated                   456K                        -
rpool  readonly                    off                         -
rpool  ashift                      12                          local
rpool  comment                     -                           default
rpool  expandsize                  -                           -
rpool  freeing                     0                           -
rpool  fragmentation               0%                          -
rpool  leaked                      0                           -
rpool  feature@async_destroy       enabled                     local
rpool  feature@empty_bpobj         enabled                     local
rpool  feature@lz4_compress        active                      local
rpool  feature@spacemap_histogram  active                      local
rpool  feature@enabled_txg         active                      local
rpool  feature@hole_birth          active                      local
rpool  feature@extensible_dataset  enabled                     local
rpool  feature@embedded_data       active                      local
rpool  feature@bookmarks           enabled                     local
rpool  feature@filesystem_limits   enabled                     local
rpool  feature@large_blocks        enabled                     local
rpool  feature@large_dnode         enabled                     local
rpool  feature@sha512              enabled                     local
rpool  feature@skein               enabled                     local
rpool  feature@edonr               enabled                     local
```
Whereas
```
sudo zpool create -O mountpoint=none -O compression=lz4 -O overlay=on -O atime=off -o ashift=12 -o feature@userobj_accounting=disabled rpool /dev/mapper/root_crypt
```
returns:
```
cannot create 'rpool': property 'feature@userobj_accounting' can only be set to 'enabled'
```

Neither the explicit disabled/disable settings nor the implicit "only enable those features selected as enabled at creation time" approach work presently. This prevents use of pools created from git master on stable systems and appears to contradict the point of feature flags.

**Comment by behlendorf** [comment] 2016-10-17 23:25
You need to add `-d` to your original `zpool create`.  From `zpool(8)`.

```
           -d

               Do not enable any features on the new pool. Individual features
               can  be  enabled  by  setting their corresponding properties to
               enabled with the -o option. See zpool-features(5)  for  details
               about feature properties.
```

That said I sympathize, as we add new features this becomes more and more painful.  @FransUrbo has a work in progress PR #3465 to add support for disabling specific flags.  The basic functional idea is described in this https://github.com/zfsonlinux/zfs/pull/3465#issuecomment-248718656.  Any help you could offer on the code/test side would be welcome.

Duplicate of #3460.

**Closed by behlendorf** 2016-10-17 23:25 UTC
