### ISSUE TITLE
zfs 0.6.3 locks on importing a pool

### ISSUE THREAD

**Issue by palica** [zfsonlinux/zfs#3129] opened 2015-02-23 21:40 UTC
Hi,

when trying to import a pool the zpool import command hangs with this bug in dmesg.
gentoo kernel 3.16.2-3
RAM 8 GB
CPU INTEL Core 2 Quad Q9300

#zpool import
   pool: storage
     id: 610138227588183309
  state: ONLINE
 action: The pool can be imported using its name or numeric identifier.
 config:

        storage     ONLINE
          mirror-0  ONLINE
            sde1    ONLINE
            sdc1    ONLINE

#zpool import -d /dev/disk/by-id/ -R /storage/ storage

[  932.132417] BUG: unable to handle kernel NULL pointer dereference at 0000000000000018
[  932.132439] IP: [<ffffffffa0f78c25>] zap_count_write+0x155/0x3f0 [zfs]
[  932.132463] PGD 21594b067 PUD 2134af067 PMD 0 
[  932.132475] Oops: 0000 [#1] SMP 
[  932.132482] Modules linked in: cfg80211 rfkill snd_hda_codec_hdmi iTCO_wdt iTCO_vendor_support ppdev mt352 dvb_bt8xx cx22702 coretemp cx88_dvb kvm_intel cx88_vp3054_i2c videobuf_dvb kvm pcspkr ps
mouse evdev serio_raw rc_winfast snd_hda_codec_realtek snd_hda_codec_generic tuner_simple tuner_types snd_usb_audio snd_usbmidi_lib snd_rawmidi snd_seq_device gspca_zc3xx gspca_main tda9887 tda8290 
tuner i2c_i801 zfs(PO) zunicode(PO) zavl(PO) zcommon(PO) znvpair(PO) spl(O) bt878 firewire_ohci firewire_core lpc_ich crc_itu_t mfd_core cx8802 rc_avermedia_dvbt dvb_core cx88_alsa cx8800 bttv cx88x
x btcx_risc tveeprom videobuf_dma_sg videobuf_core nouveau rc_core v4l2_common videodev mxm_wmi wmi video media ttm drm_kms_helper snd_hda_intel r8169 drm snd_hda_controller mii i2c_algo_bit snd_hda
_codec i2c_core snd_hwdep
[  932.132626]  ata_generic tpm_infineon snd_pcm tpm_tis parport_pc acpi_cpufreq snd_timer tpm parport snd soundcore ehci_pci processor button shpchp thermal_sys xts ablk_helper cryptd glue_helper lrw gf128mul aes_x86_64 cbc sha256_generic iscsi_tcp libiscsi_tcp libiscsi scsi_transport_iscsi tg3 libphy ptp pps_core e1000 fuse nfs fscache lockd sunrpc jfs reiserfs btrfs ext4 jbd2 mbcache crc16 
multipath linear raid0 dm_raid raid10 raid1 raid456 md_mod async_raid6_recov async_pq raid6_pq async_xor xor async_memcpy async_tx dm_snapshot dm_bufio dm_crypt dm_mirror dm_region_hash dm_log dm_mo
d hid_sunplus hid_sony hid_samsung hid_pl hid_petalynx hid_monterey hid_microsoft hid_logitech ff_memless hid_gyration hid_ezkey hid_cypress hid_chicony hid_cherry hid_belkin hid_apple hid_a4tech sl
811_hcd hid_generic
[  932.132803]  usbhid xhci_hcd ohci_hcd uhci_hcd usb_storage hid ehci_hcd usbcore usb_common mpt2sas raid_class aic94xx libsas lpfc qla2xxx megaraid_sas megaraid_mbox megaraid_mm megaraid aacraid s
x8 DAC960 hpsa cciss 3w_9xxx 3w_xxxx mptsas scsi_transport_sas mptfc scsi_transport_fc scsi_tgt mptspi mptscsih mptbase atp870u dc395x qla1280 dmx3191d sym53c8xx gdth advansys initio BusLogic arcmsr
 aic7xxx aic79xx scsi_transport_spi sr_mod cdrom sg sd_mod crc_t10dif crct10dif_common pdc_adma sata_mv ata_piix ahci libahci sata_qstor sata_vsc sata_uli sata_sis sata_sx4 sata_nv sata_via sata_svw
 sata_sil24 sata_sil sata_promise pata_via pata_jmicron pata_marvell pata_sis pata_netcell pata_pdc202xx_old pata_triflex pata_atiixp pata_amd pata_ali pata_it8213 pata_pcmcia pcmcia pcmcia_core pat
a_ns87415 pata_ns87410
[  932.132962]  pata_serverworks pata_oldpiix pata_artop pata_it821x pata_hpt37x pata_hpt366 pata_cmd64x pata_efar pata_rz1000 pata_sil680 pata_pdc2027x pata_mpiix libata scsi_mod
[  932.132994] CPU: 2 PID: 21213 Comm: txg_sync Tainted: P           O  3.16.2-3 #1
[  932.133003] Hardware name: Gigabyte Technology Co., Ltd. EP45C-DS3R/EP45C-DS3R, BIOS F5 12/16/2008
[  932.133010] task: ffff8800bd4ab2b0 ti: ffff880211028000 task.ti: ffff880211028000
[  932.133017] RIP: 0010:[<ffffffffa0f78c25>]  [<ffffffffa0f78c25>] zap_count_write+0x155/0x3f0 [zfs]
[  932.133037] RSP: 0018:ffff88021102bc48  EFLAGS: 00010296
[  932.133043] RAX: 000000000000001d RBX: ffff8800be597000 RCX: 000000000000001e
[  932.133049] RDX: 000000000000001d RSI: 000000000000001c RDI: ffff8800be597000
[  932.133055] RBP: 000000000000001c R08: 0000000000000000 R09: 0000000000000002
[  932.133062] R10: 0000000000000000 R11: 0000000000000000 R12: 000000000000001d
[  932.133068] R13: ffff880212724000 R14: 0000000000000002 R15: 0000000000000000
[  932.133074] FS:  0000000000000000(0000) GS:ffff88022fd00000(0000) knlGS:0000000000000000
[  932.133081] CS:  0010 DS: 0000 ES: 0000 CR0: 000000008005003b
[  932.133087] CR2: 0000000000000018 CR3: 00000002130bc000 CR4: 00000000000007e0
[  932.133093] Stack:
[  932.133096]  ffff8802126997f0 0000000000000000 0000000000000202 0000000000000001
[  932.133106]  ffffffffa0f1f266 ffff880212724000 0000000000000000 ffff8800bd7a4ac0
[  932.133117]  ffff880212724000 0000000000000000 ffff8802117c88b8 ffffffffa0f792b4
[  932.133127] Call Trace:
[  932.133143]  [<ffffffffa0f1f266>] ? dmu_bonus_hold+0xd6/0x820 [zfs]
[  932.133162]  [<ffffffffa0f792b4>] ? spa_feature_decr+0x44/0xc0 [zfs]
[  932.133182]  [<ffffffffa0f451fa>] ? dsl_scan_sync+0x7ea/0x9f0 [zfs]
[  932.133193]  [<ffffffffa0e1a9df>] ? spl_kmem_cache_free+0xbf/0x170 [spl]
[  932.133213]  [<ffffffffa0f54f33>] ? spa_sync+0x4b3/0xb00 [zfs]
[  932.133224]  [<ffffffff810a5404>] ? __wake_up+0x34/0x50
[  932.133231]  [<ffffffff810c5692>] ? ktime_get_ts+0x42/0xe0
[  932.133250]  [<ffffffffa0f643f6>] ? txg_fini+0x826/0xa10 [zfs]
[  932.133269]  [<ffffffffa0f64110>] ? txg_fini+0x540/0xa10 [zfs]
[  932.133279]  [<ffffffffa0e1af5b>] ? __thread_exit+0x8b/0xa0 [spl]
[  932.133288]  [<ffffffffa0e1aef0>] ? __thread_exit+0x20/0xa0 [spl]
[  932.133295]  [<ffffffff81085dfd>] ? kthread+0xbd/0xe0
[  932.133302]  [<ffffffff81085d40>] ? kthread_create_on_node+0x180/0x180
[  932.133310]  [<ffffffff815866bc>] ? ret_from_fork+0x7c/0xb0
[  932.133317]  [<ffffffff81085d40>] ? kthread_create_on_node+0x180/0x180
[  932.133322] Code: 00 00 00 0f 1f 00 66 66 66 66 90 41 57 48 89 d0 4d 89 c7 41 56 45 89 ce 41 55 41 54 49 89 d4 55 48 89 f5 53 48 89 fb 48 83 ec 28 <41> 8b 70 18 49 8b 50 08 44 89 4c 24 18 4c 8d 4
c 24 20 48 89 4c 
[  932.133416] RIP  [<ffffffffa0f78c25>] zap_count_write+0x155/0x3f0 [zfs]
[  932.133435]  RSP <ffff88021102bc48>
[  932.133439] CR2: 0000000000000018
[  932.136365] ---[ end trace f14428ff90a4b967 ]---

**Comment by behlendorf** [comment] 2015-02-24 23:25
This is a duplicate of #2946 which includes a proposed patch.

**Closed by behlendorf** 2015-02-24 23:25 UTC
