### ISSUE TITLE
Unable to view snapshots over NFS in 0.7.1

### ISSUE THREAD

**Issue by valgrind** [zfsonlinux/zfs#6594] opened 2017-09-01 13:42 UTC
### System information
Distribution Name       | CentOS
Distribution Version    | 6.9
Linux Kernel                 | 2.6.32-696.6.3.el6 (but also 2.6.32-696.10.1.el6)
Architecture                 | x86_64
ZFS Version                  | 0.7.1-1
SPL Version                  | 0.7.1-1

### Describe the problem you're observing
Contents of snapshots are not visible on NFS clients. The snapshot name itself is there, but no files are visible.

### Describe how to reproduce the problem
Machine A:
Install 0.7.1-1 via dkms RPM on CentOS6.9, 
make pool, 
create a file in the pool/filesystem, 
make a  snapshot

Machine B:
mount pool exported from A,
notice that /mountpoint/.zfs/snapshots/snapshotname/ exists but is empty

### Exact cut-n-pasted reproducer (warts and all) as performed between two cluster nodes

```
* Set up a pool using 0.7.1-1 from the start on clean n5
yum install http://download.zfsonlinux.org/epel/zfs-release.el6.noarch.rpm
yum install dkms zfs

yum install kernel-headers-2.6.32-696.6.3.el6 kernel-devel-2.6.32-696.6.3.el6
dkms install -m spl -v 0.7.1 && dkms install -m zfs -v 0.7.1

/sbin/modprobe zfs
dd if=/dev/zero of=testfs3.file bs=1M count=256
zpool create testpool3 /root/testfs3.file
echo "/testpool3 n7(rw,no_root_squash)" > /etc/exports
service nfs start

echo banan > /testpool3/banan
zfs snapshot testpool3@gamma1

* Test client on n7
mount n5:/testpool3 /mnt
ls -a /mnt/.zfs/snapshot/gamma1/
.  ..
  - No "banan"
```

**Comment by MyPod** [comment] 2017-09-01 14:51
IIRC snapshots behave like different mountpoints, so you need to add more parameters to each share in /etc/exports. Try using `(rw,no_root_squash,fsid=0,crossmnt)`.

**Comment by valgrind** [comment] 2017-09-01 16:14
This used to work in 0.6, so it's possible that this is the differance and that it was missed in the release notes. I'm not having much more luck with "crossmnt" though:

'''
# ls -a /mnt/.zfs/snapshot/
.  ..  gamma1
# ls -a /mnt/.zfs/snapshot/gamma1/
ls: cannot access /mnt/.zfs/snapshot/gamma1/: Stale file handle
'''

So there is something else not quite right.

**Comment by behlendorf** [comment] 2017-09-01 17:35
@valgrind the way ZFS handles accessing snapshots over NFS did change in 0.7.x (9b77d1c9585572b7ce3af204d40278752d5f5842) in order to address some corner cases.  If you were manually maintaining and `/etc/exports` file you will need to add the `crossmnt` option, nfsd will now be aware that the snapshots are different filesystems.

You're right this should have been added to the release notes and was overlooked, I'll add it.

**Comment by valgrind** [comment] 2017-09-01 18:55
@behlendorf thanks! Then I know it's supposed to have changed.

I've have not been able to make it work with crossmnt though. Every attempt so far returns "Stale file handle" for the snapshot dir.

**Comment by behlendorf** [comment] 2017-09-01 19:31
@valgrind are you able to view the contents of the snapshot via NFS if you first traverse in to the snapshot directory on the server to trigger the auto-mount?

**Comment by colincdean** [comment] 2017-09-01 19:34
No luck with this here either (zfs 0.7.1-1 CentOS 6.9 server and clients).  Worked fine at 0.6.5. Clients using mount options rw,noatime,nodiratime,vers=3 (vers=3 for historical reasons).  Server exported with rw,sync,no_root_squash when using 0.6, adding fsid=0,crossmnt doesn't help.  Don't know what the corner cases were, but would be helpful to at least have an option to revert to 0.6 behaviour.

**Comment by colincdean** [comment] 2017-09-01 19:41
In our case, if I unmount on client, descend into snapshot on server, and re-mount on client it still doesn't help.  I can see the snapshots on the client if I "ls .zfs/snapshot", but get "Stale file handle" if I try to look inside any of them.

**Comment by valgrind** [comment] 2017-09-01 20:10
@behlendorf no unfortunately that does not seem to change anything even if I restart the server afterwards and remounts the client.

**Comment by behlendorf** [comment] 2017-09-01 20:41
My best guess is that this issue is specific to the old CentOS 6 kernel.  If 0.6.5.11 was working well for you on CentOS 6 you may want to stick with it and only roll forward when you moving to CentOS 7.  At least until someone investigates the root cause.  To my knowledge we have not had any reports of problems from distributions running newer kernels.

**Comment by valgrind** [comment] 2017-09-01 20:46
Might have to do that. Unfortunately testing the snapshot export was not on the testing list, so I did not catch this before having already upgraded one of the production servers. The pool is not upgraded yet though, so hopefully I can roll it back without more problems.

**Comment by behlendorf** [comment] 2017-09-01 21:27
Sorry about that, unfortunately there's a huge surface area to test.  You shouldn't have any trouble rolling back to an older version since you never upgraded the pool.

**Comment by colincdean** [comment] 2017-09-01 21:51
@behlendorf We'd be happy to just roll back for now.  I've just re-downloaded the 0.6.5.11-1.el6 RPMs from http://download.zfsonlinux.org/epel/6/x86_64/, apart from kmod-zfs and kmod-spl, which I can't see there - can you point me at their location?  Many thanks.

**Comment by behlendorf** [comment] 2017-09-01 22:39
They're in http://download.zfsonlinux.org/epel/6/kmod/x86_64/ and you should be able to install them directly with by enabling the kmod repositories and running.

```
yum install spl-0.6.5.11 zfs-0.6.5.11
```

**Comment by hhhappe** [comment] 2017-09-25 12:25
I also hit this issue.

**Comment by behlendorf** [comment] 2017-09-25 18:51
@hhhappe CentOS 6 as well?  I'll update the release notes to make it clear that accessing snapshots over NFS is no longer supported for CentOS 6.

**Comment by valgrind** [comment] 2017-09-25 22:53
For the record I reverted back to 0.6 without problems.

**Comment by behlendorf** [comment] 2017-09-25 23:08
@valgrind thanks for the update.  I'm closing this issue since we can't properly address it for CentOS 6 and the release notes have been updated.  My suggestion would be to continue to run the latest 0.6.5.x if you absolutely have to keep running CentOS 6.

**Closed by behlendorf** 2017-09-25 23:08 UTC
Labels: Documentation

**Comment by hhhappe** [comment] 2017-09-26 05:37
@behlendorf I was on CentOS 6 for both client and server. Just tested with a CentOS 7 server and CentOS 6 client and it worked fine.
