### ISSUE TITLE
New mailing list: robots.txt is missing => google results all 404

### ISSUE THREAD

**Issue by GregorKopka** [zfsonlinux/zfs#3525] opened 2015-06-25 09:59 UTC
Am 25.06.2015 um 03:40 schrieb hungrywolf27 via zfs-discuss:
> Is there a way to search the zfs-discuss archives now that the list (and its pre-migration messages) have been migrated to Mailman? I've tried Google searches with "site:list.zfsonlinux.org", but this doesn't give useful results. 

My guess would be that because http://list.zfsonlinux.org/robots.txt does not exist, google (rightfully) ignores the domain completely and has only stale data (all links in the google result end in 404).

Example:  first hit on page 2 when googling just ```site:list.zfsonlinux.org``` 
(link to search https://www.google.de/search?q=site:list.zfsonlinux.org&start=10)

**[zfs-discuss] Zpool list v. zfs list - ZFS on Linux**

Google result:
http://list.zfsonlinux.org/pipermail/zfs-discuss/2015-April/000745.html (404)
snippet: ```[zfs-discuss] Zpool list v. zfs list. Tren Blackburn iam at theendoftime.net. Mon Apr 13 16:15:33 EDT 2015.```

Manual search the archive:
http://list.zfsonlinux.org/pipermail/zfs-discuss/2015-April/022073.html (correct file)
content: ```[zfs-discuss] Zpool list v. zfs list Tren Blackburn via zfs-discuss zfs-discuss at list.zfsonlinux.org Mon Apr 13 16:15:33 EDT 2015 ```

Quick fix: install a file list.zfsonlinux.org/robots.txt with the following content
```
User-agent: *
Disallow:
```
and visit google webmaster tools to reindex the site.

**Comment by kernelOfTruth** [comment] 2015-06-25 11:55
try explicitly searching through each and every mailing list:

like e.g. so:

```
site:http://list.zfsonlinux.org/pipermail/zfs-discuss/ raidz2
```

**Comment by GregorKopka** [comment] 2015-06-25 12:57
@kernelOfTruth Did you actually try this?
The results are broken...

**Comment by kernelOfTruth** [comment] 2015-06-25 13:19
@GregorKopka yes - just went through all the results for raidz2 and realized they were more broken than for other terms I used before XD

so it's more of a quick'n'dirty and temporary approach to see whether a topic already has been covered

robots.txt probably would be the best approach

**Comment by cbiffle** [comment] 2015-06-25 15:19
This isn't how robots.txt works.

You've configured mailman to request that its contents are not indexed, and Google is following your instructions.  From http://list.zfsonlinux.org/pipermail/zfs-discuss/...

    <meta name="robots" content="noindex,follow">

**Comment by GregorKopka** [comment] 2015-06-25 15:31
Which is correct, it disables indexing the listing pages (since they're irrelevant for search results).
The messages itself are correctly tagged. From http://list.zfsonlinux.org/pipermail/zfs-discuss/2015-June/022463.html
```<meta name="robots" content="index,nofollow">```

Problem is that the google index contains stale information.

**Comment by cbiffle** [comment] 2015-06-25 15:37
Ah, you are correct.  I must not attempt to diagnose web issues before coffee.

Still, the robots.txt is unlikely to be the issue.  I recently switched from a restrictive robots.txt to no robots.txt and my stuff is still indexed promptly.

Unless, of course, some intermediate version of the site *did* briefly have a restrictive robots.txt that Google is still honoring.

Whoever owns the lists.zfsonlinux.org domain should consider using Google Webmaster Tools to answer questions like this.

**Comment by behlendorf** [comment] 2015-06-25 19:21
> Whoever owns the lists.zfsonlinux.org domain should consider using Google Webmaster Tools...

That'd be me.  I had no idea such a tool existed, let me see what it has to say.  But if someone already knows how to fix this please let me know!

**Comment by behlendorf** [comment] 2015-06-29 21:59
Google appear to be happy with the missing `robots.txt` so I didn't install it.  I did however register the site with good webmaster tools and request that it be reindexed.  That scan is now complete and google claims to be happy so hopefully the search results will be improved.

**Comment by kpande** [comment] 2015-09-17 21:11
I host the ML, it seems this is working now. I don't know what the issue is. Maybe Google :-) :+1:

**Comment by behlendorf** [comment] 2015-09-22 17:42
@GregorKopka can we consider this resolved?

**Comment by GregorKopka** [comment] 2015-09-23 12:23
@behlendorf search results delivered by look good at a first glance, no longer broken.

**Comment by behlendorf** [comment] 2015-09-23 20:14
Thanks for verifying.  Closing.

**Closed by behlendorf** 2015-09-23 20:14 UTC
Labels: Bug - Trivial, Documentation
