### ISSUE TITLE
zfs 0.7.0 centos package is missing manpages

### ISSUE THREAD

**Issue by devZer0** [zfsonlinux/zfs#6460] opened 2017-08-04 10:52 UTC
for example, i am missing the zpool manpage in zfs 0.7.0 centos package. where has it gone ?

[root@backupvm1 ~]# rpm -q -a |grep zfs-
zfs-dkms-0.6.5.9-1.el7.centos.noarch
zfs-release-1-3.el7.centos.noarch
zfs-0.6.5.9-1.el7.centos.x86_64

[root@backupvm1 ~]# rpm -q -i zfs
Name        : zfs
Version     : 0.6.5.9
Release     : 1.el7.centos
Architecture: x86_64
Install Date: Mi 08 Feb 2017 14:50:09 CET
Group       : System Environment/Kernel
Size        : 820520
License     : CDDL
Signature   : RSA/SHA256, Sa 04 Feb 2017 00:30:03 CET, Key ID a9d5a1c0f14ab620
Source RPM  : zfs-0.6.5.9-1.el7.centos.src.rpm
Build Date  : Sa 04 Feb 2017 00:29:16 CET
Build Host  : fedora-25-repo
Relocations : (not relocatable)
URL         : http://zfsonlinux.org/
Summary     : Commands to control the kernel modules and libraries
Description :
This package contains the ZFS command line utilities.

[root@backupvm1 ~]# rpm -q --list zfs-0.6.5.9-1.el7.centos.x86_64 |grep man
/usr/share/man/man1/zhack.1.gz
/usr/share/man/man1/zpios.1.gz
/usr/share/man/man1/ztest.1.gz
/usr/share/man/man5/vdev_id.conf.5.gz
/usr/share/man/man5/zfs-events.5.gz
/usr/share/man/man5/zfs-module-parameters.5.gz
/usr/share/man/man5/zpool-features.5.gz
/usr/share/man/man8/fsck.zfs.8.gz
/usr/share/man/man8/mount.zfs.8.gz
/usr/share/man/man8/vdev_id.8.gz
/usr/share/man/man8/zdb.8.gz
/usr/share/man/man8/zed.8.gz
/usr/share/man/man8/zfs.8.gz
/usr/share/man/man8/zinject.8.gz
/usr/share/man/man8/zpool.8.gz
/usr/share/man/man8/zstreamdump.8.gz

[root@rx300-1 /]# rpm -q -a|grep zfs-
kmod-zfs-0.7.0-1.el7_3.x86_64
zfs-release-1-4.el7_3.centos.noarch
zfs-0.7.0-1.el7_3.x86_64

[root@rx300-1 /]# rpm -q -i zfs
Name        : zfs
Version     : 0.7.0
Release     : 1.el7_3
Architecture: x86_64
Install Date: Fr 04 Aug 2017 12:33:28 CEST
Group       : System Environment/Kernel
Size        : 1029322
License     : CDDL
Signature   : RSA/SHA256, Mi 26 Jul 2017 20:02:17 CEST, Key ID a9d5a1c0f14ab620
Source RPM  : zfs-0.7.0-1.el7_3.src.rpm
Build Date  : Mi 26 Jul 2017 19:55:28 CEST
Build Host  : fedora-24-repo
Relocations : (not relocatable)
URL         : http://zfsonlinux.org/
Summary     : Commands to control the kernel modules and libraries
Description :
This package contains the ZFS command line utilities.

[root@rx300-1 /]# rpm -q --list zfs-0.7.0-1.el7_3.x86_64|grep man
/usr/share/man/man1/raidz_test.1.gz
/usr/share/man/man1/test-runner.1.gz
/usr/share/man/man1/zhack.1.gz
/usr/share/man/man1/zpios.1.gz
/usr/share/man/man1/ztest.1.gz
/usr/share/man/man5/vdev_id.conf.5.gz
/usr/share/man/man5/zfs-events.5.gz
/usr/share/man/man5/zfs-module-parameters.5.gz
/usr/share/man/man5/zpool-features.5.gz
/usr/share/man/man8/fsck.zfs.8.gz
/usr/share/man/man8/mount.zfs.8.gz
/usr/share/man/man8/vdev_id.8.gz
/usr/share/man/man8/zdb.8.gz
/usr/share/man/man8/zed.8.gz
/usr/share/man/man8/zfs.8.gz
/usr/share/man/man8/zgenhostid.8.gz

**Comment by bunder2015** [comment] 2017-08-04 10:54
When did you install it?  I was under the impression that this was fixed in https://github.com/zfsonlinux/zfs/commit/0f69f42b43637548bec225ed25fa71b032de114e

**Comment by gmelikov** [comment] 2017-08-04 10:55
closed as duplicate of #6409, please read contribution guidelines next time.

**Closed by gmelikov** 2017-08-04 10:55 UTC

**Comment by devZer0** [comment] 2017-08-04 13:49
i reinstalled today 

[root@rx300-1 var]# rpm -q -i zfs
Name        : zfs
Version     : 0.7.0
Release     : 1.el7_3
Architecture: x86_64
Install Date: Fr 04 Aug 2017 12:33:28 CEST
Group       : System Environment/Kernel
Size        : 1029322
License     : CDDL
Signature   : RSA/SHA256, Mi 26 Jul 2017 20:02:17 CEST, Key ID a9d5a1c0f14ab620
Source RPM  : zfs-0.7.0-1.el7_3.src.rpm
Build Date  : Mi 26 Jul 2017 19:55:28 CEST
Build Host  : fedora-24-repo
Relocations : (not relocatable)
URL         : http://zfsonlinux.org/
Summary     : Commands to control the kernel modules and libraries
Description :
This package contains the ZFS command line utilities.

[root@rx300-1 var]# man zpool
Kein Handbucheintrag für zpool vorhanden
