### ISSUE TITLE
Deadlock with crashdump and zpool history

### ISSUE THREAD

**Issue by lukemarsden** [zfsonlinux/zfs#2309] opened 2014-05-07 14:56 UTC
A deadlock on recent HEAD. `modinfo zfs`:

```
filename:       /lib/modules/3.13.0-24-generic/extra/zfs/zfs/zfs.ko
version:        0.6.2-274_g2c33b91
license:        CDDL
author:         Sun Microsystems/Oracle, Lawrence Livermore National Laboratory
description:    ZFS
srcversion:     F6471B3005F520F80BF2AD5
```

Crashdump with stacks and `zpool history` output:  http://hybridcluster.net/zol-hangs/201405070723/

**Comment by behlendorf** [comment] 2016-03-25 20:45
Closing as a duplicate of #2301 was has been resolved.

**Closed by behlendorf** 2016-03-25 20:45 UTC
Labels: Bug
