### ISSUE TITLE
zfs-mount fails because directory isn't empty, screws up bind mounts and NFS

### ISSUE THREAD

**Issue by brando56894** [zfsonlinux/zfs#4784] opened 2016-06-22 16:35 UTC
I posted this over at the Arch forums but I haven't gotten any responses after a week. I've been running ZoL on Arch for probably about 6 months and ZoL on Ubuntu 14.10 LTS for about 3 months prior to that, before that I was running it on FreeNAS 9. 

Everything was working fine up until a month or so ago when the **zfs-mount.service** daemon failed to start after a reboot, which causes my bind mounts to fail, which in turn causes my NFS mounts to screw up since they're mounting empty directories and breaks my Usenet KVM since it runs out of space.

I can't seem to figure out what the issue is, it seems like Linux is trying to double mount my pools for some reason, because even though the daemon fails, all the pools (3 in total) are mounted successfully and previous to zfs-mount running since they're already mounted. If I disable the zfs-mount service then the pools never get mounted.

Here's the journal error from zfs-mount.service

```
 [root@nas ~]# status zfs-mount
● zfs-mount.service - Mount ZFS filesystems
   Loaded: loaded (/usr/lib/systemd/system/zfs-mount.service; static; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2016-06-21 21:39:40 EDT; 14h ago
  Process: 4414 ExecStart=/usr/bin/zfs mount -a (code=exited, status=1/FAILURE)
 Main PID: 4414 (code=exited, status=1/FAILURE)

Jun 21 21:39:40 nas.brandongolway.us systemd[1]: Starting Mount ZFS filesystems...
Jun 21 21:39:40 nas.brandongolway.us zfs[4414]: cannot mount '/mnt/downloads': directory is not empty
Jun 21 21:39:40 nas.brandongolway.us zfs[4414]: cannot mount '/mnt/downloads/usenet': directory is not empty
Jun 21 21:39:40 nas.brandongolway.us zfs[4414]: cannot mount '/mnt/safekeeping': directory is not empty
Jun 21 21:39:40 nas.brandongolway.us zfs[4414]: cannot mount '/mnt/storage': directory is not empty
Jun 21 21:39:40 nas.brandongolway.us zfs[4414]: cannot mount '/mnt/storage/multimedia': directory is not empty
Jun 21 21:39:40 nas.brandongolway.us systemd[1]: zfs-mount.service: Main process exited, code=exited, status=1/FAILURE
Jun 21 21:39:40 nas.brandongolway.us systemd[1]: Failed to start Mount ZFS filesystems.
Jun 21 21:39:40 nas.brandongolway.us systemd[1]: zfs-mount.service: Unit entered failed state.
Jun 21 21:39:40 nas.brandongolway.us systemd[1]: zfs-mount.service: Failed with result 'exit-code'.
```

Once the system is fully loaded I have to destroy my Usenet KVM, manually mount the bind mounts (mount -a doesn't work for some reason, even though they're in /etc/fstab), then restart the Usenet KVM and all is well. I've also tried using service files for the bind mounts but that didn't seem to work either.

I'm using the zfs-linux-git package0.6.5_r62_g16fc1ec_4.6.2_1-1

**Comment by FransUrbo** [comment] 2016-06-22 16:39
> Everything was working fine up until a month or so ago when the **zfs-mount.service** daemon failed to start after a reboot, which causes my bind mounts to fail, which in turn causes my NFS mounts to screw up since they're mounting empty directories and breaks my Usenet KVM since it runs out of space.

This happen every now and then but have proven almost impossible to debug (because it can't be reproduced reliably).

The "only" (real) way to solve this is to boot into rescue mode, import your pool WITHOUT mouthing anything but the base filesystem. Then remove everything in there.

Then run "zfs mount -a" until it possibly fail on some other directory. Then make sure nothing is mounted below that, remove all mount points (make sure they're empty!) and then try "mount -a" again. Do this until it can mount and unmount a couple of times.

Then unmount all filesystems, export the pool and reboot. This time it should boot correctly.

**Comment by brando56894** [comment] 2016-06-22 17:20
Ah that's wonderful hahaha Luckily I don't reboot often and I'm only using ZoL until FreeNAS 10 becomes usable later this year. I'll give it a try later on. Thanks for the info.

I was thinking that my best solution would be to just forgo the bind mounts and export the mount points directly so it doesn't matter if the zfs-mount fails since the pools still get mounted either way, I'm the only one using my server so security isn't really an issue.

**Comment by tuxoko** [comment] 2016-06-23 01:21
@FransUrbo 
So, mount would failed on non-empty mount point?
But doesn't linux allow mounting on non-empty directory?

**Comment by GregorKopka** [comment] 2016-06-24 08:21
> But doesn't linux allow mounting on non-empty directory?

While Linux allows mounting on a non-empty directory, Solaris didn't (where ZFS comes from).

With a current enough ZoL you can **zfs set overlay=on** on the dataset(s) in question (or a parent dataset, since the property is inherited) to make ZFS behave like linux.

**Comment by FransUrbo** [comment] 2016-06-24 10:04
@brando56894 I mean the base of your pool.

@tuxoko, what @GregorKopka  said. It was decided that ZFS is ZFS and should behave like ZFS, not Linux. Maybe don't make huge sense for the large [Linux] community, but it makes more sense when you think of ZFS a multi-OS service..

**Comment by richardelling** [comment] 2016-06-24 13:28
@GregorKopka your history is incorrect. Solaris always did allow overlay mounts, which led to a significant number of service calls. Service calls are expensive. Thus when ZFS came along, they learned from their prior mistake and restricted overlay mounts. That said, in modern times, one could argue there are use cases for overlay mounts, even though the cost of service calls continues to rise. Gun loaded, pointed down, hoping to miss foot.

**Comment by kpande** [comment] 2016-06-24 15:05
`zfs set overlay=on` is not recommended because you will eventually be hit by #3186 and that is especially nasty with root on ZFS.

**Comment by GregorKopka** [comment] 2016-06-28 12:17
@richardelling the SUN didn't shine on my prior to ZFS, sorry for that.

@kpande following that reasoning zfs send/recv shouldn't be recommended because you'll eventually be hit by https://github.com/zfsonlinux/zfs/issues/4811, I think this line of thinking is a bad idea and should not be pursued any further...

**Comment by kpande** [comment] 2016-06-28 13:00
@GregorKopka using `overlay=on` is known to make a ZFS root system not boot up, so the line of reasoning to avoid it is sound.

**Comment by GregorKopka** [comment] 2016-06-28 15:31
@kpande my point was that the bug you referenced should be fixed instead, let's continue the discussion there.

**Comment by tuxoko** [comment] 2016-07-01 00:46
@FransUrbo What about making the mountpoint readonly? That should prevent anyone from accidentally put stuff in it, no?

**Comment by pyropeter** [comment] 2016-07-28 22:25
This happens because the order in which fstab-mounts and zfs-mounts happen is undefined.

See zfs-mount.service and one of the auto-generated mount-units.

Systemd orders the auto-generated mounts by filesystem hierachy. See systemd.mount(5).

**Comment by Jip-Hop** [comment] 2018-01-17 18:30
Any news on this issue?

Because I think I'm affected too.
I followed the [Ubuntu-16.04-Root-on-ZFS guide](https://github.com/zfsonlinux/zfs/wiki/Ubuntu-16.04-Root-on-ZFS) and after a few reboots I'm running into this:
```
systemctl status zfs-mount.service
● zfs-mount.service - Mount ZFS filesystems
   Loaded: loaded (/lib/systemd/system/zfs-mount.service; static; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2018-01-17 19:20:15 CET; 1min 19s ago
  Process: 1568 ExecStart=/sbin/zfs mount -a (code=exited, status=1/FAILURE)
 Main PID: 1568 (code=exited, status=1/FAILURE)

Jan 17 19:20:15 systemd[1]: Starting Mount ZFS filesystems...
Jan 17 19:20:15 zfs[1568]: cannot mount '/root': directory is not empty
Jan 17 19:20:15 systemd[1]: zfs-mount.service: Main process exited, code=exited, status=1/FAILURE
Jan 17 19:20:15 systemd[1]: Failed to start Mount ZFS filesystems.
Jan 17 19:20:15 systemd[1]: zfs-mount.service: Unit entered failed state.
Jan 17 19:20:15 systemd[1]: zfs-mount.service: Failed with result 'exit-code'.
```
Any advice on how to fix this?
I guess this is the cause of a lot of other problems I'm seeing, e.g. apache2 not starting because `SSLCertificateFile: file '/root/.acme.sh/domain/domain.cer' does not exist or is empty`.

Even though it was there for sure before rebooting.

**Comment by Jip-Hop** [comment] 2018-01-17 18:40
Like I said I followed the guide in the wiki. Therefore I ended up with this version of ZoL:

```
dmesg | grep ZFS
[    0.000000] Command line: BOOT_IMAGE=/ROOT/ubuntu@/boot/vmlinuz-4.4.0-109-generic root=ZFS=rpool/ROOT/ubuntu ro
[    0.000000] Kernel command line: BOOT_IMAGE=/ROOT/ubuntu@/boot/vmlinuz-4.4.0-109-generic root=ZFS=rpool/ROOT/ubuntu ro
[    3.963731] ZFS: Loaded module v0.6.5.6-0ubuntu16, ZFS pool version 5000, ZFS filesystem version 5
```

That's not the most recent version I guess. Can this problem be solved by updating to the new release? If so, how should I do that?

**Comment by Tsuroerusu** [comment] 2018-03-21 00:57
I just ran into this problem on Debian 9 with ZoL 0.7.6. In my case it fails to mount my /tmp dataset for the same reasons stated earlier, that zfs-mount.service is not started early enough, so that it manages to create some dot-directories, specifically .font-unix, ICE-unix, .Test-unix, .X11-unix and .XIM-unix, before ZFS gets a chance to try to mount the /tmp folder.

**Comment by pjgoodall** [comment] 2018-11-20 21:56
I have a pool i can mount with an alternate root. Export it, and it leaves the alternate root behind. 

```
[ zpool import -R /recover/foo my-pool
 > ls -l recover
 drwxr-xr-x 6 root root 4096 Nov 20 08:13 foo
 zpool export my-pool
 > ls -l /recover
 drwxr-xr-x 6 root root 4096 Nov 20 08:13 foo
 rm -rf /recover/foo
] forever
```

**Closed** 2019-02-16 10:39 UTC
