### ISSUE TITLE
deadlock on kswapd0

### ISSUE THREAD

**Issue by tomposmiko** [zfsonlinux/zfs#2317] opened 2014-05-09 19:11 UTC
May  9 12:20:55 lxc06 kernel: [1302113.342610] kswapd0         D ffff88081fc14440     0    77      2 0x00000000
May  9 12:20:55 lxc06 kernel: [1302113.342620]  ffff8807eff093e4 ffff8807ef9417f0 00000000ffffffff ffff8807eff093e8
May  9 12:20:55 lxc06 kernel: [1302113.342633]  [<ffffffff8171c215>] __mutex_lock_slowpath+0x135/0x1b0
May  9 12:20:55 lxc06 kernel: [1302113.342702]  [<ffffffffa019c454>] zfs_inactive+0x64/0x200 [zfs]
May  9 12:20:55 lxc06 kernel: [1302113.342735]  [<ffffffff811d4770>] evict+0xb0/0x1b0
May  9 12:20:55 lxc06 kernel: [1302113.342743]  [<ffffffff811bccc9>] super_cache_scan+0xf9/0x160
May  9 12:20:55 lxc06 kernel: [1302113.342751]  [<ffffffff81163c6b>] kswapd+0x15b/0x410
May  9 12:20:55 lxc06 kernel: [1302113.342761]  [<ffffffff8108b312>] kthread+0xd2/0xf0
May  9 12:20:55 lxc06 kernel: [1302113.342769]  [<ffffffff8108b240>] ? kthread_create_on_node+0x1d0/0x1d0
May  9 12:20:55 lxc06 kernel: [1302113.342773] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
May  9 12:20:55 lxc06 kernel: [1302113.342780]  0000000000014440 0000000000014440 ffff8807ef9447d0 ffffffffa01ea358
May  9 12:20:55 lxc06 kernel: [1302113.342790]  [<ffffffff8171a3a9>] schedule_preempt_disabled+0x29/0x70
May  9 12:20:55 lxc06 kernel: [1302113.342808]  [<ffffffffa0109aea>] arc_evict+0xfa/0x6e0 [zfs]
May  9 12:20:55 lxc06 kernel: [1302113.342846]  [<ffffffffa010dee9>] arc_kmem_reap_now+0xa9/0xb0 [zfs]
May  9 12:20:55 lxc06 kernel: [1302113.342870]  [<ffffffff8115fda7>] shrink_slab+0x1c7/0x370
May  9 12:20:55 lxc06 kernel: [1302113.342877]  [<ffffffff8116311c>] try_to_free_pages+0xec/0x180
May  9 12:20:55 lxc06 kernel: [1302113.342886]  [<ffffffff8171901d>] ? schedule_timeout+0x17d/0x2d0
May  9 12:20:55 lxc06 kernel: [1302113.342893]  [<ffffffff811a8790>] ? khugepaged_scan_mm_slot+0xc90/0xc90
May  9 12:20:55 lxc06 kernel: [1302113.342900]  [<ffffffff8172637c>] ret_from_fork+0x7c/0xb0
May  9 12:20:55 lxc06 kernel: [1302113.342908]       Tainted: PF        C O 3.13.0-24-generic #46-Ubuntu
May  9 12:20:55 lxc06 kernel: [1302113.342912]  ffff8807eca47d40 0000000000000002 ffff8807ef9e8000 ffff8807eca47fd8
May  9 12:20:55 lxc06 kernel: [1302113.342920] Call Trace:
May  9 12:20:55 lxc06 kernel: [1302113.342931]  [<ffffffff8171c2af>] mutex_lock+0x1f/0x2f
May  9 12:20:55 lxc06 kernel: [1302113.342955]  [<ffffffffa010ae60>] ? arc_adjust+0x150/0x150 [zfs]
May  9 12:20:55 lxc06 kernel: [1302113.342974]  [<ffffffff81097712>] ? set_user_nice+0xd2/0x170
May  9 12:20:55 lxc06 kernel: [1302113.342996]  [<ffffffffa006a690>] ? __thread_exit+0xa0/0xa0 [spl]
May  9 12:20:55 lxc06 kernel: [1302113.343003]  [<ffffffff8172637c>] ret_from_fork+0x7c/0xb0
May  9 12:20:55 lxc06 kernel: [1302113.343015]       Tainted: PF        C O 3.13.0-24-generic #46-Ubuntu
May  9 12:20:55 lxc06 kernel: [1302113.343019]  ffff8800359bfcf0 0000000000000002 ffff8807e7ab17f0 ffff8800359bffd8
May  9 12:20:55 lxc06 kernel: [1302113.343027] Call Trace:
May  9 12:20:55 lxc06 kernel: [1302113.343033]  [<ffffffff8171c2af>] mutex_lock+0x1f/0x2f
May  9 12:20:55 lxc06 kernel: [1302113.343101]  [<ffffffffa01a89c6>] zio_execute+0xa6/0x140 [zfs]
May  9 12:20:55 lxc06 kernel: [1302113.343113]  [<ffffffff8109a790>] ? wake_up_state+0x20/0x20
May  9 12:20:55 lxc06 kernel: [1302113.343123]  [<ffffffff8108b240>] ? kthread_create_on_node+0x1d0/0x1d0

zfs was probably 0.6.2-2.1~trusty~10.gbp94fd6e or 0.6.2-2.1~trusty~11.gbpdc470a from the daily ppa, I'm not sure, since it's rebooted with the latest version now.

It's a jenkins server with a couple of other LXC containers:

                                                 capacity     operations    bandwidth
pool                                          alloc   free   read  write   read  write
--------------------------------------------  -----  -----  -----  -----  -----  -----
tank                                           626G   302G     42    130   753K  1.52M
  mirror                                       626G   302G     42    127   753K  1.42M
    ata-WDC_WD10JFCX-68N6GN0_WD-WX21EA3D4747      -      -     19     30   433K  1.65M
    ata-WDC_WD10JFCX-68N6GN0_WD-WXK1AA3Z2181      -      -     19     31   431K  1.65M
logs                                              -      -      -      -      -      -
  sda3                                         692K  1.84G      0      2     46   110K
cache                                             -      -      -      -      -      -
  sda4                                        3.86G  78.1G      2      1  49.9K   130K
  zram1                                       1.99G  7.95M      2      2  50.9K   136K
  zram2                                       1.99G     8M      2      2  49.7K   137K
  zram3                                       1.99G     8M      2      2  52.2K   140K
  zram4                                       1.99G     8M      2      2  50.2K   140K
--------------------------------------------  -----  -----  -----  -----  -----  -----

swapon -s:
Filename				Type		Size	Used	Priority
/dev/sda2                               partition	14648316	0	5
/dev/zram0                              partition	4194300	1481220	100

I'm pretty sure, that swap wasn't full.

**Comment by tomposmiko** [comment] 2015-11-07 14:00
@behlendorf
Does it make sense to keep this issue alive? There were so much changes in the code...

**Comment by behlendorf** [comment] 2015-12-16 18:15
@tomposmiko thanks for calling my attention to this issue.  Unless you're still able to reproduce something like this I don't think it makes sense to keep this open any more since so much has changed.  I'll close it out and we can always open a new one if you are still seeing this.

**Closed by behlendorf** 2015-12-16 18:15 UTC
Labels: Bug
