### ISSUE TITLE
zpool import -T is broken

### ISSUE THREAD

**Issue by ryao** [zfsonlinux/zfs#1926] opened 2013-12-04 19:05 UTC
`zpool import -T` is broken. Here are simple steps to reproduce:

```
truncate -s 1G /tmp/zfs
zpool create test /tmp/zfs
zpool export test
# This should show that the highest transaction group is 8.
zdb -lu /tmp/zfs 
zpool import -d /tmp test
zpool export test
# This should show that the transaction group increased
zdb -lu /tmp/zfs 
zpool import -T 8 -d /tmp test
```
The output will be `cannot import 'test': one or more devices is currently unavailable`. This is a problem when -F is needed and does not work. I am filing this as a note to myself to fix this.

**Comment by behlendorf** [comment] 2016-07-15 20:30
Closing as duplicate of #2452.

**Closed by behlendorf** 2016-07-15 20:30 UTC
Labels: Bug - Major, Difficulty - Medium
