### ISSUE TITLE
[discussion] How stable is the JSON Output in regards to ABI/API Compatibility

### ISSUE THREAD

**Issue by FireDrunk** [zfsonlinux/zfs#6967] opened 2017-12-15 10:37 UTC
I would like to get a discussion flowing regarding this subject:
https://github.com/storaged-project/udisks/issues/42#issuecomment-351897207

I've requested support in the udisks library (which in turn gives ZFS compatibility to a lot of applications using the udisks library, for example Cockpit).

In the discussion, some folks suggested using "shell out to cli tools" as a method to circumvent the ZFS Licensing issues for distributed binaries.

One problem might be that the JSON output is 'less stable' than the LibZFS backwards compatibility between major/minor versions.

Is there some 'guideline' or any expectation we can have regarding the 'stability' of the JSON output from any ZFS version?

**Comment by tonyhutter** [comment] 2017-12-21 21:25
I wasn't aware ZFS provided JSON output.  Where are you seeing it?

**Comment by FireDrunk** [comment] 2017-12-26 08:49
https://github.com/zfsonlinux/zfs/pull/3938

I thought it was being worked on, guess it died in the meantime.

**Comment by behlendorf** [comment] 2017-12-27 22:05
Philosophically I haven't heard any strong objections to adding JSON output as long as it can be done in a  long term maintainable way.  And as you mentioned above one potential problem is that once it's merged we do want to keep the interface stable.

**Comment by kpande** [comment] 2017-12-27 22:08
if it were merged wouldn't it be as stable as general ZFS output ever could be? i.e. adding the -c flag to zpool status wouldn't output the new JSON by default. or am I misunderstanding, and the ZFS output structure itself would change somehow?

**Comment by behlendorf** [comment] 2017-12-27 22:32
That's the idea.  And since the JSON is structured and can be versioned I'd expect the output to be more stable.

**Comment by richardelling** [comment] 2017-12-27 23:05
Having been through several of these interface translation projects, the problem is not the mechanics of converting nvlists to json objects. The problems arise in understanding how the internal representation of objects might relate to practical uses and how to handle data that doesn't fit well into a json interface. An example of the former, some attributes can only be set at creation time or inherited, yet a JSON consumer might not have the information to know how to handle these. For the latter, consider an enum, like the compression algorithm or vdev state: these do not translate well to/from a json number/string in a way that is easily maintainable over time, even with a version number.

What does work is a thoughtful model of what the control plane interface looks like and how json consumers can interact in a meaningful and intentional manner. In other words, rather than exposing all of the sausage ingredients, work with the sausage links themselves. This necessarily results in specific use case designs and implementations. I've now worked on 4 such things, all are different for various business reasons. I'm not convinced a one-size fits all solution is actually useful, given the work involved in creating and maintaining it.

**Comment by alek-p** [comment] 2017-12-28 19:34
What we've done at datto is piggyback JSON output support on top of channel programs (https://github.com/zfsonlinux/zfs/pull/6558). This way the JSON output support is targeted to scripting use cases and is easily maintainable since it really only touches one function (`zfs_do_channel_program()`).
Of course, this only adds the ability to get JSON output for zfs commands, we're still thinking about how to cleanly do this for zpool commands.

Our upstream plans is to wait for channel programs to be merged then add unit testing and upstream our patch.

**Comment by richardelling** [comment] 2017-12-29 15:37
@alek-p that is a clever use of channel programs. TBH, if we were to do this again, I'd seriously consider using protobufs over JSON because it handles numbers, enums, and versions better.

**Comment by FireDrunk** [comment] 2018-01-03 10:19
So you are suggesting we build Protobuf support on the Channel Program interface? Or are you suggesting native support for protobufs inside the entire codebase? (or maybe i'm misunderstanding, and it's the same thing :-) )

Whichever it is, can we make a decision on which it's going to be (maybe discuss this with the OpenZFS community, and get some sort of 'standard', which makes use of such an interface 'fairly' the same on all operating systems ZFS is running on.

I'd be happy to help, but i'm not the right person to lead the effort on getting this organised, I can only help in (some) building and testing.

**Comment by richardelling** [comment] 2018-01-04 03:36
@FireDrunk the internal data structures for interfaces are nvlists, which are more similar to protobufs than JSON.

Regardless of the interface data interchange format, the problem remains that the user of the interface must necessarily understand too much of the internal structure to easily use. Hence most people create a more user-friendly interface to fit their design goals.

**Comment by FireDrunk** [comment] 2018-01-04 10:06
That leaves us at an impass, Do we create a user/developer-friendly interface which is easy to use, or do we create an interface which can represent the internal data structure perfectly, but is less user/developer-friendly?

**Comment by ptx0** [comment] 2018-01-12 20:04
using JSON has the benefit of already being implemented in other languages and will not require custom interpreters to be built. it's funny, but the protobuf interface would require just as much initial work to use as the current methods are - output scraping, and the like...

and with regards to JSON schema it just seems like using a sledgehammer to turn a screw.. why do we need 1:1 correspondence between the internal structures and the JSON output? does every command even require JSON output? so far, `zpool status` is the main pain in the ass. or are you even wanting `zdb` to be JSONified?

further, it has the advantage of actually coming into fruition sometime in the next decade. if we sit around trying to figure out which schema to use or how to convert objects.. we'll never have it working..

**Comment by kpande** [comment] 2018-01-12 20:54
this discussion is better suited for [the zfs-devel mailing list](http://list.zfsonlinux.org) or even [the openzfs devel list](https://openzfs.topicbox.com/groups/developer) instead.

**Closed by kpande** 2018-01-12 20:54 UTC
