### ISSUE TITLE
Centos kernel update 693 -  zfs modules not loading

### ISSUE THREAD

**Issue by muff1nman** [zfsonlinux/zfs#6735] opened 2017-10-08 03:58 UTC
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Centos
Distribution Version    | 7
Linux Kernel                 | 3.10.0-693.2.2.el7.x86_64
Architecture                 | x86_64
ZFS Version                  | 0.6.5.9
SPL Version                  | 0.6.5.9

### Problem
The kmod based package failed for me after updating my kernel to 693. Didn't really dig into the issue with kmod much and just removed all zfs related packages and switched to the dkms package to see if that would work. The following is a log trying to install the zfs dkms based package.

### DKMS installation log

```
[root@HOST /]# yum install zfs
Loaded plugins: changelog, fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.compevo.com
 * elrepo: elrepo.org
 * epel: mirror.chpc.utah.edu
 * extras: mirror.steadfast.net
 * nux-dextop: mirror.li.nux.ro
 * updates: centos-distro.cavecreek.net
Resolving Dependencies
--> Running transaction check
---> Package zfs.x86_64 0:0.6.5.9-1.el7.centos will be installed
--> Processing Dependency: zfs-kmod = 0.6.5.9 for package: zfs-0.6.5.9-1.el7.centos.x86_64
--> Processing Dependency: spl = 0.6.5.9 for package: zfs-0.6.5.9-1.el7.centos.x86_64
--> Processing Dependency: libzpool2 = 0.6.5.9 for package: zfs-0.6.5.9-1.el7.centos.x86_64
--> Processing Dependency: libzfs2 = 0.6.5.9 for package: zfs-0.6.5.9-1.el7.centos.x86_64
--> Processing Dependency: libuutil1 = 0.6.5.9 for package: zfs-0.6.5.9-1.el7.centos.x86_64
--> Processing Dependency: libnvpair1 = 0.6.5.9 for package: zfs-0.6.5.9-1.el7.centos.x86_64
--> Processing Dependency: libzpool.so.2()(64bit) for package: zfs-0.6.5.9-1.el7.centos.x86_64
--> Processing Dependency: libzfs_core.so.1()(64bit) for package: zfs-0.6.5.9-1.el7.centos.x86_64
--> Processing Dependency: libzfs.so.2()(64bit) for package: zfs-0.6.5.9-1.el7.centos.x86_64
--> Processing Dependency: libuutil.so.1()(64bit) for package: zfs-0.6.5.9-1.el7.centos.x86_64
--> Processing Dependency: libnvpair.so.1()(64bit) for package: zfs-0.6.5.9-1.el7.centos.x86_64
--> Running transaction check
---> Package libnvpair1.x86_64 0:0.6.5.9-1.el7.centos will be installed
---> Package libuutil1.x86_64 0:0.6.5.9-1.el7.centos will be installed
---> Package libzfs2.x86_64 0:0.6.5.9-1.el7.centos will be installed
---> Package libzpool2.x86_64 0:0.6.5.9-1.el7.centos will be installed
---> Package spl.x86_64 0:0.6.5.9-1.el7.centos will be installed
--> Processing Dependency: spl-kmod = 0.6.5.9 for package: spl-0.6.5.9-1.el7.centos.x86_64
---> Package zfs-dkms.noarch 0:0.6.5.9-1.el7.centos will be installed
--> Processing Dependency: dkms >= 2.2.0.3-20 for package: zfs-dkms-0.6.5.9-1.el7.centos.noarch
--> Processing Dependency: gcc for package: zfs-dkms-0.6.5.9-1.el7.centos.noarch
--> Running transaction check
---> Package dkms.noarch 0:2.3-5.20170523git8c3065c.el7 will be installed
---> Package gcc.x86_64 0:4.8.5-16.el7 will be installed
--> Processing Dependency: cpp = 4.8.5-16.el7 for package: gcc-4.8.5-16.el7.x86_64
--> Processing Dependency: glibc-devel >= 2.2.90-12 for package: gcc-4.8.5-16.el7.x86_64
--> Processing Dependency: libmpfr.so.4()(64bit) for package: gcc-4.8.5-16.el7.x86_64
--> Processing Dependency: libmpc.so.3()(64bit) for package: gcc-4.8.5-16.el7.x86_64
---> Package spl-dkms.noarch 0:0.6.5.9-1.el7.centos will be installed
--> Running transaction check
---> Package cpp.x86_64 0:4.8.5-16.el7 will be installed
---> Package glibc-devel.x86_64 0:2.17-196.el7 will be installed
--> Processing Dependency: glibc-headers = 2.17-196.el7 for package: glibc-devel-2.17-196.el7.x86_64
--> Processing Dependency: glibc-headers for package: glibc-devel-2.17-196.el7.x86_64
---> Package libmpc.x86_64 0:1.0.1-3.el7 will be installed
---> Package mpfr.x86_64 0:3.1.1-4.el7 will be installed
--> Running transaction check
---> Package glibc-headers.x86_64 0:2.17-196.el7 will be installed
--> Processing Dependency: kernel-headers >= 2.2.1 for package: glibc-headers-2.17-196.el7.x86_64
--> Processing Dependency: kernel-headers for package: glibc-headers-2.17-196.el7.x86_64
--> Running transaction check
---> Package kernel-headers.x86_64 0:3.10.0-693.2.2.el7 will be installed
--> Finished Dependency Resolution
--> Finding unneeded leftover dependencies
Found and removing 0 unneeded dependencies

Dependencies Resolved

===================================================================================================================================================
 Package                            Arch                       Version                                           Repository                   Size
===================================================================================================================================================
Installing:
 zfs                                x86_64                     0.6.5.9-1.el7.centos                              zfs                         336 k
Installing for dependencies:
 cpp                                x86_64                     4.8.5-16.el7                                      base                        5.9 M
 dkms                               noarch                     2.3-5.20170523git8c3065c.el7                      epel                         78 k
 gcc                                x86_64                     4.8.5-16.el7                                      base                         16 M
 glibc-devel                        x86_64                     2.17-196.el7                                      base                        1.1 M
 glibc-headers                      x86_64                     2.17-196.el7                                      base                        675 k
 kernel-headers                     x86_64                     3.10.0-693.2.2.el7                                updates                     6.0 M
 libmpc                             x86_64                     1.0.1-3.el7                                       base                         51 k
 libnvpair1                         x86_64                     0.6.5.9-1.el7.centos                              zfs                          38 k
 libuutil1                          x86_64                     0.6.5.9-1.el7.centos                              zfs                          43 k
 libzfs2                            x86_64                     0.6.5.9-1.el7.centos                              zfs                         125 k
 libzpool2                          x86_64                     0.6.5.9-1.el7.centos                              zfs                         425 k
 mpfr                               x86_64                     3.1.1-4.el7                                       base                        203 k
 spl                                x86_64                     0.6.5.9-1.el7.centos                              zfs                          29 k
 spl-dkms                           noarch                     0.6.5.9-1.el7.centos                              zfs                         444 k
 zfs-dkms                           noarch                     0.6.5.9-1.el7.centos                              zfs                         1.9 M

Transaction Summary
===================================================================================================================================================
Install  1 Package (+15 Dependent packages)

Total download size: 33 M
Installed size: 77 M
Is this ok [y/d/N]: y
Downloading packages:
(1/16): dkms-2.3-5.20170523git8c3065c.el7.noarch.rpm                                                                        |  78 kB  00:00:00     
(2/16): glibc-devel-2.17-196.el7.x86_64.rpm                                                                                 | 1.1 MB  00:00:01     
(3/16): libmpc-1.0.1-3.el7.x86_64.rpm                                                                                       |  51 kB  00:00:00     
(4/16): libnvpair1-0.6.5.9-1.el7.centos.x86_64.rpm                                                                          |  38 kB  00:00:00     
(5/16): libuutil1-0.6.5.9-1.el7.centos.x86_64.rpm                                                                           |  43 kB  00:00:00     
(6/16): libzfs2-0.6.5.9-1.el7.centos.x86_64.rpm                                                                             | 125 kB  00:00:00     
(7/16): libzpool2-0.6.5.9-1.el7.centos.x86_64.rpm                                                                           | 425 kB  00:00:00     
(8/16): glibc-headers-2.17-196.el7.x86_64.rpm                                                                               | 675 kB  00:00:03     
(9/16): mpfr-3.1.1-4.el7.x86_64.rpm                                                                                         | 203 kB  00:00:00     
(10/16): spl-0.6.5.9-1.el7.centos.x86_64.rpm                                                                                |  29 kB  00:00:00     
(11/16): spl-dkms-0.6.5.9-1.el7.centos.noarch.rpm                                                                           | 444 kB  00:00:00     
(12/16): zfs-0.6.5.9-1.el7.centos.x86_64.rpm                                                                                | 336 kB  00:00:00     
(13/16): cpp-4.8.5-16.el7.x86_64.rpm                                                                                        | 5.9 MB  00:00:05     
(14/16): zfs-dkms-0.6.5.9-1.el7.centos.noarch.rpm                                                                           | 1.9 MB  00:00:01     
(15/16): kernel-headers-3.10.0-693.2.2.el7.x86_64.rpm                                                                       | 6.0 MB  00:00:07     
(16/16): gcc-4.8.5-16.el7.x86_64.rpm                                                                                        |  16 MB  00:00:12     
---------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                              2.6 MB/s |  33 MB  00:00:12     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : libuutil1-0.6.5.9-1.el7.centos.x86_64                                                                                          1/16 
  Installing : libnvpair1-0.6.5.9-1.el7.centos.x86_64                                                                                         2/16 
  Installing : mpfr-3.1.1-4.el7.x86_64                                                                                                        3/16 
  Installing : libmpc-1.0.1-3.el7.x86_64                                                                                                      4/16 
  Installing : libzpool2-0.6.5.9-1.el7.centos.x86_64                                                                                          5/16 
  Installing : libzfs2-0.6.5.9-1.el7.centos.x86_64                                                                                            6/16 
  Installing : cpp-4.8.5-16.el7.x86_64                                                                                                        7/16 
  Installing : kernel-headers-3.10.0-693.2.2.el7.x86_64                                                                                       8/16 
  Installing : glibc-headers-2.17-196.el7.x86_64                                                                                              9/16 
  Installing : glibc-devel-2.17-196.el7.x86_64                                                                                               10/16 
  Installing : gcc-4.8.5-16.el7.x86_64                                                                                                       11/16 
  Installing : dkms-2.3-5.20170523git8c3065c.el7.noarch                                                                                      12/16 
  Installing : spl-dkms-0.6.5.9-1.el7.centos.noarch                                                                                          13/16 
Loading new spl-0.6.5.9 DKMS files...
Building for 3.10.0-693.2.2.el7.x86_64
Building initial module for 3.10.0-693.2.2.el7.x86_64
Done.

spl:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/3.10.0-693.2.2.el7.x86_64/extra/

splat.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/3.10.0-693.2.2.el7.x86_64/extra/
Adding any weak-modules

depmod....

DKMS: install completed.
  Installing : zfs-dkms-0.6.5.9-1.el7.centos.noarch                                                                                          14/16 
Loading new zfs-0.6.5.9 DKMS files...
Building for 3.10.0-693.2.2.el7.x86_64
Building initial module for 3.10.0-693.2.2.el7.x86_64
Error! Bad return status for module build on kernel: 3.10.0-693.2.2.el7.x86_64 (x86_64)
Consult /var/lib/dkms/zfs/0.6.5.9/build/make.log for more information.
warning: %post(zfs-dkms-0.6.5.9-1.el7.centos.noarch) scriptlet failed, exit status 10
Non-fatal POSTIN scriptlet failure in rpm package zfs-dkms-0.6.5.9-1.el7.centos.noarch
  Installing : spl-0.6.5.9-1.el7.centos.x86_64                                                                                               15/16 
  Installing : zfs-0.6.5.9-1.el7.centos.x86_64                                                                                               16/16 
  Verifying  : cpp-4.8.5-16.el7.x86_64                                                                                                        1/16 
  Verifying  : libnvpair1-0.6.5.9-1.el7.centos.x86_64                                                                                         2/16 
  Verifying  : zfs-0.6.5.9-1.el7.centos.x86_64                                                                                                3/16 
  Verifying  : kernel-headers-3.10.0-693.2.2.el7.x86_64                                                                                       4/16 
  Verifying  : mpfr-3.1.1-4.el7.x86_64                                                                                                        5/16 
  Verifying  : zfs-dkms-0.6.5.9-1.el7.centos.noarch                                                                                           6/16 
  Verifying  : libmpc-1.0.1-3.el7.x86_64                                                                                                      7/16 
  Verifying  : spl-dkms-0.6.5.9-1.el7.centos.noarch                                                                                           8/16 
  Verifying  : spl-0.6.5.9-1.el7.centos.x86_64                                                                                                9/16 
  Verifying  : gcc-4.8.5-16.el7.x86_64                                                                                                       10/16 
  Verifying  : libzpool2-0.6.5.9-1.el7.centos.x86_64                                                                                         11/16 
  Verifying  : glibc-headers-2.17-196.el7.x86_64                                                                                             12/16 
  Verifying  : glibc-devel-2.17-196.el7.x86_64                                                                                               13/16 
  Verifying  : libuutil1-0.6.5.9-1.el7.centos.x86_64                                                                                         14/16 
  Verifying  : libzfs2-0.6.5.9-1.el7.centos.x86_64                                                                                           15/16 
  Verifying  : dkms-2.3-5.20170523git8c3065c.el7.noarch                                                                                      16/16 

Installed:
  zfs.x86_64 0:0.6.5.9-1.el7.centos                                                                                                                

Dependency Installed:
  cpp.x86_64 0:4.8.5-16.el7                    dkms.noarch 0:2.3-5.20170523git8c3065c.el7        gcc.x86_64 0:4.8.5-16.el7                        
  glibc-devel.x86_64 0:2.17-196.el7            glibc-headers.x86_64 0:2.17-196.el7               kernel-headers.x86_64 0:3.10.0-693.2.2.el7       
  libmpc.x86_64 0:1.0.1-3.el7                  libnvpair1.x86_64 0:0.6.5.9-1.el7.centos          libuutil1.x86_64 0:0.6.5.9-1.el7.centos          
  libzfs2.x86_64 0:0.6.5.9-1.el7.centos        libzpool2.x86_64 0:0.6.5.9-1.el7.centos           mpfr.x86_64 0:3.1.1-4.el7                        
  spl.x86_64 0:0.6.5.9-1.el7.centos            spl-dkms.noarch 0:0.6.5.9-1.el7.centos            zfs-dkms.noarch 0:0.6.5.9-1.el7.centos           

Complete!
[root@HOST /]# zfs list
The ZFS modules are not loaded.
Try running '/sbin/modprobe zfs' as root to load them.
[root@HOST /]# /sbin/modprobe zfs
modprobe: FATAL: Module zfs not found.
[root@HOST /]# cat /var/lib/dkms/zfs/0.6.5.9/build/make.log
DKMS make.log for zfs-0.6.5.9 for kernel 3.10.0-693.2.2.el7.x86_64 (x86_64)
Sat Oct  7 21:49:45 MDT 2017
make  all-recursive
make[1]: Entering directory `/var/lib/dkms/zfs/0.6.5.9/build'
Making all in include
make[2]: Entering directory `/var/lib/dkms/zfs/0.6.5.9/build/include'
Making all in linux
make[3]: Entering directory `/var/lib/dkms/zfs/0.6.5.9/build/include/linux'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/var/lib/dkms/zfs/0.6.5.9/build/include/linux'
Making all in sys
make[3]: Entering directory `/var/lib/dkms/zfs/0.6.5.9/build/include/sys'
Making all in fm
make[4]: Entering directory `/var/lib/dkms/zfs/0.6.5.9/build/include/sys/fm'
Making all in fs
make[5]: Entering directory `/var/lib/dkms/zfs/0.6.5.9/build/include/sys/fm/fs'
make[5]: Nothing to be done for `all'.
make[5]: Leaving directory `/var/lib/dkms/zfs/0.6.5.9/build/include/sys/fm/fs'
make[5]: Entering directory `/var/lib/dkms/zfs/0.6.5.9/build/include/sys/fm'
make[5]: Nothing to be done for `all-am'.
make[5]: Leaving directory `/var/lib/dkms/zfs/0.6.5.9/build/include/sys/fm'
make[4]: Leaving directory `/var/lib/dkms/zfs/0.6.5.9/build/include/sys/fm'
Making all in fs
make[4]: Entering directory `/var/lib/dkms/zfs/0.6.5.9/build/include/sys/fs'
make[4]: Nothing to be done for `all'.
make[4]: Leaving directory `/var/lib/dkms/zfs/0.6.5.9/build/include/sys/fs'
make[4]: Entering directory `/var/lib/dkms/zfs/0.6.5.9/build/include/sys'
make[4]: Nothing to be done for `all-am'.
make[4]: Leaving directory `/var/lib/dkms/zfs/0.6.5.9/build/include/sys'
make[3]: Leaving directory `/var/lib/dkms/zfs/0.6.5.9/build/include/sys'
make[3]: Entering directory `/var/lib/dkms/zfs/0.6.5.9/build/include'
make[3]: Nothing to be done for `all-am'.
make[3]: Leaving directory `/var/lib/dkms/zfs/0.6.5.9/build/include'
make[2]: Leaving directory `/var/lib/dkms/zfs/0.6.5.9/build/include'
Making all in rpm
make[2]: Entering directory `/var/lib/dkms/zfs/0.6.5.9/build/rpm'
Making all in generic
make[3]: Entering directory `/var/lib/dkms/zfs/0.6.5.9/build/rpm/generic'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/var/lib/dkms/zfs/0.6.5.9/build/rpm/generic'
Making all in redhat
make[3]: Entering directory `/var/lib/dkms/zfs/0.6.5.9/build/rpm/redhat'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/var/lib/dkms/zfs/0.6.5.9/build/rpm/redhat'
make[3]: Entering directory `/var/lib/dkms/zfs/0.6.5.9/build/rpm'
make[3]: Nothing to be done for `all-am'.
make[3]: Leaving directory `/var/lib/dkms/zfs/0.6.5.9/build/rpm'
make[2]: Leaving directory `/var/lib/dkms/zfs/0.6.5.9/build/rpm'
Making all in module
make[2]: Entering directory `/var/lib/dkms/zfs/0.6.5.9/build/module'
make -C /lib/modules/3.10.0-693.2.2.el7.x86_64/build SUBDIRS=`pwd`  CONFIG_ZFS=m modules
make[3]: Entering directory `/usr/src/kernels/3.10.0-693.2.2.el7.x86_64'
  CC [M]  /var/lib/dkms/zfs/0.6.5.9/build/module/avl/avl.o
  CC [M]  /var/lib/dkms/zfs/0.6.5.9/build/module/unicode/u8_textprep.o
  CC [M]  /var/lib/dkms/zfs/0.6.5.9/build/module/nvpair/nvpair.o
  CC [M]  /var/lib/dkms/zfs/0.6.5.9/build/module/zcommon/zfs_deleg.o
In file included from include/linux/blkdev.h:19:0,
                 from /usr/src/spl-0.6.5.9/include/sys/uio.h:30,
                 from /usr/src/spl-0.6.5.9/include/sys/sunddi.h:29,
                 from /usr/src/spl-0.6.5.9/include/sys/systm.h:28,
                 from /var/lib/dkms/zfs/0.6.5.9/build/include/sys/zfs_context.h:49,
                 from /var/lib/dkms/zfs/0.6.5.9/build/module/zcommon/zfs_deleg.c:27:
/var/lib/dkms/zfs/0.6.5.9/build/include/linux/blkdev_compat.h:309:18: error: expected identifier or ‘(’ before ‘struct’
 bio_set_op_attrs(struct bio *bio, unsigned rw, unsigned flags)
                  ^
include/linux/bio.h:48:44: note: in definition of macro ‘bio_set_op_attrs’
 #define bio_set_op_attrs(bio, op, flags) ((bio)->bi_rw |= (op | flags))
                                            ^
include/linux/bio.h:48:48: error: expected ‘)’ before ‘->’ token
 #define bio_set_op_attrs(bio, op, flags) ((bio)->bi_rw |= (op | flags))
                                                ^
/var/lib/dkms/zfs/0.6.5.9/build/include/linux/blkdev_compat.h:309:1: note: in expansion of macro ‘bio_set_op_attrs’
 bio_set_op_attrs(struct bio *bio, unsigned rw, unsigned flags)
 ^
make[5]: *** [/var/lib/dkms/zfs/0.6.5.9/build/module/zcommon/zfs_deleg.o] Error 1
make[4]: *** [/var/lib/dkms/zfs/0.6.5.9/build/module/zcommon] Error 2
make[4]: *** Waiting for unfinished jobs....
  CC [M]  /var/lib/dkms/zfs/0.6.5.9/build/module/unicode/uconv.o
  LD [M]  /var/lib/dkms/zfs/0.6.5.9/build/module/avl/zavl.o
  CC [M]  /var/lib/dkms/zfs/0.6.5.9/build/module/nvpair/fnvpair.o
  CC [M]  /var/lib/dkms/zfs/0.6.5.9/build/module/nvpair/nvpair_alloc_spl.o
  CC [M]  /var/lib/dkms/zfs/0.6.5.9/build/module/nvpair/nvpair_alloc_fixed.o
  LD [M]  /var/lib/dkms/zfs/0.6.5.9/build/module/unicode/zunicode.o
  LD [M]  /var/lib/dkms/zfs/0.6.5.9/build/module/nvpair/znvpair.o
make[3]: *** [_module_/var/lib/dkms/zfs/0.6.5.9/build/module] Error 2
make[3]: Leaving directory `/usr/src/kernels/3.10.0-693.2.2.el7.x86_64'
make[2]: *** [modules] Error 2
make[2]: Leaving directory `/var/lib/dkms/zfs/0.6.5.9/build/module'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/var/lib/dkms/zfs/0.6.5.9/build'
make: *** [all] Error 2

```

**Comment by loli10K** [comment] 2017-10-08 06:04
Duplicate of #6661

**Closed by loli10K** 2017-10-08 06:04 UTC
