### ISSUE TITLE
Mounting with -o noatime succeeds and shows in /proc/mounts, but is not authoritative

### ISSUE THREAD

**Issue by jvsalo** [zfsonlinux/zfs#3519] opened 2015-06-24 11:58 UTC
If a dataset has property atime=on, mounting with noatime succeeds without error and noatime is shown in /proc/mounts, but in fact, atime is still enabled.

The build I used to test was v0.6.4-1.1-1-wheezy.

Someone else confirmed on IRC this does not happen on Illumos; mounting with noatime really disables atime.

**Comment by behlendorf** [comment] 2015-06-24 17:09
@jvsalo for the moment you'll need to set this with `zfs set atime=off ...` on the dataset.  That should work.

The issue is that unlike Illumos the Linux VFS allows you to concurrently mount one filesystem in multiple locations all with _different_ mount options.  To make this possible the Linux VFS treats mount time options like 'noatime' as specific to a particular namespace and that information never gets passed all the way down to the filesystem.  The result in the kernel's generic VFS layer knows the option was set but the lower layers of ZFS don't so atime updates are still performed.  Using `zfs set atime=off` side steps this issue.  I'm sure it's possible to handle this case more cleanly but it going to require tighter integration with the VFS.

**Comment by behlendorf** [comment] 2016-10-04 03:33
Closing, the various atime issues were was addressed by:

2b54cb1 Add zfs-tests for relatime
6760077 Make zfs mount according to relatime config in dataset
704cd07 Enable lazytime semantic for atime
0df9673 Fix atime handling and relatime

**Closed by behlendorf** 2016-10-04 03:33 UTC
