### ISSUE TITLE
Poor random write performance, from 0.7.1 to 0.7.11

### ISSUE THREAD

**Issue by woquflux** [zfsonlinux/zfs#7959] opened 2018-09-26 06:02 UTC
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Redhat
Distribution Version	| 7.4
Linux Kernel	| 3.10.0-693.el7.x86_64
Architecture	| 
ZFS Version	| 0.7.1~0.7.11
SPL Version	| 0.7.1~0.7.11

### Describe the problem you're observing
Very bad write performance

Rebuild zpool with different versions on the same device

Version 0.6.5.9.11
![image](https://user-images.githubusercontent.com/30719174/46060144-9e4d8080-c194-11e8-8608-bc536dfc101f.png)

Version 0.7.1 ~0.7.11
![image](https://user-images.githubusercontent.com/30719174/46060160-b9b88b80-c194-11e8-9ddd-a55bae5c221d.png)
<img width="1163" alt="image" src="https://user-images.githubusercontent.com/30719174/46060583-72cb9580-c196-11e8-948a-61d98a541c09.png">

### Describe how to reproduce the problem
zpool create xxxx sdx
zfs create -V 100G xxxx/test 

fio.ini
[global]
ioengine=libaio
iodepth=1
direct=1
numjobs=1
group_reporting
time_based
runtime=600
size=100g
filename=/dev/xxxx/test
rw=randwrite
bs=8K

**Comment by gmelikov** [comment] 2018-09-26 07:16
Looks like a duplicate of #7834 , benchmark results are nearly same, i'd prefer to close this issue.

**Closed by gmelikov** 2018-09-26 07:16 UTC

**Comment by kpande** [comment] 2018-09-26 20:15
@behlendorf can we ban this user from the issue tracker? they can't seem to follow rules or common etiquette.

**Comment by behlendorf** [comment] 2018-09-26 21:39
@kpande that doesn't seem necessary.  The issue has been closed and marked as a duplicate.

**Comment by woquflux** [comment] 2018-09-27 06:41
@kpande 

Why? Just because I submitted a suspected duplicate question? 

The previous issue was version 0.7.9 + dataset. I was having problems with 0.7.1~0.7.11 + zvol, and the performance loss was more serious. I think it is necessary to report. 

I have no opinion that the community thinks that the repetition needs to be closed. But is it a bit too much to ban me?

@behlendorf 
In addition, this version has been used in the production environment and caused some economic losses, and can not be rolled back to the 0.6.x version, so I admit that I am a little impatient, I am sorry for this.

**Comment by drescherjm** [comment] 2018-09-27 12:04
I believe if someone who has this problem could bisect the code changes and find the commit that caused this there would be a better chance that this is fixed in the near term.

**Comment by gmelikov** [comment] 2018-09-27 12:29
@drescherjm please see #7834, bisecting is already done there.

**Comment by woquflux** [comment] 2018-09-27 12:32
This issue has been closed, we should not continue to discuss it here, thanks for your attention.
