### ISSUE TITLE
Kernel panic in ZFS on Ubuntu

### ISSUE THREAD

**Issue by sveinse** [zfsonlinux/zfs#3683] opened 2015-08-12 18:46 UTC
System: Ubuntu 15.04, amd64, Kernel 3.19.0-25-generic. zfs 0.6.4.2-1~vivid. 6-drive raidz2. zfs on root.

I have observed two similar kernel panics recently. I'm not 110% sure, but from the zfs related activities I was working on prior to the crash, it can be one of two cases:

A) Turning off sync for efficiency of installation:

`zfs snapshot tank/neo/system@$(date +%FT%TZ); zfs set sync=disabled tank/neo/system; aptitude; zfs inherit sync tank/neo/system`

B) Traversing the .zfs/snapshots/ dir from the shell.

As you can see, they are the precisely the same crash:

![2015-08-12 20 00 15e](https://cloud.githubusercontent.com/assets/13770135/9233163/e79ed946-4131-11e5-9ada-372f1762e786.png)
![20150713_185341e](https://cloud.githubusercontent.com/assets/13770135/9233167/eab784ca-4131-11e5-9837-e501067e4283.png)

**Comment by dasjoe** [comment] 2015-08-12 18:52
> B) Traversing the .zfs/snapshots/ dir from the shell.

This is a known issue, tracked mainly in #3030. There's a proposed fix in PR #3344.

**Comment by behlendorf** [comment] 2015-08-19 17:06
Closing as duplicate of #3030.

**Closed by behlendorf** 2015-08-19 17:06 UTC
