### ISSUE TITLE
losetup/truecrypt/cryptsetup hard freeze on zfs and kernel 4.1

### ISSUE THREAD

**Issue by timemaster67** [zfsonlinux/zfs#3612] opened 2015-07-19 21:43 UTC
Running zfs 0.6.4.2 on kernel 4.1.2, user can cause an oops that completly freeze the computer when using losetup or any other utility that use it (cryptsetup, truecrypt for example). Crash only happen on zfs filesystem, xfs and ext4 have not issue. 

Please see finding in arch forum https://bbs.archlinux.org/viewtopic.php?pid=1546065#p1546065
This include kernel stacktrace of the bug.

**Comment by kernelOfTruth** [comment] 2015-07-19 21:53
@timemaster67 you guys tried doing it without blk-mq and a regular i/o scheduler (cfq, deadline, noop) ?

**Comment by timemaster67** [comment] 2015-07-19 22:01
hummm... using noop io scheduler for all my disk, 
as for blk-mq, I cannot find clear indication on how to disable it ? kernel parameter scsi_mod.use_blk_mq=0 ?

**Comment by kernelOfTruth** [comment] 2015-07-19 22:14
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1397061
https://ask.fedoraproject.org/en/question/51266/how-to-enable-blk-mq-on-fedora-20-315/

yes, probably

```
scsi_mod.use_blk_mq=0
```

**Comment by behlendorf** [comment] 2015-07-20 17:02
You might also try explicitly creating the pool with `ashift=12` and see if that resolves the issue.  We've observed issues similar to this in the past caused by ZFS exposing bugs in the kernel due to it accessing block devices in 512 byte blocks.  File systems such as ext4 and xfs only access the device in page aligned chunks which is what ZFS will do if you set the `ashift=12`

**Comment by l1k** [comment] 2015-07-21 12:41
This might be a duplicate of #3511. (Unfortunately I didn't get around yet to bisect that issue or test with 4.2.)

**Comment by timemaster67** [comment] 2015-07-22 01:54
so I have been testing this, but I am even more confused than before. 
I create a vm under virtualbox with Arch on zfs root to test the issue. 
I do have kernel crash, but they produce random stacktrace. 
I tried to disable blk_mq with the kernel parameter, and tried with a pool in ashift=12, but in all scenario I get oops and crash.

**Comment by timemaster67** [comment] 2015-07-22 02:01
arch config : 
CONFIG_POSIX_MQUEUE=y
CONFIG_POSIX_MQUEUE_SYSCTL=y
# CONFIG_SCSI_MQ_DEFAULT is not set
# CONFIG_DM_MQ_DEFAULT is not set
CONFIG_DM_CACHE_MQ=m

default ashift, blk_mq default : crash http://pastebin.com/hdMwKEf8
default ashift, blk_mq disabled : crash http://pastebin.com/c0DFtEdf
ashift=12 bld_mq default : crash http://pastebin.com/iF7UhLgt

tried with both scsi_mod.use_blk_mq=N and scsi_mod.use_blk_mq=0. N seems more official as that's what I found in more pages. 
ashift=12 blk_mq disabled : crash http://pastebin.com/VxYbfbke  http://pastebin.com/kHKp0P7d

Did not try to recompile a kernel and tweak config file, as stacktrace are all random. What do we do in this case ?

**Comment by timemaster67** [comment] 2015-07-22 02:04
sorry @l1k, I thought I searched on the list before posting, but apparently did not search enough.

**Comment by DorianGray** [comment] 2015-07-22 18:47
This is still happening in kernel 4.1.3. I can easily reproduce it on my machine(zfs on top of cryptdevices) by using docker 1.7's zfs driver. Starting the service hangs the system.

**Comment by andrew-d** [comment] 2015-07-26 05:40
I have what I think is the same issue - also run Arch Linux.  I'm happy to help debug the problem, if anyone would like the help (@behlendorf).  I don't know much about the internals of ZoL, frankly, so any pointers on how I can help are appreciated :smile_cat:

**Comment by l1k** [comment] 2015-07-26 14:20
@timemaster67 @andrew-d: Please test if reverting torvalds/linux@aa4d86163e4e91a1ac560954a554bab417e338f4 ("block: loop: switch to VFS ITER_BVEC") fixes the issue for you. It does for me.

**Comment by andrew-d** [comment] 2015-07-26 22:56
Okay, so, I compiled a new kernel and installed it, and then manually compiled & installed the zfs packages for Arch (`spl-utils-git`, `spl-git`, `zfs-utils-git`, and `zfs-git`).  After doing all that, it does appear that the problem has been solved :smile: 

The next question, of course, is how to fix the problem permanently?

**Comment by behlendorf** [comment] 2015-07-27 18:49
Thanks to @l1k who identified the kernel change which caused this I think we're in a much better position to resolve it.  Unfortunately, I'm not going to have the time to investigate this but I do think it needs to be treated as a blocker for the next tag.  If someone has the time it work on this that would be very helpful!

**Comment by Bronek** [comment] 2015-07-31 09:19
FWIW I seem to have hard freeze with zfs-0.6.4.2 and linux-4.1.3 on zvols which are attached as disk images to kvm virtual machines (using virtio). Unable to give any details, my kernel build does not provide them as I foolishly disabled all debug options. As a workaround I rolled back to 4.0.9

**Comment by l1k** [comment] 2015-07-31 11:24
@Bronek: Please try applying either the two pulls #3651 + zfsonlinux/spl#468, or alternatively reverting  torvalds/linux@aa4d86163e4e91a1ac560954a554bab417e338f4.

**Comment by behlendorf** [comment] 2015-08-24 18:48
Closing.  This was resolved by #3651 which was merged to master.

**Closed by behlendorf** 2015-08-24 18:48 UTC
Labels: Bug - Major
