### ISSUE TITLE
tuxonice hibernation + thaw causes zfs to freeze/block/hang

### ISSUE THREAD

**Issue by MHOOO** [zfsonlinux/zfs#1703] opened 2013-09-07 11:56 UTC
Hey there, 

I'm using hibernation through tuxonice, since the standard hybernation methods don't work for my system(s). What I noticed though, is that zfs mounts tend to freeze after a thaw. The "freeze" happens, when I try to read files from the zfs mount. It simply blocks the respective program (that is trying to access the file), and I am unable to kill the program at that point. A file listing (think "ls") of the zfs mount still works though.

I can work-around the issue, by manually unmounting (`sudo zfs umount -af`) the mounts before hibernation and re-mounting them afterwards - but sometimes I forget, at which point all I can do is restart the system.

Anyone has an idea on what I can do to fix this?

**Comment by ryao** [comment] 2015-01-20 13:54
@simonbuehler This is a low priority, so no one has done anything with it, but I now have a conjecture that could explain why it does not always work. During normal operation, ZFS will queue IOs to disks and wait for their completion. If it never hears that an IO completed, it will hang. What happens during hibernation is that the kernel stops talking to the drives, so a drive could notify the kernel about IO completion, but the kernel, being hibernated, could no longer be listening. Upon resume, ZFS would still be waiting for the IO completion notification. This will never come because as far as the drive is concerned, it already notified the kernel. We need to use the platform_suspend_ops API to allow us to block on completion of all in-flight IOs (and prevent new ones from being queued until hibernation resumes) so that the system reaches a state where it can safely be hibernated and resumed. If my conjecture is correct, this would solve the problem. However, it opens us to another problem that we should tackle at the same time. In specific, if two systems are sharing a pool (e.g. two Linux installs), one hibernates, the other is booted and then we boot back into the hibernated state, there is a possibility of severe damage to the pool.

We would need to resync all in-core data structures with their on-disk counterparts after resuming (which might not be possible if a mounted dataset is no longer there) to make this scenario safe.

**Comment by ryao** [comment] 2015-09-09 21:03
I have not looked at this lately, but if hibernation only applies to userland processes, my previous thinking could be wrong and there would be a slim chance that this issue could go away with the following patch:

https://github.com/zfsonlinux/spl/pull/474

**Comment by ryao** [comment] 2015-09-09 21:06
This appears to be a duplicate of #1237.

**Comment by behlendorf** [comment] 2015-09-09 21:32
Closing as duplicate of #1237.

**Closed by behlendorf** 2015-09-09 21:32 UTC
Labels: Bug - Minor, Difficulty - Medium
