### ISSUE TITLE
Ubuntu dkms packages fail to build kernel modules.

### ISSUE THREAD

**Issue by tomprince** [zfsonlinux/zfs#3298] opened 2015-04-15 09:40 UTC
Building the kernel modules requires `libc6-dev` to be installed and configued. Installing `zfs-dkms` does correctly install `libc6-dev`, but the dkms build is run before `libc6-dev` is configured, which means the module compilation fails.

**Comment by Amitie10g** [comment] 2015-04-15 12:05
Try to install/update the non-zfs dependencies before installing spl-dkms and zfs-dkms, and tell the exact version that you're required to install and what kernel have you installed (remember that zfs and spl builds with kernels 3.19.x and previous, but is better to use 3.18.11).

Finally, backup the whole /boot directory and re-run ``dkms autoupdate $(uname -r)`` as root, and tell us the results.

**Comment by tomprince** [comment] 2015-04-16 09:10
> Try to install/update the non-zfs dependencies before installing spl-dkms and zfs-dkms

I'm not sure what you mean by this. If I install `libc6-dev` before trying to install `zfs-dkms`, then the install works. Also, if I run `dkms autoupdate` after installing `zfs-dkms`, then the install completes successfully.

(The error is in `./confingue`, with something about `crt1.o` or `-lc` not being available).

The `libc6-dev` package needs to be configured before the `zfs-dkms` will build, but it appears that currently happens after the `zfs-dkms` is installed.

This is on a freshly built rackspace ubuntu 14.04 server.

**Comment by dajhorn** [comment] 2015-04-17 02:39
> The  libc6-dev  package needs to be configured before the  zfs-dkms  will build, but it appears that currently happens after the  zfs-dkms  is installed

This is a known issue for some minimalist and/or incompletely bootstrapped cloud images.  To get the desired result, install `ubuntu-zfs` onto a system that was built with `ubuntu-minimal` or `ubuntu-standard`.  (ie: An initial configuration that the official Ubuntu Installer would create.)

Unfortunately, trying to mitigate this glitch through something like `Pre-Depends` has side-effects for supported system configurations.

**Comment by jongiddy** [comment] 2015-04-21 09:10
This issue duplicates zfsonlinux/pkg-zfs#129

**Comment by behlendorf** [comment] 2015-04-24 19:28
Closing as a duplicate of zfsonlinux/pkg-zfs#129 as mentioned by @jongiddy.

**Closed by behlendorf** 2015-04-24 19:28 UTC
