### ISSUE TITLE
Module load: General protection fault in user access.

### ISSUE THREAD

**Issue by AllKind** [zfsonlinux/zfs#9823] opened 2020-01-08 21:57 UTC
### System information

Type | Version/Name
 --- | --- 
Distribution Name | Linux Mint
Distribution Version	|  19.4 (tricia)
Linux Kernel	|  5.4.7 + 5.4.8
Architecture	|  amd64
ZFS Version	|  0.8.2-2~18.04.york0
SPL Version	|  0.8.2-2~18.04.york0

### Describe the problem you're observing

While booting the trace shown below appears.
It did not show until kernel v.5.4.7 (Tested with 4.19.90 and 5.4.6).
Not sure what it actually means, but thought I'd report it.
No problems are resulting from it, as far as I can tell.

### Describe how to reproduce the problem

Install kernel 5.47+ using ```make deb-pkg```.
Reboot.
```journalctl -b```

```
Jan 08 10:35:38 darklord kernel: ZFS: Loaded module v0.8.2-2~18.04.york0, ZFS pool version 5000, ZFS filesystem version 5
Jan 08 10:35:38 darklord systemd[1]: Started Install ZFS kernel module.
Jan 08 10:35:38 darklord systemd[1]: Starting Import ZFS pools by cache file...
Jan 08 10:35:38 darklord kernel: ------------[ cut here ]------------
Jan 08 10:35:38 darklord kernel: General protection fault in user access. Non-canonical address?
Jan 08 10:35:38 darklord kernel: WARNING: CPU: 15 PID: 1780 at arch/x86/mm/extable.c:126 ex_handler_uaccess+0x52/0x60
Jan 08 10:35:38 darklord kernel: Modules linked in: zfs(POE) zunicode(POE) zavl(POE) icp(POE) zlua(POE) zcommon(POE) znvpair(POE) spl(OE) snd_hda_codec_hdmi nls_iso8859_1 nvidia_uvm(OE) intel_
Jan 08 10:35:38 darklord kernel:  hid_generic usbhid hid igb dca i2c_algo_bit e1000e ahci libahci wmi
Jan 08 10:35:38 darklord kernel: CPU: 15 PID: 1780 Comm: kworker/u32:11 Tainted: P           OE     5.4.8-mint-local-5.4.8 #5.4.8
Jan 08 10:35:38 darklord kernel: Hardware name: ASUS All Series/X99-DELUXE II, BIOS 2101 07/10/2019
Jan 08 10:35:38 darklord kernel: RIP: 0010:ex_handler_uaccess+0x52/0x60
Jan 08 10:35:38 darklord kernel: Code: c4 08 b8 01 00 00 00 5b 5d c3 80 3d fc f7 78 01 00 75 db 48 c7 c7 f8 38 93 83 48 89 75 f0 c6 05 e8 f7 78 01 01 e8 0e 8d 01 00 <0f> 0b 48 8b 75 f0 eb bc 6
Jan 08 10:35:38 darklord kernel: RSP: 0018:ffffb496c0d17cc0 EFLAGS: 00010282
Jan 08 10:35:38 darklord kernel: RAX: 0000000000000000 RBX: ffffffff8340245c RCX: 0000000000000000
Jan 08 10:35:38 darklord kernel: RDX: 000000000000003f RSI: ffffffff8414f0df RDI: 0000000000000246
Jan 08 10:35:38 darklord kernel: RBP: ffffb496c0d17cd0 R08: ffffffff8414f0a0 R09: 0000000000029f80
Jan 08 10:35:38 darklord kernel: R10: 0000000000000000 R11: 00000000000006f4 R12: 000000000000000d
Jan 08 10:35:38 darklord kernel: R13: 0000000000000000 R14: 0000000000000000 R15: 0000000000000000
Jan 08 10:35:38 darklord kernel: FS:  0000000000000000(0000) GS:ffff8c539fbc0000(0000) knlGS:0000000000000000
Jan 08 10:35:38 darklord kernel: CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Jan 08 10:35:38 darklord kernel: CR2: 00005630a925c730 CR3: 0000000192e0a000 CR4: 00000000001406e0
Jan 08 10:35:38 darklord kernel: Call Trace:
Jan 08 10:35:38 darklord kernel:  fixup_exception+0x4a/0x60
Jan 08 10:35:38 darklord kernel:  do_general_protection+0x4e/0x150
Jan 08 10:35:38 darklord kernel:  general_protection+0x28/0x30
Jan 08 10:35:38 darklord kernel: RIP: 0010:strnlen_user+0x4b/0x100
Jan 08 10:35:38 darklord kernel: Code: 0f 86 ca 00 00 00 48 29 f9 45 31 c0 0f 1f 00 0f ae e8 48 39 ce 49 89 f9 48 0f 46 ce 41 83 e1 07 48 83 e7 f8 4a 8d 1c 09 31 c0 <4c> 8b 17 85 c0 75 5a 42 8
Jan 08 10:35:38 darklord kernel: RSP: 0018:ffffb496c0d17de8 EFLAGS: 00010246
Jan 08 10:35:38 darklord kernel: RAX: 0000000000000000 RBX: 0000000000020000 RCX: 0000000000020000
Jan 08 10:35:38 darklord kernel: RDX: d029e70ee4ab7c00 RSI: 0000000000020000 RDI: d029e70ee4ab7c00
Jan 08 10:35:38 darklord kernel: RBP: ffffb496c0d17df0 R08: 0000000000000000 R09: 0000000000000000
Jan 08 10:35:38 darklord kernel: R10: 0000000810d5e067 R11: fefefefefefefeff R12: 00007fffffffefee
Jan 08 10:35:38 darklord kernel: R13: ffff8c538551efee R14: 0000000000000000 R15: ffffda4a60154780
Jan 08 10:35:38 darklord kernel:  copy_strings.isra.31+0x99/0x380
Jan 08 10:35:38 darklord kernel:  __do_execve_file.isra.38+0x685/0x8c0
Jan 08 10:35:38 darklord kernel:  do_execve+0x25/0x30
Jan 08 10:35:38 darklord kernel:  call_usermodehelper_exec_async+0x1a8/0x1c0
Jan 08 10:35:38 darklord kernel:  ? umh_complete+0x40/0x40
Jan 08 10:35:38 darklord kernel:  ret_from_fork+0x1f/0x40
Jan 08 10:35:38 darklord kernel: ---[ end trace 0c50d34e04ede454 ]---
Jan 08 10:35:41 darklord systemd[1]: Started Import ZFS pools by cache file.
Jan 08 10:35:41 darklord systemd[1]: Reached target ZFS pool import target.
Jan 08 10:35:41 darklord systemd[1]: Starting Mount ZFS filesystems...
Jan 08 10:35:41 darklord systemd[1]: Starting Wait for ZFS Volume (zvol) links in /dev...
Jan 08 10:35:41 darklord zvol_wait[2165]: No zvols found, nothing to do.
Jan 08 10:35:41 darklord systemd[1]: Started Wait for ZFS Volume (zvol) links in /dev.
Jan 08 10:35:41 darklord systemd[1]: Reached target ZFS volumes are ready.
Jan 08 10:35:42 darklord systemd[1]: Started Mount ZFS filesystems.
```

**Comment by behlendorf** [comment] 2020-01-09 00:08
Thanks.  Just for reference this is a duplicate of #9609 which has a fix queued up for the as yet unreleased  0.8.3.

**Closed by behlendorf** 2020-01-09 00:08 UTC
