### ISSUE TITLE
Fails to compile with musl: zed_log.c

### ISSUE THREAD

**Issue by raphaelcohn** [zfsonlinux/zfs#4813] opened 2016-06-28 16:48 UTC
zed_log.c should have

    #include <unistd.h>

To compile correctly against musl

**Comment by behlendorf** [comment] 2016-06-28 23:11
@raphaelcohn please open a PR with the fix so we can get it reviewed, tested and applied.  Tagging @clandmeter since this is proposed change in musl related.

**Comment by raphaelcohn** [comment] 2016-06-29 15:39
I've opened a PR. This PR addresses musl compilation. It also fixes an issue with `RUSAGE_THREAD` and reduces substantially a heap of warnings about the 'correct' location of headers (only by eliminating those did I find the issue with `zed_log.c`. I've pushed the issue with `RUSAGE_THREAD` upstream, too.

This PR does not fix two other musl-related issues:-
* Looking for `attr/xattr.h` instead of `sys/xattr.h`;
* Relying on `sys/queue.h`, which musl does not ship. This probably needs a configure test which then uses our own local copy.

I see how this PR goes and, if appropriate, I might submit a further one with adjustments for those issues.

**Comment by clandmeter** [comment] 2016-07-05 13:31
@behlendorf i've just test build current master and I can confirm the RUSAGE_THREAD fix as the discussion can be found here: http://www.openwall.com/lists/musl/2016/06/28/5

The posix include changes breaks my local build.

And my local build doesn't complain about zed_log.c and unistd.h so no need for me to add it.

My suggestion would be to create a separate PR for RUSAGE_THREAD from #4817 so it can be merged.

**Comment by behlendorf** [comment] 2016-07-11 18:41
@clandmeter sounds good.  @raphaelcohn can you split the RUSAGE_THREAD fix in to a separate PR so it can be merged.

The other suggested changes which address the correct location headers are problematic because the code 1) need to build in user and kernel space, and 2) was originally written using the locations of headers from Solaris not Linux.  This can all be improved move it slightly more involved.

**Comment by raphaelcohn** [comment] 2016-07-12 11:09
New release of musl 1.1.15 has come out with a change to define RUSAGE_THREAD. I need to retest my build with this before making any changes.

**Comment by behlendorf** [comment] 2016-07-15 22:24
@raphaelcohn we'll be dropping our usage of RUSAGE_THREAD entirely in #4849 so no need to refresh your PR.

**Closed by behlendorf** 2016-07-15 22:24 UTC
Labels: Build Issue
