### ISSUE TITLE
Online rollback corrupts dcache and cause process hangs on kernel 4.18.

### ISSUE THREAD

**Issue by colmbuckley** [zfsonlinux/zfs#7970] opened 2018-09-29 18:34 UTC
### System information

Distribution Name	| Debian
Distribution Version	| 9.0 Stretch with some backports
Linux Kernel	| 4.18.0-0.bpo.1-amd64
Architecture	| amd64
ZFS Version	| v0.7.11-1
SPL Version	| v0.7.11-1

### Describe the problem you're observing
Descendent filesystems which have external mount points are not correctly recovered on 'zfs send | zfs receive', leading to problems. With kernel 4.18, processes can become wedged.

### Describe how to reproduce the problem
A pool called 'aoi' is available; there are other filesystems on this pool but they are not relevant.

```
# P=aoi
# zfs create -o mountpoint=/test $P/test                                                                                           
# zfs create -o mountpoint=/external $P/test/external
# touch /test/test.0.ok
# touch /external/external.0.ok
# zfs snapshot -r $P/test@0
# zfs send -R $P/test@0 > 0.snap
# touch /test/test.1.ok                              
# touch /external/external.1.ok                      
# zfs snapshot -r $P/test@1     
# zfs send -R -I 0 $P/test@1 > 1.isnap
# zfs list -r -t all $P/test
NAME                  USED  AVAIL  REFER  MOUNTPOINT
aoi/test              320K  94.0G   104K  /test
aoi/test@0             56K      -    96K  -
aoi/test@1              0B      -   104K  -
aoi/test/external     160K  94.0G    96K  /external
aoi/test/external@0    64K      -    96K  -
aoi/test/external@1     0B      -    96K  -
# zfs mount | grep -F $P/test
aoi/test                        /test
aoi/test/external               /external
# find /test /external -ls
       34      1 drwxr-xr-x   2 root     root            4 Sep 29 19:10 /test
        2      1 -rw-r--r--   1 root     root            0 Sep 29 19:10 /test/test.0.ok
      128      1 -rw-r--r--   1 root     root            0 Sep 29 19:10 /test/test.1.ok
       34      1 drwxr-xr-x   2 root     root            4 Sep 29 19:10 /external
        2      1 -rw-r--r--   1 root     root            0 Sep 29 19:10 /external/external.0.ok
      128      1 -rw-r--r--   1 root     root            0 Sep 29 19:10 /external/external.1.ok
```

Ok, so the key here is that the "external" child filesystem is mounted elsewhere; outside the main tree. Now we'll delete the filesystem and restore from the base snapshot, specifying an explicit mountpoint:

```
# zfs destroy -r $P/test          
# zfs receive -Fv -o mountpoint=/test $P/test < 0.snap
receiving full stream of aoi/test@0 into aoi/test@0
received 45.9K stream in 1 seconds (45.9K/sec)
receiving full stream of aoi/test/external@0 into aoi/test/external@0
received 45.9K stream in 1 seconds (45.9K/sec)
# zfs list -r -t all $P/test
NAME                  USED  AVAIL  REFER  MOUNTPOINT
aoi/test              256K  94.0G    96K  /test
aoi/test@0             64K      -    96K  -
aoi/test/external      96K  94.0G    96K  /test/external
aoi/test/external@0     0B      -    96K  -
# zfs mount | grep -F $P/test
aoi/test                        /test
aoi/test/external               /test/external
# find /test /external -ls
       34      1 drwxr-xr-x   3 root     root            4 Sep 29 19:11 /test
       34      1 drwxr-xr-x   2 root     root            3 Sep 29 19:10 /test/external
        2      1 -rw-r--r--   1 root     root            0 Sep 29 19:10 /test/external/external.0.ok
        2      1 -rw-r--r--   1 root     root            0 Sep 29 19:10 /test/test.0.ok
   123370      1 drwxr-xr-x   2 root     root            2 Sep 29 19:10 /external
```

So far so good. The external filesystem is now mounted inside, because -o mountpoint was specified. That seems sensible. Note that /external still exists (empty) despite its having been destroyed (see below).

But things get weird when we add the incremental snapshot:

```
# zfs receive -Fv  $P/test < 1.isnap
receiving incremental stream of aoi/test@1 into aoi/test@1
received 8.14K stream in 1 seconds (8.14K/sec)
receiving incremental stream of aoi/test/external@1 into aoi/test/external@1
received 8.14K stream in 1 seconds (8.14K/sec)
# zfs list -r -t all $P/test
NAME                  USED  AVAIL  REFER  MOUNTPOINT
aoi/test              320K  94.0G   104K  /test
aoi/test@0             56K      -    96K  -
aoi/test@1              0B      -   104K  -
aoi/test/external     160K  94.0G   104K  /test/external
aoi/test/external@0    56K      -    96K  -
aoi/test/external@1     0B      -   104K  -
# zfs mount | grep -F $P/test
aoi/test                        /test
aoi/test/external               /test/external
# find /test /external -ls
       34      1 drwxr-xr-x   2 root     root            4 Sep 29 19:14 /test
        2      1 -rw-r--r--   1 root     root            0 Sep 29 19:14 /test/test.0.ok
      128      1 -rw-r--r--   1 root     root            0 Sep 29 19:14 /test/test.1.ok
   123370      1 drwxr-xr-x   2 root     root            2 Sep 29 19:10 /external
```

The contents of the 'external' filesystem have disappeared. Oh dear. Worse yet, if we look into where it **should** be:

```
ls -la /test/external
<<< process hangs; becomes unkillable until system reboot. CPU usage goes to 100%>>>
```

It sounds like this is corrupting the system's mount table in some interesting way. After a reboot, this pool is correctly imported (I think using `zpool import -c /etc/zfs/zpool.cache -aN`), and we see:

```
# find /test -ls
       34      1 drwxr-xr-x   3 root     root            5 Sep 29 19:18 /test
        2      1 -rw-r--r--   1 root     root            0 Sep 29 19:14 /test/test.0.ok
      128      1 -rw-r--r--   1 root     root            0 Sep 29 19:14 /test/test.1.ok
       34      1 drwxr-xr-x   2 root     root            4 Sep 29 19:14 /test/external
        3      1 -rw-r--r--   1 root     root            0 Sep 29 19:14 /test/external/external.1.ok
        2      1 -rw-r--r--   1 root     root            0 Sep 29 19:14 /test/external/external.0.ok
```

... which is probably correct. It's not totally clear what the semantics of '-o mountpoint' should be for recovery of recursive filesystems, but I think this is clearly bad.

**NOTE:** This behavior is new in kernel 4.18. With kernel 4.17 (even with zfs/spl 0.7.11), I see a distinct difference; the child filesystem does not seem to be mounted at all, but mounting it is successful:

```
# uname -a                       
Linux aoi 4.17.0-0.bpo.3-amd64 #1 SMP Debian 4.17.17-1~bpo9+1 (2018-08-27) x86_64 GNU/Linux
# zfs list -r -t all $P/test     
NAME                  USED  AVAIL  REFER  MOUNTPOINT
aoi/test              320K  94.2G    96K  /test
aoi/test@0             64K      -    96K  -
aoi/test@1              0B      -    96K  -
aoi/test/external     160K  94.2G    96K  /test/external
aoi/test/external@0    64K      -    96K  -
aoi/test/external@1     0B      -    96K  -
# zfs mount | grep -F $P/test
aoi/test                        /test
# find /test/external -ls  
find: ‘/test/external’: No such file or directory
# zfs mount $P/test/external
# ffind /test /external -ls
       34      1 drwxr-xr-x   3 root     root            5 Sep 29 19:29 /test
       34      1 drwxr-xr-x   2 root     root            4 Sep 29 19:26 /test/external
        3      1 -rw-r--r--   1 root     root            0 Sep 29 19:26 /test/external/external.1.ok
        2      1 -rw-r--r--   1 root     root            0 Sep 29 19:26 /test/external/external.0.ok
        2      1 -rw-r--r--   1 root     root            0 Sep 29 19:26 /test/test.0.ok
        3      1 -rw-r--r--   1 root     root            0 Sep 29 19:26 /test/test.1.ok
   123373      1 drwxr-xr-x   2 root     root            2 Sep 29 19:26 /external
```

The serious problem in 4.18 is the processes hanging when trying to access the corrupted child filesystems; 4.17 (and possibly earlier) has a different problem. I think the semantics of '-o mountpoint' on a recursive 'zfs receive' need to be determined, and verified.

Thanks!

**Comment by colmbuckley** [comment] 2018-09-29 19:13
For what it's worth, I think that the most sensible semantics for 'zfs receive -o mountpoint=XXX AAA' where AAA/BBB etc. exist would be to mount AAA on XXX and AAA/BBB on XXX/BBB; that would seem to follow the principle of least surprise.

**Comment by colmbuckley** [comment] 2018-10-01 16:46
Possibly related to https://github.com/zfsonlinux/zfs/issues/3278
https://utcc.utoronto.ca/~cks/space/blog/solaris/ZFSMountpointConundrum is also interesting.

**Comment by colmbuckley** [comment] 2018-10-12 08:21
I'm seeing slightly different results on different systems; the above was on a system largely operating from Debian unstable, zfs 0.7.11-1 installed. On a system largely operating from debian stable+backports, zfs 0.7.11-1~bpo9+1 installed, a process attempting to access the /test/external directory does not hang (file not found), but the mount inconsistency is still present:

```
# cd /test
# ls -la
total 10
drwxr-xr-x  2 root root  4 Oct 12 09:09 .
drwxr-xr-x 19 root root 26 Oct 12 09:09 ..
-rw-r--r--  1 root root  0 Oct 12 09:09 test.0.ok
-rw-r--r--  1 root root  0 Oct 12 09:09 test.1.ok
# cd external
cd: no such file or directory: external
# cd /test/external
cd: no such file or directory: /test/external
# cd /external
# ls -la
total 9
drwxr-xr-x  2 root root  2 Oct 12 09:09 .
drwxr-xr-x 19 root root 26 Oct 12 09:09 ..
# zfs mount tank/test/external
cannot mount 'tank/test/external': filesystem already mounted
# zfs umount tank/test/external
umount: /test/external: mountpoint not found
cannot unmount '/test/external': umount failed
# zfs mount tank/test/external
cannot mount 'tank/test/external': filesystem already mounted
```

**Comment by colmbuckley** [comment] 2018-10-17 05:14
Is anyone else able to reproduce this? Just want confirmation that I'm not either insane or doing something stupid.

**Comment by colmbuckley** [comment] 2018-10-19 04:50
Here's a short shell script which provokes the issue:
```
#!/bin/sh

# Pick a pool (any will do; we choose the first one)
P=$(zpool list -H -o name | head -1)
[ -z "$P" ] && {
        echo "Need an active zpool."
        exit
}

# Pick two mountpoint names
M1=parent.$$
M2=child.$$

# Create ZFS
set -v
zfs create -o mountpoint=/$M1 $P/$M1
zfs create -o mountpoint=/$M2 $P/$M1/$M2

touch /$M1/$M1.0.ok /$M2/$M2.0.ok

zfs snapshot -r $P/$M1@0
zfs send -R $P/$M1@0 > /tmp/$M1.0.snap

touch /$M1/$M1.1.ok /$M2/$M2.1.ok

zfs snapshot -r $P/$M1@1
zfs send -R -I 0 $P/$M1@1 > /tmp/$M1.1.isnap

zfs list -r -t all $P/$M1
zfs mount | grep -F $P/$M1
find /$M1 /$M2 -ls

zfs destroy -r $P/$M1

zfs receive -Fv -o mountpoint=/$M1 $P/$M1 < /tmp/$M1.0.snap

zfs list -r -t all $P/$M1
zfs mount | grep -F $P/$M1
find /$M1 /$M2 -ls

zfs receive -Fv $P/$M1 < /tmp/$M1.1.isnap

zfs list -r -t all $P/$M1
zfs mount | grep -F $P/$M1
find /$M1 /$M2 -ls
find /$M1/$M2 -ls

zfs destroy -r $P/$M1
rm /tmp/$M1.0.snap /tmp/$M1.1.isnap
```

On some of my systems, the final `find` command hangs as it tries to traverse the child mountpoint which "should" be there. On others, it gives a ENOENT, but then the `zfs destroy` fails because of the inconsistent mount table (can't unmount the child filesystem).

**Comment by loli10K** [comment] 2018-11-20 22:38
This doesn't seem to be a `zfs receive` issue, i think it's the rollback (`-F`) option that is causing any command touching the filesystem to spin on cpu.

**Comment by loli10K** [comment] 2018-11-23 21:58
Actually, on second thought, this seems to be a Kernel bug, fixed in 4.18.20 by the following commit:

> mnt: fix __detach_mounts infinite loop
>commit 1e9c75fb9c47a75a9aec0cd17db5f6dc36b58e00 upstream.
>
>Since commit ff17fa561a04 ("d_invalidate(): unhash immediately")
>immediately unhashes the dentry, we'll never return the mountpoint in
>lookup_mountpoint(), which can lead to an unbreakable loop in
>d_invalidate().
>
>I have reports of NFS clients getting into this condition after the server
>removes an export of an existing mount created through follow_automount(),
>but I suspect there are various other ways to produce this problem if we
>hunt down users of d_invalidate().  For example, it is possible to get into
>this state by using XFS' d_invalidate() call in xfs_vn_unlink():
>
>truncate -s 100m img{1,2}
>
>mkfs.xfs -q -n version=ci img1
>mkfs.xfs -q -n version=ci img2
>
>mkdir -p /mnt/xfs
>mount img1 /mnt/xfs
>
>mkdir /mnt/xfs/sub1
>mount img2 /mnt/xfs/sub1
>
>cat > /mnt/xfs/sub1/foo &
>umount -l /mnt/xfs/sub1
>mount img2 /mnt/xfs/sub1
>
>mount --make-private /mnt/xfs
>
>mkdir /mnt/xfs/sub2
>mount --move /mnt/xfs/sub1 /mnt/xfs/sub2
>rmdir /mnt/xfs/sub1
>
>Fix this by moving the check for an unlinked dentry out of the
>detach_mounts() path.

On a local VM i cherry-picked said commit on top of 4.18.18 and could not reproduce the issue anymore.

**Comment by colmbuckley** [comment] 2018-11-23 22:09
That's interesting.

I guess a separate (less serious) issue is some careful thinking about how 'zfs receive' handles out-of-tree child datasets; as the current behavior does not seem to be fully documented.

**Comment by loli10K** [comment] 2018-11-24 08:14
@colmbuckley i don't think i understand what is undocumented about `zfs receive`; you said

> It's not totally clear what the semantics of '-o mountpoint' should be for recovery of recursive filesystems, but I think this is clearly bad.

but the man page states

> -o property=value
> Sets the specified property as if the command zfs set property=value was invoked immediately before the receive. **When receiving a stream from zfs send -R, causes the property to be inherited by
> all descendant datasets, as through zfs inherit property was run on any descendant datasets that have this property set on the sending system.**

which seems clear to me; i also don't understand why the current behaviour is bad.

**Comment by colmbuckley** [comment] 2018-11-24 11:20
I feel that the 'mountpoint' property is distinctive; firstly (trivially) it has effects which extend beyond the confines of the dataset, secondly inheritance works in a particular manner for this property (dataset a with mountpoint /b => dataset a/c has mountpoint /b/c).

My recommendation would be to include a specific documentation section on the inheritance of the mountpoint property, especially under send/receive.

**Comment by loli10K** [comment] 2018-11-24 11:45
> My recommendation would be to include a specific documentation section on the inheritance of the mountpoint property, especially under send/receive.

I believe this is already in the man page:

>    Mount Points
> ...
>     A file system can also have a mount point set in the mountpoint property.  This directory is created as needed, and ZFS automatically mounts the file system when the zfs mount -a command is invoked
>     (without editing /etc/fstab).  **The mountpoint property can be inherited, so if pool/home has a mount point of /export/stuff, then pool/home/user automatically inherits a mount point of
     /export/stuff/user.**

Can you propose the change you would like to be included in the documentation here or by opening a pull request? Thanks!

**Comment by colmbuckley** [comment] 2018-11-24 13:44
Yes; will do. Is there any remedial work which can be done on this issue in ZFS, or is it fully dependent on the kernel fix you mentioned? It has a pretty significant impact on systems which make extensive use of rollback (my trigger was the fairly well-known 'znapzend' backup system, but anything which uses send/receive to replicate snapshots between pools will probably have the same issue).

**Comment by loli10K** [comment] 2018-11-24 14:10
> Is there any remedial work which can be done on this issue in ZFS

I am not sure ZFS can do anything to prevent the issue; i only discovered that commit because i decided to go looking for possible bugs in the kernel since debugging was showing an infinite loop in `d_invalidate()` due to `detach_mounts() -> lookup_mountpoint()` returing ENOENT and `find_submount()` always finding the same mountpoint.

The only workaround i would suggest is to receive unmounted, readonly filesystem without `-F`.

**Comment by colmbuckley** [comment] 2018-11-24 18:12
One thing is still puzzling me; when a descendent dataset is received from a full snapshot, it is mounted, but when its received from an incremental snapshot, it is not mounted (although it shows up in 'zfs mount'). See attached:

```
!/bin/sh -v
P=rpool
M1=parent.$$
M2=child.$$
zfs create -o mountpoint=/$M1 $P/$M1
zfs create -o mountpoint=/$M2 $P/$M1/$M2
zfs snapshot -r $P/$M1@0
zfs send -R $P/$M1@0 > /tmp/$M1.0.snap
zfs snapshot -r $P/$M1@1
zfs send -R -I 0 $P/$M1@1 > /tmp/$M1.1.isnap
zfs destroy -r $P/$M1
rm -rf /$M1 /$M2
zfs receive -F -o mountpoint=/$M1 $P/$M1 < /tmp/$M1.0.snap
ls -ld /$M1 /$M1/$M2
zfs receive -F $P/$M1 < /tmp/$M1.1.isnap
zfs mount | grep -F $M1
ls -ld /$M1 /$M1/$M2
zfs mount $P/$M1/$M2
ls -ld /$M1 /$M1/$M2
zfs destroy -r $P/$M1
rm -rf /$M1 /$M2
```

After the first 'zfs receive' the parent dataset is mounted under /$M1, and the child under /$M1/$M2 as expected. But after the *second* 'zfs receive', the child shows up in zfs mount as being mounted, but /$M1/$M2 is not accessible until the child is explicitly mounted.

(This is Debian's kernel 4.18.6 (backports) with the dentry fix from earlier cherrypicked in.)

**Comment by behlendorf** [comment] 2019-03-20 22:31
Thanks for getting to the root cause of this issue and identifying the specific kernel bug and the fix.  I agree, there's nothing we can do on the ZFS side about this, so I'm going to go ahead and close this issue.

Regarding the behavior described in https://github.com/zfsonlinux/zfs/issues/7970#issuecomment-441385662 that does sound like something we need to investigate.  Let's move that issue to it's own bug.

**Closed by behlendorf** 2019-03-20 22:31 UTC
