### ISSUE TITLE
HDD had errors, ZFS reported repaired data, yet no read/write/cksum errors.

### ISSUE THREAD

**Issue by nicko88** [zfsonlinux/zfs#2246] opened 2014-04-08 03:01 UTC
I noticed after writing several GB to my zpool the other night that one of the disks accumulated 10 (187) Reported_Uncorrect errors as well as 640 (197) Current_Pending_Sector and 640 (198) Offline_Uncorrectable errors in SMART.

At this point there were never any read/write/cksum errors on any disks.

So that night I ran a scrub.  As I was watching the progress, I saw that the scrub started to say it was repairing data, and next to the cksum column there was written "(repairing)" next to the disk that I had previously identified as the one which threw the SMART errors earlier that night when I was writing data to the zpool.

While the the repaired data count for the scrub was slowly increasing, that same disk was  simultaneously gaining additional UNC errors.  A few minutes later, the amount of data  that scrub was repairing stopped increasing (it ended at 9M), and the UNC errors for that disk also stopped, (it ended up with 88 UNC errors).

Also, the 640 Current_Pending_Sector and the 640 Offline_Uncorrectable had now also gone back to 0.

From this info, it seems to me the disk was able to remap these sectors internally (or whatever it does).  Reallocated sectors still remains at 0 so it's some other kind of remapping I guess?

What I found odd is why did ZFS say it was repairing data, yet it never, neither before, during, or after, reported any read/write/cksum errors for any disks?

As far as I understand it, ZFS can't do anything to help the disk remap sectors or anything, that's a totally separate thing.

Here is the screenshots I have:

Current zpool status after scrub (I NEVER ran zpool clear or anything to clear any errors, there never were any reported)

```
root@nick-server:~# zpool status
  pool: nickarray
 state: ONLINE
  scan: scrub repaired 9.00M in 16h49m with 0 errors on Mon Apr  7 16:34:36 2014
config:

        NAME                                          STATE     READ WRITE CKSUM
        nickarray                                     ONLINE       0     0     0
          raidz2-0                                    ONLINE       0     0     0
            ata-SAMSUNG_HD203WI_S1UYJ1CZ317581        ONLINE       0     0     0
            ata-SAMSUNG_HD203WI_S1UYJ1CZ317592        ONLINE       0     0     0
            ata-SAMSUNG_HD203WI_S1UYJ1LZ202646        ONLINE       0     0     0
            ata-SAMSUNG_HD203WI_S1UYJ1LZ202647        ONLINE       0     0     0
            ata-SAMSUNG_HD203WI_S1UYJX0B900055        ONLINE       0     0     0
            ata-WDC_WD20EVDS-63T3B0_WD-WCAVY6715008   ONLINE       0     0     0
          raidz2-1                                    ONLINE       0     0     0
            ata-ST3000DM001-1CH166_W1F299TA           ONLINE       0     0     0
            ata-ST3000DM001-1CH166_W1F29PE7           ONLINE       0     0     0
            ata-WDC_WD30EFRX-68EUZN0_WD-WMC4N1413498  ONLINE       0     0     0
            ata-ST3000DM001-1CH166_Z1F2LWDL           ONLINE       0     0     0
            ata-ST3000DM001-1CH166_Z1F2PL9K           ONLINE       0     0     0
            ata-ST3000DM001-9YN166_W1F0SQF6           ONLINE       0     0     0
```

Smartctl for offending HDD (after scrub):

```
ID# ATTRIBUTE_NAME          FLAG     VALUE WORST THRESH TYPE      UPDATED  WHEN_FAILED RAW_VALUE
  1 Raw_Read_Error_Rate     0x000f   117   096   006    Pre-fail  Always       -       137351448
  3 Spin_Up_Time            0x0003   095   094   000    Pre-fail  Always       -       0
  4 Start_Stop_Count        0x0032   100   100   020    Old_age   Always       -       154
  5 Reallocated_Sector_Ct   0x0033   100   100   010    Pre-fail  Always       -       0
  7 Seek_Error_Rate         0x000f   064   058   030    Pre-fail  Always       -       12892732713
  9 Power_On_Hours          0x0032   091   091   000    Old_age   Always       -       8447
 10 Spin_Retry_Count        0x0013   100   100   097    Pre-fail  Always       -       0
 12 Power_Cycle_Count       0x0032   100   100   020    Old_age   Always       -       150
183 Runtime_Bad_Block       0x0032   099   099   000    Old_age   Always       -       1
184 End-to-End_Error        0x0032   100   100   099    Old_age   Always       -       0
187 Reported_Uncorrect      0x0032   012   012   000    Old_age   Always       -       88
188 Command_Timeout         0x0032   100   100   000    Old_age   Always       -       0
189 High_Fly_Writes         0x003a   097   097   000    Old_age   Always       -       3
190 Airflow_Temperature_Cel 0x0022   068   053   045    Old_age   Always       -       32 (Min/Max 29/35)
191 G-Sense_Error_Rate      0x0032   100   100   000    Old_age   Always       -       0
192 Power-Off_Retract_Count 0x0032   100   100   000    Old_age   Always       -       139
193 Load_Cycle_Count        0x0032   083   083   000    Old_age   Always       -       34992
194 Temperature_Celsius     0x0022   032   047   000    Old_age   Always       -       32 (0 22 0 0)
197 Current_Pending_Sector  0x0012   100   097   000    Old_age   Always       -       0
198 Offline_Uncorrectable   0x0010   100   097   000    Old_age   Offline      -       0
199 UDMA_CRC_Error_Count    0x003e   200   200   000    Old_age   Always       -       0
240 Head_Flying_Hours       0x0000   100   253   000    Old_age   Offline      -       248816045398690
241 Total_LBAs_Written      0x0000   100   253   000    Old_age   Offline      -       8184768984
242 Total_LBAs_Read         0x0000   100   253   000    Old_age   Offline      -       64804709912
```

Example SMART error (there were 10 of these before the scrub, and 88 after):

```
Error 88 occurred at disk power-on lifetime: 8441 hours (351 days + 17 hours)
  When the command that caused the error occurred, the device was active or idle.

  After command completion occurred, registers were:
  ER ST SC SN CL CH DH
  -- -- -- -- -- -- --
  40 51 00 ff ff ff 0f  Error: UNC at LBA = 0x0fffffff = 268435455

  Commands leading to the command that caused the error were:
  CR FR SC SN CL CH DH DC   Powered_Up_Time  Command/Feature_Name
  -- -- -- -- -- -- -- --  ----------------  --------------------
  60 00 28 ff ff ff 4f 00      22:24:37.633  READ FPDMA QUEUED
  60 00 08 ff ff ff 4f 00      22:24:37.633  READ FPDMA QUEUED
  60 00 08 ff ff ff 4f 00      22:24:37.632  READ FPDMA QUEUED
  60 00 00 ff ff ff 4f 00      22:24:37.632  READ FPDMA QUEUED
  60 00 00 ff ff ff 4f 00      22:24:37.631  READ FPDMA QUEUED
```

Example dmesg (there were 78 of these entries made during the scrub):

```
[80481.214023] sd 8:0:0:0: [sdn]
[80481.214027] Add. Sense: Unrecovered read error - auto reallocate failed
[80481.214031] sd 8:0:0:0: [sdn] CDB:
[80481.214033] Read(16): 88 00 00 00 00 00 d1 18 99 38 00 00 01 00 00 00
[80481.214051] end_request: I/O error, dev sdn, sector 3508050376
[80481.214124] ata8: EH complete
[80484.297229] ata8.00: exception Emask 0x0 SAct 0x3ed SErr 0x0 action 0x0
[80484.297275] ata8.00: irq_stat 0x40000008
[80484.297308] ata8.00: failed command: READ FPDMA QUEUED
[80484.297345] ata8.00: cmd 60/00:48:40:a4:18/01:00:d1:00:00/40 tag 9 ncq 131072 in
[80484.297345]          res 41/40:00:d0:a4:18/00:01:d1:00:00/00 Emask 0x409 (media error) <F>
[80484.297461] ata8.00: status: { DRDY ERR }
[80484.297494] ata8.00: error: { UNC }
[80484.298746] ata8.00: configured for UDMA/133
[80484.298761] sd 8:0:0:0: [sdn] Unhandled sense code
[80484.298762] sd 8:0:0:0: [sdn]
[80484.298763] Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
[80484.298764] sd 8:0:0:0: [sdn]
[80484.298765] Sense Key : Medium Error [current] [descriptor]
[80484.298766] Descriptor sense data with sense descriptors (in hex):
[80484.298767]         72 03 11 04 00 00 00 0c 00 0a 80 00 00 00 00 00
[80484.298771]         d1 18 a4 d0
```

Obviously this disk is probably dead soon, the  Reported_Uncorrect is down to 12 from 100, when it hits 0 it will trip SMART and I can RMA it.

The main thing that just concerned me is how can ZFS repair stuff but not report a read/write/cksum error.  Is this possible or intentional or correct ZFS behavior?  Or is it a bug?

I DO have ECC RAM and I see no ECC events reported in my kernel log nor in my motherboard's IPMI interface log.

**Comment by devZer0** [comment] 2016-10-13 16:02
i also stumbled over this. zpool status tells it had repaired data, but no read/write or chksum errors. i see errors at kernel dmesg, though. 

i`m really curious how zfs can repair something and then not be able to tell _what_ has been repaired. 

let`s me loose trust into it - ther deeper i read into is , the more i get unsure if zfs is really "self healing" when such basic things do not work as expected or are utterly complicated or badly documented.

/code

  pool: zfspool
 state: ONLINE
  scan: scrub in progress since Thu Oct 13 14:21:55 2016
    1,61T scanned out of 2,80T at 129M/s, 2h41m to go
    282K repaired, 57,57% done
config:

       	NAME        STATE     READ WRITE CKSUM
       	zfspool     ONLINE       0     0     0
       	  raidz1-0  ONLINE       0     0     0
       	    xvdb1   ONLINE       0     0     0
       	    xvdc1   ONLINE       0     0     0
       	    xvdd1   ONLINE       0     0     0  (repairing)
       	    xvde1   ONLINE       0     0     0

errors: No known data errors

**Comment by richardelling** [comment] 2016-10-13 17:01
> On Oct 13, 2016, at 9:02 AM, devZer0 <notifications@github.com> wrote:
> 
> i also stumbled over this. zpool status tells it had repaired data, but no read/write or chksum errors. i see errors at kernel dmesg, though.
> 
> i`m really curious how zfs can repair something and then not be able to tell what has been repaired.
> 
try
zpool events
 — richard

**Comment by devZer0** [comment] 2016-10-14 09:16
yes, i can see appropriate event:

  eid: 11
class: io
 host: backupvm1
 time: 2016-10-13 16:18:27+0200
vtype: disk
vpath: /dev/xvdd1
vguid: 0x6C46792B4B135931
cksum: 0
 read: 0
write: 0
 pool: zfspool

here is some more detail: 
http://sprunge.us/deGi

but i don`t understand why cksum/read/write is "0" in that events - what error makes zfs scrub repair data when it`s not a read/write or chksum error ?

**Comment by richardelling** [comment] 2016-10-14 17:02
The disk is part of a raidz vdev, so its EIO (zio_err = 0x5) can be repaired by resilvering.

The disk is also not a real disk (xv instead of sd), so there are more opportunities where it can fail than an actual drive. The dmesg error comes from blk_update_request() which is part of a request stacking driver interface, outside of zfs.

**Comment by Lennie** [comment] 2017-03-29 08:51
It could be that after multiple tries by the Linux kernel (only logging the error), a read eventually succeeded. Returning the correct data to ZFS.

**Comment by behlendorf** [comment] 2018-10-12 21:46
Marking as a duplicate of #4851.

**Closed by behlendorf** 2018-10-12 21:46 UTC
