### ISSUE TITLE
Request for recursively mount

### ISSUE THREAD

**Issue by setaur** [zfsonlinux/zfs#9635] opened 2019-11-27 00:19 UTC
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Debian
Distribution Version	| Buster
Linux Kernel	| 4.19.0-6-amd64
Architecture	| x86_64
ZFS Version	| 0.8.2-2~bpo10+1
SPL Version	| 0.8.2-2~bpo10+1

### Describe the problem you're observing
After introducing encryption to ZoL, there is a lack of an option for recursively mount datasets. 

I.e. I have dataset with keyformat=passphrase and canmount=noauto. This dataset has children encrypted datasets. To decrypt and mount them I have to build a bit too complicated script, when just a simple '-r' option similar to 'zfs load-key -r' would suffice. 

zfs mount -a won't work with canmount=noauto.

**Comment by behlendorf** [comment] 2019-12-05 01:33
Related to #9649.

**Comment by rlaager** [comment] 2019-12-14 22:56
Duplicate of #2901

**Closed by rlaager** 2019-12-14 22:56 UTC
Labels: Component: Encryption
