### ISSUE TITLE
(from spl/issues/389) -- SPLError: 26788:0:(range_tree.c:172:range_tree_add()) SPL PANIC

### ISSUE THREAD

**Issue by TioNisla** [zfsonlinux/zfs#2720] opened 2014-09-19 03:44 UTC
"rsync -PSAXrltgoD --del" from remote host caused 'SPLError'

full text here: https://gist.github.com/anonymous/39e252399acb6912a16e

P.S.
After removal of storage/samba filesystem, when importing a pool there is this problem, it isn't possible to export or remove a pool: all zfs/zpool related commands just hangs.

**Comment by behlendorf** [comment] 2015-02-14 00:10
A patch for ignoring bad DVAs on blocks which are being freed when zfs_recover=1 is set has been merged.  This doesn't get to the root cause of _how_ this could happen but it does provide as more convenient way to recover which has been damaged in this way.

**Closed by behlendorf** 2015-02-14 00:10 UTC
Labels: Bug - Minor, Difficulty - Medium
