### ISSUE TITLE
0.6.3 on debian jessie linux : under heave parallel IO locks up in a session/terminal 

### ISSUE THREAD

**Issue by yarikoptic** [zfsonlinux/zfs#2983] opened 2014-12-20 05:22 UTC
upon heavy parallel load (12 processes doing similar thing, scheduled via condor) entire terminal locs up, either it is a ls -R running on a zfs volume, or a screen ($HOME is on zfs) with top and zfs iostat 1 in two windows.  kern.log carries messages (full avail on http://pastebin.com/hgrfyv3Q):

```
Dec 20 00:03:09 smaug kernel: [111731.457312] INFO: task kswapd0:101 blocked for more than 120 seconds.
Dec 20 00:03:09 smaug kernel: [111731.457317]       Tainted: P         CIO  3.16.0-4-amd64 #1
Dec 20 00:03:09 smaug kernel: [111731.457319] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Dec 20 00:03:09 smaug kernel: [111731.457322] kswapd0         D ffff8810788a9038     0   101      2 0x00000000
Dec 20 00:03:09 smaug kernel: [111731.457329]  ffff8810788a8be0 0000000000000046 0000000000013280 ffff88103e4d3fd8
Dec 20 00:03:09 smaug kernel: [111731.457333]  0000000000013280 ffff8810788a8be0 ffff88103cc29b30 ffff88103cc299f8
Dec 20 00:03:09 smaug kernel: [111731.457337]  ffff88103cc29b38 0000000000000000 0000000000000002 000065994bf07005
Dec 20 00:03:09 smaug kernel: [111731.457341] Call Trace:
Dec 20 00:03:09 smaug kernel: [111731.457368]  [<ffffffffa049cfe5>] ? cv_wait_common+0x105/0x1a0 [spl]
Dec 20 00:03:09 smaug kernel: [111731.457377]  [<ffffffff810a5940>] ? prepare_to_wait_event+0xf0/0xf0
Dec 20 00:03:09 smaug kernel: [111731.457410]  [<ffffffffa0667413>] ? txg_wait_open+0x83/0x100 [zfs]
Dec 20 00:03:09 smaug kernel: [111731.457434]  [<ffffffffa062ca7b>] ? dmu_tx_wait+0x28b/0x290 [zfs]
Dec 20 00:03:09 smaug kernel: [111731.457445]  [<ffffffff8150bace>] ? mutex_lock+0xe/0x2a
Dec 20 00:03:09 smaug kernel: [111731.457468]  [<ffffffffa062cb0d>] ? dmu_tx_assign+0x8d/0x450 [zfs]
Dec 20 00:03:09 smaug kernel: [111731.457489]  [<ffffffffa069e61a>] ? zfs_inactive+0x15a/0x1e0 [zfs]
Dec 20 00:03:09 smaug kernel: [111731.457499]  [<ffffffff811bf58c>] ? evict+0xac/0x170
Dec 20 00:03:09 smaug kernel: [111731.457504]  [<ffffffff811bf689>] ? dispose_list+0x39/0x50
Dec 20 00:03:09 smaug kernel: [111731.457510]  [<ffffffff811c04c4>] ? prune_icache_sb+0x44/0x50
Dec 20 00:03:09 smaug kernel: [111731.457514]  [<ffffffff811a8e5f>] ? super_cache_scan+0xff/0x170
Dec 20 00:03:09 smaug kernel: [111731.457520]  [<ffffffff8114ab27>] ? shrink_slab_node+0x127/0x290
Dec 20 00:03:09 smaug kernel: [111731.457525]  [<ffffffff8114c54b>] ? shrink_slab+0x11b/0x150
Dec 20 00:03:09 smaug kernel: [111731.457530]  [<ffffffff8114fc9e>] ? balance_pgdat+0x3be/0x5c0
Dec 20 00:03:09 smaug kernel: [111731.457534]  [<ffffffff8114ffff>] ? kswapd+0x15f/0x400
Dec 20 00:03:09 smaug kernel: [111731.457538]  [<ffffffff810a5940>] ? prepare_to_wait_event+0xf0/0xf0
Dec 20 00:03:09 smaug kernel: [111731.457543]  [<ffffffff8114fea0>] ? balance_pgdat+0x5c0/0x5c0
Dec 20 00:03:09 smaug kernel: [111731.457548]  [<ffffffff81085f1d>] ? kthread+0xbd/0xe0
Dec 20 00:03:09 smaug kernel: [111731.457553]  [<ffffffff81085e60>] ? kthread_create_on_node+0x180/0x180
Dec 20 00:03:09 smaug kernel: [111731.457557]  [<ffffffff8150d27c>] ? ret_from_fork+0x7c/0xb0
Dec 20 00:03:09 smaug kernel: [111731.457561]  [<ffffffff81085e60>] ? kthread_create_on_node+0x180/0x180
```
I googled up quit a it of similar lock up issues but traces were a bit different, so decided to report/check if issue is known and remedy is ready in devel

**Comment by yarikoptic** [comment] 2015-02-25 15:09
Ok -- this issue strikes back heavily ;)  I think it was the same a week ago as well.  Here are details about current state of affairs:  http://www.onerussian.com/tmp/zfs_report_20150225/

I am running dailies with tiny tune  https://github.com/DeHackEd/zfs/commit/0647ab34defc84c3213e2ad6198017288e3b72d4

System went bzirk again while tar'ing a directory with LOTS of tiny files (can't tell how many ATM since it is stuck).  ATM load is around 50 (and rising) because all cron'ed snapshot commands are stuck too.
I would prefer not to reboot so to be able to help troubleshoot since getting in this state is a lengthy process.

**Comment by yarikoptic** [comment] 2015-02-25 15:44
as ryao at IRC points out, apparently this kernel was running without frame pointers enabled (got upgraded :-/) but here is report from last stall I believe:  http://www.onerussian.com/tmp/zfs_report_20150218/

**Comment by behlendorf** [comment] 2015-02-27 05:50
This should be addressed by #3132 which is going through testing and review right now.  This is one of a small handful of things blocking the next tag.

**Comment by yarikoptic** [comment] 2015-02-28 00:27
Thanks @behlendorf : simply by #3132 (either I am tired or anyways I don't know zfs codebase, but it doesn't make sense to me why it should have any effect) or in conjunction with https://github.com/zfsonlinux/spl/pull/435 ?

**Comment by behlendorf** [comment] 2015-02-28 00:43
@yarikoptic it's caused by a subtle deadlock in the direct memory reclaim path for ZFS.  Basically it's possible for us to enter direct reclaim while holding one of the hashed mutexes for the ARC.  During this reclaim it's then possible that we'll re-enter the VFS and attempt to take the lock again while trying to free a different object which happens to hash to the same value.  It  would be great if you could give the latest patches a try and verify they resolve your issue.

**Comment by yarikoptic** [comment] 2015-02-28 00:48
could you list any other patch I should add besides those two?

P.S. I just begged for a bit of tutoring at https://github.com/zfsonlinux/zfs/pull/3132/files#r25550686  ;-)

**Comment by yarikoptic** [comment] 2015-02-28 23:18
Dear @behlendorf   please let me know which set of patches should I try since I doubt #3132 alone would be sufficient...

**Closed** 2015-03-03 21:18 UTC
Labels: Bug - Major, Difficulty - Medium, Memory Management
