### ISSUE TITLE
zfs replace with invalid disk hangs sync()

### ISSUE THREAD

**Issue by wsldankers** [zfsonlinux/zfs#2054] opened 2014-01-16 10:18 UTC
Hi,

When replacing a failing disk I accidentally fed `zpool replace` an unpartitioned disk. It detected this properly, and refused to act.

However, when applying a GPT label to the disk, `gdisk` hung when (I assume) it called `sync()`.

Calling `/bin/sync` in a seperate window hung too. I had to reboot the system (and not in the most elegant way) to get things to working normally again. After the reboot (and with a partition table) the `zpool replace` was successful. The drive is currently resilvering.

OS: Ubuntu 12.04 amd64 with unmodified Ubuntu kernel
```
Linux homsar 3.2.0-58-generic #88-Ubuntu SMP Tue Dec 3 17:37:58 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
```
```
||/ Name             Version          Description
+++-================-================-================================================
ii  spl-dkms         0.6.2-1~precise  Solaris Porting Layer kernel modules for Linux
ii  zfs-dkms         0.6.2-1~precise  Native ZFS filesystem kernel modules for Linux
```

Transcript:

```
root@homsar:~# zpool replace zut wwn-0x5000cca369c8ea02 wwn-0x50014ee209a39e3e
invalid vdev specification
use '-f' to override the following errors:
/dev/disk/by-id/wwn-0x50014ee209a39e3e does not contain an EFI label but it may contain partition
information in the MBR.
root@homsar:~# gdisk /dev/sdg
GPT fdisk (gdisk) version 0.8.1

Partition table scan:
  MBR: not present
  BSD: not present
  APM: not present
  GPT: not present

Creating new GPT entries.

Command (? for help): w

Final checks complete. About to write GPT data. THIS WILL OVERWRITE EXISTING
PARTITIONS!!

Do you want to proceed? (Y/N): Y
OK; writing new GUID partition table (GPT).
```
(hangs)

`gdisk` (and `/bin/sync`) show as `D` processes in `ps` output.

`zpool status` (after succesful replace):
```
  pool: zut
 state: ONLINE
status: One or more devices is currently being resilvered.  The pool will
	continue to function, possibly in a degraded state.
action: Wait for the resilver to complete.
  scan: resilver in progress since Thu Jan 16 10:47:05 2014
    38,7G scanned out of 6,38T at 25,8M/s, 71h28m to go
    6,45G resilvered, 0,59% done
config:

	NAME                            STATE     READ WRITE CKSUM
	zut                             ONLINE       0     0     0
	  raidz1-0                      ONLINE       0     0     0
	    wwn-0x5000cca369c8d323      ONLINE       0     0     0
	    wwn-0x5000cca369c8a267      ONLINE       0     0     0
	    wwn-0x5000cca369c86a12      ONLINE       0     0     0
	    replacing-3                 ONLINE       0     0     0
	      wwn-0x5000cca369c8ea02    ONLINE       0     0     0
	      wwn-0x50014ee209a39e3e    ONLINE       0     0     0  (resilvering)
	    wwn-0x5000cca369ce1a28      ONLINE       0     0     0
	logs
	  wwn-0x5002538043584d30-part2  ONLINE       0     0     0
	cache
	  wwn-0x5002538043584d30-part3  ONLINE       0     0     0

errors: No known data errors
```

Perhaps there's a mutex not being unlocked somewhere in the error path?

**Comment by behlendorf** [comment] 2016-07-16 00:15
Closing, I can't reproduce this issue.

**Closed by behlendorf** 2016-07-16 00:15 UTC
Labels: Bug - Minor, Difficulty - Medium
