### ISSUE TITLE
ZFS deadlock under IO load with the latest development version

### ISSUE THREAD

**Issue by siebenmann** [zfsonlinux/zfs#3050] opened 2015-01-28 22:51 UTC
I have twice had my desktop workstation stop handling ZFS IO while tar-based system backups were running. During a deadlock, all ZFS IO stops working to at least my primary ZFS pool (which has a mirrored vdev plus a L2ARC), while IO to the ext4 root filesystem continues essentially unaffected. By the time I've inspected the system it doesn't appear to be short of memory, but in general the backups clearly would have put pressure on the ARC memory use and so on.

The machine is x86_64 Fedora 21 with 32 GB of RAM. Lockups have happened on kernels 3.17.8-300.fc21 and 3.18.3-201.fc21. Boot time SPL and ZFS version strings are:

    SPL: Loaded module v0.6.3-69_g54cccfc
    ZFS: Loaded module v0.6.3-181_gb0cf067, ZFS pool version 5000, ZFS filesystem version 5

An older ZFS/SPL version ran for weeks+ without this problem on the same system, backup environment, and so on.

I captured as full a dump as possible of all SysRq output, including 'Show Blocked State' and 'Show State' stack dumps for blocked/all processes. I've put it on the web [here](http://www.cs.toronto.edu/~cks/tmp/zol/sysrq-2015-01-26.txt).

This has been discussed on zfs-discuss, where Richard Yao used the stack backtraces to identify a potential L2ARC locking issue with the latest changes. His message about that is [here](https://groups.google.com/a/zfsonlinux.org/d/msg/zfs-discuss/4KgPvkvCT4Q/9-b58oE6YNsJ). My zfs-discuss message with 'zpool status' pool configuration output and more details is [here](https://groups.google.com/a/zfsonlinux.org/d/msg/zfs-discuss/4KgPvkvCT4Q/FPlT82n-Wz4J). I'm happy to make available whatever further details I have (or can gather).

**Comment by ryao** [comment] 2015-01-29 17:22
This deadlock could occur whenever direct reclaim occurs when we are holding an ARC hash lock. In this case, L2ARC was the lucky (unlucky?) one to be doing that. I believe ryao/zfs@916e29afddc94dd0fc152db3d473adfbea1d4c45 should resolve this, but it needs testing.

**Comment by behlendorf** [comment] 2015-01-29 22:36
@siebenmann Thank you for running the master branch and filing this.  This is exactly the sort of thing I was concerned about accidentally introducing with the kmem-rework patches.  By design they enable many more places where direct reclaim can occur which is good for latency and performance.  But these new direct reclaim locations _can_ also introduce new deadlocks which we not possible before.

The good news here is that we just need to identity these cases and flag them appropriately in the code.  @ryao's definitely on the right track with his initial patch.  It's just going to need review and testing.


  And it's unfortunately the kind of thing which can sneak through our testing.

**Comment by siebenmann** [comment] 2015-01-29 22:50
I've now updated to the latest development tip patched with @ryao 's change and I'm going to do my best to put IO load on my machine to maximize the chance of hitting any remaining deadlocks. If I get any more lockups I'll let people know and provide stack traces and so on.

**Comment by behlendorf** [comment] 2015-02-05 22:01
@ryao I like you're approach here and I think we should go a little father.  My suggestion would be to add an additional `ASSERT(spl_fstrans_check())` every place where there is an existing `ASSERT(MUTEX_HELD(hash_lock))`.  We can never allow direct reclaim to occur while we're holding the hash lock or we risk this deadlock (or one like it).

Could you open a pull request with your proposed change and the additional ASSERTs.

**Comment by behlendorf** [comment] 2015-02-05 22:05
I should mention the exact same solution can be applied to the dbuf hash  to resolve #3055.

**Comment by ryao** [comment] 2015-02-05 23:24
@behlendorf I like your suggestion. I will do that later today after I get back from an appointment.

**Comment by behlendorf** [comment] 2015-02-11 20:44
@ryao do you time to open a pull request for this?  If not, I'll make some time to work on this since it's a blockers for the next tag.

**Comment by devsk** [comment] 2015-02-11 20:48
I would like to test out master on my setup once this bug is closed.

**Comment by devsk** [comment] 2015-02-20 17:00
Sorry for being a pest, but any updates on this bug? I thought the problem was well understood and a partial fix had already seen one round of review.

**Comment by siebenmann** [comment] 2015-02-20 17:34
For what it's worth, I haven't experienced another lockup with ZoL git tip since manually patching in @ryao 's change above.

**Comment by ryao** [comment] 2015-02-20 17:47
@devsk, @behlendorf, @siebenmann Sorry for the delay. I have been busy with stuff at work and some private non-work related matters. This is on my to do list for the weekend.

**Comment by behlendorf** [comment] 2015-02-27 21:59
@siebenmann @devsk could you please test and verify the refreshed fix for this.  I've run it though extensive internal testing and it's held up very well. You'll need the patches from the following two pull requests.  @ryao can you please comment on this alternate approach.

zfsonlinux/spl#435
zfsonlinux/zfs#3132

**Comment by devsk** [comment] 2015-03-02 06:55
Brian: if the change passed your internal testing, please push to master. I would like to see it as part of master. I feel guilty about it but the truth is that I have very little time to tinker with patches and all. I would just like to emerge, get the latest from git master and run with it. That way its also easy to roll it back if needed.

Is that possible? If not, I will try to get some time over the coming weekend.

**Comment by siebenmann** [comment] 2015-03-02 07:03
@behlendorf, I apologize for being Github impaired: what's the best way to get the patches from those pull requests in the best way for testing? Use the .patch version of the pull urls? Some git pull/fetch incantation? I'd like to make sure I test the best way possible for this.

**Comment by kernelOfTruth** [comment] 2015-03-02 14:18
@siebenmann add the suffix .diff

that makes e.g. https://github.com/zfsonlinux/zfs/pull/2129.diff
out of https://github.com/zfsonlinux/zfs/pull/2129

at least that's what I've been told to do in the past and/or read

**Comment by behlendorf** [comment] 2015-03-02 19:22
@devsk @siebenmann No problem, I just wanted to give you guys a heads up there were patches available for this.  Your help verifying proposed changes is always appreciated, but I absolutely wouldn't be making those patches available unless I already felt they were ready for a wider audience.  These changes should be merged to master this week.

**Comment by siebenmann** [comment] 2015-03-02 19:25
I'm now running both PRs and I'm going to try to put as much stress on my machine as possible. I'll report back if anything explodes.

**Closed** 2015-03-03 21:18 UTC
Labels: Bug - Major, Difficulty - Medium, Memory Management

**Comment by devsk** [comment] 2015-03-04 06:56
I am running the master with 3.18.8. Will let you know if I run into any issues.

**Comment by behlendorf** [comment] 2015-03-04 19:39
@devsk @siebenmann Thank you!  The additional real world (ab)use of the code is appreciated!
