### ISSUE TITLE
my 32 zfs can't use disk big than 2t 

### ISSUE THREAD

**Issue by lihui2090** [zfsonlinux/zfs#4014] opened 2015-11-16 03:29 UTC
how can i make it sector size  become 4096 
now the sector is 512

**Comment by kernelOfTruth** [comment] 2015-11-16 03:36
```
zpool create -o ashift=12 foo /dev/bar
```

there might be a limitation with 32bit and maximum size though ...

**Comment by lihui2090** [comment] 2015-11-16 03:54
@kernelOfTruth 
ths first ,
i find  i use this cmd ,the "zpool list" show the disk can use 2t of 4t .

**Comment by lihui2090** [comment] 2015-11-20 12:21
I have check the scsi may be the reason.
I  install standard debain 7.8 32system in vmware ,and compile the  zfs 0.6.4.2, 
zfs can use disk biger than 2T. 
So the reason is my 32 kernel not support the scsi normal. the kernel has many scsi configs not set. 
The only thing make me confuse  is the same kernel compiled to 64 can surpport disk biger than 2T.
I use the real hard disk  4t.

**Comment by behlendorf** [comment] 2016-10-28 18:58
Closing.  The root cause appears to have been identified in the previous comment.

**Closed by behlendorf** 2016-10-28 18:58 UTC
Labels: Architecture Specific
