### ISSUE TITLE
arc_adapt makes cpu load go 150+

### ISSUE THREAD

**Issue by ki82** [zfsonlinux/zfs#3697] opened 2015-08-20 07:00 UTC
We have a server which cpu load spins up to above 150 during around 5-10 and then goes back to normal load around 3. When this happen we can se that there is alot of arc processing so we think that it is related. It most often happen after/during we have rsynced the entire content of the zfs dataset to another server. It could also be related to when we destroy zfs snapshot using zfs-auto-snapshot.

zfs version:0.6.4.2-1~trusty
ubuntu version:14.04.3 LTS
memory: 132 GB DDR3 ECC
server:  Dual Xeon E5-2643 v3 3.4GHZ
zfs data storage: 8 Samsung 845DC 400GB SSD in RAID 10
zfs data free storage: 587 GB (of total 1.6TB)

perf top -ag (while this was happening)
![arc_adapt](https://cloud.githubusercontent.com/assets/1379367/9377488/d12938d0-4719-11e5-9584-aaada1581365.png)

**Arcsettings(just afterwards)**
cat /proc/spl/kstat/zfs/arcstats
5 1 0x01 86 4128 5333215409 250560075874342
name                            type data
hits                            4    916903834
misses                          4    87087801
demand_data_hits                4    542460100
demand_data_misses              4    10843762
demand_metadata_hits            4    323642250
demand_metadata_misses          4    67990631
prefetch_data_hits              4    11131241
prefetch_data_misses            4    6753591
prefetch_metadata_hits          4    39670243
prefetch_metadata_misses        4    1499817
mru_hits                        4    85687932
mru_ghost_hits                  4    17411207
mfu_hits                        4    788577680
mfu_ghost_hits                  4    12827670
deleted                         4    11670382
recycle_miss                    4    7246668
mutex_miss                      4    11763
evict_skip                      4    1084024142
evict_l2_cached                 4    0
evict_l2_eligible               4    1362255604224
evict_l2_ineligible             4    10685313024
hash_elements                   4    4091926
hash_elements_max               4    4687975
hash_collisions                 4    22307817
hash_chains                     4    424399
hash_chain_max                  4    7
p                               4    3142683648
c                               4    43896062168
c_min                           4    4194304
c_max                           4    67478827008
size                            4    43895448432
hdr_size                        4    1419195744
data_size                       4    3653412352
meta_size                       4    14594271232
other_size                      4    24228569104
anon_size                       4    13606400
anon_evict_data                 4    0
anon_evict_metadata             4    0
mru_size                        4    7492215808
mru_evict_data                  4    659800064
mru_evict_metadata              4    347753472
mru_ghost_size                  4    33408803840
mru_ghost_evict_data            4    21720174592
mru_ghost_evict_metadata        4    11688629248
mfu_size                        4    10741861376
mfu_evict_data                  4    2992998400
mfu_evict_metadata              4    4467471360
mfu_ghost_size                  4    6373681664
mfu_ghost_evict_data            4    0
mfu_ghost_evict_metadata        4    6373681664
l2_hits                         4    0
l2_misses                       4    0
l2_feeds                        4    0
l2_rw_clash                     4    0
l2_read_bytes                   4    0
l2_write_bytes                  4    0
l2_writes_sent                  4    0
l2_writes_done                  4    0
l2_writes_error                 4    0
l2_writes_hdr_miss              4    0
l2_evict_lock_retry             4    0
l2_evict_reading                4    0
l2_free_on_write                4    0
l2_cdata_free_on_write          4    0
l2_abort_lowmem                 4    0
l2_cksum_bad                    4    0
l2_io_error                     4    0
l2_size                         4    0
l2_asize                        4    0
l2_hdr_size                     4    0
l2_compress_successes           4    0
l2_compress_zeros               4    0
l2_compress_failures            4    0
memory_throttle_count           4    0
duplicate_buffers               4    0
duplicate_buffers_size          4    0
duplicate_reads                 4    142
memory_direct_count             4    678348
memory_indirect_count           4    280951
arc_no_grow                     4    0
arc_tempreserve                 4    0
arc_loaned_bytes                4    0
arc_prune                       4    21
arc_meta_used                   4    40242036080
arc_meta_limit                  4    50609120256
arc_meta_max                    4    50612815216

**zdb -DD data**
![datadd](https://cloud.githubusercontent.com/assets/1379367/9377559/84791176-471a-11e5-921f-6b5214b49a36.png)

Overall memory usage:
KiB Mem:  13179458+total, 96213936 used, 35580644 free,    37932 buffers

**Comment by ki82** [comment] 2015-08-20 07:06
Let me know if there is any other information that you need.

**Comment by ki82** [comment] 2015-08-20 07:11
Adding sponsoring of 200$ here for this issue: https://freedomsponsors.org/issue/733/arc_adapt-makes-cpu-load-go-150

**Comment by ki82** [comment] 2015-08-20 08:27
Now it happen again:
load average: **404.80, 237.41, 124.09**

**Comment by behlendorf** [comment] 2015-08-24 16:44
@ki82 it definitely looks like contention in the virtual memory subsystem caused by the arc attempting to reclaim memory.  Significant work has already been done in this area and will appear in the 0.6.5 tag.  Additional work to remove this contention point is in pull request #3441 and will be merged after the 0.6.5 tag.  As for a quick fix you could try restricting the maximum ARC size (zfs_arc_max) to leave more free memory on the system.

**Comment by ki82** [comment] 2015-08-25 07:52
@behlendorf Ok, I will try out 0.6.5 and later releases as soon as they are released and report back.
Could you recommend a good value for zfs_arc_max that would work as a quick-fix?

**Comment by alexanderhaensch** [comment] 2015-09-01 12:24
@ki82 if you still having this problem, i think you problem could be related to #3376 . 
In our case this workaround https://github.com/zfsonlinux/zfs/issues/3376#issuecomment-99568712 helps.

**Comment by ki82** [comment] 2015-09-01 12:40
@alexanderhaensch Thanks for the tip, I would consider trying it out if there is no release with a solution soon.

**Comment by behlendorf** [comment] 2015-09-01 17:54
@ki82 setting `spl_kmem_cache_expire=0` may take the pressure off the VM subsystem in your case.  It will result in the ARC not as aggressively freeing memory back to the Linux slabs.  You can set this at run time as root and the option exists in both 0.6.4 and what will be 0.6.5.

```
echo 0 >/sys/module/spl/parameters/spl_kmem_cache_expire
```

**Comment by ki82** [comment] 2015-09-02 06:06
@behlendorf Thanks I have applied spl_kmem_cache_expire now and will report back how it works.
I hava also set zfs_arc_max to 20GB since your comment 8 days ago and we are still seeing high cpu spikes.

**Closed** 2019-02-16 02:24 UTC
Labels: Component: Memory Management
