### ISSUE TITLE
0.8 changelog missing lack of SIMD acceleration

### ISSUE THREAD

**Issue by ptx0** [zfsonlinux/zfs#8804] opened 2019-05-23 17:32 UTC
Major performance loss is not documented in the 0.8 changelog, people should probably know that.

**Comment by behlendorf** [comment] 2019-05-23 17:42
This issue isn't specific 0.8 and thus it wasn't included in the release notes.  The 0.7 releases are also currently not able to take advantage of the SIMD acceleration on newer kernels.

Duplicate of #8793.

**Comment by ptx0** [comment] 2019-05-23 17:43
so there's no changelog for either then

**Closed by behlendorf** 2019-05-23 17:42 UTC

**Comment by ptx0** [comment] 2019-05-23 17:49
please reopen this and add to changelog.

**Comment by behlendorf** [comment] 2019-05-23 18:26
The release notes have been updated to mention SIMD is not currently supported for 5.0 and newer kernels.
