### ISSUE TITLE
zed: hang at processing events

### ISSUE THREAD

**Issue by iggi-** [zfsonlinux/zfs#3037] opened 2015-01-24 17:46 UTC
I am using Ubuntu 14.04 with the provided PPAs. I also copied the /etc/zfs/zed.d/ contents from the current master (the scripts only) as stated in https://github.com/zfsonlinux/pkg-zfs/issues/137

Now however, when I start zed I get:

```
# zed -F
zed: ZFS Event Daemon 0.6.3-5~trusty
zed: Processing events since eid=30
```

It simply sits there, at least for the past 2 hours it has.

Relevant info:

CPUs:           1 (E5-2609 v2)
Memory:         32GB
VM/Hypervisor:      no
ECC mem:        Yes
Distribution:       Ubuntu 14.04
Kernel version:     Linux nas4 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
SPL/ZFS source:     Ubuntu 14.04 PPA
SPL/ZFS version:    [   19.682382] SPL: Loaded module v0.6.3-3~trusty
[   19.985373] ZFS: Loaded module v0.6.3-5~trusty, ZFS pool version 5000, ZFS filesystem version 5
[   51.876137] SPL: using hostid 0x007f0101
System services:    Backup Server (not in production
Short  description: zed hangs on startup

**Comment by dun** [comment] 2015-01-31 03:48
Are you sure it's hung? The '-F' option runs the daemon in the foreground. It'll be rather quiet without the '-v' (verbose) option. What's the output when starting via 'zed -F -v'?

Are events being processed? Does 'zpool events -v' report any events that aren't in the syslog?

**Comment by behlendorf** [comment] 2016-11-15 05:46
Closing, may be a duplicate of #4720.

**Closed by behlendorf** 2016-11-15 05:46 UTC
Labels: zed
