### ISSUE TITLE
zdb crash

### ISSUE THREAD

**Issue by RubenKelevra** [zfsonlinux/zfs#4262] opened 2016-01-23 12:49 UTC
[root@maschine ~]# zdb -DD tanka
zdb: kernel.c:182: Assertion `pthread_create(&kt->t_tid, &attr, &zk_thread_helper, kt) == 0 (0xb == 0x0)' failed.
Abgebrochen (Speicherabzug geschrieben)

The german text means "aborted (dump written)"

 # pacman -Qi linux | grep Version
Version              : 4.3.3-3

 # pacman -Qi zfs-git | grep Version
Version              : 0.6.5.4_r0_g1ffc4c1_4.3.3_3-1

**Comment by kernelOfTruth** [comment] 2016-01-23 19:01
so Arch Linux :+1: 

@RubenKelevra is that a 32bit system we're talking about ?

**Comment by RubenKelevra** [comment] 2016-01-23 19:20
Nope, 64 bit and the zfs-package is a binary one from http://demizerone.com/$repo/$arch

**Comment by behlendorf** [comment] 2016-01-23 23:29
The error here is 0xb = 11 = EGAIN.  From the `pthread_create(3)` man page.

```
       EAGAIN Insufficient resources to create another thread,  or  a  system-
              imposed  limit  on  the  number of threads was encountered.  The
              latter case  may  occur  in  two  ways:  the  RLIMIT_NPROC  soft
              resource  limit  (set via setrlimit(2)), which limits the number
              of process for a real user ID, was reached; or the kernel's sys‐
              tem-wide   limit   on  the  number  of  threads,  /proc/sys/ker‐
              nel/threads-max, was reached.
```

Any idea what the rlimit it set to you on your system?

**Comment by RubenKelevra** [comment] 2016-01-24 01:00
Actually not - just wanted to look at the deduplication debug output to find out how many dedupt sectors was found. :)

Everything else works great on that system. I do not remember to set any limits, and the system is fairly new. Is it possible to list the limits which apply to this process.

**Comment by loli10K** [comment] 2017-08-18 11:26
@RubenKelevra is this till an issue? This may (or may not) be related to https://github.com/zfsonlinux/zfs/issues/6329.

> Abgebrochen (Speicherabzug geschrieben)
> The german text means "aborted (dump written)"

Can you get a backtrace from the dump? Also `ulimit -a` or `cat /proc/$pid/limits`

**Comment by RubenKelevra** [comment] 2017-08-18 14:30
This ticket is 1 and a half year open, no I cannot providea dump anymore, since they are deleted after 90 days or so.

I cannot provide uname -a from that time either, since at this time a completely different kernel was running on that machine - arch does very regular updates.

**Comment by loli10K** [comment] 2017-08-18 14:35
Since we can no longer gather any meaningful information that would help debug the problem i'm closing this issue: we can reopen it when we have a reproducer.

**Closed by loli10K** 2017-08-18 14:35 UTC

**Comment by RubenKelevra** [comment] 2017-08-24 09:06
Thanks :)

**Comment by richardelling** [comment] 2017-08-28 00:33
For the archives, "zpool status -D" provides the information that "zdb -DD" presents and the zpool command is preferred over zdb when possible.
