### ISSUE TITLE
Even more hole_birth bug

### ISSUE THREAD

**Issue by rincebrain** [zfsonlinux/zfs#5030] opened 2016-08-27 03:45 UTC
So, after writing something to make it easy to test/reproduce hole_birth bugs, I tried a simplified version of the script in https://github.com/zfsonlinux/zfs/issues/4809#issuecomment-241246196 on latest git (0.6.5-419_g9907cc1), and found that in fact, it still works!

So I'm filing a new hole_birth bug for that, as it doesn't seem to be covered by #4809 or #4996.

Reproducer script:

dd if=/dev/zero of=/dev/shm/pool1 bs=1M count=1 seek=1024
dd if=/dev/zero of=/dev/shm/pool2 bs=1M count=1 seek=1024
zpool create pool1 /dev/shm/pool1
zpool create pool2 /dev/shm/pool2
zfs create pool1/fs1
dd if=/dev/urandom of=/pool1/fs1/file1 bs=4k count=11264 seek=1152
zfs snapshot pool1/fs1@snap1
truncate -s 4194304 /pool1/fs1/file1
dd if=/dev/urandom of=/pool1/fs1/file1 bs=4k count=152 seek=384 conv=notrunc
sleep 5
dd if=/dev/urandom of=/pool1/fs1/file1 bs=4k count=10 seek=1408 conv=notrunc
zfs snapshot pool1/fs1@snap2
zfs send pool1/fs1@snap1 | zfs recv pool2/fs1
zfs send -i pool1/fs1@snap{1,2} | zfs recv pool2/fs1
md5sum /pool{1,2}/fs1/file1

**Comment by loyou** [comment] 2016-08-27 04:07
This issue get different path to reproduce, but maybe same root cause.
It works fine after apply the patch in #5004 although **it is not the final patch**.

**Comment by rincebrain** [comment] 2016-08-27 04:11
If it turns out to be a dupe of #4996, all the better. I just noticed it wasn't #4809 when I had it listed as a test for 4809 and then it still worked on latest git.

**Comment by rincebrain** [comment] 2016-08-31 10:47
After the patch for #4996, the test case above no longer corrupts, so it presumably qualifies as a dupe of #4996. Does Github have any notion of that, or should I just close this?

**Comment by behlendorf** [comment] 2016-08-31 17:49
@rincebrain thanks for the follow up.  Github doesn't have a notion of duplicates aside from posting it in a comment.

Closing as a duplicate of #4996.

**Closed by behlendorf** 2016-08-31 17:49 UTC
Labels: Bug
