### ISSUE TITLE
dnf reinstall zfs-dkms ends with uninstalled dkms 

### ISSUE THREAD

**Issue by c3d** [zfsonlinux/zfs#7527] opened 2018-05-11 08:08 UTC
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  Fedora
Distribution Version    |  28
Linux Kernel                 |  4.16.6-302.fc28.x86_64
Architecture                 | x86_64
ZFS Version                  | 0.7.9
SPL Version                  | 0.7.9

### Describe the problem you're observing

I tried installed zfs on a system with libvirt / VMs installed (which require zfs-fuse), following the instructions here: https://github.com/zfsonlinux/zfs/wiki/Fedora, using `dnf --allowerasing`. After installation, `zpool create` reported that the zfs module was not loaded, and it had indeed not been installed.

I then tried to reinstall zfs and then zfs-dkms. For zfs-dkms, there was a long build time, and kernel modules were built, tested and installed, e.g. I saw:

```
zfs.ko.xz:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.16.6-302.fc28.x86_64/extra/

```

But then the process went ahead and uninstalled the dkms, which I don't think is intentional:

```
DKMS: install completed.
  Running scriptlet: zfs-dkms-0.7.9-1.fc28.noarch                           2/2

Uninstall of zfs module (zfs-0.7.9-1) beginning:

-------- Uninstall Beginning --------
Module:  zfs
Version: 0.7.9
Kernel:  4.16.6-302.fc28.x86_64 (x86_64)
-------------------------------------

Status: Before uninstall, this module version was ACTIVE on this kernel.
Removing any linked weak-modules

```

The log ended up with:

```
depmod.....

DKMS: uninstall completed.

------------------------------
Deleting module version: 0.7.9
completely from the DKMS tree.
------------------------------
Done.
  Erasing          : zfs-dkms-0.7.9-1.fc28.noarch                           2/2
  Verifying        : zfs-dkms-0.7.9-1.fc28.noarch                           1/2
  Verifying        : zfs-dkms-0.7.9-1.fc28.noarch                           2/2

Reinstalled:
  zfs-dkms.noarch 0.7.9-1.fc28
```

and the modules were not installed. Manually installing with `dkms install` worked.

Of note, when I manually built from `/usr/src`, I noticed that there was a missing dependency on `libtirpc-devel` (I saw an issue for that one) and on `libblkid-devel` (issue for that one not found). Maybe that's the cause of the problem. but I doubt it since the build was apparently successful anyway.

### Describe how to reproduce the problem

On a Fedora 28 system with kvm / qemu / libvirt installed, install zfs using

```
dnf install http://download.zfsonlinux.org/fedora/zfs-release$(rpm -E %dist).noarch.rpm
dnf install --allowerasing kernel-devel zfs
```

Then check that `modprobe zfs` does not find the module:

```
 modprobe zfs
modprobe: FATAL: Module zfs not found in directory /lib/modules/4.16.6-302.fc28.x86_64
```

Then try

```
dnf reinstall zfs-dkms
```

and check that the modules are built, installed then uninstalled.

Log looks something like that (some elements removed for clarity):

```
zfs.ko.xz:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.16.6-302.fc28.x86_64/extra/
...
DKMS: install completed.
  Running scriptlet: zfs-dkms-0.7.9-1.fc28.noarch                           2/2

Uninstall of zfs module (zfs-0.7.9-1) beginning:

-------- Uninstall Beginning --------
Module:  zfs
Version: 0.7.9
Kernel:  4.16.6-302.fc28.x86_64 (x86_64)
-------------------------------------

Status: Before uninstall, this module version was ACTIVE on this kernel.
Removing any linked weak-modules

zavl.ko.xz:
 - Uninstallation
   - Deleting from: /lib/modules/4.16.6-302.fc28.x86_64/extra/
rmdir: failed to remove 'extra': Directory not empty
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


znvpair.ko.xz:
 - Uninstallation
   - Deleting from: /lib/modules/4.16.6-302.fc28.x86_64/extra/
rmdir: failed to remove 'extra': Directory not empty
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


zunicode.ko.xz:
 - Uninstallation
   - Deleting from: /lib/modules/4.16.6-302.fc28.x86_64/extra/
rmdir: failed to remove 'extra': Directory not empty
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


zcommon.ko.xz:
 - Uninstallation
   - Deleting from: /lib/modules/4.16.6-302.fc28.x86_64/extra/
rmdir: failed to remove 'extra': Directory not empty
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


zfs.ko.xz:
 - Uninstallation
   - Deleting from: /lib/modules/4.16.6-302.fc28.x86_64/extra/
rmdir: failed to remove 'extra': Directory not empty
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


zpios.ko.xz:
 - Uninstallation
   - Deleting from: /lib/modules/4.16.6-302.fc28.x86_64/extra/
rmdir: failed to remove 'extra': Directory not empty
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


icp.ko.xz:
 - Uninstallation
   - Deleting from: /lib/modules/4.16.6-302.fc28.x86_64/extra/
rmdir: failed to remove 'extra': Directory not empty
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

depmod.....

DKMS: uninstall completed.

------------------------------
Deleting module version: 0.7.9
completely from the DKMS tree.
------------------------------
Done.
  Erasing          : zfs-dkms-0.7.9-1.fc28.noarch                           2/2
  Verifying        : zfs-dkms-0.7.9-1.fc28.noarch                           1/2
  Verifying        : zfs-dkms-0.7.9-1.fc28.noarch                           2/2

Reinstalled:
  zfs-dkms.noarch 0.7.9-1.fc28
```

**Comment by loli10K** [comment] 2018-05-13 18:48
Duplicate of #7457

**Closed by loli10K** 2018-05-13 18:48 UTC
