### ISSUE TITLE
Debian Buster Root on ZFS - Emergency Mode on Restart

### ISSUE THREAD

**Issue by chmcwill511** [zfsonlinux/zfs#9985] opened 2020-02-12 06:36 UTC
@rlaager

# System information
Distribution Name	| Buster
Distribution Version  | 10
Linux Kernel	| 4.19.0-8
Architecture	| amd64
ZFS Version	| 0.8.2-3
SPL Version	| 0.8.2-3

### Describe the problem you're observing
After following steps 1 through 6.4 in detail under the Debian Buster Root on ZFS documentation, the machine restarts in emergency mode.

### Include any warning/errors/backtraces from the system logs
The only error which seems relevant was after step 4.6 and showed the following:

Setting up zfsutils-linux (0.8.2-3~bpo10+1) ...
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.19.0-6-amd64/modules.dep.bin'
modprobe: FATAL: Module zfs not found in directory /lib/modules/4.19.0-6-amd64

I'm proficient in general linux, working mostly with Ubuntu but certainly not proficient, any assistance with this would be greatly appreciated. I've researched online as much as I can and re-worked through the process which worked just fine for me back on January 12th but late last week and this week, I've been using the same process and getting consistent emergency mode showing up. Thanks for any direction/support.

**Comment by johnnyjacq16** [comment] 2020-02-12 17:13
@chmcwill511 do you want an answer from rlaager specifically?
I will take it that you are using zfs as the root fs, it seems that zfs has not been installed as the modules have not been built.
Boot your system back into the CD/USB live environment then follow the Debian Buster Root on ZFS documentation instruction from section 1.1 - 1.5 (DO NOT FORMAT THE DISK AGAIN). Make sure that zfs is installed in the CD/USB environment.
Chroot back into the installation from the live CD/USB by doing the follow.
if you used cryptsetup, you will need to open the crypt device 
`cryptsetup open /dev/sdX luks1`
replace X with you disk number
if you did NOT use luks encryption skip the cryptsetup command
```
zpool import -N -R /mnt rpool
zpool import -N -R /mnt bpool
zfs load-key -a (ONLY NEEDED IF YOU USED zfs encryption NOT NEEDED LUKS/CRYPTSETUP)
zfs mount rpool/ROOT/debian
zfs mount -a

mount --rbind /dev  /mnt/dev
mount --rbind /proc /mnt/proc
mount --rbind /sys  /mnt/sys
chroot /mnt /bin/bash --login
mount /boot
mount -a
```
Make sure that /boot is mounted correctly when you chroot into the installation from CD/USB environment, if the /boot is on a different partition.

Once you have chrooted into the installation run `dkms status ` to ensure that zfs has been build.
It should look like the below:
```
dkms status 
zfs, 0.8.3, 5.4.0-3parrot1-amd64, x86_64: installed
```
If the module has not been built, to fix this run:
`dkms install -m zfs -v <your zfs version> -k 4.19.0-6-amd64`
To find the version number you need do `dpkg -L zfs-dkms`
Example
/usr/src/zfs-0.8.3/zfs_config.h.in
the zfs version number is 0.8.3 hence 
`dkms install -m zfs -v 0.8.3 -k 4.19.0-6-amd64`
After that then run `dkms status` again to ensure that the module is installed

**Comment by chmcwill511** [comment] 2020-02-12 18:59
Not exclusively, just trying to follow instructions on posting - I'll recheck this when I'm back in the office this afternoon and let you know what results I get. Thank you.

**Comment by chmcwill511** [comment] 2020-02-13 05:06
So I stepped through section 1.1 till 1.5, the zpool import failed without the -f (force) option being added. The dkms status showed zfs, 0.8.2, 4.19.0-8-amd64, x86_64: installed.  I then proceeded with update-initramfs -u -k all and restarted only to get the same messages showing up as follows.

[FAILED] Failed to start Mount ZFS filesystems.
See 'systemctl status zfs-mount.service' for details.
You are in emergency mode...

zfs-mount.service - Mount ZFS filesystems
Loaded: loaded (/lib/systemd/system/zfs-mount.service; enabled; vendor preset: enabled)
Active: failed (Result: exit-code) since Wed 2020-02-12 :2257:17 CST; 4min 19s ago
Docs: man:zfs(8)
Process: 1438 ExecStart=/sbin/zfs mount -a (code=exited, status=1/FAILURE)
Main PID: 1438 (code=exited, status=1/FAILURE)
zfs[1438]: cannot mount '/tmp': directory is not empty
Failed to start Mount ZFS filesystems.

**Comment by johnnyjacq16** [comment] 2020-02-13 14:05
Ok so that means that zfs is now install properly:
Your error messages looks different, orginally it was:
Your error message orginally was as shown below:
```
Setting up zfsutils-linux (0.8.2-3~bpo10+1) ...
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.19.0-6-amd64/modules.dep.bin'
modprobe: FATAL: Module zfs not found in directory /lib/modules/4.19.0-6-amd64
```
The `modprobe: FATAL: Module zfs not found in directory /lib/modules/4.19.0-6-amd64` part of the message means that zfs modules was not built, now since you have followed the instructions where the zfs modules have now been installed and built you got the message `zfs, 0.8.2, 4.19.0-8-amd64, x86_64: installed` from command `dkms status` which now means that the zfs modules are built. The `update-initramfs -u -k all `command ensured that the zfs modules are also in the initram disk which is need to boot from zfs.
**That part of the problem is now solved.**
NOTE with the  `zpool import -N -R /mnt rpool` command, when you import the pool onto another system you need to include the` -f `option as well (I should have included that)

**The next part of the problem:**
The problem that you are having now shown below:
```
[FAILED] Failed to start Mount ZFS filesystems.
See 'systemctl status zfs-mount.service' for details.
You are in emergency mode...

zfs-mount.service - Mount ZFS filesystems
Loaded: loaded (/lib/systemd/system/zfs-mount.service; enabled; vendor preset: enabled)
Active: failed (Result: exit-code) since Wed 2020-02-12 :2257:17 CST; 4min 19s ago
Docs: man:zfs(8)
Process: 1438 ExecStart=/sbin/zfs mount -a (code=exited, status=1/FAILURE)
Main PID: 1438 (code=exited, status=1/FAILURE)
zfs[1438]: cannot mount '/tmp': directory is not empty
Failed to start Mount ZFS filesystems.
```
What this message means is that zfs cannot mount all the dataset due to the /tmp directory not being empty. In your error message I am looking at the line `zfs[1438]: cannot mount '/tmp': directory is not empty`
You need boot the PC  (DO NOT BOOT FROM CD/USB NOW that part of the problem is now solved)  when you reach emerency mode again, check that zfs have imported the pool with `zpool list` also check that your root fs is mounted with `df -Th /` . This should show the zfs pool have been imported and that the root fs is also mounted.
To solve the problem `cd `to the `/tmp `directory delete all content that is in that directory ( delete ONLY in `/tmp` directory, to avoid mistakes you can ceate zfs snapshot beforehand) also ensure that there are no hidden content in the directory, if so delete them as well, if you need the data stored in /tmp  move them somewhere else for now, then re-run the `zfs mount -a `command again there should be no error messge, if there are any error messages then run the command `systemctl status zfs-mount` look for the lines that state that some directory is not empty as before, then delete whenerever is in that directory also hidden items.
After that type `exit` to boot the system.

**Comment by chmcwill511** [comment] 2020-02-13 17:09
Followed these steps and was successful in getting it mounted and signed in normally, until I restarted the machine and was right back to square one expected it said cannot mount '/var/cache': directory is not empty as well.

Under section 3.3, I went ahead to create the tmpfs, should I have not done that?

**Comment by johnnyjacq16** [comment] 2020-02-14 08:53
Creating a tmpfs is ok, did you try to change the runlevels/targets the last time you booted the machine as this may cause zfs to not mount datatset correctly due to unmounting of the dataset when the runlevel was changed at which point data gets written to mountpoint that should remain empty.

To solve this re-occurring problem:
Boot the machine, when it reaches emergency mode again, do the following:
```
zfs umount  rpool/var/cache
zfs umount  rpool/var/tmp
zfs umount  rpool/var/spool
zfs umount  rpool/var/log
```

Go to `/var/cache`,` /var/tmp/,` `/var/spool/`,` /var/log` remove all content in those directories then do `zfs mount -a` and `mount -a `then `exit`

**Comment by chmcwill511** [comment] 2020-02-14 16:08
I've restarted, zfs umounted rpool/var/cache, rpool/var/tmp, rpool/var/spool and rpool/var/log without any issues. Checking /var/cache, /var/tmp, /var/spool and /var/log which were all empty. When I try to zfs mount -a it reports cannot mount '/tmp': directory is not empty. Checking it, there is the similar systemd-private-{guid}-systemd-timesyncd.service file which I've see over and over. I remove it, then able to zfs mount -a and mount -a then exit which get's me to a login screen. I'm able to sign in without any issues and restart only to get the same messages as follows.

[FAILED] Failed to start Mount ZFS filesystems.
See 'systemctl status zfs-mount.service' for details.
You are in emergency mode...

**Comment by chmcwill511** [comment] 2020-02-14 17:24
I've got to get this resolved so I worked through the whole process from the beginning, it looks like we are still on Debian 10 Kernel 4.19.0-8-amd64 but ZFS is now showing 0.8.3-1. Here is the step by step and it's failing earlier now (see message at end). 

Boot the Debian 10 Live CD
sudo apt update
sudo apt install --yes openssh-server
sudo systemctl restart ssh
Connect with ssh user@IP
sudo -i
echo deb http://deb.debian.org/debian buster contrib >> /etc/apt/sources.list
echo deb http://deb.debian.org/debian buster-backports main contrib >> /etc/apt/sources.list
apt update
apt install --yes debootstrap gdisk dkms dpkg-dev linux-headers-$(uname -r)
apt install --yes -t buster-backports --no-install-recommends zfs-dkms
modprobe zfs
apt install --yes -t buster-backports zfsutils-linux
DISK1=/dev/disk/by-id/ata-HGST_HDN726040ALE614_K7GVWP4L
DISK2=/dev/disk/by-id/ata-HGST_HDN726040ALE614_K4K7YANB
DISK3=/dev/disk/by-id/ata-HGST_HDN726040ALE614_K4K7ZM0B
DISK4=/dev/disk/by-id/ata-HGST_HDN726040ALE614_K7GLNNKB
DISK5=/dev/disk/by-id/ata-HGST_HDN726040ALE614_K4JZ8ZWB
DISK6=/dev/disk/by-id/ata-HGST_HDN726040ALE614_K4K6AN4B
DISK7=/dev/disk/by-id/ata-HGST_HDN726040ALE614_K4K7YDEB
DISK8=/dev/disk/by-id/ata-HGST_HDN726040ALE614_K7GLNHUB
zpool import -f -d /dev/disk/by-id -R /mnt bpool
zpool destroy bpool
zpool import -f -d /dev/disk/by-id -R /mnt rpool
zpool destroy rpool
sgdisk --zap-all $DISK1
sgdisk --zap-all $DISK2
sgdisk --zap-all $DISK3
sgdisk --zap-all $DISK4
sgdisk --zap-all $DISK5
sgdisk --zap-all $DISK6
sgdisk --zap-all $DISK7
sgdisk --zap-all $DISK8
sgdisk -a1 -n1:24K:+1000K -t1:EF02 $DISK1
sgdisk -n2:1M:+512M -t2:EF00 $DISK1
sgdisk -n3:0:+1G -t3:BF01 $DISK1
sgdisk -n4:0:0 -t4:BF01 $DISK1
sgdisk -a1 -n1:24K:+1000K -t1:EF02 $DISK2
sgdisk -n2:1M:+512M -t2:EF00 $DISK2
sgdisk -n3:0:+1G -t3:BF01 $DISK2
sgdisk -n4:0:0 -t4:BF01 $DISK2
sgdisk -a1 -n1:24K:+1000K -t1:EF02 $DISK3
sgdisk -n2:1M:+512M -t2:EF00 $DISK3
sgdisk -n3:0:+1G -t3:BF01 $DISK3
sgdisk -n4:0:0 -t4:BF01 $DISK3
sgdisk -a1 -n1:24K:+1000K -t1:EF02 $DISK4
sgdisk -n2:1M:+512M -t2:EF00 $DISK4
sgdisk -n3:0:+1G -t3:BF01 $DISK4
sgdisk -n4:0:0 -t4:BF01 $DISK4
sgdisk -a1 -n1:24K:+1000K -t1:EF02 $DISK5
sgdisk -n2:1M:+512M -t2:EF00 $DISK5
sgdisk -n3:0:+1G -t3:BF01 $DISK5
sgdisk -n4:0:0 -t4:BF01 $DISK5
sgdisk -a1 -n1:24K:+1000K -t1:EF02 $DISK6
sgdisk -n2:1M:+512M -t2:EF00 $DISK6
sgdisk -n3:0:+1G -t3:BF01 $DISK6
sgdisk -n4:0:0 -t4:BF01 $DISK6
sgdisk -a1 -n1:24K:+1000K -t1:EF02 $DISK7
sgdisk -n2:1M:+512M -t2:EF00 $DISK7
sgdisk -n3:0:+1G -t3:BF01 $DISK7
sgdisk -n4:0:0 -t4:BF01 $DISK7
sgdisk -a1 -n1:24K:+1000K -t1:EF02 $DISK8
sgdisk -n2:1M:+512M -t2:EF00 $DISK8
sgdisk -n3:0:+1G -t3:BF01 $DISK8
sgdisk -n4:0:0 -t4:BF01 $DISK8
zpool create -o ashift=12 -d \
  -o feature@async_destroy=enabled \
  -o feature@bookmarks=enabled \
  -o feature@embedded_data=enabled \
  -o feature@empty_bpobj=enabled \
  -o feature@enabled_txg=enabled \
  -o feature@extensible_dataset=enabled \
  -o feature@filesystem_limits=enabled \
  -o feature@hole_birth=enabled \
  -o feature@large_blocks=enabled \
  -o feature@lz4_compress=enabled \
  -o feature@spacemap_histogram=enabled \
  -o feature@userobj_accounting=enabled \
  -o feature@zpool_checkpoint=enabled \
  -o feature@spacemap_v2=enabled \
  -o feature@project_quota=enabled \
  -o feature@resilver_defer=enabled \
  -o feature@allocation_classes=enabled \
  -O acltype=posixacl -O canmount=off -O compression=lz4 -O devices=off \
  -O normalization=formD -O relatime=on -O xattr=sa \
  -O mountpoint=/ -R /mnt bpool ${DISK1}-part3
mountpoint '/mnt/' exists and is not empty
use '-m' option to provide a different default
I manually cleared /mnt and redid the zpool create
zpool create -o ashift=12 \
  -O acltype=posixacl -O canmount=off -O compression=lz4 \
  -O dnodesize=auto -O normalization=formD -O relatime=on -O xattr=sa \
  -O mountpoint=/ -R /mnt rpool ${DISK1}-part4 ${DISK2}-part4 ${DISK3}-part4 ${DISK4}-part4 ${DISK5}-part4 ${DISK6}-part4 ${DISK7}-part4 ${DISK8}-part4
zfs create -o canmount=off -o mountpoint=none rpool/ROOT
zfs create -o canmount=off -o mountpoint=none bpool/BOOT
zfs create -o canmount=noauto -o mountpoint=/ rpool/ROOT/debian
zfs mount rpool/ROOT/debian
zfs create -o canmount=noauto -o mountpoint=/boot bpool/BOOT/debian
zfs mount bpool/BOOT/debian
zfs create rpool/home
zfs create -o mountpoint=/root rpool/home/root
zfs create -o canmount=off rpool/var
zfs create -o canmount=off rpool/var/lib
zfs create rpool/var/log
zfs create rpool/var/spool
debootstrap buster /mnt
zfs set devices=off rpool
echo UBNT-NVR > /mnt/etc/hostname
vi /mnt/etc/hosts
Add a line:
127.0.1.1       UBNT-NVR

vi /mnt/etc/network/interfaces.d/eno2
auto eno2
iface eno2 inet dhcp

vi /mnt/etc/apt/sources.list
deb http://deb.debian.org/debian buster main
deb http://deb.debian.org/debian buster main contrib
deb-src http://deb.debian.org/debian buster main contrib

vi /mnt/etc/apt/sources.list.d/buster-backports.list
deb http://deb.debian.org/debian buster-backports main contrib
deb-src http://deb.debian.org/debian buster-backports main contrib

vi /mnt/etc/apt/preferences.d/90_zfs
Package: libnvpair1linux libuutil1linux libzfs2linux libzfslinux-dev libzpool2linux python3-pyzfs pyzfs-doc spl spl-dkms zfs-dkms zfs-dracut zfs-initramfs zfs-test zfsutils-linux zfsutils-linux-dev zfs-zed
Pin: release n=buster-backports
Pin-Priority: 990

mount --rbind /dev  /mnt/dev
mount --rbind /proc /mnt/proc
mount --rbind /sys /mnt/sys
chroot /mnt /usr/bin/env DISK=$DISK1 bash --login
ln -s /proc/self/mounts /etc/mtab
apt update
apt install --yes locales
dpkg-reconfigure locales
Select en_US.UTF-8 and as default
dpkg-reconfigure tzdata
Select US and Central
apt install --yes dpkg-dev linux-headers-amd64 linux-image-amd64
apt install --yes zfs-initramfs
W: Possible missing firmware /lib/firmware/tigon/tg3_tso5.bin for module tg3
W: Possible missing firmware /lib/firmware/tigon/tg3_tso.bin for module tg3
W: Possible missing firmware /lib/firmware/tigon/tg3.bin for module tg3
setupcon is missing. Please install the 'console-setup' package?
DISK1=/dev/disk/by-id/ata-HGST_HDN726040ALE614_K7GVWP4L
apt install dosfstools
mkdosfs -F 32 -s 1 -n EFI ${DISK1}-part2
mkdir /boot/efi
echo PARTUUID=$(blkid -s PARTUUID -o value ${DISK1}-part2) \
    /boot/efi vfat nofail,x-systemd.device-timeout=1 0 1 >> /etc/fstab
mount /boot/efi
apt install --yes grub-efi-amd64 shim-signed
passwd
vi /etc/systemd/system/zfs-import-bpool.service
[Unit]
DefaultDependencies=no
Before=zfs-import-scan.service
Before=zfs-import-cache.service
[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/sbin/zpool import -N -o cachefile=none bpool
[Install]
WantedBy=zfs-import.target
systemctl enable zfs-import-bpool.service

grub-probe /boot
update-initramfs -u -k all
vi /etc/default/grub
Set: GRUB_CMDLINE_LINUX="root=ZFS=rpool/ROOT/debian"

update-grub
grub-install --target=x86_64-efi --efi-directory=/boot/efi \
    --bootloader-id=debian --recheck --no-floppy
ls /boot/grub/*/zfs.mod
umount /boot/efi
zfs set mountpoint=legacy bpool/BOOT/debian
echo bpool/BOOT/debian /boot zfs \
    nodev,relatime,x-systemd.requires=zfs-import-bpool.service 0 0 >> /etc/fstab
mkdir /var/lock
mkdir /etc/zfs/zfs-list.cache
touch /etc/zfs/zfs-list.cache/rpool
ln -s /usr/lib/zfs-linux/zed.d/history_event-zfs-list-cacher.sh /etc/zfs/zed.d
zed -F &
mkdir: cannot create directory ‘/var/lock’: File exists
cat /etc/zfs/zfs-list.cache/rpool
If it is empty, force a cache update and check again:
zfs set canmount=noauto rpool/ROOT/debian
fg
Press Ctrl-C.
sed -Ei "s|/mnt/?|/|" /etc/zfs/zfs-list.cache/rpool
zfs snapshot bpool/BOOT/debian@install
zfs snapshot rpool/ROOT/debian@install
exit

Run these commands in the LiveCD environment to unmount all filesystems as root:
sudo –i
mount | grep -v zfs | tac | awk '/\/mnt/ {print $3}' | xargs -i{} umount -lf {}
zpool export –a
reboot

Failed to unmount a bunch of directories on before restarting
After restart, Failed to mount /boot and into emergency mode again.
filesystem 'bpool/BOOT/debian' cannot be mounted, unable to open the dataset

**Comment by chmcwill511** [comment] 2020-02-14 18:33
This machine is a Dell PowerEdge T330 with 32 GB memory and 8x 4 TB drives - I really don't care which method we boot using, BIOS, UEFI, ext4, zfs, etc. but we need a Debian/Ubuntu based server with the /usr/lib/unifi-video to be on a zfs stripe of all 8 drives. I've had mixed success using Ubuntu 16.04 LTS and 18.04 LTS with everything on a single ZFS pool. The initial Debian 10 install on this machine which we did back in January worked perfectly until we did an update and reinstall (which seems to be a similar issue on the Ubuntu setup). I've done a similar process on another Dell PowerEdge T130 with 16 GB memory and 4x 4 TB drives which is having the same problems this month as well. I need to get this system back into production, any assistance with this would be greatly appreciated, thanks.

**Comment by johnnyjacq16** [comment] 2020-02-14 23:31
Thank you for detailing the process, now I see issue, there is a critical error in the documentation.
rpool should have been created first then the boot pool created second  plus the mountpoint option is incorrect for the boot pool it should be `-O mountpoint=/boot -R /mnt bpool ${DISK1}-part3` NOT `-O mountpoint=/ -R /mnt bpool ${DISK1}-part3`.
The boot pool (bpool) should not have the same mountpoint as the root pool (rpool) causing an overlapping mount situation and data not getting written to the correct places.
@behlendorf , @ahrens there are issues with the documentation https://github.com/zfsonlinux/zfs/wiki/Debian-Buster-Root-on-ZFS the boot pool should be mounted at `/boot` not `/ `along with the root pool, can you alert the person who can modify the documentation, which assist anyone who follow the guide to install zfs and get it working in linux.

**Comment by chmcwill511** [comment] 2020-02-15 00:11
Sweet, I'll run through the process again this evening but from what I understand we should have the following sequence and commands for the zpool creates?

zpool create -o ashift=12 \
  -O acltype=posixacl -O canmount=off -O compression=lz4 \
  -O dnodesize=auto -O normalization=formD -O relatime=on -O xattr=sa \
  -O mountpoint=/ -R /mnt rpool ${DISK1}-part4 ${DISK2}-part4 ${DISK3}-part4 ${DISK4}-part4 ${DISK5}-part4 ${DISK6}-part4 ${DISK7}-part4 ${DISK8}-part4
zpool create -o ashift=12 -d \
  -o feature@async_destroy=enabled \
  -o feature@bookmarks=enabled \
  -o feature@embedded_data=enabled \
  -o feature@empty_bpobj=enabled \
  -o feature@enabled_txg=enabled \
  -o feature@extensible_dataset=enabled \
  -o feature@filesystem_limits=enabled \
  -o feature@hole_birth=enabled \
  -o feature@large_blocks=enabled \
  -o feature@lz4_compress=enabled \
  -o feature@spacemap_histogram=enabled \
  -o feature@userobj_accounting=enabled \
  -o feature@zpool_checkpoint=enabled \
  -o feature@spacemap_v2=enabled \
  -o feature@project_quota=enabled \
  -o feature@resilver_defer=enabled \
  -o feature@allocation_classes=enabled \
  -O acltype=posixacl -O canmount=off -O compression=lz4 -O devices=off \
  -O normalization=formD -O relatime=on -O xattr=sa \
  -O mountpoint=/**boot** -R /mnt bpool ${DISK1}-part3

**Comment by rlaager** [comment] 2020-02-15 00:12
Canonical has moved to setting `mountpoint=/boot` on `bpool` in their installed in 19.10, but other than that, root installs have always used `mountpoint=/` for `bpool`. That's not the issue. It is not harmful for both `bpool` and `rpool` to have `mountpoint=/`, as both of those datasets are `canmount=off`.

**Comment by chmcwill511** [comment] 2020-02-15 00:19
Okay, so what is the issue with the instructions then @rlaager

**Comment by rlaager** [comment] 2020-02-15 00:22
@chmcwill511 When you land in "emergency mode", that's a systemd thing, right? Not the initramfs environment? The issues is that `/boot` is failing to mount?

If you comment out /boot and /boot/efi from /etc/fstab, does the system come up normally? If so, what happens if you leave /boot/efi commented out, but uncomment /boot? If it fails, run `zpool status` and see if the bpool is imported. Does `zfs mount bpool/BOOT/debian` work?

**Comment by chmcwill511** [comment] 2020-02-15 00:28
@rlaager I believe the original issues were with systemd and not initramfs. I've already started running through the process with the changes above so will revent as soon as I have details from how it went, thanks.

**Comment by johnnyjacq16** [comment] 2020-02-15 00:36
@rlaager  zfs mount bpool/BOOT/debian should not work because it was set to be legacy in the documentation show below: 
```
zfs set mountpoint=legacy bpool/BOOT/debian
echo bpool/BOOT/debian /boot zfs \
    nodev,relatime,x-systemd.requires=zfs-import-bpool.service 0 0 >> /etc/fstab
```

You will have to use the `mount -t zfs `command

**Comment by rlaager** [comment] 2020-02-15 00:38
@johnnyjacq16 Right. Thanks!

@chmcwill511 So `mount /boot` instead of `zfs mount /boot` in that testing.

**Comment by johnnyjacq16** [comment] 2020-02-15 00:45
I believe that the system is trying to boot with rpool instead of bpool, becasue bpool is not mounted at the time when the kernel is being installed. 
Grub may be trying to mount the pool read-only because grub does not support all zfs features of rpool.

**Comment by johnnyjacq16** [comment] 2020-02-15 00:55
Hence rpool should be created first then the bpool created second with option canmount=on instead of off and the mountpoint=/boot.

**Comment by chmcwill511** [comment] 2020-02-15 01:47
@johnnyjacq16 There are multiple create's and mounts in the following, is this correct or have I missed something still?

zpool create -o ashift=12 \
  -O acltype=posixacl -O canmount=off -O compression=lz4 \
  -O dnodesize=auto -O normalization=formD -O relatime=on -O xattr=sa \
  -O mountpoint=/ -R /mnt rpool ${DISK1}-part4 ${DISK2}-part4 ${DISK3}-part4 ${DISK4}-part4 ${DISK5}-part4 ${DISK6}-part4 ${DISK7}-part4 ${DISK8}-part4

zpool create -o ashift=12 -d \
  -o feature@async_destroy=enabled \
  -o feature@bookmarks=enabled \
  -o feature@embedded_data=enabled \
  -o feature@empty_bpobj=enabled \
  -o feature@enabled_txg=enabled \
  -o feature@extensible_dataset=enabled \
  -o feature@filesystem_limits=enabled \
  -o feature@hole_birth=enabled \
  -o feature@large_blocks=enabled \
  -o feature@lz4_compress=enabled \
  -o feature@spacemap_histogram=enabled \
  -o feature@userobj_accounting=enabled \
  -o feature@zpool_checkpoint=enabled \
  -o feature@spacemap_v2=enabled \
  -o feature@project_quota=enabled \
  -o feature@resilver_defer=enabled \
  -o feature@allocation_classes=enabled \
  -O acltype=posixacl -O canmount=on -O compression=lz4 -O devices=off \
  -O normalization=formD -O relatime=on -O xattr=sa \
  -O mountpoint=/boot -R /mnt bpool ${DISK1}-part3

zfs create -o canmount=off -o mountpoint=none rpool/ROOT
zfs create -o canmount=on -o mountpoint=/boot bpool/BOOT

zfs create -o canmount=noauto -o mountpoint=/ rpool/ROOT/debian
zfs mount rpool/ROOT/debian
zfs create -o canmount=noauto -o mountpoint=/boot bpool/BOOT/debian
zfs mount bpool/BOOT/debian

**Comment by rlaager** [comment] 2020-02-15 02:02
> Hence rpool should be created first then the bpool created second

The order of pool creation is irrelevant. The root filesystem (rpool/ROOT/debian) must be mounted first, but the instructions already have that.

> with option canmount=on instead of off

Do not set canmount=on for either bpool or rpool!

> and the mountpoint=/boot.

This is fine and will be changing in future HOWTOs just for consistency with the Ubuntu installer but has absolutely nothing to do with the issue at hand.

**Comment by chmcwill511** [comment] 2020-02-15 02:04
@rlaager When starting up, it shows /boot failed and goes into Emergency Mode. zpool status only shows rpool online, bpool not listed.

Commenting out /boot and /boot/efi from /etc/fstab does allow the system to start normally. Again zpool status only shows rpool online.

Under this startup zfs mount bpool/BOOT/debian or mount /boot all error out.

**Comment by chmcwill511** [comment] 2020-02-15 02:12
@rlaager So link this then?

zpool create -o ashift=12 \
  -O acltype=posixacl -O canmount=off -O compression=lz4 \
  -O dnodesize=auto -O normalization=formD -O relatime=on -O xattr=sa \
  -O mountpoint=/ -R /mnt rpool ${DISK1}-part4 ${DISK2}-part4 ${DISK3}-part4 ${DISK4}-part4 ${DISK5}-part4 ${DISK6}-part4 ${DISK7}-part4 ${DISK8}-part4

zpool create -o ashift=12 -d \
  -o feature@async_destroy=enabled \
  -o feature@bookmarks=enabled \
  -o feature@embedded_data=enabled \
  -o feature@empty_bpobj=enabled \
  -o feature@enabled_txg=enabled \
  -o feature@extensible_dataset=enabled \
  -o feature@filesystem_limits=enabled \
  -o feature@hole_birth=enabled \
  -o feature@large_blocks=enabled \
  -o feature@lz4_compress=enabled \
  -o feature@spacemap_histogram=enabled \
  -o feature@userobj_accounting=enabled \
  -o feature@zpool_checkpoint=enabled \
  -o feature@spacemap_v2=enabled \
  -o feature@project_quota=enabled \
  -o feature@resilver_defer=enabled \
  -o feature@allocation_classes=enabled \
  -O acltype=posixacl -O canmount=off -O compression=lz4 -O devices=off \
  -O normalization=formD -O relatime=on -O xattr=sa \
  -O mountpoint=/boot -R /mnt bpool ${DISK1}-part3

zfs create -o canmount=off -o mountpoint=none rpool/ROOT
zfs create -o canmount=off -o mountpoint=/boot bpool/BOOT

zfs create -o canmount=noauto -o mountpoint=/ rpool/ROOT/debian
zfs mount rpool/ROOT/debian
zfs create -o canmount=noauto -o mountpoint=/boot bpool/BOOT/debian
zfs mount bpool/BOOT/debian

**Comment by rlaager** [comment] 2020-02-15 02:12
Alright, excellent. So there is no need to reinstall again. We can sort this out from normal mode.

The question now is: why isn’t bpool importing? What is the status of the custom zpool-import-bpool.service? Did it try to start? If it failed, what errors?

**Comment by chmcwill511** [comment] 2020-02-15 02:36
@rlaager /etc/fstab with /boot/efi and without /boot also starts up without any issues.

service zfs-import-bpool status shows failed to load, invalid arguments, missing '='

**Comment by chmcwill511** [comment] 2020-02-15 02:57
@rlaager /etc/systemd/system/zfs-import-bpool.service

[Unit]
DefaultDependencies=no
Before=zfs-import-scan.service
Before=zfs-import-cache.service
[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/sbin/zpool import -N -o cachefile=none bpool
[Install]
WantedBy=zfs-import.target
systemctl enable zfs-import-bpool.service

**Comment by chmcwill511** [comment] 2020-02-15 02:59
@rlaager So in section 4.10, is systemctl enable zfs-import-bpool.service meant to be included in the /etc/systemd/system/zfs-import-bpool.service or a separate command run after adding the above commands to the /etc/systemd/system/zfs-import-bpool.service using vi?

**Comment by chmcwill511** [comment] 2020-02-15 03:09
@rlaager So I removed the last line from the /etc/systemd/system/zfs-import-bpool.service and restarted, it now shows the service as loaded and inactive. zfs status still only shows rpool online.

I went back to add /boot to /etc/fstab and restarted, now zfs status shows both rpool and bpool online. I'm going to run through the original process again so I can make sure that everything is working as expected now.

Maybe make it a little clearer in section 4.10 that the last line isn't to be included in the /etc/systemd/system/zfs-import-bpool.service.

**Comment by chmcwill511** [comment] 2020-02-15 03:54
@johnnyjacq16 and @rlaager Running though this with the original instructions now that the issue seemed to have been related to section 4.10 including the last line, I get to section 5.1 and grub-probe /boot fails with the message failed to get canonical path of `bpool/BOOT/debian'

I'll go ahead to retry adding the mountpoint=/boot since I assume that's the issue here?

**Comment by rlaager** [comment] 2020-02-15 03:58
It is not the mountpoint of bpool.

What is the output of:
`zpool get all bpool | grep feature | grep -v disabled`

**Comment by chmcwill511** [comment] 2020-02-15 04:37
@rlaager I had already restarted the process with the mountpoint=/boot and everything went through without any issues so I didn't have a chance to check on that output, sorry.

**Comment by rlaager** [comment] 2020-02-15 05:07
> Maybe make it a little clearer in section 4.10 that the last line isn't to be included in the /etc/systemd/system/zfs-import-bpool.service.

I separated it out. It's pretty subtle, but is that better? If not, I can add some more explicit text, like "Enable the service:". (I'm going to close this issue, but you should still be able to comment either way.)

**Closed by rlaager** 2020-02-15 05:07 UTC
