### ISSUE TITLE
Investigate memory management under large number of outstanding IOs

### ISSUE THREAD

**Issue by ryao** [zfsonlinux/zfs#2629] opened 2014-08-27 21:33 UTC
@behlendorf helped a user with a VM where import hung following a reboot that interrupted async_destroy. The behavior was consistent on FreeBSD. Disabling zfs_dedup_prefetch allowed it to work. This issue is being filed as a reference as per IRC:

```
17:11 <+ryao> fling: That isn't a solution so much as it is a workaround. Now we have to figure out why it made a difference.
17:11 <+behlendorf> fling: We may need to look in to changing the default value.  Could you run for a while with the ddt_prefetch disabled and see if performance is horible?
17:11 -!- KittenGNU [~Stop@unaffiliated/kittengnu] has quit [Remote host closed the connection]
17:12 < fling> behlendorf: I will run with disabled
17:13 <+ryao> behlendorf: It is possible that the performance might actually improve. The DDT seeks tend to be random.
17:14 <+behlendorf> ryao: True, it will be interesting to see.
17:16 <+behlendorf> ryao: As for why it helped, the prefetch appears to have proactively queued up about ~700,000 pending IOs which push a little too hard on the VM.
17:16 < fling> reimport works fast, mount takes littletime
17:16 < fling> I will try deleting tons of deduped data tomorrow
17:23 <+ryao> behlendorf: I was not following too closely. How did you determine that?
17:24 <+behlendorf> The slab stats showed that many zio_t objects in the kmem_cache.
17:25 <+behlendorf> And the vast majority of arc buffers were for 4k obejcts which is the ddt leaf block size.
17:25 <+behlendorf> prefetch seemed like a reasonable way to explain that.
17:27 <+ryao> That makes sense. I wonder if this might suggest a more general problem for memory management involving large numbers of in-flight IOs.
17:28 <+behlendorf> That's probably worth investigating
```

**Comment by behlendorf** [comment] 2016-10-12 00:21
Closing as a likely duplicate of #2581.

**Closed by behlendorf** 2016-10-12 00:21 UTC
