### ISSUE TITLE
zpool status shows sd(x) After reboot, Pool Created with by-id

### ISSUE THREAD

**Issue by JandelNinja** [zfsonlinux/zfs#3756] opened 2015-09-10 00:40 UTC
Hello 
I have just installed a fresh Proxmox 3.4.9 system. I created a RAID1 zfs pool with the command.

zpool create -f -o ashift=12 zfspool mirror /dev/disk/by-id/"DRIVE ID" /dev/disk/by-id/"DRIVE ID"

After creating this I ran a zpool status zfspool command.

  pool: zfspool
 state: ONLINE
  scan: none requested
config:

	NAME               STATE     READ WRITE CKSUM
	zfspool            ONLINE       0     0     0
	  mirror-0         ONLINE       0     0     0
	    "DRIVE ID"     ONLINE       0     0     0
	    "DRIVE ID"     ONLINE       0     0     0

After Reboot I ran a zpool status zfspool command and the output shows the following.

  pool: zfspool
 state: ONLINE
  scan: none requested
config:

	NAME        STATE     READ WRITE CKSUM
	zfspool       ONLINE       0     0     0
	  mirror-0    ONLINE       0     0     0
	    sd(x)     ONLINE       0     0     0
	    sd(x)     ONLINE       0     0     0

I believe this is my zfs version 
"ZFS: Loaded module v0.6.4.1-1099_g7939064, ZFS pool version 5000, ZFS filesystem version 5"

I can add USB drives and internal drives to the server and sd(x) changes but correct drives are remaining in the pool. Still I am concerned something is going wrong somewhere. As this going going to be a production system. I would like to know nothing is going to go wrong in the future.  
I see people get this issue on ubuntu systems but I don't seem to read about any solutions.

**Comment by Bronek** [comment] 2015-09-10 10:48
It seems to be a duplicate of #2944

**Comment by BrianPuccio** [comment] 2015-09-19 15:00
I can confirm the same behavior running Debian Wheezy.

Previously, right before the reboot, I'd see this:

```
bukkit# zpool list -v
NAME   SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
home    29T  24.8T  4.19T         -    22%    85%  1.00x  ONLINE  -
  raidz2    29T  24.8T  4.19T         -    22%    85%
    ata-HGST_HDN724040ALE640_PK1334PBK9PGZS      -      -      -         -      -      -
    ata-HGST_HDN724040ALE640_PK1334PBKEKU2S      -      -      -         -      -      -
    ata-HGST_HDN724040ALE640_PK1334PBKG1DZS      -      -      -         -      -      -
    ata-HGST_HDN724040ALE640_PK1334PBKG1E0S      -      -      -         -      -      -
    ata-HGST_HDN724040ALE640_PK1334PBKG1EBS      -      -      -         -      -      -
    ata-HGST_HDN724040ALE640_PK2334PBKBXJRT      -      -      -         -      -      -
    ata-HGST_HDN724040ALE640_PK2334PBKA1MMT      -      -      -         -      -      -
    ata-HGST_HDN724040ALE640_PK2334PBKANLPT      -      -      -         -      -      -
  ata-INTEL_SSDSC2BB120G4_BTWL40150ANZ120LGN-part1  19.9G   508K  19.9G         -    89%     0%
```

Right after the reboot I was greeted with:

```
bukkit# zpool list -v     
NAME   SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
home    29T  24.7T  4.30T         -    21%    85%  1.00x  ONLINE  -
  raidz2    29T  24.7T  4.30T         -    21%    85%
    sdc      -      -      -         -      -      -
    sdb      -      -      -         -      -      -
    sdh      -      -      -         -      -      -
    sdf      -      -      -         -      -      -
    sdd      -      -      -         -      -      -
    sde      -      -      -         -      -      -
    sdg      -      -      -         -      -      -
    sda      -      -      -         -      -      -
  sdl1  19.9G   296K  19.9G         -     0%     0%
```

Here's my history from the scrub I last did 5 days ago:

```
2015-09-12.13:02:59 zpool scrub home
2015-09-19.10:42:08 zpool export home
2015-09-19.10:43:38 zpool import -N home
2015-09-19.10:45:28 zpool upgrade home
```

Versions in case it is useful:

```
bukkit# dpkg -l | grep zfs
ii  debian-zfs                           7~wheezy                          amd64        Native ZFS filesystem metapackage for Debian.
ii  dkms                                 2.2.0.3-1.2+zfs6                  all          Dynamic Kernel Module Support Framework
ii  libzfs2                              0.6.5-3-wheezy                    amd64        Native ZFS filesystem library for Linux
ii  zfs-dkms                             0.6.5-3-wheezy                    all          Native ZFS filesystem kernel modules for Linux
ii  zfsonlinux                           6                                 all          archive.zfsonlinux.org trust package
ii  zfsutils                             0.6.5-3-wheezy                    amd64        command-line tools to manage ZFS filesystems
bukkit# uname -a
Linux bukkit 3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u3 x86_64 GNU/Linux
```

**Comment by FransUrbo** [comment] 2015-09-19 20:52
On Debian GNU/Linux (and derived distributions), have a look at <code>/etc/default/zfs</code>. Look for the <code>ZPOOL_IMPORT_PATH</code> option. There used to be the option <code>USE_DISK_BY_ID</code>, but that was removed a while ago. It still works though.

On RedHat (and derived dists), look in <code>/etc/sysconfig/zfs</code>. Gentoo: <code>/etc/conf.d/zfs</code>.

**Comment by behlendorf** [comment] 2016-10-04 05:21
This issue has been resolved.

**Closed by behlendorf** 2016-10-04 05:21 UTC
