### ISSUE TITLE
Assertion failed trying to send a snapshot

### ISSUE THREAD

**Issue by Ninpo** [zfsonlinux/zfs#4085] opened 2015-12-10 14:28 UTC
`# zpool status`
`  pool: tank`
` state: ONLINE`
`  scan: resilvered 9.94G in 0h2m with 0 errors on Thu Dec 10 10:42:10 2015`
`config:`

`        NAME        STATE     READ WRITE CKSUM`
`        tank        ONLINE       0     0     0`
`          mirror-0  ONLINE       0     0     0`
`            sdb3    ONLINE       0     0     0`
`            sda3    ONLINE       0     0     0`

`errors: No known data errors`
`# zfs list -r`
`NAME           USED  AVAIL  REFER  MOUNTPOINT`
`tank          9.86G  3.50T    19K  none`
`tank/ROOT     9.80G  3.50T  9.80G  /`
`tank/home       24K  3.50T    24K  /home`
`tank/var      58.6M  3.50T  58.4M  /var`
`tank/var/log   116K  3.50T   116K  /var/log`
`tank/var/www    20K  3.50T    20K  /var/www`

`# zfs snapshot -r tank@tank.snap1`
`# zfs list -t snapshot`
`NAME                      USED  AVAIL  REFER  MOUNTPOINT`
`tank@tank.snap1              0      -    19K  -`
`tank/ROOT@tank.snap1      168K      -  9.80G  -`
`tank/home@tank.snap1         0      -    24K  -`
`tank/var@tank.snap1          0      -  58.4M  -`
`tank/var/log@tank.snap1      0      -   116K  -`
`tank/var/www@tank.snap1      0      -    20K  -`

`# zfs send -Rv tank@tank.snap1 | gzip > /dev/null`
```zfs: libzfs_sendrecv.c:751: Assertion `0' failed.```

Line 751 of libzfs_sendrecv.c:

        if (zhp->zfs_dmustats.dds_origin[0]) {
                zfs_handle_t *origin = zfs_open(zhp->zfs_hdl,
                    zhp->zfs_dmustats.dds_origin, ZFS_TYPE_SNAPSHOT);
                if (origin == NULL)
                        return (-1);
                VERIFY(0 == nvlist_add_uint64(nvfs, "origin",
                    origin->zfs_dmustats.dds_guid));
        }

Gentoo Linux, zfs/spl version 0.6.5.3, kernel 4.3.0.

Only thing I've found to be broken so far, but snapshots are one of the reasons I'm trying ZFS out!  Doh.

**Comment by behlendorf** [comment] 2015-12-10 22:18
@Ninpo just to be clear are you seeing this failure with the version of ZFS shipped with Gentoo or with the tagged 0.6.5.3 version from zfsonlinux.org?  To help help debug this could you please build the latest version from Github and apply the following time patch.  This should cause the errno to be logged.

```
diff --git a/lib/libzfs/libzfs_sendrecv.c b/lib/libzfs/libzfs_sendrecv.c
index bd2fd29..4f8567c 100644
--- a/lib/libzfs/libzfs_sendrecv.c
+++ b/lib/libzfs/libzfs_sendrecv.c
@@ -753,7 +753,7 @@ send_iterate_fs(zfs_handle_t *zhp, void *arg)
                    zhp->zfs_dmustats.dds_origin, ZFS_TYPE_SNAPSHOT);
                if (origin == NULL)
                        return (-1);
-               VERIFY(0 == nvlist_add_uint64(nvfs, "origin",
+               VERIFY0(nvlist_add_uint64(nvfs, "origin",
                    origin->zfs_dmustats.dds_guid));
        }
 
```

**Comment by Ninpo** [comment] 2015-12-11 09:15
Hi, thanks for the reply.

I'm using the Gentoo 0.6.5.3-r1 ebuild, custom-cflags are disabled.

To make sure, do you want me to build 0.6.5.3 from releases on github or do you want me to build from master?

**Comment by behlendorf** [comment] 2015-12-11 20:50
@Ninpo please use either the master from Github or the posted 0.6.5.3 tarball from zfsonlinux.org.  Also make sure you use the newly built utilities and kernels modules when testing.  @ryao has been working on some ABI stabilization code in Gentoo and I want to rule that out as a possibility.  Plus I'm sure @ryao wants to know about any potential issues like this.

You can also easily make this change by hand if you're having trouble applying the patch.  I was expecting that would result in the errno being logged.  It looks like that's not the case in your build.  (As an aside we should probably update the code to always used our own VERIFY and not the systems so the output is predictable).

Anyway, we can just do something a little quick and dirty for debugging.  Try this.

```diff
diff --git a/lib/libzfs/libzfs_sendrecv.c b/lib/libzfs/libzfs_sendrecv.c
index bd2fd29..df9da73 100644
--- a/lib/libzfs/libzfs_sendrecv.c
+++ b/lib/libzfs/libzfs_sendrecv.c
@@ -751,10 +751,16 @@ send_iterate_fs(zfs_handle_t *zhp, void *arg)
        if (zhp->zfs_dmustats.dds_origin[0]) {
                zfs_handle_t *origin = zfs_open(zhp->zfs_hdl,
                    zhp->zfs_dmustats.dds_origin, ZFS_TYPE_SNAPSHOT);
+               int error;
                if (origin == NULL)
                        return (-1);
-               VERIFY(0 == nvlist_add_uint64(nvfs, "origin",
-                   origin->zfs_dmustats.dds_guid));
+               error = nvlist_add_uint64(nvfs, "origin",
+                   origin->zfs_dmustats.dds_guid);
+               if (error) {
+                       printf("send_iterate_fs() errno=%d origin=%llu\n",
+                           error, (u_longlong_t)origin->zfs_dmustats.dds_guid);
+                       return (-1);
+               }
        }
 
        /* iterate over props */
```

**Comment by Ninpo** [comment] 2015-12-14 11:13
That patch still throws the original error when patching against the Gentoo build, I'm building the ZFS tools by hand now, will test the send and if I get the same error, build again with the debug patch.  Info to follow..

**Comment by Ninpo** [comment] 2015-12-14 15:37
I'll have to come back to this I'm afraid, built tools/modules from tarball with above patch, rebooted (ZFS on root) and modules won't load.  Don't currently have time at work to keep playing with this with other commitments, I'll come back to it as soon as I can.

**Comment by AndCycle** [comment] 2015-12-14 16:21
@Ninpo 
so you caught this issue in Gentoo 0.6.5.3-r1 ebuild?

if it is, you could just fallback to Gentoo 0.6.5.3 ebuild, 
it use the github tarback with minor change for openrc,

r1 include quiet a lot of change that I can't even make it work.

**Comment by Ninpo** [comment] 2015-12-15 15:42
Yes it was the -r1 ebuild that won't send snapshots.

I need to reinstall OS, can't get it booted now with the modules built by hand.  I'll report back when I've had chance.  If it's fine in 0.6.5.3 ebuild I'll file a bug on b.g.o.

Thanks for your time.

**Comment by devsk** [comment] 2015-12-23 06:38
Another Gentoo user here. As luck would have it, I have run into this issue as well. Darn! Backups are broken....:(

@Ninpo: What came out of this analysis? Do I need to back out to 0.6.5.3 ebuild?

**Comment by devsk** [comment] 2015-12-23 06:46
Looks like -r1 ebuild has a large set of patches from ryao.

@ryao: is it safe to go back to 0.6.5.3 ebuild? What are all those patches for? I hope none of them are something that breaks Gentoo integration with ZoL.

**Comment by Ninpo** [comment] 2015-12-23 15:19
@devsk I still haven't had time to rebuild the server I managed to break by trying different things so I'm still not of much help I'm afraid.

Appears from the thread though that 0.6.5.3 is the version to use and a bug report should be filed on b.g.o for these patches.

I haven't a clue if simply rolling back to 0.6.5.3 will be ok though.

**Comment by devsk** [comment] 2015-12-24 20:55
@behlendorf : are you familiar with "/dev/zfs API developed by ClusterHQ"? Is there a plan to merge these into ZoL upstream?

Its a fairly large patch and I am surprised that ryao pushed this to ~amd64. This patch should be cooked here first and then released in the wild.

Basic thing like 'zfs send|recv' should never break in a ZFS setup and that's exactly what happened with -r1....:(

**Comment by devsk** [comment] 2015-12-25 03:56
I am back on 0.6.5.3 and all is well.

**Comment by smaeul** [comment] 2015-12-28 16:02
I did some testing with a flash drive, and I think I have come up with a minimal test case. This is with
sys-fs/zfs-0.6.5.3-r1::gentoo and sys-fs/zfs-kmod-0.6.5.3-r1::gentoo.

    sodium ~ # zpool create -R /mnt -O redundant_metadata=most ztest /dev/sdd 
    sodium ~ # echo 42 > /mnt/ztest/meaning_of_life
    sodium ~ # zfs snapshot ztest@snap1
    sodium ~ # zfs send -p ztest@snap1 > /dev/null 
    zfs: libzfs_sendrecv.c:751: Assertion `0' failed.
    Aborted

**Comment by behlendorf** [comment] 2015-12-28 20:27
@devsk yes the ClusterHQ changes are being worked in #3907 to iron out the issues and get feedback.  The plan is to get them merged on to OpenZFS and ZoL once they're fully baked and everyone has signed off on them.  Everyone will benefit from have a stable interface but as you can imagine there's the significant potential for subtle breakage to slip in.

These changes won't be applied to ZoL proper until we're sure all the issues have been worked though.  I'm surprised @ryao has applied them to the Gentoo packages too.  I'm not familiar with Gentoo style packaging but I would suggest keeping these changes in a different test repository so end users are aware of the increased risk.

**Comment by ryao** [comment] 2015-12-29 23:10
@behlendorf The benefits for a stable interface updates outweighed the risks, some illumos reviewers prefer to see code in production before it reaches them and all of my own tests were passing at the time. We have since found some minor issues and I intend to refresh the packaging with the latest fixes. I am looking into this one.

**Comment by ryao** [comment] 2015-12-29 23:12
@devsk I was on vacation around when you sent your message and just returned today. It is safe to downgrade, although both the kernel modules and userland tools need to be downgraded together due to a regression that was caused by a last minute bug fix before the Gentoo ebuilds were shipped. -r2 will fix that.

**Comment by alexanderhaensch** [comment] 2016-01-02 12:06
@ryao i am touched by the send/recieve assertion too. Do you have a fix already?

**Comment by ryao** [comment] 2016-01-04 17:16
@alexanderhaensch This will be fixed by today's -r2 push. Here is the patch that fixes it:

https://bpaste.net/show/d3d31f2d3b1b

**Comment by ryao** [comment] 2016-01-06 14:58
@behlendorf -r2 has been in Gentoo for 2 days. I had been able to reproduce and fix this. It should be safe to close this.

**Comment by alexanderhaensch** [comment] 2016-01-07 11:29
I can confirm that with the new patchset, the send/recieve works flawless.

**Comment by behlendorf** [comment] 2016-01-13 00:48
Great.  Closing.

**Closed by behlendorf** 2016-01-13 00:48 UTC
