### ISSUE TITLE
same data seems to be put into the L1ARC twice (two zpools)

### ISSUE THREAD

**Issue by asmo123** [zfsonlinux/zfs#6505] opened 2017-08-13 16:09 UTC
Hello, I was asked to report this.

When I copy data from a different filesystem (ext4) to the first pool and then copy the data from pool 1 to pool 2 the ARC grows twice.
It's probably easiest when I show the commands:

```
echo $((4*1024*1024*1024)) > /sys/module/zfs/parameters/zfs_arc_max
zpool create zp1 /dev/sda /dev/sde -f
zpool create zp2 /dev/sdb -f
zfs create zp1/zp1DS
zfs create zp2/zp2DS
dd if=/dev/urandom of=/mnt/gentoo/1GBfile.dd count=1024 bs=$((1*1024*1024))
ls -alh /mnt/gentoo/1GBfile.dd 
    -rw-r--r-- 1 gentoo users 1.0G Aug 13 17:38 /mnt/gentoo/1GBfile.dd

echo 3 > /proc/sys/vm/drop_caches && cat /proc/spl/kstat/zfs/arcstats | grep '^c'
    c                               4    33554432 # == 32MB
    c_min                           4    33554432
    c_max                           4    4294967296 # == 4GB
cp /mnt/gentoo/1GBfile.dd /zp1/zp1DS/
cat /proc/spl/kstat/zfs/arcstats | grep '^c '
    c                               4    919846912 # is 877 MB but should be 1GB
cp /zp1/zp1DS/1GBfile.dd /zp2/zp2DS/
cat /proc/spl/kstat/zfs/arcstats | grep '^c '
    c                               4    2156500992 # 2057 MB !!!
```

---

Distribution Name       | gentoo 
Distribution Version    | (rolling release)
Linux Kernel                 | Linux livecd 4.5.2-aufs-r1 
Architecture                 | amd64
ZFS Version                  | 0.6.5-329_g5c27b29
SPL Version                  | 0.6.5-63_g5ad98ad

**Comment by richardelling** [comment] 2017-08-13 20:54
This is not a bug. Each block in the ARC is identified as belonging to a pool. When the pool is exported, its blocks are evicted from the ARC.

**Comment by asmo123** [comment] 2017-08-13 20:58
So the ARC is not shared by pools then?

**Comment by richardelling** [comment] 2017-08-13 21:02
The ARC is shared by pools. Think of it this way: the tag for each block in the ARC includes its pool id. This is necessary because dataset ids (and others) are not globally unique. The pool id is unique, so it is needed to differentiate between blocks in pools.

**Comment by asmo123** [comment] 2017-08-13 21:28
So the space in the ARC is shared, but the data in/of a block from pool-A is and can not be available for pool-B?

cp data from ext4-partition to zpool-A
# blocks written(!?) to zpool-A are stored(?) in the ARC and labeled as "belongs to zpool-A"

cp data from zpool-A to zpool-B 
# transferred blocks are stored in the ARC and labeled as 
# read-from-A: "belongs to pool A"
# write-to-B: "belongs to pool B"

I read that the ARC does only contain blocks that was read (not written). In this scenario there was only one read (on the part of ZFS) and not two. E.g. here
http://www.c0t0d0s0.org/archives/5329-Some-insight-into-the-read-cache-of-ZFS-or-The-ARC.html

**Comment by richardelling** [comment] 2017-08-13 22:08
This is not a bug. If you would like to have a discussion, then please use the email list: zfs-discuss@list.zfsonlinux.org

**Comment by asmo123** [comment] 2017-08-13 22:10
Alright. Mark it as "invalid" please!

**Comment by DeHackEd** [comment] 2017-08-13 22:14
Based on my understanding of the original IRC-posed question, one of the diagrams in that picture shows a single block as being a member of both the LRU and LFU lists. This is likely a mistake. There are a few graphical errors as well, such as arrows without arrowheads. Also the text says "moved over to the frequently used list".

**Comment by loli10K** [comment] 2017-08-14 05:51
> Alright. Mark it as "invalid" please!

Closing.

**Closed by loli10K** 2017-08-14 05:51 UTC
