### ISSUE TITLE
Error! Bad return status for module build on kernel: 4.4.0-0.rc1.git0.1.fc24.x86_64 (x86_64)

### ISSUE THREAD

**Issue by Aikidouke** [zfsonlinux/zfs#4026] opened 2015-11-19 17:38 UTC
[k4.4.0-0.rc1_build.txt](https://github.com/zfsonlinux/zfs/files/39254/k4.4.0-0.rc1_build.txt)

Output of dkms build --force and logs + dkms install

**Comment by kernelOfTruth** [comment] 2015-11-19 23:28
https://github.com/zfsonlinux/zfs/issues/4021

**Comment by behlendorf** [comment] 2015-11-20 00:12
Right, you'll want to stick with a 4.3 or older kernel until support is added for 4.4.

**Comment by Aikidouke** [comment] 2015-11-20 02:12
Thanks, looks like I should subscribe to the mailing list. Sorry!

**Comment by kholia** [comment] 2015-11-23 19:04
[4.4-support-patch.txt](https://github.com/zfsonlinux/zfs/files/41928/4.4-support-patch.txt)

This seems to work fine with 4.4-rc2.

**Comment by colorprint** [comment] 2015-11-28 18:25
patch not works for me with 4.4-rc2 kernel:

checking whether make_request_fn() returns int... no
checking whether make_request_fn() returns void... configure: error: no - Please file a bug report at
			    https://github.com/zfsonlinux/zfs/issues/new

Building module:
cleaning build area...(bad exit status: 2)
make KERNELRELEASE=4.4.0-rc2-mainline...(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.4.0-rc2-mainline (x86_64)
Consult /var/lib/dkms/zfs/0.6.5/build/make.log for more information.

**Comment by philmmanjaro** [comment] 2015-11-30 19:40
I can confirm that this patch doesn't work for me either. Also tried with dkms.@kholia: how do you compile your modules?

**Comment by philmmanjaro** [comment] 2015-12-02 08:38
Fixed in master:

61d482f Linux 4.4 compat: xattr operations takes xattr_handler
1a09371 Linux 4.4 compat: make_request_fn returns blk_qc_t

**Comment by behlendorf** [comment] 2015-12-04 22:55
Fixed in master and we'll get the fixed applied to the next point release.

**Closed by behlendorf** 2015-12-04 22:55 UTC
Labels: Build Issue
