### ISSUE TITLE
ZFS send --raw crashes AWS instance reproducible

### ISSUE THREAD

**Issue by ronnyegner** [zfsonlinux/zfs#6512] opened 2017-08-15 11:14 UTC
### System information

Type                                | Amazon AWS t2.medium (2 cores, 4 GB memory)
  ---                                  |     --- 
Distribution Name       | Amazon Linux
Distribution Version    | 
Linux Kernel                 | 4.9.38-16.35.amzn1.x86_64
Architecture                 | x64_64
ZFS Version                  | Master (v0.7.0-29_gd49d9c2)
SPL Version                  | Master (v0.7.0-12_g9df9692)

### Describe the problem you're observing
I am playing around a bit with the recently added ZFS encryption. I have setup a small source VM at home (same versions, but Virtualbox-based VM) and a target VM at Amazon AWS (see above for versions).

On the SOURCE i created a new pool and a new dataset and copied /etc into it. 

Source data set looks like this:

```
[root@oeltest .ssh]# zfs get all testpool/encrypt
NAME              PROPERTY              VALUE                  SOURCE
testpool/encrypt  type                  filesystem             -
testpool/encrypt  creation              Tue Aug 15  4:39 2017  -
testpool/encrypt  used                  38.9M                  -
testpool/encrypt  available             94.3G                  -
testpool/encrypt  referenced            1.33M                  -
testpool/encrypt  compressratio         1.00x                  -
testpool/encrypt  mounted               yes                    -
testpool/encrypt  quota                 none                   default
testpool/encrypt  reservation           none                   default
testpool/encrypt  recordsize            128K                   default
testpool/encrypt  mountpoint            /testpool/encrypt      default
testpool/encrypt  sharenfs              off                    default
testpool/encrypt  checksum              sha512                 local
testpool/encrypt  compression           off                    default
testpool/encrypt  atime                 on                     default
testpool/encrypt  devices               on                     default
testpool/encrypt  exec                  on                     default
testpool/encrypt  setuid                on                     default
testpool/encrypt  readonly              off                    default
testpool/encrypt  zoned                 off                    default
testpool/encrypt  snapdir               hidden                 default
testpool/encrypt  aclinherit            restricted             default
testpool/encrypt  createtxg             39                     -
testpool/encrypt  canmount              on                     default
testpool/encrypt  xattr                 on                     default
testpool/encrypt  copies                1                      default
testpool/encrypt  version               5                      -
testpool/encrypt  utf8only              off                    -
testpool/encrypt  normalization         none                   -
testpool/encrypt  casesensitivity       sensitive              -
testpool/encrypt  vscan                 off                    default
testpool/encrypt  nbmand                off                    default
testpool/encrypt  sharesmb              off                    default
testpool/encrypt  refquota              none                   default
testpool/encrypt  refreservation        none                   default
testpool/encrypt  guid                  8046491042049585014    -
testpool/encrypt  primarycache          all                    default
testpool/encrypt  secondarycache        all                    default
testpool/encrypt  usedbysnapshots       0B                     -
testpool/encrypt  usedbydataset         1.33M                  -
testpool/encrypt  usedbychildren        37.6M                  -
testpool/encrypt  usedbyrefreservation  0B                     -
testpool/encrypt  logbias               latency                default
testpool/encrypt  dedup                 off                    default
testpool/encrypt  mlslabel              none                   default
testpool/encrypt  sync                  standard               default
testpool/encrypt  dnodesize             legacy                 default
testpool/encrypt  refcompressratio      1.00x                  -
testpool/encrypt  written               1.33M                  -
testpool/encrypt  logicalused           33.7M                  -
testpool/encrypt  logicalreferenced     683K                   -
testpool/encrypt  volmode               default                default
testpool/encrypt  filesystem_limit      none                   default
testpool/encrypt  snapshot_limit        none                   default
testpool/encrypt  filesystem_count      none                   default
testpool/encrypt  snapshot_count        none                   default
testpool/encrypt  snapdev               hidden                 default
testpool/encrypt  acltype               off                    default
testpool/encrypt  context               none                   default
testpool/encrypt  fscontext             none                   default
testpool/encrypt  defcontext            none                   default
testpool/encrypt  rootcontext           none                   default
testpool/encrypt  relatime              off                    default
testpool/encrypt  redundant_metadata    all                    default
testpool/encrypt  overlay               off                    default
testpool/encrypt  encryption            aes-256-gcm            -
testpool/encrypt  keylocation           prompt                 local
testpool/encrypt  keyformat             passphrase             -
testpool/encrypt  pbkdf2iters           342K                   -
testpool/encrypt  encryptionroot        testpool/encrypt       -
testpool/encrypt  keystatus             available              -
```

On the TARGET VM - which is setup brand new - i have created a new pool and trying to send testpool/encrypt from source to target crashes the machine reproducibly:

`zfs send -c --raw testpool/testenc2@snap1| ssh root@target zfs recv testpool/test`

When the crash occurs the system log shows:

`Invalid dnode block MAC`
followed by a stack trace (see attached picture)

![crash](https://user-images.githubusercontent.com/1502081/29314044-6d969bde-81bc-11e7-82e3-023b2c314496.jpg)

**Comment by tcaputi** [comment] 2017-08-15 18:16
@ronnyegner 
I am having some trouble reproducing your problem. Could you try to provide a script that causes the crash? This script seems to run without issues:

```
zpool create -f pool sdb
zpool create -f pool2 sdc
echo "password" | zfs create -o encryption=on -o keyformat=passphrase -o keylocation=prompt pool/test
cp -r /etc /pool/test
zfs snap pool/test@now
zfs send -c --raw pool/test@now | zfs recv pool2/recv
echo "password" | zfs mount -l pool2/recv
```

Is it possible you are using code from before the encryption patch was merged into master? Just before the encryption patch was merged in I fixed a problem regarding sending empty files that would trigger this kind of crash.

**Comment by tcaputi** [comment] 2017-08-15 18:19
I see from your version string that you seem to be using the correct version. Just make sure that it is the same on both the sending and receiving side.

**Comment by ronnyegner** [comment] 2017-08-16 06:40
Version on source:

```
[root@oeltest /]# cat /sys/module/zfs/version
0.7.0-29_gd49d9c2
```

Version on target:

```
[root@ip-XX-XX-XX-XX ~]# cat /sys/module/zfs/version
0.7.0-29_gd49d9c2
```

**Comment by ronnyegner** [comment] 2017-08-18 05:33
@tcaputi  I managed to reproduce the issue as follows:

On SOURCE (same ZFS version as target, VM with 1 GB memory, but under Virtualbox):

```
[root@oeltest ~]# zpool destroy testpool
[root@oeltest ~]# zpool create testpool /dev/sdb
[root@oeltest ~]# zfs set checksum=sha512 testpool
[root@oeltest ~]# zfs create -o encryption=aes-256-gcm -o keyformat=passphrase testpool/encrypt
[root@oeltest ~]# zfs create testpool/encrypt/data
[root@oeltest ~]# cp -r /etc /testpool/encrypt/data/
[root@oeltest ~]# zfs snapshot testpool/encrypt/data@snap1
```



On TARGET:

```
[root@ip-172-XX-XX-XX ~]# zpool import testpool
[root@ip-172-XX-XX-XX ~]# zpool destroy testpool
[root@ip-172-XX-XX-XX ~]# zpool create testpool /dev/xvdf
[root@ip-172-XX-XX-XX ~]# zpool list
NAME       SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
testpool  99.5G   104K  99.5G         -     0%     0%  1.00x  ONLINE  -
[root@ip-172-XX-XX-XX ~]# zfs list
NAME       USED  AVAIL  REFER  MOUNTPOINT
testpool  82.5K  96.4G    24K  /testpool
```


On SOURCE:
`zfs send -c --raw testpool/encrypt/data@snap1| ssh root@XX.XX.XX.XX zfs recv testpool/test`

**Comment by tcaputi** [comment] 2017-08-18 06:01
@ronnyegner 
I'm sorry. I'm still having trouble reproducing this..... This is the script I am running, which is basically  just your script with both pools on the same box:

```
zpool create testpool /dev/sdb
zpool create recvpool /dev/sdc
zfs set checksum=sha512 testpool
echo "password" | zfs create -o encryption=aes-256-gcm -o keyformat=passphrase testpool/encrypt
zfs create testpool/encrypt/data
cp -r /etc /testpool/encrypt/data/
zfs snapshot testpool/encrypt/data@snap1
zfs send -c --raw testpool/encrypt/data@snap1 | zfs recv recvpool/test
echo "password" | zfs mount -l recvpool/test
```

This issue should not be caused by memory configuration or distribution. Short of some strange issue where your systems are not using the latest version, but are reporting that they are I kind of don't know what to say.... This definitely looks like the issue I fixed just before the merge. You should be able to check if it is by removing all empty files from the source side before doing the send (the bug should have only effected sending empty files.

Another possibility that I just thought of is that it could be SELinux related (although this seems unlikely). Does your system use SELinux attributes?

**Comment by ronnyegner** [comment] 2017-08-18 07:28
@tcaputi 
Hi,

I am also unable to reproduce it using the SOURCE side only:

```
[root@oeltest ~]# zfs send -c --raw testpool/encrypt/data@snap1 | zfs recv testpool/recv
[root@oeltest ~]#.  <=== no crash
```

Also not when I dump the data into a file, SCP the file to TARGET and read it back:

```
[root@oeltest ~]# zfs send -c --raw testpool/encrypt/data@snap1 > /root/dump.zfs
[root@oeltest ~]# scp /root/dump.zfs root@35.157.237.109:/root/
[root@oeltest ~]# md5sum dump.zfs
70a3a9594b422178765f8d3a8ea707f8  dump.zfs
[root@oeltest ~]# zfs send -c --raw testpool/encrypt/data@snap1 > /root/dump.zfs
[root@oeltest ~]# scp /root/dump.zfs root@TARGET:/root/
[root@oeltest ~]# md5sum dump.zfs
70a3a9594b422178765f8d3a8ea707f8  dump.zfs
```




```
[root@ip-172-31-39-168 ~]# cat dump.zfs | zfs recv testpool/test2
cannot open 'testpool/test2': dataset does not exist
cannot receive new filesystem stream: dataset does not exist
[root@ip-XX-XX-XX-XX ~]# zpool import -a
[root@ip-XX-XX-XX-XX ~]# cat dump.zfs | zfs recv testpool/test2
[root@ip-XX-XX-XX-XX ~]# md5sum dump.zfs 
70a3a9594b422178765f8d3a8ea707f8  dump.zfs
```
It seems to happen only when i copy the data via SSH?

**Comment by ronnyegner** [comment] 2017-08-18 09:15
I have re-done everything:

### CLEANUP OLD VERSION ON TARGET 


```
[root@ip-XX-XX-XX-XX extra]# cd /lib/modules/`uname -r`/extra/
[root@ip-XX-XX-XX-XX extra]# ls -la
total 56
drwxr-xr-x 14 root root 4096 Aug 15 11:01 .
drwxr-xr-x  7 root root 4096 Aug 15 11:01 ..
drwxr-xr-x  2 root root 4096 Aug 15 11:01 avl
drwxr-xr-x  4 root root 4096 Aug 15 10:49 drivers
drwxr-xr-x  5 root root 4096 Aug 15 10:49 fs
drwxr-xr-x  2 root root 4096 Aug 15 11:01 icp
drwxr-xr-x  6 root root 4096 Aug 15 10:49 net
drwxr-xr-x  2 root root 4096 Aug 15 11:01 nvpair
drwxr-xr-x  2 root root 4096 Aug 15 10:54 spl
drwxr-xr-x  2 root root 4096 Aug 15 10:54 splat
drwxr-xr-x  2 root root 4096 Aug 15 11:01 unicode
drwxr-xr-x  2 root root 4096 Aug 15 11:01 zcommon
drwxr-xr-x  2 root root 4096 Aug 15 11:01 zfs
drwxr-xr-x  2 root root 4096 Aug 15 11:01 zpios
[root@ip-XX-XX-XX-XX extra]# rm -rf avl icp nvpair/ spl* zcommon/ zfs zpios unicode
[root@ip-XX-XX-XX-XX extra]# pwd
/lib/modules/4.9.38-16.35.amzn1.x86_64/extra
[root@ip-XX-XX-XX-XX extra]# uname -a
Linux ip-XX-XX-XX-XX 4.9.38-16.35.amzn1.x86_64 #1 SMP Sat Aug 5 01:39:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```


### GIT CLONE FROM TODAY ON TARGET (after reboot)

```
[root@ip-XX-XX-XX-XX ~]# date
Fri Aug 18 08:00:27 UTC 2017
[root@ip-XX-XX-XX-XX ~]# git clone https://github.com/zfsonlinux/zfs.git
Cloning into 'zfs'...
remote: Counting objects: 101585, done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 101585 (delta 3), reused 2 (delta 0), pack-reused 101562
Receiving objects: 100% (101585/101585), 38.84 MiB | 7.57 MiB/s, done.
Resolving deltas: 100% (71652/71652), done.
Checking connectivity... done.
```

```
[root@ip-XX-XX-XX-XX ~]# git clone https://github.com/zfsonlinux/spl.git
Cloning into 'spl'...
remote: Counting objects: 8731, done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 8731 (delta 8), reused 16 (delta 5), pack-reused 8701
Receiving objects: 100% (8731/8731), 3.53 MiB | 2.41 MiB/s, done.
Resolving deltas: 100% (6067/6067), done.
Checking connectivity... done.
```


Compile:
```
./autogen
./configure
Make
Make install
```


### RE-CREATE` POOL ON TARGET


```
[root@ip-XX-XX-XX-XX ~]# modprobe zfs
[root@ip-XX-XX-XX-XX ~]# zpool import -a
[root@ip-XX-XX-XX-XX ~]# zpool status 
  pool: testpool
 state: ONLINE
  scan: none requested
config:

	NAME        STATE     READ WRITE CKSUM
	testpool    ONLINE       0     0     0
	  xvdf      ONLINE       0     0     0

errors: No known data errors
[root@ip-XX-XX-XX-XX ~]# zpool destroy testpool
[root@ip-XX-XX-XX-XX ~]# zpool create testpool /dev/xvdf
```

### CHECK MODULES ON TARGET

```
[root@ip-XX-XX-XX-XX ~]# ls -latr /lib/modules/`uname -r`/extra
total 52
drwxr-xr-x  4 root root 4096 Aug 15 10:49 drivers
drwxr-xr-x  5 root root 4096 Aug 15 10:49 fs
drwxr-xr-x  6 root root 4096 Aug 15 10:49 net
drwxr-xr-x  2 root root 4096 Aug 18 08:05 spl
drwxr-xr-x  2 root root 4096 Aug 18 08:05 splat
drwxr-xr-x  2 root root 4096 Aug 18 08:14 avl
drwxr-xr-x  2 root root 4096 Aug 18 08:14 icp
drwxr-xr-x  2 root root 4096 Aug 18 08:14 nvpair
drwxr-xr-x  2 root root 4096 Aug 18 08:14 unicode
drwxr-xr-x  2 root root 4096 Aug 18 08:14 zcommon
drwxr-xr-x  2 root root 4096 Aug 18 08:14 zfs
drwxr-xr-x 13 root root 4096 Aug 18 08:14 .
drwxr-xr-x  7 root root 4096 Aug 18 08:14 ..
[root@ip-XX-XX-XX-XX ~]# date
Fri Aug 18 08:30:23 UTC 2017
```


```
[root@ip-XX-XX-XX-XX ~]# cat /sys/module/spl/version 
0.7.0-12_g9df9692
[root@ip-XX-XX-XX-XX ~]# cat /sys/module/zfs/version 
0.7.0-33_g08de8c1
```

### NEW SEND FROM TARGET

[root@oeltest ~]# cat dump.zfs | ssh TARGET zfs recv testpool/test


Boom

**Comment by ronnyegner** [comment] 2017-08-18 09:48
As a final test i have set up a new AWS instance completely from scratch using Ubuntu this time. I can also reproduce the same behavior there.

**Comment by tcaputi** [comment] 2017-08-18 20:43
I have identified the problem and am working on a fix. It should be done today or Monday.

**Closed** 2017-08-23 23:54 UTC

**Comment by ronnyegner** [comment] 2017-08-24 13:58
Confirmed. Newest changes to master solve the issue.
