### ISSUE TITLE
Broken encryption passphrase prompt in initramfs script for plymouth

### ISSUE THREAD

**Issue by belperite** [zfsonlinux/zfs#9193] opened 2019-08-21 10:53 UTC
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Debian Buster
Distribution Version	| 10
Linux Kernel	| 4.19.37-5+deb10u2
Architecture	| amd64
ZFS Version	| 0.8.1-4
SPL Version	| 0.8.1-4

### Describe the problem you're observing
When Plymouth is installed (usually as part of a display manager installation such as Lightdm), the following is displayed via ```plymouth ask-for-password```:

```
Encrypted ZFS password for rpool:***************************
cannot open ''rpool'': invalid character ''' in name
```

After the passphrase has been entered (correctly) 3 times, I get dropped to an initrd prompt and am able to manually load the key and mount the filesystem.

Prior to Lightdm/Plymouth installation, the standard TTY prompt works fine.

The problem appears to lie in _contrib/initramfs/scripts/zfs.in_ here:
```
                ENCRYPTIONROOT=$(${ZFS} get -H -o value encryptionroot "${fs}")
                DECRYPT_CMD="${ZFS} load-key '${ENCRYPTIONROOT}'"

                # If root dataset is encrypted...
                if ! [ "${ENCRYPTIONROOT}" = "-" ]; then

                        # Prompt with plymouth, if active
                        if [ -e /bin/plymouth ] && /bin/plymouth --ping 2>/dev/null; then
                                plymouth ask-for-password --prompt "Encrypted ZFS password for ${ENCRYPTIONROOT}" \
                                        --number-of-tries="3" \
                                        --command="${DECRYPT_CMD}"
```
The single quotes from DECRYPT_CMD are getting passed to plymouth literally instead of being interpreted by a shell, meaning that zfs load-key sees them as part of the filesystem name and errors out.

I've fixed this in my installation whilst preserving the general effect of the single quotes:
```
                        # Prompt with plymouth, if active
                        if [ -e /bin/plymouth ] && /bin/plymouth --ping 2>/dev/null; then
                                DECRYPT_CMD_PLYMOUTH=$(eval "echo ${DECRYPT_CMD}")
                                plymouth ask-for-password --prompt "Encrypted ZFS password for ${ENCRYPTIONROOT}" \
                                        --number-of-tries="3" \
                                        --command="${DECRYPT_CMD_PLYMOUTH}"
```
The other alternative is to just remove the single quotes from DECRYPT_CMD, but I'm not sure if this would break anything else.

As far as I can see, the systemd and TTY alternatives to entering the passphrase should still work fine with my fix. I don't use Dracut so am unable to test there unfortunately.

### Describe how to reproduce the problem

1. Install Debian using https://github.com/zfsonlinux/zfs/wiki/Debian-Buster-Encrypted-Root-on-ZFS
2. Install a display manager such as Lightdm which uses Plymouth
3. Reboot and attempt to enter ZFS passphrase

**Comment by rlaager** [comment] 2019-08-22 02:25
If you change the original code to look like this, does that work?

`--command="sh -c \"${DECRYPT_CMD}\""`

**Comment by belperite** [comment] 2019-08-22 07:51
No joy I'm afraid. Changed the script to have precisely the above and I get:

```load-key: line 1: syntax error: unterminated quoted string```

**Comment by rlaager** [comment] 2019-08-22 08:14
I took a look at the Plymouth code. It splits the command on spaces, so there really is no way for us to get proper args splitting if the pool name contains a space.

How about skipping the use of $DECRYPT_CMD altogether and just hardcoding it without the quoting? Does this sort of thing work?

```
# Plymouth splits the command on spaces, so this cannot work if ${ENCRYPTIONROOT} has spaces.
plymouth ask-for-password --prompt "Encrypted ZFS password for ${ENCRYPTIONROOT}" \
	--number-of-tries="3" \
	--command="${ZFS} load-key ${ENCRYPTIONROOT}"
```

**Comment by belperite** [comment] 2019-08-22 14:15
That did work, but only for names without spaces. With spaces, it didn't work.

I gave up trying to pass spaces in via `--command` and decided to pipe the key, and call the command directly instead (please see  #9121).

**Comment by ghfields** [comment] 2019-08-23 01:42
Duplicate #8306

**Comment by rlaager** [comment] 2019-08-23 02:27
Closing as a duplicate of #8306. Really, though, the interesting discussion will be on PR #9202 anyway.

**Closed by rlaager** 2019-08-23 02:27 UTC
