### ISSUE TITLE
Building/installing RPMs fail on Fedora 28/27

### ISSUE THREAD

**Issue by vista-** [zfsonlinux/zfs#7727] opened 2018-07-19 16:02 UTC
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Fedora 
Distribution Version	| 28 (and 27)
Linux Kernel	|  4.17.6-200.fc28 (and 4.17.6-100.fc27)
Architecture	|  x86_64
ZFS Version	|  master (0.7.9-1)
SPL Version	|  master (0.7.9-1)

### Describe the problem you're observing
I am trying to manually build the RPMs, however, rpmbuild fails with a *bus error* when installing the zfs RPM on the system. This installation failure also corrupts the entire RPM database - I am not sure whether the fault lies on ZFS or rpmbuild.

### Describe how to reproduce the problem
Clone the repository, run `autogen.sh`, followed by `./configure` and finally, `make rpm`. 

I have tested this on both my host OS (Fedora 27 Workstation) and in a freshly-installed virtual machine (Fedora 28 Minimal installation).

### Include any warning/errors/backtraces from the system logs

Build failure on Fedora 27 (same thing happens on 28):
```
Wrote: /tmp/zfs-build-xxxxxx-rPkQsvJI/SRPMS/zfs-0.7.0-1472_g2e5dc449c.fc27.src.rpm
make[1]: Leaving directory '/home/xxxxxxx/dev/zfs'
make  pkg="zfs" \
	def='--define "_without_debug 1" --define "_without_debug_kmem 1" --define "_without_debug_kmem_tracking 1" --define "_without_debuginfo 1" --define "_without_asan 1" --define "_initconfdir /etc/sysconfig"  --with systemd --define "_unitdir /usr/lib/systemd/system" --define "_presetdir /usr/lib/systemd/system-preset" --define "_generatordir /usr/lib/systemd/system-generators" ' rpm-common
make[1]: Entering directory '/home/xxxxxx/dev/zfs'
make[2]: Entering directory '/home/xxxxxx/dev/zfs'
make[2]: Leaving directory '/home/xxxxxx/dev/zfs'
Installing zfs-0.7.0-1472_g2e5dc449c.fc27.src.rpm
/bin/sh: line 13:  1003 Bus error               (core dumped) LANG=C rpmbuild --define "_tmppath $rpmbuild/TMP" --define "_topdir $rpmbuild" --define "_without_debug 1" --define "_without_debug_kmem 1" --define "_without_debug_kmem_tracking 1" --define "_without_debuginfo 1" --define "_without_asan 1" --define "_initconfdir /etc/sysconfig" --with systemd --define "_unitdir /usr/lib/systemd/system" --define "_presetdir /usr/lib/systemd/system-preset" --define "_generatordir /usr/lib/systemd/system-generators" --rebuild $rpmpkg
make[1]: *** [Makefile:1272: rpm-common] Error 1
make[1]: Leaving directory '/home/xxxxxxx/dev/zfs'
make: *** [Makefile:1231: rpm-utils] Error 2
```

RPM DB is corrupted following install:
```
[root@xxxxxxx]/home/xxxxxxx/dev/zfs# dnf
error: rpmdb: BDB0113 Thread/process 1003/140118817331392 failed: BDB1507 Thread died in Berkeley DB library
error: db5 error(-30973) from dbenv->failchk: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery
error: cannot open Packages index using db5 -  (-30973)
error: cannot open Packages database in /var/lib/rpm
Error: Error: rpmdb open failed
```

**Comment by tonyhutter** [comment] 2018-07-19 21:11
It works for me on F28:
```
spl-0.7.9 $ ./autogen && ./configure && make rpm && sudo yum localinstall *.$(uname -p).rpm *.noarch.rpm
zfs-0.7.9 $ ./autogen && ./configure && make rpm && sudo yum localinstall *.$(uname -p).rpm *.noarch.rpm
...
Installed:
  kmod-zfs-4.17.3-200.fc28.x86_64.x86_64 0.7.9-1.fc28                kmod-zfs-4.17.3-200.fc28.x86_64-debuginfo.x86_64 0.7.9-1.fc28          kmod-zfs-devel.x86_64 0.7.9-1.fc28               
  kmod-zfs-devel-4.17.3-200.fc28.x86_64.x86_64 0.7.9-1.fc28          libnvpair1.x86_64 0.7.9-1.fc28                                         libnvpair1-debuginfo.x86_64 0.7.9-1.fc28         
  libuutil1.x86_64 0.7.9-1.fc28                                      libuutil1-debuginfo.x86_64 0.7.9-1.fc28                                libzfs2.x86_64 0.7.9-1.fc28                      
  libzfs2-debuginfo.x86_64 0.7.9-1.fc28                              libzfs2-devel.x86_64 0.7.9-1.fc28                                      libzpool2.x86_64 0.7.9-1.fc28                    
  libzpool2-debuginfo.x86_64 0.7.9-1.fc28                            zfs.x86_64 0.7.9-1.fc28                                                zfs-debuginfo.x86_64 0.7.9-1.fc28                
  zfs-debugsource.x86_64 0.7.9-1.fc28                                zfs-dkms.noarch 0.7.9-1.fc28                                           zfs-dracut.x86_64 0.7.9-1.fc28                   
  zfs-kmod-debugsource.x86_64 0.7.9-1.fc28                           zfs-test.x86_64 0.7.9-1.fc28                                           zfs-test-debuginfo.x86_64 0.7.9-1.fc28           

Complete!
[hutter@fedora28 zfs-0.7.9]$ cat /etc/redhat-release 
Fedora release 28 (Twenty Eight)
[hutter@fedora28 zfs-0.7.9]$ uname -a
Linux fedora28 4.17.3-200.fc28.x86_64 #1 SMP Tue Jun 26 14:17:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

Have you tried running though these instructions?:

https://github.com/zfsonlinux/zfs/wiki/Custom-Packages

**Comment by vista-** [comment] 2018-07-19 23:40
Downloading the spl and zfs tarballs separately and building them did indeed work - but I am still not able to build it from the git master. I double-checked the required dependencies listed in the link, all of them are installed.

What I haven't really done is separately building spl... do I still have to do that in order to correctly build the ZFS RPMs? I took a look a the other repo, the README suggests that one no longer has to do that.

**Comment by Rudd-O** [comment] 2018-07-21 06:44
I can confirm:

```
/bin/sh: line 13: 25180 Segmentation fault      (core dumped) LANG=C rpmbuild --define "_tmppath $rpmbuild/TMP" --define "_topdir $rpmbuild" --define "_without_debug 1" --define "_without_debug_kmem 1" --define "_without_debug_kmem_tracking 1" --define "_without_debuginfo 1" --define "_without_asan 1" --rebuild $rpmpkg
make[1]: *** [Makefile:1272: rpm-common] Error 1
make[1]: Leaving directory '/usr/src/zfs'
make: *** [Makefile:1227: rpm-dkms] Error 2
   ERROR:          root:      install_fedora@ 962	Unexpected error
Traceback (most recent call last):
  File "zfs-fedora-installer/src/installfedoraonzfs/__init__.py", line 739, in install_fedora
    to_rmdir=to_rmdir,)
  File "zfs-fedora-installer/src/installfedoraonzfs/__init__.py", line 1254, in deploy_zfs_in_machine
    check_call(cmd)
  File "zfs-fedora-installer/src/installfedoraonzfs/cmd.py", line 30, in check_call
    return subprocess.check_call(*args,**kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['chroot', '/var/lib/zfs-fedora-installer/seed_staging_27_source_yes_yes', 'bash', '-c', 'cd /usr/src/zfs && ./autogen.sh && ./configure --with-config=user && make -j16 rpm-utils && make -j16 rpm-dkms']' returned non-zero exit status 2
Cleaning up now
```

**Comment by Rudd-O** [comment] 2018-07-21 06:44
(The host is a fully up-to-date Fedora 27 x86_64.)

**Comment by brando56894** [comment] 2018-07-23 20:21
Works for me as well on **4.17.6-200.fc28.x86_64**, but I have installed it from the repository, not compiled from Git.

**Comment by Rudd-O** [comment] 2018-07-23 22:42
It only fails during compiling it from source.  Rpmbuild segfaults (huh!?!?)

**Comment by tonyhutter** [comment] 2018-07-24 17:45
I just pulled the latest from master, and it still works for me on F28.  I'm doing `./autogen.sh && ./configure && make rpm && sudo yum localinstall *.$(uname -p).rpm *.noarch.rpm`

**Comment by vista-** [comment] 2018-07-25 07:56
That's quite odd - it seems to work for me as well now. I might have encountered another problem a bit later on - the process gets stuck on the zfs-test package now, no segfault this time. I left the "Processing zfs-test..." prompt for about 15-20 minutes and gave up after that, does that package take longer to finish?

**Comment by Rudd-O** [comment] 2018-07-26 06:51
My process also finished correctly, after I pulled from master and
merged to my personal repo.

Sooooooo weird.

**Comment by problame** [comment] 2018-10-05 20:05
> What I haven't really done is separately building spl... do I still have to do that in order to correctly build the ZFS RPMs? I took a look at the other repo, the README suggests that one no longer has to do that.

So as far as I can tell, the zfs master branch no longer requires building the spl separately.
But for the release 0.7.*, you still need to, right?

On my build setup, with tarballs 0.7.*, I can successfully build spl rpms in perpetuity.
But after 2 or 3 builds of the zfs rpms, rpmbuild hangs.
Also, any dnf / yum operations will hang until I kill the blocked rpmbuild and run ``rpmbuild --rebuild-db``.

Can anyone reproduce that?

**Comment by Rudd-O** [comment] 2019-03-10 12:05
> Update: curiously, you also cannot attach to the blocked rpmbuild using gdb. I have a suspicion that this is because Fedora gdb ships with a patch that shows which debuginfo packages to install, and that patch will probably query the RPM database, which will in turn block gdb.

Giant facepalm there on the part of the patch includers.

**Comment by behlendorf** [comment] 2019-03-12 19:51
Based on the comments it sounds like the original issue was resolved and everything is building as expected.  There may still be an issue with `rpmbuild` and multiple builds, if that's reproducible let's take it to a new issue.  Closing.

**Closed by behlendorf** 2019-03-12 19:51 UTC
Labels: Type: Building

**Comment by Rudd-O** [comment] 2019-03-21 07:28
I'm sorry but this keeps happening, even on Fedora 29, and even on non-parallel, single builds.

```
...
...
...
mangling shebang in /usr/src/zfs-0.8.0/cmd/zed/zed.d/data-notify.sh from /bin/sh to #!/usr/bin/sh
mangling shebang in /usr/src/zfs-0.8.0/cmd/zed/zed.d/scrub_finish-notify.sh from /bin/sh to #!/usr/bin/sh
mangling shebang in /usr/src/zfs-0.8.0/cmd/zed/zed.d/pool_import-led.sh from /bin/sh to #!/usr/bin/sh
mangling shebang in /usr/src/zfs-0.8.0/cmd/zed/zed.d/all-syslog.sh from /bin/sh to #!/usr/bin/sh
mangling shebang in /usr/src/zfs-0.8.0/cmd/zgenhostid/zgenhostid from /bin/bash to #!/usr/bin/bash
mangling shebang in /usr/src/zfs-0.8.0/cmd/vdev_id/vdev_id from /bin/sh to #!/usr/bin/sh
mangling shebang in /usr/src/zfs-0.8.0/cmd/fsck_zfs/fsck.zfs from /bin/sh to #!/usr/bin/sh
Processing files: zfs-dkms-0.8.0-rc3.fc29.noarch
Provides: zfs-dkms = 0.8.0-rc3.fc29 zfs-kmod = 0.8.0
Requires(interp): /bin/sh /bin/sh
Requires(rpmlib): rpmlib(CompressedFileNames) <= 3.0.4-1 rpmlib(FileDigests) <= 4.6.0-1 rpmlib(PartialHardlinkSets) <= 4.0.4-1 rpmlib(PayloadFilesHavePrefix) <= 4.0-1
Requires(post): /bin/sh
Requires(preun): /bin/sh
Obsoletes: spl-dkms
Checking for unpackaged file(s): /usr/lib/rpm/check-files /root/rpmbuild/BUILDROOT/zfs-dkms-0.8.0-rc3.fc29.x86_64
Wrote: /root/rpmbuild/RPMS/noarch/zfs-dkms-0.8.0-rc3.fc29.noarch.rpm
Executing(%clean): /bin/sh -e /var/tmp/rpm-tmp.0na9Ub
+ umask 022
+ cd /root/rpmbuild/BUILD
+ cd zfs-0.8.0
+ '[' /root/rpmbuild/BUILDROOT/zfs-dkms-0.8.0-rc3.fc29.x86_64 '!=' / ']'
+ rm -rf /root/rpmbuild/BUILDROOT/zfs-dkms-0.8.0-rc3.fc29.x86_64
+ exit 0
Executing(--clean): /bin/sh -e /var/tmp/rpm-tmp.6UxGii
+ umask 022
+ cd /root/rpmbuild/BUILD
+ rm -rf zfs-0.8.0
+ exit 0
Segmentation fault (core dumped)
# command used
# [root@roxanne zfs]# rpmbuild --rebuild zfs-dkms-0.8.0-rc3.fc29.src.rpm 
```

This is impacting all my desktop machines and my Amazon EC2 build servers.

I'm really sorry, but this must be reopened.

**Comment by Rudd-O** [comment] 2019-03-21 07:29
I have a coredump too:

```
Mar 21 07:25:41 roxanne.dragonfear systemd-coredump[27522]: Process 13082 (rpmbuild) of user 0 dumped core.
                                                            
                                                            Stack trace of thread 13082:
                                                            #0  0x00007fe8eb03e6ed __lock_freelocker_int.isra.0 (libdb-5.3.so)
                                                            #1  0x00007fe8eb03e82a __lock_id_free (libdb-5.3.so)
                                                            #2  0x00007fe8eb04caa1 __db_refresh (libdb-5.3.so)
                                                            #3  0x00007fe8eb04cfda __db_close (libdb-5.3.so)
                                                            #4  0x00007fe8eb05ec6d __db_close_pp (libdb-5.3.so)
                                                            #5  0x00007fe8eb20054e n/a (librpm.so.8)
                                                            #6  0x00007fe8eb20a349 n/a (librpm.so.8)
                                                            #7  0x00007fe8eb2365fd rpmtsCloseDB (librpm.so.8)
                                                            #8  0x00007fe8eb2374fa rpmtsFree (librpm.so.8)
                                                            #9  0x000055958c1abac1 n/a (rpmbuild)
                                                            #10 0x00007fe8ea7d0413 __libc_start_main (libc.so.6)
                                                            #11 0x000055958c1abe0e n/a (rpmbuild)
```

Will upload the core file.

**Comment by Rudd-O** [comment] 2019-03-21 07:29
```
[root@roxanne ~]# coredumpctl dump 
           PID: 13082 (rpmbuild)
           UID: 0 (root)
           GID: 0 (root)
        Signal: 11 (SEGV)
     Timestamp: Thu 2019-03-21 07:25:40 UTC (3min 56s ago)
  Command Line: rpmbuild --rebuild zfs-dkms-0.8.0-rc3.fc29.src.rpm
    Executable: /var/lib/zfs-fedora-installer/rescuebox/usr/bin/rpmbuild
 Control Group: /user.slice/user-0.slice/session-56.scope
          Unit: session-56.scope
         Slice: user-0.slice
       Session: 56
     Owner UID: 0 (root)
       Boot ID: 429cc7736c8243288e8875540dbefa64
    Machine ID: 7a503053459b45018c32faabdc8f8624
      Hostname: roxanne.dragonfear
       Storage: /var/lib/systemd/coredump/core.rpmbuild.0.429cc7736c8243288e8875540dbefa64.13082.1553153140000000.lz4
       Message: Process 13082 (rpmbuild) of user 0 dumped core.
                
                Stack trace of thread 13082:
                #0  0x00007fe8eb03e6ed __lock_freelocker_int.isra.0 (libdb-5.3.so)
                #1  0x00007fe8eb03e82a __lock_id_free (libdb-5.3.so)
                #2  0x00007fe8eb04caa1 __db_refresh (libdb-5.3.so)
                #3  0x00007fe8eb04cfda __db_close (libdb-5.3.so)
                #4  0x00007fe8eb05ec6d __db_close_pp (libdb-5.3.so)
                #5  0x00007fe8eb20054e n/a (librpm.so.8)
                #6  0x00007fe8eb20a349 n/a (librpm.so.8)
                #7  0x00007fe8eb2365fd rpmtsCloseDB (librpm.so.8)
                #8  0x00007fe8eb2374fa rpmtsFree (librpm.so.8)
                #9  0x000055958c1abac1 n/a (rpmbuild)
                #10 0x00007fe8ea7d0413 __libc_start_main (libc.so.6)
                #11 0x000055958c1abe0e n/a (rpmbuild)
Refusing to dump core to tty (use shell redirection or specify --output).
```

**Comment by Rudd-O** [comment] 2019-03-21 07:32
The RPM database is hopelessly corrupted after the crash  Only `rpmdb --rebuilddb` fixes it.  Why would `rpmbuild` need to open the database for writes?

```
[root@roxanne zfs]# rpm -Uvh libnvpair1-0.8.0-rc3.fc29.x86_64.rpm libuutil1-0.8.0-rc3.fc29.x86_64.rpm libzfs2-0.8.0-rc3.fc29.x86_64.rpm libzpool2-0.8.0-rc3.fc29.x86_64.rpm zfs-0.8.0-rc3.fc29.x86_64.rpm zfs-dkms-0.8.0-rc3.fc29.noarch.rpm zfs-dracut-0.8.0-rc3.fc29.x86_64.rpm 
error: rpmdb: BDB0113 Thread/process 13082/140638343002304 failed: BDB1507 Thread died in Berkeley DB library
error: db5 error(-30973) from dbenv->failchk: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery
error: cannot open Packages index using db5 -  (-30973)
error: cannot open Packages database in /var/lib/rpm
error: rpmdb: BDB0113 Thread/process 13082/140638343002304 failed: BDB1507 Thread died in Berkeley DB library
error: db5 error(-30973) from dbenv->failchk: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery
error: cannot open Packages index using db5 -  (-30973)
error: cannot open Packages database in /var/lib/rpm
```

**Comment by Rudd-O** [comment] 2019-03-21 07:33
Note: I would have to test this reliable reproducer on a box that does not have ZFS to see if this is a problem there.  I don't have any boxes available with that at the moment.

**Comment by kpande** [comment] 2019-03-21 07:36
please use the [zfs-discuss mailing list or IRC](http://list.zfsonlinux.org) for your support request. **this** issue is resolved, yours must be environmental. please don't flood the tracker, it produces unnecessary noise.
