### ISSUE TITLE
ZFS Diff outputs spaces in filename as \0040

### ISSUE THREAD

**Issue by TyberiusPrime** [zfsonlinux/zfs#6318] opened 2017-07-06 10:08 UTC
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Ubuntu
Distribution Version    | 16.04
Linux Kernel                 | 4.4.0-66-generic #87-Ubuntu SMP Fri Mar 3 15:29:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Architecture                 | amd64
ZFS Version                  | 0.6.5.6-0ubuntu15
SPL Version                  | 0.6.5.6-0ubuntu4

### Describe the problem you're observing
"zfs diff" mangles file names with spaces in them.
### Describe how to reproduce the problem
```sudo zfs create pool/temp
sudo zfs snapshot pool/temp@1
sudo touch "/pool/temp/A with spaces"
sudo zfs snapshot pool/temp@2
sudo zfs diff pool/temp@1 pool/temp/@2
```
Output
```+	/pool/temp/A\0040with\0040space```

Expected Output
```+	/pool/temp/A with space```

I can't make sense of the mangling - if it's 'escaping space' it would be 32 or 0x20... Is this octal of all things? Any other characters that get escaped? 

Thanks.

**Comment by TyberiusPrime** [comment] 2017-07-06 10:12
It is in the source:
```zfs/libzfs_diff.c
--
* Prints a file name out a character at a time.  If the character is
  | * not in the range of what we consider "printable" ASCII, display it
  | * as an escaped 4-digit octal value.  ASCII values less than a space
  | * are all control characters and we declare the upper end as the
  | * DELete character.  This also is the last 7-bit ASCII character.
  | * We choose to treat all 8-bit ASCII as not printable for this
  | * application.

```

So this becomes a documentation problem in 'man zfs (diff)'.
That comment should probably read 'ASCII values less or equal than a space'. as well.

**Comment by DeHackEd** [comment] 2017-07-06 10:12
This is more common than  you think and it intended to assist in machine parsing where whitespace is a separator.. See also `fstab(5)` for example.  See <a href="https://github.com/zfsonlinux/zfs/blob/master/lib/libzfs/libzfs_diff.c#L133">libzfs_diff.c</a> for the code that does the escaping.

Not a bug, operating as intended.

**Comment by GregorKopka** [comment] 2017-07-16 12:20
http://man7.org/linux/man-pages/man5/fstab.5.html
> If the name of the mount point contains spaces these can be escaped as `\040'

Two thoughts: 

- Slight difference between \040 and \0040
- should not -H be the route to take when it comes to machine parsing and spaces?

**Comment by loli10K** [comment] 2018-02-12 20:14
Duplicate of #4290

**Closed by loli10K** 2018-02-12 20:14 UTC
