### ISSUE TITLE
Data are not fully resilvered when device is re-plugged.

### ISSUE THREAD

**Issue by ab-oe** [zfsonlinux/zfs#6076] opened 2017-04-27 06:35 UTC
### System information

Type | Version/Name
-------|----------------
Distribution Name | all
Distribution Version | all
Linux Kernel | 3.10.103
Architecture | amd64
ZFS version | 0.6.5.9
SPL version | 0.6.5.9

### Describe the problem you're observing

When the resilvering process is running and device is re-plugged the resilvering process won't be restarted. Data are resilvered only partially.

Shouldn't the resilvering scan process end immediately on device removal? Or shouldn't it be restarted when reopen finds new devices available?

### Describe how to reproduce the problem

* Start writing large file to the pool when one device is not available (the file should be large enough to perform further steps).
* When some data are written plug this device back then reopen pool (amount of data should be sufficient that the resilver doesn't finish before re-plugging the device in further steps).
* When the resilvering starts unplug this device. 
* The resilver scan progress increases but no data are resilvered.
* Plug it back again and perform zpool reopen.
* The resilver is not restarted and it continues where it was at the time of putting device in ONLINE state.
* Only part of data are resilvered.

### Example

Initial pool state:

```
  pool: Pool-1
 state: ONLINE
  scan: scrub repaired 108K in 0h0m with 0 errors on Wed Apr 26 11:57:38 2017
config:

	NAME                                  STATE     READ WRITE CKSUM
	Pool-1                                ONLINE       0     0     0
	  mirror-0                            ONLINE       0     0     0
	    scsi-SQEMU_QEMU_HARDDISK_19895-3  ONLINE       0     0     0
	    scsi-SQEMU_QEMU_HARDDISK_19894-5  ONLINE       0     0     0
	  mirror-1                            ONLINE       0     0     0
	    scsi-SQEMU_QEMU_HARDDISK_19894-3  ONLINE       0     0     0
	    scsi-SQEMU_QEMU_HARDDISK_19895-2  ONLINE       0     0     0
	  mirror-2                            ONLINE       0     0     0
	    scsi-SQEMU_QEMU_HARDDISK_19895-4  ONLINE       0     0     0
	    scsi-SQEMU_QEMU_HARDDISK_19894-6  ONLINE       0     0     0
```

Before starting write operation, device is removed:

`echo 1 > /sys/block/sdh/device/delete`

Start write operation:

`dd if=/dev/urandom of=/Pools/Pool-1/file1 bs=1M count=4096`

when file has about 25% of its final size "plug" device back with:

`echo "- - -" > /sys/class/scsi_host/host1/scan`

then:
`zpool reopen Pool-1`

when the resilver starts "remove" device again:
`echo 1 > /sys/block/sdh/device/delete`

the resilver continues scan but no data are resilvered. When resilver scan is about 60% again plug device back:

`echo "- - -" > /sys/class/scsi_host/host1/scan`

and then:
`zpool reopen Pool-1`

The resilvering process is not restarted it continues at scan progress, as result it resilvers only 251M instead of ~1.3G.
The final zpool status output is:
```
  pool: Pool-1
 state: ONLINE
  scan: resilvered 251M in 0h1m with 0 errors on Wed Apr 26 15:36:58 2017
config:

	NAME                                  STATE     READ WRITE CKSUM
	Pool-1                                ONLINE       0     0     0
	  mirror-0                            ONLINE       0     0     0
	    scsi-SQEMU_QEMU_HARDDISK_19895-3  ONLINE       0     0     0
	    scsi-SQEMU_QEMU_HARDDISK_19894-5  ONLINE       0     0     0
	  mirror-1                            ONLINE       0     0     0
	    scsi-SQEMU_QEMU_HARDDISK_19894-3  ONLINE       0     0     0
	    scsi-SQEMU_QEMU_HARDDISK_19895-2  ONLINE       0     0     0
	  mirror-2                            ONLINE       0     0     0
	    scsi-SQEMU_QEMU_HARDDISK_19895-4  ONLINE       0     0     0
	    scsi-SQEMU_QEMU_HARDDISK_19894-6  ONLINE       0     0     0
errors: No known data errors
```
After running scrub on that pool:

```
  pool: Pool-1
 state: ONLINE
status: One or more devices has experienced an unrecoverable error.  An
	attempt was made to correct the error.  Applications are unaffected.
action: Determine if the device needs to be replaced, and clear the errors
	using 'zpool clear' or replace the device with 'zpool replace'.
   see: http://zfsonlinux.org/msg/ZFS-8000-9P
  scan: scrub repaired 236M in 0h1m with 0 errors on Wed Apr 26 15:47:05 2017
config:

	NAME                                  STATE     READ WRITE CKSUM
	Pool-1                                ONLINE       0     0     0
	  mirror-0                            ONLINE       0     0     0
	    scsi-SQEMU_QEMU_HARDDISK_19895-3  ONLINE       0     0     0
	    scsi-SQEMU_QEMU_HARDDISK_19894-5  ONLINE       0     0     0
	  mirror-1                            ONLINE       0     0     0
	    scsi-SQEMU_QEMU_HARDDISK_19894-3  ONLINE       0     0     0
	    scsi-SQEMU_QEMU_HARDDISK_19895-2  ONLINE       0     0 1.89K
	  mirror-2                            ONLINE       0     0     0
	    scsi-SQEMU_QEMU_HARDDISK_19895-4  ONLINE       0     0     0
	    scsi-SQEMU_QEMU_HARDDISK_19894-6  ONLINE       0     0     0
```

Scrub repaired 236M but it should repair about 1G, the data are consistent. Did the data resilvered silently during I/O or the counters lie?

**Comment by nwf** [comment] 2017-06-02 07:33
There was a bug regarding offline devices and scrubs claiming to have fixed things they did not; is it possible that this is fixed by 335b251ac1a1f8ba8434450dc0f24986bc44f688?

**Comment by ab-oe** [comment] 2017-06-02 10:06
Unfortunately, no. The scan is much faster now but when I slowed down I/O I was able to reproduce this issue. The scan should rather end immediately or resilver should restart when device is plugged back again. The zpool reopen command makes the drive ONLINE again but the resilver process continues and is not restarted. So the data on vdev are corrupted.

**Comment by behlendorf** [comment] 2017-06-02 13:42
@ab-oe thanks for the clear reproducer so we can investigate this.

**Comment by ab-oe** [comment] 2017-09-15 13:44
Could you provide me any tip where to look in code to check for this issue?

**Comment by nwf** [comment] 2017-09-15 14:40
@ab-oe The scan code is module/zfs/dsl-scan.c, but it's rather complex. :(

**Comment by loli10K** [comment] 2017-09-15 14:40
@ab-oe my suggestion would be to review any code touching DTLs and SPA async tasks; there seems to be a race condition somewhere. I've been investigating this for the past few weeks without, unfortunately, having the time to fully commit to it.

**Comment by ab-oe** [comment] 2017-09-18 08:13
@loli10K thank you. With the latest ZoL code it is much harder to reproduce because resilvering stops almost immediately after detaching disk. Now I remove two disks at once, reattach them, and then remove only one.

The test below gives me 100% reproducibility of this issue on the latest master:

```
dd if=/dev/urandom of=/Pool-0/file1 bs=1M count=10240

sleep 1

echo 1 > /sys/block/sdc/device/delete
echo 1 > /sys/block/sde/device/delete

sleep 180

echo "- - -" > /sys/class/scsi_host/host0/scan
zpool reopen Pool-0

sleep 10
echo 1 > /sys/block/sdc/device/delete
sleep 20
echo "- - -" > /sys/class/scsi_host/host0/scan
zpool reopen Pool-0
```

The data on the sdc is not fully resilvered.

**Comment by ab-oe** [comment] 2017-09-22 07:18
I was trying to look deep inside the code to find the root of this issue, but then I found something in zfs_ioctl.c
```
	/*
	 * If a resilver is already in progress then set the
	 * spa_scrub_reopen flag to B_TRUE so that we don't restart
	 * the scan as a side effect of the reopen. Otherwise, let
	 * vdev_open() decided if a resilver is required.
	 */
	spa->spa_scrub_reopen = dsl_scan_resilvering(spa->spa_dsl_pool);
```
This is the root of issue that the second reopen bring the device online but doesn't restart the resilver. I saw the origin of this modification https://www.illumos.org/issues/3129 but is that logic correct? Shouldn't it rather check if there is a new device available with dirty data and then restart resilvering?
When I modified test code and replaced ```reopen``` to ```online``` everything works as expected. New device is attached and resilver is restarted so there are no unresilvered gaps in data.
```
dd if=/dev/urandom of=/Pool-0/file1 bs=1M count=10240 &

sleep 1

echo 1 > /sys/block/sdc/device/delete
echo 1 > /sys/block/sde/device/delete

sleep 180

echo "- - -" > /sys/class/scsi_host/host0/scan
zpool online Pool-0 scsi-SQEMU_QEMU_HARDDISK_23647-5
zpool online Pool-0 scsi-SQEMU_QEMU_HARDDISK_23647-3
sleep 10

echo 1 > /sys/block/sdc/device/delete
sleep 20

echo "- - -" > /sys/class/scsi_host/host0/scan
zpool online Pool-0 scsi-SQEMU_QEMU_HARDDISK_23647-5
```

**Comment by behlendorf** [comment] 2017-09-22 19:14
@ab-oe thanks for pointing this out.  I've opened #6668 which I brings the behavior inline with what I think most users expect.  Specifically, if a vdev needs to be rebuilt it should be rebuilt even if that means restarting an in progress resilver.  An exception is left for when the pool is actively scrubbing.  It would be great if you could independently verify this change in behavior.

**Comment by ab-oe** [comment] 2017-09-25 06:39
@behlendorf Thank you, I confirm that it works with your patch. I couldn't reproduce the issue when the data are inconsistent on re-plugged devices. However, I'm concerned about the logic for scrub. It should be documented that if user execute reopen while scrub is running and there are devices that needs to be resilvered they will contain inconsistent data.

**Comment by nwf** [comment] 2017-09-25 06:47
@ab-oe My understanding of @behlendorf's change is that a scrub will continue only when the re-plugged device lacks a DTL (and so is believed *not* to contain inconsistent data).  If there is a DTL, then `vdev_open` will call for a resilver (and will so restart any ongoing scrub or resilver).  Before, it would not have, because the "are we reopening for a scrub" flag would have been erroneously set when a resilver (as opposed to scrub) was in progress.

**Comment by ab-oe** [comment] 2017-09-25 07:01
@nwf the scrub won't be restarted even if re-plugged device has a DTL. If the ```spa->spa_scrub_reopen``` flag is set the resilver won't be restarted. Only executing ```zpool online``` operation on this device will "change" the scrub operation to resilver.

**Comment by nwf** [comment] 2017-09-25 07:06
@ab-oe: the `spa->spa_scrub_reopen` flag is, after #6668, set to the result of `dsl_scan_scrubbing` (rather than `dsl_scan_resilvering`).  This function returns `B_TRUE` only when `scn->scn_phys.scn_func == POOL_SCAN_SCRUB`, which means that it will return `B_FALSE` when instead a resilver is in progress (i.e. when `scn_func` is `POOL_SCAN_RESILVER`).  Thus, a resilver (unlike a scrub) is not justification to set `spa->spa_scrub_reopen` to `B_TRUE`.

I *believe* that means "if user execute reopen while scrub is running and there are devices that needs to be resilvered they will contain inconsistent data" is false.  What am I missing?

**Comment by ab-oe** [comment] 2017-09-25 07:34
@nwf as you said the ```spa->spa_scrub_reopen``` flag is set (```B_TRUE```) when the scan type is scrub and when it is set the ```zpool reopen``` won't restart the running scan. The running scan will be restarted only when the scan type is resilver. Look at the code below:

```
dd if=/dev/urandom of=/Pool-0/file1 bs=1M count=10240

echo 1 > /sys/block/sdc/device/delete
zpool scrub
sleep 30
echo "- - -" > /sys/class/scsi_host/host0/scan
zpool reopen
```
After the ```zpool reopen``` the sdc  is put online, the scrub continues, but no data are resilvered on the sdc. When the scrub ends the sdc contains inconsistent data. After executing the ```zpool reopen``` again the data are being resilvered.

**Comment by nwf** [comment] 2017-09-25 07:39
Hazarding a guess, there are no writes in the interval between `echo 1 > /sys/block/sdc/device/delete` and `echo "- - -" > /sys/class/scsi_host/host0/scan`, and so the device has no DTL, so there is no need to resilver it?  If you mean to run the dd in the background, so that it's writing during the interval in which `/dev/sdc` is unavailable, then I think this is no longer an issue with the scrub code but with *creating* the DTLs in the first place.

**Comment by ab-oe** [comment] 2017-09-25 07:44
@nwf yes, the dd is running in the background (another console). There is dirty time log created correctly because device is resilvered after the second ```zpool reopen``` when the scrub is finished.

**Comment by behlendorf** [comment] 2017-09-25 18:48
With the small change I proposed the resilver will not be started if a scrub is already running on the pool, [here's the block of code]( https://github.com/zfsonlinux/zfs/blob/master/module/zfs/vdev.c#L1448) which is responsible.  My understanding is that this was the original intent and this behavior never got clearly documented in the man page.  Since `zpool reopen` is a relatively rarely used command it was never a big problem.

Rather than what I've suggested, which is something of a half measure, I think the right thing to do here is to add a flag to `zpool reopen` and clearly document it.  The default behavior should be safe and have it always trigger the rebuild when there's a DTL.  When the flag is set the `zpool reopen` and fetch the updated device information without triggering the rebuild which is a useful thing to be able to do.

**Comment by nwf** [comment] 2017-09-25 18:55
@behlendorf If I understand @ab-oe's comments above, it also looks like `vdev_resilver_needed` might be returning `B_FALSE` for a longer while than might be expected.  It seems like that would need to be true for the `zpool reopen` command to leave a scrub running after `sdc` was offline for 30 seconds.

Separately, when do you think it is useful to have the device open and online and not fully caught up (or catching up by DTL-indicated rebuild)?

@ab-oe Just for my own curiosity's sake, could you add a printout of `spa->spa_scrub_reopen` and `vdev_resilver_needed(vd, NULL, NULL)` just before https://github.com/zfsonlinux/zfs/blob/master/module/zfs/vdev.c#L1453 and re-run your reproducer?

**Comment by behlendorf** [comment] 2017-09-25 19:06
> when do you think it is useful to have the device open and online.

The original motivation I believe is when you want to run `zpool reopen` but there is a running resilver which is already a large fraction of the way through rebuilding a device.  In this case, it would be nice to be able to run `zpool reopen` without forcing the a potentially long running rebuild to restart from the beginning.  That said, I doubt this is a particularly common thing to want to do which is why I don't think it should be the default behavior.

**Comment by nwf** [comment] 2017-09-25 19:19
@behlendorf Ah.  Is there any way to schedule the "second resilver" after the completion of the current one?  It seems like a dubious state in which to leave the system, with a HEALTHY pool and a vdev with a DTL.

**Comment by behlendorf** [comment] 2017-09-25 19:29
@nwf there's no technical reason there couldn't be, but the code needed to queue up pending resilvers doesn't exist today.

**Comment by ab-oe** [comment] 2017-09-26 06:29
> @behlendorf If I understand @ab-oe's comments above, it also looks like vdev_resilver_needed might be returning B_FALSE for a longer while than might be expected. It seems like that would need to be true for the zpool reopen command to leave a scrub running after sdc was offline for 30 seconds.

The code won't reach the ```vdev_resilver_needed``` in https://github.com/zfsonlinux/zfs/blob/master/module/zfs/vdev.c#L1453 if the the ```spa->spa_scrub_reopen``` is B_TRUE. There is **and** not **or** in the code. 

> @ab-oe Just for my own curiosity's sake, could you add a printout of spa->spa_scrub_reopen and vdev_resilver_needed(vd, NULL, NULL) just before https://github.com/zfsonlinux/zfs/blob/master/module/zfs/vdev.c#L1453 and re-run your reproducer?

Sure, here you are:
```
[  538.772115] scsi 0:0:0:5: Direct-Access     QEMU     QEMU HARDDISK    2.5+ PQ: 0 ANSI: 5
[  538.775469] sd 0:0:0:5: Attached scsi generic sg2 type 0
[  538.775480] scst: Attached to scsi0, channel 0, id 0, lun 5, type 0
[  538.775532] sd 0:0:0:5: [sdc] 41943041 512-byte logical blocks: (21.5 GB/20.0 GiB)
[  538.775679] sd 0:0:0:5: [sdc] Write Protect is off
[  538.775682] sd 0:0:0:5: [sdc] Mode Sense: 63 00 00 08
[  538.775711] sd 0:0:0:5: [sdc] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[  538.881079]  sdc: sdc1 sdc9
[  538.882904] sd 0:0:0:5: [sdc] Attached SCSI disk
[  544.052677] spa->spa_scrub_reopen: 1, vdev_resilver_needed: 1
[  544.053226] spa->spa_scrub_reopen: 1, vdev_resilver_needed: 0
[  544.053851] spa->spa_scrub_reopen: 1, vdev_resilver_needed: 0
[  544.053875] spa->spa_scrub_reopen: 1, vdev_resilver_needed: 0
[  544.064365] spa->spa_scrub_reopen: 1, vdev_resilver_needed: 0
[  544.064398] spa->spa_scrub_reopen: 1, vdev_resilver_needed: 1
[  544.064407] spa->spa_scrub_reopen: 1, vdev_resilver_needed: 1
```
```
zpool status
  pool: pool
 state: ONLINE
status: One or more devices has experienced an unrecoverable error.  An
	attempt was made to correct the error.  Applications are unaffected.
action: Determine if the device needs to be replaced, and clear the errors
	using 'zpool clear' or replace the device with 'zpool replace'.
   see: http://zfsonlinux.org/msg/ZFS-8000-9P
  scan: scrub in progress since Tue Sep 26 08:25:59 2017
	468M scanned out of 811M at 20.4M/s, 0h0m to go
	42K repaired, 57.74% done
config:

	NAME        STATE     READ WRITE CKSUM
	pool        ONLINE       0     0     0
	  mirror-0  ONLINE       0     0     0
	    sdb     ONLINE       0     0     0
	    sdc     ONLINE       0     0     1  (repairing)
	  mirror-1  ONLINE       0     0     0
	    sdd     ONLINE       0     0     0
	    sde     ONLINE       0     0     0
```

**Comment by behlendorf** [comment] 2017-09-26 20:35
@ab-oe @nwf I'm happy to help review and proposed changes if one of you would like to take a stab at this.

**Comment by ab-oe** [comment] 2017-09-27 08:31
@behlendorf I can implement solution with parameter that allows to perform ```zpool reopen``` without triggering resilver when the scrub is running.

**Comment by ab-oe** [comment] 2017-10-09 12:39
@behlendorf I committed proposed solution. Could you review it, please? I pushed wrong branch by mistake and it is visible here, the correct one is 01ccc13. I have overwritten it but the changes are still visible. Is there any possibility to remove it to avoid confusion?

**Comment by behlendorf** [comment] 2017-10-10 18:44
@ab-oe thanks, will review.

**Closed** 2017-10-26 19:26 UTC
