### ISSUE TITLE
Script zfs-functions missing from generated .deb packages, causes kernel panic

### ISSUE THREAD

**Issue by ReimuHakurei** [zfsonlinux/zfs#7904] opened 2018-09-14 03:18 UTC
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Ubuntu Server
Distribution Version	| 18.04.1
Linux Kernel	| 4.15.0-34-generic
Architecture	| amd64
ZFS Version	| 0.8.0-rc1

### Describe the problem you're observing

When building DEB packages of ZFSonLinux with 'make deb', the script 'zfs-functions' does not end up in any of the generated DEB files.

At the very least, this results in a kernel panic when attempting to boot, if you are using a ZFS root filesystem. I would imagine it probably breaks other stuff too, but have not tested this.

The file does get generated in the source tree at ./etc/init.d/zfs-functions. Manually copying this to /etc/zfs/ (which is where Ubuntu expects it) allows the system to boot and function normally.

Modifying the DEB file to manually place this file in /etc/zfs/ also results in a package that installs and works correctly.

### Describe how to reproduce the problem

Compile ZFS, then run 'make deb'. Attempt to use the generated packages.

### Include any warning/errors/backtraces from the system logs

N/A

**Comment by ghfields** [comment] 2019-01-30 19:53
@ColinIanKing This seems like something you fix distro side.  Is there something that can be done here in the upstream that can help everyone?

**Comment by mtippmann** [comment] 2019-02-04 22:15
Could this bug be added back to the 0.8.0 milestone? This breaks updating to 0.8.0 via the tarballs here if you run Debian/Ubuntu and use ZFS as root filesystem. 

This comes totally as a surprive as the zfs-initramfs package is installed and update-initramfs works fine. 

Most users of the packages are likely building dkms packages and some are also using initramfs - even if it's not officially recommend/supported - including this script avoiding breakage would be nice :)

**Comment by ReimuHakurei** [comment] 2019-02-04 22:23
For what it's worth, I'm currently building some functional packages for my personal use on all of my systems, so I'll post a link here when I'm done with that.

**Comment by mtippmann** [comment] 2019-02-04 23:33
If anyone has this problem and access to serial console or something similiar: Add `break=premount`to linux cmdline in bootloader and you can then add the file i.e. pasting with  `cat <<'EOF'>>/etc/zfs/zfs-functions` however over ipmi SoL pasting the whole file did break, but it worked in smaller pieces. 

Adding the file to `/etc/zfs/zfs-functions` works you can check with `lsinitramfs initrd.img | grep zfs`

**Comment by cwedgwood** [comment] 2019-05-21 17:43
How does this work on rpm based systems?

A quick build and inspection of the generated `.rpms` I don't see the `/etc/zfs/zfs-functions` there either.

**Comment by mtippmann** [comment] 2019-05-21 20:50
@cwedgwood rpm-based systems use dracut - that is probably completly different? In this case the file is missing from the zfs-initramfs package and is not included in the initramfs - but there is a dedicated dracut package that might work different - so maybe the problem is debian only? Also the contents of the rpm do not matter, it's only the initrd contents that need to work correctly.

**Comment by cwedgwood** [comment] 2019-05-23 06:04
@mtippmann yeah, that makes sense ... i did a very quick hack to show some thoughts on what might make sense so people can comment, it almost certainly needs some tweaks/fixes before it's ready

**Comment by mtippmann** [comment] 2019-05-23 09:12
@cwedgwood thanks for taking care of this!

**Comment by dreamcat4** [comment] 2019-07-25 12:39
Yep... This made my zfs boot install unbootable today. While trying to upgrade from ubuntu's inbuilt `0.7.12` to `0.8.1` Kernel panics now. Without having that file there.

Tried booting back to the previous kernel but same issue.

**Comment by ColinIanKing** [comment] 2019-07-25 12:45
OK, to be clear,  zfs-functions should be copied to /etc/zfs is the fix? I can add that to the ubuntu zfs packaging now.

**Comment by Deltik** [comment] 2019-07-25 12:47
Yes, @ColinIanKing, having `zfs-functions` copied to `/etc/zfs` on the target system fixes this issue.

**Comment by ColinIanKing** [comment] 2019-07-25 13:16
FYI: The Ubuntu packaging for zfsutls-linux 0.8.1 already copies this file to /etc/zfs, the debian/zfsutils-linux.install performs this at the installation stage.

**Comment by Deltik** [comment] 2019-07-25 13:19
@ColinIanKing: Ubuntu's packaging never had this issue, as far as I know.  The issue is with the `.deb` files built by `make deb` in this project.

**Comment by ColinIanKing** [comment] 2019-07-25 13:22
Ah, apologies for my misunderstanding. Sorry for the noise.

**Comment by c0d3z3r0** [comment] 2019-08-01 17:07
This should be fixed by #9089. @ReimuHakurei could you test that, please?

**Comment by ReimuHakurei** [comment] 2019-08-01 19:05
That looks like it would probably fix it, but it's been a while since I built packages so I'll have to double-check. I'll give it a whirl tomorrow.

**Comment by ReimuHakurei** [comment] 2019-08-03 09:14
That PR actually throws a compilation error when I run 'make deb' on my system, saying zfs-functions and etc/default/zfs can't be found.

**Comment by c0d3z3r0** [comment] 2019-08-03 09:48
@ReimuHakurei Unfortunately I lost my crystal ball... *scnr* Can you share your build log, please? What debian release?

**Comment by ReimuHakurei** [comment] 2019-08-05 07:58
The full log is quite large, but here's the relevant part:

```
[ -x ./scripts/zfs-tests.sh ] && \
    ./scripts/zfs-tests.sh -c
make[5]: Entering directory '/tmp/zfs-build-acingram-dl7bLSTg/BUILD/zfs-0.8.0'
make[5]: Nothing to be done for 'install-exec-am'.
make  install-data-hook
make[6]: Entering directory '/tmp/zfs-build-acingram-dl7bLSTg/BUILD/zfs-0.8.0'
make[6]: Nothing to be done for 'install-data-hook'.
make[6]: Leaving directory '/tmp/zfs-build-acingram-dl7bLSTg/BUILD/zfs-0.8.0'
make[5]: Leaving directory '/tmp/zfs-build-acingram-dl7bLSTg/BUILD/zfs-0.8.0'
make[4]: Leaving directory '/tmp/zfs-build-acingram-dl7bLSTg/BUILD/zfs-0.8.0'
make[3]: Leaving directory '/tmp/zfs-build-acingram-dl7bLSTg/BUILD/zfs-0.8.0'
make[2]: Leaving directory '/tmp/zfs-build-acingram-dl7bLSTg/BUILD/zfs-0.8.0'
+ find /tmp/zfs-build-acingram-dl7bLSTg/BUILDROOT/zfs-0.8.0-1.x86_64/usr/local/lib -name *.la -exec rm -f {} ;
+ /usr/lib/rpm/brp-compress
+ /usr/lib/rpm/brp-strip /usr/bin/strip
+ /usr/lib/rpm/brp-strip-static-archive /usr/bin/strip
+ /usr/lib/rpm/brp-strip-comment-note /usr/bin/strip /usr/bin/objdump
Processing files: zfs-0.8.0-1.x86_64
error: File not found: /tmp/zfs-build-acingram-dl7bLSTg/BUILDROOT/zfs-0.8.0-1.x86_64/usr/local/etc/zfs/zfs-functions
error: File not found: /tmp/zfs-build-acingram-dl7bLSTg/BUILDROOT/zfs-0.8.0-1.x86_64/etc/default/zfs


RPM build errors:
    File not found: /tmp/zfs-build-acingram-dl7bLSTg/BUILDROOT/zfs-0.8.0-1.x86_64/usr/local/etc/zfs/zfs-functions
    File not found: /tmp/zfs-build-acingram-dl7bLSTg/BUILDROOT/zfs-0.8.0-1.x86_64/etc/default/zfs
Makefile:1335: recipe for target 'rpm-common' failed
make[1]: *** [rpm-common] Error 1
make[1]: Leaving directory '/home/acingram/zfs-test/zfs'
Makefile:1294: recipe for target 'rpm-utils' failed
make: *** [rpm-utils] Error 2
```

**Comment by ReimuHakurei** [comment] 2019-08-05 14:37
Also likely related: the zfs-function script doesn't seem to actually get built. It's compiled from a file named zfs-functions.in, which has some paths that get filled in to it. I just compiled 0.8.1 stock from source to update my .debs I install on my systems, and had to do that manually because that file wasn't ever built during compilation.

**Comment by c0d3z3r0** [comment] 2019-08-05 15:58
> The full log is quite large, but here's the relevant part:

I ***really*** need the full log to check this. You can upload text files to Github, so please do ;)

> Also likely related: the zfs-function script doesn't seem to actually get built. It's compiled from a file named zfs-functions.in, which has some paths that get filled in to it. I just compiled 0.8.1 stock from source to update my .debs I install on my systems, and had to do that manually because that file wasn't ever built during compilation.

My PR fixes that.

**Comment by ReimuHakurei** [comment] 2019-08-05 16:41
[out.log](https://github.com/zfsonlinux/zfs/files/3468539/out.log)

Try that.

**Comment by c0d3z3r0** [comment] 2019-08-05 18:16
@ReimuHakurei thanks, I'll have a look at this

**Comment by c0d3z3r0** [comment] 2019-08-05 18:54
@ReimuHakurei I can't reproduce this. Even the tests are all fine, see https://github.com/zfsonlinux/zfs/pull/9089.

this line confuses me....

~~~
Installing zfs-0.8.0-1.src.rpm
~~~

There is no commit hash... just to be sure... you tried to build this one https://github.com/zfsonlinux/zfs/pull/9089, right?

Which are your configure flags?

**Comment by ReimuHakurei** [comment] 2019-08-06 01:20
Yeah, I did it from that PR. No configure flags.

I'll nuke the directory tree and try it on a clean tree again.

**Comment by ReimuHakurei** [comment] 2019-08-06 02:35
Alright, I nuked the entire tree and restarted from scratch. This time it built DEBs but zfs-functions is not in the zfs DEB it builds.

I used the commands from this build guide, just like I always do when building ZFS:

https://github.com/zfsonlinux/zfs/wiki/Building-ZFS

Exact sequence of build commands that I ran:

```
git clone https://github.com/c0d3z3r0/zfs.git
cd zfs
git checkout for-upstream/initramfs_fixes
sh autogen.sh
./configure
make -s -j$(nproc)
make deb
```

So either I'm an idiot (which is quite possible), or there's still something broken there. Also, the files it generates are labeled 0.8.0-1 still, not 0.8.1-1.

**Comment by c0d3z3r0** [comment] 2019-08-06 05:40
Hmm... I will check this again later on a fresh Ubuntu Server instance. Maybe that‘s makes a difference

**Comment by c0d3z3r0** [comment] 2019-08-06 12:47
@ReimuHakurei I just reworked the rpm spec again. Could you do another test, please?

**Comment by ReimuHakurei** [comment] 2019-08-11 02:00
I just built DEBs and did a test install with ZFS root in a virtual machine, and it did boot and appear to function. The generated packages still have the dependencies being broken, but I'm not sure anything can be done about that as long as they're being translated from RPMs with alien.

**Comment by c0d3z3r0** [comment] 2019-08-11 07:56
Great, thanks for testing!

**Closed** 2019-08-16 15:02 UTC
Labels: Type: Building
