### ISSUE TITLE
zfs 0.6.4: cannot reduce arc usage, and [arc_adapt] cpu usage

### ISSUE THREAD

**Issue by ghost** [zfsonlinux/zfs#3290] opened 2015-04-14 06:58 UTC
Hi.

A day ago I upgrade zfs to 0.6.4 (from 0.6.3, using 'zpool upgrade' command), and noticed, that:

**I can't disable or reduce usage (read ops) of arc-cache for filesystems**:
(server running MySQL, so, i don't need arc-cache because of InnoDB buffer pool):
```
#zfs get primarycache
zroot                 primarycache  none          local
zroot/mysql-binlog    primarycache  none          inherited from zroot
zroot/mysql-dataset   primarycache  none          local
zroot/mysql-relaylog  primarycache  none          local
```
```
#arcstat.py 1
    time  read  miss  miss%  dmis  dm%  pmis  pm%  mmis  mm%  arcsz     c  
12:16:43     0     0      0     0    0     0    0     0    0    72M   64M  
12:16:44  1.2K  1.1K     95  1.1K   95     0    0   839   94    71M   64M  
12:16:45   420   379     90   379   90     0    0   169   80    71M   64M  
12:16:46   916   911     99   911   99     0    0   695   99    71M   64M  
12:16:47  1.9K  1.8K     95  1.8K   95     0    0  1.5K   94    85M   64M  
12:16:48  5.4K  5.2K     95  5.2K   95     0    0  5.0K   95   117M   64M  
12:16:49  2.5K  2.3K     92  2.3K   92     0    0  1.8K   90    77M   64M  
```
If i set primarycache=all, nothing changes:
```
zroot                 primarycache  all           local
zroot/mysql-binlog    primarycache  all           local
zroot/mysql-dataset   primarycache  all           local
zroot/mysql-relaylog  primarycache  all           local
```
```
#arcstat.py 1
    time  read  miss  miss%  dmis  dm%  pmis  pm%  mmis  mm%  arcsz     c
12:26:55   321   172     53   172   53     0    0   121   67    75M   64M  
12:26:56  1.0K   437     42   437   42     0    0   245   71    80M   64M  
12:26:57  2.0K  1.1K     53  1.1K   53     0    0   854   63   111M   64M  
12:26:58  1.4K  1.2K     90  1.2K   90     0    0   933   93    90M   64M  
12:26:59  1.3K   808     61   808   61     0    0   618   80    78M   64M  
12:27:00   402   231     57   231   57     0    0   176   64    78M   64M  
12:27:01  1.0K   544     52   544   52     0    0   305   77    74M   64M  
```

**ZFS kernel thread [arc_adapt] began consume more cpu, that on 0.6.3, up to 100% of one core:**

```
PID USER PR  NI   VIRT    RES       %CPU %MEM     TIME+ S COMMAND
322 root 0 -20    0.0m   0.0m        75.7      0.0  74:13.86 R arc_adapt          
```

I use perf(1) utility for some profiling of this thread:
```
arc_adapt perf:
4108 
4109   31.02%  [kernel]          [k] _raw_spin_lock
4110   10.76%  [kernel]          [k] mutex_unlock
4111   10.74%  [kernel]          [k] _raw_spin_unlock
4112    9.39%  [kernel]          [k] mutex_lock
4113    4.25%  [kernel]          [k] super_cache_scan
```

Seems, like most part of time it spent in active locks.

**So, my questions:**
- Is there new behavior (or, probably, bug...), that I cannot change usage (num of read ops) arc-cache via 'primarycache' property?
- Why [arc_adapt] in 0.6.4 consume more cpu than in 0.6.3?

Thanks in advance!

P.S.:
```
OS:
ArchLinux, 3.19.3-3-ARCH #1 SMP PREEMPT Wed Apr 8 14:10:00 CEST 2015 x86_64 GNU/Linux

ZFS module:
filename:       /lib/modules/3.19.3-3-ARCH/extra/zfs/zfs.ko.gz
version:        0.6.4-1
license:        CDDL
author:         OpenZFS on Linux
description:    ZFS
srcversion:     6189308C5B9F92C2EE5B9F0
```
ZFS installed from [demz-repo-core]:
zfs-git 0.6.4_r0_gd07a163_3.19.3_3-1

**Comment by kernelOfTruth** [comment] 2015-04-14 19:51
not 100% sure what you're trying to achieve but:

https://blogs.oracle.com/realneel/entry/mysql_innodb_zfs_best_practices
(blog not accessible)

>One of the cool things about talking about MySQL performance with ZFS is that there is not much >tuning to be done :-) Tuning with ZFS is considered evil, but a necessity at times. In this blog I will >describe some of the tunings that you can apply to get better performance with ZFS as well as >point out performance bugs which when fixed will nullify the need for some of these tunings.
>
>For the impatient, here is the summary. See below for the reasoning behind these >recommendations and some gotchas.
>
>1. Match ZFS recordsize with Innodb page size (16KB for Innodb Datafiles, and 128KB for Innodb log files).
>2. If you have a write heavy workload, use a Seperate ZFS Intent Log.
>3. If your database working set size does not fit in memory, you can get a big boost by using a SSD as L2ARC.
>4. While using storage devices with battery backed caches or while comparing ZFS with other filesystems, turn off the cache flush.
>5. Prefer to cache within MySQL/Innodb over the ZFS Adaptive replacement cache (ARC).
>6. Disable ZFS prefetch.
>7. Disable Innodb double write buffer.

if you want to limit ARC

do it via

zfs_arc_max
zfs_arc_meta_limit

**Comment by angstymeat** [comment] 2015-04-14 23:43
I think what @theairkit is referring to is that primarycache seems to have no affect anymore. If I clear the ARC, then set primarycache=none (and secondarycache=none) and run my rsync backups, my ARC grows anyway.

**Comment by theairkit** [comment] 2015-04-15 04:30
@kernelOfTruth , of course, I already set best (I think) settings for Mysql/innoDB:
1.
**recordsize=16k** //for dataset
**recordsize=128k** //for binlog/relaylog
**ashift=12** //for pool

2.
I don't use zil, because my pool built on sdd (RAID1, 2 x SSD Intel S3500)

3.
I limit arc-cache (/etc/modprobe.d/zfs.conf):
**options zfs zfs_arc_min=1 zfs_arc_max=67108865** //64Mb - minimal value, I can set, it hardcoded in sources:
less -N ./module/zfs/arc.c 
```
   4115          * Allow the tunables to override our calculations if they are
   4116          * reasonable (ie. over 64MB)
   4117          */
   4118         if (zfs_arc_max > 64<<20 && zfs_arc_max < physmem * PAGESIZE)
   4119                 arc_c_max = zfs_arc_max;
   4120         if (zfs_arc_min > 0 && zfs_arc_min <= arc_c_max)
   4121                 arc_c_min = zfs_arc_min;
```
4.
I set 'primarycache' and 'secondarycache' properties to 'none' for all filesystems on host.
<br>
Why in this setup i see lots of readings from arc-cache and I can't manage it using 'primarycache' property?..
Maybe, I misunderstood, how arc works, or, maybe, it bug in zfs?...
Thanks in advance!

**Comment by kernelOfTruth** [comment] 2015-04-15 14:45
@theairkit 

When reading about mysql, or the other databases *DIRECT_IO* comes to mind but I'm sure ZFSonLinux doesn't support it yet

https://github.com/zfsonlinux/zfs/issues/224

https://blogs.oracle.com/paulie/entry/deploying_mysql_with_the_oracle

also mentions it

You could try tinkering with the vdev settings e.g. mentioned at (not those values): 

http://serverfault.com/questions/622946/disabling-cache-on-zfsonlinux?answertab=votes#tab-top

and disable prefetch - not sure if that would be such a good idea performance-wise


Performance-wise you could take a look at https://github.com/zfsonlinux/zfs/pull/2865 if the preferred transaction or block sizes aren't supported yet

if I remember I read about a few settings that reduce ARC memory usage and/or consumption for not that huge systems

I'll see if I can get access to those, 

currently I'm posting from within Windows


I admit, that looks weird - thanks @angstymeat for making that clearer

**Comment by tuxoko** [comment] 2015-04-22 15:43
@theairkit 
I suggest that you increase arc limit a bit, few megabytes for example, and see if the result would get better.
The thing is that the kernel will pin some metadata when it's in use, so if you set the arc limit too low, the metadata it self might explode the arc cache. And when the arc_adapt see that arc is full, it will try hard to purge it, but it cannot because those are pinned by the kernel.

**Comment by tuxoko** [comment] 2015-04-22 15:48
@angstymeat 
Cache is for repeated data access, while I imagine rsync doesn't do much repeated data access. So if you run rsync when the cache is cold, there's no susprise that miss rate is high.

**Comment by angstymeat** [comment] 2015-04-22 19:56
@tuxoko, the results I get with with primarycache=none and primarycache=all are quite different. With it set to all or metadata I get a miss rate of around 5%. With it set to none, I get a miss rate >98%.

That would be expected because one is caching, the other isn't. What I'm saying is that with primarycache=none the metadata cache continues to grow anyway.

**Comment by theairkit** [comment] 2015-04-29 04:58
@behlendorf , may you clarify my case?
- I set arc size to minimal (64M); in my case big arc cache don't need: server running MySQL and I want to avoid double buffering (innodb buffer pool already contains all neccesary data for reads)
```
zfs_arc_min=1 zfs_arc_max=67108865
```
- regardless of the value of property 'primarycache' (none, metedata, all), I see lots of reading from arc-cache (stats below - 'primarycache=none'): 
```
time  read  miss  miss%  dmis  dm%  pmis  pm%  mmis  mm%  arcsz     c
10:32:23  1.3K  1.3K     96  1.3K   96     0    0   928   95    81M   64M  
10:32:24   432   412     95   412   95     0    0   336   94    74M   64M  
10:32:25   611   565     92   565   92     0    0   265   85    79M   64M  
10:32:26   632   618     97   618   97     0    0   340   96    79M   64M  
10:32:27   346   302     87   302   87     0    0   197   81    73M   64M  
10:32:28   765   708     92   708   92     0    0   467   89    76M   64M  
```
I suppose, that if read ops always going through arc, in case of small arc size and lots of reading, read ops may be longer, than in case of direct read from fs, and [arc_adapt] consume lot of cpu. And in case of 'primarycache=none' I expected to see zero reads from arc...

**Is it known behavior of zfs? May I reduce reading from arc this case?**
**[arc_adapt] thread consume up to 80-100% cpu time: is it expected behaviour in this case?**
**Is a bottleneck for zfs read perfomance - case, when [arc_adapt] consume 100% cpu?**

Thanks in advance!

**Comment by behlendorf** [comment] 2015-04-29 16:33
> I see lots of reading from arc-cache 

From the data you posted it looks like you're seeing _some_ cache hits in the ARC.  But personally I wouldn't describe a 3-8% cache hit rate as a lot of cache hits.  Keep in mind that the ARC in also used to cache some internal ZFS objects and not just file data.  Setting it too low can result in a lot of additional reads from disk.

There is a developer tool which allows you to get a detailed view of exactly what's in the ARC at any given moment.  Try running `dbufstat.py` it will dump a list of objects which are at least partially cached in the ARC.  You might also want to try running the `arc_summary.py` utility to get a high level view of how the ARC is behaving.  If you post the output from both these scripts to the issue we'll have a much better idea of exactly what's happening.

As for the arc_adapt thread consuming 80-100% of the CPU that's probably a consequence of limiting the ARC to such a small fraction of memory.  The thread is responsible for keeping the arc size under the target 'c'.  From the data you posted above it looks like it's unable to do so which is causing it to spend a lot of CPU time scavenging for blocks it can drop.  Notice that `arcsz` exceeds `c` in the output you posted.  I'd actually suggest increasing the ARC slightly, it's trying to help you.

**Comment by dweeezil** [comment] 2015-04-29 16:42
I also wanted to point out that for the use case of having the user application, MySQL innodb, perform its own caching, it's still recommended to use ```primarycache=metadata```.  If the database is of any substantial size, you most certainly want the ZFS metadata which refers to the innodb files to be cached.  Otherwise, I'd expect the performance to be terrible.

**Comment by behlendorf** [comment] 2016-10-12 01:59
Closing.  This is working as designed.

**Closed by behlendorf** 2016-10-12 01:59 UTC
Labels: Performance
