### ISSUE TITLE
zfs-0.7.0-1.el7_3.x86_64 missing /usr/share/man/man8/zpool.8.gz

### ISSUE THREAD

**Issue by voxnihil** [zfsonlinux/zfs#6430] opened 2017-07-30 17:50 UTC
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  CentOS Linux
Distribution Version    | 7.3.1611 (Core)
Linux Kernel                 | 3.10.0-514.26.2.el7.x86_64
Architecture                 | x86_64
ZFS Version                  |  0.7.0-1
SPL Version                  |  0.7.0-1

### Problem:
zfs-0.7.0-1.el7_3.x86_64 missing /usr/share/man/man8/zpool.8.gz

### Reproduce:
```
man zpool
No manual entry for zpool
$ rpm -ql zfs | grep -e 'man./zpool' -e 'man./zfs'
/usr/share/man/man5/zfs-events.5.gz
/usr/share/man/man5/zfs-module-parameters.5.gz
/usr/share/man/man5/zpool-features.5.gz
/usr/share/man/man8/zfs.8.gz
```

**Comment by loli10K** [comment] 2017-07-30 17:54
Likely duplicate of https://github.com/zfsonlinux/zfs/issues/6409, already fixed in https://github.com/zfsonlinux/zfs/commit/e0031d86b760c548c52cc10718c96e0aeeaa24e4.

**Comment by DeHackEd** [comment] 2017-07-30 17:56
While true, I think it's serious enough to warrant an interim release to correct it.

**Closed** 2017-07-30 18:06 UTC

**Comment by behlendorf** [comment] 2017-07-30 18:52
That's the plan.  We're just delaying slightly to see if [anything else](https://github.com/zfsonlinux/zfs/projects/10) comes up we need to address.
