### ISSUE TITLE
Sequential file rewrite outside of block boundaries is dead slow

### ISSUE THREAD

**Issue by dechamps** [zfsonlinux/zfs#361] opened 2011-08-12 07:38 UTC
(This was originally posted on the `zfs-discuss` mailing list.)

Let me demonstrate:

    # zpool create -f homez sdab sdac sdad sdae

Now let's create a 20 GB file in the pool.

    # dd if=/dev/zero of=/homez/zero bs=1048576 count=20480
    20480+0 records in
    20480+0 records out
    21474836480 bytes (21 GB) copied, 52.6104 s, 408 MB/s

High throughput, as expected. Let's rewrite this file using a 128 KB buffer size:

    # dd if=/dev/zero of=/homez/zero bs=131072 count=163840 conv=notrunc
    163840+0 records in
    163840+0 records out
    21474836480 bytes (21 GB) copied, 60.5479 s, 355 MB/s

Still high throughput, no issue here. Now, the same thing using a 64 KB buffer size:

    # dd if=/dev/zero of=/homez/zero bs=65536 count=327680 conv=notrunc
    327680+0 records in
    327680+0 records out
    21474836480 bytes (21 GB) copied, 812.825 s, 26.4 MB/s

That's *13 times* slower. Argh.

Here's an `iostat` during the 128 KB rewrite test:

                   capacity     operations    bandwidth
    pool        alloc   free   read  write   read  write
    ----------  -----  -----  -----  -----  -----  -----
    homez       20.8G  1.07T      2  3.16K   142K   391M
    homez       20.8G  1.07T      3  3.15K   206K   389M
    homez       20.9G  1.07T     13  2.87K   833K   351M
    homez       20.9G  1.07T     15  2.80K   999K   347M
    homez       20.0G  1.07T     14  2.25K   896K   262M
    homez       20.0G  1.07T     12  1.79K   781K   193M
    homez       20.0G  1.07T      6  2.28K   410K   267M
    homez       20.8G  1.07T     16  2.47K  1.00M   301M
    homez       20.9G  1.07T     19  2.79K  1.19M   345M
    homez       20.9G  1.07T     15  2.86K   948K   349M

And during the 64 KB rewrite test:

                   capacity     operations    bandwidth
    pool        alloc   free   read  write   read  write
    ----------  -----  -----  -----  -----  -----  -----
    homez       20.3G  1.07T    202    237  25.3M  25.7M
    homez       20.3G  1.07T    201    236  25.2M  25.6M
    homez       20.3G  1.07T    203    218  25.4M  25.3M
    homez       20.3G  1.07T    199    217  24.9M  25.3M
    homez       20.2G  1.07T    206    216  25.9M  25.0M
    homez       20.3G  1.07T    196    224  24.6M  26.0M
    homez       20.3G  1.07T    203    212  25.4M  24.6M
    homez       20.2G  1.07T    201    218  25.2M  25.3M
    homez       20.3G  1.07T    200    218  25.1M  25.3M

Note that Solaris 10 Update 10 exhibits the same problem, so it is present in the original ZFS. I did some other tests which led me to the following conclusion:

*When rewriting a file, and the beginning and end of each individual write request is not aligned with a ZFS block boundary, then performance will drop dramatically.*

Synchronous write speed is worse, even with a fast SSD as a separate log device.

Now, this issue wouldn't surprise me for random writes, but I don't expect such behavior for a purely sequential workload. What's interesting is that `iostat` shows high read activity when this happens. That's probably what's causing the performance drop, especially if the reads are random.

I can see why ZFS needs to read a block if it needs to be partially rewritten (checksuming, etc.) but I would expect it to do at least some kind of write coalescing for sequential writes. This way ZFS could "know" that a block is, in fact, going to be entirely rewritten and that there is no need to read it. Right now it seems ZFS is not smart enough to do this.

This is a *big* issue when storing VM disk images on ZFS, because VMs write on sector (512 byte) boundaries, not ZFS block boundaries. This basically means that once the disk file has expanded to its final size, sequential write performance inside the VM becomes absolutely terrible.

I did some digging using DTrace on the Solaris machine. It seems the best candidates for triggering reads are `dmu_tx_check_ioerr()` and `dbuf_will_dirty()`. The culprit is that these functions are called as part of `zfs_write()`, which means they will get called for each write request.

Merging writes in `zfs_write()` doesn't seem like an easy thing to do, so here's another idea: instead of calling these functions for each write request, call them when syncing the TXG. Given that all pending writes go into the TXG, this seems like the perfect place to go over the pending writes, merge them, read what needs to be read, then sync the TXG. Not only would this eliminate most of the read requests, but it would also make the remaining reads more efficient: indeed, by sorting read requests we can optimize disk head movement.

Bug #290 seems to be caused by this issue.

**Comment by kernelOfTruth** [comment] 2015-03-03 18:40
suggested patch/fix:

Hi,
This problem occurs on Freebsd, Here is a patch trying to fix the issue
The cause is under high memory pressure zfs will wrongly evict cached metadata in prior to data during rewrite.

People who experience the same issue might be interested.



James Pan


http://lists.open-zfs.org/pipermail/developer/2015-January/001222.html

?

**Comment by behlendorf** [comment] 2016-10-05 01:45
Closing.  While not fixed commit 755065f has been shown to significant help with these workloads.

**Closed by behlendorf** 2016-10-05 01:45 UTC
Labels: Difficulty - Medium, Performance
