### ISSUE TITLE
txg_sync and zfs stuck while doing a zfs send/recv on the same pool

### ISSUE THREAD

**Issue by sigxcpu76** [zfsonlinux/zfs#3966] opened 2015-10-28 20:31 UTC
I've attempted a zfs send from a zvol piped to a zfs recv in the same pool

```console
zones/vms/vm-700-disk-1@sync | zfs recv zones/vms/vm-701-disk-1
```

The destination volume seems to be created but everything is stuck.

```console
zfs list -rt all | grep "vm-7"                                                                                                   Wed Oct 28 22:31:10 EET 2015
zones/vms/vm-700-disk-1                                        493M  2.32T   493M  -
zones/vms/vm-700-disk-1@sync                                      0      -   493M  -
zones/vms/vm-701-disk-1                                           0  2.32T      0  -
```

Debian Jessie, ZoL 0.6.5.2, kernel 4.2.3-1-pve

```
[434614.327962] INFO: task txg_sync:6392 blocked for more than 120 seconds.
[434614.335593]       Tainted: P           O    4.2.3-1-pve #1
[434614.341920] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[434614.350896] txg_sync        D ffff8807d1a96a00     0  6392      2 0x00000000
[434614.350906]  ffff880f4b52baa8 0000000000000046 ffff8807ce2f3200 ffff880f42a97080
[434614.350910]  ffff880f4b52bad8 ffff880f4b52c000 ffff8807d1a96a00 7fffffffffffffff
[434614.350913]  ffff88036c893388 0000000000000001 ffff880f4b52bac8 ffffffff818036a7
[434614.350919] Call Trace:
[434614.350930]  [<ffffffff818036a7>] schedule+0x37/0x80
[434614.350940]  [<ffffffff818068b1>] schedule_timeout+0x201/0x2a0
[434614.350951]  [<ffffffff810bd012>] ? __wake_up_common+0x52/0x90
[434614.350957]  [<ffffffff8101e1d9>] ? read_tsc+0x9/0x10
[434614.350964]  [<ffffffff81802c9b>] io_schedule_timeout+0xbb/0x140
[434614.351028]  [<ffffffffc0b5e520>] ? zio_taskq_member.isra.6+0x80/0x80 [zfs]
[434614.351039]  [<ffffffffc025ffea>] cv_wait_common+0xba/0x140 [spl]
[434614.351043]  [<ffffffff810bd6c0>] ? wait_woken+0x90/0x90
[434614.351051]  [<ffffffffc02600c8>] __cv_wait_io+0x18/0x20 [spl]
[434614.351101]  [<ffffffffc0b60790>] zio_wait+0x120/0x200 [zfs]
[434614.351142]  [<ffffffffc0b04bde>] spa_sync+0x72e/0xb40 [zfs]
[434614.351146]  [<ffffffff810bd6d6>] ? autoremove_wake_function+0x16/0x40
[434614.351191]  [<ffffffffc0b1653a>] txg_sync_thread+0x3ea/0x6a0 [zfs]
[434614.351195]  [<ffffffff8101e809>] ? sched_clock+0x9/0x10
[434614.351241]  [<ffffffffc0b16150>] ? txg_delay+0x180/0x180 [zfs]
[434614.351249]  [<ffffffffc025b07a>] thread_generic_wrapper+0x7a/0x90 [spl]
[434614.351255]  [<ffffffffc025b000>] ? __thread_exit+0x20/0x20 [spl]
[434614.351259]  [<ffffffff8109ac0a>] kthread+0xea/0x100
[434614.351263]  [<ffffffff8109ab20>] ? kthread_create_on_node+0x1f0/0x1f0
[434614.351266]  [<ffffffff81807bdf>] ret_from_fork+0x3f/0x70
[434614.351269]  [<ffffffff8109ab20>] ? kthread_create_on_node+0x1f0/0x1f0
[434614.351314] INFO: task zfs:14016 blocked for more than 120 seconds.
[434614.358514]       Tainted: P           O    4.2.3-1-pve #1
[434614.364838] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[434614.373814] zfs             D ffff880f6f6d6a00     0 14016      1 0x00000004
[434614.373818]  ffff88055c0f3018 0000000000000086 ffff8807ce2f5780 ffff880f48b17080
[434614.373821]  0000000000000246 ffff88055c0f4000 00000000009c809d ffff880f49d3cac8
[434614.373833]  0000000000000000 ffff880f4b5d84c0 ffff88055c0f3038 ffffffff818036a7
[434614.373838] Call Trace:
[434614.373843]  [<ffffffff818036a7>] schedule+0x37/0x80
[434614.373851]  [<ffffffffc025bd60>] taskq_wait_id+0x60/0xb0 [spl]
[434614.373855]  [<ffffffff810bd6c0>] ? wait_woken+0x90/0x90
[434614.373890]  [<ffffffffc0acabc0>] ? dmu_send_impl+0x560/0x560 [zfs]
[434614.373927]  [<ffffffffc0acabc0>] ? dmu_send_impl+0x560/0x560 [zfs]
[434614.373967]  [<ffffffffc0b05b13>] spa_taskq_dispatch_sync+0x93/0xd0 [zfs]
[434614.374003]  [<ffffffffc0aca081>] dump_bytes+0x51/0x70 [zfs]
[434614.374023]  [<ffffffffc0ab2370>] ? arc_buf_remove_ref+0x150/0x150 [zfs]
[434614.374051]  [<ffffffffc0aca641>] dump_write+0x211/0x230 [zfs]
[434614.374079]  [<ffffffffc0acc920>] backup_cb+0x4d0/0x830 [zfs]
[434614.374108]  [<ffffffffc0aced1c>] traverse_visitbp+0x42c/0x950 [zfs]
[434614.374136]  [<ffffffffc0acc721>] ? backup_cb+0x2d1/0x830 [zfs]
[434614.374143]  [<ffffffffc02589af>] ? spl_kmem_alloc+0xaf/0x190 [spl]
[434614.374148]  [<ffffffffc02589af>] ? spl_kmem_alloc+0xaf/0x190 [spl]
[434614.374154]  [<ffffffffc02589af>] ? spl_kmem_alloc+0xaf/0x190 [spl]
[434614.374182]  [<ffffffffc0acee66>] traverse_visitbp+0x576/0x950 [zfs]
[434614.374211]  [<ffffffffc0acee66>] traverse_visitbp+0x576/0x950 [zfs]
[434614.374239]  [<ffffffffc0acee66>] traverse_visitbp+0x576/0x950 [zfs]
[434614.374269]  [<ffffffffc0acfa8f>] traverse_dnode+0x7f/0xe0 [zfs]
[434614.374297]  [<ffffffffc0acf04f>] traverse_visitbp+0x75f/0x950 [zfs]
[434614.374326]  [<ffffffffc0acee66>] traverse_visitbp+0x576/0x950 [zfs]
[434614.374354]  [<ffffffffc0acee66>] traverse_visitbp+0x576/0x950 [zfs]
[434614.374383]  [<ffffffffc0acee66>] traverse_visitbp+0x576/0x950 [zfs]
[434614.374411]  [<ffffffffc0acee66>] traverse_visitbp+0x576/0x950 [zfs]
[434614.374440]  [<ffffffffc0acee66>] traverse_visitbp+0x576/0x950 [zfs]
[434614.374469]  [<ffffffffc0acee66>] traverse_visitbp+0x576/0x950 [zfs]
[434614.374498]  [<ffffffffc0acfa8f>] traverse_dnode+0x7f/0xe0 [zfs]
[434614.374526]  [<ffffffffc0acef37>] traverse_visitbp+0x647/0x950 [zfs]
[434614.374555]  [<ffffffffc0acf3e0>] traverse_impl+0x1a0/0x410 [zfs]
[434614.374582]  [<ffffffffc0acabc0>] ? dmu_send_impl+0x560/0x560 [zfs]
[434614.374611]  [<ffffffffc0acc450>] ? dmu_recv_end_check+0x220/0x220 [zfs]
[434614.374640]  [<ffffffffc0acf6a2>] traverse_dataset+0x52/0x60 [zfs]
[434614.374668]  [<ffffffffc0acc450>] ? dmu_recv_end_check+0x220/0x220 [zfs]
[434614.374696]  [<ffffffffc0acaa6a>] dmu_send_impl+0x40a/0x560 [zfs]
[434614.374725]  [<ffffffffc0accf61>] dmu_send_obj+0x171/0x1e0 [zfs]
[434614.374773]  [<ffffffffc0b3a879>] zfs_ioc_send+0xe9/0x2c0 [zfs]
[434614.374780]  [<ffffffffc02588db>] ? strdup+0x3b/0x60 [spl]
[434614.374828]  [<ffffffffc0b3ec1b>] zfsdev_ioctl+0x44b/0x4f0 [zfs]
[434614.374832]  [<ffffffff811ddd7f>] ? kmem_cache_alloc+0x18f/0x200
[434614.374838]  [<ffffffff81210de4>] do_vfs_ioctl+0x2c4/0x4a0
[434614.374841]  [<ffffffff81211039>] SyS_ioctl+0x79/0x90
[434614.374844]  [<ffffffff818077b2>] entry_SYSCALL_64_fastpath+0x16/0x75
[434614.374848] INFO: task zfs:14017 blocked for more than 120 seconds.
[434614.382049]       Tainted: P           O    4.2.3-1-pve #1
[434614.388369] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[434614.397345] zfs             D ffff880f6f616a00     0 14017      1 0x00000004
[434614.397349]  ffff88069e14f988 0000000000000082 ffff8807ce2f0c80 ffff880f48b12580
[434614.397357]  0000000000000202 ffff88069e150000 ffff8807cafdb220 ffff8807cafdb248
[434614.397360]  ffff8807cafdb2e0 0000000000000000 ffff88069e14f9a8 ffffffff818036a7
[434614.397366] Call Trace:
[434614.397370]  [<ffffffff818036a7>] schedule+0x37/0x80
[434614.397380]  [<ffffffffc0260039>] cv_wait_common+0x109/0x140 [spl]
[434614.397390]  [<ffffffff810bd6c0>] ? wait_woken+0x90/0x90
[434614.397405]  [<ffffffffc0260085>] __cv_wait+0x15/0x20 [spl]
[434614.397451]  [<ffffffffc0b15d69>] txg_wait_synced+0xe9/0x130 [zfs]
[434614.397479]  [<ffffffffc0acb280>] ? dmu_recv_begin_sync+0x3d0/0x3d0 [zfs]
[434614.397516]  [<ffffffffc0af1784>] dsl_sync_task+0x174/0x260 [zfs]
[434614.397545]  [<ffffffffc0acaeb0>] ? restore_read+0x150/0x150 [zfs]
[434614.397573]  [<ffffffffc0acb280>] ? dmu_recv_begin_sync+0x3d0/0x3d0 [zfs]
[434614.397601]  [<ffffffffc0acaeb0>] ? restore_read+0x150/0x150 [zfs]
[434614.397630]  [<ffffffffc0acd5fc>] dmu_recv_begin+0x1cc/0x1e0 [zfs]
[434614.397678]  [<ffffffffc0b3fe8c>] zfs_ioc_recv+0x17c/0xc20 [zfs]
[434614.397685]  [<ffffffffc0448a1b>] ? zprop_name_to_prop+0x4b/0x80 [zcommon]
[434614.397695]  [<ffffffffc02612d4>] ? tsd_set+0x154/0x460 [spl]
[434614.397717]  [<ffffffffc0ab8a46>] ? dbuf_rele+0x36/0x40 [zfs]
[434614.397756]  [<ffffffffc0afb054>] ? rrw_exit+0x64/0x160 [zfs]
[434614.397792]  [<ffffffffc0aea979>] ? dsl_pool_rele+0x29/0x30 [zfs]
[434614.397795]  [<ffffffff811de84f>] ? __kmalloc+0x1bf/0x260
[434614.397801]  [<ffffffffc02588db>] ? strdup+0x3b/0x60 [spl]
[434614.397850]  [<ffffffffc0b3ec1b>] zfsdev_ioctl+0x44b/0x4f0 [zfs]
[434614.397855]  [<ffffffff81210de4>] do_vfs_ioctl+0x2c4/0x4a0
[434614.397858]  [<ffffffff81211039>] SyS_ioctl+0x79/0x90
[434614.397862]  [<ffffffff818077b2>] entry_SYSCALL_64_fastpath+0x16/0x75
```

**Comment by sigxcpu76** [comment] 2015-10-28 20:51
Happens after a fresh reboot, too.

**Comment by Gregy** [comment] 2015-11-05 18:46
Exactly the same thing happens to me too on Debian Jessie.
'''
ZFS: Loaded module v0.6.4-1.1-1, ZFS pool version 5000, ZFS filesystem version 5
'''
'''
Linux bc-dev-k2 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04) x86_64 GNU/Linux
'''

It worked perfectly fine on the same pool before upgrade from v0.6.4-1.1-1

**Comment by Gregy** [comment] 2015-11-05 19:04
Setting
```
options spl spl_taskq_thread_dynamic=0
```
in /etc/modprobe.d/spl.conf works around the issue so I think this is duplicate of #3872

**Comment by behlendorf** [comment] 2015-11-19 22:22
Yes, this is almost certainly a duplicate of #3872.

A fix was merged to master for this which allows dynamic taskqs to remain enabled, see zfsonlinux/spl@f5f2b87. Otherwise, you can safely use 0.6.5.3 which resolves this issue by disabling dynamic taskqs by default.

**Closed by behlendorf** 2015-11-19 22:22 UTC
