### ISSUE TITLE
zfs receive fails receiving a deduplicated stream "invalid backup stream"

### ISSUE THREAD

**Issue by pyavdr** [zfsonlinux/zfs#2210] opened 2014-03-25 11:49 UTC
"zfs receive" fails when receiving a deduplicated stream with snapshots with "invalid backup stream"
When the stream isn´t deduplicated it runs smooth.
To be sure, i patched another pool (part2 of this issue)  with the newest pull request from @dweeezil (Recent illumos/Delphix features #2149) but the problem persists.

Linux Suse122 3.7.7-2-default #1 SMP Wed Feb 13 09:33:05 UTC 2013 (d55bd47) x86_64 x86_64 x86_64 GNU/Linux
ZFS: Loaded module v0.6.2-219_ga15dac4, ZFS pool version 5000, ZFS filesystem version 5
SPL: Loaded module v0.6.2-23_g4c99541

NAME                       USED  AVAIL  REFER  MOUNTPOINT
stor2/zfstest             4.67G   102G  4.67G  /stor2/zfstest
stor2/zfstest3            49.9G   102G  49.8G  /stor2/zfstest3
stor2/zfstest3@394806312   736K      -   768K  -
stor2/zfstest3@421188256   976K      -  1.94G  -
stor2/zfstest3@484463391   992K      -  4.26G  -
stor2/zfstest3@618833865  1.28M      -  7.45G  -
stor2/zfstest3@579117221  1.41M      -  9.58G  -
stor2/zfstest3@516414280  1.54M      -  12.8G  -
stor2/zfstest3@967496177  1.68M      -  16.0G  -
stor2/zfstest3@636523150  1.77M      -  18.2G  -
stor2/zfstest3@672405261  1.87M      -  20.5G  -
stor2/zfstest3@949169779  1.99M      -  23.1G  -
stor2/zfstest3@688080912  2.33M      -  25.8G  -
stor2/zfstest3@522831668  2.91M      -  28.5G  -
stor2/zfstest3@493854542  3.20M      -  31.1G  -
stor2/zfstest3@151707443  3.32M      -  33.8G  -
stor2/zfstest3@194586695  3.46M      -  36.4G  -
stor2/zfstest3@493432740  3.58M      -  39.1G  -
stor2/zfstest3@144417120  3.68M      -  41.7G  -
stor2/zfstest3@138155230  3.80M      -  44.4G  -
stor2/zfstest3@122410522  3.98M      -  47.0G  -
stor2/zfstest3@967710983  1.86M      -  49.7G  -
stor2/zfstest3@now            0      -  49.8G  -

Suse122:/stor2/zfstest # zfs send -R -D stor2/zfstest3@now > /stor2/zfstest/test.zfs
Suse122:/stor2/zfstest # zfs destroy -r stor2/zfstest3

Suse122:/stor2/zfstest # zfs recv -v stor2/zfstest3 < /stor2/zfstest/test.zfs
receiving full stream of stor2/zfstest3@394806312 into stor2/zfstest3@394806312
received 2.11MB stream in 5 seconds (432KB/sec)
receiving incremental stream of stor2/zfstest3@421188256 into stor2/zfstest3@421188256
received 249MB stream in 14 seconds (17.8MB/sec)
receiving incremental stream of stor2/zfstest3@484463391 into stor2/zfstest3@484463391
cannot receive incremental stream: invalid backup stream

Linux linux-ts3r 3.11.10-7-desktop #1 SMP PREEMPT Mon Feb 3 09:41:24 UTC 2014 (750023e) x86_64 x86_64 x86_64 GNU/Linux
ZFS: Loaded module v0.6.2-201_g8eac9fb, ZFS pool version 5000, ZFS filesystem version 5
SPL: Loaded module v0.6.2-23_g4c99541

linux-ts3r:/etc # zpool get all
NAME  PROPERTY                    VALUE                       SOURCE
tank  size                        496G                        -
tank  capacity                    0%                          -
tank  altroot                     -                           default
tank  health                      ONLINE                      -
tank  guid                        8224401125096643018         default
tank  version                     -                           default
tank  bootfs                      -                           default
tank  delegation                  on                          default
tank  autoreplace                 off                         default
tank  cachefile                   -                           default
tank  failmode                    wait                        default
tank  listsnapshots               off                         default
tank  autoexpand                  off                         default
tank  dedupditto                  0                           default
tank  dedupratio                  1.00x                       -
tank  free                        496G                        -
tank  allocated                   126K                        -
tank  readonly                    off                         -
tank  ashift                      0                           default
tank  comment                     -                           default
tank  expandsize                  0                           -
tank  freeing                     0                           default
tank  feature@async_destroy       enabled                     local
tank  feature@empty_bpobj         enabled                     local
tank  feature@lz4_compress        enabled                     local
tank  feature@spacemap_histogram  active                      local
tank  feature@enabled_txg         active                      local
tank  feature@hole_birth          active                      local
tank  feature@extensible_dataset  enabled                     local
tank  feature@bookmarks           enabled                     local

NAME                      USED  AVAIL  REFER  MOUNTPOINT
tank                     49.8G   438G    32K  /tank
tank/zfstest               47K   438G    47K  /tank/zfstest
tank/zfstest2            49.8G   438G  49.8G  /tank/zfstest2
tank/zfstest2@300726135   242K      -  2.24G  -
tank/zfstest2@296730124   470K      -  4.81G  -
tank/zfstest2@224726639   771K      -  7.39G  -
tank/zfstest2@902427907   908K      -  9.98G  -
tank/zfstest2@540759649  1.07M      -  12.6G  -
tank/zfstest2@255536517  1.49M      -  15.1G  -
tank/zfstest2@199845779  1.62M      -  17.7G  -
tank/zfstest2@566124845  1.74M      -  20.3G  -
tank/zfstest2@956409770  1.87M      -  22.8G  -
tank/zfstest2@037434686  2.14M      -  25.5G  -
tank/zfstest2@301863766  2.63M      -  28.1G  -
tank/zfstest2@725218939  2.92M      -  30.7G  -
tank/zfstest2@694801830  3.06M      -  33.2G  -
tank/zfstest2@643148554  3.20M      -  35.9G  -
tank/zfstest2@492741743  3.33M      -  38.5G  -
tank/zfstest2@243681899  3.46M      -  41.1G  -
tank/zfstest2@659482439  3.59M      -  43.7G  -
tank/zfstest2@999733757  3.75M      -  46.2G  -
tank/zfstest2@921130344  3.69M      -  48.9G  -

linux-ts3r:/tank/zfstest # zfs snap tank/zfstest2@now
linux-ts3r:/tank/zfstest # zfs send -R -D  tank/zfstest2@now > /tank/zfstest/testD.zfs
linux-ts3r:/tank/zfstest # zfs destroy -r tank/zfstest

zfs recv -v tank/zfstest2 < /tank/zfstest/testD.zfs
receiving full stream of tank/zfstest2@300726135 into tank/zfstest2@300726135
linux-ts3r:/tank/zfstest # zfs recv -v tank/zfstest2 < /tank/zfstest/testD.zfs
receiving full stream of tank/zfstest2@300726135 into tank/zfstest2@300726135
received 283MB stream in 19 seconds (14.9MB/sec)
receiving incremental stream of tank/zfstest2@296730124 into tank/zfstest2@296730124
received 319MB stream in 13 seconds (24.6MB/sec)
receiving incremental stream of tank/zfstest2@224726639 into tank/zfstest2@224726639
cannot receive incremental stream: invalid backup stream

**Comment by kpande** [comment] 2015-04-14 13:50
@prakashsurya any movement on this?

**Comment by calmofthestorm** [comment] 2015-04-18 15:36
Just ran into this myself. No data loss thanks to backups, but this is a really scary bug. Would it at least be possible to add a warning to zfs send -R until this can be fixed as crowtrobot suggests above?

**Comment by kpande** [comment] 2015-04-18 15:46
just skip using -D until #3066 and this are fixed

**Comment by calmofthestorm** [comment] 2015-04-18 15:50
The problem is that the user learns this when receiving, not when sending. And while yes, everyone should test their backups (indeed, that's how I found this myself), it's a really nasty surprise if you don't.

Just skip using -D is a fine workaround, but it's one that is far from obvious to users that they need to be employing it:-)

**Comment by kpande** [comment] 2015-04-18 15:54
You're right, there's no warnings at all in the ZoL man pages about send -D being potentially dangerous. As far as actual danger, what I see is:

* Your sending side may be stuck forever in 'D' state if you cancel the send, or it fails with "invalid backup stream", or some other random hang-up of send -D
* Your receiving side would not receive backups for a few days at at time and you don't know

Is that about it? Why not have automatic backup verification to at least check used space on recv side vs send side? Creation times are the same on send and recv side, so you can get that to do a simple comparison..

**Comment by calmofthestorm** [comment] 2015-04-18 16:00
The issue is that receive is potentially happening (much) later than send.

In my case the issue is that send goes to a file, which is then backed up offsite, rather than being directly restored to a zpool, so the issue wouldn't be noticed until restore time. This is why I test them before I'm "done", since at least then I know there exists a version of ZFS that can receive them without error.

I understand there are always risks inherent in this approach that make testing much more crucial, but I'd argue that at the moment a flag that claims to do one thing while secretly corrupting your backup without any warning goes beyond the "always test" threshold and into the "we should warn the user" territory, ESPECIALLY since the -D flag is much more attractive if you're backing up to tape/etc than if you're immediately sending to another zpool.

**Comment by kpande** [comment] 2015-04-18 16:02
ah! I understand better now. Have you tried recv the backup in another ZFS implementation like FreeBSD or illumos?

**Comment by calmofthestorm** [comment] 2015-04-18 16:09
No, I don't have easy access to any of those systems. I'm just deleting it and am recreating the backup from the original source, without -D. I'm not looking at actual data loss because I'm pretty cautious these days, but I'm remembering several youthful errors many years ago where a bug like this could have cost me everything:-)

**Comment by kpande** [comment] 2015-04-18 16:11
I now recall, when I had this problem (and even may have documented above in this issue) it did not work to recv on FreeBSD anyway. Good catch.

@FransUrbo is usually king of PRs for man page updates. Maybe he'd take a crack at warning users about send -D.

**Comment by mantlik** [comment] 2015-04-18 19:12
If you need full receive, you can install ZFS 0.6.2 which is not yet affected by the problem and receive under this version. This rescued me a while ago. The problem is that you need to start completely from scratch.

**Comment by tycho** [comment] 2016-05-03 18:25
I just hit this as well. Would be ideal to get this working properly because deduplication could have a lot of wins when replicating an entire pool.

**Comment by darkpixel** [comment] 2016-07-02 22:57
Just a heads-up for anyone stumbling upon this issue by searching for "cannot receive incremental stream: invalid backup stream":  This error message *can also* occur if you have something running (like a cron job) that automatically takes snapshots on the pool you are zfs-receiving against.

In my case, I use puppet to automatically configure a bunch of Linux boxes that all have a standard config.  I have a pool named 'tank' on all of them, and during normal production use zfs-auto-snapshot runs every 15 minutes to ensure customer data is protected.  I was restoring data to a newly created 'tank' with much larger drives.  The zfs receive would run for a while, then zfs-auto-snapshot would snapshot, and the next snapshot in the received stream would cause this error.

**Comment by dankimmel** [comment] 2016-08-21 18:21
I believe the PR posted here (https://github.com/openzfs/openzfs/pull/159) should fix this issue, and it also needs a reviewer to get pushed upstream. If anyone here wants to take a look I'd be very appreciative!

**Comment by pyavdr** [comment] 2016-09-23 08:16
@prakashsurya @dweeezil @behlendorf @dankimmel I tried to patch the current head of 7.0.-rc1_39*  with the changes of (https://github.com/openzfs/openzfs/commit/b09697c8c18be68abfe538de9809938239402ae8) and it works successful. Receiving the deduplicated stream with snapshots works. But i am unsure with it, because there are a some ambiguous differences in the code and i cant check all of them.  Find my patch file in the attachment. There should be an additional reviewer.

[dmu_send.txt](https://github.com/zfsonlinux/zfs/files/489142/dmu_send.txt)

**Comment by behlendorf** [comment] 2016-09-23 16:45
@pyavdr thanks for porting this.  It'll be much easier to review and comment on if you open a new pull request against master with the patch.  And make sure to include the test case from the original OpenZFS patch.  You just need to add it to the `tests` directory, update the `Makefile.am`, and enabled it in the runfile.

**Comment by gmelikov** [comment] 2017-02-04 18:28
Closed by #5689

**Closed by gmelikov** 2017-02-04 18:28 UTC
