### ISSUE TITLE
very high IO load during zpool upgrade from 0.6.5 to 0.7.5

### ISSUE THREAD

**Issue by AceSlash** [zfsonlinux/zfs#7164] opened 2018-02-13 11:37 UTC
### System information
Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Debian
Distribution Version    | 9 (stretch)
Linux Kernel                 | 4.9.0-5-amd64 - SMP Debian 4.9.65-3+deb9u2 (2018-01-04)
Architecture                 | x86_64
ZFS Version                  | 0.7.5-1~bpo9+1 (from Debian Stretch backports)
SPL Version                  | 0.7.5-1~bpo9+1 (from Debian Stretch backports)

### Describe the problem you're observing
I did a zpool upgrade when I switched from ZoL 0.6.5 to the backport Debian version which is 0.7.5, the feature that were enabled are:
```
# zpool upgrade tank
This system supports ZFS pool feature flags.

Enabled the following features on 'tank':
  multi_vdev_crash_dump
  large_dnode
  sha512
  skein
  edonr
  userobj_accounting
```
The zpool upgrade command did return immediately but I also saw a heavy load on the server with a very high IO activity.

Looking at zpool iostat and iotop, I could see that z_upgrade process were the one to use IO (no surprise here), after talking about it on IRC, I think that the feature "userobj_accounting" is the one that generate such high IO.

I did the zpool upgrade on 2 different servers, and I saw a very different load on each of them, related to the number of dataset (which seems normal), the load is not related to the size of used data on the datasets:

Number of filesystem dataset | Number of snapshot dataset | Used data on pool|pool size 
--- | --- | --- | ---
16 | 15046 | 6.75T | 8.69T
103 | 49563 | 3.62T | 4.34T

There a huge amount of tiny files on every filesystem datasets, 

Please also note that both servers have the kernel option pti=off, so no meltdown mitigation (they are purely internal servers).

### Describe how to reproduce the problem
1. Install Debian Stretch with ZoL from the normal repo
1. create many dataset? I'm not sure if the amount of data or the number of files is what is needed to trigger this
1. switch to ZoL from Debian backports (`apt install -t stretch-backports zfsutils-linux zfs-dkms spl`)

I think a quick fix would be to have a warning somewhere (on the zpool upgrade manual?) that a zpool upgrade operation can use a lot of IO. I actually don't mind the high load but some kind of warning would be nice so we can trigger this outside business hour.

**Comment by behlendorf** [comment] 2018-02-13 18:07
You are correct, the I/O load is almost certainly being generated by enabling the __userobj_accounting__ feature.  How long the upgrade takes is proportional to the number of files in the pool, and usually only takes a few minutes even for pools with a large number of files.  Your pool does sound like a worst case and I'd be curious to know many files you have and how long the upgrade took.

As for a warning the __userobj_accounting__ section of the `zpool-features.5` man page does mention that the process can take some time.

```
       userobj_accounting

           GUID                   org.zfsonlinux:userobj_accounting
           READ-ONLY COMPATIBLE   yes
           DEPENDENCIES           extensible_dataset

           This  feature  allows  administrators  to  account the object usage
           information by user and group.

           This feature becomes active as soon as it is enabled and will never
           return to being enabled. Each filesystem will be upgraded automati‐
           cally when remounted, or when new  files  are  created  under  that
           filesystem.   The  upgrade can also be started manually on filesys‐
           tems by running `zfs set version=current  <pool/fs>`.  The  upgrade
           process runs in the background and may take a while to complete for
           filesystems containing a large number of files.
```

**Comment by AceSlash** [comment] 2018-02-13 18:26
Thank you for pointing that part of the manual, I guess I'm just not used to having any kind of load during zpool upgrade (I'm using ZoL since 2013 with large dataset, and did a lot of zpool upgrade).

I'll guess I'll have to check the features before blindly upgrading the zpool.

About the content of the data in those datasets, you are indeed correct in assuming that they contains a very large amount of files. I cannot even count them and expect the count to finish. Medium file size is extremely low since many file are simply folders (I'll say a little less than half of them), the files medium size excluding folders may be ~100KB.

That means several millions of files.

**Comment by behlendorf** [comment] 2018-02-13 18:36
You're right, historically for most new features we've tried hard to avoid any upgrade cost.  That just wasn't possible this time if we wanted the new quota information to be available for existing filesystems.

As for total file count you can run `df -i` to quickly report total inodes (files) used.

**Comment by AceSlash** [comment] 2018-02-13 18:40
@behlendorf 131319442 files, I guess I have a little more than I thought.

**Comment by behlendorf** [comment] 2018-02-13 18:56
That's quite a few!  Do you have a rough idea of how long the upgrade took?

**Comment by AceSlash** [comment] 2018-02-13 19:38
It looks like it is still running, I'm not quite sure because the load is almost 0 now, but I still see some z_upgrade processes running.

Number of dataset | number of files in all dataset | used space | highest IO wait % | time until the load was not noticeable anymore | CPU
--- | --- | --- | --- | --- | ---
16 | 131319442 | 6.75T | 7.6% | ~ 4h20 | 2*Xeon(R) CPU E5-2687W v3 @ 3.10GHz (40 core)
103 | 83911489 | 3.62T | 34.23% | ~ 1h20 | 2*Xeon(R) CPU E5-2667 v2 @ 3.30GHz (32 core)

On the first server, one dataset has 130 millions of files. Since it looks like each dataset get its own process which seems to stay on one core, it makes sense that it took a long time on it. Also on the second one, one dataset has 50 millions files.

You can see the IO wait in graph here:
First server with 13 dataset and almost 130 millions files in one:
![13_datasets_131millions_files](https://user-images.githubusercontent.com/5392990/36169332-45b0967c-10fc-11e8-9f03-1912d290db44.png)
Second server with a better repartition but still 50 millions files on 1 dataset:
![103_datasets_83millions_files](https://user-images.githubusercontent.com/5392990/36169333-45d4fb20-10fc-11e8-803e-0ad5f34fe3ee.png)
On the first server, the hard drives are 8xSeagate Savvio 10K 1.20 TB 2.5" (ST1200MM0007) configured in as a simple zraid1.
On the second server, the drives are 8xToshiba 10K RPM 600 GB 2.5" (AL13SEB600) also configured in as a simple zraid1.

Retrospectively, it is quite amazing to see how fast the process ran.

**Comment by behlendorf** [comment] 2018-02-13 21:06
Thanks for the nice graphs.  Sorry this caught you by surprise, but since everything here did work as intended I'm going to close the issue.

**Closed by behlendorf** 2018-02-13 21:06 UTC
Labels: Documentation
