### ISSUE TITLE
txg

### ISSUE THREAD

**Issue by nawang87** [zfsonlinux/zfs#6637] opened 2017-09-13 06:39 UTC
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  Ubuntu
Distribution Version    |  16.0.4
Linux Kernel                 | 4.4.0-93-generic
Architecture                 | x86_64
ZFS Version                  | 0.6.5.6-0ubuntu16
SPL Version                  | 0.6.5.6-0ubuntu4

### Describe the problem you're observing

Kernel Panic observed when executing decryption and tar in large file example 3GB-20GB Files.
In all occasions txg_sync process was blocker for more than 120 seconds.

### Describe how to reproduce the problem
Kernel Panic observed when executing decryption and tar in large file example 3GB-20GB Files.
This state was observed in both state where we limit the size of the ARC.

But luckily or unluckily we didn't observe this error when limiting ARC max to 2GB. 

### Include any warning/errors/backtraces from the system logs

Sep 10 09:08:48 LogPoint kernel: [ 5661.671288] INFO: task txg_sync:14028 blocked for more than 120 seconds.
Sep 10 09:08:48 LogPoint kernel: [ 5661.671510]       Tainted: P           O    4.4.0-93-generic #116-Ubuntu
Sep 10 09:08:48 LogPoint kernel: [ 5661.671724] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Sep 10 09:08:48 LogPoint kernel: [ 5661.671976] txg_sync        D ffff881fbee2baa8     0 14028      2 0x00000000

**Comment by gmelikov** [comment] 2017-09-14 07:11
Duplicate of #2934, closed.

**Closed by gmelikov** 2017-09-14 07:11 UTC

**Comment by nawang87** [comment] 2017-09-14 07:39
what is the solution for this problem ? gmelikov

**Comment by gmelikov** [comment] 2017-09-14 07:44
Please just use that issue for discussion, we don't want to make many duplicates of one issue.
