### ISSUE TITLE
Documentation: special_small_blocks does not operate as described in man page

### ISSUE THREAD

**Issue by jwittlincohen** [zfsonlinux/zfs#8351] opened 2019-01-29 02:43 UTC
Type | Version/Name
 --- | --- 
Distribution Name	|  Debian
Distribution Version	|  Stretch (9.6)
Linux Kernel	|  Linux debian 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27)
Architecture	| x64
ZFS Version	| 0.8.0-rc3
SPL Version	| 0.8.0-rc3

### Describe the problem you're observing

The man page states that the value `special_small_blocks` "represents the threshold block size for including small file blocks into the special allocation class."  Based on this description, I would expect any block smaller than, or equal to, special_small_blocks to be assigned to the special allocation. 

However, testing indicates that this property behaves slightly differently.  Only blocks smaller than `special_small_blocks `will be allocated to the special allocation.  Blocks that are equal to `special_small_blocks` will be placed in the regular vdev allocation. 

As an example, if I set `recordsize=64`k, `special_small_blocks=64k`, and set `compression=off,` all blocks from a VM image are allocated to the regular vdev.  However, setting `recordsize=32k`will ensure the blocks are saved to the special allocation.  Similarly, setting `special_small_blocks=128k` will ensure the same for `recordsize=64k`.

### Describe how to reproduce the problem

1.  Create a testpool with a special allocation class vdev
2.  Create a new dataset with `recordsize=64k`, `special_small_blocks=64k`, and` compression=of`f on the
3.  Copy a large file to the dataset while monitoring with `zpool iostat - v 1`

### Resolution

A more accurate man page summary might say something like the following, "This value represents the threshold block size for including small file blocks into the special allocation class.  Blocks smaller than this value will be assigned to the special allocation class while blocks equal to or greater than this value will be assigned to the regular allocation."

**Comment by ahrens** [comment] 2019-02-07 21:35
@don-brady Can you confirm the expected behavior here?  Should we change the documentation to match the behavior, or change the behavior to match the documentation?

**Comment by rlaager** [comment] 2019-02-07 21:42
For what my random opinion is worth, I'd much rather see the boundary condition be <= than <. It seems weird to say that `special_small_blocks=64k` and not have 64k blocks count as small. The case of settting `special_small_blocks` equal to `recordsize` and not having every block count as small is even weirder feeling.

**Comment by behlendorf** [comment] 2019-02-07 21:46
The proposed fix for this is pending review in PR #8361.  It makes the suggested `<` to `<=` change and updates the documentation accordingly.

**Comment by don-brady** [comment] 2019-02-07 23:56
Looks like the documentation was correct and that the implementation was incorrect.  I thought we had already fixed it but it (per Richard's feedback) but that change didn't land.
Confirming that PR-8361 has the fix.

**Closed** 2019-02-08 20:32 UTC
Labels: Type: Unknown
