### ISSUE TITLE
Pool wont import, problem with space map

### ISSUE THREAD

**Issue by johnramsden** [zfsonlinux/zfs#5803] opened 2017-02-17 00:02 UTC
### System information

| Type  | Version/Name  |
|---|---|
|  Distribution Name | Arch Linux  |
| Kernel  |  linux-ARCH 4.9.8-1 |
| Architecture  | x86 64  |
|  ZFS | 0.6.5.9-1  |
| SPL  |  0.6.5.9-1 |

I'm using ZFS from the [archzfs](https://github.com/archzfs/archzfs) repo with zfs-linux.

### Problem Description

The system was working normally and then crashed. After the crash my zpool wouldn't import and I got an error message saying my space map was the wrong size. I'm not sure about this but it looks similar to #2947 so It could be related. 

The specific message was ( the X's are just representing two long numbers ): 

```
VERIFY (offset + size <= sm->sm_start + sm_size) failed ( XXXXXXXXXX / XXXXXXXX )
PANIC at space_map.c:115:space_map_load()

```
### Reproducing the Problem

Everytime I boot I get this error. I attempted importing the pool from a separate linux install on the system but the pool just hangs forever.

This is what my pool looked like. Two mirrors of sandisk ssds.

```
[root]# zpool status
pool: vault
state: ONLINE
scan: scrub repaired 0 in 0h8m with 0 errors on Mon Jun 13 00:08:39 2016
config:

NAME                                       STATE     READ WRITE CKSUM
vault                                      ONLINE       0     0     0
  mirror-0                                 ONLINE       0     0     0
    ata-SanDisk_SDSSDXPS480G_152271401093  ONLINE       0     0     0
    ata-SanDisk_SDSSDXPS480G_154501401266  ONLINE       0     0     0
  mirror-1
    ata-SanDisk_SDSSDXPS480G_164277402487  ONLINE       0     0     0
    ata-SanDisk_SDSSDXPS480G_164277402657  ONLINE       0     0     0

errors: No known data errors
```

 I've been running smart on them daily and up until the error there were no problems. I did have a problem occurred about a week and a half ago whereupon turning on my computer I received the smart error, but it was just in a single file that I was able to delete and upon multiple scrubs the error was cleared completely. After that no ZFS errors or smart errors occurred. I don't have ECC memory on this computer as it's just a desktop. 

I have all my data backed up however I'd just like to know why this happened and what could have possibly caused this.

**Comment by johnramsden** [comment] 2017-02-17 06:42
Not sure if this helps, but running zdb against the spacemap gives me:

```
zdb -e -p /dev/disk/by-id -m vault                    john@sloth

Metaslabs:
        vdev          0
        metaslabs   111   offset                spacemap          free      
        ---------------   -------------------   ---------------   -------------
        metaslab      0   offset            0   spacemap     38   free    3.67G
        metaslab      1   offset    100000000   spacemap    120   free    3.12G
        metaslab      2   offset    200000000   spacemap    123   free    3.47G
        metaslab      3   offset    300000000   spacemap    126   free     762M
        metaslab      4   offset    400000000   spacemap    114   free    2.98G
        metaslab      5   offset    500000000   spacemap    163   free    3.67G
        metaslab      6   offset    600000000   spacemap    166   free    3.03G
        metaslab      7   offset    700000000   spacemap    169   free    3.67G
        metaslab      8   offset    800000000   spacemap    172   free     102M
        metaslab      9   offset    900000000   spacemap    175   free    3.34G
        metaslab     10   offset    a00000000   spacemap    178   free    3.88G
        metaslab     11   offset    b00000000   spacemap    181   free    2.76G
        metaslab     12   offset    c00000000   spacemap    184   free    3.43G
        metaslab     13   offset    d00000000   spacemap    187   free    2.86G
        metaslab     14   offset    e00000000   spacemap    190   free    3.17G
        metaslab     15   offset    f00000000   spacemap    235   free     896M
        metaslab     16   offset   1000000000   spacemap    193   free    3.90G
        metaslab     17   offset   1100000000   spacemap    196   free    3.04G
        metaslab     18   offset   1200000000   spacemap    199   free     114M
        metaslab     19   offset   1300000000   spacemap    202   free     272M
        metaslab     20   offset   1400000000   spacemap    205   free    1.69G
        metaslab     21   offset   1500000000   spacemap     37   free    1.62G
        metaslab     22   offset   1600000000   spacemap    119   free    2.91G
        metaslab     23   offset   1700000000   spacemap    122   free    3.28G
        metaslab     24   offset   1800000000   spacemap    125   free    3.68G
        metaslab     25   offset   1900000000   spacemap    113   free    3.77G
        metaslab     26   offset   1a00000000   spacemap    162   free    1.99G
        metaslab     27   offset   1b00000000   spacemap    165   free    3.16G
        metaslab     28   offset   1c00000000   spacemap    168   free    3.24G
        metaslab     29   offset   1d00000000   spacemap    171   free    3.37G
        metaslab     30   offset   1e00000000   spacemap    174   free     160M
        metaslab     31   offset   1f00000000   spacemap    177   free     245M
        metaslab     32   offset   2000000000   spacemap    180   free    3.87G
        metaslab     33   offset   2100000000   spacemap    183   free    1.51G
        metaslab     34   offset   2200000000   spacemap    186   free    3.36G
        metaslab     35   offset   2300000000   spacemap    189   free    3.72G
        metaslab     36   offset   2400000000   spacemap    234   free    1.25G
        metaslab     37   offset   2500000000   spacemap    192   free    2.32G
        metaslab     38   offset   2600000000   spacemap    195   free    3.70G
        metaslab     39   offset   2700000000   spacemap    198   free    1.44G
        metaslab     40   offset   2800000000   spacemap    201   free     104M
        metaslab     41   offset   2900000000   spacemap    204   free    3.66G
        metaslab     42   offset   2a00000000   spacemap     36   free    2.99G
        metaslab     43   offset   2b00000000   spacemap    118   free    1.45G
        metaslab     44   offset   2c00000000   spacemap    121   free     662M
        metaslab     45   offset   2d00000000   spacemap    124   free    3.63G
        metaslab     46   offset   2e00000000   spacemap    112   free    1.04G
        metaslab     47   offset   2f00000000   spacemap    161   free    2.71G
        metaslab     48   offset   3000000000   spacemap    164   free    3.25G
        metaslab     49   offset   3100000000   spacemap    167   free    3.82G
        metaslab     50   offset   3200000000   spacemap    170   free    3.28G
        metaslab     51   offset   3300000000   spacemap    173   free    3.05G
        metaslab     52   offset   3400000000   spacemap    176   free    2.40G
        metaslab     53   offset   3500000000   spacemap    179   free    3.40G
        metaslab     54   offset   3600000000   spacemap    182   free    2.86G
        metaslab     55   offset   3700000000   spacemap    185   free    2.79G
        metaslab     56   offset   3800000000   spacemap    188   free    1.51G
        metaslab     57   offset   3900000000   spacemap    233   free    2.99G
        metaslab     58   offset   3a00000000   spacemap    191   free    3.10G
        metaslab     59   offset   3b00000000   spacemap    194   free    3.97G
        metaslab     60   offset   3c00000000   spacemap    197   free    3.29G
        metaslab     61   offset   3d00000000   spacemap    200   free    3.50G
        metaslab     62   offset   3e00000000   spacemap    203   free    1.59G
        metaslab     63   offset   3f00000000   spacemap    285   free    2.83G
        metaslab     64   offset   4000000000   spacemap    288   free     122M
        metaslab     65   offset   4100000000   spacemap    291   free     131M
        metaslab     66   offset   4200000000   spacemap    294   free     130M
        metaslab     67   offset   4300000000   spacemap    297   free     239M
        metaslab     68   offset   4400000000   spacemap    300   free     143M
        metaslab     69   offset   4500000000   spacemap    302   free     109M
        metaslab     70   offset   4600000000   spacemap    304   free     217M
        metaslab     71   offset   4700000000   spacemap    306   free     130M
        metaslab     72   offset   4800000000   spacemap    308   free     131M
        metaslab     73   offset   4900000000   spacemap    310   free     264M
        metaslab     74   offset   4a00000000   spacemap    312   free     107M
        metaslab     75   offset   4b00000000   spacemap    314   free     124M
        metaslab     76   offset   4c00000000   spacemap    316   free     255M
        metaslab     77   offset   4d00000000   spacemap    318   free     131M
        metaslab     78   offset   4e00000000   spacemap    320   free     128M
        metaslab     79   offset   4f00000000   spacemap    322   free    1.69G
        metaslab     80   offset   5000000000   spacemap    586   free    3.46G
        metaslab     81   offset   5100000000   spacemap    283   free    2.45G
        metaslab     82   offset   5200000000   spacemap    607   free     276M
        metaslab     83   offset   5300000000   spacemap    602   free    3.07G
        metaslab     84   offset   5400000000   spacemap    284   free    3.53G
        metaslab     85   offset   5500000000   spacemap    287   free    3.25G
        metaslab     86   offset   5600000000   spacemap    290   free    3.67G
        metaslab     87   offset   5700000000   spacemap    293   free    3.91G
        metaslab     88   offset   5800000000   spacemap    296   free    3.84G
        metaslab     89   offset   5900000000   spacemap    299   free     162M
        metaslab     90   offset   5a00000000   spacemap    301   free    3.90G
        metaslab     91   offset   5b00000000   spacemap    303   free    2.29G
        metaslab     92   offset   5c00000000   spacemap    305   free    3.46G
        metaslab     93   offset   5d00000000   spacemap    307   free    1.09G
        metaslab     94   offset   5e00000000   spacemap    309   free     288M
        metaslab     95   offset   5f00000000   spacemap    311   free    3.22G
        metaslab     96   offset   6000000000   spacemap    313   free    3.45M
        metaslab     97   offset   6100000000   spacemap    315   free    3.15G
        metaslab     98   offset   6200000000   spacemap    317   free    3.15G
        metaslab     99   offset   6300000000   spacemap    319   free    3.74G
        metaslab    100   offset   6400000000   spacemap    321   free    3.38G
        metaslab    101   offset   6500000000   spacemap    585   free    3.49G
        metaslab    102   offset   6600000000   spacemap    657   free    2.17G
        metaslab    103   offset   6700000000   spacemap    606   free    3.71G
        metaslab    104   offset   6800000000   spacemap    600   free     607M
        metaslab    105   offset   6900000000   spacemap    618   free    3.54G
        metaslab    106   offset   6a00000000   spacemap    286   free    3.07G
        metaslab    107   offset   6b00000000   spacemap    289   free    2.69G
        metaslab    108   offset   6c00000000   spacemap    292   free    3.72G
        metaslab    109   offset   6d00000000   spacemap    295   free     124M
        metaslab    110   offset   6e00000000   spacemap    298   free    3.09G

        vdev          1
        metaslabs   111   offset                spacemap          free      
        ---------------   -------------------   ---------------   -------------
        metaslab      0   offset            0   spacemap  87324   free    3.95G
        metaslab      1   offset    100000000   spacemap 127086   free    3.17G
        metaslab      2   offset    200000000   spacemap 131082   free    3.83G
        metaslab      3   offset    300000000   spacemap 131355   free    3.84G
        metaslab      4   offset    400000000   spacemap 132051   free    2.08G
        metaslab      5   offset    500000000   spacemap 135176   free    3.68G
        metaslab      6   offset    600000000   spacemap 135195   free    3.73G
        metaslab      7   offset    700000000   spacemap 135255   free    1.55G
        metaslab      8   offset    800000000   spacemap 135257   free    3.64G
        metaslab      9   offset    900000000   spacemap 139272   free    2.73G
        metaslab     10   offset    a00000000   spacemap 102452   free    3.82G
        metaslab     11   offset    b00000000   spacemap 106527   free    3.50G
        metaslab     12   offset    c00000000   spacemap   4126   free    2.97G
        metaslab     13   offset    d00000000   spacemap 131219   free    3.66G
        metaslab     14   offset    e00000000   spacemap 143366   free    3.87G
        metaslab     15   offset    f00000000   spacemap 147461   free    3.43G
        metaslab     16   offset   1000000000   spacemap 151555   free    3.92G
        metaslab     17   offset   1100000000   spacemap 159756   free    3.86G
        metaslab     18   offset   1200000000   spacemap 160097   free    1.83G
        metaslab     19   offset   1300000000   spacemap 114754   free    3.16G
        metaslab     20   offset   1400000000   spacemap 143385   free    3.00G
        metaslab     21   offset   1500000000   spacemap  87323   free    3.56G
        metaslab     22   offset   1600000000   spacemap 127085   free     756M
        metaslab     23   offset   1700000000   spacemap 131081   free    3.23G
        metaslab     24   offset   1800000000   spacemap 131353   free    3.26G
        metaslab     25   offset   1900000000   spacemap 132050   free     410M
        metaslab     26   offset   1a00000000   spacemap 135175   free    2.95G
        metaslab     27   offset   1b00000000   spacemap 135194   free    3.78G
        metaslab     28   offset   1c00000000   spacemap 135254   free    1.90G
        metaslab     29   offset   1d00000000   spacemap 135256   free    3.51G
        metaslab     30   offset   1e00000000   spacemap 139271   free    3.56G
        metaslab     31   offset   1f00000000   spacemap 102450   free    3.44G
        metaslab     32   offset   2000000000   spacemap 106522   free    1.68G
        metaslab     33   offset   2100000000   spacemap   4125   free    3.25G
        metaslab     34   offset   2200000000   spacemap 131218   free    3.66G
        metaslab     35   offset   2300000000   spacemap 143365   free    3.58G
        metaslab     36   offset   2400000000   spacemap 147460   free    3.16G
        metaslab     37   offset   2500000000   spacemap 151554   free    2.07G
        metaslab     38   offset   2600000000   spacemap 159755   free    3.83G
        metaslab     39   offset   2700000000   spacemap 160096   free    1.45G
        metaslab     40   offset   2800000000   spacemap 114694   free    2.80G
        metaslab     41   offset   2900000000   spacemap 143383   free     571M
        metaslab     42   offset   2a00000000   spacemap 147484   free    1.88G
        metaslab     43   offset   2b00000000   spacemap 155658   free    2.32G
        metaslab     44   offset   2c00000000   spacemap 163845   free    3.76G
        metaslab     45   offset   2d00000000   spacemap 118815   free    3.42G
        metaslab     46   offset   2e00000000   spacemap 147529   free    2.76G
        metaslab     47   offset   2f00000000   spacemap 155885   free    3.64G
        metaslab     48   offset   3000000000   spacemap 172042   free     135M
        metaslab     49   offset   3100000000   spacemap 167952   free     174M
        metaslab     50   offset   3200000000   spacemap 176141   free    3.23G
        metaslab     51   offset   3300000000   spacemap 176167   free    2.08G
        metaslab     52   offset   3400000000   spacemap 176169   free    3.23G
        metaslab     53   offset   3500000000   spacemap 176174   free    3.87G
        metaslab     54   offset   3600000000   spacemap 176420   free    3.45G
        metaslab     55   offset   3700000000   spacemap 176344   free     711M
        metaslab     56   offset   3800000000   spacemap 180230   free    2.97G
        metaslab     57   offset   3900000000   spacemap 184328   free    2.55G
        metaslab     58   offset   3a00000000   spacemap 131246   free    2.65G
        metaslab     59   offset   3b00000000   spacemap 135258   free    3.85G
        metaslab     60   offset   3c00000000   spacemap 139300   free    2.99G
        metaslab     61   offset   3d00000000   spacemap 188424   free    1.64G
        metaslab     62   offset   3e00000000   spacemap 191724   free    3.12G
        metaslab     63   offset   3f00000000   spacemap 147482   free     100M
        metaslab     64   offset   4000000000   spacemap 155656   free    3.63G
        metaslab     65   offset   4100000000   spacemap 163844   free    3.23G
        metaslab     66   offset   4200000000   spacemap 118814   free    3.89G
        metaslab     67   offset   4300000000   spacemap 147528   free    2.67G
        metaslab     68   offset   4400000000   spacemap 155883   free     398M
        metaslab     69   offset   4500000000   spacemap 172041   free    3.83G
        metaslab     70   offset   4600000000   spacemap 167951   free    3.88G
        metaslab     71   offset   4700000000   spacemap 176140   free    3.63G
        metaslab     72   offset   4800000000   spacemap 176166   free    3.38G
        metaslab     73   offset   4900000000   spacemap 176168   free    2.96G
        metaslab     74   offset   4a00000000   spacemap 176173   free     692M
        metaslab     75   offset   4b00000000   spacemap 176341   free    2.18G
        metaslab     76   offset   4c00000000   spacemap 176244   free    3.19G
        metaslab     77   offset   4d00000000   spacemap 180229   free    2.04G
        metaslab     78   offset   4e00000000   spacemap 184327   free    3.28G
        metaslab     79   offset   4f00000000   spacemap 131245   free    3.74G
        metaslab     80   offset   5000000000   spacemap 135182   free    1.76G
        metaslab     81   offset   5100000000   spacemap 139299   free    3.48G
        metaslab     82   offset   5200000000   spacemap 188423   free    2.74G
        metaslab     83   offset   5300000000   spacemap 191723   free    3.82G
        metaslab     84   offset   5400000000   spacemap 151718   free    3.69G
        metaslab     85   offset   5500000000   spacemap 200708   free     429M
        metaslab     86   offset   5600000000   spacemap 200859   free    2.68G
        metaslab     87   offset   5700000000   spacemap 208900   free    2.98G
        metaslab     88   offset   5800000000   spacemap  69730   free    2.90G
        metaslab     89   offset   5900000000   spacemap  16386   free    2.51G
        metaslab     90   offset   5a00000000   spacemap  12292   free    3.81G
        metaslab     91   offset   5b00000000   spacemap  30215   free    2.70G
        metaslab     92   offset   5c00000000   spacemap 143409   free    3.10G
        metaslab     93   offset   5d00000000   spacemap 155655   free    3.41G
        metaslab     94   offset   5e00000000   spacemap 163841   free    3.68G
        metaslab     95   offset   5f00000000   spacemap 167943   free    2.98G
        metaslab     96   offset   6000000000   spacemap  49236   free    3.23G
        metaslab     97   offset   6100000000   spacemap  53250   free     603M
        metaslab     98   offset   6200000000   spacemap  57357   free    3.56G
        metaslab     99   offset   6300000000   spacemap  45061   free    3.55G
        metaslab    100   offset   6400000000   spacemap 110605   free    2.67G
        metaslab    101   offset   6500000000   spacemap 176129   free    3.70G
        metaslab    102   offset   6600000000   spacemap 196614   free    3.07G
        metaslab    103   offset   6700000000   spacemap 212993   free    3.59G
        metaslab    104   offset   6800000000   spacemap  80487   free    3.62G
        metaslab    105   offset   6900000000   spacemap 151717   free    3.79G
        metaslab    106   offset   6a00000000   spacemap 200707   free    3.45G
        metaslab    107   offset   6b00000000   spacemap 200854   free    3.87G
        metaslab    108   offset   6c00000000   spacemap 208899   free    3.79G
        metaslab    109   offset   6d00000000   spacemap  69729   free     751M
        metaslab    110   offset   6e00000000   spacemap  16385   free    3.71G
```

**Comment by johnramsden** [comment] 2017-02-17 06:57
## Update

I was able to mount readonly with:

`zpool import -N -o readonly=on -d /dev/disk/by-id -R /mnt/vault vault`

Should I run a scrub?

**Comment by ryao** [comment] 2017-02-24 01:08
I just helped someone in IRC earlier today who had this problem. In his case, his machines were not on UPS power, mains power was suffering voltage drops and there was no ground. By any chance, would you be in a similar situation?

**Comment by johnramsden** [comment] 2017-02-27 08:05
I shouldn't be, I'm using a UPS. I'm not using ECC memory though since it's just a desktop computer. Would ECC memory have likely prevented this?

I was actually worried it might be my power supply since I read about other people having problems that sounded similar where they had a malfunctioning power supply. So I brought a power supply tester and all my voltages seem to be correct. 

Right now I'm at a loss as to what would cause this issue.

**Comment by kpande** [comment] 2017-03-03 00:42
modern systems are only more and more likely to hit memory issues (which may be offset by smaller components, but there are more of them so the net effect isn't clear) and this is why ECC is considered a requirement for ZFS. I would recommend restoring from backups to a system with ECC. it is hard to consider these bugs when you are not running with it. @behlendorf can correct me if I am wrong.

**Comment by behlendorf** [comment] 2017-03-27 23:10
There are no known metaslab corruption issue so this definitely could have been caused by lack of ecc memory, but it's impossible to know for certain.  You're best bet for the moment is to import the pool read-only as you've done and recreate it.  Longer term there has been talk of extending an existing tool to repair tool to correct this specific type of damage but so far no one is currently working on this.

Thanks for reporting the issue but since there's nothing actionable here I'm closing the issue.

**Closed by behlendorf** 2017-03-27 23:10 UTC
