### ISSUE TITLE
Running zdb on an active pool

### ISSUE THREAD

**Issue by chrisrd** [zfsonlinux/zfs#8192] opened 2018-12-07 01:16 UTC
### System information
Type | Version/Name
 --- | --- 
Distribution Name	| debian jessie
Distribution Version	| 8.9
Linux Kernel	| 4.16.13 (7a4011f4, self compiled)
Architecture	| x86_64
ZFS Version	| 0.8.0 (00369f333809, self compiled)
SPL Version	| 0.8.0 (00369f333809, self compiled)

### Describe the problem you're observing

Running `zdb -bb pool` on my (active) pool produces an ASSERT like:
```
loading concrete vdev 1, metaslab 24 of 120 ...space_map_load(msp->ms_sm, msp->ms_allocatable, maptype) == 0 (0x5 == 0)
ASSERT at zdb.c:3883:load_concrete_ms_allocatable_trees()Aborted
```
Running the `zdb -bb` multiple times has the ASSERT coming up at different points of the pool, e.g.:
```
loading concrete vdev 1, metaslab 69 of 120 ...
loading concrete vdev 1, metaslab 24 of 120 ...
loading concrete vdev 0, metaslab 33 of 120 ...
loading concrete vdev 1, metaslab 23 of 120 ...
loading concrete vdev 2, metaslab 102 of 120 ...
```
The inconsistent ASSERT might be an indication of a race condition, and/or perhaps due to allocating/freeing during the run.

Running `zdb -bb` a number of times on a much smaller SSD-based (active) pool has always completed without error, but that might be simply because the command completes relatively quickly (~15m) compared to the same command on the HDD pool (1-15hrs to get to the ASSERT).

Is `zdb -bb` supposed to be able to used successfully on an active pool?

If so, what's the easiest way of tracking down the source of the inconsistency - and if there's an actual error in the pool?

Cheers,

Chris

---

The pool is 3 x raidz3 HDD vdevs, 180T total, 129T allocated, compression on, no encryption, no zvols, 2084 filesystems (5 with dedup), 22500 snapshots.

Running `echo 512 > /sys/module/zfs/parameters/zfs_flags` before the `zdb` produces copious output in `/proc/spl/kstat/zfs/dbgmsg`. Trimming the leading timestamp from the result and counting the various messages produces:

```
# {
  echo 0 > /proc/spl/kstat/zfs/dbgmsg
  echo 512 > /sys/module/zfs/parameters/zfs_flags
  zdb -bb pool
  sed -r 's/^[0-9]+  //' /proc/spl/kstat/zfs/dbgmsg | sort | uniq -c | sort -n
}
      5  dbuf.c:3126:dbuf_hold_impl_arg(): error 2
      8  dnode.c:2377:dnode_next_offset_level(): error 3
      8  zap.c:740:fzap_checksize(): error 22
     27  zap_leaf.c:492:zap_entry_read(): error 75
    165  zfs_dir.c:1075:zfs_get_xattrdir(): error 2
    310  zap_leaf.c:429:zap_leaf_lookup(): error 2
    329  dbuf.c:2675:dbuf_findbp(): error 2
    500  ddt.c:178:ddt_object_lookup(): error 2
   1052  zap_micro.c:946:zap_lookup_impl(): error 2
   1873  zap_micro.c:1563:zap_cursor_retrieve(): error 2
   5289  zap_leaf.c:513:zap_entry_read_name(): error 75
  10472  sa.c:370:sa_attr_op(): error 2
  10573  dmu.c:448:dmu_spill_hold_existing(): error 2
  15224  zfeature.c:239:feature_get_refcount(): error 95
```

The `ASSERT` is telling us the `space_map_load()` returned 5 (likely EIO) but unfortunately we don't have any `error 5` smoking gun in the `dbgmsg`. And digging into the `space_map_load()` shows the error can originate in whole host of places, none of which appear to be in the `dbgmsg`. E.g. the possibly incomplete call chain:

```
load_concrete_ms_allocatable_trees()
  VERIFY0(space_map_load(msp->ms_sm, msp->ms_allocatable, maptype));            # our ASSERT
    err = space_map_iterate(sm, space_map_load_callback, &smla)
      error = dmu_buf_hold(sm->sm_os, space_map_object(sm), block_base, FTAG, &db, DMU_READ_PREFETCH);
        err = dmu_buf_hold_noread(os, object, offset, tag, dbp);
          err = dnode_hold(os, object, FTAG, &dn);
        err = dbuf_read(db, NULL, db_flags);
          err = dbuf_read_verify_dnode_crypt(db, flags);
            err = arc_untransform(dnode_abuf, os->os_spa, &zb, B_TRUE);
              ret = arc_buf_fill(buf, spa, zb, flags);
                error = arc_fill_hdr_crypt(hdr, hash_lock, spa, zb, !!(flags & ARC_FILL_NOAUTH));
                  ret = arc_hdr_authenticate(hdr, spa, zb->zb_objset);
                    ret = spa_do_crypt_objset_mac_abd(B_FALSE, spa, dsobj, abd, psize, hdr->b_l1hdr.b_byteswap != DMU_BSWAP_NUMFUNCS);
                      ret = spa_keystore_lookup_key(spa, dsobj, FTAG, &dck);
                        ret = SET_ERROR(ENOENT);
                      ret = zio_crypt_do_objset_hmacs(&dck->dck_key, buf, datalen, byteswap, portable_mac, local_mac);
                        ret = crypto_mac_init(&mech, &key->zk_hmac_key, NULL, &ctx, NULL);
                          pd = kcf_get_mech_provider(mech->cm_type, &me, &error, list, CRYPTO_FG_MAC, CHECK_RESTRICT(crq), 0)
                            *error = CRYPTO_MECHANISM_INVALID;
                          error = CRYPTO_BUFFER_TOO_BIG;
                          error = crypto_mac_init_prov(pd, pd->pd_sid, mech, key, spi_ctx_tmpl, ctxp, crq);
                            ...
                        ret = SET_ERROR(EIO);   
                        ret = crypto_mac_update(ctx, &cd, NULL);
                          return (CRYPTO_INVALID_CONTEXT);
                          rv = KCF_PROV_MAC_UPDATE(pd, ctx, data, NULL); 
                          rv = kcf_submit_request(pd, ctx, cr, &params, B_FALSE);
                        ret = crypto_mac_update(ctx, &cd, NULL);
                        ret = SET_ERROR(EIO);
                        ret = zio_crypt_do_dnode_hmac_updates(ctx, key->zk_version, should_bswap, &osp->os_meta_dnode);
                        ret = crypto_mac_final(ctx, &cd, NULL);
                        ret = crypto_mac_init(&mech, &key->zk_hmac_key, NULL, &ctx, NULL);
                        ret = SET_ERROR(EIO);
                        ret = crypto_mac_update(ctx, &cd, NULL);
                        ret = SET_ERROR(EIO);
                        ret = zio_crypt_do_dnode_hmac_updates(ctx, key->zk_version, should_bswap, &osp->os_userused_dnode);
                        ret = zio_crypt_do_dnode_hmac_updates(ctx, key->zk_version, should_bswap, &osp->os_groupused_dnode);
                        ret = zio_crypt_do_dnode_hmac_updates(ctx, key->zk_version, should_bswap, &osp->os_projectused_dnode);
                        ret = crypto_mac_final(ctx, &cd, NULL);
                        ret = SET_ERROR(EIO);
                    ret = spa_do_crypt_mac_abd(B_FALSE, spa, dsobj, abd, psize, hdr->b_crypt_hdr.b_mac);
                      ret = spa_keystore_lookup_key(spa, dsobj, FTAG, &dck);
                        ret = SET_ERROR(ENOENT);
                      ret = zio_crypt_do_hmac(&dck->dck_key, buf, datalen, digestbuf, ZIO_DATA_MAC_LEN);
                        ret = crypto_mac(&mech, &in_data, &key->zk_hmac_key, key->zk_hmac_tmpl, &digest_data, NULL);
                          pd = kcf_get_mech_provider(mech->cm_type, &me, &error, list, CRYPTO_FG_MAC_ATOMIC, CHECK_RESTRICT(crq), data->cd_length)
                            *error = CRYPTO_MECHANISM_INVALID;
                          return (CRYPTO_OLD_CTX_TEMPLATE);
                          error = KCF_PROV_MAC_ATOMIC(pd, pd->pd_sid, &lmech, key, data, mac, spi_ctx_tmpl, KCF_SWFP_RHNDL(crq))
                            ...
                          error = CRYPTO_BUFFER_TOO_BIG;
                          error = kcf_submit_request(pd, NULL, crq, &params, KCF_ISDUALREQ(crq));
                            error = common_submit_request(pd, ctx, params, KCF_RHNDL(KM_SLEEP));
                            error = CRYPTO_FAILED;
                            error = CRYPTO_HOST_MEMORY;
                            error = kcf_disp_sw_request(areq);
                        ret = SET_ERROR(EIO);
                      return (SET_ERROR(ECKSUM));
                  ret = arc_hdr_decrypt(hdr, spa, zb);
                return (SET_ERROR(EIO));
              ret = SET_ERROR(EIO);
          err = arc_untransform(db->db_buf, spa, &zb, B_FALSE);
              ret = arc_buf_fill(buf, spa, zb, flags);
                error = arc_fill_hdr_crypt(hdr, hash_lock, spa, zb, !!(flags & ARC_FILL_NOAUTH));
                return (SET_ERROR(EIO));
              ret = SET_ERROR(EIO);
          err = dbuf_read_impl(db, zio, flags);
            err = dbuf_read_verify_dnode_crypt(db, flags);
            err = arc_read(zio, db->db_objset->os_spa, db->db_blkptr, dbuf_read_done, db, ZIO_PRIORITY_SYNC_READ, zio_flags, &aflags, &zb);
              rc = arc_buf_alloc_impl(hdr, spa, zb, private, encrypted_read, compressed_read, noauth_read, B_TRUE, &buf);
                return (arc_buf_fill(buf, spa, zb, flags));
                  error = arc_fill_hdr_crypt(hdr, hash_lock, spa, zb, !!(flags & ARC_FILL_NOAUTH));
                  return (SET_ERROR(EIO));
              rc = SET_ERROR(EIO);
              rc = zio_wait(rzio);
                error = zio->io_error;
          err = zio_wait(zio);
            error = zio->io_error;
          err = SET_ERROR(EIO);
      error = callback(&sme, arg);   ## == space_map_load_callback()
        space_map_load_callback()
          return 0;
```

As there's no encryption on this pool that call chain can be significantly reduced, but there's still a large number of places that can produce the error.

There's no practical opportunity to run the `zdb` on the pool in a quiescent state, and highly limited opportunity to reload zfs modules to add further debugging.

Any suggestions on an approach to track this down?

**Comment by behlendorf** [comment] 2018-12-11 23:35
> Is zdb -bb supposed to be able to used successfully on an active pool?

Not really, that's almost certainly the reason for the ASSERT you're hitting.  If the pool is relatively idle, or can be scanned quickly enough, you'll probably be able to use `zdb -bb` on the active pool.  But for a large active pool that's likely not going to be the case and you'll run in to this kind of thing.

Since you're running a version with the 'pool checkpoints' feature one thing you could try is to creating a checkpoint.  Then you might be able to get `zdb -bb -T <checkpoint txg>` to run cleanly against that checkpoint since all the blocks will be stable.  You can then remove the pool checkpoint.

**Comment by chrisrd** [comment] 2018-12-12 03:39
Thanks for the `zpool checkpoint` suggestion, that looks good.

This pool has only been running on 0.8 with the `checkpoint` feature for 2 weeks, having upgraded from 0.7 (no `checkpoint` available) to see if anything changed with the `zdb -bb`. I don't want to enable `checkpoint` yet, so I can go back to 0.7 if necessary. I think I'll wait until sometime after 0.8 is tagged and seems stable before enabling `checkpoint` and trying the `zdb -bb -T`.

I'm happy for the ticket to be closed (I'll report back on the `zdb -bb -T` anyhow) unless you want to take the view than any ASSERT is a bug...

We could update `zdb.8` with the caveat that on an active pool certain operations, e.g. `-b`, may not give consistent results or may even ASSERT. It would be nice to have this warning in the manual for the susceptible operations: can we identify which other operations aren't always expected to succeed on an active pool?

And/or change `load_concrete_ms_allocatable_trees()` so the ASSERT becomes a error message along the lines of "Loading the space map failed, this isn't unexpected on an active pool", and the function returns failure.

**Comment by chrisrd** [comment] 2018-12-12 22:10
Thanks for the `zpool checkpoint` suggestion, that looks good.

This pool has only been running on 0.8 with the `checkpoint` feature for 2 weeks, having upgraded from 0.7 (no `checkpoint` available) to see if anything changed with the `zdb -bb`. I don't want to enable `checkpoint` yet, so I can go back to 0.7 if necessary. I think I'll wait until sometime after 0.8 is tagged and seems stable before enabling `checkpoint` and trying the `zdb -bb -T`.

I'm happy for the ticket to be closed (I'll report back on the `zdb -bb -T` anyhow) unless you want to take the view than any ASSERT is a bug...

We could update `zdb.8` with the caveat that on an active pool certain operations, e.g. `-b`, may not give consistent results or may even ASSERT. It would be nice to have this warning in the manual for the susceptible operations: can we identify which other operations aren't always expected to succeed on an active pool?

And/or change `load_concrete_ms_allocatable_trees()` so the ASSERT becomes a error message along the lines of "Loading the space map failed, this isn't unexpected on an active pool", and the function returns failure.

**Comment by behlendorf** [comment] 2018-12-12 22:21
I'd like to say this only applied to `-bb` but the reality is that `zdb` isn't going to be reliable when running against an active pool.  This is mentioned in the man page.  Do you think this needs to be made clearer?

```

     The output of this command in general reflects the on-disk structure of a
     ZFS pool, and is inherently unstable.  The precise output of most invoca‐
     tions is not documented, a knowledge of ZFS internals is assumed.

     ...

     When operating on an imported and active pool it is possible, though
     unlikely, that zdb may interpret inconsistent pool data and behave errat‐
     ically.
```

**Comment by chrisrd** [comment] 2018-12-12 23:13
My initial quick reading of "inherently unstable" was that it might return different results for the same command (i.e. because things changed underneath it) so that was understandable, and "behave erratically" was... interesting but not hugely informative - but in hindsight it means a lot!

Perhaps something along the lines of `...zdb may interpret inconsistent pool data and produce erratic results or even ASSERT.`  Or `crash` instead of `ASSERT`?

**Comment by chrisrd** [comment] 2018-12-12 23:15
...and/or, probably even more helpful, suggest the `checkpoint` option for investigating active pools.

**Comment by behlendorf** [comment] 2018-12-12 23:31
I'm all for better documentation.  Could you open a PR with the your improved phrasing.  I like the checkpoint suggestion too, but before adding that we should double check to make sure it actually helps!

**Comment by behlendorf** [comment] 2018-12-12 23:37
Even better.  I'd forgotten the `-k` option was added to `zdb` which let's you easily access the checkpointed pool state.

```
     -k      Examine the checkpointed state of the pool.  Note, the on disk
             format of the pool is not reverted to the checkpointed state.
```

**Comment by mk01** [comment] 2020-01-19 13:56
@chrisrd @behlendorf 

guys, injecting old(er) thread, but still open. I can confirm that steps provided by @behlendorf worked. I tested zdb -bb run on 0.8.2 with 18T pool (19 disks in total = 7 classic mirrors, 1 mirror special, l2arc and log mirror). initially failing as it was supposed to.

after
```
zpool checkpoint pool
zdb -bb -k pool
```
+ 4h run time it was done
```
No leaks (block sum matches space maps exactly)
```
without checkpoint it never passed metaslabs at mirror-2 (so 3rd vdev).
perhaps one more number, during the 4h+ it was running, the checkpoint got 55G in size. so not **very** busy pool, but clearly demonstrates it can be the way to go.

mk

**Comment by behlendorf** [comment] 2020-01-21 21:14
@mk01 thanks for posting to confirm that checkpoints can be used when you need to run `zdb` against an active pool.  Using `zdb` with anything other than a checkpoint while the pool is imported is not expected to be robust.  I'm closing this because the behavior is as intended.

**Closed by behlendorf** 2020-01-21 21:14 UTC
Labels: Type: Documentation
