### ISSUE TITLE
Git tip can lock arc_no_grow to B_TRUE, resulting in a total ARC size collapse

### ISSUE THREAD

**Issue by siebenmann** [zfsonlinux/zfs#3637] opened 2015-07-27 17:09 UTC
I've observed a situation where the latest git tip experiences an ARC size collapse despite plentiful free system memory; arc_c flatlined at 32 MB (c_min), arc_no_grow reported at 1, and of course the system performed terribly because nothing was cached. On inspection, I believe that there is an oversight in current git tip (after the ARC sync-up landed) that can result in this.

If I'm reading the code right, the primary point where arc_no_grow is set to B_FALSE is in arc_reclaim_thread(). Tracing through the logic, this happens if free_memory is > (arc_c  >> arc_no_grow_shift) and we've waited for growtime. On my 32 GB machine with a c_min of 32 MB, this requires free_memory to be above 1 MB. However, free_memory comes from arc_available_memory(), which on Linux returns at most PAGE_SIZE, ie 4K. As a result, this condition can never be true and arc_no_grow will be permanently locked at B_TRUE.

The core problem here is that on Linux, arc_available_memory() is not a value, it is a signal (and it doesn't look like a particularly good one at that), but arc_reclaim_thread() wants to use it as value. This fails badly.

**Comment by behlendorf** [comment] 2015-07-27 19:40
@siebenmann thank you for catching this!  Yes, this was definitely an oversight and you've already identified the core issue.  Under Linux the VM was designed such that we should never need to know how much free memory is available on the system.  However, the ARC design from illumos assumes this information is available.

To handle this an not diverge too much from illumos the code was originally modified to use a slightly difference mechanism to manage `arc_no_grow`.  The idea is that we should rely on the `__arc_shrinker_func()` to determine if memory is low on the system.  That function will be called by the Linux VM regularly if memory is low.  It can be used to reset the `arc_grow_time` and that can be checked in `arc_available_memory()` to make a reasonable determination about the memory state of the system.  If a sufficient amount of time has passed without the shrinker being called we can safely assume there is sufficient available memory on the system.  The exact value shouldn't have been too important since the kernel will notify us when it's low.  However, as you discovered it as and I overlooked this case when doing the merge.

That said, we now do have a mechanism for checking the number of free pages on the system which is available for all the supported kernels.  Let me propose a patch which takes advantage of that interface in a way that's appropriate for Linux.

**Comment by DeHackEd** [comment] 2015-07-27 21:05
It occurs to me this might be related to the issues with #3616 - my solution was to raise `zfs_arc_min` but I didn't realize something might have been related. Stuck at low values the ARC kept trying to shrink itself and stalling.

**Comment by snajpa** [comment] 2015-07-27 22:41
I have hit this one several times already, I've seen ARC fall from 128G to 6G, ```arc_no_grow=1``` and the IOPS performance of ARC dropped from ~450k down to 40k (mostly thanks to L2ARC).

@behlendorf I'm waiting for the promised patch, I'll have a patch party on Friday, so it'd be cool to have a fix for this included, or at least I can test whatever you come up with :-)

**Comment by behlendorf** [comment] 2015-07-27 23:48
Pull request #3639 updated with the promised patch.  Effectively it updates the ARC to consult the number of free pages on the system in `arc_available_memory()` more like the illumos code.  However, because we don't have the same global tuning exposed as illumos I've added the `zfs_arc_lotsfree` and `zfs_arc_desfree` tunables which are analogous to their illumos counterparts (except in bytes not pages).  They default to the same values are are visible in /proc/spl/kstat/zfs/arcstats.

This patch follows in the same spitit of the previous ARC changes by functionally bringing the ZoL ARC back in sync with upstream as much as possible.

@nedbass @ryao @siebenmann @DeHackEd @snajpa I;ve only had a chance to lightly test this change so and feedback, review and testing would be highly appreciated.

**Closed** 2015-07-30 20:26 UTC
Labels: Bug - Major, Memory Management

**Comment by DeHackEd** [comment] 2015-08-11 01:25
Someone was just in IRC with the same symptoms.
http://paste.ubuntu.com/12052761/
He appeared to be up to date as of right now, including kernel driver version. Forcibly raising `zfs_arc_max` unwedged him.

**Comment by siebenmann** [comment] 2015-08-11 18:40
Might it be something similar to or related to #3680, where the page cache hammers the ARC into the ground? The symptoms are sort of similar; arc_no_grow goes to 1, the ARC size is hammered into the ground (especially data_size), and then it doesn't grow afterwards even if arc_no_grow becomes 0 again.

It's also possible that there's a general issue here where once the ARC has been hammered into the ground by something, it grows only very slowly even if there's lots of free memory. Forcing the ARC target size up with a zfs_arc_max reset then allows the ARC to start growing aggressively. If this is the case then I'd expect it to happen for any surge of memory demand that shoves the ARC down, whether that is from page cache growth, sudden user memory demand, or some other kernel memory usage.
