### ISSUE TITLE
resilver zed notification has old zpool status

### ISSUE THREAD

**Issue by bmcgough** [zfsonlinux/zfs#9590] opened 2019-11-14 23:02 UTC
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Ubuntu
Distribution Version	| 18.04.3
Linux Kernel	| 4.15.0-66-generic
Architecture	| x86_64
ZFS Version	| 0.8.0-1
SPL Version	| 0.8.0-1

### Describe the problem you're observing
We receive a resilver_finish event notification that shows the zpool unhealthy when the state of the pool and all drives in ONLINE. It looks like the state just prior to the finish of the resilver. Is zpool state cached or is there a possible race condition between the event and ZED running the zpool status command?
### Describe how to reproduce the problem
Cause a resilver, wait for the resilver_finish event notification.

**Comment by rlaager** [comment] 2019-12-17 20:53
Whoops, it looks like I opened a duplicate of this, in #9740. Since Brian has commented there with a potential patch, I'm going to close this in favor of that one. Sorry @bmcgough. You can subscribe to #9740.

**Closed by rlaager** 2019-12-17 20:53 UTC
Labels: Component: ZED
