### ISSUE TITLE
Slow copy between filesystems on same pool

### ISSUE THREAD

**Issue by rbabchis** [zfsonlinux/zfs#3505] opened 2015-06-18 20:02 UTC
I experience file copy speeds of larger files between two filesystems on the same pool of around 50-75MB/sec, the speed is highly variable and sometimes even dips below 50MB/sec. If I copy files within the same filesystem, I get around 110-140MB/sec and the speed is more stable. Please tell me I'm not imagining this and there's a way to fix it?

Bonnie++ run on one of the datasets, on this pool says:

Uncompressed sequential read: 223MB/sec write: 309MB/sec
Compressed sequential read: 566MB/sec write: 1.12GB/sec

The pool in question:

NAME                                                 STATE     READ WRITE CKSUM
        pool2                                                ONLINE       0     0     0
          mirror-0                                           ONLINE       0     0     0
            ata-WDC_WD20EFRX-68AX9N0_WD-WMC300004469         ONLINE       0     0     0
            ata-WDC_WD20EFRX-68EUZN0_WD-WCC4MLK57MVX         ONLINE       0     0     0
          mirror-1                                           ONLINE       0     0     0
            ata-WDC_WD20EFRX-68AX9N0_WD-WCC1T0429536         ONLINE       0     0     0
            ata-WDC_WD20EFRX-68EUZN0_WD-WCC4M0VYKFCE         ONLINE       0     0     0
        logs
          ata-KINGSTON_SV300S37A120G_50026B7751153A9F-part1  ONLINE       0     0     0
        cache
          ata-KINGSTON_SV300S37A120G_50026B7751153A9F-part2  ONLINE       0     0     0

The hardware:

AMD FX(tm)-8350 Eight-Core Processor at 4.0Ghz
16GB RAM
4x2TB WD Red Drives
1x120GB Kingston SSD

The software:

Debian Linux 8.1 Jessie
ZFS RAID-10 4-disk main storage pool - 4TB
ZFS log (ZIL) device on SSD - 16GB
ZFS cache device on SSD - 100GB
ZoL debs 0.6.4-1.1-2-wheezy
All filesystems have lz4 compression
OS packages up to date
All datasets + pools up to date

**Comment by rbabchis** [comment] 2015-06-21 16:27
I just realized I got the read/write speeds mixed up while benchmarking again. So it would read:

Uncompressed sequential write: 223MB/sec read: 309MB/sec
Compressed sequential write: 566MB/sec read: 1.12GB/sec

**Comment by rbabchis** [comment] 2015-07-03 20:04
My copying a file between ZFS filesystems with rsync:

sending incremental file list
some_file.mp4
    442,759,022 100%   41.86MB/s    0:00:10 (xfr#1, to-chk=0/1)

sent 442,867,242 bytes  received 35 bytes  38,510,198.00 bytes/sec
total size is 442,759,022  speedup is 1.00


And copying in the same directory:

$ rsync -av --progress Spaced_Out-conv_20110306.mpg  newfile.avi
sending incremental file list
Spaced_Out-conv_20110306.mpg
  2,018,226,176 100%   77.92MB/s    0:00:24 (xfr#1, to-chk=0/1)

sent 2,018,719,031 bytes  received 35 bytes  79,165,453.57 bytes/sec
total size is 2,018,226,176  speedup is 1.00

Still not as fast as I'd like, but there is a big difference between the two.

**Comment by rbabchis** [comment] 2015-10-05 10:40
The problem seems to be gone and thing are faster than before. Either I changed something (I have no idea) or ZFS 0.6.5 is faster.


Me copying a file between ZFS filesystems with rsync:

rsync -av --progress test.dat /pool2/Media/temp/test2.dat
sending incremental file list
test.dat
  4,584,408,122 100%  117.91MB/s    0:00:37 (xfr#1, to-chk=0/1)

sent 4,585,527,474 bytes  received 35 bytes  119,104,610.62 bytes/sec
total size is 4,584,408,122  speedup is 1.00


Me copying within the same filesystem:

rsync -av --progress test.dat test2.dat
sending incremental file list
test.dat
  4,584,408,122 100%  126.24MB/s    0:00:34 (xfr#1, to-chk=0/1)

sent 4,585,527,474 bytes  received 35 bytes  129,169,788.99 bytes/sec
total size is 4,584,408,122  speedup is 1.00

**Comment by behlendorf** [comment] 2015-10-13 20:35
@rbabchis thanks for following up.  There were a significant number of performance improvements in 0.6.5.x so it's definitely possible they address this issue.  I'm glad to hear things are working well for you again.  Since this issue can no longer be reproduced, and hasn't been reported by others, I'm going to close it out.

**Closed by behlendorf** 2015-10-13 20:35 UTC
Labels: Performance
