### ISSUE TITLE
Task blocked, traces in syslog

### ISSUE THREAD

**Issue by aikudinov** [zfsonlinux/zfs#4146] opened 2015-12-27 19:29 UTC
Got this in syslog: http://pastebin.ca/3304890
Ubuntu 15.10, swap on zvol

[3725092.918403] INFO: task dpkg:10163 blocked for more than 120 seconds.
[3725092.918407]       Tainted: P           OE   4.2.0-19-generic #23-Ubuntu
[3725092.918408] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[3725092.918409] dpkg            D ffff88041fc96640     0 10163   5700 0x00000000
[3725092.918412]  ffff88005bc87248 0000000000000086 ffff88040d68a580 ffff8800c8adf080
[3725092.918414]  ffff88005bc87278 ffff88005bc88000 ffff880035169424 ffff8800c8adf080
[3725092.918415]  00000000ffffffff ffff880035169428 ffff88005bc87268 ffffffff817ec197
[3725092.918416] Call Trace:
[3725092.918424]  [<ffffffff817ec197>] schedule+0x37/0x80
[3725092.918426]  [<ffffffff817ec44e>] schedule_preempt_disabled+0xe/0x10
[3725092.918428]  [<ffffffff817ee025>] __mutex_lock_slowpath+0xb5/0x120
[3725092.918429]  [<ffffffff817ee0b3>] mutex_lock+0x23/0x40
[3725092.918464]  [<ffffffffc022e616>] zfs_zinactive+0x56/0x1a0 [zfs]
[3725092.918485]  [<ffffffffc0227eb1>] zfs_inactive+0x61/0x270 [zfs]
[3725092.918488]  [<ffffffff8119414e>] ? truncate_pagecache+0x5e/0x70
[3725092.918508]  [<ffffffffc023eff7>] zpl_evict_inode+0x47/0x60 [zfs]
[3725092.918511]  [<ffffffff8121878a>] evict+0xba/0x180
[3725092.918512]  [<ffffffff8121888a>] dispose_list+0x3a/0x50
[3725092.918513]  [<ffffffff8121997a>] prune_icache_sb+0x5a/0x80
[3725092.918516]  [<ffffffff812009ef>] super_cache_scan+0x14f/0x1a0
[3725092.918518]  [<ffffffff81194f0e>] shrink_slab+0x20e/0x3b0
[3725092.918520]  [<ffffffff81199729>] shrink_zone+0x2b9/0x2d0
[3725092.918521]  [<ffffffff811998ad>] do_try_to_free_pages+0x16d/0x400
[3725092.918523]  [<ffffffff81199c4a>] try_to_free_pages+0x10a/0x150
[3725092.918525]  [<ffffffff8118ba4b>] __alloc_pages_nodemask+0x5eb/0xa10
[3725092.918527]  [<ffffffff811d3121>] alloc_pages_current+0x91/0x100
[3725092.918529]  [<ffffffff811dc618>] new_slab+0x368/0x450
[3725092.918530]  [<ffffffff811dd67f>] __slab_alloc+0x27f/0x4b0
[3725092.918534]  [<ffffffffc00f2af3>] ? spl_kmem_zalloc+0xa3/0x180 [spl]
[3725092.918536]  [<ffffffff817ee0a6>] ? mutex_lock+0x16/0x40
[3725092.918545]  [<ffffffffc019264d>] ? dbuf_read+0x66d/0x860 [zfs]
[3725092.918547]  [<ffffffff817ee0a6>] ? mutex_lock+0x16/0x40
[3725092.918548]  [<ffffffff811df845>] __kmalloc_node+0xb5/0x2e0
[3725092.918551]  [<ffffffffc00f2af3>] spl_kmem_zalloc+0xa3/0x180 [spl]
[3725092.918560]  [<ffffffffc0192dd1>] dbuf_hold_impl+0x41/0xa0 [zfs]
[3725092.918570]  [<ffffffffc019312f>] dbuf_hold+0x2f/0x60 [zfs]
[3725092.918583]  [<ffffffffc01ac4c5>] dnode_hold_impl+0x85/0x4e0 [zfs]
[3725092.918586]  [<ffffffffc00f3c62>] ? spl_kmem_cache_alloc+0x72/0x7e0 [spl]
[3725092.918598]  [<ffffffffc01ac939>] dnode_hold+0x19/0x20 [zfs]
[3725092.918609]  [<ffffffffc019b4c6>] dmu_bonus_hold+0x36/0x280 [zfs]
[3725092.918626]  [<ffffffffc01d3bde>] sa_buf_hold+0xe/0x10 [zfs]
[3725092.918646]  [<ffffffffc022dd24>] zfs_zget+0x1b4/0x330 [zfs]
[3725092.918666]  [<ffffffffc02373d4>] ? zio_rewrite+0x64/0x70 [zfs]
[3725092.918686]  [<ffffffffc022f4d0>] ? zil_add_block+0x190/0x190 [zfs]
[3725092.918707]  [<ffffffffc02296e3>] zfs_get_data+0x63/0x2f0 [zfs]
[3725092.918727]  [<ffffffffc022f4d0>] ? zil_add_block+0x190/0x190 [zfs]
[3725092.918747]  [<ffffffffc023d1f0>] ? zpl_write_common_iovec+0xe0/0xe0 [zfs]
[3725092.918767]  [<ffffffffc023198e>] zil_commit.part.11+0x62e/0x7e0 [zfs]
[3725092.918787]  [<ffffffffc0231b57>] zil_commit+0x17/0x20 [zfs]
[3725092.918810]  [<ffffffffc023d4f9>] zpl_writepages+0xd9/0x170 [zfs]
[3725092.918812]  [<ffffffff8119049e>] do_writepages+0x1e/0x30
[3725092.918814]  [<ffffffff8118343c>] __filemap_fdatawrite_range+0xcc/0x100
[3725092.918816]  [<ffffffff81183543>] filemap_fdatawrite_range+0x13/0x20
[3725092.918818]  [<ffffffff812302f5>] SyS_sync_file_range+0x145/0x160
[3725092.918820]  [<ffffffff817f01f2>] entry_SYSCALL_64_fastpath+0x16/0x75

**Comment by behlendorf** [comment] 2015-12-28 18:08
This looks like a duplicate of #4106, there is a fix in #4124 currently under review.

**Closed by behlendorf** 2015-12-28 18:08 UTC
