### ISSUE TITLE
PANIC at dnode.c:179:dnode_dest() :: VERIFY3(((*(volatile typeof((&dn->dn_mtx)->m_owner) *)&((&dn->dn_mtx)->m_owner))) == ((void *)0)) failed (ffff9e111a660fd0 == (null))

### ISSUE THREAD

**Issue by makhomed** [zfsonlinux/zfs#8221] opened 2018-12-23 11:40 UTC
### System information
Type | Version/Name
 --- | --- 
Distribution Name	| CentOS
Distribution Version	| CentOS Linux release 7.5.1804 (Core)
Linux Kernel	| 3.10.0-862.11.6.el7.x86_64
Architecture	| x86_64
ZFS Version	| 0.7.11-1
SPL Version	| 0.7.11-1

zfs kernel modules are installed from zfs-kmod repo.
```baseurl=http://download.zfsonlinux.org/epel/7.5/kmod/$basearch/```

### Describe the problem you're observing
high CPU load in kernel space, high LA==12.9, very slow server work.
```
top - 13:18:07 up 99 days, 13:21,  2 users,  load average: 12.94, 12.98, 12.42
Tasks: 361 total,   2 running, 359 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.6 us, 77.0 sy,  0.0 ni,  1.9 id, 18.3 wa,  0.0 hi,  2.1 si,  0.0 st
KiB Mem : 32841508 total,   374732 free,  1661684 used, 30805092 buff/cache
KiB Swap:        0 total,        0 free,        0 used.   149192 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
17593 root      20   0       0      0      0 D  69.3  0.0  10:00.01 [arc_prune]
  889 root      20   0       0      0      0 D  69.0  0.0 244:48.27 [arc_prune]
 5260 root      20   0       0      0      0 D  64.9  0.0 105:54.28 [arc_prune]
 6171 root      20   0       0      0      0 D  61.7  0.0 105:42.65 [arc_prune]
18350 root      20   0       0      0      0 D  60.6  0.0  10:01.86 [arc_prune]
15809 root      20   0       0      0      0 D  60.0  0.0  10:17.38 [arc_prune]
18457 root      20   0       0      0      0 D  57.4  0.0   9:59.56 [arc_prune]
16217 root      20   0       0      0      0 D  56.2  0.0  10:19.92 [arc_prune]
   64 root      20   0       0      0      0 R  45.5  0.0  36:57.67 [kswapd0]
15055 root      20   0  165812   3436    304 D  28.7  0.0   5:32.79 /sbin/zfs list -H -p -o name,creation -t snap
24052 root      20   0  165812   3420    280 D  27.5  0.0   4:52.00 /sbin/zfs list -H -p -o name,creation -t snap
 1008 root      20   0  164808   1612      0 S  13.6  0.0   0:29.89 sshd: root@pts/0
  890 root      20   0       0      0      0 S  13.3  0.0 498:04.86 [arc_reclaim]
16833 root      20   0  338528  30620      0 S   9.0  0.1  65:21.64 /usr/bin/python -Es /usr/sbin/tuned -l -P
26520 root      20   0  171792   1488    272 R   6.1  0.0   0:03.28 top
```

### Describe how to reproduce the problem
1. Install CentOS 7.5 on two source servers with zfs from zfs-kmod repo.
2. Install CentOS 7.5 on target server with zfs from zfs-kmod repo.
3. On source servers install https://github.com/makhomed/autosnap
```
interval hourly 24
interval daily  15

exclude tank
```
4. On target server install https://github.com/makhomed/autosync
5. On source servers create 100+ zvols for KVM virtual machines disk images.
6. Configure continuous replication of zvols from source servers to target server.
```
source 11.11.11.11 # kvm-hardware-node

exclude tank

destination tank/mirror/kvm-hardware-node
```
```
source 22.22.22.22 # kvm2-hardware-node

exclude tank

destination tank/mirror/kvm2-hardware-node
```
7. On target server install https://github.com/makhomed/autobackup
8. On target server configure autobackup to make daily backups from 10+ servers in OpenVZ and raw mode.
9. Don't reboot target server 99 days.

### Include any warning/errors/backtraces from the system logs
message in /var/log/messages
```
backup-server kernel: VERIFY3(((*(volatile typeof((&dn->dn_mtx)->m_owner) *)&((&dn->dn_mtx)->m_owner))) == ((void *)0)) failed (ffff9e111a660fd0 ==           (null))
backup-server kernel: PANIC at dnode.c:179:dnode_dest()
backup-server kernel: Showing stack for process 891
backup-server kernel: CPU: 1 PID: 891 Comm: dbu_evict Tainted: P           OE  ------------   3.10.0-862.11.6.el7.x86_64 #1
backup-server kernel: Hardware name: Supermicro Super Server/X10SDV-4C-TLN2F, BIOS 1.3 01/05/2018
backup-server kernel: Call Trace:
backup-server kernel: [<ffffffffa3d135d4>] dump_stack+0x19/0x1b
backup-server kernel: [<ffffffffc0743ed4>] spl_dumpstack+0x44/0x50 [spl]
backup-server kernel: [<ffffffffc0743fa9>] spl_panic+0xc9/0x110 [spl]
backup-server kernel: [<ffffffffa37f9d71>] ? __slab_free+0x81/0x2f0
backup-server kernel: [<ffffffffa36d7c3e>] ? account_entity_dequeue+0xae/0xd0
backup-server kernel: [<ffffffffa36db7bc>] ? dequeue_entity+0x11c/0x5e0
backup-server kernel: [<ffffffffc0b42bd4>] dnode_dest+0xb4/0xf0 [zfs]
backup-server kernel: [<ffffffffc074045d>] spl_kmem_cache_free+0x2d/0x1f0 [spl]
backup-server kernel: [<ffffffffc0b431f4>] dnode_destroy+0x1b4/0x220 [zfs]
backup-server kernel: [<ffffffffc0b43dfb>] dnode_special_close+0x4b/0x70 [zfs]
backup-server kernel: [<ffffffffc0b36758>] dmu_objset_evict_done+0x18/0x230 [zfs]
backup-server kernel: [<ffffffffc0b43210>] dnode_destroy+0x1d0/0x220 [zfs]
backup-server kernel: [<ffffffffc0b432c5>] dnode_buf_evict_async+0x65/0xb0 [zfs]
backup-server kernel: [<ffffffffc0741d2c>] taskq_thread+0x2ac/0x4f0 [spl]
backup-server kernel: [<ffffffffa36d1fe0>] ? wake_up_state+0x20/0x20
backup-server kernel: [<ffffffffc0b43260>] ? dnode_destroy+0x220/0x220 [zfs]
backup-server kernel: [<ffffffffc0741a80>] ? taskq_thread_spawn+0x60/0x60 [spl]
backup-server kernel: [<ffffffffa36bdf21>] kthread+0xd1/0xe0
backup-server kernel: [<ffffffffa36bde50>] ? insert_kthread_work+0x40/0x40
backup-server kernel: [<ffffffffa3d255f7>] ret_from_fork_nospec_begin+0x21/0x21
backup-server kernel: [<ffffffffa36bde50>] ? insert_kthread_work+0x40/0x40
```

**Comment by loli10K** [comment] 2018-12-23 11:44
Duplicate of #7814

**Comment by bunder2015** [comment] 2018-12-26 15:49
Closing as duplicate, please see 7814

**Closed by bunder2015** 2018-12-26 15:49 UTC
