### ISSUE TITLE
Can't remove zvol from zpool created on multipath device

### ISSUE THREAD

**Issue by arko-pl** [zfsonlinux/zfs#2882] opened 2014-11-10 09:55 UTC
Hello,
I've got problem with removing zvol from multipath device. It always ends up with: dataset is busy.

multipath config:

```
defaults {
    udev_dir            /dev
    path_grouping_policy    multibus
    getuid_callout      "/lib/udev/scsi_id --whitelisted --page=0x80 --device=/dev/%n"
}

blacklist {
    wwid    "*"
}

blacklist_exceptions {
    wwid    "SSCST_BIO0db6cd0cc51caa7dd864405"
}

multipaths {
    multipath {
    wwid        "SSCST_BIO0db6cd0cc51caa7dd864405"
    alias       "mpio+SSCST_BIO0db6cd0cc51caa7dd864405"
    path_selector   "round-robin 0"
    path_grouping_policy    group_by_serial
    failback    manual
    prio        const
    no_path_retry   1
    rr_min_io_rq    1
    flush_on_last_del   no
    }
}
```

Zpool is created as follows:
`zpool create pool -f scsi-mpio+SSCST_BIO0db6cd0cc51caa7dd864405`

where scsi-mpio+SSCST_BIO0db6cd0cc51caa7dd864405 is a symlink to mapped device.

Then zvol is created with command:
`zfs create -V 1G pool/zvol`

and then command:
`zfs destroy -f pool/zvol`
ends with:
`cannot destroy 'pool/zvol': dataset is busy`

The only way to remove zpool is to clear data at the beginning and end of mpio device and reboot the system.
Tested on ZFS 0.6.3 and with the latest version form repository. Linux kernel is mainline 3.10.

**Comment by behlendorf** [comment] 2016-11-15 05:41
Closing.  This is believed to have been caused by the zvol actually being busy, in which case the destroy should fail.

**Closed by behlendorf** 2016-11-15 05:41 UTC

**Comment by jshupe** [comment] 2019-01-18 01:21
I know this is a really old post, but for anyone who comes along needing the info:

```
$ sudo ls -l /dev/zvol/data1/1TB_POC 
lrwxrwxrwx 1 root root 9 Jan 17 19:16 /dev/zvol/data1/1TB_POC -> ../../zd0
$ sudo multipathd remove path zd0
ok
$ sudo zfs destroy -r data1/1TB_POC
```

**Comment by jshupe** [comment] 2019-01-18 05:02
Blacklisting /dev/zd devices in multipathd is the best solution, as I found other issues with iSCSI/ZFS and multipath that are resolved by that.
