### ISSUE TITLE
Missing dep in ZFS DKMS package

### ISSUE THREAD

**Issue by Rudd-O** [zfsonlinux/zfs#7919] opened 2018-09-17 00:15 UTC
Ooops.  It looks like the ZFS DKMS packages were missing dep `elfutils-libelf-devel`.

```
configure:14846: result: no
configure:14982: checking kernel source directory
configure:15025: result: /lib/modules/4.18.7-3.pvops.qubes.x86_64/build
configure:15036: checking kernel build directory
configure:15063: result: /lib/modules/4.18.7-3.pvops.qubes.x86_64/build
configure:15066: checking kernel source version
configure:15114: result: 4.18.7-3.pvops.qubes.x86_64
configure:15127: checking kernel file name for module symbols
configure:15156: result: Module.symvers
configure:15255: checking whether modules can be built
configure:15284: cp conftest.c conftest.h build && make modules -C /lib/modules/4.18.7-3.pvops.qubes.x86_64/build EXTRA_CFLAGS=-Werror -Wframe-larger-than=4096   M=/var/lib/dkms/zfs/0.8.0/build/build 
Makefile:940: *** "Cannot generate ORC metadata for CONFIG_UNWINDER_ORC=y, please install libelf-dev, libelf-devel or elfutils-libelf-devel".  Stop.
configure:15287: $? = 2
```

**Comment by Fabian-Gruenbichler** [comment] 2018-09-17 10:09
On Sun, Sep 16, 2018 at 05:15:10PM -0700, Rudd-O wrote:
> Ooops.  It looks like the ZFS DKMS packages were missing dep `elfutils-libelf-devel`.
> 
> ```
> configure:14846: result: no
> configure:14982: checking kernel source directory
> configure:15025: result: /lib/modules/4.18.7-3.pvops.qubes.x86_64/build
> configure:15036: checking kernel build directory
> configure:15063: result: /lib/modules/4.18.7-3.pvops.qubes.x86_64/build
> configure:15066: checking kernel source version
> configure:15114: result: 4.18.7-3.pvops.qubes.x86_64
> configure:15127: checking kernel file name for module symbols
> configure:15156: result: Module.symvers
> configure:15255: checking whether modules can be built
> configure:15284: cp conftest.c conftest.h build && make modules -C /lib/modules/4.18.7-3.pvops.qubes.x86_64/build EXTRA_CFLAGS=-Werror -Wframe-larger-than=4096   M=/var/lib/dkms/zfs/0.8.0/build/build 
> Makefile:940: *** "Cannot generate ORC metadata for CONFIG_UNWINDER_ORC=y, please install libelf-dev, libelf-devel or elfutils-libelf-devel".  Stop.
> configure:15287: $? = 2

as the error indicates, this depends on your kernel config and is not
(directly) caused by ZFS.

**Comment by Rudd-O** [comment] 2018-09-17 10:29
I agree that depends on kernel config.  The scenario:

Update from 4.9 to 4.17.3.
DKMS launches to install ZFS kmod and mkinitrd, fails because missing dep.
Reboot system.
System unbootable.

This can be averted by adding the buildrequires I mentioned to the zfs dkms package.

**Comment by Fabian-Gruenbichler** [comment] 2018-09-17 14:52
On Mon, Sep 17, 2018 at 03:29:33AM -0700, Rudd-O wrote:
> I agree that depends on kernel config.  The scenario:
> 
> Update from 4.9 to 4.17.3.
> DKMS launches to install ZFS kmod and mkinitrd, fails because missing dep.
> Reboot system.
> System unbootable.
> 
> This can be averted by adding the buildrequires I mentioned to the zfs dkms package.

those dependencies belong in your kernel(-dev/dkms tooling/...) packages,
not zfs(-dkms). there is no reason to pull them in if running a kernel
configured with a different unwinder (e.g., anything with a non-default
config, or anything < 4.14).

if you are using DKMS, you *always* need to check whether
the module build was successful before rebooting after a ZFS or kernel
update anyway.

**Comment by behlendorf** [comment] 2018-09-17 23:27
Was this a custom kernel or the stock Fedora kernel?  If it was the stock kernel let's get an new issue opened with Fedora to add the missing dependency to the correct package.

**Comment by Rudd-O** [comment] 2018-09-18 06:31
Can someone loop in @marmarek?  I have a Qubes bug pointed to this one but I don't have my workstation anywhere close.  Thanks.

**Comment by behlendorf** [comment] 2019-04-17 21:06
Closing.  The missing dependency here should not be required by the zfs-kmod packages but dependent dkms package.

**Closed by behlendorf** 2019-04-17 21:06 UTC
Labels: Component: Packaging, Missing Template, Type: Building
