### ISSUE TITLE
usages are not updating under 0.6.3 

### ISSUE THREAD

**Issue by cai** [zfsonlinux/zfs#2404] opened 2014-06-16 20:51 UTC
Upgraded my server from 0.6.2 to 0.6.3 this morning. "zpool upgrade" and "zfs upgrade" all reported features enabled. When I copied files into one of the zfs filesystems, I noticed "zfs list" and "du" are not updating usage on that filesystem. Anyone seeing the same problem?

Haisong

**Comment by behlendorf** [comment] 2016-03-24 01:19
I'm closing this issue out since we've had no additional reports of this and it was against an old version of ZoL (0.6.5.3).  @cai if you're still able to reproduce this with a newer version let me know and I'll reopen this.

**Closed by behlendorf** 2016-03-24 01:19 UTC
Labels: Bug
