### ISSUE TITLE
ZFS pool made out of a 2x SSDPE2KE020T7 mirror shows CHKSUM errors

### ISSUE THREAD

**Issue by Thoro** [zfsonlinux/zfs#9622] opened 2019-11-25 14:58 UTC
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| CentOS
Distribution Version	|  7
Linux Kernel	|   4.19.72
Architecture	| x86_64
ZFS Version	|  0.8.1
SPL Version	|  -

### Describe the problem you're observing
The two ssds constantly receive additional CHKSUM errors, but smartctl shows 0 errors.

Also no additional messages in dmesg that might hint on an issue.

The ssds are formatted in 512K mode, which might be an issue? (There was an issue with Samsung 850 / 860 ssds that deleted data with ashift=9)

### Describe how to reproduce the problem

unclear

**Comment by Ornias1993** [comment] 2019-11-25 16:06
Did you test different controllers and/or cables? Checksum error with good drives (thats assuming they are actually good) are often caused by controller or cable issues.

**Comment by Thoro** [comment] 2019-11-25 16:47
Sadly that's impossible, it's NVMe drives, no cables to exchange, or controllers ...

There's a total of 4 drives, but it happens on all 4 of them, I moved the mirror between them to test if any of the drives has an issue.

It's an AMD Epyc System.

**Comment by Ornias1993** [comment] 2019-11-25 17:03
May I ask why you formated SSD's ashift=9?

**Comment by Thoro** [comment] 2019-11-25 18:48
Space savings, my dataset benefits tremendously from ashift=9 => saves over 300 GB

**Comment by kpande** [comment] 2019-11-25 21:07
yeah, but, don't do that. ashift=9 is awful even when you configure the nvme device to use it.

**Comment by richardelling** [comment] 2019-11-25 21:49
Depending on the device, the small physical block size of 512 (aka ashift=9) is correct and optimal. In particular, the high-performance NVMe drives today are physical block size=512.

**Comment by kpande** [comment] 2019-11-25 21:57
@richardelling  my organisation has observed up to 4x reduction in IOPS and throughput when using `ashift=9` on several brands of SSD including those hosted on Amazon EC2. in my experience, most nvme flash is using 4k *or larger* page sizes, most commonly 8k.... not 512b. where is the source for your claim?

**Comment by richardelling** [comment] 2019-11-26 05:07
See Intel P480?/D480?, Micron X100, Samsung PCIe gen4 PM1733/PM1735... and all of the SCMs (which are cache-line optimized). For high-performance, enterprise grade SSDs 512 byte sectors is fine because many of the legacy enterprise apps are optimized for 512 byte blocks.

**Comment by Thoro** [comment] 2019-11-26 07:16
@kpande The limitation of performance comes from ZFS since it's unable to handle more than 40k 4k blocks / s  (on ashift=9) -> therefore you get better performance when using ashift 12 or 13

But I really don't care about that performance in this case, here it's purely about space savings.

But I can try the other two on 4k sectors and then with ashift=12 and zfs send over the datasets and see what happens on them

**Comment by Ornias1993** [comment] 2019-11-26 07:25
@Thoro 
besides the offtopic ashift=9 vs ashift=12 discussion: I think this is not a bug report or feature request anyway...

In accordance with the Contribution guidelines, and like @kpande rightfully suggested in #9623 , I suggest you close the issue and use the mailing list for support questions like this.

https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md

**Closed** 2019-11-27 14:56 UTC
