### ISSUE TITLE
Using normalization=normKD, filenames become unusable if there is a conflict during their creation

### ISSUE THREAD

**Issue by L-B** [zfsonlinux/zfs#3707] opened 2015-08-27 12:39 UTC
After creating a new dataset with the property normalization=formKD, if two files having the same normalized name are created at the same time, the second name becomes unusable.

See below for a demonstration using Roman numerals Ⅰ Ⅱ & Ⅲ, and their ASCII counterpart.

```
# zfs create -o utf8only=on -o normalization=formKD piscine/test 
```

First, create two files one by one, it all works:

```
# touch Ⅲ
# ls -l 
total 1
-rw-r--r--. 1 root root 0 Aug 27 08:14 Ⅲ
# rm Ⅲ

# touch III
# ls -l 
total 1
-rw-r--r--. 1 root root 0 Aug 27 08:14 III
# rm III
```

Create the two files together, they have the same normalization, so only the first should be created, which works:

```
# touch Ⅲ III
# ls -l 
total 1
-rw-r--r--. 1 root root 0 Aug 27 08:14 Ⅲ
# rm Ⅲ
```

After deleting it, try to create the files one by one again: now the second one does not appear, even though data can be piped to it:

```
# touch Ⅲ
# ls -l 
total 1
-rw-r--r--. 1 root root 0 Aug 27 08:15 Ⅲ
# rm Ⅲ

# touch III
# ls -l
total 0
# echo test > III
# ls -l 
total 0
```

Now trying with two files, the first is a new name using two new characters that have again the same normalization: after the try, the second name, which was still working, cannot be used anymore, and the one that was not working before still isn't.

```
# touch ⅠⅡ Ⅲ
# ls -l 
total 1
-rw-r--r--. 1 root root 0 Aug 27 08:26 ⅠⅡ
# rm ⅠⅡ 

# touch Ⅲ
# ls -l 
total 0
# touch III
# ls -l 
total 0
```

More information:
The touch return code is always 0, there's nothing in the logs, a scrub finds no error, it cannot be reproduced on Solaris 10.

The system is CentOS 7 configured to use the ZOL repository, fully upgraded.

**Comment by dasjoe** [comment] 2015-08-27 13:50
Possible duplicate of #3012

**Comment by L-B** [comment] 2015-08-27 14:20
Yes indeed, I had missed that one when looking for «normalization»
So both files are actually created, but only the first is visible. Also, It lasts until the dataset is unmounted.
I guess it's much easier to trigger the issue with the KD form, since there are more equivalent forms.
```
#  touch Ⅲ III
# ls -l 
total 1
-rw-r--r--. 1 root root  0 Aug 27 10:11 Ⅲ
# rm Ⅲ
# cat < III
# echo toto > III
# cat < III
toto
# ls -l
total 0
# cat < Ⅲ
-bash: Ⅲ: No such file or directory
# zfs umount piscine/test
# zfs mount piscine/test
# cat < III
-bash: III: No such file or directory
```

**Closed** 2019-02-16 02:32 UTC
