### ISSUE TITLE
Fedora 22 repository

### ISSUE THREAD

**Issue by mpalves** [zfsonlinux/zfs#3496] opened 2015-06-15 12:34 UTC
I think it's time to create a Fedora 22 repository, as it's been released almost three weeks ago. The RPMs from the Fedora 21 repository work just fine, so it should be trivial to extend support to the F22 release and provide a way for users to upgrade seamlessly.

**Comment by behlendorf** [comment] 2015-06-15 16:38
Duplicate of #3485.  Yes, I'll see about setting it up.

**Closed by behlendorf** 2015-06-15 16:38 UTC
