### ISSUE TITLE
Hot spares not automatically being used?

### ISSUE THREAD

**Issue by Ralithune** [zfsonlinux/zfs#4853] opened 2016-07-14 20:50 UTC
Hello, I've been struggling with the issue of getting hot spare drives to automatically kick over when a drive from the pool fails.

I have uncommented 2 lines in /etc/zfs/zed.d/zed.rc:
ZED_SPARE_ON_CHECKSUM_ERRORS=10
ZED_SPARE_ON_IO_ERRORS=1

And restarted the zed service / rebooted multiple times.  Is this all I need to do to ensure that hot spares will be automatically used in ZoL?  Or is there another step?

When I pull a drive from the Raidz2 pool I've made, it shows as having Read / Write errors and that the pool is Degraded, but it does nothing with the spare drives.

I'm running CentOS 7 3.10.0-327.22.2, and using the package from the instructions - zfs-0.6.5.7-1.el7.centos.x86_64.

Any ideas?

**Comment by kernelOfTruth** [comment] 2016-07-14 20:54
referencing https://github.com/zfsonlinux/zfs/issues/4358

**Comment by Ralithune** [comment] 2016-07-22 20:59
Is there any information available on this?  A timeline?  A peep?

**Comment by Ralithune** [comment] 2016-07-22 23:49
This same behavior occurs under Ubuntu 16.04, if it matters.

**Comment by rlaager** [comment] 2016-10-01 00:24
I'm boldly closing this as a duplicate of #4358. Let me know if you disagree.

**Closed by rlaager** 2016-10-01 00:24 UTC

**Comment by Ralithune** [comment] 2016-10-01 02:17
@rlaager This is still a problem - why would you close both bugs as duplicates of each other ... ?  If they're duplicates, you'd think you'd just close one and resolve the other.

By the way, this is still an issue - ZFS on Linux still does not automatically detect drive failure and begin the resilvering process with designated spares.  I never got this to work right, and ended up having to tell our customers that.

**Comment by rlaager** [comment] 2016-10-01 02:19
I didn't close both bugs. #4358 is still open.

I am aware this is still a problem. Hopefully Don Brady's work with zed will land in the not-too-distant future and this will be better.

**Comment by Ralithune** [comment] 2016-10-01 02:35
I was confused - for some reason I thought I got an email about both.  Sorry.

**Comment by ycs0220** [comment] 2022-10-28 08:05
I have the same problem. How can I solve it?
