### ISSUE TITLE
zfs allocating allocated segment

### ISSUE THREAD

**Issue by wangdbang** [zfsonlinux/zfs#6356] opened 2017-07-17 07:27 UTC
ENV:
zfs version: 0.7.0 rc5.
kernel version: 4.4.66
configuration: one pool with 4Xraidz1(5 hdds), one 1TB zvol(default setting), exported it with scst 3.2.0，16Gb emulex LPE 16002B. 
client: linux mutipath, ext4 file system created on the mutipath device. 
test tool: vdbench, blocksize, width=2,files=100,size=128k, xfersize=1m,fileio=sequential, operation=write,openflags=o_sync, threads=8
issue: when i run io test after a while, it has no IOs on client. and i check the storage, find the dump stack:
[ 3742.848692] PANIC: zfs: allocating allocated segment(offset=92815952896 size=163840)
[ 3742.848692] 
[ 3742.849914] Showing stack for process 19929
[ 3742.849918] CPU: 4 PID: 19929 Comm: txg_sync Tainted: P           O    4.4.66-v64 #1
[ 3742.849919] Hardware name: Supermicro X10DRi/X10DRi, BIOS 2.0 12/28/2015
[ 3742.849921]  0000000000000000 0000000000028000 ffffffff812ad192 0000000000000000
[ 3742.849924]  ffffffff8165b340 0000000000028000 ffff881040c0dc00 0000000000000003
[ 3742.849927]  ffffffffa0318317 6c6c61203a73667a 20676e697461636f 657461636f6c6c61
[ 3742.849929] Call Trace:
[ 3742.849938]  [<ffffffff812ad192>] ? dump_stack+0x4a/0x68
[ 3742.849946]  [<ffffffffa0318317>] ? vcmn_err+0x57/0xe0 [spl]
[ 3742.849949]  [<ffffffffa03140c3>] ? spl_kmem_cache_alloc+0x83/0x8a0 [spl]
[ 3742.849953]  [<ffffffffa03140c3>] ? spl_kmem_cache_alloc+0x83/0x8a0 [spl]
[ 3742.849956]  [<ffffffff8110c6be>] ? cache_flusharray+0xbe/0x120
[ 3742.849988]  [<ffffffffa0402271>] ? zfs_panic_recover+0x51/0x60 [zfs]
[ 3742.849991]  [<ffffffffa030d140>] ? avl_find+0x50/0x90 [zavl]
[ 3742.850013]  [<ffffffffa03ecc4f>] ? range_tree_add+0x27f/0x2c0 [zfs]
[ 3742.850032]  [<ffffffffa0454ff1>] ? zio_add_child+0x101/0x130 [zfs]
[ 3742.850050]  [<ffffffffa0455473>] ? zio_create+0x453/0x500 [zfs]
[ 3742.850071]  [<ffffffffa03e7e76>] ? metaslab_free_dva+0x146/0x3b0 [zfs]
[ 3742.850092]  [<ffffffffa03e8169>] ? metaslab_free+0x89/0xd0 [zfs]
[ 3742.850111]  [<ffffffffa0453ac7>] ? zio_dva_free+0x17/0x30 [zfs]
[ 3742.850129]  [<ffffffffa0458eb7>] ? zio_nowait+0x97/0x110 [zfs]
[ 3742.850151]  [<ffffffffa03f29a4>] ? spa_free_sync_cb+0x44/0x60 [zfs]
[ 3742.850173]  [<ffffffffa03f2960>] ? spa_sync_aux_dev+0x260/0x260 [zfs]
[ 3742.850185]  [<ffffffffa03a66a7>] ? bplist_iterate+0x67/0xb0 [zfs]
[ 3742.850207]  [<ffffffffa03f2dd9>] ? spa_sync+0x419/0xcc0 [zfs]
[ 3742.850211]  [<ffffffff8107c71a>] ? autoremove_wake_function+0x2a/0x50
[ 3742.850213]  [<ffffffff8107c9f3>] ? __wake_up+0x43/0x70
[ 3742.850233]  [<ffffffffa0407b12>] ? txg_sync_thread+0x2c2/0x470 [zfs]
[ 3742.850235]  [<ffffffff8110c57f>] ? __cache_free_alien+0xaf/0x130
[ 3742.850237]  [<ffffffff8107c52d>] ? __wake_up_common+0x4d/0x80
[ 3742.850240]  [<ffffffff8106faa0>] ? try_to_wake_up+0x2d0/0x2d0
[ 3742.850261]  [<ffffffffa0407850>] ? txg_thread_exit+0x40/0x40 [zfs]
[ 3742.850264]  [<ffffffffa0315640>] ? __thread_create+0x160/0x160 [spl]
[ 3742.850267]  [<ffffffffa03156b5>] ? thread_generic_wrapper+0x75/0x90 [spl]
[ 3742.850271]  [<ffffffffa0315640>] ? __thread_create+0x160/0x160 [spl]
[ 3742.850273]  [<ffffffff8106573c>] ? kthread+0xcc/0xf0
[ 3742.850275]  [<ffffffff81065670>] ? kthread_worker_fn+0xf0/0xf0
[ 3742.850279]  [<ffffffff815e8d9f>] ? ret_from_fork+0x3f/0x70
[ 3742.850280]  [<ffffffff81065670>] ? kthread_worker_fn+0xf0/0xf0

**Comment by bunder2015** [comment] 2017-07-22 05:44
Possible duplicate of #6315, #5504

**Comment by wangdbang** [comment] 2017-08-04 03:04
I verified it on zfs 0.7.0 release version, it was fixed, marks resolved.

**Comment by loli10K** [comment] 2017-08-04 04:57
> I verified it on zfs 0.7.0 release version, it was fixed, marks resolved.

Somehow i doubt that this was fixed, but as per reporter comment marking resolved: we can continue investigating this in the context of the other issues.

**Closed by loli10K** 2017-08-04 04:57 UTC
