### ISSUE TITLE
Illumos #3752 want more verifiable dbuf user eviction

### ISSUE THREAD

**Issue by kernelOfTruth** [zfsonlinux/zfs#4234] opened 2016-01-16 22:45 UTC
http://permalink.gmane.org/gmane.os.illumos.zfs/1471

http://cr.illumos.org/~webrev/will/illumos-3752/

**Comment by behlendorf** [comment] 2018-10-13 00:20
Duplicate of https://illumos.org/issues/3752, no need to additionally track it here.

**Closed by behlendorf** 2018-10-13 00:20 UTC
