### ISSUE TITLE
Mount a snap of zpool ZFS volume on Solaris 11.2 fails with new version 35

### ISSUE THREAD

**Issue by beachbum314159** [zfsonlinux/zfs#3704] opened 2015-08-25 15:46 UTC
ZFS does not support mounting a snap on the same machine because the pool guid is the same as the original.  In the past I had a tool that would modify the pool guid in the beginning of the label, and then update the checksum in the most recent uberblock. This would allow the pool to be imported.

This no longer works in Solaris 11.2 with ZFS version 35, even if I create an older version of the pool, because the ZFS label structure is still a version 35 structure AND it has changed in version 35.

I found that at the end of the uberblock structure, the pool guid and hostid were added in version 35. After I update the pool guid in the most recent uberblock, I can import the pool BUT only with the force option. Something is still not quite right in the label.  After I update the label, I see the error as shown at the bottom of this post.

In ZFS version 35, some extra checking seems to have been added for the "zpool import" command. I don't know what that is, or what else I need to patch in the label to make everything be good.

Even after I successfully import this pool with "zpool import -f", whatever is messed up in the label doesn't get fixed. Since if I export this pool, I still see this error and can only bring it back in again with "-f"

Ideas?
It would be nice if ZFS had an option to re-mount a snap on the same machine and do the pool guid updates for us, but it doesn't. Other filesystems do, but not ZFS.

  pool: pool_test
    id: 8765387508624335913
 state: UNAVAIL
status: Some critical pool data has been overwritten by another pool.
action: The pool cannot be imported as critical data is missing. You
        can try using -f to force an import, but there may not be
        enough data to override this.
config:

```
    pool_test             UNAVAIL  overwritten by another pool
      c0t2993d0  ONLINE
```

**Comment by ronnyegner** [comment] 2015-08-26 17:36
Can you please explain what you are doing with snaps of the pool? Why dont use use the snapshots in the pool?

**Comment by beachbum314159** [comment] 2015-08-26 20:06
Hi - thanks for commenting.  We need to run a backup of the filesystem.  So we run a hardware snapshot, mount it on the same machine, and can then run a backup of the hardware snap, while leaving the original filesystem in place and untouched.  We are very time constrained, and I believe the hardware supported snap runs faster than a ZFS filesystem level snap.

**Comment by ronnyegner** [comment] 2015-08-28 05:20
That´s exactly the purpose of ZFS snapshots - to have a read consistent version of the file system. In terms of speed there should be no difference to your approach....  but it is much more straigh forward and easy.

**Comment by rincebrain** [comment] 2015-08-28 08:04
You appear to be attempting to report a bug on Oracle Solaris against the unaffiliated ZFS on Linux github project.

This is unlikely to result in anything useful to you happening.

**Comment by beachbum314159** [comment] 2015-08-28 14:28
rincebrain - I know - just trying multiple avenues trying to find someone who can help.
For various reasons, I need to mount a LUN snapshot containing a ZFS filesystem on the same machine. It can't be a ZFS snapshot.  Many other filesystems support this.

Something changed in the ZFS import in Oracle Solaris zpool version 35 - was hoping to find someone here that might have an idea. I can see the uberblock structure changed, but there is more because even taking that into account, "zpool import" is still not happy.

Agree it's not a bug, it's a feature that ZFS should support, but doesn't.  Search the internet for people trying to mount a LUN snapshot of ZFS onto the same machine, and how they all want to be able to do it, and hack it up by changing the pool guid in the label and updating the most recent uberblock checksum.

This worked all the way up until Solaris 11.2 and zpool version 35.

Just looking for someone that might have some insight... I know I'm not in the right place, just trying everything I can.

**Comment by ronnyegner** [comment] 2015-08-28 14:39
@beachbum314159: I still don´t understand why ZFS should support THIS particular use case. It is completely unnecessary. ZFS has snapshots. Mount them and backup from there. There is absolutely NO performance difference between a hardware snapshot copy and accessing the ZFS snapshot itself. In fact it is most likely faster because the cache is already warmed.

**Comment by richardelling** [comment] 2015-08-28 17:46
> On Aug 28, 2015, at 7:28 AM, beachbum314159 <notifications@github.com> wrote:
> 
> rincebrain - I know - just trying multiple avenues trying to find someone who can help.
> For various reasons, I need to mount a LUN snapshot containing a ZFS filesystem on the same machine. It can't be a ZFS snapshot. Many other filesystems support this.
> 
> 

ZFS is not only a filesystem, it is also a "volume manager" and it is the latter functionality
that requires uniqueness. In other words, the path to the device is irrelevant. The metadata
on the device is relevant. So if you have a "hardware clone" of the metadata, then it is not
possible to reconcile the two and ZFS will treat as one.

The way Sun/Oracle deals with this is to not expose the "hardware clone" to the default
device search path on the same machine (see zpool import -d) or, more commonly as to
avoid operational mistakes leading to catastrophic data loss, to not expose the "hardware
clone" to the same machine ever.

If you are restricted to only use the same machine, you'll need to protect yourself from
data loss by carefully manipulating the zpool import search path.

> Something changed in the ZFS import in Oracle Solaris zpool version 35 - was hoping to find someone here that might have an idea. I can see the uberblock structure changed, but there is more because even taking that into account, "zpool import" is still not happy.
> 
> Agree it's not a bug, it's a feature that ZFS should support, but doesn't.

Not a bug. It is a feature of the sort where you load a gun and point it at your data.
We've consistently tried hard to prevent such data-deadly features from seeing the
light of day.

> Search the internet for people trying to mount a LUN snapshot of ZFS onto the same machine, and how they all want to be able to do it, and hack it up by changing the pool guid in the label and updating the most recent uberblock checksum.
> 
> 

"zpool reguid" is the command to change pool guid in the OpenZFS world.
> This worked all the way up until Solaris 11.2 and zpool version 35.
> 
> 

Good luck getting the zpool on-disk format information from Oracle :-/
> Just looking for someone that might have some insight... I know I'm not in the right place, just trying everything I can.
> 
> 

 -- richard

**Comment by beachbum314159** [comment] 2015-08-31 13:54
richardelling - thank you for your response.
We need to run a hardware snap, not a filesystem snap for a lot of reasons I'm not detailing.
"zpool reguid" is exactly what I wish Oracle Solaris supported so I wouldn't have to hack up the label myself to mount the hardware snapshot.

The mounted clone is only there temporarily while we run a Backup from it, then we unmount/delete it. So maybe the gun pointed at the data isn't loaded.     :-)

Thank you.

**Comment by beachbum314159** [comment] 2015-08-31 20:05
One reason that we don't use ZFS to make the snapshot is for portability. If we use a hardware snapshot, we can mount it on another machine to do the backup so that we don't tax the source machine during backup of the data.  I don't think that is possible if I use the built-in ZFS snapshot tool.

**Comment by ronnyegner** [comment] 2015-09-01 06:13
@beachbum314159  Yes, that´s correct. But this use case is rarely used. If you import the pool on another machine there should be no conflicts. And it should be safe in terms of accidently collision with the devices in the existing pool.

**Comment by sempervictus** [comment] 2015-09-02 20:10
Import the pool in a child VM with a mount to export data recovered from the pool back to the host. Also, just my $0.02, but Oracle may not take kindly to you playing with their on-disk format. That likely falls into reverse engineering and would be illegal and a breach of your contract terms. If you want an open format, use OpenZFS, otherwise, they want to you to pay them for support, and aren't shy about enforcing that desire.

**Comment by beachbum314159** [comment] 2015-09-03 13:43
Understood - wish they just supported the ability to mount a hardware snap on the same machine. I can do it with many other filesystems., including Open ZFS.

Open ZFS has the "zpool reguid" command, which would do the trick for us, allowing us to import the snap on the same machine.  Open ZFS saw the need for it, so should Oracle - and then I wouldn't have to change the guid and modify their label to re-mount the snap.

Appreciate everyone taking their time to comment - thank you.

**Comment by sempervictus** [comment] 2015-09-04 21:03
This is why we are all here - the Oracle implementation is basically like
NexSAN or a few other custom ones now. Alone, broken, and getting worse
daily. I would expect that we will no longer see Solaris and ZFS from them
in 10y time. Outside of the crypto support they inherited from Sun
engineers, there is little benefit to using their rusty fork, and hopefully
even that can be addressed in the next year or two. Sorry we couldn't be of
more help.

**Closed** 2019-02-16 02:30 UTC
