### ISSUE TITLE
adding spare fails during resilver

### ISSUE THREAD

**Issue by mjbedynek** [zfsonlinux/zfs#6678] opened 2017-09-25 15:20 UTC
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | CentOS
Distribution Version    | 7.4
Linux Kernel                 | 3.10.0-693.1.1.el7.x86_64
Architecture                 | x86_64
ZFS Version                  | 0.7.1-1
SPL Version                  | 0.7.1-1

### Describe the problem you're observing
Attempt to add spare to pool during vdev resilver results in failure with this message:

nvlist_lookup_string(cnv, ZPOOL_CONFIG_PATH, &path) == 0
ASSERT at zpool_vdev.c:880:get_replication()Aborted

This may be normal behavior during resilver but if not I wanted to report it.

### Describe how to reproduce the problem
1. Pool was in a DEGRADED state using its only hot spare. Resilver had successfully completed.
2. Replaced the faulty disk and initiated a replace for the faulty device. 
3. Problem occurred when I attempted to add a 2nd spare device during replace/resilver.

..9ddf had failed and spare ..735b had automatically been added to vdev. 

To replace - Issued:

```
zpool replace -f backups scsi-35000c50034ef9ddf scsi-35000c500341f3e5b
```

Then attempted to run:

```
zpool add backups spare scsi-35000c50034c44e9b
```

.. to add 2nd spare device.

### Include any warning/errors/backtraces from the system logs
There are no other errors.  Including relevant output from 'status' command.

	  raidz1-8                      DEGRADED     0     0     0
	    scsi-35000c50034c35f17      ONLINE       0     0     0
	    scsi-35000c50034c42f27      ONLINE       0     0     0
	    scsi-35000c50034ef42cf      ONLINE       0     0     0
	    scsi-35000c50034ef4b9b      ONLINE       0     0     0
	    scsi-35000c50034ef980b      ONLINE       0     0     0
	    scsi-35000c50034bfb11f      ONLINE       0     0     0
	    spare-6                     DEGRADED     0     0     0
	      replacing-0               DEGRADED     0     0     0
	        scsi-35000c50034ef9ddf  FAULTED      0     0     0  too many errors
	        scsi-35000c500341f3e5b  ONLINE       0     0     0  (resilvering)
	      scsi-35000c5003425735b    ONLINE       0     0     0
	spares
	  scsi-35000c5003425735b        INUSE     currently in use

**Comment by behlendorf** [comment] 2017-09-25 19:13
@mjbedynek thanks for reporting this.  This is definitely a corner case isn't cleanly handled which should be fixed.

**Comment by loli10K** [comment] 2017-12-26 11:02
This seems to affect OpenZFS too; the issue is also not restricted to spares, adding any type of new device results in the same assertion failure:

```
loli@openindiana:~$ POOLNAME='testpool'
loli@openindiana:~$ TMPDIR='/var/tmp'
loli@openindiana:~$ sudo zinject -c all
removed all registered handlers
loli@openindiana:~$ sudo zpool destroy -f $POOLNAME
loli@openindiana:~$ rm -f $TMPDIR/file-vdev* rm -f $TMPDIR/file-spare*
loli@openindiana:~$ truncate -s 512m $TMPDIR/file-vdev1
loli@openindiana:~$ truncate -s 512m $TMPDIR/file-vdev2
loli@openindiana:~$ sudo zpool create -f -O mountpoint=none $POOLNAME mirror $TMPDIR/file-vdev1 $TMPDIR/file-vdev2
loli@openindiana:~$ truncate -s 512m $TMPDIR/file-spare1
loli@openindiana:~$ sudo zpool add $POOLNAME spare $TMPDIR/file-spare1
loli@openindiana:~$ sudo zinject -d $TMPDIR/file-vdev2 -e nxio -T all -f 100 $POOLNAME
Added handler 5 with the following properties:
  pool: testpool
  vdev: b96e645a914e82cc
loli@openindiana:~$ sudo zpool scrub $POOLNAME
loli@openindiana:~$ sleep 1
loli@openindiana:~$ truncate -s 512m $TMPDIR/file-vdev3
loli@openindiana:~$ sudo zpool replace $POOLNAME $TMPDIR/file-vdev2 $TMPDIR/file-vdev3
loli@openindiana:~$ truncate -s 512m $TMPDIR/file-spare2
loli@openindiana:~$ sudo zpool add $POOLNAME spare $TMPDIR/file-spare2
Assertion failed: nvlist_lookup_string(cnv, "path", &path) == 0, file zpool_vdev.c, line 651
Abort
loli@openindiana:~$ sudo zpool add $POOLNAME $TMPDIR/file-spare2
Assertion failed: nvlist_lookup_string(cnv, "path", &path) == 0, file zpool_vdev.c, line 651
Abort
loli@openindiana:~$ uname -a
SunOS openindiana 5.11 master-0-g7624f180cf i86pc i386 i86pc
loli@openindiana:~$ zpool status $POOLNAME
  pool: testpool
 state: DEGRADED
  scan: resilvered 96.5K in 0h0m with 0 errors on Tue Dec 26 10:54:08 2017
config:

        NAME                         STATE     READ WRITE CKSUM
        testpool                     DEGRADED     0     0     0
          mirror-0                   DEGRADED     0     0     0
            /var/tmp/file-vdev1      ONLINE       0     0     0
            spare-1                  UNAVAIL      0     0     0
              replacing-0            UNAVAIL      0     0     0
                /var/tmp/file-vdev2  UNAVAIL      0     0     0  cannot open
                /var/tmp/file-vdev3  ONLINE       0     0     0
              /var/tmp/file-spare1   ONLINE       0     0     0
        spares
          /var/tmp/file-spare1       INUSE     currently in use

errors: No known data errors
loli@openindiana:~$ 
```

**Closed** 2017-12-28 18:15 UTC
Labels: bitesize
