### ISSUE TITLE
pool isn't imported automatically after update to 0.6.5.6 (debian jessie)

### ISSUE THREAD

**Issue by da-tex** [zfsonlinux/zfs#4496] opened 2016-04-07 07:47 UTC
The update worked and the kernel panics are gone. (Thanks @FransUrbo for that) 

Just one little thing: on system startup my pool isn't imported automatically. Manual import works.
`zpool list`
`no pools available`
`zpool import tank`
...
`zpool list`
... (everything fine)

How can I fix this?

**Comment by FransUrbo** [comment] 2016-04-07 08:47
Are you using systemd or sysv?

**Comment by ryabserg** [comment] 2016-04-07 08:58
Hello all,
I have the same problem. It's looking like zfs tries mount filesystems on read-only mountpoints. Here is a some logs (filtered):

daemon.log:
Apr  7 07:24:46 hme systemd-fsck[806]: home: clean, 28650/5480448 files, 2309961/21899264 blocks
Apr  7 07:24:46 hme systemd-fsck[727]: boot: clean, 299/73152 files, 46833/291840 blocks
Apr  7 07:24:46 hme systemd-fsck[781]: tmp: clean, 23/1709568 files, 143514/1708800 blocks
Apr  7 07:24:46 hme systemd-fsck[766]: var: clean, 12851/1709568 files, 289112/1709056 blocks
Apr  7 07:24:46 hme zfs[1903]: cannot mount '/home/COMMON': failed to create mountpoint
Apr  7 07:24:46 hme zfs[1903]: cannot mount '/home/DATA': failed to create mountpoint
Apr  7 07:24:46 hme zfs[1903]: cannot mount '/home/FILMS': failed to create mountpoint
Apr  7 07:24:46 hme zfs[1903]: cannot mount '/var/cache/apt/archives': failed to create mountpoint
Apr  7 07:24:46 hme systemd[1]: zfs-mount.service: main process exited, code=exited, status=1/FAILURE
Apr  7 07:24:46 hme systemd[1]: Failed to start Mount ZFS filesystems.
Apr  7 07:24:46 hme systemd[1]: Dependency failed for ZFS startup target.
Apr  7 07:24:46 hme systemd[1]: Dependency failed for ZFS file system shares.
Apr  7 07:24:46 hme systemd[1]: Unit zfs-mount.service entered failed state.
Apr  7 07:24:46 hme systemd[1]: var.mount: Directory /var to mount over is not empty, mounting anyway.
Apr  7 07:24:46 hme systemd[1]: tmp.mount: Directory /tmp to mount over is not empty, mounting anyway.

and messages:
Apr  7 07:24:46 hme kernel: [    3.838537] scsi 5:0:0:0: Direct-Access     ATA      ST1000DM003-9YN1 CC4C PQ: 0 ANSI: 5
Apr  7 07:24:46 hme kernel: [    3.838907] sd 5:0:0:0: [sdf] 1953525168 512-byte logical blocks: (1.00 TB/931 GiB)
Apr  7 07:24:46 hme kernel: [    3.882574] sr0: scsi3-mmc drive: 48x/48x writer dvd-ram cd/rw xa/form2 cdda tray
Apr  7 07:24:46 hme kernel: [    4.235449] PM: Starting manual resume from disk
Apr  7 07:24:46 hme kernel: [    4.365725] EXT4-fs (sda2): mounted filesystem with ordered data mode. Opts: (null)
Apr  7 07:24:46 hme kernel: [    8.321699] zavl: module license 'CDDL' taints kernel.
Apr  7 07:24:46 hme kernel: [    8.483843] ZFS: Loaded module v0.6.5.6-3, ZFS pool version 5000, ZFS filesystem version 5
Apr  7 07:24:46 hme kernel: [   11.207800] Adding 5896188k swap on /dev/sda7.  Priority:-1 extents:1 across:5896188k FS
Apr  7 07:24:46 hme kernel: [   20.104792] EXT4-fs (sda2): re-mounted. Opts: errors=remount-ro
Apr  7 07:24:46 hme kernel: [   20.166328] EXT4-fs (sda3): mounted filesystem with ordered data mode. Opts: (null)
Apr  7 07:24:46 hme kernel: [   20.215896] EXT4-fs (sda6): mounted filesystem with ordered data mode. Opts: (null)
Apr  7 07:24:46 hme kernel: [   20.242129] EXT4-fs (sda5): mounted filesystem with ordered data mode. Opts: (null)
Apr  7 07:24:46 hme kernel: [   20.257434] EXT4-fs (sda1): mounted filesystem with ordered data mode. Opts: (null)
Apr  7 07:24:46 hme kernel: [   21.103510] RPC: Registered named UNIX socket transport module.
Apr  7 07:24:46 hme kernel: [   21.103514] RPC: Registered udp transport module.
Apr  7 07:24:46 hme kernel: [   21.103516] RPC: Registered tcp transport module.
Apr  7 07:24:46 hme kernel: [   21.103517] RPC: Registered tcp NFSv4.1 backchannel transport module.
Apr  7 07:24:46 hme kernel: [   21.118655] FS-Cache: Loaded

**Comment by ryabserg** [comment] 2016-04-07 08:59
zfs mount -a
after boot helps

**Comment by ryabserg** [comment] 2016-04-07 09:02
/sbin/init -> /lib/systemd/systemd

**Comment by FransUrbo** [comment] 2016-04-07 09:46
The only difference between "my" systemd files and the ZFS ones are the change from https://github.com/zfsonlinux/zfs/issues/4474 but that can't affect the missing import (@da-tex's problem) .

And the mount problem (@ryabserg's problem) indicate that it's <code>zfs mount</code> that is at fault somehow! But I can't see anything obvious in the additional patches I've applied that can cause this...

So for me, these seems to be two separate issues - one can't import the pool and the other can't mount them... ?

**Comment by da-tex** [comment] 2016-04-07 10:02
I don't know whats exactly happening at statup (import or mount or whatever). I just know, that since the last update the pool isn't available after reboot and `zpool import tank` does fix this.

Let's wait and see if other useres have simular problems, too...

**Comment by ryabserg** [comment] 2016-04-07 19:30
From my side the problem was resolved by changing /lib/systemd/system/zfs-mount.service, strings "Before" replaced to "Requires":

[Unit]
Description=Mount ZFS filesystems
DefaultDependencies=no
Wants=zfs-import-cache.service
Wants=zfs-import-scan.service
Requires=systemd-udev-settle.service
After=systemd-udev-settle.service
After=zfs-import-cache.service
After=zfs-import-scan.service
#Before=local-fs.target
#Before=systemd-remount-fs.service
Requires=local-fs.target
Requires=systemd-remount-fs.service

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/sbin/zfs mount -a

**Comment by kiekerjan** [comment] 2016-04-26 12:54
I see the same issue as @da-tex, no pools are reported as available.
I see the following messages in my log:

>
[4.028544] systemd[1]: zfs-mount.service: Found ordering cycle on zfs-mount.service/start
[4.028547] systemd[1]: zfs-mount.service: Found dependency on zfs-import-cache.service/start
[4.028548] systemd[1]: zfs-mount.service: Found dependency on systemd-udev-settle.service/start
[4.028550] systemd[1]: zfs-mount.service: Found dependency on systemd-udev-trigger.service/start
[4.028551] systemd[1]: zfs-mount.service: Found dependency on systemd-hwdb-update.service/start
[4.028552] systemd[1]: zfs-mount.service: Found dependency on systemd-remount-fs.service/start
[4.028553] systemd[1]: zfs-mount.service: Found dependency on zfs-mount.service/start
[4.028554] systemd[1]: zfs-mount.service: Breaking ordering cycle by deleting job zfs-import-cache.service/start
[4.028556] systemd[1]: zfs-import-cache.service: Job zfs-import-cache.service/start deleted to break ordering cycle starting with zfs-mount.service/start                                                                                                                           <...several lines more with similar reports>

The solution that @ryabserg describes seems to solve my problem (by breaking the ordering cycle?)

**Comment by dechamps** [comment] 2016-04-30 15:48
kiekerjan@: from the log you posted it seems you are a victim of #205.

**Comment by dechamps** [comment] 2016-04-30 15:49
@kiekerjan: from the log you posted it appears you are a victim of zfsonlinux/pkg-zfs#205.

**Comment by kiekerjan** [comment] 2016-04-30 18:30
Thanks @dechamps, I would not have looked there.

**Comment by btbroot** [comment] 2016-05-24 20:32
Hello.

This is actually a **grave bug**. Currently, *zfs-import-cache.service* starts before *systemd-remount-fs.service* and fails to import pools because the */* filesystem is mounted read-only at this stage. See the fix below.

```diff
--- /lib/systemd/system/zfs-mount.service-	2016-05-24 15:44:31.460000000 -0400
+++ /lib/systemd/system/zfs-mount.service	2016-05-24 16:08:56.156000000 -0400
@@ -8,7 +8,7 @@
 After=zfs-import-cache.service
 After=zfs-import-scan.service
 Before=local-fs.target
-Before=systemd-remount-fs.service
+After=systemd-remount-fs.service
 
 [Service]
 Type=oneshot
```

**Comment by behlendorf** [comment] 2016-05-24 22:56
@btbroot this change doesn't appear in the main ZoL tree and will need to be addressed by the Debian packagers.  However, if you can open a PR which adds `After=systemd-remount-fs.service` we can more easily track and discuss this proposed change.

**Comment by btbroot** [comment] 2016-05-25 07:15
@behlendorf OK, pinging Debian ZFS on Linux maintainers <pkg-zfsonlinux-devel@lists.alioth.debian.org> with it

**Comment by behlendorf** [comment] 2016-05-25 19:24
@btbroot I've opened PR #4699 with the fix and a few additional systemd improvements for discussion.  Everyone please review and comment on the proposed change in behavior.

**Closed** 2016-05-27 18:57 UTC

**Comment by behlendorf** [comment] 2016-05-27 18:59
The fix has been merged to master and it's marked for inclusion in the next point release.  Hopefully the downstream distributions will pickup this change.

**Comment by btbroot** [comment] 2016-05-27 22:23
@behlendorf  Lot of thanks!

**Comment by ryabserg** [comment] 2016-05-28 07:14
It's  great news! Thanks to all!

**Comment by lots0logs** [comment] 2016-05-29 19:21
@behlendorf @da-tex @ryabserg Has anyone confirmed that 92547bc45ca9a2114662d9343ae53e5098acb627 resolves this issue? One of our users has reported experinecing this issue after I updated our zfs packages to the latest master yesterday (they were previously on a commit near the 0.6.5.6 release. I confirmed that 92547bc45ca9a2114662d9343ae53e5098acb627 is included in our latest package so it appears that this issue might not be reoslved. You can see the details of the report here: https://forum.antergos.com/topic/4544/auto-import-fail-after-upgrade-of-zfs-and-spl-from-0-6-5-6-to-0-6-5-7 Any insight you have will be much appreciated. Thanks! :smile:

**Comment by behlendorf** [comment] 2016-05-31 15:52
@lots0logs I wasn't able to reproduce the issue locally but the `After=systemd-remount-fs.service` should have addressed the issue reported here.  However, this patch also disables the zpool-import-scan service by default which might cause root pools to nto be automatically imported the initramfs doesn't contain a cache file.  This was done to ensure to ensure pools don't get automatically imported on two systems in a failover configuration, if the pool is only attached to one system you can safely enable it.

**Comment by lots0logs** [comment] 2016-06-01 00:55
@behlendorf That makes sense. I will pass the advice on to the user. Thanks for the quick response. Cheers!

**Comment by sunzhaoyang** [comment] 2017-03-30 08:06
Why not use @ryabserg's config file that change `local-fs.target` from `Before` to `Required`?

I had a service `intelcas.service` conflicts with zfs because 

`intelcas.service` should before `zfs.target` ,but `intelcas.service` dependencies all after `local-fs.target`.

that cause  ordering cycle of systemd
