### ISSUE TITLE
KERNEL PANIC when sending raw encrypted stream

### ISSUE THREAD

**Issue by UralZima** [zfsonlinux/zfs#6919] opened 2017-12-02 10:28 UTC
Hi. Since encryption was merged, I am still trying to make some backups, and with no success.
I successfully use encryption more than 1mo, but can't backup data.
I use zfs*-9999 from gentoo, freshly compiled 4 days ago.

zpool create -f -o ashift=12 -O normalization=formD -m none -R /.bk bke /dev/mapper/bknew
zfs create -o compression=on -o atime=off -o primarycache=none -o secondarycache=none -o mountpoint=none bke/work
zfs create -o compression=on -o atime=off -o primarycache=none -o secondarycache=none -o mountpoint=none bke/work/root
zfs snapshot -r mypool/n/R@bk
zfs send -w -c -v -R mypool/n/R@bk | zfs recv -u -d -F -s -v bke/work/root //goes ok
zfs create -o compression=on -o atime=off -o primarycache=none -o secondarycache=none -o mountpoint=none bke/work/home
zfs snapshot -r mypool/n/H@bk
zfs send -w -c -v -R mypool/n/H@bk | zfs recv -u -d -F -s -v bke/work/home

After some time of sending I get kernel panic, sending progress stops, the system is partially functioning, no pm-suspend, every console gets
Message from syslogd@local at Sat Dec  2 03:45:05 2017 ...
local kernel: VERIFY3(0 == dmu_object_set_nlevels(rwa->os, drro->drr_object, drro->drr_nlevels, tx)) failed (0 == 22)

Message from syslogd@local at Sat Dec  2 03:45:05 2017 ...
local kernel: PANIC at dmu_send.c:2540:receive_object()

ZFS become very very slow until reboot

Please help zfs send/recv raw stream!

**Comment by sjau** [comment] 2017-12-02 10:29
I think this is the issue I'm having:

https://github.com/zfsonlinux/zfs/issues/6821

**Comment by tcaputi** [comment] 2017-12-07 16:35
@sjau is correct. This is a duplicate of #6821. We are still working on a fix. Closing as a duplicate and I will update that ticket when I have an update. The fix will be included in #6864 when it is done

**Closed by tcaputi** 2017-12-07 16:35 UTC
