### ISSUE TITLE
zfs send -R requires child datasets to have identically named snapshots 

### ISSUE THREAD

**Issue by rugubara** [zfsonlinux/zfs#6231] opened 2017-06-15 14:32 UTC
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Gentoo
Distribution Version    | current
Linux Kernel                 | 4.10.17
Architecture                 | x86_64
ZFS Version                  | 0.7.0-rc4_59_g8f7933fe
SPL Version                  | 0.7.0-rc4_4_gac48361

### Describe the problem you're observing
I have a DS with many ZVOLs defined. 

r9-008cln ~ # zfs list -r VM|grep -v @

NAME | USED | AVAIL | REFER | MOUNTPOINT |
--- | ---: | ---: | ---: | --- |
VM | 122G | 42.4G |   20K | /mnt/VM |
VM/storage | 84.3G | 42.4G |   24K | /mnt/VM/storage
VM/storage/Ansell | 38.3G | 42.4G | 37.1G | -
VM/storage/Gentoo-ZFS | 12.4G | 42.4G | 12.4G | -
VM/storage/JJW10 | 33.5G | 42.4G | 28.6G | -
VM/swap | 21.3G | 63.5G |  113M | -
VM/system | 16.7G | 42.4G | 13.3G | legacy

Automatic snapshots are enabled and taken for all child DSs except VM/swap.
`r9-008cln ~ # zfs get com.sun:auto-snapshot VM/swap`

NAME  |   PROPERTY     |          VALUE        |          SOURCE
--- | --- | --- | ---
VM/swap | com.sun:auto-snapshot | false         |         local

I try to `zfs send -R VM@zfs-auto-snap_daily-2017-06-14-0012 > /dev/null` the earlierst snapshot of the root ds VM.
`cannot send VM@zfs-auto-snap_daily-2017-06-14-0012 recursively: snapshot VM/swap@zfs-auto-snap_daily-2017-06-14-0012 does not exist` 
 
Either I spotted a bug in zfs send or I have misunderstood the concept of recursive sending. I tried to check all the admin resources referenced on the project homepage and man.

**Comment by kpande** [comment] 2017-06-15 14:34
duplicate of #5196

**Comment by kpande** [comment] 2017-06-15 14:34
oops, clicked wrong button

**Comment by kpande** [comment] 2017-06-15 14:36
https://github.com/zfsonlinux/zfs/blob/6635624020506a76cb79c65c7ff5a580c4685a0b/lib/libzfs/libzfs_sendrecv.c#L815

@behlendorf do you still agree that this behaviour is what we want?

**Comment by behlendorf** [comment] 2017-06-15 16:17
@kpande yes.  This is still the intended behavior.

**Closed** 2017-06-15 16:30 UTC
