### ISSUE TITLE
4.9-rc5+ build issue:  unknown field ‘aio_fsync’ in `struct file_operations`

### ISSUE THREAD

**Issue by DeHackEd** [zfsonlinux/zfs#5395] opened 2016-11-14 15:00 UTC
<pre>
module/zfs/zpl_file.c:841: error: unknown field ‘aio_fsync’ specified in initializer
module/zfs/zpl_file.c:841: warning: initialization from incompatible pointer type
</pre>

Caused in torvalds/linux@723c038475b78edc9327eb952f95f9881cc9d79d which was between rc-4 and rc-5

Hopefully this means we can simply remove the field entirely?

**Comment by behlendorf** [comment] 2016-11-14 17:49
Closing as duplicate of #5393.  We should add an autoconf check to do so but yes that looks like a reasonable fix.

**Closed by behlendorf** 2016-11-14 17:49 UTC
