### ISSUE TITLE
zfsonlinux Debian package is not updating

### ISSUE THREAD

**Issue by hostingnuggets** [zfsonlinux/zfs#4408] opened 2016-03-12 10:38 UTC
I am using the official zfsonlinux.org packages on my Debian 8 server as instructed on http://zfsonlinux.org/debian.html and noticed that I am still using version 0.6.5.2 but that version 0.6.5.5 is already out.

So I tried doing an apt-get update and apt-get upgrade but the zfsonlinux package does not get updated. Any ideas how to update zfsonlinux on Debian 8? or am I doing something wrong here?

**Comment by kpande** [comment] 2016-03-12 20:25
Until the project has a debian package maintainer once more, the best method is to use `make deb` in the source tree which essentially compiles rpm and converts them to deb packages using alien.

**Comment by akorn** [comment] 2016-03-13 20:42
There is also the method described in http://list.zfsonlinux.org/pipermail/zfs-discuss/2016-January/024430.html -- I've been using it successfully, but ymmv. (I certainly think it beats converting rpms to deb.)

**Comment by FransUrbo** [comment] 2016-03-13 20:45
This is a duplicate of https://github.com/zfsonlinux/pkg-zfs/issues/181. Please close this one and take the discussion there.

**Comment by behlendorf** [comment] 2016-03-15 22:37
Closing.  I've updated http://zfsonlinux.org/debian.html to reflect that those packages will no longer be getting updates.

> These packages are no longer actively maintained and will not be updated as new releases are tagged. The Debian project has announced their intention to ship ZFS in Debian and that work is currently ongoing.

**Closed by behlendorf** 2016-03-15 22:37 UTC
