### ISSUE TITLE
Kernel Panic on ARM

### ISSUE THREAD

**Issue by gordan-bobic** [zfsonlinux/zfs#3470] opened 2015-06-04 16:56 UTC
Modified kernel version 3.4.0 (ChromeOS)

2GB of RAM, panic occurred 200MB into rsyncing 8GB of files from ext4 to ZFS.

![img_20150604_174422354](https://cloud.githubusercontent.com/assets/5469306/7989656/e83e51b8-0ae2-11e5-8bd1-dbb7e2603cb7.jpg)

**Comment by behlendorf** [comment] 2015-06-05 02:15
This was a 32-bit system I assume?

**Comment by gordan-bobic** [comment] 2015-06-05 08:17
Yes, armv5tel, Kernel 3.4.0, ZoL 0.6.4.1, no special zfs/spl options or special kernel boot arguments.
I considered bumping up vmalloc, but I did not see any error messages similar to what the FAQ describes is expected to happen when vmalloc limit is reached, so I 'm not sure if that is even related.

**Comment by behlendorf** [comment] 2015-06-05 20:06
@gordan-bobic it looks like you've exhausted the virtual memory address space.  The errors for this might differ on ARM vs x86_64, but the root cause is the same.  The ABD patches targeted for the next tag are the solution to this issue, in the meanwhile you could try bumping up the vmalloc limit.

**Comment by gordan-bobic** [comment] 2015-06-06 16:02
I added vmalloc=1G (on a 2GB machine), and I can no longer reproduce this crash. Thanks. :)

**Comment by mk01** [comment] 2015-06-07 16:49
@behlendorf 

actually I was assuming that ABD to help too, but with the latest tree (as well as the previous from back Feb) I'm not even able to make initial rootfs (rsync of ~250mb from current root). (the same tree runs on x64 as expected).

but master with no mods (just vmem to max and limiting vdev + arc caches) runs surprisingly well.
(arm 32bit has 1gig ram).

**Comment by gordan-bobic** [comment] 2015-06-07 17:49
What exactly do you mean by "vmem to max" and "limiting vdev"?
I did manage to get the whole rootfs rsync-ed over, and I'm now running my Chromebook with ZFS root, but the "unable to handle kernel paging request" errors in flush-zfs-1 occur often enough that the uptime is measured in minutes, and in low single figure numbers at that.

**Comment by mk01** [comment] 2015-06-07 18:29
limiting vdev cache, arc cache and maxing vmalloc.

**Comment by mk01** [comment] 2015-06-07 18:30
```
options zfs zfs_arc_max=167772160 zfs_vdev_cache_size=2621440 zfs_prefetch_disable=1 zfs_txg_timeout=1 zvol_threads=1
```

**Comment by gordan-bobic** [comment] 2015-06-07 18:31
I find that putting vmalloc over 512MB exacerbates the "unable to handle kernel paging request" error in flush-zfs-1. :-(

**Comment by loli10K** [comment] 2018-02-11 10:23
I recently moved one NFS server (odroid-xu4) from 0.6.5.8 to 0.7.6 disabling all kinds of tuning (zfs_arc_min/max, zfs_dirty_data_max/sync, zfs_prefetch_disable ...) and i'm not seeing the only issue (`vmap allocation for size xxx failed: use vmalloc=<size> to increase size.`) that was bugging me with 0.6.5.x during heavy load.

I am going to close this now that 0.7 is the current release, we can reopen if this is still an issue.

**Closed by loli10K** 2018-02-11 10:23 UTC
Labels: Architecture Specific

**Comment by ctrlbreak-** [comment] 2018-05-26 22:46
loli10K, I realize this probably isn't the best way to ask (via github), but I'm also a recent odroid-xu4 owner, and I'm trying to get ZFS working on it.  Do you have any resources or tips you could share?
