### ISSUE TITLE
ZoL 0.6.4 on Fedora 21 claims memory until system freezes

### ISSUE THREAD

**Issue by HeinzApfel** [zfsonlinux/zfs#3320] opened 2015-04-19 20:06 UTC
My system uses more and more memory until it starts to swap and then freezes.

I already tried to set "options zfs zfs_arc_max=17179869184" in modprobe.d and verified that it's really set (/proc/spl/kstat/zfs/arcstats). Setting arc_max lower allows longer system uptime but leads to the same problem.

The system is a fresh installed Fedora 21 using kernel 3.19.3 with ZoL 0.6.4 rpm for Fedora. It has 32GB ECC memory with a raidz-2 based 6x WDC Red 4TB.
If I let the system go, it's working stable and used memory (htop report) is about 18GB.
When I then start access to the filesystem like a "find /tank -print0" or "rsync -av" over the ZFS drive, the system starts using more and more  memory.
Interrupting the "find" stops eating more memory. Memory is not released. If I export/import the pool, all memory is released.

Question: Can someone please point me to some things I could try to find the cause of the problem?

**Comment by kernelOfTruth** [comment] 2015-04-19 20:28
Things to consider:

Limit ARC's size to a little less than half of the max amount of your total amount of RAM (e.g. 15 GB), (https://github.com/zfsonlinux/zfs/issues/3259)

You might want to reduce the size of your l2arc or ZIL devices (if applicable)

Make sure that you have the latest 0.6.4.y ZFS release: https://github.com/zfsonlinux/zfs/commits/zfs-0.6.4-release which includes the following commit: https://github.com/zfsonlinux/zfs/commit/5074bfe8ade40ddc64cba5526eb1333a73621e92
(see: https://github.com/zfsonlinux/zfs/issues/3283 )

and

https://github.com/zfsonlinux/zfs/commit/e548a597d0820fecf89137c0aa7add8ad4aa340c
which also should prevent several lockup possibilities


If it's an option and you're heavily using rsync - consider using a patched rsync with the fadvise functionality http://insights.oetiker.ch/linux/fadvise/
which adds the 
```
--drop-cache
```
option


I'll see what your 

```
find /tank -print0
```
does on my system


Yes, I've observed that behavior, too that memory isn't really released - as long as ARC and the portion of SUnreclaim doesn't exceed the pre-set limit of 
```
zfs_arc_max
```
it should be expected behavior - from what I understood


Hope that helps somewhat

**Comment by HeinzApfel** [comment] 2015-04-21 08:05
Dear kernelOfTruth,

thanks for your quick and helpful reply. I tried that right away and had a more stable system since then.

By enabling the zfs-testing repository, ZFS up to commit de6d197 was installed. But still reaches swapping when doing directory searches (find) or backups (rsync).

It looks like the problem is caused by the larger number of small files and directories I have in my zpool. So far I downgraded to 0.6.4 and set "options zfs zfs_arc_meta_limit=5368709120". No longer "zfs_arc_max". This seems to fix the problem.

**Comment by chjohnst** [comment] 2015-04-21 12:54
Just out of curiosity, since this comes up frequently should we maybe in
code adjust the arc as default to only 1/4 memory as a starting point?
Similar issue happened to me in CentOS on a pretty heavily taxed NFS
server.

**Comment by kpande** [comment] 2015-04-21 12:59
@chjohnst that's different from Illumos' handling of ARC, and we should try to be as close to upstream as possible.

Solaris removed a limit that kept meta at 1/4 of the total arc because it limited performance.

**Comment by behlendorf** [comment] 2016-11-15 05:57
This issue was resolved by limiting the number of cached dnodes.

**Closed by behlendorf** 2016-11-15 05:57 UTC
