### ISSUE TITLE
zfs send -R not preserving properties across replication

### ISSUE THREAD

**Issue by saloomy2017** [zfsonlinux/zfs#5967] opened 2017-04-05 08:47 UTC
Centos 7.03
kernel-ml.x86_64                        4.9.9-1.el7.elrepo             @elrepo-kernel
zfs.x86_64                              0.6.5.9-1.el7_3.centos         @zfs     
spl.x86_64                              0.6.5.9-1.el7_3.centos         @zfs     

 According to the man page:

-R               Generate a replication stream package, which will replicate the specified filesystem, and all descendent file systems, up to the named snapshot. When received, **all properties**, snapshots, descendent file systems, and clones are preserved.

I want to preserve filesystem properties:

poola/datafiles  compression           lz4                    inherited from poola

Command to replicate :

zfs send -R poola/datafiles@today | ssh root@10.0.2.11 -C "zfs receive -F poolb"

**Note:** zfs filesystem datafiles does not exist on the target pool

After replication:

poolb/datafiles  compression           off                    default

I can't seem to replicate while preserving properties such as compression, dedupe, atime, etc..... 

How can I replicate while preserving properties so NFS mounts and such come across?

**Comment by GregorKopka** [comment] 2017-04-07 09:39
The reason is in the bold part:

> poola/datafiles compression lz4 **inherited from poola**

The properties are _inherited_ into the dataset from the parent, not a part of it.

**Comment by loli10K** [comment] 2017-07-04 17:50
This is a duplicate of https://github.com/zfsonlinux/zfs/issues/2121.

**Closed by loli10K** 2017-07-04 17:50 UTC
