### ISSUE TITLE
Dataset is Busy

### ISSUE THREAD

**Issue by vmorgo** [zfsonlinux/zfs#4442] opened 2016-03-24 02:31 UTC
Under certain conditions (not necessarily consistently duplicatable), after having created a zvol for use with KVM virtual machines, a zvol cannot be deleted.  This is evinced in the following example, where we are attempting to remove a zvol at virtpool/kvm/vmgluster1/vmgluster1.vdsk.  This volume has already been "sent" (copied in snapshot form) to another host.  The snapshot was then deleted, leaving the original volume behind.  

The VM was NOT running on the volume what the copy was performed, so the zvol was not being used.

The system has been rebooted several times.

```
[root@hatshepsut /]# zfs destroy -f virtpool/kvm/vmgluster2/vmgluster1.vdsk
cannot destroy 'virtpool/kvm/vmgluster1/vmgluster1.vdsk': dataset is busy
[root@hatshepsut /]# 

[root@hatshepsut /]# grep virtpool/kvm/vmgluster1/vmgluster1.vdsk /proc/*/mounts
[root@hatshepsut /]# 

fuser -a virtpool/kvm
/virtpool/kvm:

# zfs destroy -r virtpool
cannot destroy 'virtpool/kvm/vmgluster1/vmgluster1.vdsk': dataset is busy
[root@hatshepsut /]# 
```

NOTE: lsof won't likely list vmgluster1.vdsk, because that is a special object (a zvol), not a file.  I simply did lsof | grep vmgluster, in hopes of catching something.  No such luck, other than the interesting error about fuse.gvfsd-fuse.

```
lsof | grep vmgluster
lsof: WARNING: can't stat() fuse.gvfsd-fuse file system /run/user/1000/gvfs
      Output information may be incomplete.
[root@hatshepsut /]# 
This leads to:
[root@hatshepsut /]# ps -ef | grep 1000
root      1466 10551  0 21:08 pts/4    00:00:00 grep --color=auto 1000
vmorgo   13716     1  0 Mar18 ?        00:00:00 /usr/libexec/gvfsd-fuse /run/user/1000/gvfs -f -o big_writes
```

(But even killing off gvfs did nothing to help--I tried that on the off-chance that it had somehow gotten involved with ZFS.)

So far, the only work-around is uninstalling ZFS, rebooting the system (or at least rmmod zfs) and then reinstalling ZFS, then zpool create -f virtpool mirror /dev/sda /dev/sdb (or /dev/sda1 /dev/sdb1) to forcibly overwrite the old zpool with a new one with the same name seems to resolve this....until next time it happens.

**Comment by behlendorf** [comment] 2016-03-24 20:14
That's for the detailed by report.  From the description you've given it looks as if the device must still be open by something.  Tools like `lsof` while helpful aren't 100% reliable in this area unfortunately.  For example, if another kernel process has opened the device it won't be listed.

It sounds like we may need to add a little debugging code to determine what's going on, or grab a debug log with ftrace.  However, before doing either of those things I'd suggest trying the latest 0.6.5.6 release and see if you're still able to reproduce the issue.  It included several significant zvol related fixes which might  address this.

**Comment by DeHackEd** [comment] 2016-03-24 20:20
Other things to check are with `losetup -a` and `dmsetup table | grep 230:` to see if the loopback or device mapper drivers are using it. (Loopback is unlikely, admittedly if this is a zvol)

**Comment by vmorgo** [comment] 2016-03-24 20:35
Will also try these when next I run into dataset is busy!  Many thanks  and
many thanks for your responsiveness!


On Thu, Mar 24, 2016 at 4:20 PM, DeHackEd <notifications@github.com> wrote:

> Other things to check are with losetup -a and dmsetup table | grep 230:
> to see if the loopback or device mapper drivers are using it. (Loopback is
> unlikely, admittedly if this is a zvol)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/zfsonlinux/zfs/issues/4442#issuecomment-201003373>
>



-- 
The truth is out there...somewhere....getting wet in the rain....

**Comment by vmorgo** [comment] 2016-03-28 23:34
Bug does occur under 0.6.5.6, with the same symptoms.

DeHackED suggested using losetup -a and dmsetup table | grep 230:  The former command produced no result (DeHackEd didn't think it would), but the second one DID find "something fishy" going on, as shown in the output below:

[root@kalypso ~]# zfs list -t volume
NAME                                                USED  AVAIL  REFER  MOUNTPOINT
virtpool/kvm/cherwell01/cherwell01.vdsk             162G   484G  79.1G  -
virtpool/kvm/domcr-vm-win701/domcr-vm-win701.vdsk  83.8G   450G  40.5G  -
virtpool/kvm/domcr-winmgmt2/domcr-winmgmt2.vdsk     114G   492G  31.2G  -
virtpool/kvm/vmgluster0/vmgluster0.vdsk            41.3G   449G  3.42G  -
virtpool/kvm/vmgluster1/vmgluster1.vdsk            46.0G   453G  4.73G  -
virtpool/kvm/vmgluster2/vmgluster2.vdsk            41.3G   448G  4.76G  -

[root@kalypso ~]# zfs destroy -f virtpool/kvm/vmgluster2/vmgluster2.vdsk
cannot destroy 'virtpool/kvm/vmgluster2/vmgluster2.vdsk': dataset is busy

[root@kalypso ~]# zfs destroy -f virtpool/kvm/vmgluster2/vmgluster2-vdb.vdsk
cannot open 'virtpool/kvm/vmgluster2/vmgluster2-vdb.vdsk': dataset does not exist

[root@kalypso ~]# losetup -a

[root@kalypso ~]# dmsetup table | grep 230:
centos_vmgluster2-swap: 0 8126464 linear 230:50 2048
centos_vmgluster2-root: 0 74637312 linear 230:50 8128512
[root@kalypso ~]# 

Issuing the (possibly dangerous) command "dmsetup remove -f centos_vmgluster2-swap" and then "dmsetup remove -f centos_vmgluster-root" nuked the offending device-mapped logical devices (the ZVOLS).  Then, and only then did zfs destroy -f <full path to offending zvol> work!

("But, not being experienced with dmsetup, I do not know if I have caused damage to ZFS on the server, or if I should be able to safely use this when I am sure no one else is using an unwanted ZFS ZVOL....  Perhaps someone could let me know if this is legit way of dealing with "dataset is busy", or if I have essentially "used a nuclear bomb to remove a sink-clog"....

Thanks!

**Comment by sbonds** [comment] 2018-02-05 21:37
I found this potentially helpful observation: [ZFS issue 3735](https://github.com/zfsonlinux/zfs/issues/3735)

That issue explained why some of my zvols were getting the perma-busy and some were not. Any zvol with a Linux LVM PV header was getting held open by LVM's auto-scan feature.

The fix is to check pvdisplay for the VG name, then shut it down and export it prior to the ```zfs destroy```

    # pvdisplay
      --- Physical volume ---
      PV Name               /dev/zd64
      VG Name               vg_name
      PV Size               20.00 GiB / not usable 4.00 MiB
      Allocatable           yes
      PE Size               4.00 MiB
      Total PE              5119
      Free PE               4863
      Allocated PE          256
      PV UUID               HhldEE-NiiF-BiQH-2j9u-esRu-WIfC-uLmyYC
    # vgchange --activate n vg_name
    # vgexport vg_name
    # zfs destroy -r <name>

**Comment by behlendorf** [comment] 2018-02-06 00:31
@sbonds thanks for posting that tip.  Yes, anything holding the zvol open can cause this, and I agree it's often not obvious exactly what's responsible.  Since I'm not aware of any outstanding bugs in this area I'm closing this issue.

**Closed by behlendorf** 2018-02-06 00:31 UTC
