### ISSUE TITLE
no SIMD acceleration

### ISSUE THREAD

**Issue by ptx0** [zfsonlinux/zfs#8793] opened 2019-05-22 02:55 UTC
4.14.x, 4.19.x, 5.x all have no SIMD acceleration, it is like a turtle. very slow.

**Comment by cyphar** [comment] 2019-05-22 04:00
This is presumably because of the `kernel_fpu_begin()` and `kernel_fpu_end()` licensing changes that make it no longer possible for non-GPL modules to toggle the FPU registers and thus use SIMD. How bad is the performance impact you're seeing.

**Comment by cyphar** [comment] 2019-05-22 04:06
This is because `__kernel_fpu_{begin,end}` stopped being exported by torvalds/linux@12209993e98c5fa1855c467f22a24e3d5b8be205. As a result, non-GPL modules can no longer toggle FPU registers and thus use SIMD.

**Comment by ptx0** [comment] 2019-05-23 17:27
hey @behlendorf why the fuck would you release ZoL 0.8 when it has a major performance regression?

**Comment by ptx0** [comment] 2019-05-23 17:27
this is a **REGRESSION** not a **FEATURE**

**Comment by ptx0** [comment] 2019-05-23 17:29
i don't even see it in the fucking changelog.

**Comment by beren12** [comment] 2019-05-23 17:43
Interesting thoughts on _GPL symbols. Meanings, intent, etc. https://github.com/zfsonlinux/zfs/issues/8793 quite relevant

**Comment by tonyhutter** [comment] 2019-05-23 17:47
@ptx0 it's listed in the zfs-0.7.13 changelog (https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.7.13)
`Linux 5.0 compat: Disable vector instructions on 5.0+ kernels #8259`

**Comment by ptx0** [comment] 2019-05-23 17:51
@tonyhutter it should be in the 0.8.0 branch changelog too, as it was a change from prior RCs. how is this so difficult?

**Comment by Banandana** [comment] 2019-05-23 17:53
🍆

**Comment by behlendorf** [comment] 2019-05-23 18:07
This is an issue we intend to work on resolving, once complete I expect it to be included in a future 0.8 point release.

**Comment by cyphar** [comment] 2019-05-23 22:26
@ptx0 There's no need to start swearing at people, especially not people who are not responsible for the change which caused the performance regression. The alternatives (for ZoL) are:

  * Ask upstream to change it. I sent a patch a few days ago, and GregKH said no (categorically).
  * Violate the GPL by exporting `kernel_fpu_*` through SPL.
  * Re-implement `kernel_fpu_*` in ZFS. In principle this is not the best idea in the world, because the kernel keeps track of the FPU state in a per-CPU variable. However since preemption is disabled during FPU usage we could reimplement it (`current->thread.fpu` is publicly-accessible). But then we're treading close to GPL violation again unless we re-implement it in a clean-room fashion. We'd have to copy FreeBSD's (or Illumos's) FPU register code.

**Comment by scineram** [comment] 2019-05-23 22:27
> this is a **REGRESSION** not a **FEATURE**

Actually it's not a regression since SIMD never worked on those kernels. It's a feature since ZOL now compiles against those kernels.

**Comment by igsol** [comment] 2019-05-24 09:22
@cyphar Thanks for your efforts to convince the real "authors" of the issue. I mean you messages: https://lkml.org/lkml/2019/1/15/819 and https://lkml.org/lkml/2019/1/15/792 !

> Violate the GPL by exporting kernel_fpu_* through SPL.

Is it a violation indeed? Or are there any other reasons to not go this wrapping (well GPL condom) way in ZoL 0.8 and further versions?

**Comment by cyphar** [comment] 2019-05-24 10:24
The "GPL condom" construct is very likely a GPL violation -- by definition it is a derived work of the original interface and thus must abide the GPL as a derived work. Even if that is not a correct statement legally (I'm not a lawyer after all), it is ethically not the right thing to do. I write GPL code quite often, and I would consider it a GPL violation for someone to "GPL condom" my work.

As I said, we could actually implement it separately (as in, clean-room re-implement it) because we have to disable preemption anyway during FPU usage so you aren't likely to get nested FPU users. Nesting would be quite bad, but that's all that the per-cpu variable is actually being used for (to detect and `WARN_ON` FPU nesting).

**Comment by beren12** [comment] 2019-05-24 10:53
Greg says the condom is bad, but there's no proof of it being struck down anywhere. The SPL is GPL so that's not a violation. It can provide a similar interface and if anyone did complain, they can be reminded that the interface was available to all until an arbitrary patch removed it's availability. It's no more a violation than distributing a kernel with the patch reversed. It's also not a violation unless a court somewhere says it is. Everything is based on opinions with the entire GPL for better or worse. I agree with https://lkml.org/lkml/2019/1/15/792 and GKH seems to be a GPL zealot intent on things his way, even if the SFLC disagrees. https://lwn.net/Articles/603131/ has great insights as well. the _GPL is applied arbitrary, sometimes against the author's wishes (with GKH overriding [surprise]) and applied to long existing interfaces.

**Comment by DeHackEd** [comment] 2019-05-24 12:35
Would a "wrapper/condom" like this be an acceptable compromise?
```C
void spl_fpucontext_call(void (*functocall)(void *param), void *param) { 
    /* This may vary by architecture, etc */
    kernel_fpu_begin(); 

    functocall(param); 

    kernel_fpu_end();
}
```
ZFS doesn't have "direct" control of FPU context, the code being executed would have to be modified to conform to this style, and the wrapper ensures correct usage of the GPL functions by non-GPL code.

**Comment by cyphar** [comment] 2019-05-24 13:45
@beren12 The SFLC didn't say that the GPL condom is not a GPL violation, they said there is no problem combining ZFS with Linux because ZFS is not a derived work. Again, a GPL condom *by definition* is a derived work because it is taking an existing GPL interface and re-exporting it under a different license. I cannot see how one would argue that this is anything but a derived work (and let's not forget that APIs have been ruled as copyrightable in the US).

The GPL condom is an attempt at a technical solution to a legal problem, and I think history has taught us many times that technical solutions are generally not valid methods of solving legal problems. Courts and judges are not impartial programs that execute laws indiscriminately.

@DeHackEd Personally, I don't see how that would be different to just exporting the interface. But that's just me.

**Comment by pdf** [comment] 2019-05-24 14:18
Hang on though, if SPL is already GPL licensed, and the kernel_fpu_begin/_end calls were to happen in SPL, how is there a problem? If there is a problem with that, then surely the whole SPL has problems?

**Comment by beren12** [comment] 2019-05-24 14:52
Exactly

**Comment by cyphar** [comment] 2019-05-24 15:00
The problem is that the GPL condom is that you are using a GPL module (like SPL) to take a GPL-only interface and then exporting it as a non-GPL-only interface. The first step is fine, the second is (arguably) not.

In particular, putting the following in SPL is probably a GPL violation:

```
void condom_kernel_fpu_begin(void)
{
  kernel_fpu_begin();
}
EXPORT_SYMBOL(condom_kernel_fpu_begin);
```

**Comment by igsol** [comment] 2019-05-24 15:57
> if all the crypto code was moved to SPL (not really possible since the crypto code is CDDL) maybe this would be okay since it's not so obviously a GPL condom. But I don't know.

Why not possible? I wouldn't say about all code, but about some part only or creation/finding the code under proper license.

There is a well know VPN kernel module WireGuard.
It's licensed under 2 licenses GPL and MTI.

WireGuard contains several cryptography functions e.g. **hchacha20**:
https://git.zx2c4.com/WireGuard/tree/src/crypto/zinc/chacha20/chacha20.c#n155

As you can see it's exported via EXPORT_SYMBOL (even not EXPORT_SYMBOL_**GPL**).
`hchacha20` inside calls `kernel_cpu_begin` indirectly via `hchacha20_arch`.

I don't think that the similar code is a GPL violation.
Why ZoL can not make the same: move/create/find&use a cryptographic functions in SPL?

**Comment by ptx0** [comment] 2019-05-24 16:02
armchair lawyers, please stop.

**Comment by sempervictus** [comment] 2019-05-28 18:04
This capricious un-exporting of symbols is a joke - how is any system supposed to build on it if critical infrastructure is subject to point release removals even in backport? Stable api my donkey.
Just one more reason to build in-house kernels with all this unexport idiocy reverted along with profane commit messages to expel some of the resulting fury.
Pretty sure that spender even said in a tweet they're taking the same approach. It would probably not be a terrible idea to just keep a tree of the kernel which rebases automatically to fixup the export removals and re-export everything to generate diff's.
How is nvidia dealing with this? One would think they leverage direct FPU functions.
The last couple of years make me wonder how irrelevant and unenforceable the gplv2 has to become before it starts being a "good idea" to just blatantly relicense the module at build time "as a patch" or change the macro dealing with gpl-only export idiocy in-kernel. Upstream might even allow hijacking that code to a noop at runtine since they're mostly unconstified and don't have ro kernel mappings, which could be done from a gpl-licensed SPL to then alter how all subsequent non GPL modules are loaded and which exports they can access. In kernel function hijacking... :)

**Comment by ac000** [comment] 2019-05-28 19:20
If your talking about the in-kernel API (which I assume you are given the context), then who said it was meant to be stable?

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/process/stable-api-nonsense.rst

**Comment by fixyourcodeplease** [comment] 2019-05-28 19:29
> If your talking about the in-kernel API (which I assume you are given the context), then who said it was meant to be stable?

we have a code of conduct around here, you cannot simply call us leeches. please be considerate.

**Comment by ac000** [comment] 2019-05-28 19:42
Huh!?

Please point out where I said such a thing.

**Comment by fixyourcodeplease** [comment] 2019-05-28 19:43
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/process/stable-api-nonsense.rst

> (remember we are
talking about drivers released under a GPL-compatible license here, if your
code doesn't fall under this category, good luck, you are on your own here,
you leech)

Line 172-175. I would think this goes against Linux's own Code of Conduct, as well.

**Comment by DeHackEd** [comment] 2019-05-28 19:43
This is offtopic but I wanted to answer this specific question.

> How is nvidia dealing with this? One would think they leverage direct FPU functions.

Actually, no. Their kernel module also has a GPU above it and a userspace layer below it. The kernel doesn't actually need to do any of the FPU work.

**Comment by sempervictus** [comment] 2019-05-28 19:51
Thank you as always @DeHackEd, useful tidbit.
As for an api having to be stable, then yes, a versioned api does need to be that way from a purely functional standpoint. Pulling functionality out of future releases is one thing, backporting purposeful and intentional breakage in order to harm a group of the api consumers who's environment does not come with the license that the committer is championing, is another.
Far as armchair lawyering, I'd be interested to see someone pursue a notion of such export changes to be a license change and thus requiring the explicit consent of the original contributors as a relicensing function. :)
As so many have pointed out, this sort of thing is only harmful to actual open source projects as any internal build and many distributed binaries by corner-cutting orgs will simply flaunt the GPL and do what they will for lack of enforcement in their part of the world.

**Comment by cyphar** [comment] 2019-05-28 22:03
@fixyourcodeplease I think it's a bit over-enthusiastic to assume that @ac000 is calling anyone here a leech just because the internal kernel documentation he linked to happens to use that word in the middle of the document. As for breaking their own CoC, that document was written long before Linux had any CoC so it's possible nobody has bothered to send a patch for it. If you feel strongly about it, feel free to send one -- but I think it's quite unfair to accuse other people of saying things which they clearly didn't say.

@igsol Again, the whole `EXPORT_SYMBOL` vs `EXPORT_SYMBOL_GPL` thing is very silly in my view -- but it makes sense to me that a function which happens to use the FPU can be `EXPORT_SYMBOL` while FPU usage itself could be `EXPORT_SYMBOL_GPL` (the idea of `_GPL` is more to indicate that something is "super kernel internals"). This is not the same as re-exporting an interface through a GPL condom (ignoring the legal question, and I'll avoid armchair lawyering here) purely from an ethical perspective. But, I also happen to disagree with upstream that `XSAVE`/`XRESTORE` and a per-cpu variable is somehow a deep part of kernel internals.

**Comment by sjuxax** [comment] 2019-05-28 22:12
@tonyhutter Is it prudent to clarify that this patch has been backported to the LTS branches in a semi-public place? I knew that 5.x was impacted because of the changelog entry on 0.7.13, but didn't notice the patchset got backported. The issue that tracks this (https://github.com/zfsonlinux/zfs/issues/8259) also repeatedly lists relevant commits as affecting "Linux 5.0+".

For the record, it appears the FPU export was removed in 4.19.38 (released 2019-05-02) via d4ff57d0320bf441ad5a3084b3adbba4da1d79f8 and 4.14.120 (released 2019-05-16) via a725c5201f0807a9f843db525f5f98f6c7a4c25b.

Users of the LTS branches: be advised that (at least) as of these versions, you're subject to the same slowdown that applied to the 5.0 branch.

**Comment by tonyhutter** [comment] 2019-05-28 22:34
@sjuxax thanks, I just added a link to your comment in #8259 regarding the other kernel versions.

**Comment by scineram** [comment] 2019-05-29 13:07
zfsonfreebsd just added SIMD support 8 days ago in their repo.

**Comment by kenshin33** [comment] 2019-05-30 14:25
Q: say I modify the kernel source (locally) to export kernel_fpu_{begin,end} (EXPORT_SYMBOL instead of EXPORT_SYMBOL_GPL),  would that work?

**Comment by cyphar** [comment] 2019-05-30 15:04
Yes that would work, but a more simple solution is to modify ZoL to have a different module license. This is not something you could redistribute (of course) but it would work on your local systems.

**Comment by mskarbek** [comment] 2019-05-30 18:45
@kenshin33  just use this patch, it works -https://github.com/NixOS/nixpkgs/pull/61076/commits/7b77c27caa8617c82df5c5af6b9ce6ae010d7f9a

**Comment by JoakimZiegler** [comment] 2019-06-26 01:15
Does this issue affect any CentOS stock kernels? CentOS kernels backport a lot of stuff, so it's hard to know, although I'd assume they're not affected.

**Comment by JoakimZiegler** [comment] 2019-06-26 01:15
Does this issue affect any CentOS stock kernels? CentOS kernels backport a lot of stuff, so it's hard to know, although I'd assume they're not affected.

**Comment by behlendorf** [comment] 2019-06-26 01:36
@JoakimZiegler the CentOS and RHEL stock kernels are not impacted by this.

You can determine if this optimization is available in your ZFS build by looking at the contents of the `vdev_raidz_bench` or `fletcher_4_bench` kstats.  They will show which accelerated implementations are available, and which is being used (listed as 'fastest').  For example, this system is using the **ssse3** implementation for fletcher4 checksums.  The **original** and **scalar** implementations do not require SIMD.

```
$ cat /proc/spl/kstat/zfs/fletcher_4_bench 
0 0 0x01 -1 0 13731721123 1219835121234728
implementation   native         byteswap       
scalar           3521678781     3086177698     
superscalar      4773330131     3643282020     
superscalar4     4523515398     3239394917     
sse2             7581683132     3968268139     
ssse3            7592270740     6952238919     
fastest          ssse3          ssse3         
```

**Closed** 2019-07-12 16:31 UTC
Labels: Type: Performance, Type: Regression
