### ISSUE TITLE
Can't cancel a scrub on a readonly pool

### ISSUE THREAD

**Issue by FransUrbo** [zfsonlinux/zfs#1999] opened 2013-12-23 03:43 UTC
One would think CANCELING the scrub would be possible...

Currently, with the pool imported readonly, a scrub seems to be running:

```
  scan: scrub in progress since Sun Dec 22 05:26:52 2013
    4.31T scanned out of 21.9T at 1/s, (scan is slow, no estimated time)
    0 repaired, 19.69% done
```

**Comment by devZer0** [comment] 2016-11-04 17:53
yes, i would find read-only scrubbing without modifying anything would be quite useful if you use zfs on system without ecc. so you would have a way to avoid scrub-to-death

**Comment by richardelling** [comment] 2016-11-04 18:12
This is similar to what zdb does today, yes?
The difference is the "validation" (not "scrub" because scrub includes repair) of zdb is not aware of the current in-kernel view of the pool. For readonly pools, however, zdb will see the same data as in-kernel.

**Comment by behlendorf** [comment] 2017-07-08 00:40
Pools which are imported read-only will automatically disable a running scrub.  This needs to happen since the scrub will periodically need to write to the pool to checkpoint its progress and to potentially perform needed repairs.

Related to this there is an open PR #6209 which adds a `scrub` sub-command to `zhack` for doing an offline pool scrub.

Closing since this is working as intended.

**Closed by behlendorf** 2017-07-08 00:40 UTC
