### ISSUE TITLE
Can not install ZFS after Kernel Upgrade

### ISSUE THREAD

**Issue by salsalem** [zfsonlinux/zfs#4574] opened 2016-04-28 02:22 UTC
Using Centos with Mainline Kernel 4.5, I can not install ZFS even though I have installed sources:

Loading new spl-0.6.5.6 DKMS files...
Building for 4.5.0-1.el7.elrepo.x86_64
Module build for kernel 4.5.0-1.el7.elrepo.x86_64 was skipped since the
kernel source for this kernel does not seem to be installed.

Anyone know how to resolve?

```
[root@mgmtzfs ~]#  yum install ifs -y
Loaded plugins: fastest mirror
No Match for argument: ifs
No Packages marked for removal
Loaded plugins: fastest mirror
Loading mirror speeds from cached hostile
 * base: mirror.pac-12.org
 * elrepo: repos.dfw.lax-noc.com
 * elrepo-extras: repos.dfw.lax-noc.com
 * elrepo-kernel: repos.dfw.lax-noc.com
 * elrepo-testing: repos.dfw.lax-noc.com
 * epel: fedora-epel.mirror.lstn.net
 * extras: repos.forethought.net
 * updates: mirror.nexcess.net
Resolving Dependencies
--> Running transaction check
---> Package zfs.x86_64 0:0.6.5.6-1.el7.centos will be installed
--> Processing Dependency: zfs-kmod = 0.6.5.6 for package: zfs-0.6.5.6-1.el7.centos.x86_64
--> Processing Dependency: spl = 0.6.5.6 for package: zfs-0.6.5.6-1.el7.centos.x86_64
--> Running transaction check
---> Package spl.x86_64 0:0.6.5.6-1.el7.centos will be installed
--> Processing Dependency: spl-kmod = 0.6.5.6 for package: spl-0.6.5.6-1.el7.centos.x86_64
---> Package zfs-dkms.noarch 0:0.6.5.6-1.el7.centos will be installed
--> Processing Dependency: dkms >= 2.2.0.3-20 for package: zfs-dkms-0.6.5.6-1.el7.centos.noarch
--> Running transaction check
---> Package dkms.noarch 0:2.2.0.3-30.git.7c3e7c5.el7 will be installed
---> Package spl-dkms.noarch 0:0.6.5.6-1.el7.centos will be installed
--> Finished Dependency Resolution

Dependencies Resolved

=======================================================================================================================================================================================================================================
 Package                                              Arch                                               Version                                                                Repository                                        Size
=======================================================================================================================================================================================================================================
Installing:
 zfs                                                  x86_64                                             0.6.5.6-1.el7.centos                                                   zfs                                              330 k
Installing for dependencies:
 dkms                                                 noarch                                             2.2.0.3-30.git.7c3e7c5.el7                                             epel                                              77 k
 spl                                                  x86_64                                             0.6.5.6-1.el7.centos                                                   zfs                                               28 k
 spl-dkms                                             noarch                                             0.6.5.6-1.el7.centos                                                   zfs                                              426 k
 zfs-dkms                                             noarch                                             0.6.5.6-1.el7.centos                                                   zfs                                              1.8 M

Transaction Summary
=======================================================================================================================================================================================================================================
Install  1 Package (+4 Dependent packages)

Total download size: 2.7 M
Installed size: 15 M
Downloading packages:
(1/5): dkms-2.2.0.3-30.git.7c3e7c5.el7.noarch.rpm                                                                                                                                                               |  77 kB  00:00:00     
(2/5): spl-0.6.5.6-1.el7.centos.x86_64.rpm                                                                                                                                                                      |  28 kB  00:00:00     
(3/5): spl-dkms-0.6.5.6-1.el7.centos.noarch.rpm                                                                                                                                                                 | 426 kB  00:00:00     
(4/5): zfs-0.6.5.6-1.el7.centos.x86_64.rpm                                                                                                                                                                      | 330 kB  00:00:00     
(5/5): zfs-dkms-0.6.5.6-1.el7.centos.noarch.rpm                                                                                                                                                                 | 1.8 MB  00:00:00     
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                                                                  1.8 MB/s | 2.7 MB  00:00:01     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : dkms-2.2.0.3-30.git.7c3e7c5.el7.noarch                                                                                                                                                                              1/5 
  Installing : spl-dkms-0.6.5.6-1.el7.centos.noarch                                                                                                                                                                                2/5 
Loading new spl-0.6.5.6 DKMS files...
Building for 4.5.0-1.el7.elrepo.x86_64
Module build for kernel 4.5.0-1.el7.elrepo.x86_64 was skipped since the
kernel source for this kernel does not seem to be installed.
  Installing : zfs-dkms-0.6.5.6-1.el7.centos.noarch                                                                                                                                                                                3/5 
Loading new zfs-0.6.5.6 DKMS files...
Building for 4.5.0-1.el7.elrepo.x86_64
Module build for kernel 4.5.0-1.el7.elrepo.x86_64 was skipped since the
kernel source for this kernel does not seem to be installed.
  Installing : spl-0.6.5.6-1.el7.centos.x86_64                                                                                                                                                                                     4/5 
  Installing : zfs-0.6.5.6-1.el7.centos.x86_64                                                                                                                                                                                     5/5 
  Verifying  : zfs-0.6.5.6-1.el7.centos.x86_64                                                                                                                                                                                     1/5 
  Verifying  : zfs-dkms-0.6.5.6-1.el7.centos.noarch                                                                                                                                                                                2/5 
  Verifying  : spl-0.6.5.6-1.el7.centos.x86_64                                                                                                                                                                                     3/5 
  Verifying  : spl-dkms-0.6.5.6-1.el7.centos.noarch                                                                                                                                                                                4/5 
  Verifying  : dkms-2.2.0.3-30.git.7c3e7c5.el7.noarch                                                                                                                                                                              5/5 

Installed:
  zfs.x86_64 0:0.6.5.6-1.el7.centos                                                                                                                                                                                                    

Dependency Installed:
  dkms.noarch 0:2.2.0.3-30.git.7c3e7c5.el7                    spl.x86_64 0:0.6.5.6-1.el7.centos                    spl-dkms.noarch 0:0.6.5.6-1.el7.centos                    zfs-dkms.noarch 0:0.6.5.6-1.el7.centos                   

Complete!
[root@mgmtzfs ~]# yum list | grep kernel
 * elrepo-kernel: repos.dfw.lax-noc.com
kernel-ml.x86_64                        4.5.0-1.el7.elrepo             @elrepo-kernel
kernel-ml.x86_64                        4.5.2-1.el7.elrepo             @elrepo-kernel
**kernel-ml-devel.x86_64                  4.5.2-1.el7.elrepo             @elrepo-kernel
kernel-ml-headers.x86_64                4.5.2-1.el7.elrepo             @elrepo-kernel
**kernel-ml-tools.x86_64                  4.5.2-1.el7.elrepo             @elrepo-kernel
kernel-ml-tools-libs.x86_64             4.5.2-1.el7.elrepo             @elrepo-kernel
kernel-ml-tools-libs-devel.x86_64       4.5.2-1.el7.elrepo             @elrepo-kernel
python-perf.x86_64                      4.5.2-1.el7.elrepo             @elrepo-kernel
abrt-addon-kerneloops.x86_64            2.1.11-36.el7.centos           base     
erlang-kernel.x86_64                    R16B-03.16.el7                 epel     
kernel.x86_64                           3.10.0-327.13.1.el7            updates  
kernel-abi-whitelists.noarch            3.10.0-327.13.1.el7            updates  
kernel-debug.x86_64                     3.10.0-327.13.1.el7            updates  
kernel-debug-devel.x86_64               3.10.0-327.13.1.el7            updates  
kernel-devel.x86_64                     3.10.0-327.13.1.el7            updates  
kernel-doc.noarch                       3.10.0-327.13.1.el7            updates  
kernel-headers.x86_64                   3.10.0-327.13.1.el7            updates  
kernel-lt.x86_64                        4.4.8-1.el7.elrepo             elrepo-kernel
kernel-lt-devel.x86_64                  4.4.8-1.el7.elrepo             elrepo-kernel
kernel-lt-doc.noarch                    4.4.8-1.el7.elrepo             elrepo-kernel
kernel-lt-headers.x86_64                4.4.8-1.el7.elrepo             elrepo-kernel
kernel-lt-tools.x86_64                  4.4.8-1.el7.elrepo             elrepo-kernel
kernel-lt-tools-libs.x86_64             4.4.8-1.el7.elrepo             elrepo-kernel
kernel-lt-tools-libs-devel.x86_64       4.4.8-1.el7.elrepo             elrepo-kernel
kernel-ml-doc.noarch                    4.5.2-1.el7.elrepo             elrepo-kernel
kernel-tools.x86_64                     3.10.0-327.13.1.el7            updates  
kernel-tools-libs.x86_64                3.10.0-327.13.1.el7            updates  
kernel-tools-libs-devel.x86_64          3.10.0-327.13.1.el7            updates  
libreport-plugin-kerneloops.x86_64      2.1.11-32.el7.centos           base     
lirc-disable-kernel-rc.x86_64           0.9.1a-4.el7                   epel     
perf.x86_64                             4.5.2-1.el7.elrepo             elrepo-kernel
php-symfony-http-kernel.noarch          2.7.11-2.el7                   epel     
texlive-l3kernel.noarch                 2:svn29409.SVN_4469-38.el7     base     
texlive-l3kernel-doc.noarch             2:svn29409.SVN_4469-38.el7     base     
[root@mgmtzfs ~]# 
```

**Comment by gmelikov** [comment] 2016-05-05 15:57
Did you install kernel sources to 4.5.0-1.el7.elrepo.x86_64 or just kernel-devel? 
You have to install sources exactly to 4.5.0.

**Comment by loli10K** [comment] 2017-08-17 11:58
Likely caused by missing kernel sources, closing.

**Closed by loli10K** 2017-08-17 11:58 UTC
