### ISSUE TITLE
ashift= doesn't make sense for zpool attach

### ISSUE THREAD

**Issue by rincebrain** [zfsonlinux/zfs#4435] opened 2016-03-19 10:57 UTC
```
       zpool attach [-f] [-o property=value] pool device new_device

           Attaches new_device to an existing zpool device. The existing device cannot be part of a raidz configuration. If device is not currently part of a mirrored configuration, device automatically transforms into a two-way mirror of device and new_device.  If  device  is
           part of a two-way mirror, attaching new_device creates a three-way mirror, and so on. In either case, new_device begins to resilver immediately.

           -f    Forces use of new_device, even if its appears to be in use. Not all devices can be overridden in this manner.

           -o property=value

               Sets the given pool properties. See the "Properties" section for a list of valid properties that can be set. The only property supported at the moment is "ashift".
```

...except that attach can only be done to an existing top-level vdev, which has an ashift defined, so as far as I can see, there's no context where attempting to specify ashift can make sense, unless explicitly specifying it is how you force add an ashift={9,12} device to a vdev that has a differing ashift parameter?

But if that's the only context it makes sense, it probably makes sense to have a note about that in the man page, since users don't necessarily understand that specifying said parameter would be meaningless at best otherwise.

**Comment by ilovezfs** [comment] 2016-03-19 11:33
This is why git blame exists.
https://github.com/zfsonlinux/zfs/blame/master/man/man8/zpool.8#L934
https://github.com/zfsonlinux/zfs/commit/df83110856950c8e7b16a7e94cdf42b8531b9cc8
https://github.com/zfsonlinux/zfs/issues/566
https://github.com/zfsonlinux/zfs/commit/0a5be7be42fa5172492cefaae2219dde7977005e
https://github.com/zfsonlinux/zfs/commit/b28e57cb82c5d5a992b90c56f67dd7dbf9b6f296
https://github.com/zfsonlinux/zfs/issues/1381
https://github.com/zfsonlinux/zfs/issues/1328
https://github.com/zfsonlinux/zfs/issues/967
https://github.com/zfsonlinux/zfs/issues/548

If you believe that the man page should discuss the intended use cases in more detail feel free to open a pull request, but I'd recommend closing this issue.

**Comment by rlaager** [comment] 2016-10-12 00:52
@behlendorf can you clarify why `zpool attach -o ashift` is a useful option?

This comment says it doesn't work (even after the -o fix):
https://github.com/zfsonlinux/zfs/issues/566#issuecomment-10915019

This comment from @ryao basically says it _can't_ work, which makes sense to me:
https://github.com/zfsonlinux/zfs/issues/566#issuecomment-10915081

If it _can_ work, then I'd love to understand why and what it would be used for. If it _can't_ work, then we should remove the option entirely from `zpool attach`.

**Comment by behlendorf** [comment] 2016-10-12 01:16
@rlaager it's useful when the default value ZFS wants to use is wrong for some reason and you need to manually override it to match the other vdevs ashift.  Arguably this could be considered a bug is ZFS but having this functionality has proved useful in the past.  But you're right, you can't use it to mix and match ashifts and perhaps this could be more clearly explained in the documentation.

**Comment by DeHackEd** [comment] 2016-10-12 01:24
The main purpose is a sort of "force" command for when you have a pool created with ashift=9, then you try to replace/attach a disk with 4k sectors. ZFS doesn't like this (and with good reason) so specifying `-o ashift=9` overrides sector size detection and makes ZFS take it.

Yes it could be documented better. But the above is the important bit.

**Comment by rlaager** [comment] 2016-10-12 01:29
Given that you cannot have different ashift values, shouldn't `zpool attach` always copy the ashift from the device _being attached to_, not detect on the device _being attached_?

**Comment by DeHackEd** [comment] 2016-10-12 06:32
No, the <a href="https://github.com/zfsonlinux/zfs/blob/master/module/zfs/spa.c#L4660">requirement is that `ashift_of(inserting_disk) <= ashift_of(existing_vdev)`</a>. Failure to do so will result in `EDOM` being returned and the operation not proceeding. The `inserting_disk` value is read from the disk itself, but can be overridden with `-o ashift=value` with a value satisfying the inequality above to make ZFS accept the disk.

The rationale is that attaching a disk with too big an ashift will result in such staggeringly bad performance (for rotational media anyway) that users will be unhappy. I've done it, my 500G (half filled 1TB drives) mirror took 24 hours to resilver when should have been 2 hours. It was caused by mixing 512 and 4096 byte sector drives.

**Comment by rlaager** [comment] 2016-10-12 06:35
So in your case, the ashift of the inserting_disk must have been 9, while that of the existing_vdev was 12? And you had a bad time. So why shouldn't we force it to 12 in that case?

**Comment by DeHackEd** [comment] 2016-10-12 09:25
Other way around. The pool had `ashift=9` but inserting a disk with 4k sectors (`ashift=12`) results in the inequality `12 <= 9` which is incorrect. Using `zpool ... -o ashift=9` makes it `9 <= 9` and ZFS accepts it.

**Comment by richardelling** [comment] 2016-10-12 14:40
@DeHackEd wrote, "The rationale is that attaching a disk with too big an ashift will result in such staggeringly bad performance (for rotational media anyway) that users will be unhappy."

Many SSDs are also similarly affected. We've measured performance hits > 50% for some models. Many of these are firmware-release-sensitive, so YMMV.

**Comment by behlendorf** [comment] 2016-10-12 18:08
I think the rational for allowing `ashift` to be specified to `zfs attach` has been sufficiently explained to justify closing this issue.

**Closed by behlendorf** 2016-10-12 18:08 UTC
Labels: Documentation
