### ISSUE TITLE
vdev_stat_update: Assertion `spa_sync_pass(spa) == 1' failed.`

### ISSUE THREAD

**Issue by ryao** [zfsonlinux/zfs#2335] opened 2014-05-15 00:35 UTC
I observed the following failure with ztest:

```
ztest: ../../module/zfs/vdev.c:2766: vdev_stat_update: Assertion `spa_sync_pass(spa) == 1' failed.
```

Examining the core dump with zdb revealed the following stack traces of interest:

```
Thread 201 (Thread 0x7f755ebfb700 (LWP 74902)):
#0  pthread_cond_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007f756d0ac395 in cv_wait (cv=cv@entry=0x7f74f663ef48, mp=mp@entry=0x7f74f663ef10) at ../../lib/libzpool/kernel.c:485
#2  0x00007f756d1601bb in zio_wait (zio=zio@entry=0x7f74f663ec00) at ../../module/zfs/zio.c:1403
#3  0x00007f756d10067a in dsl_pool_sync (dp=dp@entry=0x11e3540, txg=txg@entry=2857) at ../../module/zfs/dsl_pool.c:473
#4  0x00007f756d122aae in spa_sync (spa=spa@entry=0x11e8930, txg=txg@entry=2857) at ../../module/zfs/spa.c:6236
#5  0x00007f756d133e69 in txg_sync_thread (dp=0x11e3540) at ../../module/zfs/txg.c:564
#6  0x00007f756d0a8d27 in zk_thread_helper (arg=0x15a92f0) at ../../lib/libzpool/kernel.c:135
#7  0x00007f756c96ee03 in start_thread (arg=0x7f755ebfb700) at pthread_create.c:308
#8  0x00007f756c6a7dad in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113

Thread 1 (Thread 0x7f75631f1700 (LWP 74825)):
#0  0x00007f756c5f50d9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007f756c5f6438 in __GI_abort () at abort.c:90
#2  0x00007f756c5ee276 in __assert_fail_base (fmt=0x7f756c7258a8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x7f756d183f52 "spa_sync_pass(spa) == 1", file=file@entry=0x7f756d183c41 "../../module/zfs/vdev.c", line=line@entry=2766, 
    function=function@entry=0x7f756d184b70 <__PRETTY_FUNCTION__.14302> "vdev_stat_update") at assert.c:92
#3  0x00007f756c5ee322 in __GI___assert_fail (assertion=assertion@entry=0x7f756d183f52 "spa_sync_pass(spa) == 1", file=file@entry=0x7f756d183c41 "../../module/zfs/vdev.c", line=line@entry=2766, 
    function=function@entry=0x7f756d184b70 <__PRETTY_FUNCTION__.14302> "vdev_stat_update") at assert.c:101
#4  0x00007f756d139b5b in vdev_stat_update (zio=zio@entry=0x7f748c001b80, psize=<optimized out>) at ../../module/zfs/vdev.c:2766
#5  0x00007f756d1635fb in zio_done (zio=0x7f748c001b80) at ../../module/zfs/zio.c:3051
#6  0x00007f756d15c0b9 in __zio_execute (zio=0x7f748c001b80) at ../../module/zfs/zio.c:1374
#7  zio_execute (zio=0x7f748c001b80) at ../../module/zfs/zio.c:1311
#8  0x00007f756d0ae4b4 in taskq_thread (arg=0x11f33a0) at ../../lib/libzpool/taskq.c:244
#9  0x00007f756d0a8d27 in zk_thread_helper (arg=0x11f3ac0) at ../../lib/libzpool/kernel.c:135
#10 0x00007f756c96ee03 in start_thread (arg=0x7f75631f1700) at pthread_create.c:308
#11 0x00007f756c6a7dad in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113
```

Also, spa->spa_sync_pass == 2 and the offending zio is the following:

```
(gdb) print *zio
$14 = {io_bookmark = {zb_objset = 0, zb_object = 0, zb_level = 0, zb_blkid = 0}, io_prop = {zp_checksum = ZIO_CHECKSUM_INHERIT, zp_compress = ZIO_COMPRESS_INHERIT, zp_type = DMU_OT_NONE, zp_level = 0 '\000', zp_copies = 0 '\000', zp_dedup = B_FALSE, 
    zp_dedup_verify = B_FALSE, zp_nopwrite = B_FALSE}, io_type = ZIO_TYPE_WRITE, io_child_type = ZIO_CHILD_VDEV, io_cmd = 0, io_priority = ZIO_PRIORITY_ASYNC_WRITE, io_reexecute = 0 '\000', io_state = "\001", io_txg = 2194, io_spa = 0x11e8930, io_bp = 0x0, 
  io_bp_override = 0x0, io_bp_copy = {blk_dva = {{dva_word = {0, 0}}, {dva_word = {0, 0}}, {dva_word = {0, 0}}}, blk_prop = 0, blk_pad = {0, 0}, blk_phys_birth = 0, blk_birth = 0, blk_fill = 0, blk_cksum = {zc_word = {0, 0, 0, 0}}}, io_parent_list = {list_size = 48, 
    list_offset = 16, list_head = {list_next = 0x7f748c001690, list_prev = 0x7f748c001690}}, io_child_list = {list_size = 48, list_offset = 32, list_head = {list_next = 0x7f748c001ca0, list_prev = 0x7f748c001ca0}}, io_walk_link = 0x0, io_logical = 0x7f73b1a6ac00, 
  io_transform_stack = 0x0, io_ready = 0x0, io_physdone = 0x0, io_done = 0x7f756d142d20 <vdev_raidz_child_done>, io_private = 0x7f748c002540, io_prev_space_delta = 0, io_bp_orig = {blk_dva = {{dva_word = {0, 0}}, {dva_word = {0, 0}}, {dva_word = {0, 0}}}, blk_prop = 0, 
    blk_pad = {0, 0}, blk_phys_birth = 0, blk_birth = 0, blk_fill = 0, blk_cksum = {zc_word = {0, 0, 0, 0}}}, io_data = 0x7f748c005000, io_orig_data = 0x7f748c005000, io_size = 44032, io_orig_size = 44032, io_vd = 0x11e6520, io_vsd = 0x0, io_vsd_ops = 0x0, 
  io_offset = 98224640, io_timestamp = 4986306151849, io_delta = 38440, io_delay = 0, io_queue_node = {avl_child = {0x0, 0x0}, avl_pcb = 1}, 
  io_flags = (ZIO_FLAG_IO_REPAIR | ZIO_FLAG_RESILVER | ZIO_FLAG_SCAN_THREAD | ZIO_FLAG_CANFAIL | ZIO_FLAG_DONT_CACHE | ZIO_FLAG_DONT_QUEUE | ZIO_FLAG_DONT_PROPAGATE), io_stage = ZIO_STAGE_DONE, io_pipeline = (ZIO_STAGE_READY | ZIO_STAGE_DONE), 
  io_orig_flags = (ZIO_FLAG_IO_REPAIR | ZIO_FLAG_RESILVER | ZIO_FLAG_SCAN_THREAD | ZIO_FLAG_CANFAIL | ZIO_FLAG_DONT_CACHE | ZIO_FLAG_DONT_PROPAGATE), io_orig_stage = ZIO_STAGE_READY, 
  io_orig_pipeline = (ZIO_STAGE_VDEV_IO_START | ZIO_STAGE_VDEV_IO_DONE | ZIO_STAGE_VDEV_IO_ASSESS | ZIO_STAGE_DONE), io_error = 6, io_child_error = {0, 0, 0, 0}, io_children = {{0, 0}, {0, 0}, {0, 0}, {0, 0}}, io_child_count = 0, io_phys_children = 0, 
  io_parent_count = 1, io_stall = 0x0, io_gang_leader = 0x0, io_gang_tree = 0x0, io_executor = 0x11f3ac0, io_waiter = 0x0, io_lock = {m_owner = 0x0, m_magic = 10746421124467712806, m_lock = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, 
        __spins = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}}, io_cv = {cv_magic = 15212783131315351748, cv = {__data = {__lock = 0, __futex = 0, __total_seq = 0, __wakeup_seq = 0, __woken_seq = 0, __mutex = 0x0, 
        __nwaiters = 0, __broadcast_seq = 0}, __size = '\000' <repeats 47 times>, __align = 0}}, io_cksum_report = 0x0, io_ena = 0, io_tqent = {tqent_next = 0x0, tqent_prev = 0x0, tqent_func = 0x7f756d15bfe0 <zio_execute>, tqent_arg = 0x7f748c001b80, tqent_flags = 1}}
```

My tentative theory is that we had a prefetch IO from dsl_scan_prefetch() trigger a checksum failure during spa_sync_pass == 1, which became a repair IO during spa_sync_pass == 2, but I would like a second opinion on this.

**Comment by behlendorf** [comment] 2016-03-25 20:52
This hasn't been observed in a long time but since it's a rare issue that may not be surprising.  I'm leaving it open for now but we should consider closing this if it's no longer reproducible.

**Comment by thegreatgazoo** [comment] 2016-05-03 20:37
I've hit this assertion a couple of times lately, but still investigating if it's caused by the draid driver I'm working on.

**Comment by behlendorf** [comment] 2017-01-24 19:02
Closing as stale.  @thegreatgazoo definitely let us know is you observe this again on a clean version of master and we'll reopen it.

**Closed by behlendorf** 2017-01-24 19:02 UTC
Labels: Test Suite
