### ISSUE TITLE
Excessively slowed down zpool scrub "performance"

### ISSUE THREAD

**Issue by kernelOfTruth** [zfsonlinux/zfs#4970] opened 2016-08-15 13:55 UTC
@behlendorf @dweeezil can the following pull-request (https://github.com/zfsonlinux/zfs/pull/4850) be the cause for excessively slowed down zpool scrub "performance" ?

Usually scrub needs around 10-11 hours,

now it only reads at around 25 MiB/s and would take 25+ hours for it.

Also the L2ARC device is currently not attached whereas previously it was attached - there doesn't seem to be a connection but I'll see today or within the next days if by doing so the behavior is changed

branch is zfs_master from July 29th:

https://github.com/kernelOfTruth/zfs/commits/zfs_master_29.07.2016

on first look it doesn't seem that recent changes could have caused it,

and it could be kernel-side (4.7.0).

Will install from latest master and see if things improve ...

**Comment by dweeezil** [comment] 2016-08-16 03:55
@kernelOfTruth I'll check into this.  I've never really looked into whether good scrub performance might depend on caching lots of dnodes.  My initial thinking is that it shouldn't.

**Comment by kernelOfTruth** [comment] 2016-08-17 15:52
@dweeezil Thanks for looking into it,

I'm currently running a branch with the dnode limitation reverted and your "extend balanced metadata eviction strategy" patch (https://github.com/kernelOfTruth/zfs/commits/zfs_master_15.08.2016_balanced-metadata-strategy)

which, if I remember correctly, did not show that behavior in the past,

so the only factors that have changed are 4.6 to 4.7 kernel migration and a slightly fuller pool and thus fragmentation (+/- non-related changes on top on master)

My guess currently is on the kernel and changes

**Comment by kernelOfTruth** [comment] 2016-08-19 12:44
```
zpool status
  pool: WD30EFRX
 state: ONLINE
status: Some supported features are not enabled on the pool. The pool can
	still be used, but some features are unavailable.
action: Enable all features using 'zpool upgrade'. Once this is done,
	the pool may no longer be accessible by software that does not support
	the features. See zpool-features(5) for details.
  scan: scrub repaired 0 in 10h15m with 0 errors on Fri Aug 19 10:37:13 2016
```

finished within 10 hours with 4.6.7 based kernel and deadline i/o scheduler used for the harddrives and zfs_vdev_scheduler , NCQ disabled (queue_depth set to 1),

now will see in a few days if this also works with 4.7 based kernel

dnodes in slab were only about 120 MiB, so that definitely cannot be the reason.

Third step after that will then be to test vanilla master (or at least not reverted dnode metadata limit changes)

**Comment by dweeezil** [comment] 2016-08-19 13:13
@kernelOfTruth Yes, after a bit of testing, I also came to the conclusion that scrub doesn't have any particularly great need for caching lots of dnodes.  Given that a scrub is essentially a block traversal, that's not terribly surprising.  Also, re-reading I'll note that the 2e099b8  patch (I believe I purged the branch in which it was referenced from github)  you may have been using wasn't really production-ready in any way.  It was an early attempt at solving the problems addressed by the dnode limiting.

**Comment by kernelOfTruth** [comment] 2016-08-19 14:30
@dweeezil the patches looked interesting and save enough to test (I also always do a buildbot testrun before using it on my desktop: https://github.com/zfsonlinux/zfs/pull/4835 ), and that was the last branch that I had used before, which didn't exhibit this significantly prolonged zpool time

My current theories for the causes are:

- ~~dnode metadata limit~~ (unprobable)
- NCQ regression with 4.7 kernel
- Some other issue that limits throughput (with 4.6 the read speed with that mirror was up to 200 MiB/s and more, with 4.7 if I remember correctly, I only saw around 25 MiB/s and it stayed there)

**Comment by behlendorf** [comment] 2016-10-11 22:16
@kernelOfTruth it sounds like you've determined that this issue is somehow caused by the kernel version and isn't a regression in ZFS.  Where does this stand?

**Closed** 2019-02-18 23:30 UTC
Labels: Type: Performance
