### ISSUE TITLE
kABI kmod install: CentOS 6.9 696 kernel: no zfs.ko

### ISSUE THREAD

**Issue by cousins** [zfsonlinux/zfs#6043] opened 2017-04-19 22:42 UTC
*IMPORTANT* - This issue tracker is for *bugs* and *issues* only.
Please search the wiki and the mailing list archives before asking 
questions on the mailing list.
https://github.com/zfsonlinux/zfs/wiki/Mailing-Lists

Please fill in as much of the template as possible.
-->

### System information
Type                                | Version/Name
Distribution Name       |   CentOS 
Distribution Version    |  6.9
Linux Kernel                 |  2.6.32-696.1.1.el6
Architecture                 | x86_64
ZFS Version                  | 
SPL Version                  |  0.6.5.8-1

### Describe the problem you're observing

I just updated system to kmod-kABI and went through the process of wiping out all other zfs and spl related packages, including using "find" to delete modules in /lib/modules. Then installed zfs-release repo, changed the repo file to disable the [zfs] dkms section and enable [zfs-kmod]. Then ran "yum install zfs" and got:
```
[root@nfs2 ~]# yum install zfs
Loaded plugins: fastestmirror, refresh-packagekit, security
Setting up Install Process
Determining fastest mirrors
epel/metalink                                                                                                                                               |  13 kB     00:00
 * base: centos.aol.com
 * epel: archive.linux.duke.edu
 * extras: centos.sonn.com
 * updates: centos.firehosted.com
base                                                                                                                                                        | 3.7 kB     00:00
base/primary_db                                                                                                                                             | 4.7 MB     00:01
epel                                                                                                                                                        | 4.3 kB     00:00
epel/primary_db                                                                                                                                             | 5.9 MB     00:02
extras                                                                                                                                                      | 3.4 kB     00:00
extras/primary_db                                                                                                                                           |  37 kB     00:00
updates                                                                                                                                                     | 3.4 kB     00:00
updates/primary_db                                                                                                                                          | 766 kB     00:00
zfs-kmod                                                                                                                                                    | 2.9 kB     00:00
zfs-kmod/primary_db                                                                                                                                         | 230 kB     00:00
Resolving Dependencies
--> Running transaction check
---> Package zfs.x86_64 0:0.6.5.8-1.el6 will be installed
--> Processing Dependency: zfs-kmod = 0.6.5.8 for package: zfs-0.6.5.8-1.el6.x86_64
--> Processing Dependency: spl = 0.6.5.8 for package: zfs-0.6.5.8-1.el6.x86_64
--> Processing Dependency: libzpool2 = 0.6.5.8 for package: zfs-0.6.5.8-1.el6.x86_64
--> Processing Dependency: libzfs2 = 0.6.5.8 for package: zfs-0.6.5.8-1.el6.x86_64
--> Processing Dependency: libnvpair1 = 0.6.5.8 for package: zfs-0.6.5.8-1.el6.x86_64
--> Processing Dependency: libzpool.so.2()(64bit) for package: zfs-0.6.5.8-1.el6.x86_64
--> Processing Dependency: libzfs_core.so.1()(64bit) for package: zfs-0.6.5.8-1.el6.x86_64
--> Processing Dependency: libzfs.so.2()(64bit) for package: zfs-0.6.5.8-1.el6.x86_64
--> Processing Dependency: libnvpair.so.1()(64bit) for package: zfs-0.6.5.8-1.el6.x86_64
--> Running transaction check
---> Package kmod-zfs.x86_64 0:0.6.5.8-1.el6 will be installed
--> Processing Dependency: spl-kmod for package: kmod-zfs-0.6.5.8-1.el6.x86_64
---> Package libnvpair1.x86_64 0:0.6.5.8-1.el6 will be installed
---> Package libzfs2.x86_64 0:0.6.5.8-1.el6 will be installed
---> Package libzpool2.x86_64 0:0.6.5.8-1.el6 will be installed
---> Package spl.x86_64 0:0.6.5.8-1.el6 will be installed
--> Running transaction check
---> Package kmod-spl.x86_64 0:0.6.5.8-1.el6 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

===================================================================================================================================================================================
 Package                                    Arch                                   Version                                          Repository                                Size
===================================================================================================================================================================================
Installing:
 zfs                                        x86_64                                 0.6.5.8-1.el6                                    zfs-kmod                                 330 k
Installing for dependencies:
 kmod-spl                                   x86_64                                 0.6.5.8-1.el6                                    zfs-kmod                                 111 k
 kmod-zfs                                   x86_64                                 0.6.5.8-1.el6                                    zfs-kmod                                 636 k
 libnvpair1                                 x86_64                                 0.6.5.8-1.el6                                    zfs-kmod                                  33 k
 libzfs2                                    x86_64                                 0.6.5.8-1.el6                                    zfs-kmod                                 119 k
 libzpool2                                  x86_64                                 0.6.5.8-1.el6                                    zfs-kmod                                 408 k
 spl                                        x86_64                                 0.6.5.8-1.el6                                    zfs-kmod                                  27 k

Transaction Summary
===================================================================================================================================================================================
Install       7 Package(s)

Total download size: 1.6 M
Installed size: 5.7 M
Is this ok [y/N]: y
Downloading Packages:
(1/7): kmod-spl-0.6.5.8-1.el6.x86_64.rpm                                                                                                                    | 111 kB     00:00
(2/7): kmod-zfs-0.6.5.8-1.el6.x86_64.rpm                                                                                                                    | 636 kB     00:00
(3/7): libnvpair1-0.6.5.8-1.el6.x86_64.rpm                                                                                                                  |  33 kB     00:00
(4/7): libzfs2-0.6.5.8-1.el6.x86_64.rpm                                                                                                                     | 119 kB     00:00
(5/7): libzpool2-0.6.5.8-1.el6.x86_64.rpm                                                                                                                   | 408 kB     00:00
(6/7): spl-0.6.5.8-1.el6.x86_64.rpm                                                                                                                         |  27 kB     00:00
(7/7): zfs-0.6.5.8-1.el6.x86_64.rpm                                                                                                                         | 330 kB     00:00
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                              9.0 MB/s | 1.6 MB     00:00
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing : libnvpair1-0.6.5.8-1.el6.x86_64                                                                                                                                 1/7
  Installing : libzpool2-0.6.5.8-1.el6.x86_64                                                                                                                                  2/7
  Installing : kmod-spl-0.6.5.8-1.el6.x86_64                                                                                                                                   3/7
  Installing : spl-0.6.5.8-1.el6.x86_64                                                                                                                                        4/7
  Installing : libzfs2-0.6.5.8-1.el6.x86_64                                                                                                                                    5/7
  Installing : kmod-zfs-0.6.5.8-1.el6.x86_64                                                                                                                                   6/7
WARNING: /lib/modules/2.6.32-696.1.1.el6.x86_64/weak-updates/zfs/zpios/zpios.ko needs unknown symbol dmu_tx_hold_write
WARNING: /lib/modules/2.6.32-696.1.1.el6.x86_64/weak-updates/zfs/zpios/zpios.ko needs unknown symbol dmu_read
WARNING: /lib/modules/2.6.32-696.1.1.el6.x86_64/weak-updates/zfs/zpios/zpios.ko needs unknown symbol dmu_tx_assign
WARNING: /lib/modules/2.6.32-696.1.1.el6.x86_64/weak-updates/zfs/zpios/zpios.ko needs unknown symbol dmu_tx_create
WARNING: /lib/modules/2.6.32-696.1.1.el6.x86_64/weak-updates/zfs/zpios/zpios.ko needs unknown symbol dmu_object_alloc
WARNING: /lib/modules/2.6.32-696.1.1.el6.x86_64/weak-updates/zfs/zpios/zpios.ko needs unknown symbol dmu_object_free
WARNING: /lib/modules/2.6.32-696.1.1.el6.x86_64/weak-updates/zfs/zpios/zpios.ko needs unknown symbol dmu_objset_own
WARNING: /lib/modules/2.6.32-696.1.1.el6.x86_64/weak-updates/zfs/zpios/zpios.ko needs unknown symbol dsl_destroy_head
WARNING: /lib/modules/2.6.32-696.1.1.el6.x86_64/weak-updates/zfs/zpios/zpios.ko needs unknown symbol dmu_write
WARNING: /lib/modules/2.6.32-696.1.1.el6.x86_64/weak-updates/zfs/zpios/zpios.ko needs unknown symbol dmu_objset_disown
WARNING: /lib/modules/2.6.32-696.1.1.el6.x86_64/weak-updates/zfs/zpios/zpios.ko needs unknown symbol dmu_tx_commit
WARNING: /lib/modules/2.6.32-696.1.1.el6.x86_64/weak-updates/zfs/zpios/zpios.ko needs unknown symbol dmu_tx_wait
WARNING: /lib/modules/2.6.32-696.1.1.el6.x86_64/weak-updates/zfs/zpios/zpios.ko needs unknown symbol dmu_tx_abort
WARNING: /lib/modules/2.6.32-696.1.1.el6.x86_64/weak-updates/zfs/zpios/zpios.ko needs unknown symbol dmu_object_set_blocksize
WARNING: /lib/modules/2.6.32-696.1.1.el6.x86_64/weak-updates/zfs/zpios/zpios.ko needs unknown symbol dmu_objset_create
WARNING: /lib/modules/2.6.32-696.1.1.el6.x86_64/weak-updates/zfs/zpios/zpios.ko needs unknown symbol dmu_tx_hold_free
  Installing : zfs-0.6.5.8-1.el6.x86_64                                                                                                                                        7/7
  Verifying  : libnvpair1-0.6.5.8-1.el6.x86_64                                                                                                                                 1/7
  Verifying  : libzfs2-0.6.5.8-1.el6.x86_64                                                                                                                                    2/7
  Verifying  : zfs-0.6.5.8-1.el6.x86_64                                                                                                                                        3/7
  Verifying  : spl-0.6.5.8-1.el6.x86_64                                                                                                                                        4/7
  Verifying  : kmod-zfs-0.6.5.8-1.el6.x86_64                                                                                                                                   5/7
  Verifying  : libzpool2-0.6.5.8-1.el6.x86_64                                                                                                                                  6/7
  Verifying  : kmod-spl-0.6.5.8-1.el6.x86_64                                                                                                                                   7/7

Installed:
  zfs.x86_64 0:0.6.5.8-1.el6

Dependency Installed:
  kmod-spl.x86_64 0:0.6.5.8-1.el6    kmod-zfs.x86_64 0:0.6.5.8-1.el6    libnvpair1.x86_64 0:0.6.5.8-1.el6    libzfs2.x86_64 0:0.6.5.8-1.el6    libzpool2.x86_64 0:0.6.5.8-1.el6
  spl.x86_64 0:0.6.5.8-1.el6

Complete!
```
However:

```
[root@nfs2 ~]# modprobe zfs
FATAL: Module zfs not found.

[root@nfs2 ~]# find /lib/modules/ -name zfs.ko
/lib/modules/2.6.32-642.4.2.el6.x86_64/extra/zfs/zfs/zfs.ko
/lib/modules/2.6.32-504.el6.x86_64/weak-updates/zfs/zfs/zfs.ko
```

And that is very odd because I have never had the 2.6.32.642.4.2.el6.x86_64 kernel/kernel-devel packages installed. It seems that zfs-kmod is installing into the wrong directory for some reason.

Is it just that the 696 kernel is too new to use with ZFSonLinux yet? 

Thanks,

Steve

**Comment by loli10K** [comment] 2017-04-20 06:03
@cousins this seems like a duplicate of https://github.com/zfsonlinux/zfs/issues/5930, can we close it?

**Comment by cousins** [comment] 2017-04-20 14:25
It does look like the same issue but I don't see a viable solution in it. One mention was to change grub.conf to default to the previous kernel but that does not work. My previous kernel is not 2.6.32-642.3.2.el6. It seems that the "solution" is to wait. How long to wait? Or am I misreading it?

**Comment by cousins** [comment] 2017-04-21 14:33
Issue #5930 indicates that the after the release of CentOS 6.9 (April 5) kmod-zfs and kmod-spl build fine. The only problem right now is that the these packages in the ZFS repository are still for the previous kernel (2.6.32-642.4.2.el6) instead of the latest one for 6.9 which is 2.6.32-696.1.1.el6

What is the process for getting the repository updated? Is that generally done within the zfsonlinux project or does someone else handle that? My impression is that it is part of this project. If so, what is the usual lag time after a CentOS release before the ZFS repository is updated? Does it get built and then have to go through some testing for a certain amount of time? I think I just happened to hit a window where I could do the updates on the machine and it happened to be when the kmods were inconsistent with the CentOS. 

Thanks,

Steve

**Comment by behlendorf** [comment] 2017-04-21 19:41
The CentOS 6 kmod and dkms repositories have been updated with spl/zfs-0.6.5.9 built against the 2.6.32-696 kernel. Sorry about the delay.

**Closed by behlendorf** 2017-04-21 19:41 UTC

**Comment by cousins** [comment] 2017-04-21 19:51
@behlendorf Thanks very much! 

```
[root@nfs2 ~]# yum clean all
Loaded plugins: fastestmirror, refresh-packagekit, security
Cleaning repos: base epel extras updates zfs-kmod
Cleaning up Everything

[root@nfs2 ~]# repoquery -ql kmod-zfs kmod-spl
/lib/modules/2.6.32-696.1.1.el6.x86_64
/lib/modules/2.6.32-696.1.1.el6.x86_64/extra
/lib/modules/2.6.32-696.1.1.el6.x86_64/extra/spl
/lib/modules/2.6.32-696.1.1.el6.x86_64/extra/spl/spl
/lib/modules/2.6.32-696.1.1.el6.x86_64/extra/spl/spl/spl.ko
/lib/modules/2.6.32-696.1.1.el6.x86_64/extra/spl/splat
/lib/modules/2.6.32-696.1.1.el6.x86_64/extra/spl/splat/splat.ko
/lib/modules/2.6.32-696.1.1.el6.x86_64
/lib/modules/2.6.32-696.1.1.el6.x86_64/extra
/lib/modules/2.6.32-696.1.1.el6.x86_64/extra/zfs
/lib/modules/2.6.32-696.1.1.el6.x86_64/extra/zfs/avl
/lib/modules/2.6.32-696.1.1.el6.x86_64/extra/zfs/avl/zavl.ko
/lib/modules/2.6.32-696.1.1.el6.x86_64/extra/zfs/nvpair
/lib/modules/2.6.32-696.1.1.el6.x86_64/extra/zfs/nvpair/znvpair.ko
/lib/modules/2.6.32-696.1.1.el6.x86_64/extra/zfs/unicode
/lib/modules/2.6.32-696.1.1.el6.x86_64/extra/zfs/unicode/zunicode.ko
/lib/modules/2.6.32-696.1.1.el6.x86_64/extra/zfs/zcommon
/lib/modules/2.6.32-696.1.1.el6.x86_64/extra/zfs/zcommon/zcommon.ko
/lib/modules/2.6.32-696.1.1.el6.x86_64/extra/zfs/zfs
/lib/modules/2.6.32-696.1.1.el6.x86_64/extra/zfs/zfs/zfs.ko
/lib/modules/2.6.32-696.1.1.el6.x86_64/extra/zfs/zpios
/lib/modules/2.6.32-696.1.1.el6.x86_64/extra/zfs/zpios/zpios.ko
```
That's great. I really appreciate it.

**Comment by charlesg** [comment] 2018-08-04 02:37
I have the same issue on 2.6.32-754 with ZoL 0.7.9-1.

Do we simply have to install manually with older kernels?

I tried several cycles of:

* yum erase
* find /lib/modules -name *zfs* -exec rm {}
* reboot
* yum install zfs spl

I tried with DKMS and KMOD and it yielded similar results. I'm not sure what I'm doing wrong. Since this is fixed, I'm assuming I should be able to install from yum...
