### ISSUE TITLE
Clarification on "Debian Buster Root on ZFS" statement

### ISSUE THREAD

**Issue by 0x3333** [zfsonlinux/zfs#9053] opened 2019-07-17 14:44 UTC
In the wiki page for [Debian Buster Root on ZFS](https://github.com/zfsonlinux/zfs/wiki/Debian-Buster-Root-on-ZFS) there is a statement that says:

`"Computers that have less than 2 GiB of memory run ZFS slowly."`

I'd like more clarification about it, eventually a link to a resource where this affirmation is based on.

In some machines with 2GB or less, the workload might not be that huge, so this statement doesn't apply, would be nice if we have more information about whether this issue applies to us or not.

Thanks!

**Comment by gmelikov** [comment] 2019-07-17 15:04
Please don't delete issue template next time, and use mailing lists for support questions https://github.com/zfsonlinux/zfs/wiki/Mailing-Lists .

It's a rule of thumb that on systems with small amount or RAM you can't use much of it for FS cache, so it's better not to reassure people in this case. I'll add a comment about it.

Closed as not a bug.

**Closed by gmelikov** 2019-07-17 15:04 UTC

**Comment by 0x3333** [comment] 2019-07-17 17:36
I thought that as the wiki was lacking this information, I should file an issue. Sorry, lesson learned.
