### ISSUE TITLE
KDE Neon Root

### ISSUE THREAD

**Issue by benyanke** [zfsonlinux/zfs#8073] opened 2018-10-30 19:47 UTC
When I attempt to follow this (or any other) 18.04 guide on KDE Neon (Which is 18.04  based), I get stuck on the initial pool create, with modprobe issues.

```
# zfs create [...]
The ZFS modules are not loaded.
Try running '/sbin/modprobe zfs' as root to load them.
# /sbin/modprobe zfs
modprobe: ERROR: could not insert 'zfs': Unknown symbol in module, or unknown parameter (see dmesg)
```

Is there a guide for installing on KDE Neon?

**Comment by stephenmclan** [comment] 2018-10-30 20:12
Days since https://github.com/zfsonlinux/zfs/commit/bfcb82cb5426e75799705938a9d17deb6cfaca82 was merged: 13.
Days since the https://github.com/zfsonlinux/zfs/blob/master/.github/ISSUE_TEMPLATE.md was ignored: ~~1~~ 0.

**Comment by bunder2015** [comment] 2018-10-30 20:41
This is probably not a bug, but rather an issue with your running kernel (mismatched modules, etc).  Please use IRC or the [mailing list](http://list.zfsonlinux.org/) for support requests.  Thank you.

**Closed by bunder2015** 2018-10-30 20:41 UTC
