### ISSUE TITLE
PGP-signed releases

### ISSUE THREAD

**Issue by eli-schwartz** [zfsonlinux/zfs#8557] opened 2019-04-01 20:02 UTC
The release tarballs listed at https://github.com/zfsonlinux/zfs/releases do not come with PGP signatures.

The tarballs do have a .sha256sums file providing integrity protection against accidental file corruption, and the checksums are further signed, but a checksum file is an indirect way of providing signed assurances, and requiring users to first PGP-verify the checksum file, then extract the checksum hashes from the file and compare them to the tarball, is inconvenient and makes automation difficult.

Please provide, instead or in addition, detached .sig/.asc files for the tarballs themselves. This could then be used for the community-provided Arch Linux packaging in order to verify the authenticity of zfs releases, as the `makepkg` program supports verifying detached signatures via a pinned key fingerprint.

**Comment by behlendorf** [comment] 2019-04-01 21:17
Thank you for the reminder we plan to start doing this the 0.8 release series.  To make sure we're on the same page, would you mind referencing a couple Github projects which you feel are doing this right.

Duplicate of #7636

**Comment by eli-schwartz** [comment] 2019-04-01 21:51
Some upstreams, like https://github.com/Cloudef/bemenu/releases or https://github.com/Sigil-Ebook/Sigil/releases/tag/0.9.13, provide signature files for the archive that github created, which can be created locally with the command:

```
reponame="zfs"
tag="zfs-0.7.13"
git archive --prefix="${reponame}-${tag#v}/" -o "${repo}-${tag#v}.tar.gz" "${tag}"
```

https://github.com/bazelbuild/bazel/releases provides many files, all of which have .sig and .sha256 accompanying files.

https://github.com/darktable-org/darktable/releases provides their own tarballs, dmgs, and .asc files for both, and lists sha256sums in the description.

https://github.com/strace/strace/releases and https://github.com/mesonbuild/meson/releases provide tarballs + .asc files again.

https://github.com/USBGuard/usbguard/releases provides tarballs, .sig, .sum, and inlines the .sum in the release description.

...

According to my grep of packaging recipes for Arch Linux, there are lots more examples, but this is pretty fairly representative I guess.

**Comment by behlendorf** [comment] 2019-04-17 20:16
A detached signature has been provided for the latest [zfs-0.8.0-rc4 release](https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.8.0-rc4).  These will be included for all new tagged releases.  Please let me know if for some reason this isn't sufficient.

```
gpg --verify ./zfs-0.8.0-rc4.tar.gz.asc ./zfs-0.8.0-rc4.tar.gz
gpg: Signature made Tue 16 Apr 2019 01:58:24 PM PDT using DSA key ID C6AF658B
gpg: Good signature from "Brian Behlendorf <behlendorf1@llnl.gov>"
gpg:                 aka "Brian Behlendorf (LLNL) <behlendorf1@llnl.gov>"
```

**Closed** 2019-04-17 20:57 UTC
Labels: Component: Packaging

**Comment by eli-schwartz** [comment] 2019-04-17 21:01
Thank you, this works great for me.
