### ISSUE TITLE
Very, very weird behavior importing pools in msdos-partitioned disks

### ISSUE THREAD

**Issue by Rudd-O** [zfsonlinux/zfs#1735] opened 2013-09-18 10:10 UTC
I suspect the import order for devices has changed in 0.6.2, because (as I discovered with zfs-fedora-installer) when I have a whole disk, that has been partitioned NOT with GPT but rather with msdos partitions, and this device is partitioned in such a way that the very last partition on the device covers up to the end of the disk, and then it is used for a ZFS pool, then when trying to import the ZFS pool in question, it fails, because it wants to import the whole disk (WTF) and this -- sadly -- reflects "corruption" (for obvious reasons).  BUT, if I DELETE the device file corresponding to the whole disk in question, suddenly zpool import can import the partition-backed device just fine, no corruption, all good.

W T F.

So far my workaround has been to avoid the last 16 megs (or so) for the last partition, which makes the whole disk not have any ZFS pool signatures at the end.

Can anyone reproduce?  You have to reboot in order for this to be an issue.  I am filing a ticket in the ZFS bug tracker about this.

**Comment by GregorKopka** [comment] 2016-07-16 22:17
@behlendorf has this been fixed in the partition detection code?

**Comment by behlendorf** [comment] 2016-07-18 17:20
@GregorKopka I'm not positive let me reopen this.  It would be great if someone could post a test case.

**Comment by dasjoe** [comment] 2016-07-18 18:25
I believe https://github.com/zfsonlinux/zfs/commit/7d90f569b3f05def7cbd0a52ce8ac3040364d702 fixed this. I can't reproduce this with a msdos labelled disk:

```
root@sbooblehat:~# parted /dev/sdb -s -- \
>   mklabel msdos \
>   mkpart primary 1M 100M \
>   mkpart primary 100M 100% \
>   u b p
Model: Sharkoon Flexi-Drive EC4 (scsi)
Disk /dev/sdb: 4009754624B
Sector size (logical/physical): 512B/512B
Partition Table: msdos
Disk Flags: 

Number  Start      End          Size         Type     File system  Flags
 1      1048576B   99614719B    98566144B    primary               lba
 2      99614720B  4009754623B  3910139904B  primary               lba

root@sbooblehat:~# zpool create TEST /dev/sdb2
root@sbooblehat:~# zpool export TEST
root@sbooblehat:~# zpool import
   pool: TEST
     id: 6260344620714813540
  state: ONLINE
 action: The pool can be imported using its name or numeric identifier.
 config:

	TEST        ONLINE
	  sdb2      ONLINE
root@sbooblehat:~# zpool import TEST
root@sbooblehat:~# zpool status TEST
  pool: TEST
 state: ONLINE
  scan: none requested
config:

	NAME        STATE     READ WRITE CKSUM
	TEST        ONLINE       0     0     0
	  sdb2      ONLINE       0     0     0

errors: No known data errors
```

**Comment by rlaager** [comment] 2016-10-01 02:03
Sounds like this was fixed?

**Closed by rlaager** 2016-10-01 02:03 UTC
Labels: Difficulty - Medium
