### ISSUE TITLE
 could not insert 'zfs': Unknown symbol in module, or unknown parameter (see dmesg)

### ISSUE THREAD

**Issue by luofeiyu** [zfsonlinux/zfs#6483] opened 2017-08-09 09:18 UTC
root@wifi:/home/debian# sudo zfs list
The ZFS modules are not loaded.
Try running '/sbin/modprobe zfs' as root to load them.
root@wifi:/home/debian# /sbin/modprobe zfs
modprobe: ERROR: could not insert 'zfs': Unknown symbol in module, or unknown parameter (see dmesg)

dmesg 
[ 5979.240083] SPL: Loaded module v0.6.5.9-1~bpo8+1
[ 5979.245465] zfs: Unknown symbol setattr_prepare (err 0)
[ 6182.431939] zfs: Unknown symbol setattr_prepare (err 0)

**Comment by gmelikov** [comment] 2017-08-09 09:27
Check zfs/spl version identity, and remove all old package versions before update, it's not a bug.

Next time please don't just remove issue template, closed as non constructive.

**Closed by gmelikov** 2017-08-09 09:27 UTC
