### ISSUE TITLE
ZFS causes kernel tasks to hang and processes to get stuck in uninterruptable sleep

### ISSUE THREAD

**Issue by DarthAndroid** [zfsonlinux/zfs#3900] opened 2015-10-08 15:40 UTC
**OS**: Ubuntu Vivid 3.19.0-26-generic 28-Ubuntu SMP Tue Aug 11 14:16:32 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
**ZoL**: 0.6.5.2, provided by the [ubuntu-zfs](https://launchpad.net/~zfs-native/+archive/ubuntu/stable) package version 9~vivid
**dmesg**: http://pastebin.com/jSYiwv0H
**arc_summary**: http://pastebin.com/abAayE8P
**Hardware**: 64GiB ECC memory, Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz (4 physical cores + Hyperthreading, 8 logical cores)
**Pool Configuration**: 2x 2TB vdev (mirror), 2x 200GB SSD cache

I upgraded ZFS last night (0.6.4.2 -> 0.6.5.2) and started running into issues when my system encountered heavy I/O during startup (heavy sequential reads followed by heavy random and sequential writes). In particular, The kernel started printing informational messages about kernel tasks that have been hung for more than 120 seconds, and the tasks themselves have been stuck in uninterruptable sleep for hours. Sometimes they resolve themselves (the `txg_quiesce:1013` task resolved sometime during the night), otherwise restarting is the only option. `run_electrum_lt:24008` in particular is still frozen nearly 12 hours later.

Please let me know if there is additional information that I can provide to help resolve this issue.

**Comment by kernelOfTruth** [comment] 2015-10-08 15:46
@DarthAndroid does 

``` spl_taskq_thread_dynamic=0 ```

(preferrably setting it in /etc/modprobe.d/spl.conf via 

``` options spl spl_taskq_thread_dynamic=0``` )

help ?

**Comment by DarthAndroid** [comment] 2015-10-08 20:48
It did not appear to help. I still have the same `INFO` messages with the same stack trace, and I still have processes entering the "uninterruptable sleep" state while the server is more or less sitting idle (<1% disk IO, <1% CPU, <50% memory, etc)

I did delay starting up the disk-intensive applications this time around, and did not see any uninterruptable processes until I started the disk-intensive applications, at which point 2 of the 4 disk-intensive applications entered such a state after about 60-120 seconds of execution.

**Comment by ryao** [comment] 2015-10-08 21:52
Pull request #3901 should fix this, but I think this needs more analysis before that fix is merged. The root cause of the failure needs to be understood. I believe it is coming from one of the callees of `dmu_spill_hold_existing()`. @DarthAndroid informs me in IRC that he is using pool version 5000, so the branch that checks for SPA_VERSION_SA is not causing this. There are two others in that function.

**Comment by hjjg** [comment] 2015-10-19 20:11
I can confirm this bug. I got this after an upgrade on one Ubuntu box. All allowed NFS kernel server threads were taking 100% SYS CPU. A simple directory listing I've issued could not be killed.

There was not a single IO-Request on the disks/vdev, the time I investigated this.

A reboot fixed this issue, but the dataset was mounted read-only afterwards.

**Comment by DarthAndroid** [comment] 2015-10-22 16:15
@hjjg This wound up being fixed for me by #3906 and is related to #3899 where it is being discussed.

**Comment by behlendorf** [comment] 2015-12-23 19:46
@DarthAndroid thanks for following up.  I've added #3906 to patches for the next point release.

**Closed by behlendorf** 2015-12-23 19:46 UTC

**Comment by krichter722** [comment] 2017-01-22 09:44
I experience this issue (pretty sure that it's the same because the OS and the symptoms match) on Ubuntu 16.10 with zfs-0.7.0-rc3-2-gbb7ffda and spl 0.7.0-rc3 which should include the referenced patches.

There're little differences: The hangs are a little bit less severe (up to 10 minutes instead of hours or nights) and there're some short interruptions of the hang when I/O works for some seconds. Watching I/O and system load with monitors `iotop` and `htop` shows that I/O is 0/0 B/s for up to some seconds while the system load remains close to 80 which is quite rare for my system. Both with the Ubuntu system packages with version 0.6.5.8-0ubuntu4.1 and the source build I have > 100 `z_rd_int_[n]` and `z_wr_int_[n]` each (kernel)threads/processes. That can't be right, can it?

If you want I can open a new issue.

**Comment by baharclerode** [comment] 2017-01-22 10:18
@krichter722 I have 97 `z_rd_int` threads and 102 `z_wr_int` threads on my current 12-core/128GiB system and 105/133 respectively on my 8-core/16GiB system, so those numbers could very well be right.

Do you have stack dumps in your kernel messages with warnings about tasks blocking for more than 120 seconds? (See the end of my dmesg linked in the first post for an example). If the top of the stack looks about the same (names, not necessarily the numbers/offsets), then it's probably the same bug. If it's different, then you should probably open a new bug ticket with the information that you're seeing from your system.
