### ISSUE TITLE
Kernel Panic

### ISSUE THREAD

**Issue by standula** [zfsonlinux/zfs#5615] opened 2017-01-19 09:40 UTC
Hello i have next Kernel panic on my system:
I report one kernel panic on  #4857. 
System configuration is the same. 
ZFS version : v0.6.5.8

 containers_br: port 8(veth68T8Y1) entered disabled state
 device veth68T8Y1 left promiscuous mode
 containers_br: port 8(veth68T8Y1) entered disabled state
 device vethWTU8OG entered promiscuous mode
 IPv6: ADDRCONF(NETDEV_UP): vethWTU8OG: link is not ready
 containers_br: port 8(vethWTU8OG) entered forwarding state
 containers_br: port 8(vethWTU8OG) entered forwarding state
 IPv6: ADDRCONF(NETDEV_CHANGE): vethWTU8OG: link becomes ready
 containers_br: port 8(vethWTU8OG) entered forwarding state
 containers_br: port 8(vethWTU8OG) entered forwarding state
 cgroup: new mount options do not match the existing superblock, will be ignored
 systemd-journal D ffff8801b5041708     0  5841   5058 0x00000100
ffff8801b50412b0 0000000000000082 0000000000012f40 ffff8801b148ffd8
0000000000012f40 ffff8801b50412b0 ffff8800b14f31c0 ffff8800b14f3000
ffff8800b14f31c8 0000000000000000 0000000000001000 0000000000000000
 Call Trace:
[<ffffffffa02cf4ed>] ? cv_wait_common+0xbd/0xf0 [spl]
[<ffffffff810a9590>] ? prepare_to_wait_event+0xf0/0xf0
[<ffffffffa0419c5b>] ? zil_commit.part.11+0x6b/0x750 [zfs]
[<ffffffffa0405462>] ? zfs_range_unlock+0xe2/0x2a0 [zfs]
[<ffffffffa042a552>] ? zvol_request+0x322/0x5d0 [zfs]
[<ffffffff8127fcb0>] ? generic_make_request+0xb0/0x100
[<ffffffff8127fd71>] ? submit_bio+0x71/0x150
[<ffffffff8117bfd0>] ? reset_node_managed_pages+0x40/0x40
[<ffffffff8117c5a0>] ? __swap_writepage+0x200/0x250
[<ffffffff812b26cb>] ? radix_tree_insert+0x2b/0xe0
[<ffffffff81156db4>] ? shmem_writepage+0x184/0x2c0
[<ffffffff81151dd9>] ? shrink_page_list+0x7c9/0xa60
[<ffffffff81152632>] ? shrink_inactive_list+0x192/0x530
[<ffffffff81153261>] ? shrink_lruvec+0x511/0x6a0
[<ffffffff811c277a>] ? __d_lookup+0x7a/0x150
[<ffffffff811c277a>] ? __d_lookup+0x7a/0x150
[<ffffffff81153464>] ? shrink_zone+0x74/0x1b0
[<ffffffff8115399d>] ? do_try_to_free_pages+0x12d/0x520
[<ffffffff8114f788>] ? throttle_direct_reclaim+0xa8/0x260
[<ffffffff81153e55>] ? try_to_free_pages+0xc5/0x190
[<ffffffff81148b46>] ? __alloc_pages_nodemask+0x726/0xb50
[<ffffffff8118a3f8>] ? alloc_pages_vma+0x98/0x160
[<ffffffff8116c35d>] ? handle_mm_fault+0xe3d/0x11c0
[<ffffffff81514951>] ? __schedule+0x2b1/0x6f0
[<ffffffff810582a7>] ? __do_page_fault+0x177/0x4f0
[<ffffffff81190024>] ? cache_grow+0x154/0x240
[<ffffffff81190196>] ? ____cache_alloc_node+0x86/0x150
[<ffffffff812b7016>] ? string.isra.7+0x36/0xe0
[<ffffffff812b849d>] ? vsnprintf+0x17d/0x5c0
[<ffffffff8151a5a8>] ? page_fault+0x28/0x30
[<ffffffff812b922c>] ? copy_user_generic_string+0x2c/0x40
[<ffffffff811cc408>] ? seq_read+0x258/0x360
[<ffffffff811aa6e3>] ? vfs_read+0x93/0x170
[<ffffffff811ab312>] ? SyS_read+0x42/0xa0
[<ffffffff8151873c>] ? tracesys+0x7e/0xc7
[<ffffffff8151879f>] ? system_call_trace_compare_end+0x10/0x15
 postgres        D ffff8800b9d999c8     0  5019   5011 0x00000000
ffff8800b9d99570 0000000000000086 0000000000012f40 ffff88002ceebfd8
0000000000012f40 ffff8800b9d99570 ffff8800b14f31c0 ffff8800b14f3000
ffff8800b14f31c8 0000000000000000 0000000000001000 0000000000000000
 Call Trace:
[<ffffffffa02cf4ed>] ? cv_wait_common+0xbd/0xf0 [spl]
[<ffffffff810a9590>] ? prepare_to_wait_event+0xf0/0xf0
[<ffffffffa0419c5b>] ? zil_commit.part.11+0x6b/0x750 [zfs]
[<ffffffffa0405462>] ? zfs_range_unlock+0xe2/0x2a0 [zfs]
[<ffffffffa042a552>] ? zvol_request+0x322/0x5d0 [zfs]
[<ffffffff8127fcb0>] ? generic_make_request+0xb0/0x100
[<ffffffff8127fd71>] ? submit_bio+0x71/0x150
[<ffffffff8117bfd0>] ? reset_node_managed_pages+0x40/0x40
[<ffffffff8117c5a0>] ? __swap_writepage+0x200/0x250
[<ffffffff81177276>] ? rmap_walk+0x266/0x340
[<ffffffff81151dd9>] ? shrink_page_list+0x7c9/0xa60
[<ffffffff81152632>] ? shrink_inactive_list+0x192/0x530
[<ffffffff81153261>] ? shrink_lruvec+0x511/0x6a0
[<ffffffff81153464>] ? shrink_zone+0x74/0x1b0
[<ffffffff8115399d>] ? do_try_to_free_pages+0x12d/0x520
[<ffffffff8114f788>] ? throttle_direct_reclaim+0xa8/0x260
[<ffffffff81153e55>] ? try_to_free_pages+0xc5/0x190
[<ffffffff81148b46>] ? __alloc_pages_nodemask+0x726/0xb50
[<ffffffff8118a3f8>] ? alloc_pages_vma+0x98/0x160
[<ffffffff8116c35d>] ? handle_mm_fault+0xe3d/0x11c0
[<ffffffff81171f8f>] ? mmap_region+0x15f/0x650
[<ffffffff810582a7>] ? __do_page_fault+0x177/0x4f0
[<ffffffff81172769>] ? do_mmap_pgoff+0x2e9/0x3b0
[<ffffffff8115b51b>] ? vm_mmap_pgoff+0x9b/0xc0
[<ffffffff8151a5a8>] ? page_fault+0x28/0x30
named           D ffff88001beb0e78     0 27168      1 0x00000000
ffff88001beb0a20 0000000000000086 0000000000012f40 ffff8800ae42ffd8
0000000000012f40 ffff88001beb0a20 ffff8800b14f31c0 ffff8800b14f3000
ffff8800b14f31c8 0000000000000000 0000000000001000 0000000000000000
Call Trace:
[<ffffffffa02cf4ed>] ? cv_wait_common+0xbd/0xf0 [spl]
[<ffffffff810a9590>] ? prepare_to_wait_event+0xf0/0xf0
[<ffffffffa0419c5b>] ? zil_commit.part.11+0x6b/0x750 [zfs]
[<ffffffffa0405462>] ? zfs_range_unlock+0xe2/0x2a0 [zfs]
[<ffffffffa042a552>] ? zvol_request+0x322/0x5d0 [zfs]
[<ffffffff8127fcb0>] ? generic_make_request+0xb0/0x100
[<ffffffff8127fd71>] ? submit_bio+0x71/0x150
[<ffffffff8117bfd0>] ? reset_node_managed_pages+0x40/0x40
[<ffffffff8117c5a0>] ? __swap_writepage+0x200/0x250
[<ffffffff81177276>] ? rmap_walk+0x266/0x340
[<ffffffff81151dd9>] ? shrink_page_list+0x7c9/0xa60
[<ffffffff81152632>] ? shrink_inactive_list+0x192/0x530
[<ffffffff81153261>] ? shrink_lruvec+0x511/0x6a0
[<ffffffff81153464>] ? shrink_zone+0x74/0x1b0
[<ffffffff8115399d>] ? do_try_to_free_pages+0x12d/0x520
[<ffffffff8114f788>] ? throttle_direct_reclaim+0xa8/0x260
[<ffffffff81153e55>] ? try_to_free_pages+0xc5/0x190
[<ffffffff81148b46>] ? __alloc_pages_nodemask+0x726/0xb50
[<ffffffffa031213e>] ? reiserfs_write_lock_nested+0x1e/0x40 [reiserfs]
[<ffffffff8118830d>] ? alloc_pages_current+0x9d/0x150
[<ffffffff8113fc63>] ? pagecache_get_page_fixed+0x53/0x1b0
[<ffffffff8113fdf5>] ? grab_cache_page_write_begin+0x25/0x40
[<ffffffffa02f2a45>] ? reiserfs_write_begin+0x55/0x200 [reiserfs]
[<ffffffff8113f046>] ? generic_perform_write+0xd6/0x1c0
[<ffffffff81140f98>] ? __generic_file_write_iter+0x158/0x340
[<ffffffff811411b9>] ? generic_file_write_iter+0x39/0xa0
rsyslogd: [origin software="rsyslogd" swVersion="8.4.2" x-pid="3176" x-info="http://www.rsyslog.com"] start

**Comment by loli10K** [comment] 2017-08-17 11:24
Likely duplicate of #5835 caused by memory pressure/direct reclaim when using swap-on-ZVOL, closing.

**Closed by loli10K** 2017-08-17 11:24 UTC
