### ISSUE TITLE
Mount encrypted datasets to replay logs

### ISSUE THREAD

**Issue by Harvie** [zfsonlinux/zfs#9576] opened 2019-11-12 16:00 UTC
I have failed SSD log device. Now ZFS is running in DEGRADED mode and i want to remove the device. This is my pool:

```
# zpool status
  pool: tank
 state: DEGRADED
status: One or more devices has experienced an error resulting in data
	corruption.  Applications may be affected.
action: Restore the file in question if possible.  Otherwise restore the
	entire pool from backup.
   see: http://zfsonlinux.org/msg/ZFS-8000-8A
  scan: scrub repaired 0B in 0 days 10:19:52 with 0 errors on Sun Oct 13 10:43:55 2019
config:

	NAME                        STATE     READ WRITE CKSUM
	tank                        DEGRADED     0     0     0
	  mirror-0                  ONLINE       0     0     0
	    wwn-0x5000c5006e9e2a92  ONLINE       0     0     0
	    wwn-0x5000c5006e9d9050  ONLINE       0     0     0
	logs	
	  4929563301382628102       UNAVAIL      0     0     0  was /dev/disk/by-id/ata-TS32GSSD370S_C160932696-part1

errors: 2 data errors, use '-v' for a list
```

This is how i try to remove it:
```
# zpool remove tank 4929563301382628102
cannot remove 4929563301382628102: Mount encrypted datasets to replay logs.
```

It says to mount encrypted datasets. but when i run `zfs get all`, all datasets say `encryption off` and `mounted yes`. So i don't know how am i supposed to mount encrypted datasets in this situation...

**Comment by behlendorf** [comment] 2019-11-13 00:37
@Harvie the error message in this case is a bit misleading.  This looks to me like a duplicate of #8748, which we were not able to reproduce.  Would you mind posting in #8748 the information @tcaputi asked for in this https://github.com/zfsonlinux/zfs/issues/8748#issuecomment-500568015 , and then we can take it from there.

**Closed by behlendorf** 2019-11-13 00:37 UTC
Labels: Type: Question

**Comment by devvythelopper** [comment] 2022-04-01 11:17
I've had a similar issue. I tried to remove a log device from a zpool and got:

```
cannot remove sdb1: Mount encrypted datasets to replay logs.
```

then I mounted all encrypted datasets, and tried again, but the error showed again...

I then exported the pool and imported it again. Then I mounted all datasets with 

```
zfs load-keys -a
zfs mount -a
```

then I tried again to remove the log device, and this time it worked!
