### ISSUE TITLE
Receive of raw encrypted dataset caused PANIC in zio_encrypt

### ISSUE THREAD

**Issue by aarononeal** [zfsonlinux/zfs#7231] opened 2018-02-24 21:09 UTC
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Ubuntu
Distribution Version    | 16.04.4 LTS (Xenial Xerus)
Linux Kernel                 | 4.4.0-1052-aws 
Architecture                 | x86_64
ZFS Version                  | 0.7.0-338_g41532e5
SPL Version                  | 0.7.0-29_g378c6ed

### Describe the problem you're observing

Receive of raw encrypted dataset causes a panic and stack trace below.

This happened 71.3M into a 223M dataset.

### Describe how to reproduce the problem

```
zfs send -w 'pool1/docker/data@snap-20180224.105113'|ssh -o batchMode=yes -o ConnectTimeout=30 'server.compute.amazonaws.com' 'zfs recv -F cloud1/docker/data'
```

@tcaputi My build includes your 2/21 fixes but maybe `-F` still has issues with encrypted datasets. The `cloud1/docker/data` dataset did not exist prior to send.

### Include any warning/errors/backtraces from the system logs

```
Feb 24 19:33:50 ip-172-31-22-6 kernel: [40709.869069] VERIFY3(0 == spa_do_crypt_abd(B_TRUE, spa, dsobj, bp, zio->io_txg, psize, zio->io_abd, eabd, iv, mac, salt, &no_crypt)) failed (0 == 2)
Feb 24 19:33:50 ip-172-31-22-6 kernel: [40709.876681] PANIC at zio.c:3866:zio_encrypt()
Feb 24 19:33:50 ip-172-31-22-6 kernel: [40709.880163] Showing stack for process 883
Feb 24 19:33:50 ip-172-31-22-6 kernel: [40709.880167] CPU: 0 PID: 883 Comm: z_wr_iss Tainted: P           OE   4.4.0-1052-aws #61-Ubuntu
Feb 24 19:33:50 ip-172-31-22-6 kernel: [40709.880168] Hardware name: Xen HVM domU, BIOS 4.2.amazon 08/24/2006
Feb 24 19:33:50 ip-172-31-22-6 kernel: [40709.880170]  0000000000000286 4e650f52da724e28 ffff88003c173ae0 ffffffff813fce53
Feb 24 19:33:50 ip-172-31-22-6 kernel: [40709.880173]  ffffffffc057daf8 0000000000000f1a ffff88003c173af0 ffffffffc02d54b2
Feb 24 19:33:50 ip-172-31-22-6 kernel: [40709.880175]  ffff88003c173c78 ffffffffc02d5585 ffff88003c173bc8 ffffffff00000030
Feb 24 19:33:50 ip-172-31-22-6 kernel: [40709.880177] Call Trace:
Feb 24 19:33:50 ip-172-31-22-6 kernel: [40709.880183]  [<ffffffff813fce53>] dump_stack+0x63/0x90
Feb 24 19:33:50 ip-172-31-22-6 kernel: [40709.880193]  [<ffffffffc02d54b2>] spl_dumpstack+0x42/0x50 [spl]
Feb 24 19:33:50 ip-172-31-22-6 kernel: [40709.880198]  [<ffffffffc02d5585>] spl_panic+0xc5/0x100 [spl]
Feb 24 19:33:50 ip-172-31-22-6 kernel: [40709.880242]  [<ffffffffc043ab20>] ? spa_do_crypt_abd+0x80/0x310 [zfs]
Feb 24 19:33:50 ip-172-31-22-6 kernel: [40709.880246]  [<ffffffff811ef701>] ? kmem_cache_alloc+0x1a1/0x1f0
Feb 24 19:33:50 ip-172-31-22-6 kernel: [40709.880285]  [<ffffffffc04ce613>] zio_encrypt+0x5a3/0x660 [zfs]
Feb 24 19:33:50 ip-172-31-22-6 kernel: [40709.880323]  [<ffffffffc04ced99>] ? zio_write_compress+0x6c9/0x6e0 [zfs]
Feb 24 19:33:50 ip-172-31-22-6 kernel: [40709.880361]  [<ffffffffc04cdcb0>] zio_execute+0x90/0xf0 [zfs]
Feb 24 19:33:50 ip-172-31-22-6 kernel: [40709.880366]  [<ffffffffc02d3714>] taskq_thread+0x2b4/0x4b0 [spl]
Feb 24 19:33:50 ip-172-31-22-6 kernel: [40709.880370]  [<ffffffff810ae930>] ? wake_up_q+0x70/0x70
Feb 24 19:33:50 ip-172-31-22-6 kernel: [40709.880406]  [<ffffffffc04cdc20>] ? zio_reexecute+0x420/0x420 [zfs]
Feb 24 19:33:50 ip-172-31-22-6 kernel: [40709.880411]  [<ffffffffc02d3460>] ? task_done+0xb0/0xb0 [spl]
Feb 24 19:33:50 ip-172-31-22-6 kernel: [40709.880414]  [<ffffffff810a2ee7>] kthread+0xe7/0x100
Feb 24 19:33:50 ip-172-31-22-6 kernel: [40709.880416]  [<ffffffff810a2e00>] ? kthread_create_on_node+0x1e0/0x1e0
Feb 24 19:33:50 ip-172-31-22-6 kernel: [40709.880420]  [<ffffffff81822af5>] ret_from_fork+0x55/0x80
Feb 24 19:33:50 ip-172-31-22-6 kernel: [40709.880422]  [<ffffffff810a2e00>] ? kthread_create_on_node+0x1e0/0x1e0
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.228111] INFO: task z_wr_iss:883 blocked for more than 120 seconds.
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.231539]       Tainted: P           OE   4.4.0-1052-aws #61-Ubuntu
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.234725] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.238293] z_wr_iss        D ffff88003c173ad8     0   883      2 0x00000000
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.238298]  ffff88003c173ad8 ffff880029900988 ffff88001f35b700 ffff880036e81b80
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.238300]  ffff88003c174000 0000000000000f1a ffffffffc0557070 ffffffffc057e000
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.238302]  ffff880029900988 ffff88003c173af0 ffffffff8181e525 ffffffffc057daf8
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.238304] Call Trace:
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.238312]  [<ffffffff8181e525>] schedule+0x35/0x80
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.238320]  [<ffffffffc02d55aa>] spl_panic+0xea/0x100 [spl]
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.238363]  [<ffffffffc043ab20>] ? spa_do_crypt_abd+0x80/0x310 [zfs]
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.238367]  [<ffffffff811ef701>] ? kmem_cache_alloc+0x1a1/0x1f0
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.238406]  [<ffffffffc04ce613>] zio_encrypt+0x5a3/0x660 [zfs]
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.238447]  [<ffffffffc04ced99>] ? zio_write_compress+0x6c9/0x6e0 [zfs]
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.238485]  [<ffffffffc04cdcb0>] zio_execute+0x90/0xf0 [zfs]
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.238490]  [<ffffffffc02d3714>] taskq_thread+0x2b4/0x4b0 [spl]
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.238494]  [<ffffffff810ae930>] ? wake_up_q+0x70/0x70
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.238530]  [<ffffffffc04cdc20>] ? zio_reexecute+0x420/0x420 [zfs]
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.238535]  [<ffffffffc02d3460>] ? task_done+0xb0/0xb0 [spl]
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.238538]  [<ffffffff810a2ee7>] kthread+0xe7/0x100
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.238541]  [<ffffffff810a2e00>] ? kthread_create_on_node+0x1e0/0x1e0
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.238544]  [<ffffffff81822af5>] ret_from_fork+0x55/0x80
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.238546]  [<ffffffff810a2e00>] ? kthread_create_on_node+0x1e0/0x1e0
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.238551] INFO: task txg_sync:1486 blocked for more than 120 seconds.
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.241690]       Tainted: P           OE   4.4.0-1052-aws #61-Ubuntu
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.244828] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.248553] txg_sync        D ffff88003ba5ba98     0  1486      2 0x00000000
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.248556]  ffff88003ba5ba98 ffff880015be4520 ffff880036e81b80 ffff88003b146040
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.248558]  ffff88003ba5c000 ffff88003ba5bad0 ffff88003e210440 ffff88003e210440
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.248560]  ffff880015be2668 ffff88003ba5bab0 ffffffff8181e525 00000001009b4bbb
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.248562] Call Trace:
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.248565]  [<ffffffff8181e525>] schedule+0x35/0x80
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.248567]  [<ffffffff818215e9>] schedule_timeout+0x129/0x270
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.248572]  [<ffffffff810ed680>] ? trace_event_raw_event_tick_stop+0x120/0x120
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.248575]  [<ffffffff810f6afe>] ? ktime_get+0x3e/0xb0
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.248577]  [<ffffffff8181dcb4>] io_schedule_timeout+0xa4/0x110
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.248583]  [<ffffffffc02d767c>] __cv_timedwait_common+0x12c/0x170 [spl]
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.248587]  [<ffffffff810c6630>] ? wake_atomic_t_function+0x60/0x60
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.248592]  [<ffffffffc02d76f9>] __cv_timedwait_io+0x19/0x20 [spl]
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.248631]  [<ffffffffc04d10a3>] zio_wait+0x123/0x260 [zfs]
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.248662]  [<ffffffffc043bd08>] dsl_pool_sync+0xb8/0x410 [zfs]
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.248697]  [<ffffffffc045f01f>] spa_sync+0x40f/0xd40 [zfs]
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.248700]  [<ffffffff810c5ff4>] ? __wake_up+0x44/0x50
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.248703]  [<ffffffff810cd281>] ? __raw_callee_save___pv_queued_spin_unlock+0x11/0x20
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.248738]  [<ffffffffc0472442>] txg_sync_thread+0x2e2/0x4b0 [zfs]
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.248773]  [<ffffffffc0472160>] ? txg_delay+0x170/0x170 [zfs]
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.248777]  [<ffffffffc02d24a0>] ? __thread_exit+0x20/0x20 [spl]
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.248781]  [<ffffffffc02d2513>] thread_generic_wrapper+0x73/0x80 [spl]
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.248784]  [<ffffffff810a2ee7>] kthread+0xe7/0x100
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.248786]  [<ffffffff810a2e00>] ? kthread_create_on_node+0x1e0/0x1e0
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.248788]  [<ffffffff81822af5>] ret_from_fork+0x55/0x80
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.248790]  [<ffffffff810a2e00>] ? kthread_create_on_node+0x1e0/0x1e0
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.248797] INFO: task zfs:30392 blocked for more than 120 seconds.
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.251705]       Tainted: P           OE   4.4.0-1052-aws #61-Ubuntu
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.254838] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.258691] zfs             D ffff88000e7eb8e8     0 30392  30354 0x00000000
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.258693]  ffff88000e7eb8e8 ffff88000d1d5270 ffff8800262e8000 ffff880036e8a940
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.258696]  ffff88000e7ec000 ffff88000d1d5230 ffff88000d1d5258 ffff88000d1d5270
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.258698]  0000000000000000 ffff88000e7eb900 ffffffff8181e525 ffff88000d1d5268
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.258700] Call Trace:
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.258702]  [<ffffffff8181e525>] schedule+0x35/0x80
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.258708]  [<ffffffffc02d74bb>] cv_wait_common+0x10b/0x140 [spl]
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.258711]  [<ffffffff810c6630>] ? wake_atomic_t_function+0x60/0x60
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.258715]  [<ffffffffc02d7505>] __cv_wait+0x15/0x20 [spl]
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.258738]  [<ffffffffc04037d2>] bqueue_enqueue+0x62/0xe0 [zfs]
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.258764]  [<ffffffffc04194ca>] dmu_recv_stream+0x68a/0x1190 [zfs]
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.258789]  [<ffffffffc0412690>] ? receive_cksum+0x30/0x30 [zfs]
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.258814]  [<ffffffffc0418df0>] ? dmu_recv_begin+0x180/0x1d0 [zfs]
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.258852]  [<ffffffffc04aa3b8>] zfs_ioc_recv_impl+0xc58/0x1100 [zfs]
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.258855]  [<ffffffff810cd281>] ? __raw_callee_save___pv_queued_spin_unlock+0x11/0x20
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.258893]  [<ffffffffc04aae89>] zfs_ioc_recv_new+0x369/0x3f0 [zfs]
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.258898]  [<ffffffffc02d2369>] ? spl_vmem_alloc+0x19/0x20 [spl]
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.258906]  [<ffffffffc033f10f>] ? nv_alloc_sleep_spl+0x1f/0x30 [znvpair]
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.258910]  [<ffffffffc033a670>] ? nv_mem_zalloc.isra.12+0x30/0x40 [znvpair]
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.258914]  [<ffffffffc033a749>] ? nvlist_xalloc.part.13+0x69/0xd0 [znvpair]
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.258951]  [<ffffffffc04a6c99>] zfsdev_ioctl+0x219/0x670 [zfs]
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.258954]  [<ffffffff81224c1f>] do_vfs_ioctl+0x2af/0x4b0
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.258957]  [<ffffffff8106c754>] ? __do_page_fault+0x1b4/0x400
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.258959]  [<ffffffff81224e99>] SyS_ioctl+0x79/0x90
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.258962]  [<ffffffff81822688>] entry_SYSCALL_64_fastpath+0x1c/0xbb
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.258964] INFO: task receive_writer:30444 blocked for more than 120 seconds.
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.262499]       Tainted: P           OE   4.4.0-1052-aws #61-Ubuntu
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.265599] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.269503] receive_writer  D ffff88002606fb58     0 30444      2 0x00000000
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.269506]  ffff88002606fb58 ffff88003cebe190 ffffffff81e13500 ffff88003676b700
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.269509]  ffff880026070000 ffff88003cebe150 ffff88003cebe178 ffff88003cebe190
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.269511]  0000000000000000 ffff88002606fb70 ffffffff8181e525 ffff88003cebe188
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.269513] Call Trace:
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.269516]  [<ffffffff8181e525>] schedule+0x35/0x80
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.269523]  [<ffffffffc02d74bb>] cv_wait_common+0x10b/0x140 [spl]
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.269526]  [<ffffffff810c6630>] ? wake_atomic_t_function+0x60/0x60
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.269531]  [<ffffffffc02d7505>] __cv_wait+0x15/0x20 [spl]
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.269562]  [<ffffffffc041cc52>] dmu_tx_wait+0xb2/0x3a0 [zfs]
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.269588]  [<ffffffffc041cfce>] dmu_tx_assign+0x8e/0x460 [zfs]
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.269613]  [<ffffffffc041bd4c>] ? dmu_tx_hold_object_impl+0x6c/0xc0 [zfs]
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.269638]  [<ffffffffc04144c0>] receive_object+0x3a0/0x8e0 [zfs]
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.269643]  [<ffffffffc02d1af8>] ? spl_kmem_cache_free+0x138/0x1c0 [spl]
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.269648]  [<ffffffff810cd281>] ? __raw_callee_save___pv_queued_spin_unlock+0x11/0x20
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.269652]  [<ffffffffc02d1af8>] ? spl_kmem_cache_free+0x138/0x1c0 [spl]
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.269654]  [<ffffffff810cd281>] ? __raw_callee_save___pv_queued_spin_unlock+0x11/0x20
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.269680]  [<ffffffffc0417969>] receive_writer_thread+0x439/0xdb0 [zfs]
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.269683]  [<ffffffff810bb4e4>] ? enqueue_task_fair+0xa4/0x8b0
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.269685]  [<ffffffff810cd281>] ? __raw_callee_save___pv_queued_spin_unlock+0x11/0x20
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.269689]  [<ffffffffc02cfe4a>] ? spl_kmem_free+0x2a/0x40 [spl]
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.269693]  [<ffffffffc02d24a0>] ? __thread_exit+0x20/0x20 [spl]
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.269717]  [<ffffffffc0417530>] ? receive_freeobjects.isra.11+0x110/0x110 [zfs]
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.269721]  [<ffffffffc02d24a0>] ? __thread_exit+0x20/0x20 [spl]
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.269725]  [<ffffffffc02d2513>] thread_generic_wrapper+0x73/0x80 [spl]
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.269728]  [<ffffffff810a2ee7>] kthread+0xe7/0x100
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.269730]  [<ffffffff810a2e00>] ? kthread_create_on_node+0x1e0/0x1e0
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.269733]  [<ffffffff81822af5>] ret_from_fork+0x55/0x80
Feb 24 19:37:21 ip-172-31-22-6 kernel: [40920.269735]  [<ffffffff810a2e00>] ? kthread_create_on_node+0x1e0/0x1e0
```

**Comment by loli10K** [comment] 2018-02-24 21:23
Duplicate of #7215

**Closed** 2018-02-24 21:44 UTC
