### ISSUE TITLE
Kernel Oops - RIP: 0010:avl_insert+0x4a/0xe0 [zavl]

### ISSUE THREAD

**Issue by ajl5t** [zfsonlinux/zfs#9481] opened 2019-10-18 19:58 UTC
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Ubuntu
Distribution Version	| 18.04.03
Linux Kernel	| 4.15.0-55-generic
Architecture	| x86_64
ZFS Version	| 0.7.5-1ubuntu16.6
SPL Version	| 0.7.5-1ubuntu1

### Describe the problem you're observing
Kernel crash on avl_insert.

### Include any warning/errors/backtraces from the system logs

```
Oct 14 22:49:31 my_server_name kernel: [89268.080648] BUG: unable to handle kernel paging request at ffffffffc086e036
Oct 14 22:49:31 my_server_name kernel: [89268.080715] IP: avl_insert+0x4a/0xe0 [zavl]
Oct 14 22:49:31 my_server_name kernel: [89268.080743] PGD 1d6a0e067 P4D 1d6a0e067 PUD 1d6a10067 PMD 105b0c6067 PTE 104ecf6061
Oct 14 22:49:31 my_server_name kernel: [89268.080795] Oops: 0003 [#1] SMP PTI
Oct 14 22:49:31 my_server_name kernel: [89268.080820] Modules linked in: bonding xt_tcpudp xt_multiport xt_set xt_conntrack iptable_filter iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_i
pv4 nf_nat nf_conntrack iptable_mangle ip_set_hash_net ip_set_bitmap_port ip_set_hash_ip ip_set nfnetlink arptable_filter arp_tables intel_rapl sb_edac x86_pkg_temp_thermal intel_powerclamp
 coretemp kvm_intel kvm irqbypass intel_cstate intel_rapl_perf joydev input_leds mei_me mei lpc_ich ioatdma zfs(PO) zunicode(PO) zavl(PO) icp(PO) zcommon(PO) znvpair(PO) spl(O) ipmi_ssif ip
mi_si ipmi_devintf ipmi_msghandler shpchp acpi_pad acpi_power_meter mac_hid sch_fq_codel ib_iser rdma_cm iw_cm ib_cm ib_core iscsi_tcp libiscsi_tcp libiscsi scsi_transport_iscsi drbd lru_ca
che ip_tables x_tables autofs4 btrfs zstd_compress raid10 raid456 async_raid6_recov async_memcpy
Oct 14 22:49:31 my_server_name kernel: [89268.081256]  async_pq async_xor async_tx xor raid6_pq libcrc32c raid0 multipath linear dm_mirror dm_region_hash dm_log ixgbe igb ast ttm crct10dif_pcl
mul crc32_pclmul ses ghash_clmulni_intel drm_kms_helper pcbc enclosure syscopyarea sysfillrect aesni_intel sysimgblt aes_x86_64 hid_generic raid1 fb_sys_fops nvme dca i2c_algo_bit usbhid cr
ypto_simd ahci mpt3sas glue_helper ptp drm nvme_core cryptd mdio hid libahci raid_class pps_core scsi_transport_sas wmi
Oct 14 22:49:31 my_server_name kernel: [89268.081509] CPU: 18 PID: 12089 Comm: smbd Tainted: P           O L   4.15.0-55-generic #60-Ubuntu
Oct 14 22:49:31 my_server_name kernel: [89268.081606] RIP: 0010:avl_insert+0x4a/0xe0 [zavl]
Oct 14 22:49:31 my_server_name kernel: [89268.081636] RSP: 0018:ffffb9e2d8277ab8 EFLAGS: 00010286
Oct 14 22:49:31 my_server_name kernel: [89268.081668] RAX: ffff96f00c2d7208 RBX: ffff96f00c2d7200 RCX: 0000000000000000
Oct 14 22:49:31 my_server_name kernel: [89268.081710] RDX: 0000000000000000 RSI: ffffffffc086e036 RDI: ffff96f00b051d60
Oct 14 22:49:31 my_server_name kernel: [89268.081751] RBP: ffffb9e2d8277b08 R08: ffffffffc086e036 R09: ffff96e81f407180
Oct 14 22:49:31 my_server_name kernel: [89268.081792] R10: ffffb9e2d82779f0 R11: 0000000000000400 R12: ffff96f00b051d30
Oct 14 22:49:31 my_server_name kernel: [89268.081833] R13: ffff96f00b051d60 R14: ffffffffc086e02e R15: 0000000000000000
Oct 14 22:49:31 my_server_name kernel: [89268.081876] FS:  00007f157ce22700(0000) GS:ffff96f01f380000(0000) knlGS:0000000000000000
Oct 14 22:49:31 my_server_name kernel: [89268.081922] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Oct 14 22:49:31 my_server_name kernel: [89268.081956] CR2: ffffffffc086e036 CR3: 0000000d241cc004 CR4: 00000000001606e0
Oct 14 22:49:31 my_server_name kernel: [89268.081998] Call Trace:
Oct 14 22:49:31 my_server_name kernel: [89268.082089]  ? zfs_range_lock+0x39c/0x5a0 [zfs]
Oct 14 22:49:31 my_server_name kernel: [89268.082126]  ? spl_kmem_alloc+0xe6/0x1a0 [spl]
Oct 14 22:49:31 my_server_name kernel: [89268.082208]  zvol_request+0x15c/0x330 [zfs]
Oct 14 22:49:31 my_server_name kernel: [89268.082242]  generic_make_request+0x124/0x300
Oct 14 22:49:31 my_server_name kernel: [89268.082272]  submit_bio+0x73/0x140
Oct 14 22:49:31 my_server_name kernel: [89268.082297]  ? submit_bio+0x73/0x140
Oct 14 22:49:31 my_server_name kernel: [89268.082373]  vdev_disk_io_start+0x61e/0x760 [zfs]
Oct 14 22:49:31 my_server_name kernel: [89268.084346]  ? spl_kmem_cache_alloc+0x64/0x140 [spl]
Oct 14 22:49:31 my_server_name kernel: [89268.086285]  ? _cond_resched+0x19/0x40
Oct 14 22:49:31 my_server_name kernel: [89268.088202]  ? mutex_lock+0x12/0x40
Oct 14 22:49:31 my_server_name kernel: [89268.090133]  ? taskq_init_ent+0x3c/0x80 [spl]
Oct 14 22:49:31 my_server_name kernel: [89268.092046]  ? _cond_resched+0x19/0x40
Oct 14 22:49:31 my_server_name kernel: [89268.093945]  ? mutex_lock+0x12/0x40
Oct 14 22:49:31 my_server_name kernel: [89268.095870]  zio_vdev_io_start+0xa8/0x340 [zfs]
Oct 14 22:49:31 my_server_name kernel: [89268.097801]  ? zio_vdev_io_start+0xa8/0x340 [zfs]
Oct 14 22:49:31 my_server_name kernel: [89268.099730]  zio_nowait+0xb1/0x150 [zfs]
Oct 14 22:49:31 my_server_name kernel: [89268.101662]  zio_flush+0x2d/0x30 [zfs]
Oct 14 22:49:31 my_server_name kernel: [89268.103585]  zil_commit_writer+0x76d/0x7c0 [zfs]
Oct 14 22:49:31 my_server_name kernel: [89268.105521]  zil_commit.part.14+0x93/0x100 [zfs]
```

**Comment by kusumi** [comment] 2019-10-18 21:45
https://github.com/zfsonlinux/zfs/issues/8379

**Comment by ajl5t** [comment] 2019-11-12 22:23
> #8379

Thanks Kusumi for linking that.  Do you know what version includes the fix?  I searched in the release notes for #8379 or #8401, but am not seeing it mentioned there.

Thank you

**Comment by behlendorf** [comment] 2019-11-13 00:56
@ajl5t the fix for this was included as of 0.8.0, it was not backported to the earlier 0.7.x releases.  If you're comfortable rebuilding from source it should be pretty straight forward to cherry-pick this commit, 9abbee491285303d78704e937a13ddcbb6cd0f79.

**Comment by ajl5t** [comment] 2019-11-13 13:43
@behlendorf Thanks, Brian.  I will look into doing the upgrade to 0.8.0 or potentially beyond to 0.8.1 or 0.8.2.

**Comment by behlendorf** [comment] 2019-11-13 18:41
@ajl5t I'd recommend installing the latest, 0.8.2, if you upgrade since it includes additional bug fixes.

**Comment by behlendorf** [comment] 2019-11-13 18:42
Closing as duplicate of #8379.

**Closed by behlendorf** 2019-11-13 18:42 UTC
Labels: Type: Defect
