### ISSUE TITLE
ZFS Linux/illumos functionality differences

### ISSUE THREAD

**Issue by kvaps** [zfsonlinux/zfs#3851] opened 2015-09-28 13:55 UTC
Permissions are applied, but /usr/sbin/zfs does not runs from simple user

``` bash
# zfs create rpool/test
# zfs allow someuser destroy,clone,create,mount,share,sharenfs rpool/test
# zfs allow rpool/test
---- Permissions on rpool/test ---------------------------------------
Local+Descendent permissions:
    user someuser clone,create,destroy,mount,share,sharenfs
# su - someuser
# zfs create rpool/test/123
Permission denied the ZFS utilities must be run as root.
```

CentOS Linux release 7.1.1503 (Core)

**Comment by DeHackEd** [comment] 2015-09-28 14:02
#434 This is a known deficiency. More advanced ZFS features are not likely to be available for a while. We're still focusing on stability, reliability and the most common features.

**Comment by behlendorf** [comment] 2015-09-28 18:14
This is one of the few remaining standard ZFS features which has not yet been implemented for Linux.  We'd definitely like to implement it once a developer has time to work on it.

**Comment by ryao** [comment] 2015-09-30 13:06
Here is a brief summary of the things we are missing that Illumos has:

* Delegation support
* ClamAV support
* iSCSI integration (shareiscsi)
* Multiple vdev dump device support (a feature flag that has some minor disk format changes)
* sharesmb option support
* NFSv4 ACL support (Linux's NFSv4 ACL support being bad is a blocker)
* Support for OpenSolaris File Attributes (we currently only support the ones common to both Linux and OpenSolaris).

There might be others, but those are all that I recall offhand.

**Comment by FransUrbo** [comment] 2015-09-30 13:46
> iSCSI integration (shareiscsi)
> sharesmb option support

Actually, neither of these are technically true. Especially not the last one! It's not good (I have a rewrite), but it works most of the time for most people.

**Comment by behlendorf** [comment] 2015-09-30 17:36
This is a good thing to document to let me expand a little on each of these items.

* Delegation support - This can be implemented it requires integration with Linux permissions, #434.
* ClamAV - This can be implemented but there's been very little interest.
* iSCSI (shareiscsi) - This support was [removed from illumos in 2010](https://github.com/illumos/illumos-gate/commit/ab003da878e3fe36b164e1856f9e15a78384c9eb), there is interest in adding it back.  One nice flexible way to go about this is to build it on new ZED infrastructure for handling share events.
* sharesmb option support - This can be implemented it also depends on new ZED infrastructure.
* NFSv4 ACL support - Depends on Linux adding support NFSv4 ACLs or some equivalent.
* Multiple vdev dump device support - This feature is useful for compatibility between platform but serves no real value under Linux due to how differently crash dumps are handled.
* Support for OpenSolaris File Attributes - Only support for the ones common to both Linux and OpenSolaris, support should be added for Linux specific attributes.

**Comment by kpande** [comment] 2019-02-16 03:25
duplicate of:

#362 - zfs permissions
#1608 - zfs allow does not work
#6865 - user namespaces fixes and features
#7860 - fix 'zfs allow' for create time permissions

resolved in:
#434 - Support ZFS delegations

**Closed by kpande** 2019-02-16 03:25 UTC
Labels: Type: Documentation
