### ISSUE TITLE
/boot/grub is not readable by GRUB on boot

### ISSUE THREAD

**Issue by CodeBleu** [zfsonlinux/zfs#1828] opened 2013-11-03 05:44 UTC
Reminder for ryao to document possible causes for getting "/boot/grub is not readable by GRUB on boot" error.

**Comment by ryao** [comment] 2016-07-13 14:33
@behlendorf I believe that this issue is obsolete. The causes likely have been long fixed in GRUB2.

The only thing here that comes to mind off the top of my head is that this might happen if the pool is newer than what GRUB2 supports. I would need to look at the code to be sure, but I am fairly confident this could be closed as obsolete.

**Comment by behlendorf** [comment] 2016-07-13 16:32
@ryao thanks.  Closing as obsolete.

**Closed by behlendorf** 2016-07-13 16:32 UTC
Labels: Difficulty - Easy, Documentation, ZFS Labels / GRUB
