### ISSUE TITLE
Schedule a scrub once the resilver is finished

### ISSUE THREAD

**Issue by FransUrbo** [zfsonlinux/zfs#4662] opened 2016-05-18 10:17 UTC
I'd like the option to schedule a scrub (<code>zpool scrub [pool]</code>) which should run as soon as the current resilver is finished. As it is now, it (the scrub request) will fail and I have to wait at the console until the resilver is done until I can run the scrub.

```
# zpool scrub share
cannot scrub share: currently resilvering
# zpool status
  pool: share
 state: ONLINE
status: One or more devices is currently being resilvered.  The pool will
        continue to function, possibly in a degraded state.
action: Wait for the resilver to complete.
  scan: resilver in progress since Wed May 18 11:11:32 2016
    130M scanned out of 29.2T at 9.30M/s, (scan is slow, no estimated time)
    5.69M resilvered, 0.00% done
```

This would probably be something that ZED should deal with.

**Comment by ptx0** [comment] 2016-05-18 11:23
resilver already scrubs, no?

**Comment by Lilolbet** [comment] 2016-05-18 19:03
No it doesn't. Say you have two mirrors of two drives. You lose one drive in one of the mirrors and replace it. It resilvers from it's mirror companion, not touching the other drives in the pool.

**Comment by DeHackEd** [comment] 2016-05-18 19:16
A resilver does do a metadata walk of the whole pool, but while a scrub will read from all disks (parity, mirrors and copies/ditto blocks) a resilver will only do so when it involves a disk marked as `(resilvering)`.

**Comment by GregorKopka** [comment] 2016-05-23 20:37
Wouldn't be a mode in which the resilver touches everything be better?

**Comment by rlaager** [comment] 2016-05-23 22:30
Not necessarily. If you have a resilver that is half done, it'd still be better to let it finish before starting the scrub. The behavior requested here would be especially nice for the default system-wide scrubbing script (if your distro has such a thing).

**Comment by kingneutron** [comment] 2016-06-18 02:56
--You can accomplish similar with a shell script (recommend running in a GNU "screen" session):

<code>
#!/bin/bash
zp=your-zfs-pool-name-here
# OR
zp=$1 # pass arg to script

        printf `date +%H:%M:%S`" ...waiting for $zp resilver to complete..."
        waitresilver=1
        while [ $waitresilver -gt 0 ];do 
          waitresilver=`zpool status -v $zp |grep -c resilvering`
          sleep 5
        done 
        echo 'Syncing to be sure'; time sync;

# do your next thing after this line
zpool scrub $zp

</code>

**Comment by behlendorf** [comment] 2016-10-19 23:39
@tonyhutter this might be a nice configurable way to handle some of drive replacement issues we talked about regarding when a pool should be automatically scrubbed.

**Comment by tonyhutter** [comment] 2016-10-20 01:01
Yep, this would be very nice.  You could kick off a zedlet on a resilver finish event to do it.  Below is a **completely untested** script, using `resilver_finish-notify.sh` as inspiration.  If I wrote it correctly, you should just be able to paste it in `cmd/zed/zed.d/resilver_finish-start-scrub.sh` and it will work:

```
# resilver_finish-start-scrub.sh
# Run a scrub after a resilver
#
# Exit codes:
# 9: internal error
#
[ -f "${ZED_ZEDLET_DIR}/zed.rc" ] && . "${ZED_ZEDLET_DIR}/zed.rc"
. "${ZED_ZEDLET_DIR}/zed-functions.sh"

[ -n "${ZEVENT_POOL}" ] || exit 9
[ -n "${ZEVENT_SUBCLASS}" ] || exit 9

zed_check_cmd "${ZPOOL}" || exit 9

if   [ "${ZEVENT_SUBCLASS}" = "resilver_finish" ]; then
	${ZPOOL} scrub ${ZEVENT_POOL}
fi
```

**Comment by pashford** [comment] 2018-01-10 17:05
If I understand the dRAID information I've been reading, this feature would be very important for pools containing dRAID VDEVs, as a dRAID resilver doesn't do checksum validation of the source data.

Has the above script from @tonyhutter been tested yet?

**Comment by behlendorf** [comment] 2018-01-10 21:41
@pashford yes we're going to want exactly this for dRAID.

@tonyhutter what do you think about opening a PR which adds this script, then create a new test case under `tests/zfs-tests/tests/functional/fault/` which verifies it works as intended.

**Comment by tonyhutter** [comment] 2018-01-12 17:55
@behlendorf good idea, I'm on it.

**Closed** 2018-02-23 19:38 UTC
Labels: Feature, zed
