### ISSUE TITLE
backtrace when sending encrypted dataset

### ISSUE THREAD

**Issue by kpande** [zfsonlinux/zfs#7223] opened 2018-02-23 07:04 UTC
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Gentoo
Distribution Version    | 17.0
Linux Kernel                 | 4.14.20
Architecture                 | amd64
ZFS Version                  | 0.7.0-330_g09302a4c (master)
SPL Version                  | master

### Describe the problem you're observing
```
[ 1049.376479] VERIFY3(0 == spa_do_crypt_abd(B_TRUE, spa, dsobj, bp, zio->io_txg, psize, zio->io_abd, eabd, iv, mac, salt, &no_crypt)) failed (0 == 2)
[ 1049.376484] PANIC at zio.c:3866:zio_encrypt()
[ 1049.376486] Showing stack for process 13445
[ 1049.376489] CPU: 0 PID: 13445 Comm: z_wr_iss Tainted: P           O    4.14.20-gentoo #1
[ 1049.376490] Hardware name:                  /DX79TO, BIOS SIX7910J.86A.0650.2014.0307.0138 03/07/2014
[ 1049.376492] Call Trace:
[ 1049.376501]  dump_stack+0x63/0x81
[ 1049.376508]  spl_dumpstack+0x42/0x50 [spl]
[ 1049.376511]  spl_panic+0xc8/0x110 [spl]
[ 1049.376514]  ? spl_kmem_cache_alloc+0x64/0xa20 [spl]
[ 1049.376534]  ? spa_do_crypt_abd+0x44/0x4f0 [zfs]
[ 1049.376543]  zio_push_transform+0x5bb/0x12d0 [zfs]
[ 1049.376554]  ? zio_push_transform+0xc95/0x12d0 [zfs]
[ 1049.376564]  zio_execute+0x90/0x4d0 [zfs]
[ 1049.376566]  taskq_dispatch_delay+0x5b1/0x900 [spl]
[ 1049.376569]  ? wake_up_q+0x80/0x80
[ 1049.376579]  ? zio_interrupt+0x17c0/0x17c0 [zfs]
[ 1049.376582]  kthread+0x128/0x140
[ 1049.376584]  ? taskq_dispatch_delay+0x320/0x900 [spl]
[ 1049.376585]  ? kthread_create_on_node+0x40/0x40
[ 1049.376587]  ? kthread_create_on_node+0x40/0x40
[ 1049.376589]  ret_from_fork+0x35/0x40
```
### Describe how to reproduce the problem
`zfs send -Rw pool/filesystem | zfs recv -Fus pool2/filesystem`

**Comment by kpande** [comment] 2018-02-23 07:05
@tcaputi close this if satisfied that it's a duplicate, please

**Comment by tcaputi** [comment] 2018-02-23 07:06
Duplicate of #7215

**Closed by tcaputi** 2018-02-23 07:06 UTC

**Comment by kpande** [comment] 2018-04-01 22:00
@tcaputi I'm still seeing this one;

```
Mar 27 13:03:19 labmouse kernel: [  875.581219] VERIFY3(0 == spa_do_crypt_abd(B_TRUE, spa, dsobj, bp, zio->io_txg, psize, zio->io_abd, eabd, iv, mac, salt, &no_crypt)) failed (0 == 2)
Mar 27 13:03:19 labmouse kernel: [  875.581226] PANIC at zio.c:3866:zio_encrypt()
Mar 27 13:03:19 labmouse kernel: [  875.581229] Showing stack for process 5573
Mar 27 13:03:19 labmouse kernel: [  875.581234] CPU: 4 PID: 5573 Comm: z_wr_iss Tainted: P           O     4.15.12-gentoo #1
Mar 27 13:03:19 labmouse kernel: [  875.581235] Hardware name: System manufacturer System Product Name/PRIME X399-A, BIOS 0503 01/03/2018
Mar 27 13:03:19 labmouse kernel: [  875.581237] Call Trace:
Mar 27 13:03:19 labmouse kernel: [  875.581250]  dump_stack+0x4f/0x70
Mar 27 13:03:19 labmouse kernel: [  875.581258]  spl_dumpstack+0x42/0x50 [spl]
Mar 27 13:03:19 labmouse kernel: [  875.581262]  spl_panic+0xc5/0x100 [spl]
Mar 27 13:03:19 labmouse kernel: [  875.581267]  ? spl_kmem_cache_alloc+0x64/0x700 [spl]
Mar 27 13:03:19 labmouse kernel: [  875.581270]  ? spl_kmem_cache_alloc+0x64/0x700 [spl]
Mar 27 13:03:19 labmouse kernel: [  875.581289]  ? spa_do_crypt_abd+0x4f/0x2f0 [zfs]
Mar 27 13:03:19 labmouse kernel: [  875.581302]  zio_push_transform+0x5f1/0x12b0 [zfs]
Mar 27 13:03:19 labmouse kernel: [  875.581314]  ? zio_push_transform+0xc56/0x12b0 [zfs]
Mar 27 13:03:19 labmouse kernel: [  875.581325]  zio_execute+0x90/0xf0 [zfs]
Mar 27 13:03:19 labmouse kernel: [  875.581329]  taskq_dispatch_delay+0x56e/0x8c0 [spl]
Mar 27 13:03:19 labmouse kernel: [  875.581334]  ? wake_up_q+0x80/0x80
Mar 27 13:03:19 labmouse kernel: [  875.581345]  ? zio_interrupt+0x19e0/0x19e0 [zfs]
Mar 27 13:03:19 labmouse kernel: [  875.581349]  kthread+0x121/0x140
Mar 27 13:03:19 labmouse kernel: [  875.581352]  ? taskq_dispatch_delay+0x2e0/0x8c0 [spl]
Mar 27 13:03:19 labmouse kernel: [  875.581355]  ? kthread_create_worker_on_cpu+0x40/0x40
Mar 27 13:03:19 labmouse kernel: [  875.581357]  ? kthread_create_worker_on_cpu+0x40/0x40
Mar 27 13:03:19 labmouse kernel: [  875.581360]  ret_from_fork+0x22/0x40
Mar 27 13:07:10 labmouse kernel: [ 1106.927609] INFO: task z_wr_iss:5573 blocked for more than 120 seconds.
Mar 27 13:07:10 labmouse kernel: [ 1106.927613]       Tainted: P           O     4.15.12-gentoo #1
Mar 27 13:07:10 labmouse kernel: [ 1106.927614] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Mar 27 13:07:10 labmouse kernel: [ 1106.927615] z_wr_iss        D    0  5573      2 0x80000000
Mar 27 13:07:10 labmouse kernel: [ 1106.927619] Call Trace:
Mar 27 13:07:10 labmouse kernel: [ 1106.927627]  __schedule+0x1bb/0x7f0
Mar 27 13:07:10 labmouse kernel: [ 1106.927632]  schedule+0x36/0x90
Mar 27 13:07:10 labmouse kernel: [ 1106.927637]  spl_panic+0xeb/0x100 [spl]
Mar 27 13:07:10 labmouse kernel: [ 1106.927642]  ? spl_kmem_cache_alloc+0x64/0x700 [spl]
Mar 27 13:07:10 labmouse kernel: [ 1106.927644]  ? spl_kmem_cache_alloc+0x64/0x700 [spl]
Mar 27 13:07:10 labmouse kernel: [ 1106.927662]  ? spa_do_crypt_abd+0x4f/0x2f0 [zfs]
Mar 27 13:07:10 labmouse kernel: [ 1106.927673]  zio_push_transform+0x5f1/0x12b0 [zfs]
Mar 27 13:07:10 labmouse kernel: [ 1106.927684]  ? zio_push_transform+0xc56/0x12b0 [zfs]
Mar 27 13:07:10 labmouse kernel: [ 1106.927694]  zio_execute+0x90/0xf0 [zfs]
Mar 27 13:07:10 labmouse kernel: [ 1106.927697]  taskq_dispatch_delay+0x56e/0x8c0 [spl]
Mar 27 13:07:10 labmouse kernel: [ 1106.927701]  ? wake_up_q+0x80/0x80
Mar 27 13:07:10 labmouse kernel: [ 1106.927711]  ? zio_interrupt+0x19e0/0x19e0 [zfs]
Mar 27 13:07:10 labmouse kernel: [ 1106.927715]  kthread+0x121/0x140
Mar 27 13:07:10 labmouse kernel: [ 1106.927719]  ? taskq_dispatch_delay+0x2e0/0x8c0 [spl]
Mar 27 13:07:10 labmouse kernel: [ 1106.927723]  ? kthread_create_worker_on_cpu+0x40/0x40
Mar 27 13:07:10 labmouse kernel: [ 1106.927725]  ? kthread_create_worker_on_cpu+0x40/0x40
Mar 27 13:07:10 labmouse kernel: [ 1106.927727]  ret_from_fork+0x22/0x40

```

not trying to split the pool, just normal operations

**Comment by tcaputi** [comment] 2018-04-01 22:29
@kpande 
Would you mind making a new issue for this, since we closed this as a duplicate of another ticket that has been locked. Please include info about your zfs version and what kind of workload you were running? Also let me know what commands froze (if any).
