### ISSUE TITLE
dp_sync_taskq causes machine to crash

### ISSUE THREAD

**Issue by flaminmoe** [zfsonlinux/zfs#8027] opened 2018-10-16 09:33 UTC
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| RedHat
Distribution Version	| 7.5
Linux Kernel	|  3.10.0-862.14.4.el7.x86_64
Architecture	| x86_64
ZFS Version	| 0.7.11-1
SPL Version	| 0.7.11-1

### Describe the problem you're observing

Machine freezes (or reboots, not sure since in clustered environment, and was fenced after too many missed heartbeats)

### Describe how to reproduce the problem

happened during normal operation (no idea)

### Include any warning/errors/backtraces from the system logs

````
Oct 15 16:05:32 iistore-node2.inf.ethz.ch kernel: BUG: unable to handle kernel NULL pointer dereference at           (null)
Oct 15 16:05:32 iistore-node2.inf.ethz.ch kernel: IP: [<ffffffff8bd6cf2b>] __list_add+0x1b/0xc0
Oct 15 16:05:32 iistore-node2.inf.ethz.ch kernel: PGD 0 
Oct 15 16:05:32 iistore-node2.inf.ethz.ch kernel: Oops: 0000 [#1] SMP 
Oct 15 16:05:32 iistore-node2.inf.ethz.ch kernel: Modules linked in: cts rpcsec_gss_krb5 binfmt_misc nfsv3 nfs fscache 8021q garp mrp stp llc bonding xt_multiport ip6t_REJECT nf_reject_ipv6 nf_conntrack_ipv6 nf_defrag_ipv6 ip6table_filter ip6_tables nf_conntrack_netbios_ns nf_connt
Oct 15 16:05:32 iistore-node2.inf.ethz.ch kernel:  lockd grace auth_rpcgss sunrpc ip_tables xfs libcrc32c sd_mod crc_t10dif crct10dif_generic mgag200 drm_kms_helper syscopyarea sysfillrect sysimgblt fb_sys_fops ttm mpt3sas ahci drm ixgbe crct10dif_pclmul crct10dif_common libahci cr
Oct 15 16:05:32 iistore-node2.inf.ethz.ch kernel: CPU: 14 PID: 81050 Comm: dp_sync_taskq Tainted: P           OE  ------------   3.10.0-862.14.4.el7.x86_64 #1
Oct 15 16:05:32 iistore-node2.inf.ethz.ch kernel: Hardware name: DALCO AG S2600WT2R/S2600WT2R, BIOS SE5C610.86B.01.01.0024.021320181901 02/13/2018
Oct 15 16:05:32 iistore-node2.inf.ethz.ch kernel: task: ffff951821243f40 ti: ffff951822adc000 task.ti: ffff951822adc000
Oct 15 16:05:32 iistore-node2.inf.ethz.ch kernel: RIP: 0010:[<ffffffff8bd6cf2b>]  [<ffffffff8bd6cf2b>] __list_add+0x1b/0xc0
Oct 15 16:05:32 iistore-node2.inf.ethz.ch kernel: RSP: 0018:ffff951822adfbf8  EFLAGS: 00010246
Oct 15 16:05:32 iistore-node2.inf.ethz.ch kernel: RAX: 00000000ffffffff RBX: ffff951822adfc20 RCX: 0000000000000000
Oct 15 16:05:32 iistore-node2.inf.ethz.ch kernel: RDX: ffff95123bc2bb78 RSI: 0000000000000000 RDI: ffff951822adfc20
Oct 15 16:05:32 iistore-node2.inf.ethz.ch kernel: RBP: ffff951822adfc10 R08: 0000000000000000 R09: 0000000000000001
Oct 15 16:05:32 iistore-node2.inf.ethz.ch kernel: R10: 00000000000003e0 R11: 0000000000000000 R12: ffff95123bc2bb78
Oct 15 16:05:32 iistore-node2.inf.ethz.ch kernel: R13: 0000000000000000 R14: 00000000ffffffff R15: ffff95123bc2bb78
Oct 15 16:05:32 iistore-node2.inf.ethz.ch kernel: FS:  0000000000000000(0000) GS:ffff95287de00000(0000) knlGS:0000000000000000
Oct 15 16:05:32 iistore-node2.inf.ethz.ch kernel: CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Oct 15 16:05:32 iistore-node2.inf.ethz.ch kernel: CR2: 0000000000000000 CR3: 0000000d59a0e000 CR4: 00000000003607e0
Oct 15 16:05:32 iistore-node2.inf.ethz.ch kernel: DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
Oct 15 16:05:32 iistore-node2.inf.ethz.ch kernel: DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
Oct 15 16:05:32 iistore-node2.inf.ethz.ch kernel: Call Trace:
Oct 15 16:05:32 iistore-node2.inf.ethz.ch kernel:  [<ffffffff8c117bf6>] __mutex_lock_slowpath+0xa6/0x1d0
Oct 15 16:05:32 iistore-node2.inf.ethz.ch kernel:  [<ffffffff8c116fff>] mutex_lock+0x1f/0x2f
Oct 15 16:05:32 iistore-node2.inf.ethz.ch kernel:  [<ffffffffc0b2bfeb>] userquota_updates_task+0x12b/0x580 [zfs]
Oct 15 16:05:32 iistore-node2.inf.ethz.ch kernel:  [<ffffffffc0b292f0>] ? dmu_objset_userobjspace_upgradable+0x60/0x60 [zfs]
Oct 15 16:05:32 iistore-node2.inf.ethz.ch kernel:  [<ffffffffc0b292f0>] ? dmu_objset_userobjspace_upgradable+0x60/0x60 [zfs]
Oct 15 16:05:32 iistore-node2.inf.ethz.ch kernel:  [<ffffffff8bd6d0ad>] ? list_del+0xd/0x30
Oct 15 16:05:32 iistore-node2.inf.ethz.ch kernel:  [<ffffffffc081ed2c>] taskq_thread+0x2ac/0x4f0 [spl]
Oct 15 16:05:32 iistore-node2.inf.ethz.ch kernel:  [<ffffffff8bad2010>] ? wake_up_state+0x20/0x20
Oct 15 16:05:32 iistore-node2.inf.ethz.ch kernel:  [<ffffffffc081ea80>] ? taskq_thread_spawn+0x60/0x60 [spl]
Oct 15 16:05:32 iistore-node2.inf.ethz.ch kernel:  [<ffffffff8babdf21>] kthread+0xd1/0xe0
Oct 15 16:05:32 iistore-node2.inf.ethz.ch kernel:  [<ffffffff8babde50>] ? insert_kthread_work+0x40/0x40
Oct 15 16:05:32 iistore-node2.inf.ethz.ch kernel:  [<ffffffff8c1255f7>] ret_from_fork_nospec_begin+0x21/0x21
Oct 15 16:05:32 iistore-node2.inf.ethz.ch kernel:  [<ffffffff8babde50>] ? insert_kthread_work+0x40/0x40
Oct 15 16:05:32 iistore-node2.inf.ethz.ch kernel: Code: ff ff ff 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 00 55 48 89 e5 41 55 49 89 f5 41 54 49 89 d4 53 4c 8b 42 08 48 89 fb 49 39 f0 75 2a <4d> 8b 45 00 4d 39 c4 75 68 4c 39 e3 74 3e 4c 39 eb 74 39 49 89 
Oct 15 16:05:32 iistore-node2.inf.ethz.ch kernel: RIP  [<ffffffff8bd6cf2b>] __list_add+0x1b/0xc0
-- Reboot --

````

**Comment by bunder2015** [comment] 2018-10-16 09:44
I believe this is a duplicate of #7997

**Comment by flaminmoe** [comment] 2018-10-16 15:53
I have rebuilt 0.7.11 with PR#8005 and will install it tonight.
Will see what I find (2 more crashes in the meantime)

**Comment by loli10K** [comment] 2019-11-18 06:59
Should be fixed by https://github.com/zfsonlinux/zfs/commit/b32f1279d4a09a932dcbfa79e125ce60cd8d75bf (zfs-0.7.12), closing.

**Closed by loli10K** 2019-11-18 06:59 UTC
