### ISSUE TITLE
Fragmentation increases after zfs send/recv

### ISSUE THREAD

**Issue by zrait** [zfsonlinux/zfs#4491] opened 2016-04-06 00:18 UTC
I am in the process of running zfs send | zfs recv to backup a dataset onto a freshly created pool and am a bit confused about why my new pool (which is made up of freshly formatted disks) has a significantly higher fragmentation % than the original pool. Is this behavior expected?

The output of zpool list -v is as follows:

```
backup    29T  19.6T  9.37T         -    39%    67%  1.00x  ONLINE  -
  raidz1    29T  19.6T  9.37T         -    39%    67%
    pci-0000:03:00.0-scsi-0:0:6:0      -      -      -         -      -      -
    pci-0000:03:00.0-scsi-0:0:6:1      -      -      -         -      -      -
    pci-0000:03:00.0-scsi-0:0:6:2      -      -      -         -      -      -
    pci-0000:03:00.0-scsi-0:0:6:3      -      -      -         -      -      -
tank    65T  30.3T  34.7T         -     9%    46%  1.00x  ONLINE  -
  raidz2  32.5T  29.5T  3.02T         -    19%    90%
    pci-0000:03:00.0-scsi-0:0:4:4      -      -      -         -      -      -
    pci-0000:03:00.0-scsi-0:0:4:5      -      -      -         -      -      -
    pci-0000:03:00.0-scsi-0:0:4:6      -      -      -         -      -      -
    pci-0000:03:00.0-scsi-0:0:4:7      -      -      -         -      -      -
    pci-0000:03:00.0-scsi-0:0:5:0      -      -      -         -      -      -
    pci-0000:03:00.0-scsi-0:0:5:1      -      -      -         -      -      -
  raidz2  32.5T   801G  31.7T         -     0%     2%
    pci-0000:03:00.0-scsi-0:0:5:2      -      -      -         -      -      -
    pci-0000:03:00.0-scsi-0:0:5:3      -      -      -         -      -      -
    pci-0000:03:00.0-scsi-0:0:5:4      -      -      -         -      -      -
    pci-0000:03:00.0-scsi-0:0:5:5      -      -      -         -      -      -
    pci-0000:03:00.0-scsi-0:0:5:6      -      -      -         -      -      -
    pci-0000:03:00.0-scsi-0:0:5:7      -      -      -         -      -      -
```

(The second vdev in the pool was added recently but I was bitten by a separate issue, which is that I expected ashift to be a per-pool setting rather than per vdev and didn't realize I'd need to re-specify it when adding the second vdev)

**Comment by pcd1193182** [comment] 2016-04-06 01:26
Your backup pool is significantly smaller than your primary pool, and as I understand it, fragmentation tends to go up significantly as pool full % goes up.  What I'm confused by is that the fragmentation on your first raidz2 vdev is so low; 90% capacity and 19% fragmentation?  That seems *very* low, from my experience.

**Comment by kenthinson** [comment] 2016-05-23 19:17
Maybe you are think frag is related to your data? It's a free space measurement.
https://utcc.utoronto.ca/~cks/space/blog/solaris/ZFSZpoolFragmentationMeaning

**Comment by behlendorf** [comment] 2016-11-08 20:41
Closing.  Working as intended.

**Closed by behlendorf** 2016-11-08 20:41 UTC
