### ISSUE TITLE
0.6.5 iSCSI target very slow and unresponsive

### ISSUE THREAD

**Issue by alexanderhaensch** [zfsonlinux/zfs#3793] opened 2015-09-17 15:37 UTC
The iSCSI target used by VMware esxi seems to work but the performance is so slow that the virtual machines running become unresponsive and boot very slowly.
dmesg is full of errors like this:
[11334.299177] TARGET_CORE[iSCSI]: Detected NON_EXISTENT_LUN Access for 0x0000004c
[11334.299466] TARGET_CORE[iSCSI]: Detected NON_EXISTENT_LUN Access for 0x0000004d
[11334.299769] TARGET_CORE[iSCSI]: Detected NON_EXISTENT_LUN Access for 0x0000004e
[11334.299967] TARGET_CORE[iSCSI]: Detected NON_EXISTENT_LUN Access for 0x0000004f
[11334.300269] TARGET_CORE[iSCSI]: Detected NON_EXISTENT_LUN Access for 0x00000050
[11334.301068] TARGET_CORE[iSCSI]: Detected NON_EXISTENT_LUN Access for 0x00000051
[11334.301734] TARGET_CORE[iSCSI]: Detected NON_EXISTENT_LUN Access for 0x00000052
[11334.301898] TARGET_CORE[iSCSI]: Detected NON_EXISTENT_LUN Access for 0x00000053
[11334.302409] TARGET_CORE[iSCSI]: Detected NON_EXISTENT_LUN Access for 0x00000054
[11347.641513] TARGET_CORE[iSCSI]: Detected NON_EXISTENT_LUN Access for 0x00000055
[11347.642172] ABORT_TASK: Found referenced iSCSI task_tag: 731579
[11347.642176] ABORT_TASK: Sending TMR_FUNCTION_COMPLETE for ref_tag: 731579
[11347.642179] ABORT_TASK: Found referenced iSCSI task_tag: 731577
[11347.642179] ABORT_TASK: ref_tag: 731577 already complete, skipping
[11347.642180] ABORT_TASK: Sending TMR_TASK_DOES_NOT_EXIST for ref_tag: 731577
[11361.245366] TARGET_CORE[iSCSI]: Detected NON_EXISTENT_LUN Access for 0x0000005e
[11361.245701] Unexpected ret: -32 send data 48

reverted to 0.6.4.2 to resolve the issue.

**uname -a**
Linux io 3.14.51-hardened #1 SMP Thu Sep 17 12:21:09 CEST 2015 x86_64 Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz GenuineIntel GNU/Linux

**Comment by kpande** [comment] 2015-09-21 22:12
I discovered this while doing some stuff with Tripleback as a host for ESX as well. In my experience the issue is related to LIO. Using IET does not result in these errors. The SVN version of IET has SCSI-3 PRs which help with ESX clustering.

**Comment by ryao** [comment] 2015-09-21 22:15
The attempt to access non-existent LUNs is something VMWare's initiator is doing. I do not understand the iSCSI protocol well enough to know offhand what communication between the two is supposed to look like, but my guess is that the zvol changes made us respond so quickly that we are triggering a race somewhere.

**Comment by kpande** [comment] 2015-09-21 22:18
From http://www.spinics.net/lists/target-devel/msg07187.html:
```
This is simply ESX re-scanning the target side LUN layout on an
individual iSCSI target instance, and aside from the extra warnings
you've noticed above there is nothing to be concerned about on the
target side.

It is kind of unusual that ESX is (automatically) doing this every 30-60
minutes, as it's usually manually initiated by admin with vicfg-rescan.

Looking around a bit more, there is a kb entry for explicitly disabling
the automatic rescanning logic in vCenter:

http://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=1016873

Apparently the 'rescan storms' do cause problems on some targets, but
we've not had any issues thus far reported related to the automatic
rescanning.  That said, disabling it and using vicfg-rescan manually
when the LUN layout changes what can be done to avoid the extra noise.

--nab
```

Maybe you can disable that and see if it helps?

**Comment by kpande** [comment] 2015-09-21 22:21
FWIW I'm able to reproduce a crash with LIO (tasks hung) by placing the iSCSI filesystem under extreme load.

**Comment by alexanderhaensch** [comment] 2015-09-22 04:46
From my understanding, the vmfs cluster filesystem is aggressivly fsynced in order to have data consistent on disk. 
The performance regression for fsync slows things down and maybe the iscsi stack responses strange here. Maybe there are some timeouts triggered in the iscsi stack.

**Comment by behlendorf** [comment] 2015-09-23 16:21
@alexanderhaensch many clustered filesystems behave this way which is why their performance can leave a lot to be desired.  Adding a ZIL device, even a middle-of-the-road SSD, should help considerably.  Until we get to the root cause you may want to leave your systems at 0.6.4.2 if they don't exhibit the issue.   

The fsync(2) issue referenced is #3780.

**Comment by alexanderhaensch** [comment] 2015-09-23 16:36
Thanks @behlendorf for your response, the system in question has a mirrored ZIL. The system should handle the load even without the ZIL. I guess the issue is not related to the real speed of the storage devices.
Downgraded the system to 0.6.4.2 for the moment.

**Comment by alexanderhaensch** [comment] 2015-09-25 20:30
this is closed by 5592404

**Comment by kernelOfTruth** [comment] 2015-09-25 20:33
@alexanderhaensch still open ;)

there should be:

```
comment and close
```

**Comment by behlendorf** [comment] 2015-09-25 20:34
@alexanderhaensch right, thanks.  Closing.

**Closed by behlendorf** 2015-09-25 20:34 UTC
Labels: Performance
