### ISSUE TITLE
Feature Request: "destroyable" flag

### ISSUE THREAD

**Issue by yurelle** [zfsonlinux/zfs#7357] opened 2018-03-28 05:11 UTC
Perhaps it's just me, but I'm a bit paranoid about blasting my pools & datasets, mostly due to my ADHD & fat-fingers; and especially since the `destroy` command doesn't do the normal "_Are you sure_" thing that `rm` does. I know the "proper" response is just to have redundant backups, but I currently have an 80 TB pool (not full), and haven't saved up the cash yet to duplicate it. I'm new to ZFS, so it's entirely possible that this already exists, but I looked, and couldn't find anything.

It would be great if you could add a settable flag to pools, datasets, & snapshots, that was something like "destroyable" or maybe "locked"/"protected" or something, that can be set to true/false or yes/no. If the object is marked as destroyable, it behaves as normal: a call to `zfs destroy myThing` destroys it, no questions asked. However, if you manually set the flag to protect the object, it behaves differently. It is still writable/modifiable if the `readOnly` flag is off, but any call to `zfs destroy myThing` will abort and error out; something like "_Cannot destroy 'myThing'. Pool/Dataset/Snapshot is locked/protected/not destroyable._".

At least, I think it would be great. Maybe others don't agree,
-Yurelle

**Comment by loli10K** [comment] 2018-03-28 05:24
Duplicate of #4134

**Closed** 2018-03-28 07:35 UTC
