### ISSUE TITLE
ZFS on root boot broken on arch

### ISSUE THREAD

**Issue by jfburdet** [zfsonlinux/zfs#4749] opened 2016-06-11 11:07 UTC
Hi,

I have an Arch Linux NAS server, using ZFS on root

Yesterday, I rebooted my server and got stuck on boot with : "libgcc_s.so.1 must be installed for pthread_cancel to work"

The workaround I found was to boot using emergency usb key and put : 

FILES="/usr/lib/libgcc_s.so.1"

into /etc/mkinitcpio.conf

then running mkinicpio -p linux

Hope this makes sense.

**Comment by WoefulDerelict** [comment] 2016-06-14 23:26
This was a bit vague; however, as I've managed to produce a rather similar case to the user's issue I'll expound on my own experience.

After synchronising my Arch Linux system with the latest changes in the ZoL repo I rebooted the system. The system booted into a failover console as it was under the impression the pools were from another system and had not been exported. As I knew this wasn't true I set about correcting the issue by importing the pools manually with the appropriate flags. Instead of playing nice as one had expected zpool spat out the error jfburdet mentions: libgcc_s.so.1 must be installed for pthread_cancel to work.

One encounters this error as the file is not part of the initrd by default and it appears that it's dynamically linked against in builds of the current source on synchronised Arch systems. I was able to use a rescue disk to cleanly export the pools and the system booted properly. I suspect it would be wise to follow jfburdet's practice and place the offending library into my initial ramdisk to prevent the need to use a rescue disk in the future. 

I did find that the DKMS PKGBUILD I used from the AUR left me with all the zfs services disabled by default and not as described in the presets mentioned here: https://github.com/zfsonlinux/zfs/commit/92547bc45ca9a2114662d9343ae53e5098acb627 

After manually enabling the services the rest of my pools mounted normally at boot and all was well.

**Comment by kpande** [comment] 2016-06-15 01:54
this seems to be a distribution packaging issue, correct?

**Comment by WoefulDerelict** [comment] 2016-06-15 08:14
kpande: Hard to box this one in. I'd have to look into why there is a new dynamically linked dependency for the zpool utility.

It certainly breaks down to one that would need to be solved at the distribution/packaging level. Avoiding dynamically linked binaries would certainly prevent it from happening.

**Comment by jfburdet** [comment] 2016-06-15 08:27
Some more info to help solve this problem.

When I dig around on my server, i found that some shell code seems to exist to include libgcc_s.so.1 into the ramdisk in /usr/share/initramfs-tools/hooks/zfs

```
# ZDB uses pthreads for some functions, but the library dependency is not
# automatically detected. The `find` utility and extended `cp` options are
# used here because libgcc_s.so could be in a subdirectory of /lib for
# multi-arch installations.
cp --target-directory="$DESTDIR" --parents $(find /lib -type f -name libgcc_s.so.1)
```

Since libgcc_s.so.1 is under /usr/lib, I tried to change the line above, but this shell script file doesn't seems to be executed when running mkinitcpio -p linux, that's why I tried to change /etc/mkinitcpio.conf

One can test the result by doing 
```
~# lsinitcpio /boot/initramfs-linux.img | grep gcc
usr/lib/libgcc_s.so.1
```

**Comment by lnicola** [comment] 2016-06-16 06:25
ZFS root is working fine for me, although I can confirm that `libgcc_s.so.1` is not present in my initramfs image.

**Comment by grmblfrz** [comment] 2016-08-16 08:58
FTR, I had the same issue with  zfs-linux-git 0.6.5_r403_ge35c5a8_4.7.0_1-1.

**Comment by drescherjm** [comment] 2016-08-16 13:10
I am having this issue on gentoo using genkernel-next. ldd does not detect libgcc_s.so.1 as a dependency of zpool so it is not added to the initramfs.

**Comment by behlendorf** [comment] 2016-08-16 23:18
The patches which added support for resumable send/recv added the dependency on `pthread_cancel()`.  Removing that dependency is doable but not really desirable, it would be best if this dependency could be handled in the packaging.

**Comment by ryao** [comment] 2016-08-17 15:19
@behlendorf The dependency is from either sysdeps/gnu/unwind-resume.c or sysdeps/nptl/unwind-forcedunwind.c in glibc. In short, it wants _Unwind_Resume, which the LSB puts into libgcc_s:

http://refspecs.linuxbase.org/LSB_4.1.0/LSB-Core-generic/LSB-Core-generic/libgcc-s.html

**Comment by WoefulDerelict** [comment] 2016-08-17 15:22
On Arch Linux it ought to be decently easy to create an install and remove hook that would check for and add the data necessary to include the library in the initrd and regenerate it using mkinitcpio. Solving this at a packaging level should indeed be trivial.

**Comment by ryao** [comment] 2016-08-17 15:27
@WoefulDerelict It can be worked around in the initramfs generator, although an idea that would allow existing initramfs generators to work would be to add the required symbol into zpool and zdb. There is a MIT licensed version of this here:

https://github.com/pathscale/libunwind/blob/vanilla_pathscale/src/unwind/Resume.c
https://github.com/pathscale/libunwind/blob/vanilla_pathscale/src/unwind/unwind-internal.h

Anyway, I am evaluating a patch to gentoo's genkernel that works around this.

**Comment by WoefulDerelict** [comment] 2016-08-17 15:31
@ryao That might be very useful as well. As the issue only affects systems with a ZFS pool configured as / the Arch crowd may adhere rather closely to their KISS philosophy and document the case and fixes in the wiki, expecting users to either edit mkinitcpio.conf themselves or implement other solutions at their own risk.

**Comment by ryao** [comment] 2016-08-17 15:40
@WoefulDerelict A fix is in genkernel master:

https://gitweb.gentoo.org/proj/genkernel.git/commit/?id=6b5eb0fe52a49b1aa050f4b9f2e46b03f5c2940c

**Comment by Calrama** [comment] 2016-09-01 16:54
https://github.com/zfsonlinux/zfs/pull/5058 among others adapts @ryao's fix for dracut.

**Closed** 2016-09-09 17:18 UTC
Labels: Packaging
