### ISSUE TITLE
zpool history only shows history from zpool commands, not from zfs commands

### ISSUE THREAD

**Issue by janlam7** [zfsonlinux/zfs#4294] opened 2016-01-31 12:49 UTC
Recently I reinstalled my system with gentoo-zfs-0.6.5.3-r3 and just upgraded to gentoo-zfs-0.6.5.4-r2
I saved a zpool history export before destroying the previous pool. I was just comparing zpool history of my old and new pool to see what I've missed, when I noticed zpool history is currently only showing history of zpool commands, and not of zfs commands.

This is probably gentoo specific, so I'll tag @ryao here

**Comment by drescherjm** [comment] 2016-01-31 14:31
On gentoo I am not seeing that with the zfs-9999 build so its most likely something in the new api.

**Comment by ilovezfs** [comment] 2016-01-31 14:41
@drescherjm Yes, and I can confirm I *do* see the issue running
```
openzfs ~ # echo /var/db/pkg/sys-fs/zfs-0*
/var/db/pkg/sys-fs/zfs-0.6.5.4-r2
openzfs ~ # cat /sys/module/zfs/version 
0.6.5.4-r1-gentoo
```
which uses the new API.

**Comment by ryao** [comment] 2016-01-31 20:04
What is happening is that the kernel is returning EPERM because `ZFS_IOC_LIBZFS_CORE` is set to disable logging so that it does not get enabled globally and the logging functionality is not currently a part of the stable API. `zfs_ioc_stable()` should have enabled it, but the TSD mechanism used here is semi-broken on Linux (no strict guarantee of cleanup), so it was omitted. It looks like we might be able to use the `zfs_onexit_*` logic to implement the permissions for logging in a way that works on Linux, although I am going to think about this some more.

**Comment by ryao** [comment] 2016-02-02 00:28
It occurred to me that the `zfs_onexit_*` mechanism would suffer a race condition with two processes sharing the same fd due to a `fork()` in their past try to talk to `/dev/zfs` simultaneously. Specifically, one's log messages could be clobbered. Instead of pushing forward with the `zfs_onexit_*` mechanism, I have decided to extend the stable API functions to support logging via the `opts` nvlist.

I have an early patch working locally, but it needs a bit more work before it is right. I will push the final version of it to #3907 and queue it for the next ebuild revision when it is done.

**Comment by ilovezfs** [comment] 2016-02-02 02:15
@ryao @ahrens @behlendorf I'm wondering if such a change is going to interfere with or undermine the chance of the stable API getting upstreamed. Although the onexit mechanism feels hacky to a certain extent, given that history is not the only thing in zfs that uses it, I'm wondering if switching to some other mechanism that is part of the new API specifically for history but not for the other uses of cleanup fds and onexit solves anything. If it is going to be changed, wouldn't it make more sense to switch over all of the uses of cleanup fds and onexit to use the stable API's new mechanism? Does the new mechanism have any way of handling a cleanup callback or is it incompatible with that altogether?

**Comment by ryao** [comment] 2016-02-02 17:53
@ilovezfs The semantics of passing a string to the kernel with a library call are not general enough to handle callbacks in general.

That said, there are 3 approaches to logging the CLI commands that have been discussed:

1) TSD, which is the current approach and is generically known as thread local storage. Linux mainline rejected thread local storage for kernel threads. TSD was implemented in ZoL by adding call points that enable clean up when exiting to userland, but those cannot be used in the ioctl interface where state is expected across multiple ioctls. Consequently, userland can cause something like a memory leak on Linux where state is left inside the kernel for the next thread with that pid_t. It is bounded by the limit on system pid_t values, but it is an ugly behavior.
2) onexit, which is your suggestion. Its semantics would be portable, but applications sharing a common fork doing things on different pools could log things to the wrong pool and/or not at all.
3) Including the history string with an API call via the new API's `opts` variable. This allows us to avoid the races of the other two while eliminating an ioctl call.

I think that the third option is precisely what we want when doing history logging. In case of a command that causes multiple operations such as `zfs destroy -r`, we can just log the command invocation with the first library call that succeeds and leave it out of subsequent library calls. If none succeed, then nothing is logged, which is almost the current behavior. The only difference is that the position of the `zpool history` entry with respect to the entries in `zpool history -i` would be altered, but that is okay. Things would differ when the userland process is killed before it finishes, such that we would would show entries in `zpool history` and `zpool history -i` while the TSD approach would only show entries in `zpool history -i`.

The only time we would need to log at the end as the TSD approach does would be if we roll back on failure. In that case, neither case would log the command and the behavior would be the same.

**Comment by ptx0** [comment] 2016-04-01 18:57
:+1:

**Comment by behlendorf** [comment] 2016-11-08 01:20
Closing.  This is Gentoo specific at the moment and caused by the proposed stable API changes.

**Closed by behlendorf** 2016-11-08 01:20 UTC
