### ISSUE TITLE
panic[cpu0]/thread=fffffe001e02fc20: assertion failed: msp->ms_max_size == 0 (0x1000000 == 0x0), file: ../../common/fs/zfs/metaslab.c, line: 2526

### ISSUE THREAD

**Issue by ikozhukhov** [zfsonlinux/zfs#9121] opened 2019-08-03 02:58 UTC
it is panic with commit https://github.com/zfsonlinux/zfs/commit/7f31908913592b3075306daf403f2a334602493e

### System information

Type | Version/Name
 --- | --- 
Distribution Name	| DilOS
Distribution Version	| 
Linux Kernel	| 
Architecture	| 
ZFS Version	| 
SPL Version	| 

### Describe how to reproduce the problem
second run of ZTS in loop on 2 different environments
```
01:15:25.435 Test: /opt/zfs-tests/tests/functional/cli_root/zpool_create/setup.ksh (run as root) [00:08] [PASS]
01:15:38.846 Test: /opt/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_001_pos.ksh (run as root) [00:13] [PASS]
01:16:07.099 Test: /opt/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_002_pos.ksh (run as root) [00:28] [PASS]
01:16:11.719 Test: /opt/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_003_pos.ksh (run as root) [00:04] [PASS]
01:16:15.846 Test: /opt/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_004_pos.ksh (run as root) [00:04] [PASS]
01:16:25.958 Test: /opt/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_005_pos.ksh (run as root) [00:10] [PASS]
01:16:46.416 Test: /opt/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_006_pos.ksh (run as root) [00:20] [PASS]
01:16:50.052 Test: /opt/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_007_neg.ksh (run as root) [00:03] [PASS]
01:19:24.843 Test: /opt/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_008_pos.ksh (run as root) [02:34] [PASS]
01:20:10.601 Test: /opt/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_009_neg.ksh (run as root) [00:45] [PASS]
01:20:15.145 Test: /opt/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_010_neg.ksh (run as root) [00:04] [PASS]
01:20:38.782 Test: /opt/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_011_neg.ksh (run as root) [00:23] [PASS]
01:20:38.940 Test: /opt/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_012_neg.ksh (run as root) [00:00] [PASS]
01:20:39.159 Test: /opt/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_014_neg.ksh (run as root) [00:00] [PASS]
01:20:40.763 Test: /opt/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_015_neg.ksh (run as root) [00:01] [PASS]
01:20:44.310 Test: /opt/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_016_pos.ksh (run as root) [00:03] [PASS]
01:20:44.820 Test: /opt/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_017_neg.ksh (run as root) [00:00] [PASS]
01:20:48.353 Test: /opt/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_018_pos.ksh (run as root) [00:03] [PASS]
01:20:48.662 Test: /opt/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_019_pos.ksh (run as root) [00:00] [PASS]
01:20:49.407 Test: /opt/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_020_pos.ksh (run as root) [00:00] [PASS]
01:21:00.295 Test: /opt/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_021_pos.ksh (run as root) [00:10] [PASS]
01:21:01.763 Test: /opt/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_022_pos.ksh (run as root) [00:01] [PASS]
01:21:14.207 Test: /opt/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_023_neg.ksh (run as root) [00:12] [PASS]
```
### Include any warning/errors/backtraces from the system logs
```
panic[cpu0]/thread=fffffe001e02fc20: assertion failed: msp->ms_max_size == 0 (0x1000000 == 0x0), file: ../../common/fs/zfs/metaslab.c, line: 2526

fffffe001e02f570 genunix:process_type+194d99 ()
fffffe001e02f5a0 zfs:metaslab_should_allocate+ca ()
fffffe001e02f660 zfs:find_valid_metaslab+63 ()
fffffe001e02f750 zfs:metaslab_group_alloc_normal+332 ()
fffffe001e02f7f0 zfs:metaslab_group_alloc+64 ()
fffffe001e02f8b0 zfs:metaslab_alloc_dva+2a7 ()
fffffe001e02f970 zfs:metaslab_alloc+198 ()
fffffe001e02fa10 zfs:zio_dva_allocate+182 ()
fffffe001e02fa50 zfs:zio_execute+d8 ()
fffffe001e02fb00 genunix:taskq_thread+2ee ()
fffffe001e02fb10 unix:thread_start+8 ()


panic: entering debugger (continue to save dump)
```

**Comment by ahrens** [comment] 2019-08-03 03:14
cc @sdimitro @pcd1193182

**Comment by ikozhukhov** [comment] 2019-08-03 19:42
cc @behlendorf

**Comment by sdimitro** [comment] 2019-08-03 21:35
@ikozhukhov can you also point us to a branch with the all the zfs code running on that machine?
I want to make sure that we rule out the scenario where there has been a mismerge of previous commits.

**Comment by ikozhukhov** [comment] 2019-08-03 22:01
@sdimitro https://bitbucket.org/dilos/dilos-illumos/branch/int-zol-0802?dest=int
you can find reverted commit 6448d62 where was introduced panic
branch int-zol-0802 will be available in one week, please let me know if you need it available more time.

**Comment by sdimitro** [comment] 2019-08-06 00:03
The relevant place where the panic happened is the one below:
```
 boolean_t
 metaslab_should_allocate(metaslab_t *msp, uint64_t asize)
 {
	if (msp->ms_loaded) {
 		return (msp->ms_max_size >= asize);
	} else {
		ASSERT0(msp->ms_max_size);  // <---- panic happened here
	}
... <cropped> ...
```
The reason for the panic was that `ms_max_size` was not zero. This assertion exists as a sanity-check and the above logic checks the following invariant: "A metaslab that is not loaded, has an empty `ms_allocatable` tree and thus its `ms_max_size` is 0". 

I asked Igor for a crash dump and I think I was able to root-cause the issue. Firing up mdb I found the following:
```
> $C
fffffe002e6834e0 vpanic()
fffffe002e683570 0xfffffffffbe3d421()
fffffe002e6835a0 metaslab_should_allocate+0xca(fffffee5965b4800, 200)
fffffe002e683660 find_valid_metaslab+0x63(fffffe11bdc94e80, 8000000000000000, fffffe4317f7b3c0, 0, 1, 200, fffffe0000000001, fffffe279363fcf0, fffffee5967af800, fffffe002e6836ec)
fffffe002e683750 metaslab_group_alloc_normal+0x332(fffffe11bdc94e80, fffffe279363fcf0, 200, 4, 1, fffffe4317f7b3c0, fffffe2900000000, fffffe4000000001)
fffffe002e6837f0 metaslab_group_alloc+0x64(fffffe11bdc94e80, fffffe279363fcf0, 200, 4, 1, fffffe4317f7b3c0, fffffe0000000000, ffffffff00000001)
fffffe002e6838b0 metaslab_alloc_dva+0x2a7(fffffee596512000, fffffe942c72a080, 200, fffffe4317f7b3c0, 0, 0, 4, fffffee500000008, fffffe279363fcf0, fffffe0000000001)
fffffe002e683970 metaslab_alloc+0x198(fffffee596512000, fffffe942c72a080, 200, fffffe4317f7b3c0, 2, 4, 0, 8, fffffe279363fcf0, fffffe279363fa00, 1)
fffffe002e683a10 zio_dva_allocate+0x182(fffffe279363fa00)
fffffe002e683a50 zio_execute+0xd8(fffffe279363fa00)
fffffe002e683b00 taskq_thread+0x2ee(fffffe43348238a8)
fffffe002e683b10 thread_start+8()

> fffffee5965b4800::print metaslab_t ms_loaded
ms_loaded = 0x1 (B_TRUE)
```

It looks like the metaslab was loaded right under us, and there exist a race condition. Looking for any loading happening at the same time, I found the thread that just loaded our metaslab:
```
> ::stacks -c metaslab_load
THREAD           STATE    SOBJ                COUNT
fffffe002e671c20 ONPROC   <NONE>                  1
                 apix_hilevel_intr_prolog+0xa3
                 apix_do_interrupt+0x5c1
                 _interrupt+0x1e9
                 mutex_delay_default+0xc
                 mutex_vector_enter+0xc8
                 metaslab_group_sort+0x61
                 metaslab_recalculate_weight_and_sort+0x66
                 metaslab_load_impl+0x195
                 metaslab_load+0x7b
                 metaslab_activate+0xa0
                 metaslab_group_alloc_normal+0x42c
                 metaslab_group_alloc+0x64
                 metaslab_alloc_dva+0x2a7
                 metaslab_alloc+0x198
                 zio_dva_allocate+0x182
                 zio_execute+0xd8
                 taskq_thread+0x2ee
                 thread_start+8
```

What's ironic is that this thread was waiting to grab the `mg_lock` that the panicked thread was holding before it blew up. 

My theory of this panic is the following:
[1] Thread A was in `metaslab_group_alloc()` and had picked metaslab M to make its allocation, that was unloaded so it started loading it (`metaslab_load()`).
[2] Thread B went to `metaslab_should_allocate()` without holding the `ms_lock` from `find_valid_metaslab()`/`metaslab_group_alloc()`. Saw that `ms_loaded` was not set and decided to go into the `else` clause of the aforementioned code-snippet.
[3] Thread A passed the point where `metaslab_load{_impl}()` sets `ms_loaded` to `B_TRUE` and went on and set `ms_max_size`.
[4] Thread B tried to assert that `ms_max_size` was 0 and blew up.

I'll sync up with @pcd1193182 and @ahrens tomorrow to validate my theory and try to come up with a proper fix for this.

**Comment by pcd1193182** [comment] 2019-08-06 03:14
This fixed tangentially in https://github.com/zfsonlinux/zfs/commit/c81f1790e28a547769ce9d8e2d25391cf4317cc0 since it removed the assertion in question.

**Comment by ikozhukhov** [comment] 2019-08-06 15:05
i have merged to changes to https://bitbucket.org/dilos/dilos-illumos/commits/branch/int-zol-9055
and have started tests in loop.
result will be tomorrow (5h per iteration, we need about 3 iterations and more)

**Comment by behlendorf** [comment] 2019-08-21 16:20
Confirmed fixed, closing.

**Closed by behlendorf** 2019-08-21 16:20 UTC
