### ISSUE TITLE
Error by GPL-only symbol

### ISSUE THREAD

**Issue by sergiall** [zfsonlinux/zfs#4098] opened 2015-12-14 00:10 UTC
Then building ZoL as builtin mainline kernel I get this issue
Building modules, stage 2.
  MODPOST 4013 modules
FATAL: modpost: GPL-incompatible module zfs.ko uses GPL-only symbol 'event_triggers_call'
scripts/Makefile.modpost:90: recipe for target '__modpost' failed
make[2]: *** [__modpost] Error 1
Makefile:1095: Error for make recipe for target «modules»
make[1]: *** [modules] Error 2
make[1]: exit  from the catalog «/media/BUILD/zen++»
debian/ruleset/targets/common.mk:295: error for make recipe for target «debian/stamp/build/kernel»
make: *** [debian/stamp/build/kernel] Error 2

As workaround I make by self  easy script,what remove parts of promts "EXPORT_SYMBOL_GPL" "_GPL" out of the way,and then recompile my kernel build without error.
prep_kern_4_zfs_spl_compile.sh
#!/bin/sh
find kernel/ -type f -name "*.c" | while read i; do
    sed -i 's/EXPORT_SYMBOL_GPL/EXPORT_SYMBOL/g' "$i"
done    
sed -i 's/EXPORT_SYMBOL_GPL/EXPORT_SYMBOL/g' block/*.c
If this may help someone I will be glad
With my reggards.

**Comment by DeHackEd** [comment] 2015-12-14 22:02
What distro and kernel are you running? Something's changed if that symbol isn't available without GPL

**Comment by behlendorf** [comment] 2015-12-15 00:19
I suspect this was accidentally caused by b22e2797970b44e6b9d1e4624a5ede935c851010 and ZFS it being built with support with tracepoints.   @sergiall is HAVE_DECLARE_EVENT_CLASS defined in your `zfs_config.h`?

**Comment by sergiall** [comment] 2015-12-15 03:31
@behlendorf  Yes I have 
/* DECLARE_EVENT_CLASS() is available */
#define HAVE_DECLARE_EVENT_CLASS 1
in my zfs_config.h
I try to build zen-kernel 4.3/master branch on Ubuntu 16.04 (development branch) and Debian stratch/sid,GCC 5.2.3,but this is deja vu from prevous releases ZoL and this issue you may see in users discussions on different forums of internetland...Early from Arch & Gentoo users,now and on Debian derivatives.

**Comment by behlendorf** [comment] 2015-12-16 01:01
@sergiall with an unmodified upstream kernel this test should be failing because `trace_event_raw_init` is also a GPL-only symbol.  Admittedly this will result in tracepoints being disabled but it should build.  If your using unmodified source can you post the DECLARE_EVENT_CLASS test results from the ZFS config.log and check how `trace_event_raw_init` is exported.

**Comment by sergiall** [comment] 2015-12-16 10:02
I don't know how repossition the spoiler here,then else attach this files from zfs & spl
[zfs.config.log.txt](https://github.com/zfsonlinux/zfs/files/63822/zfs.config.log.txt)
[spl.config.log.txt](https://github.com/zfsonlinux/zfs/files/63834/spl.config.log.txt)

**Comment by behlendorf** [comment] 2015-12-16 17:17
@sergiall thanks for the logs, that's what I needed.  Can to try reverting commit b22e2797970b44e6b9d1e4624a5ede935c851010 to verify it fixes the issue.  If it does we'll want to add an autoconf check for this.

**Comment by sergiall** [comment] 2015-12-16 19:03
Great Thank you! I will do this necessarily,but it take a some times (till 2days),becouse I must go in little travel...I'm necessarily write about results here.Thank you again!

**Comment by sergiall** [comment] 2015-12-18 09:31
I've comeback.@behlendorf I try make revert the trace_dbgmsg.h and now it look like this:
[trace_dbgmsg.h.txt](https://github.com/zfsonlinux/zfs/files/66388/trace_dbgmsg.h.txt)
Then I probe to build the new stable linux-4.3.3 kernel,but again give the such error:
  
  Building modules, stage 2.
  MODPOST 3995 modules
FATAL: modpost: GPL-incompatible module zfs.ko uses GPL-only symbol 'event_triggers_call'
scripts/Makefile.modpost:90: recipe for target '__modpost' failed
make[2]: *** [__modpost] Error 1

So,reverting commit b22e279 is not insufficiently to solve this issue
Can it be that part of the code in file trace_dbgmsg.h :
...
DECLARE_EVENT_CLASS(zfs_set_error_class, ...
is the source of problem?Although I think about file sdt.h...That's just how exclude wrong part of code?...

**Comment by behlendorf** [comment] 2016-10-21 04:33
Closing.  Unable to reproduce.

**Closed by behlendorf** 2016-10-21 04:33 UTC

**Comment by xvzf** [comment] 2017-08-20 20:27
Hi there,

Happend again here. Running on ArchLinux (latest roll out as of 20.08.2017), I can send you the PKGBUILD if you want @behlendorf! I was able to reproduce it on 3 independent installations.

Linux:      4.12.8
GCC:        gcc (GCC) 7.1.1 20170630
SPL/ZFS:  0.7.1
