### ISSUE TITLE
zfs 0.6.4-36_g98b2541, snapshot destroy working, but a dump happened

### ISSUE THREAD

**Issue by turrini** [zfsonlinux/zfs#3590] opened 2015-07-12 18:18 UTC
Hello, I'm running ZFS 0.6.4-36_g98b2541 / SPL 0.6.4-4_g62e2eb2 under kernel  3.18.12 (vanilla).

Today while destroying a snapshot, this ocurred:

```
[1295287.752802] BUG: Bad page state in process z_wr_iss/20  pfn:22871f5
[1295287.752836] page:ffffea0078d8ed98 count:0 mapcount:-1 mapping:          (null) index:0x0
[1295287.752866] flags: 0x600000000008000(tail)
[1295287.752886] page dumped because: nonzero mapcount
[1295287.752905] Modules linked in: arc4 ecb md4 hmac nls_utf8 cifs dns_resolver fuse nfnetlink_log nfnetlink loop dm_round_robin ib_iser rdma_cm iw_cm ib_cm ib_sa ib_mad ib_core ib_addr iscsi_tcp libiscsi_tcp libiscsi scsi_transport_iscsi nfsd auth_rpcgss oid_registry nfs_acl nfs lockd grace fscache sunrpc ext4 crc16 mbcache jbd2 dm_crypt bonding dm_multipath scsi_dh joydev hid_generic usbhid hid x86_pkg_temp_thermal dm_mod intel_powerclamp coretemp mgag200 kvm_intel kvm ttm evdev drm_kms_helper drm crct10dif_pclmul crc32_pclmul iTCO_wdt iTCO_vendor_support i2c_algo_bit ghash_clmulni_intel dcdbas i2c_core aesni_intel mei_me aes_x86_64 snd_pcm lrw gf128mul ehci_pci glue_helper tpm_tis snd_timer mei ehci_hcd ablk_helper snd usbcore cryptd soundcore sb_edac shpchp edac_core lpc_ich pcspkr ipmi_si tpm ipmi_msghandler mfd_core acpi_power_meter usb_common wmi acpi_pad button processor thermal_sys zfs(PO) zunicode(PO) zcommon(PO) znvpair(PO) spl(O) zavl(PO) raid1 md_mod sg sd_mod crc32c_intel ahci libahci libata megaraid_sas ixgbe dca ptp pps_core scsi_mod mdio
[1295287.752974] CPU: 2 PID: 6202 Comm: z_wr_iss/20 Tainted: P    B      O   3.18.12-0 #1
[1295287.752976] Hardware name: Dell Inc. PowerEdge M620/093MW8, BIOS 2.0.19 08/30/2013
[1295287.752977]  0000000000000000 ffffffff81720b4d ffffffff814f95c4 ffffea0078d8ed98
[1295287.752980]  ffffffff81136185 ffffea0078d8ed98 ffffea0078d8edd0 0000000000000000
[1295287.752982]  ffffffff8113632b 0000000000000296 ffffffff8171d760 ffff883fdee87048
[1295287.752984] Call Trace:
[1295287.752986]  <IRQ>  [<ffffffff814f95c4>] ? dump_stack+0x41/0x51
[1295287.752995]  [<ffffffff81136185>] ? bad_page.part.53+0xb5/0x110
[1295287.752997]  [<ffffffff8113632b>] ? free_pages_prepare+0x14b/0x1a0
[1295287.753000]  [<ffffffff811384d4>] ? __free_pages_ok+0x14/0xd0
[1295287.753003]  [<ffffffff813fe1f8>] ? skb_release_data+0x78/0xc0
[1295287.753006]  [<ffffffff813fe396>] ? consume_skb+0x26/0x80
[1295287.753015]  [<ffffffffa00c79dc>] ? ixgbe_poll+0xdc/0x7e0 [ixgbe]
[1295287.753019]  [<ffffffff8108afb6>] ? scheduler_tick+0x66/0xd0
[1295287.753023]  [<ffffffff810cbf50>] ? tick_sched_handle.isra.16+0x60/0x60
[1295287.753026]  [<ffffffff8140e99a>] ? net_rx_action+0x12a/0x230
[1295287.753029]  [<ffffffff81069033>] ? __do_softirq+0x113/0x290
[1295287.753045]  [<ffffffffa0308190>] ? zio_taskq_member.isra.6+0xa0/0xa0 [zfs]
[1295287.753047]  [<ffffffff8106930d>] ? irq_exit+0x9d/0xa0
[1295287.753051]  [<ffffffff81043adb>] ? smp_apic_timer_interrupt+0x3b/0x50
[1295287.753054]  [<ffffffff814ffd7d>] ? apic_timer_interrupt+0x6d/0x80
[1295287.753056]  <EOI>  [<ffffffffa0308190>] ? zio_taskq_member.isra.6+0xa0/0xa0 [zfs]
[1295287.753070]  [<ffffffff814fe6f9>] ? _raw_spin_unlock_irqrestore+0x9/0x10
[1295287.753086]  [<ffffffffa02b2cec>] ? spa_taskq_dispatch_ent+0x7c/0xb0 [zfs]
[1295287.753099]  [<ffffffffa0307678>] ? zio_taskq_dispatch+0x88/0xa0 [zfs]
[1295287.753110]  [<ffffffffa030769d>] ? zio_issue_async+0xd/0x20 [zfs]
[1295287.753122]  [<ffffffffa030824f>] ? zio_execute+0xbf/0x170 [zfs]
[1295287.753128]  [<ffffffffa007dbc1>] ? taskq_thread+0x1a1/0x340 [spl]
[1295287.753131]  [<ffffffff8108c720>] ? wake_up_state+0x10/0x10
[1295287.753136]  [<ffffffffa007da20>] ? taskq_destroy+0xe0/0xe0 [spl]
[1295287.753138]  [<ffffffff810810be>] ? kthread+0xce/0xf0
[1295287.753140]  [<ffffffff81080ff0>] ? kthread_create_on_node+0x180/0x180
[1295287.753142]  [<ffffffff814feed8>] ? ret_from_fork+0x58/0x90
[1295287.753144]  [<ffffffff81080ff0>] ? kthread_create_on_node+0x180/0x180
```

The snapshot is gone, pool is online and healthy, only this little dump happened.

Server is a Dell PowerEdge M620, 256GB (ARC 50%) with eight 8-tb pools over iscsi.

Any insights?

**Comment by behlendorf** [comment] 2015-07-13 23:18
This looks like a duplicate of #3309.  It's not yet clear if this is actually a ZFS issue or if it's caused by something else.  The others who have reported it are also using DRBD.

**Comment by gmelikov** [comment] 2017-07-16 21:35
Close as stale.

If it's actual - feel free to reopen.

**Closed by gmelikov** 2017-07-16 21:35 UTC
