### ISSUE TITLE
Crash with SCST + ZFS + IOmeter

### ISSUE THREAD

**Issue by kpande** [zfsonlinux/zfs#3127] opened 2015-02-23 00:31 UTC
Some people here say "SCST brings out the worst in ZFS" but I am wondering if it is poorly written or simply using some kind of functionality that IET does not use.

I started testing SCST because it is hailed as a mythical beast in the Linux iSCSI world, supporting features the more basic IET or even COMSTAR don't - one of these claims includes 'higher performance'.

I began testing using my regular i7, 32GB, 4x2TB WD Black box

test: boot a Windows 8.1 image from iSCSI over 1gbe and run latest IOmeter (as of today)
- 64kb block size
- 32 IO per burst
- 80% random, 20% sequential
- 90% write, 10% read
- 8 workers

SCST:
- starts at 750 IOPS and climbs to 1800 and then tanks back to 800 IOPS over 8 minutes
- system crash and becomes unresponsive. I tried to unload SCST but ZFS still blocked in zr_wr_iss

IET:
- starts at 1200 IOPS, climbs to 2100 and stays there

image of server-side stats: http://tripleback.net/public/scst-iet.png

The red rectangle is the area where SCST is tested and the green rectangle is IET test results. The sharp drop-off is because my stats failed to collect any data while SCST hung the box. You can see IET clearly pushes 3k IOPS and uses the same net I/O.

What's going on here?

**Comment by fajarnugraha** [comment] 2015-02-23 02:46
Some more info would be nice
- which versions used (e.g. zol 0.6.3 or head? scst 3.0.0 or trunk?). If you're not using head/trunk, does the same thing happen when you use them?
- what happens when you use LVM disk backend, do you see similar results?
- what is your config file for scst? Do you use vdisk_fileio or vdisk_blockio?

Those above should help pinpoint the source of the problem. If you're lucky, the problem is already known and fixed in current head. If you're not-so-lucky, at least you know whether the problem is specific to scst, zfs, or only to the combination of both.

**Comment by kpande** [comment] 2015-02-23 03:55
The performance suffers with LVM backend but doesn't result in the ultimate hang and crash which leads me to believe there are bugs in ZFS that are exposed by SCST. 

There's bugs in SCST itself because the performance is a bust even without ZFS involved.. 

I've tested on the latest 200 revisions from 0.6.3-159 til -220. This issue is present in all revisions. I've seen other issues reported about SCST (I think of #3062).

I created my SCST targets using vdisk_blockio handlers. Is that not the best to use?

**Comment by fajarnugraha** [comment] 2015-02-23 04:55
Yep, vdisk_blockio is the one to use for zvol, which rules-out cache-related problems. For scst-related slowdown with LVM (which should affect zol as well), you should file a bug on their list/tracker.

As for ZOL side, if I'm reading #3062 and #3050 correctly, the issue is a know one, and a fix is currently in testing. Can you try manually applying ryao/zfs@916e29a and see if the crash still happens? Or alternatively, roll back to earliest 0.6.3 to make sure that is indeed a problem caused by latest kmem rework.

**Comment by kpande** [comment] 2015-02-23 05:12
Sorry, I should have been more clear about what it means to have tested revisions 159 to 220 - the kmem rework was introduced somewhere arond 175 and this crash occurred with my pre-kmem code.

**Comment by fajarnugraha** [comment] 2015-02-23 08:34
I'm trying to reproduce your results on VM environment, but unable to do so. One thing strikes me as odd though. You say "IET clearly pushes 3k IOPS" and that you use "4x2TB WD Black box". What is the capability of the disks, and how did you set it up (e.g. raidz, stripe, mirror)?

Even 15k rpm disks should only be able to handle around 200 random IOPS, making 4 disks in stripe capable of at most 800. How were you able to get 3k? My test setup can only get around 100 IOPS, which is consistent to what my hardware has (2xSATA disks, mirrored). Did you perhaps enable cache or compression somehwhere?

Others might have a better response, but for now I recommend using latest scst (I'm using my slightly-older build: https://launchpad.net/~scst/+archive/ubuntu/3.0.x) and zfs-0.6.3 (not from daily/testing/git. I use 0.6.3-1~wheezy), windows 8.1 32bit. Both ubuntu zfs-scst and windows client on virtualbox.

**Comment by kpande** [comment] 2015-02-23 15:15
I'm using mirrored pairs - 2-way mirrors, in a 'stripe'. I wouldn't expect a VM environment could do this...

My test is running over 1Gbe so it's limited to that, I get better results (up to 10,000IOPS) when using local non-network testing. I use compression=lz4 and my read speeds are throttled (see #3106) @ 1.5GB/s and writes are 300MB/s but with compression=off I can see 3GB/s and 100MB/s writes.



Were you able to compare the performance of IET to SCST?

**Comment by sempervictus** [comment] 2015-02-25 06:30
A bit of clarification may be in order here - on setups like this, you probably wont hit the performance boundaries of most iSCSI implementations provided your processing hardware is reasonable. 
We're running full-SSD ZVOLs on low latency 10G, MPIO iSCSI SAN with large VDEVs ( + L2ARC/SLOG SSD mirrors), and things of that nature through SCST on patched kernels. Our aggregate disk throughput is significantly higher, stripe width smaller, (even on a z2, an 11 disk array is rather quick, esp with a SLOG mirror in front of it), and we somewhat often run workloads that cause cache evictions through tens/hundreds of gigs of L2ARC.

SCST handles these workloads very well, and for long periods of time - iSCSI SAN is not a server, you dont turn it off, hopefully ever, until you're done with it. It also seems to love RAM for use as cache or buffer, even when ZVOLs are exported through BIO, SCST fights it out with page cache all the time (since ARC is set, and being abused, it tends to stay full). We've found that giving SCST its berth in terms of RAM allocation is well worth the small loss in ARC capacity, and prevents those ugly OOMs caused by any one of half a dozen kernel modules in heavily contentious play.

@kpande: Try reducing your ARC, setting sync to always (throttling mechanism), and increasing the number of writer threads ZFS is using (jitter reduction). If SCST is outpacing ZFS that badly, with no userspace/kernel barriers like those present in IET, you may be seeing an unmitigated low level resource exhaustion resulting in your crash.

**Comment by fajarnugraha** [comment] 2015-02-25 07:03
@kpande: there is no way 4x2TB HDD in "2-way mirrors stripe" configuration can deliver 3k random write IOPS without cache. Your best numbers should be less than 500.

I agree with @sempervictus , you should probably set sync=always in this case, as all async writes should be buffered on the initiator side anyway

**Comment by kpande** [comment] 2015-02-27 15:38
@fajarnugraha Please, do go on and tell me what I've "never seen". Using ARC cache during benchmarking should deliver more than 3k IOPS at workstation level. I've seen 3k IOPS being done while the server is "asleep". See my reports in bug #3106 where I give quite extensive benchmark information on my setup.

You should spend less time thinking of how to dismiss bug reports and more time on what is actually happening with them.

**Comment by kpande** [comment] 2015-02-27 15:39
Plus @fajarnugraha the total IOPS (3000) count is combined read+write, it's about 90% write.

**Comment by kpande** [comment] 2015-02-27 15:41
@fajarnugraha Consider the actual results of my test, IET delivers X performance by SCST fails with "Y" which is much less than X. 

It's not a "theoretical" I'm trying to achieve. I've done it once with IET and trying to duplicate it with SCST.

How come SCST needs sync=always ? I do not have SLOG.

**Comment by behlendorf** [comment] 2016-10-12 01:37
@kpande is there any remaining issue here which needs to be addressed?

**Comment by sempervictus** [comment] 2016-10-12 18:49
Not sure about @kpande, but we still see offset errors on ZVOLs exported
via iscsi under heavy fio induced abuse from the initiator side which
doesn't occur with other targets, or if exporting other blockdevs via scst.
Local loopback target simply doesn't work over zvols.

Unfortunately this has caused us to replace all our current targets with
lio despite a long and happy relationship with scst.

**Closed** 2019-02-16 01:12 UTC
