### ISSUE TITLE
bad path in zfs-functions.sh on centos 6

### ISSUE THREAD

**Issue by dmaziuk** [zfsonlinux/zfs#9890] opened 2020-01-25 16:48 UTC
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  centos
Distribution Version	|  6
Linux Kernel	| 
Architecture	| 
ZFS Version	|  0.8.3
SPL Version	| 

### Describe the problem you're observing

pool won't import on boot after 0.8.3 update, `zfs-functions` has
> \# Paths to what we need
> ZFS="/usr/local/sbin/zfs"
> ZED="/usr/local/sbin/zed"
> ZPOOL="/usr/local/sbin/zpool"

**Comment by loli10K** [comment] 2020-01-26 08:34
Duplicate of #9443

**Comment by dmaziuk** [comment] 2020-01-27 15:49
not sure how much of a duplicate it is, as this is in the published RPMs currently in `zfs-kmod` at least. They should be pulled from the repo by yesterday.

**Comment by fdr** [comment] 2020-01-29 00:10
This bit me in auto-remounting totally breaking. Not so great.

**Comment by dmaziuk** [comment] 2020-02-03 18:38
Guys, how !@#$ing hard is it to hand-edit the rpm and release it as 0.8.3-2 so it doesn't keep killing ervery el6 system out there?

Also, `/etc/zfs/zfs-functions` begins with 
> PATH=/sbin:/bin:/usr/bin:/usr/sbin
then goes on to sourcing a bunch of distro-specific stuff, and then come the offending defs:
> ZFS="/usr/local/sbin/zfs"
...
> export ZFS ZED ZPOOL ZPOOL_CACHE ZFS_MOUNT ZFS_UNMOUNT

So I guess I'm not sure what the goal is here. If it's to keep them from being overwritten by the `source`d stuff, why not something like
```
PATH=/sbin:/bin:/usr/bin:/usr/sbin
KEEP_ZFS="`which zfs`"
... stuff ...
ZFS=${KEEP_ZFS}
...
PATH=/sbin:/bin:/usr/bin:/usr/sbin
```
This way you don't need to care where your build scripts set $install root this week.

**Comment by fdr** [comment] 2020-02-03 19:22
...or even going back to 0.8.2. Breaking reboots on every el6 system until 0.8.4, unless you release it, like, today, well...may as well just drop EL6 support if you are going to do it like this.

**Closed** 2020-02-04 03:58 UTC
Labels: Component: Packaging
