### ISSUE TITLE
With new scan code, interrupted ZFS Resilvers start over from zero

### ISSUE THREAD

**Issue by DurvalMenezes** [zfsonlinux/zfs#9646] opened 2019-11-28 09:32 UTC
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Ubuntu
Distribution Version	| 18.04.3 LTS
Linux Kernel	| 4.15.0-70-generic
Architecture	| x86_64
ZFS Version	| 0.8.2-1 (srcversion:     29C160FF878154256C93164)
SPL Version	| 0.8.2-1 (srcversion:     FE982CE539C0DFB51627194)

### Describe the problem you're observing
Using the new sequential code, interrupted resilvers restart from zero. 
Please see thread discussing this on the ZFS mailing list: https://zfsonlinux.topicbox.com/groups/zfs-discuss/T5334632f5200fbb4/zfs-resilver-starting-over-from-zero-after-export

### Describe how to reproduce the problem
1) Start a resilver (eg `zfs replace`); 
2) wait some time (eg a few hours) and note the progress via the `scan: ` lines on the `zfs status` output; 
3) interrupt the resilver (either by exporting the pool or restarting the machine, it doesn't matter);
4) import the pool, wait 10 minutes for the preliminary scan pass to end, thencheck `zfs status` again: the `scan:` lines will show the resilver restarted from zero.

To show the problem is in the new scan code: 
5) Turn the new scan code off (ie, revert to legacy scan, eg via `echo 1 > /sys/module/zfs/parameters/zfs_scan_legacy`);
6) Repeat steps 1-4 above (or only steps 2-4, using the same resilver already on the way); on step 4, notice that the resilver restarted from where it left off, *not* from zero.

### Include any warning/errors/backtraces from the system logs

There is absolutely nothing on the system logs.

**Comment by Ornias1993** [comment] 2019-11-28 11:01
This is actually quite the high priority issue and could potentially cost people their pool.
@behlendorf

**Comment by shodanshok** [comment] 2019-11-28 16:24
I can confirm the issue (just tested on a nearly empty pool). Some additional information:
- I tried on both an un-upgraded pool (from 0.7.13) and an upgraded one (0.8.2); same results;
- I tried changing the value of the `resilver_defer` feature; again, same results.

**Comment by loli10K** [comment] 2019-11-28 18:49
Duplicate of #9393

**Comment by behlendorf** [comment] 2019-12-02 18:32
@DurvalMenezes thanks for the clear reproducer to help us investigate this.

**Comment by DurvalMenezes** [comment] 2019-12-02 20:38
> @DurvalMenezes thanks for the clear reproducer to help us investigate this.

@behlendorf, you are more than welcome. If you need anything else, please don't hesitate to ask (I'm on a road trip with intermittent internet connectivity so I may not be able to respond immediately, but I will at the earliest opportunity).

**Comment by behlendorf** [comment] 2020-01-10 20:16
@DurvalMenezes I've added a https://github.com/zfsonlinux/zfs/issues/9393#issuecomment-573187623 to the original issue to try and better explain this.  The short version is that this behavior is as intended, but it should be better explained in the man page.  Furthermore, there's room for improvement and part of that might be more intelligently setting the relevant default tunings.

**Closed by behlendorf** 2020-01-10 20:16 UTC
Labels: Type: Documentation

**Comment by zenaan** [comment] 2020-07-02 08:06
ZFS on USB (external) drives user here.

Laptop outta space, making use of two ext USB drives, the first was created for backups and offloading, and the second was added as a mirror of the first.

First USB adapter is USB3 and seems to work ok. Second is really cheap, also USB3, but fails consistently after ~580MB (failed about same point, tested twice now) as follows (syslog):

```
Jul 02 17:10:35 eye kernel: usb 1-1.2: reset high-speed USB device number 69 using ehci-pci    
Jul 02 17:10:45 eye kernel: usb 1-1.2: device not accepting address 69, error -110
Jul 02 17:10:45 eye kernel: usb 1-1.2: reset high-speed USB device number 69 using ehci-pci
Jul 02 17:10:56 eye kernel: usb 1-1.2: device not accepting address 69, error -110
Jul 02 17:10:56 eye kernel: usb 1-1.2: reset high-speed USB device number 69 using ehci-pci
Jul 02 17:10:58 eye kernel: sd 6:0:0:0: [sdb] tag#0 FAILED Result: hostbyte=DID_TIME_OUT driverbyte=DRIVER_OK cmd_age=35s
Jul 02 17:10:58 eye kernel: sd 6:0:0:0: [sdb] tag#0 CDB: Write(10) 2a 00 ce a3 2c 88 00 00 80 00                        
Jul 02 17:10:58 eye kernel: blk_update_request: I/O error, dev sdb, sector 3466800264 op 0x1:(WRITE) flags 0x700 phys_seg 1 prio class 0
Jul 02 17:10:58 eye kernel: zio pool=zb2t01 vdev=/dev/disk/by-id/usb-WDC_WD20_SPZX-22UA7T0_0000000000016742-0:0-part1 error=5 type=2 offset=
1774999703552 size=1048576 flags=40080caa
```

So at least the first drive still works, but every reconnect of the second mirror drive restarts a full resilver, which always fails!

Also wrote my steps as a tutorial here:
https://github.com/zenaan/quick-fixes-ftfw/blob/master/zfs/zfs.md#user-content-step-5b---clear-resilvering-errors

**Comment by zenaan** [comment] 2020-07-05 04:41
This "restart resilver on every interruption" ZFS __bug__, may be considered a sort of ultra conservative, ultra paranoid thing.

But the fact is that the ultra paranoid can run a scrub after an interrupted resilver later finishes, and ZFS could anyway (possibly) auto schedule a scrub if the resilver has been interrupted at all...

The irony of this "ultra paranoid" ZFS behaviour is that it is not a usable filesystem on USB drives which might be connected through cheap USB adaptors.

And the sweet irony of reverting ZFS to its previous (slightly less paranoid) behaviour, is that it will instantly become the ONLY safe filesystem to use in such situations.

So +1 for reverting this behaviour and allowing interrupted resilvers to continue when the drive is reconnected.

@DurvalMenezes
