### ISSUE TITLE
Failure during restoring via zfs recv

### ISSUE THREAD

**Issue by evoron** [zfsonlinux/zfs#3292] opened 2015-04-14 13:13 UTC
Sorry, I'm not native English speaker.
I created a pool:

```
# zpool create -m legacy homestank /dev/sda12 /dev/sda5 /dev/sda2
I created a filesystem:
# zfs create -o mountpoint=legacy homestank/homes
# zfs set compression=gzip-9 homestank/homes
# zfs set dedup=on homestank/homes
# zfs set relatime=on homestank/homes
I filled the filesystem with data:
# mount homestank/homes /home
<SNAPSHOTTING>
<READING and WRITING a lot>
I created a backup copy of the filesystem:
# zfs send -vRD homestank/homes >./somefile
I destroyed the pool.
I recreated the pool.
I began to restore the filesystem from the backup copy:
# zfs recv -vu homestank <./somefile
```

System gave me an error:

```
receiving full stream of homestank/homes@zfs-auto-snap_weekly-2015-01-17-1133 into homestank/homes@zfs-auto-snap_weekly-2015-01-17-1133 
received 62,3GB stream in 3926 seconds (16,2MB/sec) 
receiving incremental stream of homestank/homes@zfs-auto-snap_monthly-2015-01-20-1225 into homestank/homes@zfs-auto-snap_monthly-2015-01-20-1225 
received 464MB stream in 101 seconds (4,59MB/sec) 
receiving incremental stream of homestank/homes@zfs-auto-snap_weekly-2015-01-28-1738 into homestank/homes@zfs-auto-snap_weekly-2015-01-28-1738 
cannot receive incremental stream: invalid backup stream
```

**Comment by kpande** [comment] 2015-04-14 13:48
#3066

**Comment by evoron** [comment] 2015-04-14 14:28
ZFS version 0.6.3

**Comment by kpande** [comment] 2015-04-14 14:30
Please try without send -D and then update to 0.6.4 because 0.6.3 is a year+ old and is missing a ton of critical fixes for send/recv. Once you upgrade to 0.6.4 if send -D hangs it is a duplicate of #2210

**Comment by evoron** [comment] 2015-04-17 04:10
I can't reproduce the bug.
In newly created filesystem restoring (zfs recv) was OK.
It was OK when I send it with and without -D.

Is there any way to rescue the data from file?

**Comment by GregorKopka** [comment] 2015-04-28 11:35
After homestank/homes@zfs-auto-snap_monthly-2015-01-20-1225 is received you could try to put a hold on it to keep it from being destroyed in the rollback (which happens after the failure) to at least access that.

Sadly i have no idea how to salvage the rest of the stream.

**Comment by evoron** [comment] 2015-04-30 11:27
Thanks anyway

**Comment by gmelikov** [comment] 2017-02-04 19:09
I think that #5689 closes the issue with -D. Reopen the issue again if it's actual.

**Closed by gmelikov** 2017-02-04 19:09 UTC
