### ISSUE TITLE
large kmem_alloc(9648, 0x20) at nv_alloc_nosleep_spl:45 (1238956/1238956)

### ISSUE THREAD

**Issue by FransUrbo** [zfsonlinux/zfs#2459] opened 2014-07-06 11:39 UTC
Way to reproduce:

```
#!/bin/ksh -p

get_prop
{
    zfs get -H -ovalue $1 $2
}

# Create the base file
rm /var/tmp/zfs_test-1
scripts/mkfile -s 25000m /var/tmp/zfs_test-1

# Base partitioning
/sbin/parted -a none -s /var/tmp/zfs_test-1 mklabel msdos
/sbin/parted -a none -s /var/tmp/zfs_test-1 mkpart primary 1 205
/sbin/parted -a none -s /var/tmp/zfs_test-1 mkpart extended 205 "25G"
/sbin/parted -a none -s /var/tmp/zfs_test-1 mkpart logical 205 410
/sbin/parted -a none -s /var/tmp/zfs_test-1 mkpart logical 410 615
/sbin/parted -a none -s /var/tmp/zfs_test-1 mkpart logical 615 820
/sbin/parted -a none -s /var/tmp/zfs_test-1 mkpart logical 820 1025
/sbin/parted -a none -s /var/tmp/zfs_test-1 mkpart logical 1025 1230
kpartx -asfv /var/tmp/zfs_test-1

# Change the paritioning
/sbin/parted -a none -s /var/tmp/zfs_test-1 mklabel msdos
/sbin/parted -a none -s /var/tmp/zfs_test-1 mkpart primary 1 24425
kpartx -d /var/tmp/zfs_test-1
kpartx -asfv /var/tmp/zfs_test-1

# Create base pool
zpool create -f testpool.3091 /dev/mapper/loop0p1
rm -rf /var/tmp/testdir3091
mkdir -p /var/tmp/testdir3091
zfs create testpool.3091/testfs.3091
zfs set mountpoint=/var/tmp/testdir3091 testpool.3091/testfs.3091

# Create files for test pool
typeset PIDLIST=""
typeset vdevs_list=""
for i in {1..300}; do
        scripts/mkfile 74m /var/tmp/testdir11077/file.$i &
        PIDLIST="$PIDLIST $!"
        vdevs_list="$vdevs_list /var/tmp/testdir11077/file.$i"
done

# Wait for all mkfiles to finish                                                                                                                              
wait $PIDLIST
if (( $? != 0 )); then
    echo "ERROR: Create vdevs failed."
    exit 1
fi

sync

# ISSUE 1
zpool create -f testpool1.3091 $vdevs_list
if [[ $? == 0 ]]; then
    # ISSUE 2
    zpool destroy testpool1.3091
else
    echo "ERROR: Couldn't create testpool1.3091 with large number of file-vdevs"
    exit 1
fi

file_size=74
left_space=$(get_prop "available" testpool.3091/testfs.3091)
echo "left_space='$left_space'"
# Count the broken file size. make sure it should be greater than $left_space                                                                                 
# so, here, we plus a number -- $file_size, this number can be any other number.                                                                              
(( file_size = left_space / (1024 * 1024) + file_size ))
echo "file_size='$file_size'"

# ISSUE 3
scripts/mkfile 22577m /var/tmp/testdir3091/broken_file
```

At _ISSUE 1_ I get:

```
Jul  6 13:28:02 DebianZFS-Wheezy-SCST2 kernel: [  732.301374] SPL: large kmem_alloc(9648, 0x20) at nv_alloc_nosleep_spl:45 (1238956/1238956)
Jul  6 13:28:02 DebianZFS-Wheezy-SCST2 kernel: [  732.301382] Pid: 5973, comm: zpool Tainted: P           O 3.2.0-4-amd64 #1 Debian 3.2.51-1
Jul  6 13:28:02 DebianZFS-Wheezy-SCST2 kernel: [  732.301386] Call Trace:
Jul  6 13:28:02 DebianZFS-Wheezy-SCST2 kernel: [  732.301401]  [<ffffffffa02a8f34>] ? kmem_alloc_debug+0xd0/0x2d0 [spl]
Jul  6 13:28:02 DebianZFS-Wheezy-SCST2 kernel: [  732.301409]  [<ffffffffa0269279>] ? native_cp+0x43/0x55 [znvpair]
Jul  6 13:28:02 DebianZFS-Wheezy-SCST2 kernel: [  732.301414]  [<ffffffffa02695d3>] ? nv_mem_zalloc.isra.12+0xa/0x21 [znvpair]
Jul  6 13:28:02 DebianZFS-Wheezy-SCST2 kernel: [  732.301419]  [<ffffffffa0269879>] ? nvs_operation+0xb6/0x21c [znvpair]
Jul  6 13:28:02 DebianZFS-Wheezy-SCST2 kernel: [  732.301425]  [<ffffffffa026a7f0>] ? nvlist_common+0x1b3/0x1b5 [znvpair]
Jul  6 13:28:02 DebianZFS-Wheezy-SCST2 kernel: [  732.301431]  [<ffffffffa026a83a>] ? nvlist_xunpack+0x48/0x68 [znvpair]
Jul  6 13:28:02 DebianZFS-Wheezy-SCST2 kernel: [  732.301469]  [<ffffffffa064adcf>] ? get_nvlist+0x82/0xb6 [zfs]
Jul  6 13:28:02 DebianZFS-Wheezy-SCST2 kernel: [  732.301492]  [<ffffffffa06506ab>] ? zfs_ioc_pool_create+0x43/0x241 [zfs]
Jul  6 13:28:02 DebianZFS-Wheezy-SCST2 kernel: [  732.301499]  [<ffffffffa02a8e4f>] ? strdup+0x21/0x36 [spl]
Jul  6 13:28:02 DebianZFS-Wheezy-SCST2 kernel: [  732.301526]  [<ffffffffa06513ad>] ? zfsdev_ioctl+0x3a6/0x453 [zfs]
Jul  6 13:28:02 DebianZFS-Wheezy-SCST2 kernel: [  732.301535]  [<ffffffff81352198>] ? do_page_fault+0x30a/0x345
Jul  6 13:28:02 DebianZFS-Wheezy-SCST2 kernel: [  732.301541]  [<ffffffff810380d3>] ? set_next_entity+0x32/0x55
Jul  6 13:28:02 DebianZFS-Wheezy-SCST2 kernel: [  732.301548]  [<ffffffff81107b11>] ? do_vfs_ioctl+0x459/0x49a
Jul  6 13:28:02 DebianZFS-Wheezy-SCST2 kernel: [  732.301552]  [<ffffffff81039ac2>] ? finish_task_switch+0x88/0xb9
Jul  6 13:28:02 DebianZFS-Wheezy-SCST2 kernel: [  732.301556]  [<ffffffff8134de91>] ? __schedule+0x5f9/0x610
Jul  6 13:28:02 DebianZFS-Wheezy-SCST2 kernel: [  732.301562]  [<ffffffff810eb124>] ? kmem_cache_free+0x2d/0x69
Jul  6 13:28:02 DebianZFS-Wheezy-SCST2 kernel: [  732.301566]  [<ffffffff81107b9d>] ? sys_ioctl+0x4b/0x72
Jul  6 13:28:02 DebianZFS-Wheezy-SCST2 kernel: [  732.301577]  [<ffffffff81354212>] ? system_call_fastpath+0x16/0x1b
```

At _ISSUE 2_ I get:

```
Jul  6 13:28:17 DebianZFS-Wheezy-SCST2 kernel: [  747.789498] SPL: large kmem_alloc(8240, 0x20) at nv_alloc_nosleep_spl:45 (93999253/94506277)
Jul  6 13:28:17 DebianZFS-Wheezy-SCST2 kernel: [  747.789506] Pid: 5973, comm: zpool Tainted: P           O 3.2.0-4-amd64 #1 Debian 3.2.51-1
Jul  6 13:28:17 DebianZFS-Wheezy-SCST2 kernel: [  747.789510] Call Trace:
Jul  6 13:28:17 DebianZFS-Wheezy-SCST2 kernel: [  747.789524]  [<ffffffffa02a8f34>] ? kmem_alloc_debug+0xd0/0x2d0 [spl]
Jul  6 13:28:17 DebianZFS-Wheezy-SCST2 kernel: [  747.789532]  [<ffffffffa02695d3>] ? nv_mem_zalloc.isra.12+0xa/0x21 [znvpair]
Jul  6 13:28:17 DebianZFS-Wheezy-SCST2 kernel: [  747.789539]  [<ffffffffa0269879>] ? nvs_operation+0xb6/0x21c [znvpair]
Jul  6 13:28:17 DebianZFS-Wheezy-SCST2 kernel: [  747.789545]  [<ffffffffa026a7f0>] ? nvlist_common+0x1b3/0x1b5 [znvpair]
Jul  6 13:28:17 DebianZFS-Wheezy-SCST2 kernel: [  747.789550]  [<ffffffffa026a83a>] ? nvlist_xunpack+0x48/0x68 [znvpair]
Jul  6 13:28:17 DebianZFS-Wheezy-SCST2 kernel: [  747.789582]  [<ffffffffa064adcf>] ? get_nvlist+0x82/0xb6 [zfs]
Jul  6 13:28:17 DebianZFS-Wheezy-SCST2 kernel: [  747.789589]  [<ffffffff81036628>] ? should_resched+0x5/0x23
Jul  6 13:28:17 DebianZFS-Wheezy-SCST2 kernel: [  747.789624]  [<ffffffffa06510c1>] ? zfsdev_ioctl+0xba/0x453 [zfs]
Jul  6 13:28:17 DebianZFS-Wheezy-SCST2 kernel: [  747.789631]  [<ffffffff81352198>] ? do_page_fault+0x30a/0x345
Jul  6 13:28:17 DebianZFS-Wheezy-SCST2 kernel: [  747.789637]  [<ffffffff811b2d0d>] ? copy_user_generic_string+0x2d/0x40
Jul  6 13:28:17 DebianZFS-Wheezy-SCST2 kernel: [  747.789643]  [<ffffffff81107b11>] ? do_vfs_ioctl+0x459/0x49a
Jul  6 13:28:17 DebianZFS-Wheezy-SCST2 kernel: [  747.789648]  [<ffffffff81107b9d>] ? sys_ioctl+0x4b/0x72
Jul  6 13:28:17 DebianZFS-Wheezy-SCST2 kernel: [  747.789652]  [<ffffffff81354212>] ? system_call_fastpath+0x16/0x1b
```

At _ISSUE 3_ I get:

```
[... the first four lines here repeated 'a million times']
Jul  6 13:32:20 DebianZFS-Wheezy-SCST2 kernel: [  990.411809] loop: Write error at byte offset 22284607488, length 1024.
Jul  6 13:32:20 DebianZFS-Wheezy-SCST2 kernel: [  990.412385] ZFS: zio error=28 type=2 offset=22284591104 size=1024 flags=62441 delay=1
Jul  6 13:32:20 DebianZFS-Wheezy-SCST2 kernel: [  990.412436] loop: Write error at byte offset 22284608512, length 512.
Jul  6 13:32:20 DebianZFS-Wheezy-SCST2 kernel: [  990.412963] ZFS: zio error=28 type=2 offset=22284592128 size=512 flags=62441 delay=0
Jul  6 13:32:20 DebianZFS-Wheezy-SCST2 kernel: [  990.413704] SPLError: 4674:0:(spl-err.c:67:vcmn_err()) WARNING: Pool 'testpool.3091' has encountered an uncorrectable I/O failure and has been suspended.
```

**Comment by behlendorf** [comment] 2015-07-16 19:52
This issue was resolved by the kmem restructuring.  I'm unable to reproduce it with the test suite.

**Closed by behlendorf** 2015-07-16 19:52 UTC
Labels: Bug - Minor, Difficulty - Easy, Test Suite
