### ISSUE TITLE
weird bug in creating pool

### ISSUE THREAD

**Issue by luxflow** [zfsonlinux/zfs#5075] opened 2016-09-08 03:15 UTC
`zpool create -m "/media/test" "test" raidz1 ata-QEMU_HARDDISK_QM00004 ata-QEMU_HARDDISK_QM00003 ata-QEMU_HARDDISK_QM00002 ata-QEMU_HARDDISK_QM00001 &&  zpool export test && zpool import test` not works
`zpool create "test" raidz1 ata-QEMU_HARDDISK_QM00004 ata-QEMU_HARDDISK_QM00003 ata-QEMU_HARDDISK_QM00002 ata-QEMU_HARDDISK_QM00001 &&  zpool export test && zpool import test` works
only difference is changing mountpoint

If you curious why I export and import after create
It is because there is issue, when create new pool, blkid dosen't show properly. so I have to fix that with export and import

version info
ii  debian-zfs                     7~jessie                  amd64        Native ZFS filesystem metapackage for Debian.
ii  libzfs2                        0.6.5.7-8-jessie          amd64        Native ZFS filesystem library for Linux
ii  openmediavault-zfs             3.0.3                     amd64        OpenMediaVault plugin for ZFS
ii  zfs-dkms                       0.6.5.7-8-jessie          all          Native ZFS filesystem kernel modules for Linux
ii  zfsonlinux                     8                         all          archive.zfsonlinux.org trust package
ii  zfsutils                       0.6.5.7-8-jessie          amd64        command-line tools to manage ZFS filesystems

**Comment by kingneutron** [comment] 2016-09-09 04:34
--Using a slightly different test environment (vmware workstation 11.1.4 for Linux) and Ubuntu 16.04.1--LTS-64, I do not get an error when doing virtually the same command:

$ zpool create -m "/media/test" "test" raidz1 \
   pci-0000:02:05.0-scsi-0:0:0:0 pci-0000:02:05.0-scsi-0:0:1:0 pci-0000:02:05.0-scsi-0:0:2:0 pci-0000:02:05.0-scsi-0:0:3:0

$ df
Filesystem        1K-blocks    Used Available Use% Mounted on
zmirpool1/dvcompr   1332864     128   1332736   1% /zmirpool1/dvcompr
test                3514112       0   3514112   0% /media/test

--Package version:
ii  zfsutils-linux                              0.6.5.6-0ubuntu12                                           amd64        Native OpenZFS management utilities for Linux

--Kernel:
$ uname -a
Linux xubuntu1604zfsvm 4.4.0-36-generic #55-Ubuntu SMP

--I pre-labeled the disks with a GPT label (even re-using disks from a previous test pool after running 'zpool labelclear' on them) and it worked fine...  vSCSI Disk size is 1200MB, I have 2GB RAM and 2 vCPUs allocated to the VM.

(example commandline GPT label)
$ parted -s /dev/disk/by-path/pci-0000:02:05.0-scsi-0:0:0:0  mklabel gpt || exit 99 

--In fact, I replicated your exact command to the best of my ability and even threw in some debugging, and it is working fine for me:

 # zpool create -m "/media/test" "test" raidz1   pci-0000:02:05.0-scsi-0:0:0:0 pci-0000:02:05.0-scsi-0:0:1:0 pci-0000:02:05.0-scsi-0:0:2:0 pci-0000:02:05.0-scsi-0:0:3:0 && echo '1' && zpool export test && echo '2' && zpool import test && echo '3'
1
2
3

--The only thing I can think of to recommend is that you try:
a) Ubuntu 14.04 or 16.04 instead of Debian, and/or
b) Vmware Player (free) or Virtualbox (free) instead of Qemu...

**Comment by luxflow** [comment] 2016-09-09 05:25
After trying Ubuntu 16.04 with same hypervisor (qemu) (only os change)
It works.. 
but I'm not sure what is the cause
here are, cause I can think
debian (os change) or zfs-package change(debian 0.6.5,  ubuntu 0.6.5.6) or kernel change(debian backports use 4.6, ubuntu use 4.4)

**Comment by loli10K** [comment] 2017-08-17 11:31
> only difference is changing mountpoint

Likey caused by a non-empty mountpoint, closing.

**Closed by loli10K** 2017-08-17 11:31 UTC
