### ISSUE TITLE
zfs get behavior changed at sys-fs/zfs-0.6.5.4-r2

### ISSUE THREAD

**Issue by AndCycle** [zfsonlinux/zfs#4287] opened 2016-01-29 18:04 UTC
@ryao 

I hit this because zrep heavily rely on zfs properties,

here is the example code which should show the snap

```
$ zfs create pool/test
$ zfs snapshot pool/test@snap
$ zfs set zrep:sent=123456 pool/test@snap
$ zfs get -H -o name -r -s local zrep:sent pool/test
pool/test@snap
```

at sys-fs/zfs-0.6.5.4-r2,
the zfs get return nothing

```
$ zfs create pool/test
$ zfs snapshot pool/test@snap
$ zfs set zrep:sent=123456 pool/test@snap
$ zfs get -H -o name -r -s local zrep:sent pool/test
```

**Comment by ryao** [comment] 2016-01-29 19:09
@AndCycle This would be a regression in the code from #3907 where I had fully unified `zfs get` and `zfs list`, making zfs get subject to the pool's listsnapshots property. This can be overridden by specifying the types via `-t` and is something that I will change to the code to do by default when `-t` is unspecified.

**Comment by AndCycle** [comment] 2016-01-29 19:15
@ryao got it, thanks for the prompt reply

**Comment by ryao** [comment] 2016-01-29 19:20
@AndCycle This patch is queued for the next ebuild revision:

https://github.com/ryao/zfs/commit/8dd00ec43d61d0ede37ad573864266164ba2024a

It should restore the original behavior.

**Comment by ilovezfs** [comment] 2016-01-29 19:51
I'm wondering if it's an upstream bug or feature that bookmarks don't seemed to be included in <code>zfs get all</code>

```
root@omnios-vm:/root# uname -a
SunOS omnios-vm 5.11 omnios-2e8c0ba i86pc i386 i86pc
root@omnios-vm:/root# zfs get all|grep '#'
root@omnios-vm:/root# zfs get -t all all|grep '#'
rpool/ROOT/omnios#install  type                          bookmark                              -
rpool/ROOT/omnios#install  creation                      Fri Jan 29  0:11 2016                 -
root@omnios-vm:/root# zfs get -t all all rpool|grep '#'
root@omnios-vm:/root# zfs get -r -t all all rpool|grep '#'
rpool/ROOT/omnios#install  type                          bookmark                              -
rpool/ROOT/omnios#install  creation                      Fri Jan 29  0:11 2016                 -
root@omnios-vm:/root# zfs get -r all rpool|grep '#'
root@omnios-vm:/root# zfs get -r -t bookmark all rpool|grep '#'
rpool/ROOT/omnios#install  type                  bookmark               -
rpool/ROOT/omnios#install  creation              Fri Jan 29  0:11 2016  -
root@omnios-vm:/root# zfs get all rpool/ROOT/omnios#install |grep '#'
cannot open 'rpool/ROOT/omnios#install': invalid dataset name
root@omnios-vm:/root# zfs get -t bookmark all rpool/ROOT/omnios#install |grep '#'
cannot open 'rpool/ROOT/omnios#install': invalid dataset name
root@omnios-vm:/root# zfs get -t bookmark all rpool/ROOT/omnios#install |grep '#'
cannot open 'rpool/ROOT/omnios#install': invalid dataset name
root@omnios-vm:/root# zfs get -t all all rpool/ROOT/omnios#install |grep '#'
cannot open 'rpool/ROOT/omnios#install': invalid dataset name
root@omnios-vm:/root# zfs list -o space rpool/ROOT/omnios#install |grep '#'
cannot open 'rpool/ROOT/omnios#install': invalid dataset name
root@omnios-vm:/root# zfs list rpool/ROOT/omnios#install       
cannot open 'rpool/ROOT/omnios#install': invalid dataset name
root@omnios-vm:/root# zfs list -t bookmark rpool/ROOT/omnios         
cannot open 'rpool/ROOT/omnios': operation not applicable to datasets of this type
root@omnios-vm:/root# zfs list -r -t bookmark rpool/ROOT/omnios
NAME                        USED  AVAIL  REFER  MOUNTPOINT
rpool/ROOT/omnios#install      -      -      -  -
root@omnios-vm:/root#
```

**Comment by ryao** [comment] 2016-01-29 20:15
@ilovezfs It was an implementation decision that @ahrens made. We probably could change it, but that should be done independently of the stable API. The only behavior change that I an willing to make as part of that is fixing `zfs list $BOOKMARK`, which was broken.

**Comment by AndCycle** [comment] 2016-02-14 09:23
@ryao 
hit another one, it's about list depth parameter
```
# zfs list -r -d 0 zbackup-20150922
NAME                                       USED  AVAIL  REFER  MOUNTPOINT
zbackup-20150922                          22.7T  4.05T   219K  none
zbackup-20150922/backup                   22.7T  4.05T   219K  none
zbackup-20150922/backup/zmess             7.69T  4.05T   219K  none
zbackup-20150922/backup/zmess/p2p         7.69T  4.05T  7.68T  none
zbackup-20150922/backup/zroot              830G  4.05T   219K  none
zbackup-20150922/backup/zroot/mysql       24.2G  4.05T  15.4G  none
zbackup-20150922/backup/zroot/postgresql   648G  4.05T   286G  none
zbackup-20150922/backup/zroot/root        64.9G  4.05T  40.2G  none
zbackup-20150922/backup/zroot/var         92.7G  4.05T  46.1G  none
zbackup-20150922/backup/ztank             14.2T  4.05T   219K  none
zbackup-20150922/backup/ztank/home        13.1T  4.05T  12.7T  none
zbackup-20150922/backup/ztank/iso         1.10T  4.05T  1.10T  none
```
```
# zfs list -d 0 zbackup-20150922
NAME                                       USED  AVAIL  REFER  MOUNTPOINT
zbackup-20150922                          22.7T  4.05T   219K  none
```
the depth parameter doesn't work as intend while conjunction with recursive, 
although it doesn't according to manual
[-r|-d depth]

it do work with ZoL without stable API patch

and  here is another related
```
# zfs list -d 10 -t snapshot zbackup-20150922
cannot open 'zbackup-20150922': operation not applicable to datasets of this type
```

which should show snapshot without stable API patch

**Comment by AndCycle** [comment] 2016-02-14 16:25
got another one which spit out dmesg error then lock up zfs cmd until reboot, haven't verify,

```
/usr/local/sbin/zrep: line 311: 22973: Memory fault
```
```
zfs[28116]: segfault at 7fdb1a0369fc ip 00007f8b19d2d211 sp 00007fffe6e16598 error 4 in libzpool.so.2.0.0[7f8b19cff000+131000]
```

what zrep execute there is probably a standard zfs send/recv,

I accidently modify the recv side so it won't match,
then I execute a zfs rollback cmd trying to make it right,

unfortunately the rollback cmd hang in D+ state,

looks like the zfs cmd doesn't correct bail out due to Memory fault, 
left some kind of lock there,

I have one addition patch https://github.com/zfsonlinux/spl/commit/e843553d0341c4edd880f5ad40da8211669348bd 
on top of sys-kernel/spl-0.6.5.4-r1 so I am not sure is this related.

**Comment by AndCycle** [comment] 2016-02-14 16:38
confirmed hang on zfs rollback -r

```
cannot rollback to 'zbackup-20150922/backup/zmess/p2p@zrep_00009d': more recent snapshots or bookmarks exist
use '-r' to force deletion of the following snapshots and bookmarks:
zbackup-20150922/backup/zmess/p2p@zfs-auto-snap_hourly-2016-02-14-1600
zbackup-20150922/backup/zmess/p2p@zfs-auto-snap_hourly-2016-02-14-1500
zbackup-20150922/backup/zmess/p2p@zfs-auto-snap_hourly-2016-02-14-1400
zbackup-20150922/backup/zmess/p2p@zfs-auto-snap_hourly-2016-02-14-1000
zbackup-20150922/backup/zmess/p2p@zfs-auto-snap_daily-2016-02-14-1600
zbackup-20150922/backup/zmess/p2p@zfs-auto-snap_hourly-2016-02-14-1100
zbackup-20150922/backup/zmess/p2p@zfs-auto-snap_hourly-2016-02-14-1300
zbackup-20150922/backup/zmess/p2p@zfs-auto-snap_hourly-2016-02-14-0900
zbackup-20150922/backup/zmess/p2p@zfs-auto-snap_hourly-2016-02-14-1200
bacztwo ~ # zfs rollback -r zbackup-20150922/backup/zmess/p2p@zrep_00009d
```

**Comment by ryao** [comment] 2016-02-16 20:46
@AndCycle Unless you have 10 levels of descendents, `zfs list -d 10 -t snapshot zbackup-20150922` should not list anything at all.

I need to finish my fixes for other things and get out the new ebuild revision. I think your problems *might* be already fixed in what I have queued.

**Comment by ilovezfs** [comment] 2016-02-17 07:40
>@AndCycle Unless you have 10 levels of descendents, zfs list -d 10 -t snapshot zbackup-20150922 should not list anything at all.

@ryao That is not correct.

illumos:
```
root@omni151017:/root# zfs list -d 10 -t snapshot rpool
NAME                        USED  AVAIL  REFER  MOUNTPOINT
rpool/ROOT/omnios@install   273M      -  1.62G  
```
Which is exactly what you'd expect based on what the man page says.

As for -r and -d, since they are explicitly defined as mutually exclusive in the man page, using them in combination has undefined behavior unless the man page were to also specify what the combined behavior should be. illumos does the following:
```
root@omni151017:/root# zfs list -r -d 0 rpool
NAME    USED  AVAIL  REFER  MOUNTPOINT
rpool  3.93G  11.4G    22K  /rpool
root@omni151017:/root# zfs list -d 0 rpool
NAME    USED  AVAIL  REFER  MOUNTPOINT
rpool  3.93G  11.4G    22K  /rpool
root@omni151017:/root#
```
which is the same behavior @AndCycle says ZoL master has. By contrast the stable API treats `zfs list -d 0 -r o3xpool` and `zfs list -r o3xpool` identically ignoring -d entirely.

**Comment by ryao** [comment] 2016-02-17 14:38
> On Feb 17, 2016, at 2:40 AM, ilovezfs <notifications@github.com> wrote:
> 
> @AndCycle Unless you have 10 levels of descendents, zfs list -d 10 -t snapshot zbackup-20150922 should not list anything at all.
> 
> @ryao That is not correct.
> 
> illumos:
> 
> root@omni151017:/root# zfs list -d 10 -t snapshot rpool
> NAME                        USED  AVAIL  REFER  MOUNTPOINT
> rpool/ROOT/omnios@install   273M      -  1.62G  
> Which is exactly what you'd expect based on what the man page says.
> 
> As for -r and -d, since they are explicitly defined as mutually exclusive in the man page, using them in combination has undefined behavior unless the man page were to also specify what the combined behavior should be. illumos does the following:
> 
> root@omni151017:/root# zfs list -r -d 0 rpool
> NAME    USED  AVAIL  REFER  MOUNTPOINT
> rpool  3.93G  11.4G    22K  /rpool
> root@omni151017:/root# zfs list -d 0 rpool
> NAME    USED  AVAIL  REFER  MOUNTPOINT
> rpool  3.93G  11.4G    22K  /rpool
> root@omni151017:/root#
> which is the same behavior @AndCycle says ZoL master has. By contrast the stable API treats zfs list -d 0 -r o3xpool and zfs list -r o3xpool identically ignoring -d entirely.
> 

Thanks for the correction. I forgot that -D was maximum depth rather than minimum depth. The latter of which is not present in the original code. I will put this in my queue to check after the other regression fixes are ready.

**Comment by AndCycle** [comment] 2016-02-18 16:16
http://list.zfsonlinux.org/pipermail/zfs-discuss/2016-February/024759.html
here is a related recursive destory hang

**Comment by loli10K** [comment] 2017-09-05 17:47
Closing as stale and possibly distro specific, we can reopen this if it still reproduces on vanilla ZoL.

**Closed by loli10K** 2017-09-05 17:47 UTC
