### ISSUE TITLE
libvirt scsi-block generic scsi interface broken

### ISSUE THREAD

**Issue by sempervictus** [zfsonlinux/zfs#4012] opened 2015-11-15 00:11 UTC
When creating a KVM domain with libvirt (in virsh) which utilizes the scsi-block driver with lun targets instead of the disk variant, sgio errors erupt preventing the domain from booting.

Example configuration segment:

```
<disk type='block' device='lun' rawio='no' sgio='unfiltered'>
  <source dev='/dev/zvol/tank/disk0'/>
  <target dev='vda' bus='scsi'/>
  <address type='drive' controller='0' bus='0' target='0' unit='0'/>
</disk>
<disk type='block' device='lun' rawio='no' sgio='unfiltered'>
  <source dev='/dev/zvol/tank/disk1'/>
  <target dev='vdb' bus='scsi'/>
  <address type='drive' controller='0' bus='0' target='1' unit='0'/>
</disk>
<controller type='scsi' index='0' model='virtio-scsi'>
  <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x0'/>
</controller>
```

Errors raised by attempting to boot the domain:
with sgio='unfiltered':

```
error: Requested operation is not valid: unpriv_sgio is not supported by this kernel
```

with sgio='filtered'

```
error: internal error: process exited while connecting to monitor: qemu-system-x86_64: -device scsi-block,bus=scsi0.0,channel=0,scsi-id=0,lun=0,drive=drive-scsi0-0-0-0,id=scsi0-0-0-0,bootindex=2: scsi-block: scsi generic interface too old
qemu-system-x86_64: -device scsi-block,bus=scsi0.0,channel=0,scsi-id=0,lun=0,drive=drive-scsi0-0-0-0,id=scsi0-0-0-0,bootindex=2: Device initialization failed.
qemu-system-x86_64: -device scsi-block,bus=scsi0.0,channel=0,scsi-id=0,lun=0,drive=drive-scsi0-0-0-0,id=scsi0-0-0-0,bootindex=2: Device 'scsi-block' could not be initialized
```

This [ diff ](http://git.qemu.org/?p=qemu.git;a=blobdiff;f=hw/scsi/scsi-disk.c;fp=hw/scsi/scsi-disk.c;h=4bcef551a62eb425edc52034d2ee9c993c1ac571;hp=48a28ae199d11d3214fa814c211eac0e5d1cd8c3;hb=6a23082b4eca28df6a26efae8016d2f2f0921da5;hpb=1a381811b495651ddfc2b50d7c8cfaaf375816b0) seems to show that its trying to look up the version of the SCSI generic interface, and upon not finding one (or finding one lower than v3) throwing that message seen in the sgio='filtered' variant

**Comment by kpande** [comment] 2019-02-16 04:32
Duplicate of #4042

**Closed by kpande** 2019-02-16 04:32 UTC
