### ISSUE TITLE
Another deadlock with crashdump

### ISSUE THREAD

**Issue by lukemarsden** [zfsonlinux/zfs#2307] opened 2014-05-07 08:03 UTC
Another deadlock on yeserday's HEAD. `modinfo zfs`:

```
filename:       /lib/modules/3.13.0-24-generic/extra/zfs/zfs/zfs.ko
version:        0.6.2-274_g2c33b91
license:        CDDL
author:         Sun Microsystems/Oracle, Lawrence Livermore National Laboratory
description:    ZFS
srcversion:     F6471B3005F520F80BF2AD5
```

Crashdump with stacks this time:  http://hybridcluster.net/zol-hangs/201405070038/

Sorry if I'm reporting the same issue multiple times, the stacks and crashdump are fairly opaque to me.  Feel free to close this issue citing a dupe if that's the case.

**Comment by ryao** [comment] 2015-06-11 19:14
@behlendorf HybridCluster/ClusterHQ has not hit this since last year. It should be safe to close this as a duplicate of #2301.

**Comment by behlendorf** [comment] 2015-06-15 22:25
@ryao thanks for mentioning this.  Closing as stale.

**Closed by behlendorf** 2015-06-15 22:25 UTC
Labels: Bug
