### ISSUE TITLE
archive.zfsonlinux.org return 404 for everything

### ISSUE THREAD

**Issue by shurkaxaa** [zfsonlinux/zfs#5536] opened 2016-12-29 03:47 UTC
As result it is impossible to perform installation at least on Debian according to documentation
as it tries download packages from this repository.
...
https://github.com/zfsonlinux/zfs/wiki/HOWTO-install-Debian-GNU-Linux-to-a-Native-ZFS-Root-Filesystem
...
wget http://archive.zfsonlinux.org/debian/pool/main/z/zfsonlinux/zfsonlinux_6_all.deb
...
akharkov$ wget http://archive.zfsonlinux.org/debian/pool/main/z/zfsonlinux/zfsonlinux_6_all.deb
--2016-12-29 10:46:36--  http://archive.zfsonlinux.org/debian/pool/main/z/zfsonlinux/zfsonlinux_6_all.deb
Resolving archive.zfsonlinux.org... 52.216.224.27, 2600:1fa0:80a0:241:36e7:5173::
Connecting to archive.zfsonlinux.org|52.216.224.27|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-12-29 10:46:36 ERROR 404: Not Found.

**Comment by FutureCow** [comment] 2016-12-29 16:10
That page needs an update.

ZFS inside the official Debian Repo: https://github.com/zfsonlinux/zfs/wiki/Debian

**Comment by gmelikov** [comment] 2016-12-29 20:19
HOWTO is outdated,

I wrote the new instruction, you can try to use it, but one problem which exists - don't make datasets for /usr and /var directories, there are some problems with mount order for now.

# new (beta) HOWTO:

These instructions are for Debian GNU/Linux. 
It is an almost exact clone of the [HOWTO install Ubuntu to a Native ZFS Root Filesystem](https://github.com/zfsonlinux/zfs/wiki/Ubuntu%2016.04%20Root%20on%20ZFS) 
procedure with some very small differences.

### System Requirements
  * 64-bit Debian GNU/Linux Live CD.  (Not the alternate installer, and not the 32-bit installer!)
    For Jessie, have a look at [Debian GNU/Linux live cd - Jessie](http://cdimage.debian.org/debian-cd/current-live/amd64/iso-hybrid/).
  * AMD64 or EM64T compatible computer. (ie: x86-64)
  * 8GB disk storage available.
  * 2GB memory minimum.

Computers that have less than 2GB of memory run ZFS slowly.  4GB of memory is recommended for normal performance in basic workloads.  16GB of memory is the recommended minimum for deduplication.  Enabling deduplication is a permanent change that cannot be easily reverted.

### This guide was tested on:
* Debian GNU/Linux 8.6 Jessie
* zfs-0.6.5.8

**WARNING - This instruction uses packages from `unstable` repository for now!**

## Step 1: Prepare The Install Environment

1.1 Start the Debian GNU/Linux LiveCD. Log in by user `user`, password `live`. Enter `sudo bash` to have root privileges.

**Optional:** You can use SSH for easier installation - just enable Password authentication: 
`sed -i "s/PasswordAuthentication no/PasswordAuthentication yes/g" /etc/ssh/sshd_config && service ssh restart`

1.2 Input these commands at the terminal prompt:

	# echo "deb http://ftp.debian.org/debian jessie-backports main contrib" >> /etc/apt/sources.list.d/backports.list
	# apt update
	# apt install linux-headers-$(uname -r) gdisk
	# apt install -t jessie-backports zfs-dkms
	
**Warning:** ZFS is in jessie-backports repository, so it can install some additional packages from testing repository.

1.3 Check that the ZFS filesystem is installed and available:

	# modprobe zfs
	# dmesg | grep ZFS
	[    5.588948] ZFS: Loaded module v0.6.2-524_gd6385c9, ZFS pool version 5000, ZFS filesystem version 5

## Step 2: Disk Partitioning

This tutorial suggests that whole disk will be used.

2.1  If you are re-using any disks which were previously in an MD array, zero the MD superblock now to avoid corruption if MD were to try to assemble the old array.

    # mdadm --zero-superblock --force /dev/disk/by-id/scsi-SATA_disk1

2.2a  If you don't want to use whole disk, prepare partitions by your favorite disk partitioner like `parted` or `cfdisk`.

2.3b  Partition your disk (if you want to use whole disk):

    Run this if you need legacy (BIOS) booting:
    # sgdisk -a1 -n2:34:2047  -t2:EF02 /dev/disk/by-id/scsi-SATA_disk1

    Run this for UEFI booting (for use now or in the future):
    # sgdisk     -n3:1M:+512M -t3:EF00 /dev/disk/by-id/scsi-SATA_disk1

    Run these in all cases:
    # sgdisk     -n9:-8M:0    -t9:BF07 /dev/disk/by-id/scsi-SATA_disk1
    # sgdisk     -n1:0:0      -t1:BF01 /dev/disk/by-id/scsi-SATA_disk1

**Hints:**
* `ls -la /dev/disk/by-id` will list the aliases.
* Are you doing this in a virtual machine? If your virtual disk is missing from `/dev/disk/by-id`, use `/dev/vda` if you are using KVM with virtio; otherwise, read the troubleshooting section.

## Step 3: Disk Formatting

3.1  Create the root pool on the device (use /dev/disk/by-id/scsi-SATA_disk1-partX for specific partition):

	# zpool create -o ashift=12 -o altroot=/mnt \
	-O atime=off -O compression=lz4 -O xattr=sa -m none \
	rpool /dev/disk/by-id/scsi-SATA_disk1-part1

Always use the long `/dev/disk/by-id/*` aliases with ZFS.  Using the `/dev/sd*` device nodes directly can cause sporadic import failures, especially on systems that have more than one storage pool.

**Notes:**
* The use of `ashift=12` is recommended here because many drives today have 4KiB (or larger) physical sectors, even though they present 512B logical sectors.  Also, a future replacement drive may have 4KiB physical sectors (in which case `ashift=12` is desirable) or 4KiB logical sectors (in which case `ashift=12` is required).
* Enable compression by `compression=lz4` is highly recommended, your CPU won't suffer from it, LZ4 algorithm is very fast.
* `xattr=sa` store extended file attributes as system attributes (better performance).
* The root pool can be a mirror.  For example, `zpool create -o ashift=12 rpool mirror /dev/disk/by-id/scsi-SATA_disk2 /dev/disk/by-id/scsi-SATA_disk3`. Remember that the version and ashift matter for any pool that GRUB must read, and that these things are difficult to change after pool creation.
* The latest GRUB can boot from any type of RAID-Z groups. For example, `zpool create -o ashift=12 rpool raidz3 /dev/disk/by-id/scsi-SATA_disk[2-6]`.
* The pool name is arbitrary.  On systems that can automatically install to ZFS, the root pool is named "rpool" by default.  Note that system recovery is easier if you choose a unique name instead of "rpool".  Anything except "rpool" or "tank", like the hostname, would be a good choice. If you DO choose to name your pool by any other name, the grub boot option `rpool` can be used to specify this.

3.2  Create a "ROOT" filesystem in the root pool:

	# zfs create -o mountpoint=none rpool/ROOT

3.3  Create a descendant filesystem for the Debian GNU/Linux system:

	# zfs create -o mountpoint=/ rpool/ROOT/debian-1

On Solaris systems, the root filesystem is cloned and the suffix is incremented for major system changes through `pkg image-update` or `beadm`.  Similar functionality for APT is possible but currently unimplemented.

**NOTE:** if you prefer, you can name the root filesystem you like. Just use the appropriate grub boot option `bootfs`. For example: `zfs create zfspool/hostname`. This would need the following grub boot commandline: `rpool=zfspool bootfs=zfspool/hostname` (replace `hostname` with the actual hostname of the machine).

3.4   Set the `bootfs` property on the root pool.

	# zpool set bootfs=rpool/ROOT/debian-1 rpool

The boot loader uses these two properties to find and start the operating system.  These property names are *not* arbitrary, although their values are (as long as they corresponds with the reality).

3.5  Creating File Systems (recommended, but not necessary):

	# zfs create -o mountpoint=/home rpool/home
	# zfs create -o mountpoint=/root rpool/home/root
	# zfs create -o canmount=off 								rpool/ROOT/debian-1/usr
	# zfs create 												rpool/ROOT/debian-1/var
	# zfs create -o compression=lz4 			             	rpool/ROOT/debian-1/var/cache
	# zfs create -o compression=lz4 -o atime=on 				rpool/ROOT/debian-1/var/mail
	# zfs create -o compression=lz4                            	rpool/ROOT/debian-1/var/spool
	# zfs create -o compression=lz4 -o setuid=off -o exec=off 	rpool/ROOT/debian-1/var/log
	# zfs create -o compression=lz4 -o setuid=off -o exec=off 	rpool/ROOT/debian-1/var/tmp
	# zfs create -o compression=lz4 -o setuid=off -o exec=off 	rpool/ROOT/debian-1/tmp

3.6  Export the pool:

	# zpool export rpool

Don't skip this step.  The system is put into an inconsistent state if this command fails or if you reboot at this point.


## Step 4:  System Installation

**Remember:** Substitute "rpool" for the name chosen in Step 3.1.

4.1  Import the pool:

	# zpool import -d /dev/disk/by-id -R /mnt rpool
	# ## alternative method
	# zpool import -o altroot=/mnt rpool
	
4.2  Place cache pool configuration:

	# mkdir -p /mnt/etc/zfs/
	# zpool set cachefile=/mnt/etc/zfs/zpool.cache rpool

4.3  Install the minimal system (read more https://www.debian.org/releases/jessie/amd64/apds03.html.en):

	# apt install debootstrap
	# debootstrap jessie /mnt

The `debootstrap` command leaves the new system in an unconfigured state.  In Step 5, we will only do the minimum amount of configuration necessary to make the new system runnable.

## Step 5:  System Configuration

5.1  Configure the hostname (change `HOSTNAME` to the desired hostname).

    # echo HOSTNAME > /mnt/etc/hostname

    # nano /mnt/etc/hosts #Add HOSTNAME to line
    127.0.0.1       localhost HOSTNAME 

5.2  Edit the `/mnt/etc/network/interfaces` file so that it contains something like this:

	# interfaces(5) file used by ifup(8) and ifdown(8)
	auto lo
	iface lo inet loopback
	
	auto eth0
	iface eth0 inet dhcp

Customize this file if the new system is not a DHCP client on the LAN.

5.3  Make virtual filesystems in the LiveCD environment visible to the new system and `chroot` into it:

	# mount --bind /dev  /mnt/dev
	# mount --bind /proc /mnt/proc
	# mount --bind /sys  /mnt/sys
	# chroot /mnt /bin/bash --login
	
5.4 Configure a basic system environment:

	# apt-get install locales
    # locale-gen en_US.UTF-8

Even if you prefer a non-English system language, always ensure that `en_US.UTF-8` is available.

    # echo 'LANG="en_US.UTF-8"' > /etc/default/locale
    # dpkg-reconfigure tzdata
    # ln -s /proc/self/mounts /etc/mtab

5.5 Install the ZoL archive support and needed packages in the chroot environment:

	# echo "deb http://ftp.debian.org/debian jessie-backports main contrib" >> /etc/apt/sources.list.d/backports.list
	# apt update
	# apt install linux-image-amd64 linux-headers-$(uname -r) gdisk
	# apt install -t jessie-backports zfs-dkms zfs-initramfs
	# apt-get dist-upgrade
	# update-initramfs -u
	
**Warning:** This is the second time that you must wait for the SPL and ZFS modules to compile.  
*Do not* try to skip this step by copying anything from the host environment into the chroot environment.

**Note:** This should install a kernel package and its headers and dkms packages.  
	
5.6  Install GRUB

**Note:** We need to install grub from **unstable** repository for now.
	
Add preferences for apt in `/etc/apt/preferences` file:
```
Package: *
Pin: release  a=stable
Pin-Priority: 700

Package: *
Pin: release a=jessie-backports
Pin-Priority: 650

Package: *
Pin: release  a=testing
Pin-Priority: 600

Package: *
Pin: release a=unstable
Pin-Priority: 100
```

Add unstable repo:
 	# echo "deb http://http.us.debian.org/debian unstable main contrib non-free" >> /etc/apt/sources.list.d/backports.list
	# apt-get update

Install grub from unstable:
	# apt install grub-pc -t unstable

Choose `/dev/disk/by-id/scsi-SATA_disk1` if prompted to install the MBR loader.

**Note** You can check grub zfs support:
	# grub-probe /
	zfs
        
Ignore warnings that are caused by the chroot environment like:

* `Can not write log, openpty() failed (/dev/pts not mounted?)`
* `df: Warning: cannot read table of mounted file systems`

5.7  Edit `/etc/grub.d/10_linux` file, find this line:

    LINUX_ROOT_DEVICE="ZFS=${rpool}${bootfs}"
    
Add ` boot=zfs` to get this result:

    LINUX_ROOT_DEVICE="ZFS=${rpool}${bootfs} boot=zfs"
    
5.8  Update grub:

	# update-grub

5.8  Set a root password on the new system:

	# passwd root

**Note:** At this time the system have been installed on a new ZFS root system so it is clean and pristine. 
It would be a good idea to do a zfs snapshot here. For example: 

	# zfs snapshot rpool/ROOT/debian-1@YYYYMMDD-cleaninstall

## Step 6:  Cleanup and First Reboot

6.1  Exit from the `chroot` environment back to the LiveCD environment:

	# exit

6.2  Run these commands in the LiveCD environment to dismount all filesystems:

	# umount /mnt/dev
	# umount /mnt/proc
	# umount /mnt/sys
	# zfs umount -a
	
Test valid zfs mounting:

	# zfs mount -a
	# zfs umount -a
	
**Note:** If you have `cannot mount '/mnt/any': directory is not empty` error, you have to rename children datasets, mount parent dataset correctly, rename datasets back and test mount again (see (4784 issue)[https://github.com/zfsonlinux/zfs/issues/4784#issuecomment-227802989]).

Example for `var` dataset:

    # zfs rename rpool/var/log rpool/home/log
    # zfs rename rpool/var/mail rpool/home/mail
    # zfs rename rpool/var/tmp rpool/home/tmp
    # rm -rf /mnt/var
    # zfs mount -a
    # zfs rename rpool/home/tmp rpool/var/tmp
    # zfs rename rpool/home/log rpool/var/log
    # zfs rename rpool/home/mail rpool/var/mail
    # zfs mount -a
    # zfs umount -a
    # zfs mount -a
	# zfs umount -a
	
6.3  Export rpool:
	
	# zpool export rpool

**Warning:** The `zpool export` command must succeed without being forced or the new system will fail to start.

6.4  We're done!

	# reboot


## Caveats and Known Problems

### This is an experimental system configuration.

This document was first published in 2010 to demonstrate that the `lzfs` implementation made ZoL 0.5 feature complete.  Upstream integration efforts began in 2012, and it will be at least a few more years before this kind of configuration is even minimally supported.

Gentoo, and its derivatives, are the only Linux distributions that are currently mainlining support for a ZoL root filesystem.

### `zpool.cache` inconsistencies cause random pool import failures.

The `/etc/zfs/zpool.cache` file embedded in the initrd for each kernel image must be the same as the `/etc/zfs/zpool.cache` file in the regular system.  Run `update-initramfs -c -k all` after any `/sbin/zpool` command changes the `/etc/zfs/zpool.cache` file.

This will be a recurring problem until issue [zfsonlinux/zfs#330](https://github.com/zfsonlinux/zfs/issues/330) is resolved.

### Every upgrade can break the system.

Debian GNU/Linux based systems remove old dkms modules before installing new dkms modules.  If the system crashes or restarts during a ZoL module upgrade, which is a failure window of several minutes, then the system becomes unbootable and must be rescued.

This will be a recurring problem until issue [zfsonlinux/pkg-zfs#12](https://github.com/zfsonlinux/pkg-zfs/issues/12) is resolved.


# Troubleshooting

## (i) MPT2SAS

Most problem reports for this tutorial involve `mpt2sas` hardware that does slow asynchronous drive initialization, like some IBM M1015 or OEM-branded cards that have been flashed to the reference LSI firmware.

The basic problem is that disks on these controllers are not visible to the Linux kernel until after the regular system is started, and ZoL does not hotplug pool members.  See https://github.com/zfsonlinux/zfs/issues/330.

Most LSI cards are perfectly compatible with ZoL, but there is no known fix if your card has this glitch.  Please use different equipment until the `mpt2sas` incompatibility is diagnosed and fixed, or donate an affected part if you want solution sooner.

## (ii) Areca

Systems that require the `arcsas` blob driver should add it to the `/etc/initramfs-tools/modules` file and run `update-initramfs -c -k all`.

Upgrade or downgrade the Areca driver if something like `RIP: 0010:[<ffffffff8101b316>]  [<ffffffff8101b316>] native_read_tsc+0x6/0x20` appears anywhere in kernel log.  ZoL is unstable on systems that emit this error message.


## (iii) GRUB Installation

Verify that the ZoL repository for the ZFS enhanced GRUB is installed:

	# rgrep -E '^deb .*archive.zfsonlinux.org' `find /etc/apt/sources.list*`
	/etc/apt/sources.list.d/zfsonlinux.list:deb http://archive.zfsonlinux.org/debian wheezy main
	/etc/apt/sources.list.d/zfsonlinux.list:deb http://archive.zfsonlinux.org/debian wheezy main

If not, install the ZoL repository trust package like you did in point 1.2 and 5.5:

	# wget http://archive.zfsonlinux.org/debian/pool/main/z/zfsonlinux/zfsonlinux_3%7Ewheezy_all.deb
	# dpkg -i zfsonlinux_3~wheezy_all.deb
	# apt-get update

Reinstall the `zfs-grub` package, which is an alias for a patched `grub-common` package:

	# apt-get install --reinstall zfs-grub

Afterwards, this should happen:

	# apt-cache search zfs-grub
	grub-common - GRand Unified Bootloader (common files)
	grub-pc - GRand Unified Bootloader, version 2 (PC/BIOS version)
	grub-pc-bin - GRand Unified Bootloader, version 2 (PC/BIOS binaries)
	
	# apt-cache show zfs-grub
	N: Can't select versions from package 'zfs-grub' as it is purely virtual
	N: No packages found
	
	# apt-cache policy grub-common zfs-grub
	grub-common:
	  Installed: 2.01-22debian1+zfs3~wheezy
	  Candidate: 2.01-22debian1+zfs3~wheezy
	  Version table:
	 *** 2.01-22debian1+zfs3~wheezy 0
	       1001 http://archive.zfsonlinux.org/debian/ wheezy/main amd64 Packages
	        100 /var/lib/dpkg/status
	     1.99-27+deb7u2 0
	        500 http://ftp.us.debian.org/debian/ wheezy/main amd64 Packages
	zfs-grub:
	  Installed: (none)
	  Candidate: (none)
	  Version table:

For safety, grub modules are never updated by the packaging system after initial installation. Manually refresh them by doing this:

	# cp /usr/lib/grub/i386-pc/*.mod /boot/grub/i386-pc/

If the problem persists, then open a bug report and attach the entire output of those `apt-get` commands.

GRUB packages in the ZoL repository are compiled against the stable distribution.

Note that GRUB does not currently dereference symbolic links in a ZFS filesystem, so you cannot use the  `/vmlinux` or `/initrd.img` symlinks as GRUB command arguments.

## (iv) VMware

* Set `disk.EnableUUID = "TRUE"` in the vmx file or vsphere configuration.  Doing this ensures that `/dev/disk` aliases are created in the guest.

## (v) QEMU/KVM/XEN

* In the `/etc/default/grub` file,  enable the `GRUB_TERMINAL=console` line and remove the `splash` option from the `GRUB_CMDLINE_LINUX_DEFAULT` line.  Plymouth can cause boot errors in these virtual environments that are difficult to diagnose.

* Set a unique serial number on each virtual disk.  (eg: `-drive if=none,id=disk1,file=disk1.qcow2,serial=1234567890`)

## (vi) Kernel Parameters

The `zfs-initramfs` package requires that `boot=zfs` always be on the kernel command line.  If the `boot=zfs` parameter is not set, then the init process skips the ZFS routine entirely.  This behavior is for safety; it makes the casual installation of the zfs-initramfs package unlikely to break a working system.

ZFS properties can be overridden on the the kernel command line with `rpool` and `bootfs` arguments.  For example, at the GRUB prompt:

`linux /ROOT/debian-1/@/boot/vmlinuz-3.0.0-15-generic boot=zfs rpool=AltPool bootfs=AltPool/ROOT/foobar-3`

## (vii) System Recovery

If the system randomly fails to import the root filesystem pool, then do this at the initramfs recovery prompt:

	# zpool export rpool
	: now export all other pools too
	# zpool import -d /dev/disk/by-id -f -N rpool
	: now import all other pools too
	# mount -t zfs -o zfsutil rpool/ROOT/debian-1 /root
	: do not mount any other filesystem
	# cp /etc/zfs/zpool.cache /root/etc/zfs/zpool.cache
	# exit

This refreshes the `/etc/zfs/zpool.cache` file.  The `zpool` command emits spurious error messages regarding missing or corrupt vdevs if the `zpool.cache` file is stale or otherwise incorrect.

**Comment by dave-fl** [comment] 2017-01-02 13:40
@gmelikov Where in the logs do you see issues with the mount?  If seeing mount issues they can probably be solved with legacy and fstab.

**Comment by jumbi77** [comment] 2017-01-03 21:42
Maybe a bit off-topic but i guess that 'zfsonlinux/**zfs**/**wiki**' is main repository and all important github-wiki-pages are published in that repository. I find it a bit confusing that the repositories '[zfsonlinux/zfs-auto-snapshot](https://github.com/zfsonlinux/zfs-auto-snapshot/wiki)' and '[zfsonlinux/pkg-zfs'](https://github.com/zfsonlinux/pkg-zfs/wiki) has its own github-wiki pages. For e.g. you find several (outdated?) HOWTO's to create ZFS rpool for Ubuntu/RHEL/... in 'zfsonlinux/pkg-zfs'. Especially the '[HOWTO use zvol as swap](https://github.com/zfsonlinux/pkg-zfs/wiki/HOWTO-use-a-zvol-as-a-swap-device)' is quit important and should be listed in the /zfsonlinux/zfs/wiki repository. So maybe someone can move the wiki pages to main repository and also update them if necessary/delete if outdated. If you don't agree ignore my suggestion.

**Comment by ghfields** [comment] 2017-01-04 17:03
I agree that the other repositories are off the beaten track.  Correct me if I'm wrong, but I think that the OS specific wiki articles existed first in '[zfsonlinux/pkg-zfs/](https://github.com/zfsonlinux/pkg-zfs/wiki)'.  I still do a little work ([Ubuntu 16.10 Root Pool install /w Ubiquity GUI installer](https://github.com/zfsonlinux/pkg-zfs/wiki/HOWTO-install-Ubuntu-16.10-to-a-Whole-Disk-Native-ZFS-Root-Filesystem-using-Ubiquity-GUI-installer)) in that because it allows for edits, where as 'zfsonlinux/zfs/wiki' does not.

**Comment by rlaager** [comment] 2017-01-05 01:29
I merged the changes from @gmelikov to create: https://github.com/zfsonlinux/zfs/wiki/Debian-Jessie-Root-on-ZFS

I copied the Ubuntu 16.04 instructions and manually merged the changes in, for a variety of reasons. This intentionally lost a few of @gmelikov's changes, which I am open to considering separately.

**Closed by rlaager** 2017-01-05 01:29 UTC

**Comment by rlaager** [comment] 2017-01-05 01:31
@gmelikov I mentioned you by name in the Debian HOWTO as someone who should be mentioned in bug reports. I'm assuming you're looking to help maintain the HOWTOs. If that is not the case, please let me know and I'll remove your name so you don't get hit with bug reports.

**Comment by dave-fl** [comment] 2017-01-05 02:10
@rlaager there are issues with the new instructions. There will be no mountpoint on the var or home directories. They won't be used.

**Comment by gmelikov** [comment] 2017-01-05 08:07
Yes, i'm ready to help, thanks for merging.

**Comment by shurkaxaa** [comment] 2017-01-07 06:40
With this guide I can not even create pool after partitioning.

root@localhost:/home/vagrant# sgdisk -a1 -n2:34:2047  -t2:EF02 /dev/disk/by-id/ata-VBOX_HARDDISK_VB9699ebb0-2a7a78d8
The operation has completed successfully.
root@localhost:/home/vagrant# sgdisk     -n9:-8M:0    -t9:BF07 /dev/disk/by-id/ata-VBOX_HARDDISK_VB9699ebb0-2a7a78d8
The operation has completed successfully.
root@localhost:/home/vagrant# sgdisk     -n1:0:0      -t1:BF01  /dev/disk/by-id/ata-VBOX_HARDDISK_VB9699ebb0-2a7a78d8
The operation has completed successfully.
root@localhost:/home/vagrant# zpool create -o ashift=12 -o altroot=/mnt -O atime=off -O compression=lz4 -O xattr=sa -m none rpool /dev/disk/by-id/ata-VBOX_HARDDISK_VB9699ebb0-2a7a78d8-part1
invalid vdev specification
use '-f' to override the following errors:
/dev/disk/by-id/ata-VBOX_HARDDISK_VB9699ebb0-2a7a78d8-part1 contains a filesystem of type 'ext4'
...
root@localhost:/home/vagrant# sgdisk -p /dev/disk/by-id/ata-VBOX_HARDDISK_VB9699ebb0-2a7a78d8
Disk /dev/disk/by-id/ata-VBOX_HARDDISK_VB9699ebb0-2a7a78d8: 16777216 sectors, 8.0 GiB
Logical sector size: 512 bytes
Disk identifier (GUID): 575E5142-7DDC-4894-B57C-D1C516D2AAB8
Partition table holds up to 128 entries
First usable sector is 34, last usable sector is 16777182
Partitions will be aligned on 2-sector boundaries
Total free space is 0 sectors (0 bytes)

Number  Start (sector)    End (sector)  Size       Code  Name
   1            2048        16760797   8.0 GiB     BF01  
   2              34            2047   1007.0 KiB  EF02  
   9        16760798        16777182   8.0 MiB     BF07

**Comment by gmelikov** [comment] 2017-01-07 09:31
Yes, it's a normal behaviour, there's a safety check because zpool commands don't ask prompts. You can just add `-f` to override this check, as the command wrote to you.
