### ISSUE TITLE
ZIL not mirroring writes (corrected: mirror out of sync due to varying write speeds)

### ISSUE THREAD

**Issue by devonblzx** [zfsonlinux/zfs#5890] opened 2017-03-14 02:56 UTC
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  Debian
Distribution Version    |   Jessie (8)
Linux Kernel                 |  4.4
Architecture                 |   x64
ZFS Version                  |  0.6.5.9-1
SPL Version                  |   0.6.5.9-1

### Describe the problem you're observing

Only seeing writes to one drive in my ZIL mirror.  I imagine this could be a major issue if the one drive failed, as the mirror does not seem to be replicating the writes across the drives.  (See attached image)

![image](https://cloud.githubusercontent.com/assets/8078969/23883825/dd59de8c-083f-11e7-8d57-0ff8a9714390.png)

I also notice that alloc is 0, not sure if that is an accounting error or it is showing the problem is elsewhere.

### Describe how to reproduce the problem

Set up a pool with a mirrored log, ran fio benchmark, monitored zpool iostat as well as the iostat (from sysstat) and compared writes on the mirrored vdevs.   zpool iostat allowed me to confirm the issue was with the zil, the system iostat showed me that there was much more write bandwidth on one SSD.

#### Fio config

```
[randread]
ioengine=libaio
iodepth=4
rw=randread
bs=4k
direct=0
size=8g
numjobs=12
```

If unable to reproduce, above if the fio file I used to run the benchmark.  This is a test bed system that will be available for another week or so, if you want me to run more tests, I can without worrying about data.

**Comment by behlendorf** [comment] 2017-03-14 17:28
@devonblzx thanks for reporting this, it's something we'll definitely want to look in too.  If possible can you verify this is also still in issue in either the 0.7.0-rc3 tag or the master source.

**Comment by devonblzx** [comment] 2017-03-15 15:51
@behlendorf I'm trying to build from master but I'm running into this:

```
Making all in module
make[2]: Entering directory '/home/devon/zfs/module'
-e 
 *** Missing spl symbols ensure you have built the spl:
 *** - /home/devon/spl/Module.symvers, or
 *** - /home/devon/spl/module/Module.symvers
```

I built SPL from master without issue, the spl module is loaded:

```
$ sudo modinfo spl
filename:       /lib/modules/4.4.40-1-pve/extra/spl/spl/spl.ko
version:        0.7.0-rc3_4_ge0aacd9
license:        GPL
author:         OpenZFS on Linux
description:    Solaris Porting Layer
srcversion:     2E6C2336B6FC8FAF131780E
```

Any ideas?

**Comment by devonblzx** [comment] 2017-03-15 16:48
@behlendorf 
So I took 5 screenshots running on master:

![selection_068](https://cloud.githubusercontent.com/assets/8078969/23959421/8b36cbb4-097b-11e7-97c3-3c9af908fbff.jpg)
![selection_069](https://cloud.githubusercontent.com/assets/8078969/23959423/8b3f9be0-097b-11e7-9765-87fe0723a688.jpg)
![selection_070](https://cloud.githubusercontent.com/assets/8078969/23959425/8b4180c2-097b-11e7-836b-ed29040353bb.jpg)
![selection_071](https://cloud.githubusercontent.com/assets/8078969/23959424/8b410228-097b-11e7-8c94-5681c1f775a5.jpg)
![selection_072](https://cloud.githubusercontent.com/assets/8078969/23959422/8b3eef4c-097b-11e7-9a44-c905942ebaeb.jpg)

So I found that it was writing a lot to one SSD right off the bat, then it seemed to stop writing to that SSD so the other could catch up.  Maybe this is working as expected and in my system, the one SSD is being written to much slower.

I decided to test it further by disabling secondary cache and setting up iostat on a 60 second interval, here you can see more:

![selection_073](https://cloud.githubusercontent.com/assets/8078969/23960147/843ba530-097d-11e7-8fb6-e84f2101f492.jpg)

So in the first minute, sdc receives the bulk of the load, but the situation reverses the second minute.  To me, it still has the possibility to leave the two drives out of sync for up to a minute, so that may still indicate an issue.

(By the way, zpool iostat interval doesn't appear to work like the iostat interval, iostat polls constantly and builds up the statistics for 60 seconds, zpool iostat only polls every 60 seconds)

**Comment by devonblzx** [comment] 2017-03-15 17:06
I did confirm the sandisk is maxing out at 70MB/s on sequential writes so that is what is leading to it being out of sync.

**Comment by behlendorf** [comment] 2017-03-20 18:43
@devonblzx thanks for posting the additional data.  Based on the screen shots you've provided it appears that this is working as intended.  The performance mismatch from your log devices just makes it somewhat difficult to observe.  I don't believe there's a bug here, so let's close this issue.

**Closed** 2017-03-20 20:41 UTC
