### ISSUE TITLE
Hang on mount with kernel 4.7.x or newer with 0.6.5.8

### ISSUE THREAD

**Issue by satmandu** [zfsonlinux/zfs#5148] opened 2016-09-22 00:49 UTC
I'm using the stock ubuntu yakkety (dev) 0.6.5.8 release, and I have a volume that mounts just fine when using a 4.6.x kernel with that version of zfsonlinux.

When I use a 4.7.x or 4.8.x (linux-signed-image-4.8.0-11-generic is now available in the ubuntu dev pool) kernel, the system hangs at:

```
Starting Import ZFS pools by cache file.
Starting Mount ZFS Filesystems...
A start job is running for Mount ZFS filesystems (time / no limit)
INFO: task zfs:3907 blocked for more than 120 seconds.
```

(I have to eventually hit ctrl-alt-del to reboot.)

I imagine that this trouble report is pretty close to less than useless to help debug. What information can I provide to help fix this issue?

**Comment by behlendorf** [comment] 2016-09-22 00:55
By chance have you set `casesensitivity=insensitive`, if so this may be a duplicate of #5124.  If so there's a proposed fix in #5141, if you could verify it resolves the issue that would be very helpful.

**Comment by satmandu** [comment] 2016-09-22 00:56
I DO have casesensitivity=insensitive on that volume!

**Comment by satmandu** [comment] 2016-09-22 01:33
That patch doesn't work against the 0.6.5.8 branch, so I'll wait to test a version that does. :)

**Closed** 2016-09-23 02:09 UTC

**Comment by ezplanet** [comment] 2023-03-02 17:58
I have exactly the same problem. Running Ubuntu Server 22. Updated to the latest patches. case-insensitive isn't set anywhere. I have 2 servers both hang at the same point. The only way is to disconnect the drive, boot, reconnect the drive, if I import the pool now it works, but I can never reboot with the zpool drive connected or it will not boot at all.

**Comment by satmandu** [comment] 2023-03-02 19:44
@ezplanet If case insensitivity isn't set on the volume, then this probably isn't your issue. You should create a new issue.
