### ISSUE TITLE
Read IO errors not reported by zpool status

### ISSUE THREAD

**Issue by JeroenDeKleijn** [zfsonlinux/zfs#1814] opened 2013-10-26 22:15 UTC
Hello,

I'm not sure if this is a bug or how it is supposed to work but to me the following seems incorrect/strange:
I always understood the read errors reported by the zpool status command show IO errors reported by the disks in the pool. Now I have a disk with some unreadible sectors, which are reported in dmesg (See below). I would expect these to show up in the zpool status command, but they do not. How come?
If I compare the md5 of the file that has the bad sectors I can see that the file is correct, so I suspect ZFS is reconstructing the correct data.

My setup:
Ubuntu 12.04 with ZoL 0.6.2 from the stable PPA.
10x 2TB in a RaidZ2 configuration 

<code>
[   91.994614] ata3.00: exception Emask 0x0 SAct 0x28 SErr 0x0 action 0x0
[   91.994740] ata3.00: irq_stat 0x40000008
[   91.994815] ata3.00: failed command: READ FPDMA QUEUED
[   91.994915] ata3.00: cmd 60/f1:28:01:c3:18/00:00:14:00:00/40 tag 5 ncq 123392 in
[   91.994918]          res 41/40:00:b0:c3:18/00:00:14:00:00/40 Emask 0x409 (media error) <F>
[   91.995184] ata3.00: status: { DRDY ERR }
[   91.995256] ata3.00: error: { UNC }
[   92.007602] ata3.00: configured for UDMA/133
[   92.007620] ata3: EH complete
[   92.424928] ata3.00: exception Emask 0x0 SAct 0x3 SErr 0x0 action 0x0
[   92.425042] ata3.00: irq_stat 0x40000008
[   92.425123] ata3.00: failed command: READ FPDMA QUEUED
[   92.425226] ata3.00: cmd 60/f1:00:01:c3:18/00:00:14:00:00/40 tag 0 ncq 123392 in
[   92.425229]          res 41/40:00:b0:c3:18/00:00:14:00:00/40 Emask 0x409 (media error) <F>
[   92.425516] ata3.00: status: { DRDY ERR }
[   92.425592] ata3.00: error: { UNC }
[   92.437942] ata3.00: configured for UDMA/133
[   92.437957] ata3: EH complete
[   92.822156] ata3.00: exception Emask 0x0 SAct 0x3 SErr 0x0 action 0x0
[   92.822275] ata3.00: irq_stat 0x40000008
[   92.822347] ata3.00: failed command: READ FPDMA QUEUED
[   92.822457] ata3.00: cmd 60/f1:08:01:c3:18/00:00:14:00:00/40 tag 1 ncq 123392 in
[   92.822460]          res 41/40:00:b0:c3:18/00:00:14:00:00/40 Emask 0x409 (media error) <F>
[   92.822747] ata3.00: status: { DRDY ERR }
[   92.822819] ata3.00: error: { UNC }
[   92.835149] ata3.00: configured for UDMA/133
[   92.835167] ata3: EH complete
[   93.197312] ata3.00: exception Emask 0x0 SAct 0x3 SErr 0x0 action 0x0
[   93.197431] ata3.00: irq_stat 0x40000008
[   93.197509] ata3.00: failed command: READ FPDMA QUEUED
[   93.197612] ata3.00: cmd 60/f1:00:01:c3:18/00:00:14:00:00/40 tag 0 ncq 123392 in
[   93.197618]          res 41/40:00:b0:c3:18/00:00:14:00:00/40 Emask 0x409 (media error) <F>
[   93.197897] ata3.00: status: { DRDY ERR }
[   93.197973] ata3.00: error: { UNC }
[   93.210324] ata3.00: configured for UDMA/133
[   93.210341] ata3: EH complete
[   93.583504] ata3.00: exception Emask 0x0 SAct 0xf SErr 0x0 action 0x0
[   93.583628] ata3.00: irq_stat 0x40000008
[   93.583702] ata3.00: failed command: READ FPDMA QUEUED
[   93.583801] ata3.00: cmd 60/f1:08:01:c3:18/00:00:14:00:00/40 tag 1 ncq 123392 in
[   93.583804]          res 41/40:00:b0:c3:18/00:00:14:00:00/40 Emask 0x409 (media error) <F>
[   93.584095] ata3.00: status: { DRDY ERR }
[   93.584172] ata3.00: error: { UNC }
[   93.596522] ata3.00: configured for UDMA/133
[   93.596541] ata3: EH complete
[   94.080027] ata3.00: exception Emask 0x0 SAct 0xc SErr 0x0 action 0x0
[   94.080150] ata3.00: irq_stat 0x40000008
[   94.080229] ata3.00: failed command: READ FPDMA QUEUED
[   94.080333] ata3.00: cmd 60/f1:10:01:c3:18/00:00:14:00:00/40 tag 2 ncq 123392 in
[   94.080336]          res 41/40:00:b0:c3:18/00:00:14:00:00/40 Emask 0x409 (media error) <F>
[   94.080624] ata3.00: status: { DRDY ERR }
[   94.080695] ata3.00: error: { UNC }
[   94.093064] ata3.00: configured for UDMA/133
[   94.093086] sd 2:0:0:0: [sdc] Unhandled sense code
[   94.093091] sd 2:0:0:0: [sdc]  Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
[   94.093098] sd 2:0:0:0: [sdc]  Sense Key : Medium Error [current] [descriptor]
[   94.093107] Descriptor sense data with sense descriptors (in hex):
[   94.093112]         72 03 11 04 00 00 00 0c 00 0a 80 00 00 00 00 00
[   94.093129]         14 18 c3 b0
[   94.093142] sd 2:0:0:0: [sdc]  Add. Sense: Unrecovered read error - auto reallocate failed
[   94.093152] sd 2:0:0:0: [sdc] CDB: Read(10): 28 00 14 18 c3 01 00 00 f1 00
[   94.093173] end_request: I/O error, dev sdc, sector 337167280
[   94.093297] ata3: EH complete
[  103.768054] ata3.00: exception Emask 0x0 SAct 0x383 SErr 0x0 action 0x0
[  103.768181] ata3.00: irq_stat 0x40000008
[  103.771926] ata3.00: failed command: READ FPDMA QUEUED
[  103.775720] ata3.00: cmd 60/a0:38:a6:64:1a/00:00:14:00:00/40 tag 7 ncq 81920 in
[  103.775724]          res 41/40:00:b8:64:1a/00:00:14:00:00/40 Emask 0x409 (media error) <F>
[  103.783435] ata3.00: status: { DRDY ERR }
[  103.787194] ata3.00: error: { UNC }
[  103.803202] ata3.00: configured for UDMA/133
[  103.803223] ata3: EH complete
[  113.544169] ata3.00: exception Emask 0x0 SAct 0x3ff SErr 0x0 action 0x0
[  113.547963] ata3.00: irq_stat 0x40000008
[  113.551718] ata3.00: failed command: READ FPDMA QUEUED
[  113.555431] ata3.00: cmd 60/00:30:b1:4b:1c/01:00:14:00:00/40 tag 6 ncq 131072 in
[  113.555434]          res 41/40:00:b1:4b:1c/00:00:14:00:00/40 Emask 0x409 (media error) <F>
[  113.563023] ata3.00: status: { DRDY ERR }
[  113.566795] ata3.00: error: { UNC }
[  113.582827] ata3.00: configured for UDMA/133
[  113.582854] ata3: EH complete
[  121.212779] ata3.00: exception Emask 0x0 SAct 0x2ec SErr 0x0 action 0x0
[  121.216600] ata3.00: irq_stat 0x40000008
[  121.220365] ata3.00: failed command: READ FPDMA QUEUED
[  121.224085] ata3.00: cmd 60/00:18:b1:4b:1c/01:00:14:00:00/40 tag 3 ncq 131072 in
[  121.224089]          res 41/40:00:b1:4b:1c/00:00:14:00:00/40 Emask 0x409 (media error) <F>
[  121.231697] ata3.00: status: { DRDY ERR }
[  121.235483] ata3.00: error: { UNC }
[  121.251523] ata3.00: configured for UDMA/133
[  121.251545] ata3: EH complete
[  126.387714] ata3.00: exception Emask 0x0 SAct 0x18 SErr 0x0 action 0x0
[  126.391549] ata3.00: irq_stat 0x40000008
[  126.395337] ata3.00: failed command: READ FPDMA QUEUED
[  126.399075] ata3.00: cmd 60/00:20:b1:4b:1c/01:00:14:00:00/40 tag 4 ncq 131072 in
[  126.399079]          res 41/40:00:b1:4b:1c/00:00:14:00:00/40 Emask 0x409 (media error) <F>
[  126.406723] ata3.00: status: { DRDY ERR }
[  126.410526] ata3.00: error: { UNC }
[  126.426586] ata3.00: configured for UDMA/133
[  126.426603] ata3: EH complete
[  131.441276] ata3.00: exception Emask 0x0 SAct 0x3 SErr 0x0 action 0x0
[  131.445122] ata3.00: irq_stat 0x40000008
[  131.448922] ata3.00: failed command: READ FPDMA QUEUED
[  131.452674] ata3.00: cmd 60/00:00:b1:4b:1c/01:00:14:00:00/40 tag 0 ncq 131072 in
[  131.452679]          res 41/40:00:b1:4b:1c/00:00:14:00:00/40 Emask 0x409 (media error) <F>
[  131.460341] ata3.00: status: { DRDY ERR }
[  131.464147] ata3.00: error: { UNC }
[  131.480178] ata3.00: configured for UDMA/133
[  131.480196] ata3: EH complete
[  136.759659] ata3.00: exception Emask 0x0 SAct 0x2 SErr 0x0 action 0x0
[  136.763515] ata3.00: irq_stat 0x40000008
[  136.767317] ata3.00: failed command: READ FPDMA QUEUED
[  136.771078] ata3.00: cmd 60/00:08:b1:4b:1c/01:00:14:00:00/40 tag 1 ncq 131072 in
[  136.771083]          res 41/40:00:b1:4b:1c/00:00:14:00:00/40 Emask 0x409 (media error) <F>
[  136.778749] ata3.00: status: { DRDY ERR }
[  136.782562] ata3.00: error: { UNC }
[  136.798620] ata3.00: configured for UDMA/133
[  136.798637] ata3: EH complete
[  157.271830] ata3.00: exception Emask 0x0 SAct 0xc SErr 0x0 action 0x0
[  157.275698] ata3.00: irq_stat 0x40000008
[  157.279494] ata3.00: failed command: READ FPDMA QUEUED
[  157.283253] ata3.00: cmd 60/20:10:d5:ce:20/00:00:14:00:00/40 tag 2 ncq 16384 in
[  157.283257]          res 41/40:00:d8:ce:20/00:00:14:00:00/40 Emask 0x409 (media error) <F>
[  157.290930] ata3.00: status: { DRDY ERR }
[  157.294730] ata3.00: error: { UNC }
[  157.310770] ata3.00: configured for UDMA/133
[  157.310787] ata3: EH complete
[  174.120721] ata3.00: exception Emask 0x0 SAct 0xf SErr 0x0 action 0x0
[  174.124577] ata3.00: irq_stat 0x40000008
[  174.128354] ata3.00: failed command: READ FPDMA QUEUED
[  174.132135] ata3.00: cmd 60/01:00:94:23:25/00:00:14:00:00/40 tag 0 ncq 512 in
[  174.132139]          res 41/40:00:94:23:25/00:00:14:00:00/40 Emask 0x409 (media error) <F>
[  174.139715] ata3.00: status: { DRDY ERR }
[  174.143496] ata3.00: error: { UNC }
[  174.159521] ata3.00: configured for UDMA/133
[  174.159541] ata3: EH complete
[  181.436255] ata3.00: exception Emask 0x0 SAct 0xf SErr 0x0 action 0x0
[  181.440102] ata3.00: irq_stat 0x40000008
[  181.443845] ata3.00: failed command: READ FPDMA QUEUED
[  181.447621] ata3.00: cmd 60/20:00:a1:53:25/00:00:14:00:00/40 tag 0 ncq 16384 in
[  181.447625]          res 41/40:00:a8:53:25/00:00:14:00:00/40 Emask 0x409 (media error) <F>
[  181.455184] ata3.00: status: { DRDY ERR }
[  181.458955] ata3.00: error: { UNC }
[  181.474971] ata3.00: configured for UDMA/133
[  181.474991] ata3: EH complete
[  186.434453] ata3.00: exception Emask 0x0 SAct 0xc SErr 0x0 action 0x0
[  186.438271] ata3.00: irq_stat 0x40000008
[  186.442016] ata3.00: failed command: READ FPDMA QUEUED
[  186.445765] ata3.00: cmd 60/20:18:a1:53:25/00:00:14:00:00/40 tag 3 ncq 16384 in
[  186.445769]          res 41/40:00:a8:53:25/00:00:14:00:00/40 Emask 0x409 (media error) <F>
[  186.453333] ata3.00: status: { DRDY ERR }
[  186.457099] ata3.00: error: { UNC }
[  186.473103] ata3.00: configured for UDMA/133
[  186.473117] ata3: EH complete
[  191.212173] ata3.00: exception Emask 0x0 SAct 0x3f SErr 0x0 action 0x0
[  191.215971] ata3.00: irq_stat 0x40000008
[  191.219739] ata3.00: failed command: READ FPDMA QUEUED
[  191.223496] ata3.00: cmd 60/20:00:a1:53:25/00:00:14:00:00/40 tag 0 ncq 16384 in
[  191.223499]          res 41/40:00:a8:53:25/00:00:14:00:00/40 Emask 0x409 (media error) <F>
[  191.231291] ata3.00: status: { DRDY ERR }
[  191.235194] ata3.00: error: { UNC }
[  191.251331] ata3.00: configured for UDMA/133
[  191.251348] ata3: EH complete
[  213.765822] ata3.00: exception Emask 0x0 SAct 0xf0 SErr 0x0 action 0x0
[  213.769662] ata3.00: irq_stat 0x40000008
[  213.773417] ata3.00: failed command: READ FPDMA QUEUED
[  213.777174] ata3.00: cmd 60/00:28:87:b1:2b/01:00:14:00:00/40 tag 5 ncq 131072 in
[  213.777179]          res 41/40:00:58:b2:2b/00:00:14:00:00/40 Emask 0x409 (media error) <F>
[  213.784747] ata3.00: status: { DRDY ERR }
[  213.788530] ata3.00: error: { UNC }
[  213.804549] ata3.00: configured for UDMA/133
[  213.804569] ata3: EH complete
[  221.301852] ata3.00: exception Emask 0x0 SAct 0x106 SErr 0x0 action 0x0
[  221.305702] ata3.00: irq_stat 0x40000008
[  221.309470] ata3.00: failed command: READ FPDMA QUEUED
[  221.313235] ata3.00: cmd 60/f0:40:75:79:2d/00:00:14:00:00/40 tag 8 ncq 122880 in
[  221.313240]          res 41/40:00:e0:79:2d/00:00:14:00:00/40 Emask 0x409 (media error) <F>
[  221.320820] ata3.00: status: { DRDY ERR }
[  221.324609] ata3.00: error: { UNC }
[  221.340625] ata3.00: configured for UDMA/133
[  221.340644] ata3: EH complete
[  221.732171] ata3.00: exception Emask 0x0 SAct 0x7 SErr 0x0 action 0x0
[  221.735986] ata3.00: irq_stat 0x40000008
[  221.739755] ata3.00: failed command: READ FPDMA QUEUED
[  221.743526] ata3.00: cmd 60/f0:00:75:79:2d/00:00:14:00:00/40 tag 0 ncq 122880 in
[  221.743529]          res 41/40:00:e0:79:2d/00:00:14:00:00/40 Emask 0x409 (media error) <F>
[  221.751383] ata3.00: status: { DRDY ERR }
[  221.755300] ata3.00: error: { UNC }
[  221.771436] ata3.00: configured for UDMA/133
[  221.771450] ata3: EH complete
[  222.372149] ata3.00: exception Emask 0x0 SAct 0xf SErr 0x0 action 0x0
[  222.375973] ata3.00: irq_stat 0x40000008
[  222.379751] ata3.00: failed command: READ FPDMA QUEUED
[  222.383659] ata3.00: cmd 60/f0:10:75:79:2d/00:00:14:00:00/40 tag 2 ncq 122880 in
[  222.383662]          res 41/40:00:e0:79:2d/00:00:14:00:00/40 Emask 0x409 (media error) <F>
[  222.391281] ata3.00: status: { DRDY ERR }
[  222.395085] ata3.00: error: { UNC }
[  222.411124] ata3.00: configured for UDMA/133
[  222.411143] ata3: EH complete
[  222.901776] ata3.00: exception Emask 0x0 SAct 0x1f SErr 0x0 action 0x0
[  222.905623] ata3.00: irq_stat 0x40000008
[  222.909534] ata3.00: failed command: READ FPDMA QUEUED
[  222.913453] ata3.00: cmd 60/f0:08:75:79:2d/00:00:14:00:00/40 tag 1 ncq 122880 in
[  222.913458]          res 41/40:00:e0:79:2d/00:00:14:00:00/40 Emask 0x409 (media error) <F>
[  222.921343] ata3.00: status: { DRDY ERR }
[  222.925290] ata3.00: error: { UNC }
[  222.941449] ata3.00: configured for UDMA/133
[  222.941465] ata3: EH complete
[  223.607953] ata3.00: exception Emask 0x0 SAct 0xf SErr 0x0 action 0x0
[  223.611826] ata3.00: irq_stat 0x40000008
[  223.615625] ata3.00: failed command: READ FPDMA QUEUED
[  223.619421] ata3.00: cmd 60/f0:18:75:79:2d/00:00:14:00:00/40 tag 3 ncq 122880 in
[  223.619426]          res 41/40:00:e0:79:2d/00:00:14:00:00/40 Emask 0x409 (media error) <F>
[  223.627067] ata3.00: status: { DRDY ERR }
[  223.630881] ata3.00: error: { UNC }
[  223.646934] ata3.00: configured for UDMA/133
[  223.646954] ata3: EH complete
[  224.060343] ata3.00: exception Emask 0x0 SAct 0xf SErr 0x0 action 0x0
[  224.064213] ata3.00: irq_stat 0x40000008
[  224.068138] ata3.00: failed command: READ FPDMA QUEUED
[  224.072078] ata3.00: cmd 60/f0:00:75:79:2d/00:00:14:00:00/40 tag 0 ncq 122880 in
[  224.072083]          res 41/40:00:e0:79:2d/00:00:14:00:00/40 Emask 0x409 (media error) <F>
[  224.079990] ata3.00: status: { DRDY ERR }
[  224.083933] ata3.00: error: { UNC }
[  224.100103] ata3.00: configured for UDMA/133
[  224.100122] sd 2:0:0:0: [sdc] Unhandled sense code
[  224.100127] sd 2:0:0:0: [sdc]  Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
[  224.100134] sd 2:0:0:0: [sdc]  Sense Key : Medium Error [current] [descriptor]
[  224.100143] Descriptor sense data with sense descriptors (in hex):
[  224.100148]         72 03 11 04 00 00 00 0c 00 0a 80 00 00 00 00 00
[  224.100171]         14 2d 79 e0
[  224.100184] sd 2:0:0:0: [sdc]  Add. Sense: Unrecovered read error - auto reallocate failed
[  224.100194] sd 2:0:0:0: [sdc] CDB: Read(10): 28 00 14 2d 79 75 00 00 f0 00
[  224.100216] end_request: I/O error, dev sdc, sector 338524640
[  224.104200] ata3: EH complete
[  231.111060] ata3.00: exception Emask 0x0 SAct 0x7f SErr 0x0 action 0x0
[  231.114933] ata3.00: irq_stat 0x40000008
[  231.118737] ata3.00: failed command: READ FPDMA QUEUED
[  231.122498] ata3.00: cmd 60/00:08:a7:94:2e/01:00:14:00:00/40 tag 1 ncq 131072 in
[  231.122502]          res 41/40:00:08:95:2e/00:00:14:00:00/40 Emask 0x409 (media error) <F>
[  231.130200] ata3.00: status: { DRDY ERR }
[  231.134029] ata3.00: error: { UNC }
[  231.150130] ata3.00: configured for UDMA/133
[  231.150154] ata3: EH complete
[  252.186164] ata3.00: exception Emask 0x0 SAct 0x18f SErr 0x0 action 0x0
[  252.190042] ata3.00: irq_stat 0x40000008
[  252.193851] ata3.00: failed command: READ FPDMA QUEUED
[  252.197618] ata3.00: cmd 60/00:00:71:b3:33/01:00:14:00:00/40 tag 0 ncq 131072 in
[  252.197623]          res 41/40:00:71:b3:33/00:00:14:00:00/40 Emask 0x409 (media error) <F>
[  252.205325] ata3.00: status: { DRDY ERR }
[  252.209163] ata3.00: error: { UNC }
[  252.225258] ata3.00: configured for UDMA/133
[  252.225280] ata3: EH complete
[  257.372125] ata3.00: exception Emask 0x0 SAct 0x31 SErr 0x0 action 0x0
[  257.375983] ata3.00: irq_stat 0x40000008
[  257.379813] ata3.00: failed command: READ FPDMA QUEUED
[  257.383595] ata3.00: cmd 60/00:28:71:b3:33/01:00:14:00:00/40 tag 5 ncq 131072 in
[  257.383599]          res 41/40:00:71:b3:33/00:00:14:00:00/40 Emask 0x409 (media error) <F>
[  257.391325] ata3.00: status: { DRDY ERR }
[  257.395165] ata3.00: error: { UNC }
[  257.411259] ata3.00: configured for UDMA/133
[  257.411278] ata3: EH complete</code>

**Comment by behlendorf** [comment] 2016-07-15 23:45
Closing as duplicate of #4149.

**Closed by behlendorf** 2016-07-15 23:45 UTC
Labels: Bug - Trivial, Documentation, zed
