### ISSUE TITLE
auto-unmount race over NFS

### ISSUE THREAD

**Issue by danBhentschel** [zfsonlinux/zfs#3794] opened 2015-09-17 15:52 UTC
### Pastebin of the `dmesg` error: http://pastebin.com/cTVbu2kY

    $ uname -a
    Linux zfsman 3.13.0-63-generic #103-Ubuntu SMP Fri Aug 14 21:42:59 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Running in a VM under Xen, with ZFS 0.6.5-1:

    $ apt --installed list | grep -e zfs -e spl

    dkms/trusty,now 2.2.0.3-1.1ubuntu5.14.04.1+zfs10~trusty all [installed,upgradable to: 2.2.0.3-1.1ubuntu5.14.04.1+zfs10~trusty]
    kmod-spl-3.13.0-54-generic/now 0.6.4-8 amd64 [installed,local]
    libzfs2/trusty,now 0.6.5-1~trusty amd64 [installed,automatic]
    mountall/trusty,now 2.53-zfs1 amd64 [installed]
    spl/trusty,now 0.6.5-1~trusty amd64 [installed]
    spl-dkms/trusty,now 0.6.5-1~trusty all [installed,automatic]
    ubuntu-zfs/trusty,now 8~trusty amd64 [installed]
    zfs-dkms/trusty,now 0.6.5-1~trusty amd64 [installed]
    zfs-doc/trusty,now 0.6.5-1~trusty amd64 [installed,automatic]
    zfsutils/trusty,now 0.6.5-1~trusty amd64 [installed]

Rebooted and came up just fine. Here's `zpool status` after reboot:

      pool: scratch
     state: DEGRADED
    status: One or more devices could not be used because the label is missing or
            invalid.  Sufficient replicas exist for the pool to continue
            functioning in a degraded state.
    action: Replace the device using 'zpool replace'.
       see: http://zfsonlinux.org/msg/ZFS-8000-4J
      scan: scrub repaired 1.77G in 1h13m with 0 errors on Thu Sep 17 01:13:49 2015
    config:
    
            NAME                      STATE     READ WRITE CKSUM
            scratch                   DEGRADED     0     0     0
              raidz2-0                DEGRADED     0     0     0
                xvdd                  ONLINE       0     0     0
                xvds                  ONLINE       0     0     0
                xvdt                  ONLINE       0     0     0
                13461005652690450481  UNAVAIL      0     0     0  was /dev/xvdg
    
    errors: No known data errors
    
      pool: storage
     state: ONLINE
    status: Some supported features are not enabled on the pool. The pool can
            still be used, but some features are unavailable.
    action: Enable all features using 'zpool upgrade'. Once this is done,
            the pool may no longer be accessible by software that does not support
            the features. See zpool-features(5) for details.
      scan: scrub repaired 0 in 28h10m with 0 errors on Thu Sep 17 04:10:20 2015
    config:
    
            NAME        STATE     READ WRITE CKSUM
            storage     ONLINE       0     0     0
              raidz3-0  ONLINE       0     0     0
                xvde    ONLINE       0     0     0
                xvdu    ONLINE       0     0     0
                xvdk    ONLINE       0     0     0
                xvdf    ONLINE       0     0     0
                xvdh    ONLINE       0     0     0
                xvdr    ONLINE       0     0     0
                xvdi    ONLINE       0     0     0
                xvdm    ONLINE       0     0     0
                xvdj    ONLINE       0     0     0
                xvdl    ONLINE       0     0     0
            logs
              mirror-1  ONLINE       0     0     0
                xvdn    ONLINE       0     0     0
                xvdo    ONLINE       0     0     0
            cache
              xvdq      ONLINE       0     0     0
    
    errors: No known data errors

Before upgrading to 0.6.5, I had been running the same two pools error-free since June. The xvdg drive in the `scratch` pool was removed several days ago (shortly before upgrading to 0.6.5) after it died a horrible death. I don't think they're related, but mention it for completeness' sake.

 - dan

**Comment by danBhentschel** [comment] 2015-09-17 17:41
More info: This is likely related to accessing snapshots via NFS. I started doing that for the first time today, and the system crashed again just a few minutes ago. I will avoid snapshots via NFS for now and see if things seem more stable.

 - dan

**Comment by erkston** [comment] 2015-09-18 18:46
I'm also getting lockups on seemingly any access after updating to 0.6.5.  The system completely locks up until a reboot, after which it seems fine until accessed again.  The error doesn't seem to make it to syslog, but I grabbed a pretty readable photo of the console: http://i.imgur.com/ALLkLPY.jpg

```

        NAME        STATE     READ WRITE CKSUM
        hermes      ONLINE       0     0     0
          raidz2-0  ONLINE       0     0     0
            sdc     ONLINE       0     0     0
            sdd     ONLINE       0     0     0
            sde     ONLINE       0     0     0
            sdf     ONLINE       0     0     0
            sdg     ONLINE       0     0     0
            sdh     ONLINE       0     0     0


$ uname -a

Linux hermes 3.16.0-49-generic #65~14.04.1-Ubuntu SMP Wed Sep 9 10:03:23 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ apt --installed list | grep -e zfs -e spl

dkms/trusty,now 2.2.0.3-1.1ubuntu5.14.04.1+zfs10~trusty all [installed,upgradable to: 2.2.0.3-1.1ubuntu5.14.04.1+zfs10~trusty]
libzfs2/trusty,now 0.6.5-1~trusty amd64 [installed,automatic]
mountall/trusty,now 2.53-zfs1 amd64 [installed]
spl/trusty,now 0.6.5-1~trusty amd64 [installed]
spl-dkms/trusty,now 0.6.5-1~trusty all [installed,automatic]
ubuntu-zfs/trusty,now 8~trusty amd64 [installed]
zfs-dkms/trusty,now 0.6.5-1~trusty amd64 [installed]
zfs-doc/trusty,now 0.6.5-1~trusty amd64 [installed,automatic]
zfsutils/trusty,now 0.6.5-1~trusty amd64 [installed]
```

I also found this issue which could be related (though it's from before the 0.6.5 release: https://github.com/zfsonlinux/zfs/issues/3487

**Comment by gdevenyi** [comment] 2015-09-21 21:37
I see i/o errors in that OOPS, are you sure your disks and/or SATA/SAS connectivity is okay?

**Comment by danBhentschel** [comment] 2015-09-22 12:55
I assume that you are talking about the very first line of the log? I understand why you would bring it up, and I included that line in case it is relevant to the failure. To answer your specific question, I have seen periodic I/O errors for that specific drive. It's a 6TB WD Red, and I'm holding off on replacing it because I'm lazy, and the errors only happen every couple of weeks. However, consider the following:

1) That I/O error occurred more than 48 hours (according to the timestamp) before the CPU lockup.

2) I have been seeing periodic I/O errors on that drive for months without any lockup issues. I/O errors are expected, and par for the course when working with a large number of large disks. I have had many drive failures over the years. I would not expect my system to come to a screeching halt for an I/O error.

3) The first several stack traces in the log are related to either umount or nfsd.

4) Accessing snapshots over NFS is a new feature in 0.6.5

5) My machine crashed twice in a single day, and both crashes were while I was accessing snapshots via NFS.

6) I have refrained from accessing snapshots via NFS, and there have been no further incidents in the past 5 days.

It's not conclusive, but I really believe that there might be some stability issues with accessing snapshots via NFS on 0.6.5. It might be specific to my environment and how I am using the system. It might even be related to I/O issues in conjunction with the new code. Either way, I think there is a software problem to discover, and hence the bug report.

**Comment by behlendorf** [comment] 2015-09-23 20:09
@danBhentschel based on the dmesg output you posted this absolutely looks like a bug in snapshot access via NFS code.  Specifically, the BUG is caused by the existence of a dentry which should not exist because the umount should have already removed them all.  I suspect it's possible that an NFS access which occurs concurrently with an unmount can case a new dentry to be created _after_ the unmount has removed them but _before_ the sanity check your hitting.

```
BUG: Dentry ffff8800658ba3c0{i=6ee,n=Robots.vob}  still in use (1) [unmount of zfs zfs]
```

I've opened pull request #3823 with a patch which should make this race more unlikely and is a good optimization.  But it doesn't strictly make this impossible.

Aside from this crash did you observe any other issues with accessing snapshots over NFS?  This is still a new feature so I'm very curious how it's working for real workloads.

**Comment by danBhentschel** [comment] 2015-09-24 12:45
Thank you for your reply. Other than the lockups, everything worked well. I didn't have any problems with enabling or accessing snapshots. It just worked. I found it very handy. I tend to use snapshots extensively, and it is very convenient to be able to access my snapshots from the system I am working on, rather than logging into my ZFS host every time I want to access old data.

Thanks for your continued efforts. I look forward to when I can use this feature.

 - dan

**Comment by behlendorf** [comment] 2015-12-30 23:05
This has been resolved in master and the release branch.

**Closed by behlendorf** 2015-12-30 23:05 UTC
Labels: Bug - Minor
