### ISSUE TITLE
zfs get lused gives wrong value for snapshots

### ISSUE THREAD

**Issue by ggzengel** [zfsonlinux/zfs#3962] opened 2015-10-27 18:10 UTC
> logicalused
>           The amount of space that is "logically" consumed by this dataset and all its descendents.  See the used property.  The logical space ignores the effect of the  compression  and  copies
>           properties, giving a quantity closer to the amount of data that applications see.  However, it does include space consumed by metadata.

That means: lused > used
But lused is always zero. It should be greater than "used" or give a minus.

```
 zfs list -o name,used,lused,ratio,refratio
NAME                                           USED  LUSED  RATIO  REFRATIO
zpool1                                        25.3T  30.1T  1.41x     1.00x
zpool1/samba                                  25.3T  30.1T  1.41x     1.00x
zpool1/samba/imagepool                        25.3T  30.1T  1.41x     1.00x
zpool1/samba/imagepool/imagepool1             6.50T  7.54T  1.35x     1.35x
zpool1/samba/imagepool/imagepool1@stage2      1.20G      0  1.31x     1.31x
zpool1/samba/imagepool/imagepool1@stage3      4.31G      0  1.33x     1.33x
zpool1/samba/imagepool/imagepool1@stage4      7.09G      0  1.34x     1.34x
zpool1/samba/imagepool/imagepool1@stage5      3.15G      0  1.35x     1.35x
zpool1/samba/imagepool/imagepool1@stage6      4.85G      0  1.35x     1.35x
zpool1/samba/imagepool/imagepool1@stage7      14.9G      0  1.35x     1.35x
zpool1/samba/imagepool/imagepool1@stage8      14.9G      0  1.35x     1.35x
zpool1/samba/imagepool/imagepool1@first_pass  15.0G      0  1.35x     1.35x
zpool1/samba/imagepool/imagepool2             9.24T  10.8T  1.38x     1.38x
zpool1/samba/imagepool/imagepool2@STAGE1      8.03G      0  1.33x     1.33x
zpool1/samba/imagepool/imagepool2@STAGE2      11.7G      0  1.34x     1.34x
zpool1/samba/imagepool/imagepool2@STAGE3      14.6G      0  1.35x     1.35x
zpool1/samba/imagepool/imagepool2@STAGE4      16.9G      0  1.37x     1.37x
zpool1/samba/imagepool/imagepool2@STAGE5      19.8G      0  1.39x     1.39x
zpool1/samba/imagepool/imagepool2@first_pass  22.2G      0  1.38x     1.38x
zpool1/samba/imagepool/imagepool3             6.61T  8.11T  1.49x     1.49x
zpool1/samba/imagepool/imagepool3@STAGE1      1.16G      0  1.43x     1.43x
zpool1/samba/imagepool/imagepool3@STAGE2      2.52G      0  1.42x     1.42x
zpool1/samba/imagepool/imagepool3@STAGE3      4.63G      0  1.43x     1.43x
zpool1/samba/imagepool/imagepool3@STAGE4      6.86G      0  1.43x     1.43x
zpool1/samba/imagepool/imagepool3@STAGE6      9.84G      0  1.46x     1.46x
zpool1/samba/imagepool/imagepool3@STAGE7      12.6G      0  1.49x     1.49x
zpool1/samba/imagepool/imagepool3@STAGE8      16.1G      0  1.49x     1.49x
zpool1/samba/imagepool/imagepool3@first_pass  16.7G      0  1.49x     1.49x
zpool1/samba/imagepool/imagepool4             2.96T  3.60T  1.47x     1.47x
zpool1/samba/imagepool/imagepool4@STAGE1      2.71G      0  1.42x     1.42x
zpool1/samba/imagepool/imagepool4@STAGE2      5.59G      0  1.47x     1.47x
zpool1/samba/imagepool/imagepool4@first_pass  7.40G      0  1.47x     1.47x
```

**Comment by rsyring** [comment] 2017-04-14 20:10
Same issue reported in #5461.

**Comment by loli10K** [comment] 2017-08-18 12:49
Closing as duplicate of https://github.com/zfsonlinux/zfs/issues/5461

**Closed by loli10K** 2017-08-18 12:49 UTC
