### ISSUE TITLE
Provide a way to recover from "permanent errors"

### ISSUE THREAD

**Issue by devsk** [zfsonlinux/zfs#5528] opened 2016-12-25 07:31 UTC
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  Gentoo
Distribution Version    | 
Linux Kernel                 | 4.9.0
Architecture                 | x86_64
ZFS Version                  | 0.7.0-rc2_83_gf2d8bdc6
SPL Version                  | 0.7.0-rc2_4_gf200b83

### Describe the problem you're observing
One file in my backup pool is showing permanent errors in a snapshot. The snapshot was made 2 years ago. All previous snapshots from that point onward have that file shown as corrupt (I/O error) when accessed through .zfs folder as well.

So, out of the blue, suddenly I have this file corrupt in every snapshot I have.

### Describe how to reproduce the problem

Its not reproducible but this is second time it has hit me. The last time I hit this was in 2013 and I ended up recreating the pool.

My big worry is that if I need to replace a disk, its going to fail during resilvering and cause me to either delete all my snapshots or the whole pool itself and recreate it.

If we can have an option of correcting a specific file in all snapshots, that would be great and avoid a whole lot of pain of buying new drives, creating temporary pools, copying data back and fro. The suggestion came from another user on the list:

> A function to rewrite defective, non-reconstructable (file) data could be helpful:
>
> ZFS knows the file in question, it knows the mode how the data was written, it knows
> offset and lendth of the bad data and the checksum that would need to have.
>
> So it should be possible to feed in that file (from a backup) for ZFS to rewrite
> the defective part inplace (as the data there is currently known-bad), healing the defect.
>
> Gregor

--------------------------------------- Original email from zfs-discuss------------------
One fine day after the update to v0.6.5.8-r0-gentoo, a scrub finds a file 
which has permanent error(I guess it means that it can't correct the 
blocks in error) on a file in an old snapshot. The file is unreadable 
(Input/Output error) in all snapshots taken after that but they were 
taken in the years since.

    # zpool status -v
       pool: backup
      state: DEGRADED
    status: One or more devices has experienced an error resulting in data
             corruption.  Applications may be affected.
    action: Restore the file in question if possible.  Otherwise restore the
             entire pool from backup.
        see: http://zfsonlinux.org/msg/ZFS-8000-8A
       scan: scrub repaired 0 in 9h16m with 1 errors on Sat Dec 10 23:19:10 2016
    config:
 
             NAME                                            STATE READ
    WRITE CKSUM
             backup DEGRADED     0     0     1
               raidz2-0 DEGRADED     0     0     2
                 ata-WDC_WD4001FAEX-00MJRA0_WD-WCCxxxxxxxxx ONLINE   
    0     0     0
                 ata-ST4000VN000-1H4168_xxxx ONLINE       0     0     0
                 ata-WDC_WD4001FAEX-00MJRA0_WD-WCCxxxxxxxxx ONLINE   
    0     0     0
                 /mnt/serviio/4tbFile OFFLINE      0     0     0
 
    errors: Permanent errors have been detected in the following files:
 
    backup/zfs-backup@move_backup_to_4tb_external_sep25_2014:/Installs/clonezilla/live/filesystem.squashfs

I tried to read the file in all subsequent snapshots (using 
.zfs/snapshot folder) since Sept 2014 and its unreadable in all of them. 
I can copy the correct  file over and take snapshots and they are all 
fine. I can keep deleting snapshots and the scrub keep pointing to the 
next snapshot.

Neither of the 3 disks in there show any pending, uncorrectable or 
reallocated sectors. Overall health is fine with the disks and scrub has 
never failed on these for last any number of months I can remember (and 
from zpool history).

Any ideas? I remember I had to restore from backup (of backup in this 
case) last time I ran into this. Is there any other way? Its a pain to 
start over.

Also, I want to add a 4TB disk to replace 4tbFile but I am wondering if 
the resilver will even succeed in this state. I am afraid it will fail 
at this snapshot and it will be a waste of time.

Thanks
-devsk

**Comment by mailinglists35** [comment] 2016-12-25 11:38
please use the edit button and prefix all code/output with four spaces. you can automate this with `cat << EOF | sed 's/^/    /g'`, then paste your output, then press `ctrl-d`

**Comment by ronnyegner** [comment] 2016-12-26 08:26
Hi,

you can and should go on with the replacement. It will run. In it´s current state the pool is missing a disk.
There is a chance that the problem will go away after the disk is replaced AND a scrub has been run. I had the same problem some time ago and the pool healed itself after all missing disks were replaced and a scrub has been run.

**Comment by devsk** [comment] 2016-12-29 10:03
Resilver has completed without additional errors 3 times so far. It keeps resilvering from scratch every time I import the pool.

The resilvering does not make the original 1 error go away.

I need a way out of this. Its causing a lot of disk churn for 24 hours period.

**Comment by devsk** [comment] 2016-12-29 10:06
One more thing: deleting all my snapshots (the only way to get rid of this error) is not a good solution for me.

**Comment by gmelikov** [comment] 2016-12-30 18:24
IIRC permanent resilver usually caused by hardware problems (see #4873 for example).

Which disk resilvers? I think there may be something with it.

**Comment by devsk** [comment] 2016-12-30 20:16
I did mention that the resilver completes successfully, except for the known error with single file in the older snapshots.

>  pool: backup
> state: ONLINE
>status: One or more devices has experienced an error resulting in data
>        corruption.  Applications may be affected.
> action: Restore the file in question if possible.  Otherwise restore the
>       entire pool from backup.
>  see: http://zfsonlinux.org/msg/ZFS-8000-8A
>  scan: resilvered 2.25T in 26h24m with 1 errors on Fri Dec 30 01:02:01 2016
>config:
>
>        NAME                                            STATE     READ WRITE CKSUM
>        backup                                          ONLINE       0     0     1
>          raidz2-0                                      ONLINE       0     0     2
>            ata-WDC_WD4001FAEX-00MJRA0_WD-  ONLINE       0     0     0
>            ata-ST4000VN000-1H4168_abc             ONLINE       0     0     0
>            ata-WDC_WD4001FAEX-00MJRA0_WD-  ONLINE       0     0     0
>            ata-ST4000VN000-1H4168_xyz             ONLINE       0     0     0
>
>errors: Permanent errors have been detected in the following files:
>
>        backup/zfs-backup@move_backup_to_4tb_external_sep25_2014:/Installs/clonezilla/live/filesystem.squashfs
>
The drive that resilvers is the new one I added. It is a pretty new Seagate 4TB NAS drive model ST4000VN000-1H4168 (shown xyz above). There is nothing wrong showing in the SMART data. I have used this drive extensively and it has never failed me so far:

>ID# ATTRIBUTE_NAME          FLAGS    VALUE WORST THRESH FAIL RAW_VALUE
>  1 Raw_Read_Error_Rate     POSR--   118   100   006    -    184350472
>  3 Spin_Up_Time            PO----   094   094   000    -    0
>  4 Start_Stop_Count        -O--CK   100   100   020    -    6
>  5 Reallocated_Sector_Ct   PO--CK   100   100   010    -    0
>  7 Seek_Error_Rate         POSR--   072   060   030    -    17840492
>  9 Power_On_Hours          -O--CK   100   100   000    -    144
> 10 Spin_Retry_Count        PO--C-   100   100   097    -    0
> 12 Power_Cycle_Count       -O--CK   100   100   020    -    6
>184 End-to-End_Error        -O--CK   100   100   099    -    0
>187 Reported_Uncorrect      -O--CK   100   100   000    -    0
>188 Command_Timeout         -O--CK   100   100   000    -    0
>189 High_Fly_Writes         -O-RCK   100   100   000    -    0
>190 Airflow_Temperature_Cel -O---K   064   057   045    -    36 (Min/Max 33/40)
>191 G-Sense_Error_Rate      -O--CK   100   100   000    -    0
>192 Power-Off_Retract_Count -O--CK   100   100   000    -    5
>193 Load_Cycle_Count        -O--CK   100   100   000    -    6
>194 Temperature_Celsius     -O---K   036   043   000    -    36 (0 17 0 0 0)
>197 Current_Pending_Sector  -O--C-   100   100   000    -    0
>198 Offline_Uncorrectable   ----C-   100   100   000    -    0
>199 UDMA_CRC_Error_Count    -OSRCK   200   200   000    -    0

**Comment by devsk** [comment] 2016-12-30 20:20
Nothing reported in 'dmesg'. Its clean.

**Comment by gmelikov** [comment] 2016-12-30 20:45
> I did mention that the resilver completes successfully

My bad, you're right.

Did you see #591?

> The resivering is triggered when a vdev is offline for some length of time and then the same original vdev is brought back online. ZFS will basically resync the array updating it missing vdev to reflect any changes which were made while it was offline. It would be interesting to see the contents of zpool events.

**Comment by kernelOfTruth** [comment] 2016-12-30 21:09
I wonder how stable and production ready https://github.com/zfsonlinux/zfs/pull/5316 is which could prevent lots of spurious i/o in those kind of situations

**Comment by devsk** [comment] 2016-12-30 21:53
I think 5018 comes close to what I am seeing, except that the error is in a file in older snapshots.

**Comment by kernelOfTruth** [comment] 2016-12-30 22:18
Additionally the following comes to mind (hole_birth), not sure however if there _could_ be a connection

https://github.com/zfsonlinux/zfs/pull/5239 Rename hole_birth tunable to match OpenZFS
https://github.com/zfsonlinux/zfs/pull/5004 fix hole_birth issue #4996 and add hole_birth Test Suite 
https://github.com/zfsonlinux/zfs/pull/4754 6513 partially filled holes lose birth time
https://github.com/zfsonlinux/zfs/pull/4369 6370 ZFS send fails to transmit some holes

can't totally remember, but I'm sure it was something with snapshots, sending of snapshots and holes ...

**Comment by mailinglists35** [comment] 2016-12-30 23:45
have you tried scrubbing twice? i remember once i have had to to scrub twice to get an error cleared (scrub, export, import, scrub, export, import). but in my case it was after already deleting the affected file (it gave an error out of the blue then i recovered the file from backup)

**Comment by devsk** [comment] 2016-12-31 13:38
My pools get scrubbed every Saturday. So, it has been scrubbed many many times since I hit the issue (I waited before reporting it here, and discussed it on zfs-discuss).

**Comment by devsk** [comment] 2017-01-19 03:26
My pool continues to resilver 10TB of data on every import.

Can someone please tell me how to abort a resilver? I don't care about that file in any of those snapshots. But I do care about those snapshots.

**Comment by ronnyegner** [comment] 2017-01-19 05:32
Then your only option may be a zfs send, re-create the pool and zfs receive. With no guarantee that this will work.

**Comment by devsk** [comment] 2017-01-19 06:04
Complete FS restore from backup is something I used to do with BTRFS...:-) This is ZFS. There must be something I can do, like tell ZFS to shut up about this pool and not resilver on every import.

Mentally, I am not able to accept the fact that backing up and restoring such a large pool is the only option here. For such a simple thing as ignoring 1 file or aborting resilver.

**Comment by ronnyegner** [comment] 2017-01-19 09:32
There are permanent errors in the file due to some unrecoverable errors happened in the past. The only way to get rid of that is to drop the snapshots and maybe the file as well. After that the pool should be clean as well. Or live with the fact that a resilver happens every time during import. 

With BTRFS your whole pool would be already toast...

**Comment by behlendorf** [comment] 2017-01-19 21:42
> There must be something I can do, like tell ZFS to shut up about this pool and not resilver on every import.

My best guess as to what's likely happening is the resilver at import time is being triggered by the existence of a dirty time log (DTL).  The DTL is normally used to track times (txgs) when a vdev was offline so it can be efficiently rebuild when brought back online.  You may have a DTL log for that vdev which is never getting removed because it can't fully rebuild the space due to that persistent error.

The next time you're able to export the pool could you run `zdb -dddddd <pool>` and post the "Dirty time logs" section of the output.  That should let us inspect the DTL.  You can run this online if taking the pool offline briefly isn't possible.  But the advantage of doing it offline is everything will be in a stable state for easier inspection.

Based on what we see in the DTL was can determine what the best way for ZFS to handle this is.

**Comment by devsk** [comment] 2017-01-19 22:59
Brian, sure. I am generate that output for you after the export at the next opportunity.

**Comment by devsk** [comment] 2017-01-21 19:11
I did zpool export of the pool and ran the zdb command above. It says 

    # zdb -dddddd backup
    zdb: can't open 'backup': No such file or directory

**Comment by behlendorf** [comment] 2017-01-21 21:57
@devsk since the pool is exported and apparently not in the cache file you'll need to add the `-e` option.  From `zdb(8)`.

```
       -e [-p path]...

           Operate on an exported pool, not present  in  /etc/zfs/zpool.cache.
           The  -p  flag  specifies  the  path  under  which devices are to be
           searched.
```

**Comment by devsk** [comment] 2017-01-22 06:25
Oh well...ran it like:

# time zdb -dddddd -e -p /dev/disk/by-id backup &>/var/log/zbd.backup
^C
real    397m34.869s

It created a 30GB file after 397 mins and I had to stop it with a Ctrl-C because it was not finishing.

Ran it with only '-dd' and still the same.

What happened there?

**Comment by behlendorf** [comment] 2017-01-23 21:20
It was working, you have very large pool with a huge number of objects.  Sorry, I should have mentioned that it could potentially take a long time to run.  Can you check if the generated log contains the "Dirty time logs:" section, and if so post it in the issue.  It _should_ be fairly small.

**Comment by devsk** [comment] 2017-01-24 01:24
So, it can take more than 7hours? OK, in that case I need to find a place where I have more than 30 GB disk space. The log can't be dumped on rootfs.

The 30 GB it had generated, "grep -i dirty" did not return anything on that. Let me rerun it.

**Comment by behlendorf** [comment] 2017-01-24 02:36
Well the trouble is there's no existing way to dump just that information. Which would be quick.  Rather than asking you to to take things down again for that long let me see about extending zdb to get just  that info.

**Comment by dweeezil** [comment] 2017-01-24 13:59
@devsk You can build my [dweeezil:zdb](https://github.com/dweeezil/zfs/tree/zdb) branch and use ```zdb -ii``` to only dump the DTLs.  I figured this was another good one to add to the other set of hacks in there.  As a reminder, you do _not_ need to install, but instead can simply run from the build tree as ```cmd/zdb/zdb``` after compiling.

**Comment by devsk** [comment] 2017-01-25 01:37
OK, 24 hours and 107GB dumped and still not finishing. I think there is something wrong for sure. It takes typically 9hrs to scrub the whole pool.

**Comment by dweeezil** [comment] 2017-01-25 03:03
@devsk You should interrupt the long-running ```zdb``` and build my hacked version.  Then you can use ```zdb -ii``` and get the DTL pretty much immediately.  A 6-d zdb is going to produce an insane amount of output for a large pool.

**Comment by devsk** [comment] 2017-01-25 05:06
@dweeezil: Any reason why your changes are not pushed to master yet? It looks like its not something that will affect ZFS functionality (unless the users have built apps around zdb).

**Comment by devsk** [comment] 2017-01-26 03:02
@dweeezil : does your branch not build against the master? I am running ZFS from master and I had trouble building your branch. configure failed with:

```
   /home/devsk/Installs/zfs-dweeezil/build/conftest.c:104:33: error: passing argument 2 of 'blk_queue_make_request' from incompatible pointer type [-Werror=incompatible-pointer-types]
    blk_queue_make_request(NULL, &make_request);
                                 ^
    In file included from /home/devsk/Installs/zfs-dweeezil/build/conftest.c:93:0:
./include/linux/blkdev.h:984:13: note: expected 'blk_qc_t (*)(struct request_queue *, struct bio *) {aka unsigned int (*)(struct request_queue *, struct bio *)}' but argument is of type 'void (*)(struct request_queue *, struct bio *)'
 extern void blk_queue_make_request(struct request_queue *, make_request_fn *);
             ^~~~~~~~~~~~~~~~~~~~~~
    cc1: all warnings being treated as errors
    make[1]: *** [scripts/Makefile.build:300: /home/devsk/Installs/zfs-dweeezil/build/conftest.o] Error 1
    make: *** [Makefile:1490: _module_/home/devsk/Installs/zfs-dweeezil/build] Error 2
    configure:30045: $? = 2
```

**Comment by behlendorf** [comment] 2017-01-26 18:32
@dweeezil I'd love to see the most useful of these `zdb` enhancements applied to master.

@devsk the easiest way to build this will be to just build the user space utilities like `zdb`.  Then you can eliminate any spl and kernel dependencies which might result in a build failure.

```
./configure --with-config=user && make
```

**Comment by devsk** [comment] 2017-01-26 19:22
Thanks Brian. I could build it but it generates the same output as the zdb I have in /usr:

```
26.01-11:10:45 root@localhost ~/Installs/zfs-dweeezil/cmd/zdb 
# time ./zdb -v -ii -e -p /dev/disk/by-id backup &>~/zbd.backup                        

real    0m2.225s
user    0m0.025s
sys     0m0.166s

26.01-11:10:56 root@localhost ~/Installs/zfs-dweeezil/cmd/zdb 
# vi ~/zbd.backup

26.01-11:16:19 root@localhost ~/Installs/zfs-dweeezil/cmd/zdb 
# cd /

26.01-11:16:20 root@localhost /  
# time zdb -v -ii -e -p /dev/disk/by-id backup &>~/zbd.backup.old

real    0m1.585s
user    0m0.028s
sys     0m0.133s

26.01-11:16:29 root@localhost /  
# vi ~/zbd.backup.old

26.01-11:16:37 root@localhost /  
# diff ~/zbd.backup.old ~/zbd.backup    
76c76
< Verified large_blocks feature refcount of 0 is correct
---
> Verified large_blocks feature refcount is correct (0)
```

what gives?

**Comment by behlendorf** [comment] 2017-01-26 21:09
@devsk at a minimum you should get the line "Dirty time logs:".  For example, from an imported root pool.

```
$ sudo ./cmd/zdb/zdb -ii rpool

Dirty time logs:

	rpool [DTL-required]
	    /dev/sdd1 [DTL-required]
```

**Comment by devsk** [comment] 2017-01-26 21:39
Brian: as you can see I ran the command as root and from the cmd/zdb folder. For an exported pool, it does not show any lines in the output containing Dirty or DTL.

May be I need to run it on the imported pool?

If I import, it will take a while (24 hrs) before it settles down with resilvering. Not sure if I should wait for that to settle before getting DTL info.

One thing towards the end of the output of 77 lines, which struck me odd was:

```
...
Verified large_blocks feature refcount is correct (0)
space map refcount mismatch: expected 209 != actual 208
```
Is that refcount mismatch relevant?

I will try with imported pool and see if I can get DTL info. Its strange that zdb -ii does not dump that info for an exported pool.

**Comment by dweeezil** [comment] 2017-01-26 21:50
@devsk Don't use ```-v```.  It causes the new ```-ii``` detection to be bypassed (I think).  For reference:
```
root@zfs-dev:/home/dweeezil/src/zfs# cmd/zdb/zdb -ii -e -p /dev/disk/by-id tank

Dirty time logs:

	tank [DTL-required]
	    raidz [DTL-required]
	        /dev/disk/by-id/ata-ST1000DM003-1CH162_S1DJ1PWQ-part1 [DTL-expendable]
	        /dev/disk/by-id/ata-ST1000DM003-1CH162_S1DJ1RTS-part1 [DTL-expendable]
	        /dev/disk/by-id/ata-ST1000DM003-1CH162_Z1DB5S8Y-part1 [DTL-expendable]
	        /dev/disk/by-id/ata-ST1000DM003-1CH162_Z1DB69GQ-part1 [DTL-expendable]
	        /dev/disk/by-id/ata-ST1500DM003-1CH16G_Z1E382F9-part1 [DTL-expendable]
...
```

@behlendorf Yes, I'll have to go through this set of hacks and see which ones would be useful to get pushed upstream.

**Comment by devsk** [comment] 2017-01-26 21:55
Strange!!! I ran the same command (from the newly built dweezil branch) on another imported pool. I don't see anything for Dirty or DTL in the output.

zdb has no version option but I cloned yesterday. I am running zol from master as of yesterday night.

```
26.01-13:50:30 root@localhost ~/Installs/zfs-dweeezil/cmd/zdb 
# ./zdb -ii mydata &>~/zbd.mydata

26.01-13:51:43 root@localhost ~/Installs/zfs-dweeezil/cmd/zdb 
# grep -i dtl ~/zbd.mydata

26.01-13:51:54 root@localhost ~/Installs/zfs-dweeezil/cmd/zdb 
# grep -i dirty ~/zbd.mydata

26.01-13:51:59 root@localhost ~/Installs/zfs-dweeezil/cmd/zdb 
# ./zdb -ii -e -p /dev/disk/by-id backup &>~/zbd.backup

26.01-13:52:27 root@localhost ~/Installs/zfs-dweeezil/cmd/zdb 
# grep -i dirty ~/zbd.ba
zbd.backup      zbd.backup.old  

26.01-13:52:27 root@localhost ~/Installs/zfs-dweeezil/cmd/zdb 
# grep -i dirty ~/zbd.backup

26.01-13:52:33 root@localhost ~/Installs/zfs-dweeezil/cmd/zdb 
# grep -i dtl ~/zbd.backup

26.01-13:52:38 root@localhost ~/Installs/zfs-dweeezil/cmd/zdb
```
mydata is imported and backup is exported.

**Comment by dweeezil** [comment] 2017-01-27 16:21
@devsk Is there _anything_ in your ```zdb.mydata``` files?  Is ```zdb``` even opening the pool?

**Comment by devsk** [comment] 2017-01-27 17:33
This is all of zbd.mydata (I misspelled but grep is on correct name):

`
Dataset mos [META], ID 0, cr_txg 4, 48.6M, 290 objects
Dataset mydata/Photos@before_we_move_to_bcache [ZPL], ID 199, cr_txg 4987070, 78.7G, 11762 objects
Dataset mydata/Photos@full_pool_restore [ZPL], ID 103, cr_txg 649, 47.6G, 6689 objects
Dataset mydata/Photos@Sep2nd2013 [ZPL], ID 60, cr_txg 2846486, 73.8G, 12795 objects
Dataset mydata/Photos [ZPL], ID 99, cr_txg 455, 328G, 24012 objects
Dataset mydata/tars-backup@full_pool_restore [ZPL], ID 180, cr_txg 3818, 212G, 62591 objects
Dataset mydata/tars-backup@before_we_move_to_bcache [ZPL], ID 201, cr_txg 4987070, 218G, 62594 objects
Dataset mydata/tars-backup@Sep2nd2013 [ZPL], ID 62, cr_txg 2846486, 214G, 62592 objects
Dataset mydata/tars-backup [ZPL], ID 165, cr_txg 2952, 226G, 62624 objects
Dataset mydata/Videos@full_pool_restore [ZPL], ID 128, cr_txg 1775, 278G, 2456 objects
Dataset mydata/Videos@Sep2nd2013 [ZPL], ID 64, cr_txg 2846486, 278G, 2455 objects
Dataset mydata/Videos@before_we_move_to_bcache [ZPL], ID 203, cr_txg 4987070, 278G, 2457 objects
Dataset mydata/Videos [ZPL], ID 108, cr_txg 650, 319G, 2524 objects

    ZIL header: claim_txg 0, claim_blk_seq 0, claim_lr_seq 0 replay_seq 0, flags 0x0 

Dataset mydata/raid-vol@before_we_move_to_bcache [ZPL], ID 205, cr_txg 4987070, 79.6G, 1823022 objects
Dataset mydata/raid-vol@full_pool_restore [ZPL], ID 94, cr_txg 454, 61.2G, 1710147 objects
Dataset mydata/raid-vol@Sep2nd2013 [ZPL], ID 66, cr_txg 2846486, 75.6G, 1710206 objects
Dataset mydata/raid-vol [ZPL], ID 85, cr_txg 215, 145G, 1823210 objects

    ZIL header: claim_txg 0, claim_blk_seq 0, claim_lr_seq 0 replay_seq 0, flags 0x0

Dataset mydata/Songs@before_we_move_to_bcache [ZPL], ID 207, cr_txg 4987070, 266G, 80128 objects
Dataset mydata/Songs@Sep2nd2013 [ZPL], ID 68, cr_txg 2846486, 262G, 79205 objects
Dataset mydata/Songs@full_pool_restore [ZPL], ID 151, cr_txg 2837, 262G, 79205 objects
Dataset mydata/Songs [ZPL], ID 133, cr_txg 1776, 274G, 81026 objects

    ZIL header: claim_txg 0, claim_blk_seq 0, claim_lr_seq 0 replay_seq 0, flags 0x0

Dataset mydata/portage@before_we_move_to_bcache [ZPL], ID 209, cr_txg 4987070, 43.3G, 20421 objects
Dataset mydata/portage@full_pool_restore [ZPL], ID 160, cr_txg 2951, 26.8G, 16352 objects
Dataset mydata/portage@Sep2nd2013 [ZPL], ID 70, cr_txg 2846486, 34.9G, 18466 objects
Dataset mydata/portage [ZPL], ID 156, cr_txg 2838, 68.7G, 30380 objects

    ZIL header: claim_txg 0, claim_blk_seq 0, claim_lr_seq 0 replay_seq 0, flags 0x0

Dataset mydata@Sep2nd2013 [ZPL], ID 72, cr_txg 2846486, 199K, 4 objects
Dataset mydata@before_we_move_to_bcache [ZPL], ID 211, cr_txg 4987070, 199K, 4 objects 
Dataset mydata@full_pool_restore [ZPL], ID 79, cr_txg 213, 199K, 4 objects
Dataset mydata [ZPL], ID 21, cr_txg 1, 170K, 4 objects
Verified large_blocks feature refcount is correct (0)
`
The output is similar for exported pool, except for last line I mentioned about the refcount mismatch above.

**Comment by dweeezil** [comment] 2017-01-27 17:54
@devsk It doesn't look like you're running my hacked ```zdb``` or may be giving it some options other than ```-ii```.  See the sample output from it that both myself and @behlendorf showed earlier in this issue.

**Comment by devsk** [comment] 2017-01-28 01:26
Ah darn! I cloned from your repo but didn't realize to checkout your branch. Ding it! Sorry for wasting your time.

One request: can we create an option to show the version of zdb with the git commit of the head shown in the output?

**Comment by devsk** [comment] 2017-01-28 01:36
```
Dirty time logs:

        backup [DTL-required]
            raidz [DTL-required]
              partial [4,16500722) length 16500718
                /dev/disk/by-id/ata-WDC_WD4001FAEX-00MJRA0_WD-XXXXXXXXXXXX-part1 [DTL-expendable]
                /dev/disk/by-id/ata-ST4000VN000-1H4168_YYYYYYYY-part1 [DTL-expendable]
                /dev/disk/by-id/ata-WDC_WD4001FAEX-00MJRA0_WD-ZZZZZZZZZZZZ-part1 [DTL-expendable]
                /dev/disk/by-id/ata-ST4000VN000-1H4168_AAAAAAAA-part1 [DTL-expendable]
                  missing [4,16500722) length 16500718
                  partial [4,16500722) length 16500718
                  outage [4,16500722) length 16500718
space map refcount mismatch: expected 209 != actual 208
```
Thats the output for pool needing resilver on every import.

**Comment by devsk** [comment] 2017-01-31 19:39
Given the output above, what do we do now?

**Comment by dweeezil** [comment] 2017-02-03 18:58
It's as if the vdev needs to be resilvered from the beginning of time (txg 4).  Have you tried importing the pool without the troublesome vdev  (symlink all the other vdevs into a private directory and use ```zpool import -d```)?  If that works, then you ought to be able to do a ```zpool replace``` (maybe will need a ```zpool labelclear -f``` first) which is effectively what a full-vdev resilver would do anyway.

**Comment by devsk** [comment] 2017-02-04 18:09
This device WAS the replacement and it resilvered from scratch. It still resilvers from scratch.

May be I am not following your comment Tim...:-)

**Comment by dweeezil** [comment] 2017-02-04 21:09
@devsk It wasn't clear to me that you had actually done the ```zpool replace```.  When a replace operation can't complete because there is unrepairable damage (permanent errors), the "replacing" vdev normally stays in the pool but in your case, something else appeared to have happened.  I tried a few experiments and couldn't reproduce your scenario so I can't recommend much more at the moment.  The state of your pool is likely worthy of a PR on its own which would, at least, include the pool history (some combination of ```zdb -h```, ```zdb -hh``` and/or ```zpool history``` or ```zpool history -i```) and the exact steps that led to the problem.  What I can glean from this issue so far is:
 - Start with a pool that's been working properly for a long time
 - Issue ```zpool scrub``` which detects permanent errors.
 - At some point, one (file) vdev was taken administratively offline
 - Issue ```zpool replace``` to replace the file vdev
 - Something bad happens... replace fails?  replace succeeds but pool in in weird state?  something else?

**Comment by devsk** [comment] 2017-02-05 03:38
1. - Start with a pool with one disk (it was a sparse 4TB file, which I intended to replace with a disk at some point in future) offline that's been working properly for a long time
2. - Issue zpool scrub which detects permanent errors in one file in an old snapshot.
3. - Issue zpool replace to replace the missing 4TB sparse file with actual disk
4. - zpool replace resilvers the new device completely successfully (sans the permanent errors in 1 file that was present to begin with)
5. - zpool export the pool
6. - zpool import the pool and resilver begins all over again

Is it possible that the original sparse file I had in there was few bytes larger than the disk I am replacing it with? I had made sure to align the 4 (3 real and 1 sparse file) disks' sizes before creating the pool originally.

Let me know what all information you know. I have been away from ZFS debugging for quite a few years. To ZFS's credit, it has never needed any maintenance or debugging from me so far until I hit this issue with permanent errors. That's exactly how a good FS should be.

**Comment by dweeezil** [comment] 2017-02-05 19:10
@devsk Does your system have ECC memory?  If not, there's a few scenarios that could have caused this.  Normally, a replace will not succeed if there are errors preventing it from being completely resilvered (the "replacing-X" vdev stays around).  The only way a replace should succeed in this situation is if the errant file was sufficiently small to not cover the replacing vdev (with any of its data or parity blocks).  Based on its name in your case, my guess is that it's a pretty big file so that wouldn't be the case.

As to the actual topic of this PR, "recovering from permanent errors", there should be some sort of error management and/or recovery section in the wiki.  For example, when an error is reported in a snapshot, it could easily impact other snapshots or clones or other completely different files due to dedup (if enabled).

**Comment by dweeezil** [comment] 2017-02-06 05:58
@devsk I'd like to clarify one thing about ```zpool replace```:  it's very similar to ```zpool attach``` in that it creates a "temporary mirror" named "replacing-X" that has a DTL just like the one you showed above.  In your case, however, something is happening in that the resilver didn't complete properly yet the temporary mirror is gone.  It would be interesting to see the pool configuration both in the MOS and in at least one of the disk labels (```zdb -CC backup```).  Also the history following one of the resilvers after import (```zpool history``` and/or ```zpool history -i```).

**Comment by dweeezil** [comment] 2017-02-06 15:10
@devsk I've looked into this further and the behavior your seeing is sort of normal, except for your "replacing-X" vdev going away.  It's a pretty easy scenario to reproduce, however, since one can simply "detach" the device being replaced and then you're left with the replacement which will always have a "full" DTL (starting at txg 4).  Also, I suspect your RAM is not a problem because you've done multiple resilvers and the errors are detected each time.  This means you really do most likely have an unrepairable error in the data of the specified file.

As to your immediate issue that the resilver happens every time the pool is imported:  if you take the replacement vdev offline (zpool offline) and let the resilver finish, it should not start resilvering on the next import.  Furthermore, its DTL will properly grow to include new changes made to the rest of the pool.

The issue of providing a way to "recover" from permanent errors (unrepairable errors) is somewhat unrelated to your (@devsk) need to replace a file vdev with a disk vdev and the continuous resilvering that happens when unrecoverable errors are encountered.  The continuous resilvering is a byproduct of the way that replace and attach use the DTL mechanism to indicate what should be replicated.  It seems the issue of restarting resilvers could be worked around with a knob that would cause the resilvering process to treat unrecoverable errors as though they succeeded.

**Comment by devsk** [comment] 2017-02-07 02:30
I created symlinks for all drives in /root/mydisks except for the one which was new and was getting resilvered every time. The following is what happened after I did "zpool import -d /root/mydisks backup":

```
# zpool status -v  backup
  pool: backup
 state: DEGRADED
status: One or more devices is currently being resilvered.  The pool will
        continue to function, possibly in a degraded state.
action: Wait for the resilver to complete.
  scan: resilver in progress since Sat Jan 21 11:12:12 2017
        562G scanned out of 9.53T at 400M/s, 6h32m to go
        18.6G resilvered, 5.76% done
config:

        NAME                                            STATE     READ WRITE CKSUM
        backup                                          DEGRADED     0     0     0
          raidz2-0                                      DEGRADED     0     0     0
            ata-WDC_WD4001FAEX-00MJRA0_WD-WCCXXXXXXXXX  ONLINE       0     0     0
            ata-ST4000VN000-1H4168_YYYYYYYY             ONLINE       0     0     0
            ata-WDC_WD4001FAEX-00MJRA0_WD-WCCZZZZZZZZZ  ONLINE       0     0     0
            1470659950255941170                         UNAVAIL      0     0     0  was /dev/disk/by-id/ata-ST4000VN000-1H4168_MMMMMMMM-part1

errors: Permanent errors have been detected in the following files:

        backup/zfs-backup@move_backup_to_4tb_external_sep25_2014:/Installs/clonezilla/live/filesystem.squashfs
```
No idea what is being resilvered? I removed the symlink for /dev/disk/by-id/ata-ST4000VN000-1H4168_MMMMMMMM-part1 also to make sure that it does not follow that.

**Comment by dweeezil** [comment] 2017-02-07 14:25
@devsk You can try the simple patch c434394 in the [dweeezil:dtl](https://github.com/dweeezil/zfs/tree/dtl) to work around this issue.  The single commit should apply cleanly to pretty much any version of ZoL.  When the ```zfs_scan_ignore_errors``` module parameter is set non-zero, it causes DTLs to be removed even if the scan/scrub had errors.  If you set the parameter before importing the pool, the next resilver will appear to succeed even though there were errors and the DTL will be cleared.  Then you can clear the parameter and everything will be normal except that you'll still, of course, have the one file with an error.

**Closed** 2019-02-19 06:22 UTC
